### PR TITLE
[fastlane] Improve Lane Variables documentation by detecting `SharedValues` key assignment in functions

### LINKED ISSUE #14891: Improve Lane Variables documentation by detecting `SharedValues` key assignment in functions
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Recently we have been working on adding a [new `rubocop` rule](https://github.com/fastlane/fastlane/issues/14517) to prevent missing keys on the shared area provided by an action. @janpio noticed that there are `SharedValues` key assignment in functions, but they are **not** added to the `SharedValues` constants declaration. These keys are not detect by the `rubocop` rule so can be easily missed in the documentation process. 

The `rubocop` rule called `MissingKeysOnSharedArea` should be improved and check if there's `Actions.lane_context[SharedValues::KEY_NAME] = ...` assignment in a code but not declared in `SharedValues` module.

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The rubocop rule called `MissingKeysOnSharedArea` should be improved and check if there's `Actions.lane_context[SharedValues::KEY_NAME] = ...` assignment in a code but not declared in `SharedValues` module.

https://github.com/fastlane/fastlane/blob/457c5d647c77f0e078dafa5129da616914e002c5/fastlane/lib/fastlane/actions/sync_code_signing.rb#L1-L38

This PR is an attempt to fix it 💪 

closes https://github.com/fastlane/fastlane/issues/14891

The whole thread: https://github.com/fastlane/fastlane/issues/14255. 

### Description

Modified `MissingKeysOnSharedArea` rule, added missing `SharedValues` keys and `output` values. 

🙇 🙇

### CODE REVIEW

**Comment by janpio** [comment]
> The rubocop rule called `MissingKeysOnSharedArea` should be improved and check if there's `Actions.lane_context[SharedValues::KEY_NAME] = ...` assignment in a code but not declared in `SharedValues` module.

These are mainly "foreign" SharedValues being used here then, that usually "belong" to another action, correct? If so, it would probably be good to add a comment behind the docs definition to make this obvious.

**Comment by mollyIV** [comment]
> These are mainly "foreign" SharedValues being used here then, that usually "belong" to another action, correct?

That is correct 👍 

> it would probably be good to add a comment behind the docs definition to make this obvious.

Any suggestions how the comment could look like @janpio ? 🤔

**Comment by janpio** [comment]
Not really, just something that differentiates them from the "non foreign" ones. Maybe something along the lines of "# originally defined in ...Action"

**Comment by mollyIV** [comment]
@janpio I implemented the suggested changes, could you please 👀 ? 🙏

**Review by joshdholtz — COMMENTED** [review]
@mollyIV Quick question on this! Instead of redefining with `||=`, is it possible to add some sort of rubocop exception? It seems like it might be best to fix this with rubocup insetad of with `||=` 🤔

**Comment by mollyIV** [comment]
Hey @joshdholtz 👋 

We assume that all `SharedValues` values must be defined in `module SharedValues` module and added to `self.output` action's method. I agree that redefining with `||=` is not the best solution, however I believe it is quite good compromise 🙂 

We added additional comment `# originally defined in ...Action` to highlight the existing const definition. 

The cases we are handling here are rather edge cases than a common scenario. 

WDYT @joshdholtz? 🤔

**Review by joshdholtz — APPROVED** [review]
@mollyIV I do agree that its a pretty good compromise 😊 I think the only thing that is still a _bit_ weird with me is that adding the `||=` is needed not because of functionality of code but because a rubocop rule 😇 But... I might just be nitpicky so this is probably good 👌

**Review by janpio — APPROVED** [review]
👍

**Comment by mollyIV** [comment]
Great, thank you guys for the review 🙇

**Comment by janpio** [comment]
First own PR merged? Yay! 🎆 🍰

**Pull request merged**
