### PR TITLE
Add check for ImageMagick before running the badge action

### PR DESCRIPTION
**Pull request by AliSoftware**
This allows to check for the presence of ImageMagick before trying to run the `badge` action, which requires ImageMagick to be installed in order to work properly without erroring.

This intends to implement what has been discussed in https://github.com/fastlane/fastlane/issues/481#issuecomment-147425621 which seems not to have been implemented in the end. This has also been discussed with @KrauseFx directly in the [Fastlane Slack](https://fastlane-tools.slack.com/archives/general/p1476433989000193).

---
### Specs

I'm not sure how to write specs for this, as we'd have to fake various binary installations to check that properly. Besides, it seems that other helpers (like `git_helper.rb` etc) don't have specs either, so I'm not sure you're expecting them for helpers anyway?

### CODE REVIEW

**Comment by mfurtak** [comment]
Hi @AliSoftware - thanks for the contribution! 👍 

Is there a reason that we need to require that homebrew is installed? Shouldn't we only need to verify that ImageMagick is installed?

**Comment by AliSoftware** [comment]
@mfurtak there isn't a real reason to only check if ImageMagick is installed via homebrew rather than in any other method. I just don't really know what feature (lib? Binary? Other?) `badge` specifically needs from ImageMagick and how it uses or invoke it to know exactly what to check instead of it being installed by homebrew.

Besides, the author of the action seem themselves to suggest to install ImageMagick via homebrew (and it's the official way to install it at least for what the action needs) so I figured it should be the best way to check, but if you know a better way I'd love to adapt the PR.


The main purpose of this PR is also, in case ImageMagick isn't actually installed on the mac, to actually give the proper instructions to install it (at least in the form requested/used by the `badge` action), so in case of error, we'll mention `brew` anyway in those installation instructions.

But if you have a better way to suggest for the ImageMagick detection we call still change the detection code while still suggestion to install/use `brew` only in case ImageMagick is needed?

**Comment by mfurtak** [comment]
Cool. While I like the precision from using `brew` to make the check, I think it is better to recognize that they have ImageMagick even if they don't have Homebrew. 👍 

The `convert` binary is at the core of ImageMagick so checking for that [like _frameit_ does](https://github.com/fastlane/fastlane/issues/481#issuecomment-147425621) should be fine.

Suggesting to install via Homebrew is good for the most part, but we should also be aware that some folks run _fastlane_ on non-Mac machines, and telling them about `brew` won't help. :smile:

If you want to try adding some tests, one way to mock the result from shelling-out can be seen [here](https://github.com/fastlane/fastlane/blob/master/fastlane_core/spec/project_spec.rb#L382). That intercepts the call to the backticks, but I suspect you want something closer to:

```ruby
expect(Fastlane::Actions).to receive(:`).and_return('')
```

**Comment by AliSoftware** [comment]
@mfurtak I've refactored the check to now check for the `convert` binary and use the same check and error message as `frameit` does.

Let me know if that better suits you. If so, I might try to add the associated specs for this new code!

**Comment by mfurtak** [comment]
Looks good! 🙌

**Comment by AliSoftware** [comment]
I'm afraid the only time window I had was this weekend and today and won't have time to write specs for that until not next weekend (busy) but the one after…

So probably best to merge this now, and I'll reopen a PR later to write specs when I have more free time for that 👍

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
Great, thanks for the improvement!

**Pull request merged**
