### PR TITLE
[action] gradle: Add support for GRADLE_OUTPUT_JSON_OUTPUT_PATH and GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS

### PR DESCRIPTION
**Pull request by ikesyo**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I want to read metadata from `output.json` which is next to a generated apk.

### Description
Provides `GRADLE_OUTPUT_JSON_OUTPUT_PATH` and `GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS` shared values as well as apk and aab equivalents.

### CODE REVIEW

**Comment by janpio** [comment]
Thanks for this PR @ikesyo!

Just for context, what does gradle put into these `output.json` files?

(Ping @mollyIV to check the SharedValue usage here)

**Comment by ikesyo** [comment]
@janpio The file's content is such as:

```json
[
    {
        "outputType": {
            "type": "APK"
        },
        "apkData": {
            "type": "MAIN",
            "splits": [],
            "versionCode": 123,
            "versionName": "1.0.0",
            "enabled": true,
            "outputFile": "app-develop-debug.apk",
            "fullName": "developDebug",
            "baseName": "develop-debug"
        },
        "path": "app-develop-debug.apk",
        "properties": {}
    }
]
```

> This is only generated with APKs, not with bundles?

Yes, `output.json` is only generated for apks (in `build/outputs/apk/${buildType}/${flavor}`).

**Comment by janpio** [comment]
> The file's content is such as:

Pretty useful, didn't know about this!

**Review by joshdholtz — APPROVED** [review]
I didn't know about these either! Thanks for adding this 😊 We appreciate the contribution ❤️

**Comment by ikesyo** [comment]
Thank you!

**Pull request merged**
