### PR TITLE
Stop suggesting sudo to install gems

### PR DESCRIPTION
**Pull request by qrush**
Fastlane is great, thanks! However I don't feel it should suggest `sudo` to install itself. I'd rather see the guide recommend installation of `rbenv` (or another ruby version manager) and `bundler`, or anything else than relying on `sudo`. :)

### CODE REVIEW

**Comment by ashfurrow** [comment]
Most iOS developers don't need `rbenv` or similar; for this reason, CocoaPods has avoided suggesting users install it. Instead, I think it would be nice if we followed their lead and make it optional `sudo`:

```sh
[sudo] gem install fastlane
```

Does that make sense?

**Comment by qrush** [comment]
I'd rather see it removed entirely but that's a fine compromise too.

**Comment by orta** [comment]
Yeah, that's the decision we ended up with CocoaPods, should't force everyone to use a ruby manager, but we should at least note that it can be optional. 

You can also link to our sued-less instructions: https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation

**Comment by KrauseFx** [comment]
@qrush I agree, it's not best practice, I use `rbenv` myself, but we must not forget who our target group is: We address iOS developers, that are not familiar with Ruby and the Ruby environment. They don't want to learn a technology, but want to get a job done. That is the only reason why I suggest `sudo`.

If we decided to tell the user how to use `rbenv`, I'm sure, we'd scare away a lot of users. 

With the current solution, Ruby developers will use `rbenv` without `sudo` anyway and non-Ruby developers will just use `sudo gem install`.

Does that make sense?

**Comment by KrauseFx** [comment]
I'll close this pull request, thanks for suggesting @qrush.

**Comment by swizzlr** [comment]
I have looked into [Releasy] on several occasions but my lack of esoteric ruby knowledge failed me. However, distribution as a binary that can be brew install'd, or a pkg, is definitely the ideal to strive for.

**Comment by ashfurrow** [comment]
I don't know if I agree that homebrew or a binary is necessarily better. People who don't want to learn minimal ruby to automate things sound like the kind of iOS developers who don't want to automate things anyway.

**Pull request closed without merging**
