### PR TITLE
[fastlane_core] build_settings parsing - fix #7141

### LINKED ISSUE #7141: `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
### Issue Description
Issue occurs when no run target is set for scheme(only using the scheme for running tests).
Workaround was to set a run target(test host in my case).

##### Complete output when running fastlane, including the stack trace and command used

```
scan
fastlane_core-0.57.0/lib/fastlane_core/project.rb:188:in `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/fastlane_core-0.57.0/lib/fastlane_core/project.rb:184:in `ios?'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan/detect_values.rb:28:in `set_additional_default_values'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan.rb:27:in `config='
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan/manager.rb:4:in `work'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/fastlane_core-0.57.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan/commands_generator.rb:60:in `run'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/lib/scan/commands_generator.rb:14:in `start'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/gems/scan-0.14.2/bin/scan:6:in `<top (required)>'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/bin/scan:23:in `load'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/bin/scan:23:in `<main>'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/belmoj/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

I have scan and gym installed as separate gems, without 'fastlane' installed.

### PR DESCRIPTION
**Pull request by hjanuschka**
should fix: https://github.com/fastlane/fastlane/issues/7141

### CODE REVIEW

**Comment by 0xced** [comment]
@hjanuschka Thanks for the quick fix. Have you understood if this issue is directly related to #6925 or if that's just a coincidence? Also, maybe you could add a spec to avoid regressions on this issue?

**Comment by hjanuschka** [comment]
@0xced no i am quite sure it has nothing todo with #6925  - was just my first idea - because of "supported_platforms"

**Comment by hjanuschka** [comment]
@0xced maybe you have an idea.

it tried the following:

```
describe "Build Settings with default empty line" , now: true do
      before do
        options = { project: "./spec/fixtures/projects/Example.xcodeproj" }
        @project = FastlaneCore::Project.new(options, xcodebuild_list_silent: true, xcodebuild_suppress_stderr: true)
        $stdout.puts @project.instance_variables
        @project.build_settings = File.read("./spec/fixtures/projects/broken_build_settings")
      end

      it "SUPPORTED_PLATFORMS should be iphonesimulator iphoneos" do
        expect(@project.build_settings(key: "SUPPORTED_PLATFORMS")).to eq("iphonesimulator iphoneos")
      end
    end
```

whereas in the fixtures i put the broken thing from the issue creator.
any idea on how to overrid `@project.build_settings` with out adding an explicit setter to project.rb?

**Comment by sogko** [comment]
Hi guys, just helping out with getting the 'broken' output for your test specs.

To get it via `xcodebuild` command (xcode v8.1):

```
$ xcodebuild -showBuildSettings -scheme app -project ./ios/app.xcodeproj -toolchain "com.apple.dt.toolchain.XcodeDefault"

Output:

Build settings from command line:
    TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault

Build settings for action build and target flagship:
    ACTION = build
    AD_HOC_CODE_SIGNING_ALLOWED = NO
    ALTERNATE_GROUP = staff
    ALTERNATE_MODE = u+w,go-w,a+rX
...
```

Other notes: Previously on xcode v8.0, `xcodebuild` would give the same above output without the `-toolchain` params passed through command line.

**Comment by 0xced** [comment]
@hjanuschka You should probably mock the call to `FastlaneCore::Project.run_command` with something like this (untested, typed in the browser):

```ruby
it "SUPPORTED_PLATFORMS should be iphonesimulator iphoneos" do
  expect(FastlaneCore::Project).to receive(:run_command).with(command: 'xcodebuild -showBuildSettings -scheme app -project ./ios/app.xcodeproj -toolchain "com.apple.dt.toolchain.XcodeDefault"').and_return(the_problematic_xcodebuild_output)
  expect(@project.build_settings(key: "SUPPORTED_PLATFORMS")).to eq("iphonesimulator iphoneos")
end
```

I'm not sure if you have to specify all the `run_command` parameters using `with()` or if `with(command: ...'` is enough.

**Comment by hjanuschka** [comment]
thank you guys, spec added.
READY for review 👍

**Comment by hjanuschka** [comment]
@0xced done thx.

**Review by asfalcone — APPROVED** [review]

**Comment by asfalcone** [comment]
Nice team work @hjanuschka @0xced @sogko 🎉

**Pull request merged**
