### PR TITLE
[match] add git private key support for match

### PR DESCRIPTION
**Pull request by mbogh**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

We plan to have our `certificates` repository hosted GitHub and need to have access to it from different CI runners e.g. GitLab, Azure via [Deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys).

### Description

I have added a new option to `match` called `git_private_key` and made it a conflicting option with `git_basic_authorization` and `git_bearer_authorization` and the other way around as well.

When `match` is used with this new option then the git command is wrapped in `ssh-agent bash -c 'ssh-add /path/given/id_dsa; GIT_COMMAND'`, this spawns a ssh-agent bash shell and adds private key to the ssh-agent. I learn this from [Martin v. Löwis@StackOverflow](https://stackoverflow.com/a/4565746/342437).

### Testing Steps

1. Have a certificates repository
2. Ensure that `ssh-add -l` does not list any identities related to the repository, to clear it `ssh-add -d IDENTITY` or simply `ssh-add -D`.
3. Now run `match` without the option `git_private_key` and it should fail.
4. Add `git_private_key` option to `match` and see it succeed.
5. Replace the path to a private key with `File.read(private_key_path)` and see it succeed.

### CODE REVIEW

**Comment by mbogh** [comment]
A question, is the Swift interface autogenerated or should I commit changes to these files as well?

**Comment by janpio** [comment]
It is and will be updated with the next release.

**Comment by mbogh** [comment]
I saw a tweet by @joshdholtz mentioning a new [GitHub Actions plugin](https://github.com/joshdholtz/fastlane-plugin-github_action) and it uses a private key entirely as a string. This is especially if the private key originates from a GitHub Secret or GitLab Variable, so I will update the changes to accept either a file path or on string form.

**Review by minuscorp — APPROVED** [review]
Looks good to me, don't know if this conflicts with @joshdholtz  implementation with .env files to work with github actions

**Review by janpio — APPROVED** [review]
👍

**Comment by mbogh** [comment]
@joshdholtz  could you take a look at this? 🤞

**Comment by joshdholtz** [comment]
@mbogh Can do! Last week got away from me but I’m back at it this week 💪

**Comment by mbogh** [comment]
Understandable with everything going on at the moment 😿

**Comment by mbogh** [comment]
Is there anything I can do to move this PR forward?

**Comment by mbogh** [comment]
Just rebased with master, was faling a bit behind 😱

**Comment by mbogh** [comment]
The first step failed to some Homebrew error, could @janpio or @joshdholtz maybe rerun it?

**Comment by janpio** [comment]
Done. I keep having no idea what is going on there :/

**Comment by mbogh** [comment]
@joshdholtz is there anything I can do to help this along?

**Review by joshdholtz — APPROVED** [review]
This is fantastic! Thanks so much for adding this ❤️ I’ll actually be using this in one of my own CIs here soon 😇 Really appreciate the contribution!

**Comment by mbogh** [comment]
@joshdholtz 🥳

**Pull request merged**
