### PR TITLE
[fastlane_core] mask passwords in verbose output

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

as discussed @joshdholtz.

Cheers,
Christoph

### CODE REVIEW

**Comment by dreis2211** [comment]
@googlebot I signed it!

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by dreis2211** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
@dreis2211 Thank you so much for this PR! I had no idea it was doing this so really excited to have this fixed ❤️

**Comment by dreis2211** [comment]
Well, the change fixes a security issue, so I'd rather have this sooner than later.

**Pull request merged**
