### PR TITLE
[Fastlane.Swift][update_fastlane] upgrade Fastlane.swift files

### PR DESCRIPTION
**Pull request by jhandguy**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

It would be nice to be able to upgrade Fastlane.swift files automatically when running the `update_fastlane` action.

### Description

Upgrade Fastlane.swift files automatically upon general Fastlane update.

### CODE REVIEW

**Review by rogerluan — APPROVED** [review]
I like this! 🎉 (code review only, I didn't test it)

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This change makes a lot of sense! But it looks like there are some tests failing 😔 Do you mind fixing these? 😊 

Also... what is the behavior like if its a pure Ruby implementation? Or do we need another check for that somewhere?

**Comment by jhandguy** [comment]
@rogerluan @joshdholtz it should be good now, found the helper to check wether Fastlane is being ran with Swift or not 👍 
Also tested with the Fastlane project itself, by removing the `swift` folder, worked like a charm 👌

**Review by joshdholtz — APPROVED** [review]
Looks perfect! Thanks for making that change ❤️ ❤️ ❤️

**Pull request merged**
