### PR TITLE
Fix spaceauth YAML spaceship cookie loading

### PR DESCRIPTION
**Pull request by hjanuschka**
introduced by:
  *  https://github.com/fastlane/fastlane/pull/7883 (rubocop rules update)

issues: 
  * https://github.com/fastlane/fastlane/issues/8011

### CODE REVIEW

**Comment by mfurtak** [comment]
When testing `spaceauth` from the command line, I was not able to reproduce the problem. I had to start an `irb` session and effectively run the `SpaceauthRunner` code in order to see it.

```
$ irb
>> require 'spaceship'
=> true
>> require 'spaceship/spaceauth_runner'
=> true
>> Spaceship::SpaceauthRunner.new(username: 'your@email.address').run
Logging into to iTunes Connect (michael.furtak@gmail.com)...
Successfully logged in to iTunes Connect
```

I added a commit that adjusts the `safe_load` call to account for all of the settings needed to make the call work for me.

**Comment by mfurtak** [comment]
I should say that the account that I used has two-step auth turned on, but I don't think that's a requirement for testing this?

**Comment by KrauseFx** [comment]
Code-wise this looks fine to me, however I'll have to have a way to reproduce the issue to say for sure that's a valid fix. Seems like @dimmdesign mentioned it didn't work for him?

**Comment by hjanuschka** [comment]
i am pretty sure the fix is ok - here is stripped down sample to reproduce.


```
require 'http-cookie'

stored = "1.cookie"


# try to redo the things going on in client.rb
jar = HTTP::CookieJar.new
cookie = HTTP::Cookie.new("uid", "u12345", domain: 'example.org',
                                            for_domain: true,
                                            path: '/',
                                            max_age: 7*86400)

jar.add(cookie)
jar.save(stored, :yaml, session: true)


cookie_content = File.read(stored)

# load it -> redo things going on in spaceauth_runner
begin
  deserialized = YAML.safe_load(cookie_content)
  puts "Non whitelist works (UNEXPECTED)"
  puts deserialized.inpsect
rescue => ex
  puts "Non Whitelist does not work (EXPECTED)"
end


deserialized = YAML.safe_load(
         cookie_content,
        [HTTP::Cookie, Time], # classes whitelist
        [],                   # symbols whitelist
        true                  # allow YAML aliases
       )


puts deserialized.inspect
puts "with whitelist it works"
```

**Review by mfurtak — APPROVED** [review]

**Comment by dimmdesign** [comment]
@KrauseFx @mfurtak @hjanuschka — 
I tried this again and it seems to be working with this fix. I didn't use the local version of fastlane correctly before, my bad. Confirming that `master` branch (since this PR merged) can create a session.

**Comment by KrauseFx** [comment]
Cool, thanks for confirming @dimmdesign, we're about to ship a new release for this fix 👍

**Pull request merged**
