### PR TITLE
(feat/actions): Add new action 'Upload symbols to new relic'

### PR DESCRIPTION
**Pull request by bitwit**
[Related to #5399]

This PR is near ready for merging but I would like to expand just a little bit on the tests before merging. I'm new to ruby and fastlane so I think it's best to state my intentions and criticisms of what is here so far because a little feedback will probably go a long way.

What I see in the specs folder is mostly what we would probably call 'integration tests' rather than 'unit tests' since most are kicked off with the `Fastlane::FastFile.new.parse("action")` format and the crashlytics tests simply set expectations for what `sh` should execute. There were no direct method tests or dependency injections going on, from what I could see.

The biggest criticism of what I have right now is [this nil check on line 53](https://github.com/fastlane/fastlane/compare/master...bitwit:feat/upload-symbols-new-relic?expand=1#diff-cf71198d0bcc8c2ffb8c61a7b32c7f89R53) which really only exists to satisfy the tests so far.

Is there a way to either A. execute sh commands for real or B. stub sh somehow so I can mock the return value? I think this would help me get the best coverage

On a related note, I also found it hard to execute static method directly in tests if they contained any other calls to other actions, such as sh. Only my first test seems to work that way since it has no outside dependencies. Is there a way to get around that problem?

If I can get some feedback on a good way to approach some of these sorts of tests I think it will be more robust and easier for people to provide failing test examples if there are any issues in the future.

### CODE REVIEW

**Comment by asfalcone** [comment]
hi @bitwit. Thanks for the PR. We're encouraging contributors interested in creatings new actions to create a [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md) instead. This way you can manage your own code style and releases. 🚀

**Comment by bitwit** [comment]
@asfalcone According to the issue I created before making this PR @KrauseFx had said this was worthy of being in the main project and then I took the extra time to make this. Why has this opinion changed?

**Comment by asfalcone** [comment]
@bitwit Sorry for any confusion. I did not see the comment in the related issue. 😞 

I'll work with @KrauseFx to come to a resolution. Thanks for your contribution and patience 🌷

**Comment by bitwit** [comment]
Thank you for clarifying. For the record the questions I've posted here about thorough unit testing are certainly an optional improvement and not required if that is difficult to achieve in the current suite. I'm just trying to provide the highest quality contribution.

**Comment by bitwit** [comment]
Any news on this PR?

**Comment by bitwit** [comment]
Closing this because I don't think you are actually interested in merging it since New Relic is not a Twitter-owned company. Anyone googling deserves to know that they will have to copy paste this on their own.
Someone else is welcome to implement it as a plugin but, as I mentioned before in the original ticket before spending many hours polishing this for general use, I wasn't going to maintain it alone.

**Comment by mikecole20** [comment]
We would also find this very useful as we're having issue getting New Relic to symbolicate crash logs. I think a lot of developers would like to see this feature  included.

**Comment by hjanuschka** [comment]
ok i took the code from @bitwit including its tests. and did a plugin around it -> https://github.com/hjanuschka/fastlane-plugin-upload_symbols_to_new_relic (feel free to join and PR)

i strongy have to say, that i don't believe its "not-twitter-owned-company" issue here - as fastlane at it's core is a liberal place!


so whoever requires the plugin, there you go! and maybe the plugin will mature and evolve to get picked up for core fastlane.

**Comment by bitwit** [comment]
Thank you @hjanuschka for taking the plugin on.

I appreciate and respect your two-cents on Fastlane's core values. 

My only comment would be that I did not appreciate the fact that the Fastlane team asked me on Twitter if I'd be interested in sharing the work I'd done. I then read the guidelines, and posted an issue first stating my intentions which @KrauseFx responded to very quickly agreeing there were some legitimate reasons for putting this in core and feedback on my code. After spending time rewriting and making this PR-worthy I've been left with near silence on the matter. So while I can respect that at it's core Fastlane is a good community of well intentioned people, I can't imagine anyone would argue that this was the best way to handle things.

**Comment by hjanuschka** [comment]
yeah i read the issues - it was not perfect - i also had a few PR's not getting merged, i know it hurts, but at the end of the day life goes on, and sometimes its not a company reason, maybe the guys where busy, and it went below the radar.

anyway  i would be more than happy if you join the plugin repo :)

**Pull request closed without merging**
