### PR TITLE
[sigh] Extract entitlements from the app while resigning

### PR DESCRIPTION
**Pull request by mgrebenets**
Fix for #4397

When no explicit entitlements file specified
extract entitlements from the app bundle and combine with profile entitlements
to create new patche entitlements for resigning

### CODE REVIEW

**Comment by asfalcone** [comment]
@mgrebenets While I see the value in this PR and truly appreciate how much effort you put into the description of the issue, I am afraid that this PR is too complex to merge at this time. There hasn't been any interest from the community to support this feature which makes it hard to justify merging such a large change (especially in bash 😱). 

I am going to close this PR for now. If we hear from other developers that this workflow is important for them, we will definitely reconsider this PR. Thanks again for your time and all of the contributions you've made to `sigh` and `resign` ❤️

**Comment by mgrebenets** [comment]
@asfalcone Thanks for the update 👍 

I'm a bit confused though that this PR and related issue are called a _feature_. 
I'm pretty sure it's a bugfix :)

Is #4397 still considered to be a bug?

Whatever is the outcome of this particular PR, I really hope the issue itself is not going to be closed.
The bug is real and caused us a great deal of trouble at some point.

Will it still be open to keep a reference to the problem and to see if community will have interest in a bugfix in the future?

With regards to this change. I totally acknowledge that it's complex, but such is an original problem itself. 

We will be forced to maintain our own fork and have in-house `sigh` gem build, since we've migrated our resigning pipeline to use the fixed version. That's something we can live with, but ideally I would really love the official version of the gem to have a fix instead, so I'm super keen to tackle this problem in any other way possible.

**Comment by asfalcone** [comment]
@mgrebenets I sincerely appreciate your conversation on this and want to make sure we reach a conclusion that is best for everyone!

We can definitely leave that issue open for now.

Getting some buy in from the community via some 👍 for the need for this change (I'll stop saying *feature*) would help get this PR reopened, as would independent verification of the code change in a few different people's app build environment. 

@KrauseFx suggested possibly adding a flag to enable this behavior and leaving the original behavior as default. I am a proponent of this idea but worry that it is hard to untangle the change to make both code paths still possible. What do you think?

**Comment by asfalcone** [comment]
@mgrebenets Sorry for the delay in responding. I like what you've described here, with 3 clear code paths. It will allow people with all varieties of setups to continue using `resign`. Thank you for taking the time to work on this! ❤️

**Pull request closed without merging**
