### PR TITLE
[supply] Add support for ack_bundle_installation_warning

### LINKED ISSUE #16597: Support for ackBundleInstallationWarning
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`supply` does not support setting of the `ackBundleInstallationWarning` parameter in google apis.
This appears to be triggered for app bundles over 100mb according to the very vague description at https://developers.google.com/android-publisher/api-ref/edits/bundles/upload resulting in a failure to upload AABs with asset bundles (which can be up to 2GB in size together with the apks)

##### Command executed
```
 supply(
      package_name: "_redacted_",
      skip_upload_apk: true,
      aab: "_redacted_",
      track: "internal",
      json_key: "_redacted_",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )  
```
##### Complete output when running fastlane, including the stack trace and command used

```
[!] Google Api Error: apkNotificationMessageKeyBundleInstallationSizeWarning: The installation of the app bundle may  be too large and trigger user warning on some devices, and this needs to be explicitly acknowledged in the request.
```

### PR DESCRIPTION
**Pull request by RedWhiteMiko**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
resolve #16597 

### Description
Add `:ack_bundle_installation_warning` option is `Supply` function.
Tested by uploading APK with Androi app bundle over 100MB with and without `ack_bundle_installation_warning` supplied.

### Testing Steps
Tested by uploading APK with Android app bundle over 100MB with and without `ack_bundle_installation_warning` supplied.
```
supply(
    package_name: "test.package.name",
    skip_upload_apk: true,
    aab: "AAB_FILE",
    track: "TRACK_NAME",
    json_key: "VALIDATION_KEY",
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    ack_bundle_installation_warning: true
)
```

### CODE REVIEW

**Comment by Guy-kun** [comment]
Contrary to Google's documentation, Google Play Console states that this flag is needed for bundles over 150mb (as seen here once a build is uploaded with this flag set)

**Comment by Guy-kun** [comment]
Hi, any chance this can get looked at it? It's a fairly small fix to an important issue preventing the use of aab for large apps in supply.

**Review by janpio — APPROVED** [review]
Looks good and safe to me.

**Comment by RedWhiteMiko** [comment]
I added a commit to fixes the conflict

**Comment by joshdholtz** [comment]
@RedWhiteMiko OMG, I don’t know what happened here. I rebased this and GitHub ended up closing the PR 😔 I am so sorry. This has never happened before 😬 Would you be able to recreate another PR and mention me in it? I will get it merged right away! Below are the changes you had 👇  I’m sooooooo confused what happened here...


`supply/lib/supply/options.rb:350`
```rb
content_type: "application/octet-stream",
ack_bundle_installation_warning: Supply.config[:ack_bundle_installation_warning]
```

`supply/lib/supply/options.rb:213` 
```rb
FastlaneCore::ConfigItem.new(key: :ack_bundle_installation_warning,
                                      env_name: "ACK_BUNDLE_INSTALLATION_WARNING",
                                      description: "Must be set to true if the bundle installation may trigger a warning on user devices (e.g can only be downloaded over wifi). Typically this is required for bundles over 150MB",
                                      optional: true,
                                      type: Boolean,
                                      default_value: false)

```

**Comment by janpio** [comment]
Makes 0 sense to me either @joshdholtz - somehoe that force push of a rebase made it think it got merged via another commit? But usually it shows the commit and links to it then. Straaaange.

**Comment by RedWhiteMiko** [comment]
Hi @joshdholtz , I recreated the PR in https://github.com/fastlane/fastlane/pull/16971
Please check it,

Thank you.

**Comment by joshdholtz** [comment]
Thank you so much!! Sorry again ☹️

**Pull request closed without merging**
