### PR TITLE
Update slather action with new commands

### PR DESCRIPTION
**Pull request by bootstraponline**
Fix https://github.com/fastlane/fastlane/issues/4796

Added
- teamcity
- verbose
- source_files
- decimals

(updated version of #4795)

### CODE REVIEW

**Comment by bootstraponline** [comment]
I don't see why this is failing on circleci? My guess is the failures are unrelated.

**Comment by KrauseFx** [comment]
The tests are failing due to the provided description. Make sure to read the contribution guidelines on how to run the tests and verify everything is okay locally 👍

**Comment by bootstraponline** [comment]
`Your build ran 1944 tests in RSpec with 0 failures` ??

**Comment by bootstraponline** [comment]
Resubmitting again to work around danger failing the pull request (https://github.com/fastlane/fastlane/issues/4810).

**Pull request closed without merging**
