### PR TITLE
Correctly support version: "latest" for download_dsyms

### PR DESCRIPTION
**Pull request by freak4pc**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
While trying to use the `download_dsyms` tool to download the Bitcoded dSYMs from iTC, I wanted to use the "latest" version as described in the documentation. Unfortunately it seems to ignore that option, and unless a specific version is stated, begins downloads dSYMs for *all* available versions in iTC.

I've tested this on my project locally and after the provided fix everything looks good
2870df84-8c2e-4676-a81d-29cf63597f36

### Description
It seems the "latest" codepath doesn't actually set the version retrieved from the call to Spaceship, and also doesn't warn if it can't retrieve that latest version. 

_note:_ While running rubocop It complains about `Perceived complexity for run is too high. [19/18]`. This warning is removed if I get rid of the test to make sure there is an available version. I prefer not to remove that check but can if you prefer so. 

Let me know if there's any extra information needed !

Shai

### CODE REVIEW

**Comment by freak4pc** [comment]
I signed it!

**Comment by freak4pc** [comment]
Passing this here so it's clear why CI is failing. If this is an issue I can get rid of that test, but think its beneficial to have: 

> _note:_ While running rubocop It complains about `Perceived complexity for run is too high. [19/18]`. This warning is removed if I get rid of the test to make sure there is an available version. I prefer not to remove that check but can if you prefer so.

**Comment by KrauseFx** [comment]
Whops, really sorry for the delay here, taking a look now 👍

**Comment by freak4pc** [comment]
Thanks @KrauseFx. Seems this is passing tests now, just this CLA thing, which seems to be a manual merge you would need to do regardless of merge status ?

**Review by KrauseFx — APPROVED** [review]
Beautiful, thanks for your contribution @freak4pc and sorry it took so long

**Comment by freak4pc** [comment]
Thanks @KrauseFx ! And no worries :)

**Pull request merged**
