### PR TITLE
Add Android support to DeployGate action

### PR DESCRIPTION
**Pull request by tomorrowkey**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

---

Upgrade the Deploygate action.
Support Uploading apk file to DeployGate. Please review this :pray:
cc: @tnj 

ref: https://github.com/fastlane/fastlane/pull/38

### CODE REVIEW

**Review by KrauseFx — CHANGES_REQUESTED** [review]
Thanks for the PR, before we can review it, please make sure the code style validation and tests pass

**Comment by asfalcone** [comment]
@tomorrowkey The error on CI is currently

```
bundle exec rspec --format documentation --format j --out rspec_logs.json --format RspecJunitFormatter --out /tmp/circle-junit.BjFXdfm/rspec/fastlane-junit.xml
[Coveralls] Using SimpleCov's default settings.
NameError: undefined method `parse_response' for class `#<Class:Fastlane::Actions::DeploygateAction::UploaderBase>'
  /Users/distiller/fastlane/fastlane/lib/fastlane/actions/deploygate.rb:81:in `private_class_method'
  /Users/distiller/fastlane/fastlane/lib/fastlane/actions/deploygate.rb:81:in `<class:UploaderBase>'
```

**Comment by hjanuschka** [comment]
@asfalcone tests pass now i think its a good addition for the android users, how about merging it?

**Comment by mfurtak** [comment]
I think this is great, but we need to coordinate with the changes in #6991, which I believe will conflict

**Comment by mpirri** [comment]
As per @mfurtak's comment above, there are conflicts that need to be cleaned up before we can merge this. We'd love to get this added for Android users, can you rebase, @tomorrowkey ?

**Comment by tomorrowkey** [comment]
Okay, wait for a minute...

**Comment by tomorrowkey** [comment]
1a4e908 is not rebased changes. 
Thanks to removing shenzhen dependency, changes has been became simply.

**Comment by tomorrowkey** [comment]
Why CI was faild? What shoud I do?

**Comment by KrauseFx** [comment]
It seems like coveralls failed, I'll try to re-trigger CI 👍

**Comment by tomorrowkey** [comment]
Thanks. CI is now green 😎

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
🚀

**Pull request merged**
