### PR TITLE
Fix a filter for the target name.

### PR DESCRIPTION
**Pull request by twhaolee**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

The target name should not be product name of target.
So, use directly the target name.

### CODE REVIEW

**Comment by kokuyoku82** [comment]
I signed it!

**Comment by KrauseFx** [comment]
Could you provide some more context? How did this work until now? What has changed?

**Comment by kokuyoku82** [comment]
My target name is `SHULoginDemo` when creating the project. The target name displays `SHULoginDemo` on Xcode. There are two variables associated with the target name on `project.pbxproj`.


If I modify the target name on Xcode. Only `name` is updated on `project.pbxproj`. But `productName` is old on `project.pbxproj`.


Intuitively, Fastlane should use `name`, not `productName`.

**Review by ohayon — APPROVED** [review]
This is a great change. Thanks @kokuyoku82 ! 🚀

**Pull request merged**
