### PR TITLE
[Fastlane.swift] Add formatter to Fastlane.swift

### PR DESCRIPTION
**Pull request by minuscorp**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I've seen that the Swift codebase doesn't follow any lint rules nor common syntax rules, so the first step is to integrate Swiftformat to ensure that every API or external change gets linted properly into the codebase. This not makes conflict to propose changes or cleanup code as proposed by another members.

### CODE REVIEW

**Comment by minuscorp** [comment]
I just wanted a formatter, not a linter, if that difference makes sense. I just want to make sure that the code is following a set of common format rules and correct them if they fail (as Rubocop do) Swiftlint goes further with enabling and disabling rules and so on, I think it'll be too much for the project itself. What do you think?

**Comment by jhandguy** [comment]
Of course, I was not questioning the choice of the formatter, formatters and linters do serve different purposes and both are valid in a project. I was only raising the possibility of adding SwiftLint on top of SwiftFormat, which could lint things that a formatter does not handle such as function and file length, nesting, etc. 
And since some of the Fastlane Swift files require to be imported in the project (i.e. SnapshotHelper.swift), developers might expect those to be linted via SwiftLint.
But that's just a thought 👍

**Comment by minuscorp** [comment]
The case is, the people will get the project already formatted into their Fastlane.swift, we do not force any rules because we do not embed the formatter into the project, just into the code that is being pushed. It is then user choice to make their own code changes, linting, etc. Any code that breaks is actually out of the organization, more of the user digging into the codebase 😛

**Comment by jhandguy** [comment]
Makes sense @minuscorp, thanks for the clarification 👌

**Comment by minuscorp** [comment]
My plans are to improve the Swift current codebase as much as possible in further PRs, but I have a wait list 😪 it will come 😈

**Comment by minuscorp** [comment]
@joshdholtz 👀  😄

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Never crossed my mind to format this lol. Thanks for adding this in 😍

**Pull request merged**
