### PR TITLE
Allow deliver to work with multiple iTunes Providers

### PR DESCRIPTION
**Pull request by mfurtak**
Takes the work started in https://github.com/fastlane/fastlane/pull/3843, which aims to address #1524 - rebases it on master, and cleans it up a bit.

### CODE REVIEW

**Comment by mfurtak** [comment]
Hi @grantjk - thank for your work on #3843! 👍 I've branched off of it here to get it cleaned up against `master`.

Can you let me know whether it looks good and works for you? Then I think we can get it merged! 🎉

**Comment by mfurtak** [comment]
Reminder for myself: this will also need to be made possible through `pilot`

**Comment by KrauseFx** [comment]
This is ready to be merged once we get a +1 from someone who experienced the problem, right? cc @grantjk

**Comment by grantjk** [comment]
Thanks @mfurtak ! We'll be making a build tomorrow and I'll let you know if it works.

**Comment by grantjk** [comment]
@mfurtak Perhaps you can help me here.

I've been trying to get this to work all day (it's still failing with the same error). But I'm not sure the updates are actually being used.

I've followed this process (the same one that worked for me before when I was working on this):
1. Clone fastlane repo
1. Checkout the `multiple-itunes-providers` branch
1. run `bundle install & rake install`
1. run `fastlane lane --verbose` inside my project
1. Wait 20 minutes (not exaggerated - it takes between 10-20 mins for the fastlane script to start - which is why it's taking me so long to figure out this issue)
1. The script fails with the error.

I've tried adding logging statements using `puts` as well as `UI.verbose` but I don't see any of my logs in the log output.

Regarding the code in this PR - it looks the same as the one that I know worked, so it seems to me that my environment is loading the wrong version of fastlane. Is there something else I can do to get it to use this branch?

**Comment by mfurtak** [comment]
OK, I think I know what might be happening there. This branch is now behind master with regard to what the latest version of `fastlane` is. The branch was created when the fastlane version was **1.89**, and the public release is now **1.91**.

If you have any version of `fastlane` installed that is newer than **1.89**, that is the one which will be called when you run `fastlane` on your command line. You can verify this by running `fastlane -v`.

So, one thing you can do is uninstall any versions of fastlane other than **1.89** (presumably the copy you installed from the branch). You can do this with `gem uninstall fastlane` and pick the version you'd like to get rid of. Repeat as necessary.

Once `gem list fastlane` only returns the 1.89 version, you should be good to go.

As for `fastlane` start-up speed... that is really prohibitive! Generally the more old versions of gems you have installed, the longer the start-up process takes, so the way we generally counsel people to speed that up is to clean up old versions of gems. This can be done by running `gem cleanup`.

If none of that helps, I can rebase this branch on master to get its fastlane version up-to-date. Please let me know!

**Comment by mfurtak** [comment]
Oh, and I guess make sure you're not using the `update_fastlane` action as part of your `Fastfile`!

**Comment by grantjk** [comment]
Thanks for the speed tip - that made a huge difference.

You're right, even after I do a `gem uinstall fastlane` and `gem cleanup` and re-install the branch, I'm still getting a `1.91.0` response to `fastlane -v`. I'll have to look some more at this tomorrow. Might be my rvm setup.

**Comment by grantjk** [comment]
@mfurtak Alright! It worked! I had to rebase from master (locally) to get the install script to install the right version and everything went smoothly.

Thanks for your help on this one!

**Comment by KrauseFx** [comment]
That's great news, I guess it's ready to merge now 👍

**Comment by mfurtak** [comment]
This is released as part of [`deliver` 1.12.0](https://github.com/fastlane/fastlane/releases/tag/deliver/1.12.0) 🚀 

Cheers, @grantjk 🍻

**Comment by grantjk** [comment]
nice! 🎉  🍻

**Comment by rompic** [comment]
@mfurtak how does this work? i.e. how can the option be defined?

**Comment by KrauseFx** [comment]
This is rolled back now due to https://github.com/fastlane/fastlane/issues/4954 with https://github.com/fastlane/fastlane/pull/4961

**Comment by rompic** [comment]
back to the start I guess :|

**Comment by grantjk** [comment]
Oh no! Sorry everyone. That's my fault. Only thing I can think that's happening is that the key we are using from the `Appfile` isn't the right one for some people - it must be already using that key for something else.  

The original intention was to add a new Appfile key and a new environment variable to avoid breaking any existing functionality. However, when I ran the command in #1524 :

`{path_to_iTMSTransporter} -m provider -u {username} -p {password} -account_type itunes_connect -v off`

it gave me the same identifier as our dev portal so I assumed that would be the case for everyone. Maybe that's not the case - or if you don't have multiple accounts, you shouldn't pass one along?

Perhaps the right approach here is to use an entirely separate key/env var? @mfurtak Thoughts?

Can we reopen the original issue?

**Comment by rompic** [comment]
I think that's already happening in https://github.com/fastlane/fastlane/issues/4936#issuecomment-223408660

**Comment by grantjk** [comment]
Ah. Beauty!

**Comment by mfurtak** [comment]
@grantjk No worries at all, thanks again for the contribution! 👍 

Yeah, despite all our efforts testing the work, this area proved to have some rather interesting edge cases that you couldn't really find without using the right Apple ID accounts. 😅

**Pull request merged**
