### PR TITLE
fixes the conditional check if one should load dotenv

### PR DESCRIPTION
**Pull request by iamjason**
See issue for more detail: https://github.com/fastlane/fastlane/issues/819

### CODE REVIEW

**Comment by barbelith** [comment]
+1 This is very important for us to be merged, as we depend totally from env files

**Comment by KrauseFx** [comment]
Thanks everyone, I merged the PR and will also update it to include sub directories.

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/releases/tag/1.38.1 :rocket:

**Comment by kcharwood** [comment]
@KrauseFx Are there any tests that could be added to ensure environment variable loading isnt broken again? That's a key part of our setup!

:beers:

**Comment by KrauseFx** [comment]
@kcharwood Should be possible, yes. All tests are located in the [spec](https://github.com/fastlane/fastlane/tree/master/spec) folder :+1:

**Pull request merged**
