### PR TITLE
[WIP] [frameit] Add iPad Pro 11, 10.5 and 9.7 frames (by resizing 12.9)

### LINKED ISSUE #9651: Unsupported screen size [1668, 2224] - iPad Pro10.5 inch
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
when I ran `fastlane frameit` I get an error for some screenshot I got from snapshot just certain size, size [1668, 2224]. Everything else works just fine

I'm running it individually not with fastlane fastfile.

command used: `fastlane frameit silver`

**Error Example:**
[19:10:54]: Framing screenshot './en-US/iPadPro(10.5-inch)-0-seoul_en-d41d8cd98f00b204e9800998ecf8427e.png'
[19:10:54]: Unsupported screen size [1668, 2224] for path './en-US/iPadPro(10.5-inch)-0-seoul_en-d41d8cd98f00b204e9800998ecf8427e.png'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.2                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-07-01**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
⚠️ WIP - still need to add 9.7 and 11 support

Fixes #9651 + #14079

This is a replacement for #12837 as new frame files are actually needed (closes #12837)

## Problem
iPad Pro 10.5 and 9.7 frames are not supported by _frameit_. The frame images that are used by _frameit_ are pulled from https://facebook.design/devices but this only contains frames for iPad Pro 12.9.

## Solution
This solution adds a new file called `resizes.json` which will take existing frames and resize them. This **shouldn't** be used heavily as it it mess up the aspect ratio but this works as an automated approach for making iPad Pro 10.5 and 9.7 frames without modifying the aspect ratio 😬

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by KrauseFx — APPROVED** [review]
Assuming this works, then yes, code looks good 👍

**Comment by janpio** [comment]
After spending some time with `frameit` I found some code that already does some resizing of the device frames before they are used: https://github.com/fastlane/fastlane/blob/c4def9f78622851b7c51bdfbc55080659b38b8fe/frameit/lib/frameit/editor.rb#L240-L248 This compares the "slot width" (defined as `width` in offsets.json`) with the size of the screenshot, and then resizes the frame to match. As far as I understood it, all our device frames are (or should be) the same size, so no resizing should happen. In practice this is not true all the time as the `width` does not match the device frames being present.

So theoretically that could code be used as the base for a new function ti resize the device frames on demand somehow, instead of "inventing" new devices that don't really exist. Of course we would need another new mapping for that - so maybe it isn't worth the effort.

Advantage of doing this as suggested here in this PR of course would mean that if someone gets a frame from another source, she can just replace the image and update `offsets.json` with the new data.

So I think I actually like your approach better.

**Comment by joshdholtz** [comment]
@janpio I will revive / finish off this PR so we can get frameit support for the rest of the devices 💪 Thanks for doing that analysis on the different approaches we can take. I didn’t actually know there was a dynamic resizing function that we could have used 😇

**Comment by janpio** [comment]
Same here - as it currently doesn't do anything it really took me a long time to understand what its actual goal is when debugging it for #14088 to be honest.

**Comment by JulesMoorhouse** [comment]
@joshdholtz / @janpio looks like one of you needs to provide consent?

**Pull request closed without merging**
