### PR TITLE
[action] sonar: new optional param for branch name

### PR DESCRIPTION
**Pull request by husyn**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fastlane action sonar doesn't support branch analysiswhich is important for SonarQube usage
https://github.com/fastlane/fastlane/issues/14552

### Description
Add branch_name parameter in sonar action to be passed to sonar scanner.
Used my local fastlane code to test the changes and it works. Executed the Tests by running `bundle exec fastlane test` and everything works fine.

### CODE REVIEW

**Comment by husyn** [comment]
I signed it!

**Comment by husyn** [comment]
I signed it!

**Comment by husyn** [comment]
Updated the name/email. I signed it!

**Review by janpio — APPROVED** [review]
Code looks good and simple 🚀

**Comment by janpio** [comment]
To take care of the CLA:

You could do a "reset" of your repo to before you committed and keep your local changes, then commit them again with your correct git configuration, then force push.

Or, if this sounds scary, just create another PR with a new branch where you commit only with your correct configuration, then the CLA should be recognized instantly.

**Pull request closed without merging**
