### PR TITLE
Add supported platforms for platform parameter description.

### PR DESCRIPTION
**Pull request by fassko**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Improving documentation otherwise it's not understandable if this supports tvOS.

### Description
I added supported platforms to description.

### CODE REVIEW

**Comment by fassko** [comment]
I signed it!

**Comment by ohayon** [comment]
Hey @fassko - Is it possible that we support downloading dSYM files for macOS and watchOS also?

**Comment by fassko** [comment]
I signed it!

**Comment by fassko** [comment]
@ohayon I can dig deeper and understand how this all works. Right now I just improved the documentation. ;)

**Comment by fassko** [comment]
@ohayon Apple Watch app is extension not separate app. When you download dsyms for iOS app you are doing it for extensions as well.

**Comment by fassko** [comment]
Maybe someone can explain about macOS and dSYMS. I have two simple apps for macOS in iTunes Connect, but there is no downloading for dSYMS available.

**Comment by fassko** [comment]
@milch Can you please review this PR? Thanks!

**Review by milch — APPROVED** [review]
Looks good! Congrats on your first contribution 😊

**Pull request merged**
