### PR TITLE
[pilot][deliver] fix private method clone' called for #<Hash> on uploading app 

### PR DESCRIPTION
**Pull request by freddi-kit**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes: https://github.com/fastlane/fastlane/pull/20631#issuecomment-1247998588 by https://github.com/fastlane/fastlane/pull/20631#issuecomment-1248022225

### Description
Use dup instead of clone when copying api_key

### Testing Steps
run 

I tested by pure project with below fastfile

```rb
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xcode_select("/Applications/Xcode_14.app")
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
      scheme: "EmptyTestApp",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "com.freddi.testapp.EmptyTestApp" => "release",
        },
      },
      silent: true,
      clean: true
    )
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
    # pilot(
    #  username: "test@test.com"
    # )
  end
end
```

### CODE REVIEW

**Review by crazymanish — APPROVED** [review]
Looks good to me! 🚀

**Comment by azilbershtein** [comment]
Thanks for this PR, when are you planning to merge it?

**Comment by freddi-kit** [comment]
could someone take a look it?

**Review by AliSoftware — APPROVED** [review]

**Review by AliSoftware — APPROVED** [review]
:shipit:

**Comment by azilbershtein** [comment]
@freddi-kit Merge? :)

**Comment by freddi-kit** [comment]
I'm not fastlane member so I wanna ask @crazymanish or @joshdholtz to merge it

**Comment by crazymanish** [comment]
i can merge this PR, but can't release it. only Josh has permission to make a Fastlane release! 
Till we have a new Fastlane release, users can point Fastlane to this PR git-branch...please find the steps. 

### Point Fastlane to this PR git-branch
- Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "fix-altool-key-clone"
```

 i will ping Josh on slack to make a new release soon.

**Comment by freddi-kit** [comment]
@joshdholtz it is also necessary for some engineer to solve pilot issue, please take a look when you have time 🙇

**Comment by joshdholtz** [comment]
Thank you for ping! Will take a look 😊 

And sorry for slow response as of lately! Me and wife are expecting a new baby in a few days so definitely a little bit off my game 😛

Feel free to ping me (multiple times if needed) if anything urgent comes up! I don't mind because I want to solve/release the urgent things 💪

**Comment by freddi-kit** [comment]
> And sorry for slow response as of lately! Me and wife are expecting a new baby in a few days so definitely a little bit off my game 😛

Oh, congrats! We have a workaround to use my forked branch so it would not be so urgent. Please take your time.

**Comment by freddi-kit** [comment]
"Family First" 💪  💪  💪  💪

**Comment by azilbershtein** [comment]
@joshdholtz Hi, any chance you can take a look?

**Comment by azilbershtein** [comment]
Any updates about that?

**Review by joshdholtz — APPROVED** [review]
Ooops, sorry! It took me a long longer to get back into things and catch up from my family leave than I thought 🤦‍♂️ 

This looks great and will ship this soon!

**Pull request merged**
