### PR TITLE
[WIP] Enable danger

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Doesn't work currently... still work in progress

**Comment by KrauseFx** [comment]
Closing, as Circle isn't stable enough for _danger_ yet 😢

**Comment by hjanuschka** [comment]
@KrauseFx  can't we use travis for danger only? or some other CI?

**Comment by KrauseFx** [comment]
It's a problem with Circle CI, it seems like the combination of danger and Circle isn't stable enough yet

**Comment by KrauseFx** [comment]
It might be a good idea to run it on a separate CI, e.g. travis

**Comment by hjanuschka** [comment]
this way it even could run in parallel - only thing is about test results, or do you think we should run the tests on travis too? 
or we could ignore test results, from danger point of view, as github already shows the red X on failed tests.

**Comment by KrauseFx** [comment]
No, we don't want to introduce Travis, as the mac containers are too slow for us

**Pull request closed without merging**
