### PR TITLE
Fix `fastlane env` command for bundled fastlane

### PR DESCRIPTION
**Pull request by KrauseFx**
Also rename `x` to `current_gem` cc @hjanuschka

Before that, it didn't actually show all fastlane gems, since they don't get required at that point yet
screenshot 2016-11-10 12 50 48

### CODE REVIEW

**Comment by hjanuschka** [comment]
lgtm, i didn't realize the troubles with the gems not required at this point 😭

**Comment by milch** [comment]
Looks good, but it would be nice if we could also say "This is the bundled version of fastlane" or something somewhere.

**Comment by KrauseFx** [comment]
@milch: Yeah, but this would be a separate PR as it would be another row being added. For now, this fixes the issue with listing the gems. 

Currently we can already see if it's bundled as part of the Ruby path 👍

**Comment by milch** [comment]
Alright, then

**Review by milch — APPROVED** [review]
🍕

**Pull request merged**
