### PR TITLE
Add a message about the badge plugin

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @ohayon</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by taquitos — APPROVED** [review]
Best messages ever. 🐐 🥅

**Review by KrauseFx — APPROVED** [review]
Looks great 👍 

Did we talk with the author of the plugin about this? Is the author aware of it?

**Comment by ohayon** [comment]
I don't believe we have talked to them, but they are also the ones that are managing the plugin as well 🔌

**Comment by KrauseFx** [comment]
@ohayon My feeling is that it would make sense to ping them to let them know still :)

**Pull request merged**
