### PR TITLE
[fastlane_core] added deliver/pilot support for Xcode 11 - new search path for itms_path

### LINKED ISSUE #14955: [pilot] Support Xcode 11 (beta)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Fastlane seems to lack support for uploading build to testflight with Xcode 11 beta, which is required for building apps that are targeting iOS 13.

Error is "Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/" which makes sense given that Xcode 11 doesn't include the Transporter application anymore.

See also: https://stackoverflow.com/questions/56504929/bitrise-could-not-find-transporter-at-applications-xcode-beta-app-contents-devel and https://developer.apple.com/videos/play/wwdc2019/301/

##### Command executed
fastlane upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[09:02:37]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:02:37]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[09:02:37]: ----------------------------------------
[09:02:37]: --- Step: Verifying fastlane version ---
[09:02:37]: ----------------------------------------
[09:02:37]: Your fastlane version 2.125.2 matches the minimum requirement of 2.121.1  ✅
[09:02:37]: ------------------------------
[09:02:37]: --- Step: default_platform ---
[09:02:37]: ------------------------------
[09:02:37]: Driving the lane 'ios publish' 🚀
[09:02:37]: ----------------------------------
[09:02:37]: --- Step: upload_to_testflight ---
[09:02:37]: ----------------------------------
[09:02:38]: Login to App Store Connect (****)
Available session is not valid any more. Continuing with normal login.
[09:02:40]: Login successful
[09:02:41]: Ready to upload new build to TestFlight (App: xxxxxxxxx)...
[09:02:41]: Going to upload updated app to App Store Connect
[09:02:41]: This might take a few minutes. Please don't interrupt the script.
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios publish |
+------------------+-------------+
[09:02:41]: Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | upload_to_testflight       | 3           |
+------+----------------------------+-------------+

[09:02:41]: fastlane finished with errors

[!] Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation. </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #14955

## Motivation
Couldn't find `itms_path` when using Xcode 11 Beta 2 💥 

## Description
Adds new `itms_path` to search 👀

### CODE REVIEW

**Comment by snatchev** [comment]
According to https://help.apple.com/itc/transporteruserguide/en.lproj/static.html

`itms` can also live in  `/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/MacOS/itms/bin` or `/usr/local/itms`

Do we have a preference about which ones to choose? Or what if people download the standalone transporter executable. Will this work with that?

**Comment by joshdholtz** [comment]
@snatchev `Applications/Xcode.app/Contents/Applications/Application Loader.app` doesn't exist in Xcode 11 Beta 2 (see https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_2_release_notes). That doc you linked was last updated in 12/5/2018 so looks to be out of date 🙃

So we need to look for it in a different place for Xcode 11 Beta 2 with the hope this still works for GM release 😬

**Comment by janpio** [comment]
> Do we have a preference about which ones to choose? Or what if people download the standalone transporter executable. Will this work with that?

Transporter is quite aggressive with self updating, so I would guess it is fine to use whatever install we can find.

**Review by janpio — APPROVED** [review]

**Comment by joshdholtz** [comment]
But I’ll have to check for the `/use/local/itms` on my machine. I wasn’t aware of that option 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshdholtz** [comment]
Confirmed that`/usr/local/itms` doesn't exist on my machine 🙈

**Comment by janpio** [comment]
I _think_ that was the install location of a manual install via https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/Transporter__OSX/bin/

**Comment by joshdholtz** [comment]
Ahhh... I will download that and add it to this PR 😊

**Comment by joshdholtz** [comment]
Didn't expect this? 🤔

Screen Shot 2019-06-27 at 3 12 02 PM

**Comment by janpio** [comment]
You can change that setting somewhere. Never remember where and always have to google though :p

**Comment by joshdholtz** [comment]
Now updated to first check for `usr/local/itms`. My thought was if a user manually has that installed they want to use it? 🙃

**Comment by janpio** [comment]
Makes sense.

Do we have proper logging or output by default to be able to debug this when people report issues? Eventual error messages should be pretty clear in theory, but maybe by default output the version number or something?

**Comment by joshdholtz** [comment]
@janpio The path shows in transporter output if `--verbose` is used but nothing official on _fastlane_'s part on what path is being used

**Comment by janpio** [comment]
Yeah, I strikethrough-ed that part of the comment as I realized that would be premature here - if stuff breaks, users will tell us and we will just figure it out. No need to spend more time on this now.

**Review by snatchev — APPROVED** [review]
LGTM, thanks for updating with all of your research.

**Pull request merged**
