### PR TITLE
Add option to update provision profile with a single UDID (Issue #6901)

### PR DESCRIPTION
**Pull request by craigho**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [X] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [X] Run `bundle exec rubocop -a` to ensure the code style is valid
- [X] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

---
See: https://github.com/fastlane/fastlane/issues/6901

The purpose of this enhancement is to allow the renewal of an adhoc/development provision profile while adding only a single new UDID, rather than pulling in all available UDIDs. This is useful if you have a single developer.apple.com account but there are multiple projects and users. Some devices will be used to develop one app, while a different set of devices might be used to develop a different app. Adding all devices to all provisioning profiles might allow app leakage across testing teams.

### CODE REVIEW

**Comment by KrauseFx** [comment]
I'm not 100% sold on this feature, this seems to be a very specific use-case. Couldn't you solve this by providing the name instead?

**Comment by craigho** [comment]
@krausefx thanks for taking the time to review. 

I apologize, but I don't quite follow your question. I'm not aware of any functionality in sigh that allows you to add a single device to a profile without pulling in all available devices - either by name or UDID. If there is such an option, I feel foolish having overlooked it!

**Comment by craigho** [comment]
@krausefx I'd like to merge this in if possible.... lets continue the discussion on this one.

**Comment by craigho** [comment]
Happy to resubmit if necessary?

**Comment by milch** [comment]
Hi @craigho, sorry for the huge delay with your PR/issue. 

I'm not 100% sold on the idea - is there any reason/benefit of doing this as part of running `sigh`, instead of adding the device before and then running `sigh` with `force:true`? I'd rather not repurpose the tool for something it's not intended for and that's not beneficial to most users.

I think it'd be better if we added a flag for renewing, but keeping the same device list. That way one could add as many devices as one wants, e.g. 

```ruby
lane :add_new_devices do
    register_devices(devices_file: "devices.txt")

    profile = Sigh.Runner.new.fetch_profiles.first
    #... extract new devices from "devices.txt" into device_list
    profile.devices << device_list    
    profile.update!

    sigh(
        keep_device_list: true, 
        force: true,
        # ... 
    ) 
end
```

**Comment by craigho** [comment]
Your suggestion seems workable. I do agree that my solution is fairly specific to my use-case. I guess the flip side of the argument is that if you did want to add only a single device, my workflow is a single stage and easier from a user standpoint.

If we want to go in this direction, I can test out the workflow and submit a new PR. But I won't be able to do so until March.

**Comment by milch** [comment]
> Your suggestion seems workable. I do agree that my solution is fairly specific to my use-case.

Alright, thanks for understanding! We generally only want to support features with fastlane that are useful to a majority of users. I can see the value in keeping the device list of a profile constant, both for small developers and large, so that is what I'd rather support - especially if it also solves this issue. 

>  I guess the flip side of the argument is that if you did want to add only a single device, my workflow is a single stage and easier from a user standpoint.

There is always the option to make a more easy-to-use action out of this, and submit it as a [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins)! Plugins are first class citizens in fastlane, the only difference is that they are user maintained. If you decide to create a plugin and it turns out a lot of users are using it, we can then always revisit adding those features back into the main fastlane repo. 

> If we want to go in this direction, I can test out the workflow and submit a new PR. But I won't be able to do so until March.

No worries, no one is in a rush here. I'm going to close this PR for now, let me know if I should reopen it!

**Pull request closed without merging**
