### PR TITLE
Fix match to use fastlane_core keychain_importer

### LINKED ISSUE #6866: Keychain prompts for permission to use private key regardless of access control settings on sierra
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlan gym hangs on `xcodebuild archive` commands.

Keychain prompts for permission to use private key regardless of access control settings on sierra this cases a hang on build servers when tools calling `codesign` tool, like signing an archive, or during copying a framework or embedding pods.

Related [openradar issue](https://openradar.appspot.com/28524119).

The mentioned solution seems to be working, our implementation: https://github.com/bitrise-io/steps-certificate-and-profile-installer/blob/master/main.go#L548

# Log 1:

```
+----------------------+-------------------------+
|             [32mSummary for gym 1.11.3[0m             |
+----------------------+-------------------------+
| scheme               | [REDACTED]                 |
| configuration        | Alpha                   |
| use_legacy_build_api | true                    |
| export_method        | development             |
| workspace            | ./[REDACTED].xcworkspace   |
| destination          | generic/platform=iOS    |
| output_name          | [REDACTED]                 |
| clean                | false                   |
| output_directory     | .                       |
| silent               | false                   |
| buildlog_path        | ~/Library/Logs/gym      |
| xcode_path           | /Applications/Xcode.app |
+----------------------+-------------------------+

[07:58:19]: [4m[36m$ set -o pipefail && xcodebuild -workspace ./[REDACTED].xcworkspace -scheme [REDACTED] -configuration 'Alpha' -destination 'generic/platform=iOS' -archivePath /Users/vagrant/Library/Developer/Xcode/Archives/2016-11-03/[REDACTED]\ 2016-11-03\ 07.58.19.xcarchive archive | tee /Users/vagrant/Library/Logs/gym/[REDACTED]-[REDACTED].log | xcpretty[0m[0m
[07:58:24]: [35m[33m▸[0m [39;1mBuilding[0m [REDACTED]/[REDACTED]-notification [(Release)][0m
[07:58:24]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
[07:58:24]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
[07:58:24]: [35m[33m▸[0m [39;1mCompiling[0m NotificationService.swift[0m
[07:58:29]: [35m[33m▸[0m [39;1mCompiling[0m NotificationService.swift[0m
[07:58:37]: [35m[33m▸[0m [39;1mLinking[0m [REDACTED]-notification[0m
[07:58:38]: [35m[33m▸[0m [39;1mLinking[0m [REDACTED]-notification[0m
[07:58:43]: [35m[33m▸[0m [39;1mGenerating '[REDACTED]-notification.appex.dSYM'[0m[0m
[07:58:45]: [35m[33m▸[0m [39;1mTouching[0m [REDACTED]-notification.appex[0m
[07:58:45]: [35m[33m▸[0m [39;1mSigning[0m /Users/vagrant/Library/Developer/Xcode/DerivedData/[REDACTED]-euwzwswygybbklfshqvjvmmgzspa/Build/Intermediates/ArchiveIntermediates/[REDACTED]/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/[REDACTED]-notification.appex[0m

hang on this line...
```

# Log 2:

```
+----------------------+-------------------------+ 
| Summary for gym 1.11.3 | 
+----------------------+-------------------------+ 
| scheme | Palace | 
| configuration | Adhoc | 
| use_legacy_build_api | true | 
| export_method | ad-hoc | 
| project | ./[REDACTED].xcodeproj | 
| destination | generic/platform=iOS | 
| output_name | [REDACTED] | 
| clean | false | 
| output_directory | . | 
| silent | false | 
| buildlog_path | ~/Library/Logs/gym | 
| xcode_path | /Applications/Xcode.app | 
+----------------------+-------------------------+

[12:13:35]: $ set -o pipefail && xcodebuild -scheme [REDACTED] -project ./[REDACTED].xcodeproj -configuration 'Adhoc' -destination 'generic/platform=iOS' -archivePath /Users/vagrant/Library/Developer/Xcode/Archives/2016-11-03/[REDACTED]\ 2016-11-03\ 12.13.35.xcarchive archive | tee /Users/vagrant/Library/Logs/gym/[REDACTED]-[REDACTED].log | xcpretty 
[12:13:37]: ▸ Building [REDACTED]/[REDACTED] [Adhoc] 
[12:13:37]: ▸ Check Dependencies 
[12:14:36]: ▸ Compiling [REDACTED]_vers.c 
[12:14:37]: ▸ Compiling [REDACTED]_vers.c 
[12:14:37]: ▸ Linking [REDACTED] 
[12:14:39]: ▸ Linking [REDACTED] 
[12:14:39]: ▸ Compiling LaunchScreen.storyboard 
[12:14:45]: ▸ Processing Info.plist 
[12:14:45]: ▸ Generating '[REDACTED].app.dSYM' 
[12:14:45]: ▸ Running script 'Copy Frameworks'

hang on this line...
```

# Log 3:

```
Compiling alot...

[20:42:44]: ▸ Compiling Main.storyboard
[20:42:50]: ▸ Processing Info.plist
[20:42:50]: ▸ Generating '[REDACTED].app.dSYM'
[20:42:50]: ▸ Running script 'Run Script'
[20:42:50]: ▸ Running script '[CP] Embed Pods Frameworks'

hang on this line...
```

### PR DESCRIPTION
**Pull request by milch**
This will fix #6866.

Depends on #6932 being released.

PR 3 of 3 🎉

### CODE REVIEW

**Comment by KrauseFx** [comment]
Does that mean people have to provide that password by default now when using _gym_?

**Comment by KrauseFx** [comment]
If so, is that also the case for Xcode itself?

**Comment by milch** [comment]
No, you don't have to provide the password... On Sierra, when you don't provide the keychain password when running match, a popup will show up the first time when you are using gym to build the app asking if codesign is allowed to use the private key. This is not desirable for CI, so when you provide the password the popup will not appear.

**Comment by KrauseFx** [comment]
Alright, that makes sense, thanks for clarifying 👍

**Review by KrauseFx — APPROVED** [review]

**Pull request merged**
