### PR TITLE
[snapshot] add the iPhone 14 devices for the HTML report page

### LINKED ISSUE #20950: iPhone 14 models missing in report
Please add the latest devices here -> 
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/reports_generator.rb#L87

### PR DESCRIPTION
**Pull request by crazymanish**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
- Resolves #20950

### Description
- add the iPhone 14 devices for the HTML report page

### Screenshot

Screenshot 2022-12-26 at 11 16 54

### CODE REVIEW

**Comment by sandeep-yudiz** [comment]
@cbowns , @crazymanish , @kommen , @lsegal 

Can you please review this PR and merge it because we are facing the issue on HTML report generating due to all iPhone 14 devices name is not found.

Thanks

**Comment by thartzheim** [comment]
Wanted to bump this PR as this support would be super helpful for the designers on my team as they can't easily look over all of our screenshots for iPhone 14 due to this limitation.

**Comment by micke-b** [comment]
I need this as well. Please review and merge. 👍

**Comment by getaaron** [comment]
This was addressed in https://github.com/fastlane/fastlane/pull/21554 so I'm closing this PR. Thank you for sending it in anyway and apologies for not getting to this sooner.

**Pull request closed without merging**
