### PR TITLE
Revert to old colored gem

### PR DESCRIPTION
**Pull request by KrauseFx**
Introduced many regressions

Fixes https://github.com/fastlane/fastlane/issues/8111 and https://github.com/fastlane/fastlane/issues/8112 and https://github.com/Microsoft/app-store-vsts-extension/issues/57 and more

### CODE REVIEW

**Comment by mike011** [comment]
"Error pushing Slack message, maybe the integration has no permission to post on this channel? Try removing the channel parameter in your Fastfile."

**Comment by KrauseFx** [comment]
@mike011 What do you mean?

**Comment by mike011** [comment]
It's the error message from the circle ci build. Sorry for the lack of context.

**Review by endocrimes — APPROVED** [review]
LGTM with passing ci

**Pull request merged**
