### PR TITLE
Add the ability to only show merge commits

### PR DESCRIPTION
**Pull request by tabuchid**
If you use a pull request workflow its useful to create a changelog with only merge commits.

### CODE REVIEW

**Comment by mfurtak** [comment]
Thank you for the contribution! :+1: 

What do you think the behavior should be if someone specifies `include_merges: false` and `only_merges: true`?

**Comment by jcampbell05** [comment]
@mfurtak  Could we introduce a `merge_behaviour` property ? 

- `merge_behaviour: :merges_only`
- `merge_behaviour: :ignore_merges`
- `merge_behaviour: :include_merges`

If people set the old property to true we could make it set the merge behavior to `include_merges` until we remove it.

**Comment by mfurtak** [comment]
I think that's a great idea @jcampbell05 :+1: I'd love to see a new option with three possible values:

- `merge_commit_filtering: :include_merges` [default]
- `merge_commit_filtering: :exclude_merges`
- `merge_commit_filtering: :only_include_merges`

Setting `include_merges: false` should mean `merge_commit_filtering: :exclude_merges`

Would that work for you, @tabuchid?

**Comment by tabuchid** [comment]
Works for me. I think thats clearer then multiple options.
FYI I just tried this with git `git log --merges --no-merges` and it is a noop.

**Comment by mfurtak** [comment]
Cool. Would you like to adapt this in that way, @tabuchid?

**Comment by tabuchid** [comment]
@mfurtak How does that look? Forgive my ruby, I haven't worked much in it.

**Comment by mfurtak** [comment]
@tabuchid I think that's pretty good! :+1: I added onto it a bit with #1152. Please let me know if that still works for your needs and we can get it in!

**Pull request closed without merging**
