### PR TITLE
Fastlane.swift : Fixes issue with XCOV params 

### PR DESCRIPTION
**Pull request by xlsmearlx**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

FastlaneSwift fails using XCOV:

**Issue 1: Hardcoded Xcode path**
Fails with error
```
[16:56:16]: ▸ Loading... 
[16:56:16]: ▸ IDEFoundation could not be loaded IDEFoundation could not be loaded 
[16:56:16]: Exit status: 66
```

**Issue 2: Minimum coverage should be Double/Float as same as the ruby function**
Fails with error
`[16:29:25]: 'minimum_coverage_percentage' value must be a Float! Found Integer instead.`

### Description

Fix: Change `minimumCoveragePercentage: Int` to `minimumCoveragePercentage: Double`

Fix: Change  Xcode path from:
`"/Applications/Xcode-11.4.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation"` 

to 

`ideFoundationPath: String? = nil`

### FIXES ISSUES

- https://github.com/fastlane/fastlane/issues/16495
- https://github.com/fastlane/fastlane/issues/16494

### CODE REVIEW

**Comment by xlsmearlx** [comment]
@googlebot I signed it!

**Review by janpio — CHANGES_REQUESTED** [review]
Unfortunately the `Fastlane.swift` file is auto generated and should not be edited manually: https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane/swift/Fastfile.swift#L1-L4

**Comment by xlsmearlx** [comment]
@janpio is `Fastlane.swift` also autogenerated? the file does not have that message like `Fastfile.swift`. If so, where is the correct place to make this modification to the autogenerated file?

**Comment by janpio** [comment]
You are right, we are missing a helpful message in the file - but it _is_ generated on release/publish (see the history of the file). I think the things you touched come from https://github.com/fastlane/fastlane/blob/1aa8cdd2df87378a487b421607a1532a84f7974a/fastlane/lib/fastlane/actions/xcov.rb#L26-L45 - although some more investigation might be necessary.

**Comment by janpio** [comment]
Let's continue this discussion in the issue 👍

**Pull request closed without merging**
