### PR TITLE
Version bump to 2.64.0

### PR DESCRIPTION
**Pull request by KrauseFx**
Auto-generated by fastlane 🤖

**Changes since release '2.63.0':**

* Fixed instruction for update plugin (#10809) via Rishabh Tayal
* Support App Preview for iPhone X (#10799) via Fumiya Nakamura
* Fix mismatched <th> tags in docs_generator (#10797) via David Vanoni
* Add auto_release_date option to deliver (#10768) via Joshua Liebowitz
* Support for iPhone X in frameit (#10533) via Alfredo Delli Bovi
* Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta
* Remove redundant let declaration for a discardable result (#10762) via Sampsa Kuronen
* Allow in app purchases check to be disabled via deliver (#10758) via Iulian Onofrei
* Update AppfileTemplate (#10759) via Aaron Brager
* Added is_string: false to active_days_limit config entry (#10763) via vspac
* Commit version bump enhancements (#9483) via Jimmy Dee
* issue template fix (#10673) via Rishabh Tayal
* [Deliver] Fix uses idfa limits tracking (#10715) via Jorge
* Allow snapshots on older iOS versions when no specified/latest found (see #10211) (#10755) via Ely Alvarado
* In two-stage Hockey action, do not set the status to 2 (downloadable) until after the app is uploaded (#10706) via Steve Rubin
* Fix colon styling in SnapshotHelper (#10736) via Sampsa Kuronen

### CODE REVIEW

**Review by mpirri — APPROVED** [review]

**Review by jetersen — APPROVED** [review]
🚀

**Comment by revolter** [comment]
Any reason for #10758 not being added to the Releases page?

**Comment by revolter** [comment]
@KrauseFx, `Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta` appears twice [here](https://github.com/fastlane/fastlane/releases/tag/2.64.0), so I guess that one of them replaced #10758.

**Comment by revolter** [comment]
@mpirri, @casz, Any help with my question? As from what I saw previously, Krause never replies to mentions on closed Issues or PRs :(

**Comment by revolter** [comment]
Great, it's even missing from terminal 😢 :

```
...

[13:48:53]: fastlane.tools finished successfully 🎉

#######################################################################
# fastlane 2.64.0 is available. You are on 2.63.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.64.0 iPhone X support and more
* Support App Preview for iPhone X (#10799) via Fumiya Nakamura
* Add auto_release_date option to deliver (#10768) via Joshua Liebowitz
* Support for iPhone X in frameit (#10533) via Alfredo Delli Bovi
* Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta
* Commit version bump enhancements (#9483) via Jimmy Dee
* [Deliver] Fix uses idfa limits tracking (#10715) via Jorge
* Allow snapshots on older iOS versions when no specified/latest found (see #10211) (#10755) via Ely Alvarado
* In two-stage Hockey action, do not set the status to 2 (downloadable) until after the app is uploaded (#10706) via Steve Rubin
* Fix colon styling in SnapshotHelper (#10736) via Sampsa Kuronen
* Fixes image reference in pilot's README. (#10804) via Péter Krassay
* Fixed instruction for update plugin (#10809) via Rishabh Tayal
* Fix mismatched <th> tags in docs_generator (#10797) via David Vanoni
* Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta
* Remove redundant let declaration for a discardable result (#10762) via Sampsa Kuronen
* Update AppfileTemplate (#10759) via Aaron Brager
* Added is_string: false to active_days_limit config entry (#10763) via vspac
* issue template fix (#10673) via Rishabh Tayal

Please update using `bundle update fastlane`
```

where `Snapshot - fix String character count deprecation warning in SnapshotHelper (#10761) via xta` is duplicated.

**Pull request merged**
