### PR TITLE
Adds --llvm-cov option support to slather action

### PR DESCRIPTION
**Pull request by sgtsquiggs**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Slather recently accepted a PR to add --llvm-cov output option: https://github.com/SlatherOrg/slather/pull/354

**This PR should be placed on hold until slather cuts a new release with the above merged PR.**

### Description

Adds --llvm-cov option to the slather action. This option outputs code coverage in the raw `llvm-cov show` format.

### CODE REVIEW

**Comment by sgtsquiggs** [comment]
@googlebot I signed it!

**Comment by sgtsquiggs** [comment]
@googlebot I signed it twice!

**Review by dunyakirkali — APPROVED** [review]
Looks good!

**Comment by KrauseFx** [comment]
Hey @sgtsquiggs, thanks for the PR. Is this ready for review + merge, or are we waiting for the release to be shipped?

**Comment by KrauseFx** [comment]
I updated the PR title for now to indicate that this shouldn't be merged yet until the release is confirmed

**Comment by sgtsquiggs** [comment]
Hi @KrauseFx. The release I was waiting on is out: https://github.com/SlatherOrg/slather/releases/tag/v2.4.4. It's also made it to rubygems https://rubygems.org/gems/slather/versions/2.4.4.

**Review by KrauseFx — APPROVED** [review]
Wonderful, thanks for your contribution 👍

**Comment by janpio** [comment]
(I removed the [WIP] from the PR title then)

**Pull request merged**
