### PR TITLE
Don't show version bump info on manual `fastlane init`

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by hjanuschka — APPROVED** [review]

**Comment by lacostej** [comment]
I don't understand. Aren't you only showing it in manual mode? It sounds countrary to your issue description.

**Comment by KrauseFx** [comment]
Nice catch @lacostej, I in fact mixed up the boolean value, time to get some coffee ☕️ 👍

**Comment by lacostej** [comment]
It wasn't obvious to me what the relation between manual mode and showing the version bump information was.

Just for the sake of understanding it, you are hiding the message in manual mode because we assume the user is a power user and knows what he is doing, right? If this is right, and it's the only place we take such a decision, maybe add a little comment to explain the relationship.

**Review by lacostej — APPROVED** [review]
Change is fine. A comment might help!

**Comment by KrauseFx** [comment]
Yah, hiding, because we're not actually doing a version bump, and often on manual mode, the user might not even have an Xcode project

**Pull request merged**
