### PR TITLE
testfairy: removed watermark, added defaults to auto-update

### PR DESCRIPTION
**Pull request by yairba**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by janpio** [comment]
Why did you remove the watermark option?

**Comment by yairba** [comment]
It is an old feature that is not supported any more.
Here is the updated list: https://docs.testfairy.com/API/Upload_API.html

**Review by taquitos — COMMENTED** [review]
Before merging, can you also remove the code that makes use of the `icon_watermark` value in `testfairy.rb`?

**Review by taquitos — APPROVED** [review]
🎈:goat:

**Pull request merged**
