### PR TITLE
Fixed slack action in Swift.

### PR DESCRIPTION
**Pull request by antonino-u**
The default `slack` action doesn't work even if you override the two parameters that are broken. This is due to Ruby recognizing the default `"{}"` string as a string and not as a hash.

(I'm not a Ruby dev at all so if this isn't the right way to fix this please help me!)

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Slack action failling to send any messages.

### CODE REVIEW

**Comment by antonino-u** [comment]
I signed it!

**Comment by antonino-u** [comment]
I signed it!

**Comment by taquitos** [comment]
Good news/bad news, 
Good news: that fix would work, so thank you for looking into it! 
Bad news: That file is actually autogenerated 

@thii has a PR open to fix the code generator 🎉  https://github.com/fastlane/fastlane/pull/11749 so once that is updated and merged, `Fastlane.swift` will be updated at the next deployment 🎈

**Comment by antonino-u** [comment]
@taquitos I thought it might be autogenerated, but I wasn't 100% sure hehe. Thanks for looking at this, I'll close the PR now and wait for the one you mentioned to be merged. Cheers!

**Pull request closed without merging**
