### PR TITLE
Updating last_git_tag to use

### PR DESCRIPTION
**Pull request by jeeftor**
In reference to my issue #1039 I thought this "might" help things.

Updating the last tag comment to use 

```
git describe --tags `git rev-list --tags --max-count=1`
```

### CODE REVIEW

**Comment by mfurtak** [comment]
Hey @jeeftor - thanks for this contribution :+1: 

I was able to confirm that your improved command works on a shallow clone where our original does not. :100: 

I noticed you updated the `last_git_tag_spec`, which is great! However, I think the failing CI build is because of some other areas of code (and their tests) which also depend on that `last_git_tag_name` helper. Can you make sure that `bundle exec fastlane test` passes for you locally, and check out updating the `changelog_from_git_commits_spec`?

Thanks! :dart:

**Comment by jeeftor** [comment]
I'm on it!

**Comment by jeeftor** [comment]
Also thanks for the bundle info - I've actually done very minimal ruby work so wasn't sure how to run the tests locally

**Comment by jeeftor** [comment]
Looks like we are good to go!

**Comment by jeeftor** [comment]
I might update the documentation however...

**Comment by jeeftor** [comment]
:+1:  - everything is ready to go.

**Comment by mfurtak** [comment]
Great, this looks good to me! Please squash to 1 commit, and we'll get it merged. :rocket:

**Comment by jeeftor** [comment]
Single commit it is :rocket:

**Comment by mfurtak** [comment]
@jeeftor Cheers! :beers: Thanks for the fix!

**Pull request merged**
