### PR TITLE
[fastlane_core] improve simulator parsing of simctl 

### PR DESCRIPTION
**Pull request by dmytro-me**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [] I've updated the documentation if necessary.

### Motivation and Context

Better parsing simctl output to build list of available iOS/tvOS/watch simulators

Resolves issue  #16264

### Description

Updated regular expression to better parse simctl output. A newer regular expression tries to parse simulator name as a single group instead of multiple groups.

I was using Xcode 11.4 Simulators to test my changes, additionally I have created custom "iPad Air (3rd generation) Dark" simulator.

<pre>
+--------------------------------+-------+
|            snapshot results            |
+--------------------------------+-------+
| Device                         | en-US |
+--------------------------------+-------+
| iPad Air (3rd generation) Dark |  💚   |
| iPad (7th generation)          |  💚   |
+--------------------------------+-------+
</pre>

In fastlane 2.145 it was impossible to test on "iPad Air (3rd generation) Dark" simulator.

### CODE REVIEW

**Comment by dmytro-me** [comment]
@googlebot I signed it!

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This looks great! Do you think you can update a test in the device_manager_spec.rb to include a test for a custom named simulator like yours? 😊

**Comment by dmytro-me** [comment]
@joshdholtz, done! I didn't want to modify existing "fixtures" since they were from previous Xcode versions, so I've created new one and added Xcode 11 test group.

The source code lint fails on CI, but I've used existing test code style.

**Comment by joshdholtz** [comment]
Thanks for fixing! I’ll go take a look and fix 😇 I’ll merge this in today and probably get a new release out on Friday or Saturday with this in it. Thanks for PRs ❤

**Comment by dmytro-me** [comment]
@joshdholtz  do not merge please, it looks like lint issues is my fault.

**Comment by dmytro-me** [comment]
@joshdholtz I will close this PR and reopen new one tomorrow. Have to revert last commit and do not want to bloat fastlane history.

**Comment by joshdholtz** [comment]
You really didn’t have to close 😊 We squash the commits when they get merged

**Pull request closed without merging**
