### PR TITLE
Implement Amazon Appstore support

### LINKED ISSUE #15148: Amazon Appstore Support
### Feature Request
Amazon Appstore Submission Support

It seems that Amazon has finally provided an API for submissions. It is supposedly largely compatible with the Play store one.

https://developer.amazon.com/blogs/appstore/post/a7f55c5e-aa33-4301-b92b-753ffc875ba7/introducing-the-app-submission-api%20(Amazon%20submission%20API)

https://developer.amazon.com/docs/app-submission-api/overview.html

Previous issue auto-closed here:
https://github.com/fastlane/fastlane/issues/14681#issue-437342861

#### Motivation Behind Feature
This is a growing platform with a unique userbase that is simply time-consuming to manage the release process.

#### Feature Description
Fastlane should provide support for submission to Amazon Appstore. This should not negatively impact any developers.

#### Alternatives or Workarounds
We manually submit on our own today.

### PR DESCRIPTION
**Pull request by kreeger**
### Checklist

- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
    * Tests currently fail (see below)
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #15148

This changeset introduces a new plugin to help Fastlane interface with the Amazon Appstore App Submission API, much like `supply` does with the Google Play Store API.

This pull request is currently a work-in-progress with some changes soon to come from @joshdholtz to help tie things into Fastlane plugin ecosystem.

### Testing Steps

Testing steps are coming soon, and unit tests are currently unhappy due to the use of a new `ActionSets` namespace (this is part of what @joshdholtz will be helping with).

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by lacostej** [comment]
Wouldn't it make more sense to have those plugins outside of fastlane?

**Comment by tmm1** [comment]
Hi, is this still in progress?

How does it compare to https://github.com/ugroupmedia/fastlane-plugin-amazon-app-store-submission

**Comment by redreceipt** [comment]
ping

**Comment by kreeger** [comment]
I'm going to move this out to a separate gem and plugin repo that I'll link here momentarily. Closing this PR since it's been dead for a while!

**Pull request closed without merging**
