### PR TITLE
[match] delete the correct files when working with multiple teams on S3

### PR DESCRIPTION
**Pull request by castus**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
It fixes the bug https://github.com/fastlane/fastlane/issues/16532

### Description
According to documentation S3 and Google Cloud storage saves the files starting with `team_id`. Git storage uses branches to distinguish between teams. The fix was to correct the way each storage list files to delete. I've tested it on S3 and Git using multiple teams and it works.

### Testing Steps
* To test it you need to have an account with multiple teams.
* Then you need to use `match` to generate profiles and certificates. You don't need to create each type, one type is enough to test the fix (for ex. development).
* You need to `match` for Git and S3 (or Google Cloud)
* Then you need to `nuke` it. Previously when you nuke S3 account, it will delete all files no matter what team you give. 
* Expected behaviour is to nuke only files in the team you provided. This pull request fixes it.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
Thanks for making this fix! Great catch 😊 I added one commit to get the `team_id` from the logged in Spaceship session but other than that this was 💯

**Comment by castus** [comment]
Thanks for accepting @joshdholtz It was a real fun contributing to fastlane, I should definitely do it more often ;) Could you tell me when you would like to release that fix?

**Comment by joshdholtz** [comment]
@castus We'd be happy to have more contributions! And its release now 😊 Thanks again! ❤️

**Pull request merged**
