### PR TITLE
[spaceship] Replace apple endpoints used for teams with olympus session

### PR DESCRIPTION
**Pull request by VrsajkovIvan33**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Apple started returning "Unauthorized Access" errors when trying to do a login. Namely, we noticed that it was failing at the step where the `team_id` is either retrieved or set in the Spaceship client. Given the widespread reports that reverting back to Fastlane version 2.176.0 solved the issue, we assumed it had to be somehow connected with the [changes to the way the team id is managed in 2.177.0](https://github.com/fastlane/fastlane/pull/18279). 

Further investigation led us to observe that, when switching between teams/providers in App Store Connect, the following two endpoints are not used:
- `/WebObjects/iTunesConnect.woa/ra/user/detail`
- `/olympus/v1/providerSwitchRequests`

Instead, a GET and a POST request are used on `https://appstoreconnect.apple.com/olympus/v1/session`, respectively.

The providers themselves can now be found in the response to the GET request, under the `availableProviders` field. 

Furthermore, while examining the payload sent to Apple when switching between two providers, we determined that the only data that refers to the new provider in the payload is stored inside `"provider": {"providerId": ...}`, using the provider ID and not the public provider ID.

Taking this into account, we tried making a POST request to `https://appstoreconnect.apple.com/olympus/v1/session` while providing just the provider ID in the payload and the call has seemingly worked. Crucially, the `X-Requested-With` header needed to be provided with the value `olympus-ui` in order to make the call work. 

Potentially resolves:
- Unauthorized access (upload_to_testflight) [#20071](https://github.com/fastlane/fastlane/issues/20071)
- Unauthorized Access (Spaceship::UnauthorizedAccessError) [#20072](https://github.com/fastlane/fastlane/issues/20072)
- The request could not be completed because: Unauthorized Access [#20078](https://github.com/fastlane/fastlane/issues/20078)

And the other similar ones being reported.

### Description
**This is just a work in progress!** The main purpose of this PR is to help the Fastlane maintainers understand what is causing the current issue, after we have already come to these conclusions. The implementation is opinionated and any suggestion is very appreciated! 😃 

This PR modifies the way the teams are set + the way the user details data is fetched (and, by extension, the teams too) by changing the methods to target Apple's `https://appstoreconnect.apple.com/olympus/v1/session` endpoint instead.

The mapping is updated so that the current variables in the code can preserve their current role.

As mentioned above, the call to set the team is modified so that only the `provider` -> `providerId` is specified because this is the minimal solution we were able to find. We have observed that the call works even if we put the whole result from the GET request in the body of the POST.

### Testing Steps
Local checks performed show that no `Unauthorized Access` checks are being returned when trying to fetch or modify the team.

The tests in Fastlane have not yet been updated due to this being just a WIP.

### CODE REVIEW

**Comment by snatchev** [comment]
This looks promising @VrsajkovIvan33. I am taking a look locally as well.

**Comment by joshdholtz** [comment]
@VrsajkovIvan33 Thanks so much for this! I'm going to test this out now.

Quick question... do you mind giving me access to your fork or remaking this PR form a personal account? I can't add commits to this if its fork on an org 🙃

**Comment by VrsajkovIvan33** [comment]
@joshdholtz We'd need to consult our legal team in order to give you access to our internal fork and that would take time. On the other hand, I can't re-create the PR with my personal account because I do not have CLA set up to contribute. 😞 

But! Since time is of the essence, what about you just copying the changes from this PR as is and using it in any way you seem fit in your official fix, while closing this PR?

We don't mind giving up the contribution if it means that you will be able to prepare a fix ASAP, which is in everyone's interest. 😃

**Comment by joshdholtz** [comment]
@VrsajkovIvan33 You are hero! I can do that but I will make sure you get full credit ❤️ 

I will also talk to GitHub to see if we can get this org fork thing changed 😊

**Comment by joshdholtz** [comment]
@VrsajkovIvan33 @valerio-castelli Thank you both so much! Do either of you have Twitter handles I can mention you in when a release gets made?

**Comment by joshdholtz** [comment]
@VrsajkovIvan33 I've created #20083 with your commit in it! Do you mind commenting in there saying something like "you approve of this"? 🙃 Just for the record 🤷‍♂️

**Comment by VrsajkovIvan33** [comment]
@joshdholtz Left the comment on the new PR as asked, my Twitter handle should be `VrsajkovIvan33`. Happy to have been of help, big fan of your work! 💪

**Pull request closed without merging**
