### PR TITLE
Return url rather than JSON

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Whops :)

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @ohayon</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
Do you think this PR will fail the tests? https://github.com/fastlane/fastlane/blob/master/fastlane/spec/actions_specs/create_pull_request_spec.rb#L30-L31

**Review by KrauseFx — APPROVED** [review]
👍

**Pull request merged**
