### PR TITLE
Version link for hockey app fix

### PR DESCRIPTION
**Pull request by wolffan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
This fixes the issue (generated by the previous merge) https://github.com/fastlane/fastlane/issues/9614

### CODE REVIEW

**Review by ilyasemenow90 — COMMENTED** [review]
Maybe you can select solution with trying get "version" parameter from response. And only if version parameter nil get version from "config_url" ? Because now if HockeyApp will change response "config_url" app will crash with simultaneously error.

**Comment by wolffan** [comment]
@lexusilia any idea how to create tests for this? My knowledge of ruby is limited...

**Comment by wolffan** [comment]
@lexusilia i'm having a weird issue with versions.
I've updated my repo and created this: https://github.com/fastlane/fastlane/pull/9619

**Comment by wolffan** [comment]
I'll close

**Pull request closed without merging**
