### PR TITLE
Validate CocoaPods Keys action

### PR DESCRIPTION
**Pull request by ashfurrow**
Continued from our discuss at https://github.com/artsy/eidolon/pull/541/files#r42803717

Tests _pass_, but I am using a partial mock to stub out accessing the Podfile, and also invoking a CocoaPods shell command. Happy to be pointed in the right direction to avoid those, if that's a good idea.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Not sure why the CI is still red...

**Comment by KrauseFx** [comment]
Really sorry about the failing build - I broke some things with the big merges yesterday.

Thanks for the pull request @ashfurrow, reviewing it now :+1:

**Comment by KrauseFx** [comment]
Great implementation, updated documentation and tests, what a perfect pull request, thanks @ashfurrow :heart_eyes:

**Comment by ashfurrow** [comment]
:bow: :tada:

**Pull request merged**
