### PR TITLE
[core] added loading indicator for importing keys command

### PR DESCRIPTION
**Pull request by RishabhTayal**
Sometimes it takes a lot of time to run command `security set-key-partition-list` in https://github.com/fastlane/fastlane/blob/f9db58aa8059cf2a47cb00939e9566efeffe69cc/fastlane_core/lib/fastlane_core/keychain_importer.rb#L20-L20

Adding a loading indicator to give feedback to the user that the keys are being imported.

### CODE REVIEW

**Comment by janpio** [comment]
What does that look like? What are the reasons for this command needing so long?

**Comment by RishabhTayal** [comment]
@snatchev has a [branch](https://github.com/fastlane/fastlane/tree/speed-up-keychain-importer) which reduces the time so this PR might not be relevant. @snatchev can make the decision.

**Comment by RishabhTayal** [comment]
Actually, I test @snatchev's branch and there is still some processing time for the command. It's significantly improved but there is still some duration. I think it's better to add a loading indicator.

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@RishabhTayal Can you rebase this so that this is ontop of the commits with the improved import times? 🙃 My import isn't instant so I'd like to see what this is like with that. How long does this take for you?

**Comment by RishabhTayal** [comment]
Done.

**Comment by RishabhTayal** [comment]
@Joshdholtz its ready to review again.

**Review by joshdholtz — APPROVED** [review]

**Pull request merged**
