### PR TITLE
Fix import_from_git when specifying a tag and cache_path

### LINKED ISSUE #21142: Using import_from_git with version tag
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [+] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [+] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If import_from_git lead to update repository, fastlane execute chain of commands:
cd ./my-repository.git && git checkout HEAD && git reset --hard && git pull --all

Command "git pull --all" causes to an error.

##### Command executed
import_from_git(
    url: 'ssh://git@git/my-repository.git',
    branch: 'HEAD',
    path: 'SharedFrameworks/Fastfile',
    version: ['1.3.0'],
    cache_path: File.join(Dir.pwd, 'remote_fastlane')
  )

##### Complete output when running fastlane, including the stack trace and command used
"You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details."

### Environment

<details>
  <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 13.0.1                                         |
| Ruby                        | 2.7.4                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.37.0                             |
| Installation Source         | ~/am-ios/vendor/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | macOS 13.0.1 (22A400)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.4/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1l  24 Aug 2021                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 14.1                                           |
| Swift Version               | 5.7.1                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-appcenter                 | 1.11.0  | 🚫 Update available |
| fastlane-plugin-badge                     | 1.5.0   | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution | 0.3.6   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.4.0        |
| bundler                                   | 2.2.28       |
| uri                                       | 0.10.0       |
| rake                                      | 13.0.6       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.10       |
| i18n                                      | 1.12.0       |
| minitest                                  | 5.16.3       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.10       |
| activesupport                             | 5.2.4.5      |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.1        |
| mustache                                  | 1.1.1        |
| zip                                       | 2.0.2        |
| agen                                      | 0.16.0       |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.3        |
| algoliasearch                             | 1.27.5       |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.2       |
| colored2                                  | 3.1.2        |
| stringio                                  | 0.1.0        |
| date                                      | 3.3.0        |
| time                                      | 0.2.0        |
| open-uri                                  | 0.3.0        |
| alfa_utils                                | 0.22.1       |
| rchardet                                  | 1.8.0        |
| git                                       | 1.12.0       |
| liquid                                    | 5.4.0        |
| thor                                      | 0.20.3       |
| algen                                     | 0.1.1        |
| artifactory                               | 3.0.5        |
| ast                                       | 2.4.2        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.716.0      |
| aws-sigv4                                 | 1.5.2        |
| jmespath                                  | 1.6.2        |
| aws-sdk-core                              | 3.170.0      |
| aws-sdk-kms                               | 1.62.0       |
| aws-sdk-s3                                | 1.119.1      |
| babosa                                    | 1.0.4        |
| fastimage                                 | 2.2.6        |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.99.0       |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.3       |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.7.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.17.0       |
| googleauth                                | 1.3.0        |
| mini_mime                                 | 1.1.2        |
| declarative                               | 0.0.20       |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| rexml                                     | 3.2.5        |
| webrick                                   | 1.8.1        |
| google-apis-core                          | 0.11.0       |
| google-apis-androidpublisher_v3           | 0.34.0       |
| google-apis-playcustomapp_v1              | 0.12.0       |
| digest-crc                                | 0.6.4        |
| google-apis-iamcredentials_v1             | 0.17.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.44.0       |
| mini_magick                               | 4.12.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.7.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.10       |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| claide                                    | 1.0.3        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.22.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| badge                                     | 0.13.0       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.5.1        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| cocoapods                                 | 1.11.2       |
| diffy                                     | 3.4.2        |
| fastlane-plugin-appcenter                 | 1.11.0       |
| fastlane-plugin-badge                     | 1.5.0        |
| fastlane-plugin-firebase_app_distribution | 0.3.6        |
| parallel                                  | 1.22.1       |
| parser                                    | 3.1.2.1      |
| rack                                      | 3.0.0        |
| rainbow                                   | 3.1.1        |
| regexp_parser                             | 2.5.0        |
| rubocop-ast                               | 1.21.0       |
| ruby-progressbar                          | 1.11.0       |
| rubocop                                   | 1.8.1        |
| rubocop-minitest                          | 0.10.3       |
| rubocop-performance                       | 1.10.1       |
| rubocop-rails                             | 2.9.1        |
| rubocop-rake                              | 0.5.1        |
| rubocop-rspec                             | 2.2.0        |
| rubocop-sequel                            | 0.2.0        |
| slack-notifier                            | 2.4.0        |
| xcode-install                             | 2.7.0        |
| xcresult                                  | 0.2.1        |
| xcov                                      | 1.7.2        |
</details>

*generated on:* **2023-03-17**
</details>
</details>

### PR DESCRIPTION
**Pull request by jenskuhrjorgensen**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Fixes #21142.

If you run `import_from_git` with a tag and `cache_path` like this:

```
import_from_git(
  url: "https://myprivaterepo",
  branch: "fastlane/1.2.3", # This is a tag, not a branch!
  cache_path: "./cache/fastlane",
)
```

It fails (for full error log see bottom of post):

```
...
bundler: failed to load command: fastlane (/Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/bin/fastlane)
/Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'cd /Users/johndoe/Documents/repos/myrepo/fastlane/cache/fastlane/myprivaterepo && git fetch --all --quiet && git checkout fastlane/0  && git reset --hard && git rebase' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
HEAD is now at d81cbd8 revert
HEAD is now at d81cbd8 revert
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-rebase(1) for details.

    git rebase '<branch>'
...
```

### Description

This PR avoids running `git rebase` when `cache_path` is provided and `branch` is actually a git tag and not a branch - because you have to be on a branch in order to do a git rebase.

I've tested my PR by both running `import_from_git` with the `branch` parameter being a git tag and a git branch and verified that `git rebase` is still called when `branch` is actually a branch and not called when `branch` is a git tag:

`branch` is a git branch:

```
import_from_git(
  url: "https://myprivaterepo",
  branch: "fastlane/some-branch", # This is a branch, not a tag!
  cache_path: "./cache/fastlane",
)
```

`branch` is a git tag:

```
import_from_git(
  url: "https://myprivaterepo",
  branch: "fastlane/1.2.3", # This is a tag, not a branch!
  cache_path: "./cache/fastlane",
)
```

### Testing Steps

See previous description on how to test this. 

<details>
  <summary>Full error log</summary>

```
[13:31:51]: -----------------------------
[13:31:51]: --- Step: import_from_git ---
[13:31:51]: -----------------------------
[13:31:51]: Eligible for caching
[13:31:51]: Fetching remote git branches and updating git repo...
[13:31:51]: $ cd /Users/johndoe/Documents/repos/myrepo/fastlane/cache/fastlane/myprivaterepo && git fetch --all --quiet && git checkout fastlane/0  && git reset --hard && git rebase
[13:31:52]: ▸ HEAD is now at d81cbd8 revert
[13:31:52]: ▸ HEAD is now at d81cbd8 revert
[13:31:52]: ▸ You are not currently on a branch.
[13:31:52]: ▸ Please specify which branch you want to rebase against.
[13:31:52]: ▸ See git-rebase(1) for details.
[13:31:52]: ▸ git rebase '<branch>'

Looking for related GitHub issues on fastlane/fastlane...

+-------------------------------------------+
|         Plugin updates available          |
+-----------+--------------+----------------+
| Plugin    | Your Version | Latest Version |
+-----------+--------------+----------------+
| appcenter | 2.0.0        | 2.1.2          |
+-----------+--------------+----------------+
[13:31:52]: To update all plugins, just run
[13:31:52]: $ bundle exec fastlane update_plugins

bundler: failed to load command: fastlane (/Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/bin/fastlane)
/Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'cd /Users/johndoe/Documents/repos/myrepo/fastlane/cache/fastlane/myprivaterepo && git fetch --all --quiet && git checkout fastlane/0  && git reset --hard && git rebase' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
HEAD is now at d81cbd8 revert
HEAD is now at d81cbd8 revert
You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-rebase(1) for details.

    git rebase '<branch>'


	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:346:in `block (3 levels) in import_from_git'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/helper.rb:342:in `with_env_values'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:345:in `block (2 levels) in import_from_git'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:393:in `block in import_from_git'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:282:in `import_from_git'
	from Fastfile:4:in `parsing_binding'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:61:in `eval'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:61:in `block in parse'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:50:in `parse'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane_manager.rb:14:in `new'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/lane_manager.rb:14:in `cruise_lane'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/gems/fastlane-2.221.1/bin/fastlane:23:in `<top (required)>'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/bin/fastlane:25:in `load'
	from /Users/johndoe/Documents/repos/myrepo/gems/ruby/3.2.0/bin/fastlane:25:in `<top (required)>'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli.rb:455:in `exec'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli.rb:35:in `dispatch'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/cli.rb:29:in `start'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/exe/bundle:28:in `block in <top (required)>'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/johndoe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.5.13/exe/bundle:20:in `<top (required)>'
	from /Users/johndoe/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
	from /Users/johndoe/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
```
</details>

### CODE REVIEW

**Comment by jenskuhrjorgensen** [comment]
@oct0f1sh thanks for fixing the CircleCI checks! How do I rerun the checks for my PR so my PR it appears "green"? Do I have to make a new commit to it?

**Comment by jenskuhrjorgensen** [comment]
Nevermind, I found the "Sync fork" button in my PR which retriggered the CI checks 👍

**Comment by jenskuhrjorgensen** [comment]
Nevermind, I found the "Sync fork" button in my PR which retriggered the CI checks 👍

**Comment by jenskuhrjorgensen** [comment]
@joshdholtz it looks like @oct0f1sh has become inactive on GitHub. Maybe you or some other maintainer can give this PR a quick look? 

Thanks in advance.

**Review by lucgrabowski — APPROVED** [review]
Thank you for your contribution 💪. Looks good to me :)

**Comment by jenskuhrjorgensen** [comment]
Thanks a lot @lucgrabowski <3

Together with this PR I also created another one about adding support for `git_basic_authorization`. Maybe you could also have a look at that at some point? 
https://github.com/fastlane/fastlane/pull/22135

**Pull request merged**
