### PR TITLE
[spaceship] Add basic support for Developer ID profiles

### PR DESCRIPTION
**Pull request by radex**
This extends Spaceship's provisioning profile support for Mac Developer ID distribution:
- If you have any Developer ID profiles, fetching all profiles won't blow up at `Can't find class '#{attrs['distributionMethod']}`
- Developer ID profiles become `Spaceship::Portal::ProvisioningProfile::Direct` objects
- Creating new Developer ID profiles works
- Updating Developer ID profiles works

### CODE REVIEW

**Comment by mfurtak** [comment]
Hi @radex - thanks for putting this together. It is looking great! 👍 

Can you take a look at `provisioning_profile_spec.rb` and see how it best makes sense to extend those tests to account for your changes?

Thanks!

**Review by mfurtak — CHANGES_REQUESTED** [review]
Please update tests to account for the new changes and prevent future regressions.

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
On second thought, we're going to try to get a _fastlane_ release out today, so let's adopt these changes as-is, and I'll supplement the tests 👍

**Comment by KrauseFx** [comment]
Looks great, thanks @radex 🚀

**Comment by radex** [comment]
Awesome — thanks @mfurtak!

liftoff

**Pull request merged**
