### PR TITLE
[action] new create_xcframework action

### LINKED ISSUE #17836: Support to create xcframeworks
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

There's currently no action in `fastlane` to create XCFrameworks, other than manually crafting the proper parameters calling the `xcodebuild` action.

### PR DESCRIPTION
**Pull request by jgongo**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #17836 
Conflict with #17837: only one should be merged into master

### Description

I have created a new `create_xcframework` action, separated from the `xcodebuild` action, although this action also generates a `xcodebuild` command. I think it made more sense to do it this way as the set of parameters of `-create-xcframework` is quite small and completely independent from the rest of parameters of `xcodebuild` (I think only `-output` it's used in other commands)

I'm rather new to Ruby, so please feel free to comment anything about the code (without hurting my delicate developer heart ❤️😝 ). Specifically, the `-create-xcframework` action supports a list of libraries which may have an associated headers directory. I have modeled this input parameter as a hash with library paths as keys and headers directory paths as values, using an empty string in the case that a library doesn't have associated headers. If you can think of a better way of expressing this in Ruby just tell me!

### Testing Steps

I have added a test suite providing tests for the most common scenarios.

```
bundle exec fastlane test
```

### CODE REVIEW

**Comment by rogerluan** [comment]
Hey @jgongo ! 👋 

Thanks for opening this alternate PR! I haven't reviewed your code yet, but I'm glad you were able to stretch your Ruby skills 😎 
I personally prefer this option so far, since it's more complete than the other one provided (it is a full solution, as opposed to partial), and keeps the code more modular. However, keep in mind [_fastlane's_ vision](https://github.com/fastlane/fastlane/blob/master/VISION.md#actions-and-plugins), specially regarding actions and plugins. For this reason, I'm not sure if this action will be approved to be merged into _fastlane_ core. However, there's always space for community-maintained actions and plugins 🤗 

I'll leave it up to @joshdholtz  to decide which PR to accept, and whether it should belong to this repo 😃 

Once again, thank you for your contributions!! ❤️

**Comment by jgongo** [comment]
Ok, just let me know if this can be accepted into fastlane core or not. If not I'll publish it as a plugin. Thanks!!

**Comment by jgongo** [comment]
Hi @joshdholtz sorry to insist, but I'm waiting for this to continue working in a project. Could you please tell me if this will be accepted into fastlane core? If not I can publish this as an independent action and declare a dependency to that... thanks, and sorry again.

**Comment by joshdholtz** [comment]
@jgongo Hey! Sorry about the wait. Me and my wife just had a baby so I'm getting to things a little bit slower than usual. I do appreciate the friendly ping though! ❤️

I'm hoping to get to reviewing more PRs this afternoon and another release cut soon there after.

**Comment by jgongo** [comment]
Congratulations, @joshdholtz !! I wouldn't have bothered you if I knew!! 😄 I've been there, so take it easy and rest while the baby is sleeping 😉

**Comment by joshdholtz** [comment]
@jgongo No worries at all! I put it as my GitHub status but I don't actual know how that gets used or seen 😝 And thank you!! ❤️

**Review by joshdholtz — APPROVED** [review]
This looks perfect! Thank you not only for creating the action but also adding tests with it as well ❤️ Really appreciate the contribution!

**Comment by jgongo** [comment]
You're welcome!! Thanks for accepting it!!

**Pull request merged**
