### PR TITLE
Fix typo in Produce::Service

### PR DESCRIPTION
**Pull request by duxins**
Fix typo

### CODE REVIEW

**Comment by asfalcone** [comment]
Thanks @duxins 👍

**Comment by aln787** [comment]
@duxins thanks for the correction!  

This will resolve issue `[!] undefined method `data_proection'`. 

Detail:
- `produce enable_services -a <bundle_id> --data-protection unlessopen`
- Currently returns this error in produce 1.1.3:
```
/Users/<user>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/produce-1.1.3/lib/produce/service.rb:76:in `update': [!] undefined method `data_proection' for Spaceship::Portal::AppService:Class (NoMethodError)
Did you mean?  data_protection
Did you mean?  data_protection
```

**Comment by aln787** [comment]
@asfalcone any idea when this will be added into produce 1.1.4?

**Comment by asfalcone** [comment]
[`produce 1.1.4`](https://github.com/fastlane/fastlane/releases/tag/produce/1.1.4) has been release

**Pull request merged**
