### PR TITLE
[docs] Fix typo: exiting -> existing

### PR DESCRIPTION
**Pull request by svanzoest**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context

when reading the Plugins documentation, I stumbed across a typo which may confuse other readers. 

### Description

Fixes a small typo in the Plugins documentation

### CODE REVIEW

**Comment by svanzoest** [comment]
I signed it!

**Comment by KrauseFx** [comment]
Hehe, thanks, I think that was supposed to be `existing` :)

**Comment by svanzoest** [comment]
@KrauseFx that makes even more sense. Let me adjust that.

**Review by KrauseFx — APPROVED** [review]
Wohoo 👍

**Pull request merged**
