### PR TITLE
[fastlane_core] recognize "Buddy" CI service as a CI environment

### PR DESCRIPTION
**Pull request by sztwiorok**
Buddy is a CI/CD service. 
Please add this VAR to automatically setup the keychain and match to work with CI.

Here is a list of defaults ENV VARs in Buddy:
https://buddy.works/docs/pipelines/environment-variables#default-environment-variables

### CODE REVIEW

**Comment by ainame** [comment]
@sztwiorok Hi! Thank you for contributing to fasltane for the first time! As you see the above comment from 🤖, we need you to sign CLA to merge your PR. Please follow the instructions. 

If you have any difficulties to do so for whatever reasons, we can make another PR on behalf of you to add exactly the same change 🙇

**Review by ainame — APPROVED** [review]

**Review by ainame — APPROVED** [review]

**Comment by sztwiorok** [comment]
Hi @ainame, I have already sign CLA. Could you run this check once again?

**Comment by ainame** [comment]
@sztwiorok 

> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.

You need to do this

**Comment by ainame** [comment]
Oh apparently my comment triggered that so now you don't have to😅

**Comment by ainame** [comment]
@joshdholtz will double-check and merge when he can 🙇

**Review by joshdholtz — APPROVED** [review]
Love it! Thank you for the contribution ❤️

**Pull request merged**
