### PR TITLE
[action] add api bearer to create pull request

### PR DESCRIPTION
**Pull request by thilek**
Add bearer authentication option for create_pull_request action

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Currently the create_pull_request actions only support basic authentication. By adding this change, it is possible to specify a bearer token. A use case for example is if you're using a [github app](https://docs.github.com/en/free-pro-team@latest/developers/apps/authenticating-with-github-apps) to connect instead of a Personal Access Token.

### Description
Added an api_bearer parameter to create_pull_request action.
In create_pull_request, the bearer is propagated all the way down to the github_api action calls.

### Testing Steps
Changes have been tested by using my local branch of Fastlane in a Gemfile and running a lane that interacts with it.

```
  create_pull_request(
    api_bearer: 'a_valid_bearer',
    repo: "valid-repo",
    title: "'title",
    head: "head",
    base: "base",
    body: "message"
  )
```

### CODE REVIEW

**Comment by ThilekSilvadorai-TomTom** [comment]
@joshdholtz with your last commit its failing on CLA. Can you ammend the commit with a valid account ?

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by joshdholtz** [comment]
@ThilekSilvadorai-TomTom My apologies on that not fixing that right away 😇

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much for the contribution ❤️  Really appreciate it!

**Comment by ThilekSilvadorai-TomTom** [comment]
@joshdholtz no worries, this is my first time contributing to fastlane so wasn't sure whats the rules but you sorted it. Thank you. Looking forward to contribute more as we are using fastlane extensively.

**Comment by joshdholtz** [comment]
@ThilekSilvadorai-TomTom Super excited to hear you will be contributing more 🥳 I'll be reviewing hopefully at a faster pace now. I was unprepared for what my scheduled would be like when becoming a parent 😅 Thanks again for the contribution!

**Comment by ThilekSilvadorai-TomTom** [comment]
@joshdholtz  oh yes.. its exciting times. I had my first 3 years back and it's life changing experience but worth it. Congrats 🥳 to all 3 of you and all the best mate .

**Pull request merged**
