### PR TITLE
Update Supply to use 0.12.0 of google-api-client

### PR DESCRIPTION
**Pull request by tmtrademarked**
### Checklist
- [ X ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [  X ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ X ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ X ] I've updated the documentation if necessary.

### Motivation and Context

The problem is pretty simple: version 0.12.0 of the API has breaking changes. Without this change, unless developers know to manually lock their google-api-gem to 0.11.x, supply will not work for them.

### Description

Version 0.12.0 of the Google API Client gem has breaking API changes. Unfortunately, the previous gemspec requirement (~> 0.11) was slightly too permissive, and allowed the new version to be pulled in accidentally. This PR fixes this by upgrading to the new gem explicitly and updating the API calls.

This was generated by following the API diffs here (https://github.com/google/google-api-ruby-client/commit/3f26743ef728466c7f3edfe8dfb1224122c596b5#diff-215abaa8c4101dcb8977c43a24964183) and changing all calls in client.rb. I've validated by running my local project against this version of fastlane, and it seems to work as expected.

While I'm in here, it seemed like a good idea to update to 0.12.0 and fix the breakages. But the simplest possible fix would just be to lock the gem to 0.11.0 < 0.12.0 if someone else wants to do the upgrade later.

### CODE REVIEW

**Comment by ohayon** [comment]
Hey @tmtrademarked - we would definitely like to get this merged in. Would you mind just taking care of the merge conflicts and we can 🚀 !

**Comment by tmtrademarked** [comment]
@ohayon - resolved!

**Review by ohayon — APPROVED** [review]
🚀  Thanks @tmtrademarked !

**Comment by Capyvara** [comment]
Can we get back the supply --check-superseded-tracks after this?

**Comment by ohayon** [comment]
@Capyvara - Would you mind opening up an issue to discuss that?

**Comment by Capyvara** [comment]
I'll create an updated PR so.

**Comment by ohayon** [comment]
Sweet thanks @Capyvara !

**Comment by Capyvara** [comment]
Done!

**Comment by Capyvara** [comment]
@ohayon
Done!

**Pull request merged**
