### PR TITLE
Enforcing CSRF token fetching when working with provisioning profile

### PR DESCRIPTION
**Pull request by pbeast**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
When working with provisioning profiles (`portal_client.rb`) it looks like CSRF tokens may become obsolete sporadically what leads to error responses.

### Description
The solution is to enforce CSRF token update before making following requests:

- /createProvisioningProfile.action
- /downloadProfileContent
- /deleteProvisioningProfile.action
- /regenProvisioningProfile.action

### CODE REVIEW

**Comment by KrauseFx** [comment]
This will cause every spaceship request to send an additional request. Can we find a way to still use that caching, while also fix the situation you described?

**Comment by KrauseFx** [comment]
What's the best way to reproduce

**Comment by pbeast** [comment]
Hi,

The issue #11162 contains reproduction scenario. The reproduction doesn’t depends on time you are connected to the systems, but on number of calls to the same endpoint.

**Comment by pbeast** [comment]
Hi, just noted another open issue - #11434

**Comment by lacostej** [comment]
Just curious, 
* have we looked at the response headers of the response previous to the one that cause errors to see if there are hints that something is going to go wrong?
* alternatively, could we do a retry with fetching the CSRF upon 421 error ?

**Review by julianoterres — APPROVED** [review]

**Comment by janpio** [comment]
Hey @pbeast, is this still something that should be merged or did the problem go away in the meantime?

**Comment by pbeast** [comment]
Hi, the issue was resolved and can be closed. Thanks

Regards,
Pavel Yankelevich

________________________________

**Pull request closed without merging**
