### PR TITLE
Enable set 'NFC Tag Reading' at produce.

### PR DESCRIPTION
**Pull request by kazuhidet**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I wanted to use the "NFC Tag Reading" function on the iPhone, but since it was not in "fastlane produce enable_services", I added it.

### Description

Just added "- nfc - tag - reading" to "fastlane produce enable_services" option.

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Thanks for adding this! Can you also add documentation to `create_app_online.md` for this? 😊

**Comment by kazuhidet** [comment]
I'm sorry.
Since I forgot about it, I added a description about "NFC Tag Reading" to create_app_online.md.

**Comment by janpio** [comment]
Uh, what about those 2 deleted `.gif` files?

**Comment by kazuhidet** [comment]
It seems that the synchronization of my master branch and master branch of upstream was broken, so I fixed it.

**Comment by kazuhidet** [comment]
I added a description to switch between enable and disable for the following items which were missing even more.
--hotspot
--multipath

**Pull request closed without merging**
