### PR TITLE
Added gcovr action for code coverage generation.

### PR DESCRIPTION
**Pull request by dtrenz**
Added new [gcovr](http://gcovr.com/) code coverage generation action w/ spec.

This action supports all available gcovr CLI args:

``` ruby
object_directory: '--object-directory',
output: '-o',
keep: '-k',
delete: '-d',
filter: '-f',
exclude: '-e',
gcov_filter: '--gcov-filter',
gcov_exclude: '--gcov-exclude',
root: '-r',
xml: '-x',
xml_pretty: '--xml-pretty',
html: '--html',
html_details: '--html-details',
html_absolute_paths: '--html-absolute-paths',
branches: '-b',
sort_uncovered: '-u',
sort_percentage: '-p',
gcov_executable: '--gcov-executable',
exclude_unreachable_branches: '--exclude-unreachable-branches',
use_gcov_files: '-g',
print_summary: '-s'
```

Usage Example:

``` ruby
lane :test do
  # Run tests
  xctool :test

  # Create code coverage report directory, if it doesn't already exist
  sh "mkdir -p code-coverage"

  # Generate HTML code coverage
  gcovr({
    html: true,
    html_details: true,
    output: "./code-coverage/code-coverage-report.html"
  })
end
```

The above test lane is being used by me currently to run tests and generate HTML code coverage reports.

### CODE REVIEW

**Comment by KrauseFx** [comment]
This looks really great, thanks for working on this :+1: 

How about automatically creating the folder if necessary? 

Could you also update the README to explain how to use it (just a few lines, to not clutter the README)

Thanks!

**Comment by dtrenz** [comment]
Will do!

This is a great project. I’m happy to contribute to it. -d

-- 
Dan Trenz

On February 26, 2015 at 3:52:38 PM, Felix Krause (notifications@github.com) wrote:

This looks really great, thanks for working on this  

How about automatically creating the folder if necessary?

Could you also update the README to explain how to use it (just a few lines, to not clutter the README)

Thanks!

**Comment by dtrenz** [comment]
Hmm... I made the changes you asked for, but GitHub is now claiming there are merge conflicts. I'm not able to see any conflicts locally, are you able to see them or resolve them?

**Comment by dtrenz** [comment]
By the way, my IDE (sublime) is setup to auto-strip trailing whitespace, so maybe trimming up the README caused the conflict?

**Comment by KrauseFx** [comment]
Looks great, thanks for also adding a unit test for it :+1:

**Comment by KrauseFx** [comment]
This will be in the next release, thanks! :smiley:

**Pull request merged**
