### PR TITLE
[resign] fix entitlements merging when changing team while resigning

### PR DESCRIPTION
**Pull request by silvervest**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
These are the changes from https://github.com/fastlane/fastlane/pull/12131 updated to master and with merge conflicts resolved. Please see that issue for more in-depth detail.

This was resubmitted again due to lose head repository branch, but is the same changes.

### Testing Steps

supersedes #12131 and #15388

### CODE REVIEW

**Comment by silvervest** [comment]
The contents of this PR were approved, and all author CLAs have been signed a couple of times now in the other linked PRs.
@joshdholtz Is there anything (other than time and my messing up the previous PR) blocking this from being approved and merged? Please and thank you!

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@silvervest Hello! Do you mind appending the changelog to the top of the file with a summary of the changes here? 😊 After that we can get this merged 💪

**Comment by silvervest** [comment]
Done and done @joshdholtz, cheers!

**Comment by joshdholtz** [comment]
@silvervest Thank you! Will smash the merge button when tests are done running 💪

**Review by joshdholtz — APPROVED** [review]
This looks good to me! Thank you so much for reviving this PR (again (again)) ❤️ Really appreciate it!

**Comment by silvervest** [comment]
Great! And just for the official merge record, want to provide thanks to @kapfab for actually authoring this change in the first place 🥂

**Comment by kapfab** [comment]
You’re welcome. I just hope this PR will finally find its way to a release.

And in case this is needed, I’ll consent to the CLA.

**Comment by kapfab** [comment]
@googlebot I consent.

**Comment by kapfab** [comment]
Just had a quick look at the changes.

I think lines 798-805 (replacement of App ID and Team ID) could be removed, as lines 845-855 do the same on the whole entitlements file (which seems fine as other entitlements values could refer the App ID or Team ID).

Also, AFAIR, the `tr '\n' '\r’ | … | tr '\r' '\n’` (removed on line 788) was meant to actually remove the entitlements header (which it does not without it). This does not prevent the whole thing to work as `plutil` handles that gracefully, but the log will dump the headers for each key.

**Comment by kapfab** [comment]
@silvervest, did you voluntarily rollback you previous commit (https://github.com/fastlane/fastlane/commit/dd77fef0ac1677560a4e2fbffe1d166b0276fcb4)?

Also, is there a reason why line 827 changed from
```if [[ "$certificate_name" =~ "Distribution:" ]]; then```
to
```if [[ "$CERTIFICATE" =~ "Distribution:" ]]; then```
? I’m a bit worried on this specific change…

**Comment by silvervest** [comment]
> @silvervest, did you voluntarily rollback you previous commit ([dd77fef](https://github.com/fastlane/fastlane/commit/dd77fef0ac1677560a4e2fbffe1d166b0276fcb4))?

Hmm! Not voluntarily. I have no idea how that happened, actually.

> Also, is there a reason why `if [[ "$certificate_name" =~ "Distribution:" ]]; then` changed to this?
> https://github.com/fastlane/fastlane/blob/abe50beef43f5c8ccadc026f8dcd0d353bc2762a/sigh/lib/assets/resign.sh#L827

That appears to have been a typo from the very first merge conflicts I fixed in your original PR. Likely as the change to `$certificate_name` happened between your original commit and my involvement.
https://github.com/fastlane/fastlane/commit/b25f9ce37b0fed166ac69070c1beb9dd9a257f53#diff-95cccef747680a2777fd80b592db939260ffbd33ad1e31314635b8b9b01fe933L770-R803

I'll resolve these ASAP and submit another PR. Thanks for catching those @kapfab!

**Comment by silvervest** [comment]
> @silvervest, did you voluntarily rollback you previous commit ([dd77fef](https://github.com/fastlane/fastlane/commit/dd77fef0ac1677560a4e2fbffe1d166b0276fcb4))?

Actually @kapfab I'm looking at this again and I can't see this commit reverted? The file is up to date with this change in master?
https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L541

**Comment by kapfab** [comment]
> > @silvervest, did you voluntarily rollback you previous commit ([dd77fef](https://github.com/fastlane/fastlane/commit/dd77fef0ac1677560a4e2fbffe1d166b0276fcb4))?
> 
> Actually @kapfab I'm looking at this again and I can't see this commit reverted? The file is up to date with this change in master?
> https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L541

My mistake, I probably saw that on https://github.com/silvervest/fastlane/commit/caf995ebf3a181b0ceec9fb97faafd5e5d7315ee when I was looking for the origin of the certificate-related change.

**Comment by silvervest** [comment]
> Also, AFAIR, the `tr '\n' '\r’ | … | tr '\r' '\n’` (now removed on line 791) was meant to actually remove the entitlements header (which it does not without it). This does not prevent the whole thing to work as `plutil` handles that gracefully, but the log will dump the headers for each key.
> https://github.com/fastlane/fastlane/blob/abe50beef43f5c8ccadc026f8dcd0d353bc2762a/sigh/lib/assets/resign.sh#L791

I am really confused by this. I didn't remove this change, and if you look at the .patch of this pull request, that change is definitely in there, but it wasn't part of the merged changes, nor does it show on the files changed tab. I am at a loss...

**Comment by kapfab** [comment]
> > Also, AFAIR, the `tr '\n' '\r’ | … | tr '\r' '\n’` (now removed on line 791) was meant to actually remove the entitlements header (which it does not without it). This does not prevent the whole thing to work as `plutil` handles that gracefully, but the log will dump the headers for each key.
> > https://github.com/fastlane/fastlane/blob/abe50beef43f5c8ccadc026f8dcd0d353bc2762a/sigh/lib/assets/resign.sh#L791
> 
> I am really confused by this. I didn't remove this change, and if you look at the [.patch](https://github.com/fastlane/fastlane/pull/18713.patch) of this pull request, that change is definitely in there, but it wasn't part of the merged changes, nor does it show on the files changed tab. I am at a loss...

It was part of my initial commit that never reached the master branch (until today!), it probably got lost by someone else months ago during one of the different merges that occurred since. Not a big deal, that might be fixed in a future PR.

**Comment by csc-EricWu** [comment]
Hi @silvervest , I updated to the latest Fastlane, but this permission is invalid for me. Can you have a look?

com.apple.developer.icloud-container-environment

**Comment by csc-EricWu** [comment]
WARNING: Changing team while resigning
WARNING: Using these entitlements from the provisioning profile instead of the existing app:
WARNING: App Groups, Merchant IDs (Apple Pay In-App Payments), iCloud Containers, Pass Type IDs (Wallet)
WARNING: If these capabilities are enabled, make sure AppID and provisioning profile are properly configured
WARNING: Resigned app will allow all pass types from the new team, even if old app only allowed a restricted list
sed: 1: "s/<?xml version="1.0" e ...": unterminated substitute pattern
_floatsignTemp/Payload/Fuse.app: replacing existing signature
_floatsignTemp/patchedEntitlements: Could not modify plist, error: Failed to parse value  with type -xml

**Comment by kapfab** [comment]
> Hi @silvervest , I updated to the latest Fastlane, but this entitlement is invalid for me. Can you have a look?
> 
> com.apple.developer.icloud-container-environment

Which value did you expect and which one did you get?

**Comment by csc-EricWu** [comment]
image
This is the bag that was made through Xcode.

image
After Fastlane redesign, it disappeared.

**Comment by csc-EricWu** [comment]
image
I got an error message

**Comment by kapfab** [comment]
> After Fastlane redesign, it disappeared.

The only reason I can see for such a behaviour would be that your app did not include this entitlement but your provisioning profile did, which is quite unusual.
Can you unzip your old IPA and run the following command?
```
codesign -d --verbose --entitlements :- /path/to/unzipped/ipa/Payload/YourAppName.app
```

**Comment by csc-EricWu** [comment]
image
Yes, I tried to try again command, no problem.

**Comment by csc-EricWu** [comment]
@kapfab 
                ENTITLEMENTS_VALUE=$(echo "$ENTITLEMENTS_VALUE" | sed "s/$OLD_ICLOUD_ENV/$NEW_ICLOUD_ENV/g")

https://github.com/fastlane/fastlane/blob/abe50beef43f5c8ccadc026f8dcd0d353bc2762a/sigh/lib/assets/resign.sh#L833
In this line, I printed it out empty, adjusted the code here locally, and everything was OK

**Comment by kapfab** [comment]
I still do not understand how you original app ended up in this state.
It would be useful to know if this is an isolated case or if a recent change in Xcode broke the whole thing.

**Comment by csc-EricWu** [comment]
You need to try it once, I've found the cause of the problem

ENTITLEMENTS_VALUE=$NEW_ICLOUD_ENV

It works for me.

**Comment by kapfab** [comment]
After some investigation, your issue is related to the way entitlement values are extracted (what the lost `tr '\n' '\r' | … | tr '\r' '\n'` discussed above was meant to fix).

Your workaround might work (even though you feed the — quite permissive — `plutil` with `Production` instead of the `<string>Production</string>` XML element it expects), but this issue will affect other future entitlements whose `APP_ID`/`TEAM_ID`/`ICLOUD_ENV` fragment is to be patched.

I will open a new PR with a less specific fix.

Could you try to resign your app with this change (https://github.com/kapfab/fastlane/commit/8e988464b342e0b1f7c981c37ce1f05b5cdff3eb) to confirm this solves your issue?

**Comment by csc-EricWu** [comment]
After my test, the problem was solved perfectly. And I deliver to Appstore connect. thank you.

gem "fastlane", :git => "https://github.com/kapfab/fastlane", :branch => "resign_app_entitlements_fixes"

**Pull request merged**
