### PR TITLE
adding in pendingDeveloperRelease status

### PR DESCRIPTION
**Pull request by patternpaul**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:
#6430 gave me the AOK to giv'r. Here is my college try!

LETS DO THIS!

### CODE REVIEW

**Comment by KrauseFx** [comment]
Nice catch, thanks. Can you look a few line up, you'll find 

```
       # PENDING_APPLE_RELASE = "Pending Apple Release"
```

Would you mind removing this from the list of unused states? Also, feel free to implement more app states, if you have the short code for any of those 👍

**Comment by patternpaul** [comment]
@KrauseFx I cleaned out that line. I went and added three additional statuses (as shown in this commit https://github.com/fastlane/fastlane/pull/6436/commits/c07514d8998a5f7bd8c44352a4fbb14a52287143 ) and then backed it out because I was taking a huge guess at what those short codes were.

**Comment by KrauseFx** [comment]
Just to confirm, the mapping you added, you are sure the short code is correct?

**Comment by patternpaul** [comment]
@KrauseFx Very Sure! As noted in the ticket, I locally hacked my spacegem while the app was in the current state to validate. Kinda hacky but worked.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Awesome, thanks @patternpaul 👍

**Comment by patternpaul** [comment]
np! 💯

**Pull request merged**
