### PR TITLE
[fastlane] also support gm - as badge uses minimagick

### PR DESCRIPTION
**Pull request by hjanuschka**
badge - has  a fixed check for `convert` - but the `badge` gem uses minimagick - wich is compatible with `graphicsmagick` too.

issue is here: https://github.com/fastlane/fastlane/issues/6904
came in with: https://github.com/fastlane/fastlane/pull/6568

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looking at the action, the check should actually happen in the `badge` plugin, right? Why does _fastlane_ do it?

**Comment by hjanuschka** [comment]
@KrauseFx  you are right. i did a PR on `badge` https://github.com/HazAT/badge/pull/33
and did a if - so until `badge` has merged it. fastlane will do the check.

once the PR is merged - i am happy to do a follow up PR to remove the code at-all

**Comment by KrauseFx** [comment]
This is great, thanks @hjanuschka. Should we close this PR in the mean-time?

**Comment by hjanuschka** [comment]
currently since the the `check_imagemagick!` was implement it fails for users who don't have installed imagemagick, but have installed graphicsmagick. - i think we should merge it - ship it - so users are able to choose between gm and im, and after the PR - remove the code from fastlane.


actually there are some cases where GM is a alot better than im. so i think the argument to support both is valid.

**Comment by KrauseFx** [comment]
I think we should get rid of the verification in _fastlane_ for that action

**Comment by hjanuschka** [comment]
there it is! :) - keep you updated update the HazAT/badge#33 PR

**Comment by ooopscc** [comment]
Awesome, fastlane indeed should not check this action. If imagemagick or graphicsmagick not installed, just fails the job as expected. But now even one of them installed the job will fail. 

`HazAT/badge` use **mini_magick** to add badge, if neither of them installed, this error will throw

```shell
→ badge                                                                           [acc99c9]
[16:49:08]: Start adding badges...
[16:49:08]: './images.xcassets/AppIcon-Internal.appiconset/Icon-20@2x.png'

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Feature] Add overlay image on icons action
   https://github.com/fastlane/fastlane/issues/481 [closed] 21 💬
   22 Sep 2016

➡️  Escape single quotes in frameit title strings
   https://github.com/fastlane/fastlane/pull/4849 [closed] 25 💬
   06 Jul 2016

##################### NOTE THE FOLLOWING LINE #########################
/Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:204:in `rescue in validate!': **[!] ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)**
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:202:in `validate!'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:113:in `block in create'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `tap'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:112:in `create'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:34:in `read'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:90:in `block in open'
        from /Users/ooops/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:36:in `open'
        from /Users/ooops/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:36:in `open'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:89:in `open'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/lib/badge/runner.rb:128:in `add_badge'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/lib/badge/runner.rb:59:in `block in run'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/lib/badge/runner.rb:52:in `each'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/lib/badge/runner.rb:52:in `run'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/bin/badge:53:in `block (2 levels) in run'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/bin/badge:57:in `run'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/gems/badge-0.4.2/bin/badge:63:in `<top (required)>'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/bin/badge:22:in `load'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/bin/badge:22:in `<main>'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ooops/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```
by mini_magick with a non-zero status code, so neither fastlane nor badge need to add this verification.

So, will you just merge this pr and release a minor version like 1.108.1 to fix this issue, otherwise, I must use the old version back to 1.105.2. Our SRE will not install imagemagick as a workaround for this issue for security considerations (though imagemagick has fixed that problem).

**Comment by hjanuschka** [comment]
@KrauseFx  @HazAT merged the PR - so this PR is ready for review - as the code is now in `badge` itself.

@ooopscc in generall it is nicer to have handled errors - but you are right that mini_magick itself handles the error.

**Comment by orkenstein** [comment]
Please, merge this PR. `mini_magick` for life!

**Comment by milch** [comment]
Hey everyone, sorry about the delay! I see that badge has merged the required checks a while ago, so I'll merge this now! 

@hjanuschka Thanks for your contribution 🚀

**Review by milch — APPROVED** [review]

**Pull request merged**
