### PR TITLE
Fix wrong URL in S3 HTML template

### PR DESCRIPTION
**Pull request by thii**
Remove the duplicated `itms-services://?action=download-manifest&url=`

### CODE REVIEW

**Comment by ohwutup** [comment]
Thanks for the PR @thii! Do you have an example of how this was failing? Or a test to confirm it is working as expected now? Would you mind creating an issue and linking this PR with a bit more description of the problem?

**Comment by thii** [comment]
There was an issue here #743 but it was closed without being fixed.

**Comment by KrauseFx** [comment]
@thii I know of multiple teams successfully using the action. If we would merge this, it would probably break their setup. Do you know why this is working for some people?

**Comment by thii** [comment]
@KrauseFx Probably they (and I think most people) use custom template.

**Comment by KrauseFx** [comment]
@thii You're right, according to https://stackoverflow.com/questions/25562693/ios-enterprise-deployement-clicking-on-itms-services-link-results-in-cannot-co we're currently using the wrong format.
I'm really surprised this hasn't been raised or fixed before. Let's see if everything works as expected now.
Thanks for the pull request @thii 🚀

**Pull request merged**
