### PR TITLE
[screengrab] LocaleUtil set default locale

### PR DESCRIPTION
**Pull request by vanniktech**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Some of my code does depend on the default locale which wasn't set via the rule.

cc @janpio since you seem to be the person reviewing the related screengrab changes

### CODE REVIEW

**Comment by janpio** [comment]
Is this regarding #14584?

**Comment by vanniktech** [comment]
No. They are unrelated. This only sets the default locale on the device that we're running.

Pulling the screenshots and placing them inside the correct directory is another topic. If you can answer my [question](https://github.com/fastlane/fastlane/issues/14584#issuecomment-483060958), I can try pin pointing the exact version where this broke.

**Comment by janpio** [comment]
Ok, so no issue for this PR, correct?

Could this have any side effects (on others apps for example)?

**Comment by vanniktech** [comment]
> Ok, so no issue for this PR, correct?

Yes

> Could this have any side effects (on others apps for example)?

Only for the better since the locale wasn't changed before.

**Comment by vanniktech** [comment]
@janpio I'll sum it up here. This PR does indeed fix #14584 

In my app, I have a feature to change the language at runtime. It's similar to what fastlane does. (By creating a new Configuration and doing the entire ceremony.)

Now in my language feature, I only cared about the language (`Locale.getDefault().language`) which explained why images were being pulled into the `en` directory instead of `en-US`. Seems like those paths are created on the device rather than from the `locales` attribute in the Screengrab file.

I did fix my part of the section.

However, since fastlane does change the language before my code is run and I'm relying on `Locale.getDefault()`, fastlane needs to set the Locale. Otherwise, I have an inconsistent state my app (thinking it's on the phone's default language) vs the language chosen by fastlane (iterating through the locales).

This PR fixes the Locale and hence solves all of the problems. I've also verified this locally by applying the following patch file:

```diff
diff --git a/screengrab/screengrab-lib/build.gradle b/screengrab/screengrab-lib/build.gradle
index 9d2c68bb5..523d387f8 100644
--- a/screengrab/screengrab-lib/build.gradle
+++ b/screengrab/screengrab-lib/build.gradle
@@ -45,3 +45,14 @@ dependencies {
     api 'com.android.support.test.uiautomator:uiautomator-v18:2.1.3'
     api 'com.jraska:falcon:1.0.4'
 }
+
+buildscript {
+  repositories {
+    mavenCentral()
+  }
+  dependencies {
+    classpath 'com.vanniktech:gradle-maven-publish-plugin:0.8.0'
+  }
+}
+
+apply plugin: "com.vanniktech.maven.publish"
\ No newline at end of file
diff --git a/screengrab/screengrab-lib/gradle.properties b/screengrab/screengrab-lib/gradle.properties
new file mode 100644
index 000000000..f0b26368d
--- /dev/null
+++ b/screengrab/screengrab-lib/gradle.properties
@@ -0,0 +1,5 @@
+POM_NAME=Foo
+POM_ARTIFACT_ID=screengrab
+GROUP=tools.fastlane
+POM_PACKAGING=aar
+VERSION_NAME=3.0.0
\ No newline at end of file

```

By using my plugin and setting the necessary POM values I can execute `./gradlew installArchives` which does publish the library into my local maven repository which I can consume via:

```groovy
repositories {
  mavenLocal()
}

dependencies {
  androidTestImplementation "tools.fastlane:screengrab:3.0.0"
}
```

**Review by joshdholtz — COMMENTED** [review]
This seems legit to me! I will test this out later tonight/tomorrow. Thanks for finding this! ❤️

**Comment by vanniktech** [comment]
You're welcome! Have you had time to check it out?

**Comment by vanniktech** [comment]
Is there anything I can help to assist getting this merged in?

**Comment by vanniktech** [comment]
Friendly reminder @joshdholtz

**Comment by ppamorim** [comment]
@joshdholtz Could you please check this? :D

**Comment by ppamorim** [comment]
@vanniktech Is there any way to install this PR in my machine?

**Comment by janpio** [comment]
In your `Gemfile`, replace `gem "fastlane"` with `gem "fastlane", :git => "https://github.com/vanniktech/fastlane", :branch => "screengrab-localeutil-set-locale"`, then run `bundle update`.

**Comment by ppamorim** [comment]
@janpio Thank you!

**Comment by vanniktech** [comment]
Hmm, I'm not sure this works @janpio since I touched an android library and nothing in regards to the fastlane bundles. 

Why can't we merge this PR?

**Comment by janpio** [comment]
You are probably right @vanniktech - sorry @ppamorim.

I don't have the capacity to properly reproduce and test this @vanniktech right now. And in general I don't like approving code that I don't fully understand intuitively and have not tested.

**Comment by vanniktech** [comment]
Would it be possible to get someone to look at this? It's still blocking me and it's a bit sad to see that such a small PR has been open for 4 months.

**Comment by vanniktech** [comment]
Friendly ping @janpio

**Review by taquitos — APPROVED** [review]
🎈🐐

**Comment by vanniktech** [comment]
Thank you very much!

**Pull request merged**
