### PR TITLE
[spaceship] also catch and handle "Gateway Timeout"

### LINKED ISSUE #13241: download_dsyms does not retry errors
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Getting lots of errors during download_dsyms recently.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Spaceship::UnexpectedResponse: [!] <HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;54273017&#46;1535504570&#46;2614afa
</BODY></HTML>
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:602:in `parse_response'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/tunes_client.rb:256:in `applications'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:73:in `find'
  /Users/fancybox/source/channels/vendor/gems/ruby/2.4.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/actions/download_dsyms.rb:19:in `run'
</pre>
</details>

### PR DESCRIPTION
**Pull request by tmm1**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
fixes #13241

### CODE REVIEW

**Review by janpio — APPROVED** [review]

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Can we have this actually raise a new error called `GatewayTimeoutError`? 😊 A gateway error and internal service error will get handled the same way but it feels a bit dangerous to have the gateway error map to the `InternalServerError` and have the same error message as the `InternalServerError`. 

I think it would be ideal if we could get this mapped to a new error 💪

**Comment by tmm1** [comment]
I don't understand what's dangerous about it? They're both the same "in read" error.

**Comment by joshdholtz** [comment]
@tmm1 A gateway timeout error (504) is inherently different from an internal server error (500) where an 500 happens at an application level and a 504 happens at some network level.

I would suggest adding a new conditional with something like...
```rb
raise GatewayTimeoutInReadError, "Received an \"Gateway Timeout - In Read\" from App Store Connect / Developer Portal, please try again later"
```
as this error message will get printed out to the user. We do not want to map a "Gateway Timeout" as an "Internal Server Error".

To then account for this in the retry, we would add `GatewayTimeoutInRead` error to this rescue so that it gets retried - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L530-L535

This should have the same end result as your initial fix but this will present the proper error message to the end user if the retries are not successful

**Comment by tmm1** [comment]
Okay I can make those changes this week. Feel free to commit on this PR directly if you would like.

**Comment by joshdholtz** [comment]
@tmm1 Can you give me permission to push to this branch? There should be some permission option on the right side of the page I believe 🤔 Thanks!

**Comment by tmm1** [comment]
It's enabled already. Are you not able to push to my branch?

**Comment by tmm1** [comment]
I guess maybe it only works for "Maintainers"?

**Comment by joshdholtz** [comment]
@tmm1 Whoops! Was pushing to `apple_errors` instead of `apple-errors` 😝

**Comment by joshdholtz** [comment]
@tmm1 @janpio Pushed some changes here! Added new `GatewayTimeoutError` and also added a bunch of tests around these parts that should have existed before but didn't 😇

**Comment by tmm1** [comment]
👍🏼 LGTN

**Review by joshdholtz — APPROVED** [review]

**Pull request merged**
