### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by ashfurrow**
So you asked for feedback on the setup process, and I thought some updates to the documentation might help other developers get set up. There is a _tonne_ of awesome information in this repo, but it seems to have grown organically over time, so it's not necessarily the most organized. 

There were two goals I had in mind for this pull request:
- Make the README more of a sales pitch: "this is what fastlane is, this is why it's useful, this is how to install it, and here's where to go for more information."
- Make the documentation easy to find, read, and reference.

I made some major changes to accomplish these goals:
- Moved the documentation into a new `/docs` directory.
- Moved a lot of the README into the `/docs/README.md` file, which is parsed by GitHub when you look at that directory.
- Moved a lot of the README into other, more specific markdown files in the `/docs` directory.
- Reorganized the `Actions.md` file to group all the actions into one of several categories: Building, Testing, Deploying, Modifying Project, Developer Portal, Using git, and Notifications. Keeping all of these straight was actually one of the biggest challenges for me when I was setting up fastlane, so hopefully this makes things easier. 

There're also some smaller things I changed throughout, like consistently ending lists with periods, consistent capitalization, and consistent use of H1, H2, H3 in markdown files. I almost certainly missed some of these, but it's a start.

You can preview any changes [on my fork](https://github.com/ashfurrow/fastlane/tree/documentation). 

This is just an idea of how things could be – really looking forward to hearing your feedback. If you like something, we can more more in that direction. If you don't like something, we can change it.

### CODE REVIEW

**Comment by orta** [comment]
With them separated out you can also use these markdown files to generate a guides page on your website

**Comment by ashfurrow** [comment]
Updated docs for `add_git_tag` based on https://github.com/KrauseFx/fastlane/pull/175

**Comment by KrauseFx** [comment]
Hey Ash,

First off, thank you for working on this. It is super helpful and will help a lot of users.

Introducing the `/doc` directory is a great idea. I love how you improved and re-worked some poorly written sentences and code examples. 

The `Actions.md` is perfect! I love it :heart_eyes: 

I'd like to move the `fastlane Toolchain` entry from the `docs/README.md` to the project's README.

While you're at it, you can add a few links to `eidolon` as real world example setup :+1: 

Thanks again for working on this, really appreciated :rocket:

**Comment by ashfurrow** [comment]
Awesome, glad you feel it fits. Moving the fasten Toolchain back into the main README makes sense. I'll get it pushed up shortly.

**Comment by KrauseFx** [comment]
I think it's ready to merge, right? Anything missing from your side? :+1:

**Comment by ashfurrow** [comment]
All good to me!

**Comment by KrauseFx** [comment]
Thank you so much :+1:

**Pull request merged**
