### PR TITLE
[sigh] Fix entitlements merging when changing team while resigning

### PR DESCRIPTION
**Pull request by silvervest**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
These are the changes from https://github.com/fastlane/fastlane/pull/12131 updated to master and with merge conflicts resolved. Please see that issue for more in-depth detail.

### Testing Steps

supersedes #12131

### CODE REVIEW

**Comment by janpio** [comment]
Can you fix the CLA thing please @snatchev @joshdholtz?

**Comment by snatchev** [comment]
@janpio It looks like the commit was authored by `kapfab@github.somesite.net` who has not signed the CLA.

@silvervest needs to either amend the commit with `git commit --amend --author="Author Name <email@address.com>"` or (_I think_) reply to googlebot with "I consent."

**Comment by kapfab** [comment]
@googlebot I consent.

**Comment by janpio** [comment]
Thanks @snatchev, consent from @kapfab was already at https://github.com/fastlane/fastlane/pull/12131 so I hoped I could override the message here, but only you could - mentioning @kapfab solved the problem as well of course. (Thanks!)

**Comment by aklowther** [comment]
@kapfab @silvervest could this get some attention?  The changes look good to me  (as its impacting me right now :D )

**Comment by silvervest** [comment]
@janpio This was closed without merging - possible to reopen and give it some ❤️? We're still affected, and other users too it seems.

**Comment by janpio** [comment]
Closing was unintentional, sorry: https://github.com/fastlane/fastlane/issues/16048

You can always help us by trying and reviewing the code yourself and let us know if it does what you want it to.

**Comment by silvervest** [comment]
I can't seem to do any kind of formal review, Github notes review is required by reviewers with write access. I did however resolve the newly developed merge conflict so this is good to go again.

**Review by lyndsey-ferguson — APPROVED** [review]
Looks okay

**Review by aklowther — APPROVED** [review]

**Comment by silvervest** [comment]
I was debugging a different fastlane issue and completely forgot about this PR, and deleted my repo to fork it completely fresh.
I have since salvaged these changes in my fork, and resolved the conflicts for this, but the PR is stuck linked to an "unknown repository" now. This change should still go out however. Any ideas on how to fix this, or should I open a new PR and link to this one?

**Comment by lyndsey-ferguson** [comment]
You can pull down the patch from this PR and apply that to your local copy.

https://coderwall.com/p/6aw72a/creating-patch-from-github-pull-request

**Comment by silvervest** [comment]
I don't need the patch, I still had my local branch. However, this PR itself has unlinked from my repository in Github but I still would like to see this change merged.

**Comment by lyndsey-ferguson** [comment]
Oh right. Well, close this PR and link it to a new one? This one had already been approved so as long as they're the same, the process should be quicker (I would guess). 

I'm just a contributor and cannot speak to how quickly the actual maintainers of the repo respond.

**Comment by csc-EricWu** [comment]
No updates here?

**Comment by joshdholtz** [comment]
I will take a look at this tomorrow and see if I can get the merge conflict resolved 😊

**Comment by kapfab** [comment]
FYI @joshdholtz, I’ve merged the changes a few days ago (https://github.com/kapfab/fastlane/tree/resign_fixes) and successfully ran a few tests chaining team while resigning.

**Comment by silvervest** [comment]
Due to lost head branch, I've reopened this as #18713, which is up-to-date with master and has no merge conflicts.

**Pull request closed without merging**
