### PR TITLE
Add Action that updates the Info.plist so that the built app works with Good Dynamics

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
This action will update the plist so that the built application can be deployed and managed within BlackBerry's Good Dynamics Control Center for Enterprise Mobility Management.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @lyndsey-ferguson,
Thanks for your fastlane pull request, this looks great! 
We recently introduced the new [fastlane plugin system](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#create-your-own-plugin) that allows you to distribute and maintain your own plugins, and still be exposed to `fastlane` users. 
We'd love this new action to be a `fastlane` plugin so people who want to use it, can easily add it to their project.
Please let us know how the integration goes, and if you need any help getting up and running 🚀

**Comment by lyndsey-ferguson** [comment]
@KrauseFx so this should be converted to use the new fastlane plugin system? I have not looked at that yet.

**Comment by KrauseFx** [comment]
@lyndsey-ferguson Yes, that would be awesome. It's really easy to get started, update to the latest version of fastlane, and run `fastlane new_plugin` 👍 Follow the guide and copy over your new action

**Comment by lyndsey-ferguson** [comment]
@KrauseFx I am getting this error with an empty plug-in when I try and test it:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- fastlane/plugin/goodify_info_plist (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:271:in `block in load_plugins'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:263:in `each'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/plugins/plugin_manager.rb:263:in `load_plugins'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/commands_generator.rb:17:in `start'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/lyndsey.ferguson/.gems/gems/fastlane-1.94.1/bin/fastlane:5:in `<top (required)>'
	from /Users/lyndsey.ferguson/.gems/bin/fastlane:23:in `load'
	from /Users/lyndsey.ferguson/.gems/bin/fastlane:23:in `<main>'
```

**Comment by lyndsey-ferguson** [comment]
I had tried to create the plug-in by updating the action from my existing code, but I was getting that error in my project that I am using fastlane with (after adding the plug-in).

**Comment by lyndsey-ferguson** [comment]
@KrauseFx so, I created a default plugin and tried to add it an existing iOS repo that uses fastlane (successfully). When I try to run fastlane after adding the plugin, I get the above error. I would expect that an empty default plugin should just work.

**Comment by lyndsey-ferguson** [comment]
`ruby -v`: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

**Comment by lyndsey-ferguson** [comment]
It must be something with my setup. I ran `fastlane init` on a version of my iOS project that did not have fastlane setup. With a clean Fastfile and the plug-in, it starts up fine.

**Comment by KrauseFx** [comment]
An empty default plugin should just work, could you submit a new issue here, so we can discuss it there instead of this PR? 
We'll help you get all this up and running 👍

**Comment by lyndsey-ferguson** [comment]
Roger that, I tried repeating the steps of creating a simple fastlane enabled project and everything was working fine until I added the plugin

**Comment by lyndsey-ferguson** [comment]
@KrauseFx published my first [plugin](https://rubygems.org/gems/fastlane-plugin-goodify_info_plist/versions/0.1.0)!

**Comment by KrauseFx** [comment]
@lyndsey-ferguson This looks so great, thanks for publishing this as a plugin 👍 How was the process like for you?

**Comment by KrauseFx** [comment]
@lyndsey-ferguson Could you also provide the GitHub URL in your gemspec?

**Comment by lyndsey-ferguson** [comment]
The process was fairly simple, but it was not clear that I was to put the plugin into a git repo before performing the `rake release` steps. Perhaps either explain that in the plugin docs (plus the github url in the gemspec), or tell people, **read the RubyGems docs first**.

**Comment by lyndsey-ferguson** [comment]
Other than the hiccups, it was straightforward. Hopefully the people developing Good iOS apps will find this plugin useful (and drive more people to use Fastlane).

**Comment by KrauseFx** [comment]
@lyndsey-ferguson Great feedback, do you mind submitting a PR for this, or should we update the docs? 👍

**Comment by lyndsey-ferguson** [comment]
Sure, I can open up a PR

**Pull request closed without merging**
