### PR TITLE
[match] fix non-interactive shell password_ask loop

### PR DESCRIPTION
**Pull request by hjanuschka**
as discussed in: https://github.com/fastlane/fastlane/issues/7513

### CODE REVIEW

**Comment by lacostej** [comment]
I was aiming to test the following patch:

````
diff --git a/fastlane_core/lib/fastlane_core/itunes_transporter.rb b/fastlane_core/lib/fastlane_core/itunes_transporter.rb
index 79d73a8..56af7aa 100644
--- a/fastlane_core/lib/fastlane_core/itunes_transporter.rb
+++ b/fastlane_core/lib/fastlane_core/itunes_transporter.rb
@@ -103,7 +103,7 @@ module FastlaneCore
         if $1.include? "Your Apple ID or password was entered incorrectly" or
            $1.include? "This Apple ID has been locked for security reasons"
 
-          unless Helper.is_test?
+          if UI.interactive?
             CredentialsManager::AccountManager.new(user: @user).invalid_credentials
             UI.error("Please run this tool again to apply the new password")
           end
diff --git a/match/lib/match/change_password.rb b/match/lib/match/change_password.rb
index 929cce9..2b9b2e4 100644
--- a/match/lib/match/change_password.rb
+++ b/match/lib/match/change_password.rb
@@ -1,6 +1,7 @@
 module Match
   class ChangePassword
     def self.update(params: nil, from: nil, to: nil)
+      ensure_UI_interactive
       to ||= ChangePassword.ask_password(message: "New passphrase for Git Repo: ", confirm: false)
       from ||= ChangePassword.ask_password(message: "Old passphrase for Git Repo: ", confirm: true)
       GitHelper.clear_changes
@@ -13,6 +14,7 @@ module Match
     end
 
     def self.ask_password(message: "Passphrase for Git Repo: ", confirm: true)
+      ensure_UI_interactive
       loop do
         password = UI.password(message)
         if confirm
@@ -26,5 +28,10 @@ module Match
         UI.error("Passhprases differ. Try again")
       end
     end
+
+    private
+      def self.ensure_UI_interactive
+        raise "This code should only run in interactive mode" unless UI.interactive?
+      end
   end
 end
diff --git a/match/lib/match/encrypt.rb b/match/lib/match/encrypt.rb
index 2119284..8c74894 100644
--- a/match/lib/match/encrypt.rb
+++ b/match/lib/match/encrypt.rb
@@ -15,11 +15,15 @@ module Match
       end
 
       unless password
-        UI.important "Enter the passphrase that should be used to encrypt/decrypt your certificates"
-        UI.important "This passphrase is specific per repository and will be stored in your local keychain"
-        UI.important "Make sure to remember the password, as you'll need it when you run match on a different machine"
-        password = ChangePassword.ask_password(confirm: true)
-        store_password(git_url, password)
+        if !UI.interactive?
+          UI.error "No password found neither in environment nor in local keychain. Bailing out as in non interactive mode."
+        else
+          UI.important "Enter the passphrase that should be used to encrypt/decrypt your certificates"
+          UI.important "This passphrase is specific per repository and will be stored in your local keychain"
+          UI.important "Make sure to remember the password, as you'll need it when you run match on a different machine"
+          password = ChangePassword.ask_password(confirm: true)
+          store_password(git_url, password)
+        end
       end
 
       return password
diff --git a/spaceship/lib/spaceship/client.rb b/spaceship/lib/spaceship/client.rb
index 31cfb3b..7caf3b1 100644
--- a/spaceship/lib/spaceship/client.rb
+++ b/spaceship/lib/spaceship/client.rb
@@ -247,7 +247,7 @@ module Spaceship
       rescue InvalidUserCredentialsError => ex
         raise ex unless keychain_entry
 
-        if keychain_entry.invalid_credentials
+        if FastlaneCore::UI.interactive? && keychain_entry.invalid_credentials
           login(user)
         else
           puts "Please run this tool again to apply the new password"
```

But had problems with my test setup so didn't complete it yet. WDYT?

**Comment by KrauseFx** [comment]
👍

**Comment by lacostej** [comment]
Submitted as #7561

**Review by KrauseFx — CHANGES_REQUESTED** [review]
.

**Comment by hjanuschka** [comment]
@lacostej your PR looks nice too. i am ok with closing this one, what do you think @KrauseFx ?

**Comment by KrauseFx** [comment]
Sounds good to me :+1:

**Pull request closed without merging**
