### PR TITLE
[scan] Handle single scheme Xcode projects

### PR DESCRIPTION
**Pull request by 0xced**
- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)
- [x] #6555 is merged (and this PR is rebased)
- [x] A new version of `fastlane_core` is released

Single scheme projects are explained here: http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

With a single scheme project, it is possible that both `Scan.project.ios?` and `Scan.project.tvos?` return false even though iOS and tvOS are supported platforms for the project. So instead of detecting simulators if the project supposedly support iOS or tvOS, simulators are detected when the --device or --devices option is passed to scan.

### CODE REVIEW

**Comment by 0xced** [comment]
This PR is ready for review now that #6555 is merged and fastlane_core 0.53.0 is released.

**Review by ohayon — APPROVED** [review]
This looks great! 💯 Love the idea of having just one scheme!

**Comment by 0xced** [comment]
Oops, I just realised that there’s now a spurious warning when running scan on a multi-scheme project. For example:

```
$ scan --project "AFNetworking.xcodeproj" --scheme "AFNetworking iOS"
[21:04:37]: $ xcodebuild -list -project AFNetworking.xcodeproj
[21:04:38]: $ xcodebuild clean -showBuildSettings -scheme AFNetworking\ iOS -project AFNetworking.xcodeproj
[21:04:39]: Couldn't find any matching simulators for '[]' - falling back to default simulator
[21:04:39]: Found simulator "iPhone 5s (10.0)"
```

Will try to fix that and submit a new PR.

**Comment by ohwutup** [comment]
Thanks @0xced, I noticed that warning too when I was testing, and didn't want it to block merging this as it ends up working as expected. Would be great if you could fix that up though! 🚀

**Comment by 0xced** [comment]
Actually, that warning was already emitted before merging this pull request. I will still have a look.

**Pull request merged**
