### PR TITLE
Update AvailablePlugins.md

### PR DESCRIPTION
**Pull request by joshrlesch**
Adding `upload_to_onesky` plugin to the list, and adding a hyperlink for `instrumented_tests` plugin

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @joshrlesch, thanks for the PR. Please add the URL to https://github.com/joshrlesch/fastlane-plugin-instrumented_tests/blob/master/fastlane-plugin-instrumented_tests.gemspec#L13 instead of directly here, it will automatically be updated in the AvailablePlugins.md based on that 👍 
I'll close this PR, just ping me when you did a new release with the updated gemspec 🚀

**Comment by joshrlesch** [comment]
Thanks for the heads up @KrauseFx. I updated that line in both of my plugins and created a new release for both of them. Keep up the good work my man!

**Comment by KrauseFx** [comment]
Awesome, thanks for the quick action @joshrlesch 🚀

**Comment by joshrlesch** [comment]
is there anything I need to do to update the `avaliablePlugins.md` file? Not sure the process with this.

**Comment by KrauseFx** [comment]
@joshrlesch We'll update it regularly, your plugin will be in the next train 👍

**Comment by joshrlesch** [comment]
Oh nice, thanks for the heads up

**Pull request closed without merging**
