### PR TITLE
[action] add SonarQube pull request parameters to sonar

### LINKED ISSUE #15068: [sonar] Add Pull Request parameters
#### Motivation Behind Feature
At my current company (& for my side job too), I'm currently using **fastlane** for most of the mobile projects (iOS / Android) and we've just finished integrating our own **SonarQube** instance.

In order to get **Pull Request** decoration and code coverage differences between the base branch and the targeted one, we need to pass three more parameters to the scanner script.

#### Feature Description

From the official documentation of **SonarQube**, the three parameters can be found in the `Analysis Parameters` section.

#### Alternatives or Workarounds
Workaround to include those parameters is to bypass **fastlane** by using our CI configuration file and perform the call to `sonnar-scanner` ourself.

### PR DESCRIPTION
**Pull request by damien-rivet**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This PR implements and closes #15068.

As explained in the linked issue, using the currently available parameters of the `sonar` action is limited in term of PR management from **SonarQube**.

This PR goal is to add the missing parameters that would allow for relevant code coverage comparison between branches.

### Description
This PR add three new parameters to the `sonar` action.

Those parameters can be used to allow **SonarQube** to perform code coverage differentiation between the base branch and the targeted branch.

### CODE REVIEW

**Comment by Ethenyl** [comment]
I signed it!

**Comment by janpio** [comment]
Awesome.

I know https://github.com/fastlane/fastlane/blob/master/fastlane/spec/actions_specs/sonar_spec.rb is pretty basic right now, but can you maybe add some tests for these new params?

**Comment by Ethenyl** [comment]
@janpio I'll look into the test file to see what can be done, since it's my first contribution to the project I didn't notice the test file.

**Comment by janpio** [comment]
Yeah, as this is really barebones you'll probably have to look around a bit through the other test files to find something that tests the generated command of an external tool that is being triggered (hint: during tests `sh` doesn't actually execute the command, but just return the generated one so we can compare strings).

**Comment by Ethenyl** [comment]
@janpio I've added a new unit test to check for the parameters (thanks `slather`).

I'm sorry but my current **Ruby** knowledge won't allow me to do better than that for the moment...

**Comment by Ethenyl** [comment]
Hi @janpio,

I've fixed all the code issues (wow that was a lot of security checks, but worth it).

The PR should be cleared for review now ;-)

**Comment by janpio** [comment]
Ha yeah, our rules are pretty tight there - but makes it easier to not have to discuss the small things.

**Review by joshdholtz — APPROVED** [review]
Looks good! I added a commit to remove the `Fastlane.swift` changes (those get automatically created when a new version of _fastlane_ is released so no need to do it 😊). And thanks for this contribution! ❤️

**Comment by Ethenyl** [comment]
@joshdholtz thanks for the update :D I was worried I did something wrong and the whole PR would be declined.

**Pull request merged**
