### PR TITLE
Use all commits instead of current HEAD in `number_of_commits`.

### LINKED ISSUE #5376: number_of_commits issue when using branches
Would number_of_commits be better using `git rev-list --all --count` rather than `git rev-list HEAD --count`?

I find the current version does not work so well when using branches.

### PR DESCRIPTION
**Pull request by samuelbeek**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description
Fixes https://github.com/fastlane/fastlane/issues/5376. 

### Motivation and Context
The documentation described the `number_of_commits` command as `The total number of all commits in current git repo`. But it was the total number of commits on the current branch. This PR fixes that.

### CODE REVIEW

**Comment by samuelbeek** [comment]
I signed it!

**Comment by mfurtak** [comment]
I think changing the behavior of the action isn't something we can do at this point, as some number of people are likely already dependent on it. Would it make sense to correct the documentation instead?

**Comment by KrauseFx** [comment]
I agree with @mfurtak, adding a parameter to this action might be a good idea. The key is to not change any default behavior, which would break existing setups.

**Comment by samuelbeek** [comment]
That makes sense, I will update my PR accordingly.

**Review by hjanuschka — CHANGES_REQUESTED** [review]
can you please add the `available_options` method to the action with the `:all` option listed?

`optional` => `true`
`is_string` => `false`

example:
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/adb.rb#L27

**Comment by samuelbeek** [comment]
@hjanuschka thanks for the comments, it's fixed now!

**Review by hjanuschka — APPROVED** [review]

**Comment by hjanuschka** [comment]
@samuelbeek  many thx.


tested with:
`fastlane run number_of_commits` (expected behaviour on current users)
results in: `git rev-list HEAD --count`


`fastlane run number_of_commits all:true`
results in: `git rev-list --all --count`


many thx for your contribution 🚀

**Pull request merged**
