### PR TITLE
Added initial danger integration

### PR DESCRIPTION
**Pull request by KrauseFx**
cc @orta

### CODE REVIEW

**Comment by orta** [comment]
Hrm, this should have triggered:

```
if pr_body.length < 5
  warn "Please provide a changelog summary in the Pull Request description @#{pr_author}"
end
```

**Comment by KrauseFx** [comment]
:rocket:

**Comment by KrauseFx** [comment]
Ready to merge?

**Comment by orta** [comment]
Do it

**Comment by ohwutup** [comment]
:+1:

**Comment by KrauseFx** [comment]
`danger` all the things :rocket:

**Pull request merged**
