### PR TITLE
pilot add support for app description and feedback email

### PR DESCRIPTION
**Pull request by Jossif**
pass _TestFlight app description_ as `-d` and _feedback email_ as `-n` when running `pilot`
Mentioned in: #1882

### CODE REVIEW

**Comment by KrauseFx** [comment]
This is a great PR, thanks @Jossif. Could you rebase from master, so that the last styling issue gets resolved? 

Looking at the code, does it work to call `update_build_information!` multiple times with different key values each time? 
I have the feeling we should call this method only once with all the values at the same time 👍

**Comment by hjanuschka** [comment]
@KrauseFx i think this is done with: https://github.com/fastlane/fastlane/pull/6435

**Comment by KrauseFx** [comment]
Nice catch @hjanuschka 👍  However the other PR didn't add the feedback_email. Either way, I'm gonna close this PR for now, thanks 👍

**Comment by hjanuschka** [comment]
@KrauseFx  done with https://github.com/fastlane/fastlane/pull/6550 💥

**Comment by KrauseFx** [comment]
💥  nice!!!

**Comment by youngrafi** [comment]
When is release expected for this?

**Comment by KrauseFx** [comment]
Preparing one now 👍

**Pull request closed without merging**
