### PR TITLE
[scan] Add support for disabling "KeyboardContinuousPathEnabled"

### PR DESCRIPTION
**Pull request by AlexTrott**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

With the release of iOS 13, newly recreated/reset simulators all have "Slide to type" enabled by default.
This new functionality now causes an issue when executing XCUITest via `scan` which interact with textfields. As they will see the following screen when interacting with the UITextField for the first time.

Screen Shot 2019-11-30 at 4 42 32 PM

This will then cause the XCUITest to fail, due to the inability to interact with the keyboard.

### Description

This change adds a new config option for scan,`SCAN_DISABLE_SLIDE_TO_TYPE` this is disabled by default, to revert back the keyboard behavior of a clean simulator.

**Resolves:** https://github.com/fastlane/fastlane/issues/15742

### Testing Steps

Testing in the following project: 
https://github.com/AlexTrott/Fastlane-iOS13-TextField-test

Test:
```
  desc "Test: Fastlane sets the default param, so the user has to do nothing"
  lane :test_default_param do
    scan(
      reset_simulator: true,
      disable_slide_to_type: true
    )
  end

  desc "Test: Fastlane responds when the user inputs the same selection as the default param"
  lane :test_setting_param do
    scan(
      reset_simulator: true,
      disable_slide_to_type: true
    )
  end

  desc "Test: Fastlane responds when the user sets the property to false"
  lane :test_which_will_fail do
    # This test will fail, as the 'Slide to Type' prompt is shown
    scan(
      reset_simulator: true,
      disable_slide_to_type: false
    )
  end
```

### CODE REVIEW

**Comment by AlexTrott** [comment]
@googlebot I signed it!

**Review by jaleksynas — APPROVED** [review]
This looks good to me.

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This is 🔥 And thank you sooooo much for providing that sample project. That sped up my testing process so much 😊 I added one commit to add some conditional checking to make sure that this is an iOS simulator running 13.0 or greater and some tests. Thanks so much for this contribution ❤️

**Pull request merged**
