### PR TITLE
supply: Add support for apk superseded

### LINKED ISSUE #6791: Google Play Store APK version code conflicts between tracks...
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

**TLDR->** I expect APK's with a higher versionCode to automatically deactivate versions in preceding tracks with a lower versionCode.

S'pose the APK in Alpha has versionCode 1. I want to upload a new version to Beta with versionCode 2. 

When I try to do this I get the following error:

_Version 2 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes._

I understand the reasoning behind this error, but this is not the expected behavior as described by the [Google documentation](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en):
- _If a beta APK is uploaded with a higher version code than an alpha APK, the alpha version will automatically be deactivated._
- _If a Production APK is uploaded with a higher version code than an alpha or beta APK, the alpha and/or beta version will automatically be deactivated._

What I expect is the Alpha track with versionCode 1 to automatically be deactivated and the new APK with version 2 to be uploaded to the Beta track. This logic also applies to the Production track, where any version uploaded to the Production track with a higher version code than the versions that are in Beta and Alpha should automatically disable those tracks.
##### Complete output when running fastlane, including the stack trace and command used

```

+-------------------------+--------------------------------------------------------------------+
|                                   Summary for supply 0.7.1                                   |
+-------------------------+--------------------------------------------------------------------+
| track                   | beta                                                               |
| skip_upload_images      | true                                                               |
| skip_upload_screenshots | true                                                               |
| apk                     | /home/ubuntu/sw-android/app/build/outputs/apk/app-prod-release.apk |
| package_name            | com.shaleapps.logistics                                            |
| rollout                 | 1.0                                                                |
| metadata_path           | ./fastlane/metadata/android                                        |
| json_key                | key.json                                                           |
| skip_upload_apk         | false                                                              |
| skip_upload_metadata    | false                                                              |
+-------------------------+--------------------------------------------------------------------+

[20:54:12]: Preparing to upload for language 'en-US'...
[20:54:13]: Updating changelog for code version '39' and language 'en-US'...
[20:54:13]: Updating changelog for code version '40' and language 'en-US'...
[20:54:13]: Updating changelog for code version '41' and language 'en-US'...
[20:54:14]: Updating changelog for code version '42' and language 'en-US'...
[20:54:14]: Updating changelog for code version '43' and language 'en-US'...
[20:54:14]: Updating changelog for code version '44' and language 'en-US'...
[20:54:14]: Updating changelog for code version '45' and language 'en-US'...
[20:54:14]: Updating changelog for code version '46' and language 'en-US'...
[20:54:15]: Updating changelog for code version '47' and language 'en-US'...
[20:54:15]: Updating changelog for code version '56' and language 'en-US'...
[20:54:15]: Updating changelog for code version '57' and language 'en-US'...
[20:54:16]: Updating changelog for code version '920' and language 'en-US'...
[20:54:16]: Updating changelog for code version '923' and language 'en-US'...
[20:54:17]: Updating changelog for code version '931' and language 'en-US'...
[20:54:17]: Updating changelog for code version '1002' and language 'en-US'...
[20:54:17]: Preparing apk at path '/home/ubuntu/sw-android/app/build/outputs/apk/app-prod-release.apk' for upload...
[20:54:20]: Updating track 'beta'...
[20:54:20]: Uploading all changes to Google Play...
[20:54:21]: Variable Dump:
[20:54:21]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta", :GRADLE_BUILD_TYPE=>"release", :GRADLE_FLAVOR=>"prod", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/home/ubuntu/sw-android/app/build/outputs/apk/app-prod-release.apk"], :GRADLE_APK_OUTPUT_PATH=>"/home/ubuntu/sw-android/app/build/outputs/apk/app-prod-release.apk"}
[20:54:21]: Google Api Error: multiApkShadowedActiveApk: Version 1123 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 28          |
| 4    | gradle                              | 171         |
| 💥    | supply                              | 9           |
+------+-------------------------------------+-------------+

[20:54:21]: fastlane finished with errors

[!] Google Api Error: multiApkShadowedActiveApk: Version 1123 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.

fastlane beta returned exit code 1

Action failed: fastlane beta
```

### PR DESCRIPTION
**Pull request by capyvara**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context
Trying to fix #6791

### Description
Before uploading a new apk, some update_track's are issued to clean outdated apk versions, following the rules:
- Remove any version codes that is lesser than the greatest of any later (i.e. production) track 
  - Ex: v4 being uploaded to alpha, production has v3, beta has v2, alpha is empty: v2 will be removed from beta, v4 will be added at alpha
- Also remove any version codes that is lesser than the currently being uploaded if it's in an earlier (i.e. alpha) track
  - Ex: v4 being uploaded to beta, production has v2, beta is empty, alpha has v3: v3 will be removed from alpha, v4 will be added at beta

I never touched any ruby code before, so if any rubyist can review this it will be great.

### CODE REVIEW

**Comment by Capyvara** [comment]
I signed it!

**Review by felipeplets — APPROVED** [review]
I was looking for this solution myself. I've checked @Capyvara PR and it seems good!

**Review by jhilden — APPROVED** [review]
worked for us as well, thank you very much :green_heart:

**Comment by ndbroadbent** [comment]
Thanks!! I just ran into this when I had an alpha version that was "superseded by production", and I tried directly pushing to the production track.

**Comment by Capyvara** [comment]
I did some cleanup refactoring and added a --check_superseded_tracks command line option, so users need to opt-in using the feature (principle of least surprise).

**Review by hjanuschka — APPROVED** [review]
@Capyvara  🚀  looking good. many thx for your work!
@mfurtak you can look at it too (as requested by @ohayon )

**Comment by mfurtak** [comment]
This seems great, but I will need a little time before I can fully review it. Thanks for your patience!

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
Thanks for this improvement! 🚀

**Pull request merged**
