### PR TITLE
[action] fix a type error in the Swift setupCi action.

### PR DESCRIPTION
**Pull request by IngmarStein**
`provider` should be an optional String, not a Bool. This fixes the following error when using the action:

```
[!] 'provider' value must be a String! Found FalseClass instead.
```

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Review by janpio — CHANGES_REQUESTED** [review]
As far as I know `Fastlane.swift` is auto generated - to fix this the underlying ruby action has to be fixed.

**Comment by IngmarStein** [comment]
I missed that `Fastlane.swift` is autogenerated, so I fixed the underlying Ruby action. Looks like the generated file picked up some unrelated changes.

**Comment by janpio** [comment]
Thanks, that looks good now.

Unfortunately I do not know enough about the Swift part to be able to confirm if the unrelated changes are a problem - we'll have to wait for someone else to approve here.

**Comment by IngmarStein** [comment]
Regarding the other changes: noCache was only added in #16132 and it was probably forgotten to generate the Swift file after making the change.
The metadataPath argument doesn't seem to have a default value: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/download_from_play_store.rb#L32

**Comment by joshdholtz** [comment]
@IngmarStein The swift file gets generated automatically so I'm not going to include those changes in this PR but I will look into those discrepancies that you found 🤔

**Comment by IngmarStein** [comment]
@joshdholtz this PR also includes the necessary changes to the Ruby action (`setup_ci.rb`), not just the generated Swift API. Am I missing something?

**Comment by joshdholtz** [comment]
@IngmarStein Yup yup, we'll be keeping the changes in `setup_ci.rb` 😊 We will just remove the changes to the `.swift` files since those are autogenerated

**Comment by IngmarStein** [comment]
@joshdholtz Ah, sure thing. In that case, I've just removed those changes from this PR to make it mergeable.

**Review by joshdholtz — APPROVED** [review]
This makes so much sense 😊 Thanks for catching this! Appreciate the contribution ❤️

**Pull request merged**
