### PR TITLE
Fix git-branch crash if no ENV vars present

### PR DESCRIPTION
**Pull request by mfurtak**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

Fix a crash in the `git_branch` action that happens if no Git branch indicating ENV vars are present.

### Motivation and Context

```
/Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/git_branch.rb:10:in `fetch': [!] no implicit conversion of nil into String (TypeError)
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/git_branch.rb:10:in `run'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/one_off.rb:41:in `run'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:192:in `block (2 levels) in run'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
	from /Users/mfurtak/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.17.1/bin/fastlane:15:in `<top (required)>'
	from /Users/mfurtak/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/mfurtak/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

### CODE REVIEW

**Review by asfalcone — APPROVED** [review]
It might be good to add a test for the empty string case? Otherwise 👍

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Fastlane::Action git_branch description | <a href='https://github.com/fastlane/fastlane/blob/c32038439fa5f9eab30e58fd0f226419c3449e4c/./fastlane/spec/action_metadata_spec.rb'>action_metadata_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mfurtak** [comment]
Yeah, it's a good thought. 👍  I considered it, but it would wind up being pretty artificial. Empty string is the return value of 

```ruby
`git symbolic-ref HEAD --short 2>/dev/null`.strip
```

which I need to mock out to return whatever I need anyhow. So, basically I'd be asserting that my mocked call returned what I told it to.

**Comment by cooksimo** [comment]
Will there be a release for this? Currently causing all our builds to crash.

**Comment by mfurtak** [comment]
Yes, I'll do a hotfix release ASAP

**Comment by mfurtak** [comment]
[_fastlane_ 2.18.1](https://github.com/fastlane/fastlane/releases/tag/2.18.1) has gone out with a fix. Please let me know if it works for you 🚀

**Pull request merged**
