### PR TITLE
Clean up _pilot_ maintenance mode message to better reflect reality

### PR DESCRIPTION
**Pull request by mpirri**

### CODE REVIEW

**Comment by mpirri** [comment]
Old and busted:
image

New hotness:
image

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @mpirri</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by snatchev — APPROVED** [review]
🚢

**Comment by KrauseFx** [comment]
Should we mention that people should submit issues if they run into problems? This way we learn more about the things that don't work @mpirri @snatchev

**Comment by mpirri** [comment]
@KrauseFx How about this?  https://github.com/fastlane/fastlane/pull/8966

**Pull request merged**
