### PR TITLE
spaceship: fix flaky test. Not all sampled provisioningProfile for xcode seem to have a managingApp field

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Comment by mfurtak** [comment]
@snatchev Is this related to #8359?

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
I'm going to put this through for now, since people's new PRs are getting hung up on it 👍

**Comment by ohayon** [comment]
This test is still failing on my machine.  But passed for my PR https://github.com/fastlane/fastlane/pull/8397.

**Comment by ohayon** [comment]
This is sorted out, I was not using `bundle exec` to run `rspec`.

**Comment by snatchev** [comment]
@lacostej thanks for catching this. I had not realized that some of the profile entries might be missing a key.

**Pull request merged**
