### PR TITLE
[spaceship] Support manual app release

### PR DESCRIPTION
**Pull request by valerio-castelli**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR adds support for `appStoreVersionReleaseRequests`, enabling fastlane users to release an app update that has been approved by Apple and for which the release type is set to manual release.

### Description

The PR adds a new `AppStoreVersionReleaseRequest` model to the App Store Connect API interface and a dedicated `create_app_store_version_release_request` method in the `AppStoreVersion` model.

### Testing Steps

I've written two unit tests to cover the new logic of the Connect API Tunes client and the expected API response. They can be run individually as follows:
```
bundle exec rspec ./spaceship/spec/connect_api/models/app_store_version_release_request_spec.rb
bundle exec rspec ./spaceship/spec/connect_api/tunes/tunes_client_spec.rb
```

### CODE REVIEW

**Comment by joshdholtz** [comment]
@valerio-castelli Hey 👋 This is amazing! Can you sign the CLA so that we can get this merged in? 😊

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thank you so much for adding the associated tests 😍 Just need the CLA to be accepted and then we should be good to merge!

**Comment by valerio-castelli** [comment]
Hi @joshdholtz, sure! The company I'm working for is currently reviewing the CLA, we should be good to go in a few hours 🙂 
In the meantime, I took the occasion to test the code live with one of our apps and I confirm it works. 🎉

**Comment by joshdholtz** [comment]
@valerio-castelli Heyyy! Just wanted to check in with you to see if you knew that status of the CLA 😇 I don’t want to rush it but I am working on getting a new build out tonight and wanted to include this if possible 😊

**Comment by valerio-castelli** [comment]
I'm sorry @joshdholtz, we're a bit late 🙁 Our legal team just gave the green light and we're now waiting to receive the CLA agreement from Google, which is going to be signed soon by our legal representative. 

We hope everything will be signed by tomorrow, I'll keep you posted 🙏

**Comment by joshdholtz** [comment]
❤️ Thank you for the update!

**Comment by valerio-castelli** [comment]
@googlebot I signed it!

**Comment by valerio-castelli** [comment]
@googlebot I signed it!

**Comment by valerio-castelli** [comment]
I'm not sure if I have to do something else, as Google Bot doesn't seem to have picked up the CLA change. Since this is a corporate submission, what we did so far is: 

1. Create a Google Group within our GSuite organization for open source contributions
2. Add my contributor email to that group
3. Ask our legal team to fill the details for the corporate CLA submission
4. Submit the signed CLA agreement
5. Reply to Google Bot that we signed the agreement

However, the status of the Google comment hasn't changed, and Google reports that they have no individual agreement on file for me. I'm troubleshooting this with our legal team 🤞

**Comment by valerio-castelli** [comment]
@googlebot I signed it!

**Comment by valerio-castelli** [comment]
@googlebot I fixed it.

**Comment by valerio-castelli** [comment]
@joshdholtz Sorry for the long wait, we're finally good to go. 🎉

**Comment by joshdholtz** [comment]
@valerio-castelli Thank you!! So excited to have this released 😊

**Comment by iliao58** [comment]
@valerio-castelli Does this change work for phased release as well? so when phased release has been chosen,  will calling `post_app_store_version_release_request` start the phased release? In addition, when phased release is in process, will calling `post_app_store_version_release_request` immediately phased release to all users?

**Comment by joshdholtz** [comment]
@iliao58 That is a great question! I would _assume_ so but I don't have anything in that state to know for sure 😔 

@valerio-castelli Would you happen to know? 😇

**Comment by iliao58** [comment]
@joshdholtz I haven't tested with this API yet, but I don't think it would work. By going through the source, 
```
releaseToAllUsers: function() {
    return function(e, t) {
        var n = t(),
            r = Object(y.o)(n.storeVersions);
        e(Object(_.a)(g.nc, {
            providerOps: {
                versionId: r
            },
            attributes: {
                phasedReleaseState: v.b
            }
        }))
    }
}
```
it is patching the phasedReleaseState. Can you add support for this? Thanks.

**Comment by joshdholtz** [comment]
@iliao58 Can do! You mind creating a discussion over at https://github.com/fastlane/fastlane/discussions for this? I’m not able to get to this right away but I’d love to track it and then report back to you there when its done 😊

**Pull request merged**
