### PR TITLE
[Ready] Updated cache path

### PR DESCRIPTION
**Pull request by KrauseFx**
Saving 1-2 minutes on each run now

### CODE REVIEW

**Comment by jeeftor** [comment]
Is it possible that the changes you have here are causing my PR #3904 to fail?

**Comment by KrauseFx** [comment]
It shouldn't be related, as this is a separate branch + PR, but I'll investigate

**Comment by mfurtak** [comment]
Sweet! :+1:

**Comment by KrauseFx** [comment]
:rocket:

**Pull request merged**
