### PR TITLE
[WIP] Add Core Parts for Events in fastlane

### PR DESCRIPTION
**Pull request by hjanuschka**
as there seems to be a demand for a bit more details of current running actions. (like: https://github.com/fastlane/fastlane/issues/8977) - but providing lambda's on all actions is not generic enough and may confuse "non-expert" users.

here is my try to implement a "easy" interface.

test (can be in fastfile or in a plugin 👍 ):

```ruby
class MyFirstReceiver
  def event_receiver(event)
    puts "#{event.inspect}"
  end
end

Fastlane::PluginEventManager.subscribe(MyFirstReceiver.new)
```

once the manager is available we could start adding hooks on various actions/tools - to fire events like.:

```ruby
  Fastlane::PluginEventManager.publish("category", {payload: 123})
```

the final idea is that plugins can hook into events.
like registering a receiver in the main plugin rb (e.g: https://github.com/hjanuschka/fastlane-plugin-aws_device_farm/blob/master/lib/fastlane/plugin/aws_device_farm.rb#L12)

let me know what you think.

example Events:

## Fastlane

|  Event  |  Payload  |
|--------|----------|
|  action_started  |  actionInstance, timestamp   |
|  action_finished  |  timestamp, actionInstance  |
| started  |  timstamp |
| finished  |  timestamp  |
| plugins_loaded  |  Plugin list  |

## Gym

|  Event  |  Payload  |
|--------|----------|
|  build_started  |  timestamp, app_id, project_folder  |
|  build_finished  |  timestamp, app_id, project_folder, ipa-path  |
| archive_started  |  timestamp, app_id, project_folder  |
| archive_finished  |  timestamp, app_id, project_folder  |

## Pilot

|  Event  |  Payload  |
|--------|----------|
|  upload_started  |  timestamp, app_id, project_folder, build  |
|  build_started_processing  |  build |
| build_finished_processing  |  build  |
| build_submitted  |  build  |

## Match

|  Event  |  Payload  |
|--------|----------|
|  repo_cloned  |  repo_url, repo_path  |
|  repo_crypted  |  repo_path, repo_url |
| repo_decrypted  |  repo_path, repo_url  |
| profile_valid  |  profile  |
| profile_invalid  |  profile  |
| profile_created  |  profile  |

and so on, i  think that in almost all actions/tools we could have atleast a couple of events.
this should improve/extend plugins et-all.

actions could also publish a event providing the number of events that will follow, and later on one could do a progress bar (like the slack_train thing)

TODO:
  - [ ] add specs
  - [ ] add hooks to tools
  - [ ] provide sample plugin working with hooks

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @hjanuschka, could you provide some more example on how this would work in action? Thanks 👍

**Comment by hjanuschka** [comment]
@KrauseFx added a few samples!

**Comment by lyndsey-ferguson** [comment]
Very cool!

**Comment by ohayon** [comment]
This is really cool @hjanuschka. We know you are totally busy now with the 👶  but whenever you are free we should have some conversation about what it would take to get this to move forward! 🚀

**Comment by ohayon** [comment]
Chatted with @hjanuschka offline about this. We are going to close it for now and reopen when he has time to get back to work on it! 😄 🚀

**Pull request closed without merging**
