### PR TITLE
Add 'associated_groups' attribute to Spaceship::Portal::App

### PR DESCRIPTION
**Pull request by xai3**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

`getAppIdDetail.action` API returns the `associatedApplicationGroups` element.
So I added the `associated_groups` attribute to `Spaceship::Portal::App` class.

### Motivation and Context

#8508 
#8143

### CODE REVIEW

**Comment by yukiasai** [comment]
I signed it!

**Review by hjanuschka — APPROVED** [review]

**Comment by hjanuschka** [comment]
thx - cool PR 🚀

**Comment by nafu** [comment]
@yukiasai @hjanuschka 🚀

**Comment by yukiasai** [comment]
@hjanuschka @nafu thank you for reviewing 👍

**Pull request merged**
