### PR TITLE
#6279: Move from sonar-runner to sonar-scanner

### PR DESCRIPTION
**Pull request by giacgbj**
Related to #6279.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for your contribution, this looks great, however we can't just break the API of the action. Could you revert the changes of the public API? 👍

**Comment by giacgbj** [comment]
I mainly created this pull request to avoid the warning, and I know it can be done without breaking the public API.
However I think that sooner or later the public API should be changed to align everything to the new name in order to avoid confusion.
I'm going to revert those changes.

**Comment by KrauseFx** [comment]
The tests seem to be failing

**Comment by giacgbj** [comment]
Fixed.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
This is great, thanks for your contribution @giacgbj, this will be in the next release 🚀

**Pull request merged**
