### PR TITLE
[frameit] [frames_generator] update for iPhone 14

### PR DESCRIPTION
**Pull request by guidev**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Update for iPhone 14 

depends on https://github.com/fastlane/frameit-frames/pull/31

### CODE REVIEW

**Comment by getaaron** [comment]
@guidev same on this PR, you need to auth with CircleCI and rebuild so the checks run

**Comment by guidev** [comment]
Hi @getaaron, this is what I see... Am I missing something?
Screenshot 2022-12-14 at 15 38 36

**Comment by nickkaczmarek** [comment]
Can't wait to see this get merged. Thanks @guidev and @getaaron

**Comment by schulzp** [comment]
Hi! Thanks for the great work! I highly appreciate it. 🙏🏻  Any chance, this PR could get reviewed (and merged)?

**Comment by barringb** [comment]
Bump, hoping for iPhone 14 support for app store 🙏

**Review by Damien-B — APPROVED** [review]

**Comment by Damien-B** [comment]
Waiting for the review and merge as well.
@guidev you might want to add some reviewers to this PR

**Comment by DigitalRogues** [comment]
With the iPhone 15 normally coming out in a couple months it’d sure be nice to get support for the iPhone 14 that’s been out for almost a year.

**Review by ricsantos — APPROVED** [review]
LGTM

**Comment by ricsantos** [comment]
@joshdholtz would you be able to have a quick peek at this? needs a review to get merged, would be great to have support for the dynamic island screenshots...

**Comment by andreialecu** [comment]
@joshdholtz version 2.217.0 says that support for iPhone 14 devices has been added, but only the images are added. `device_types.rb` doesn't seem to have been updated. I believe this PR also needs to be merged and a new release cut.

I'm still getting `[09:56:37]: Unsupported screen size [1290, 2796] for path './en-US/iPhone 15 Pro Max - 1 - Home.png'` otherwise.

Note how iPhone 14 is missing here: https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/device_types.rb#L131-L137

**Comment by dahchon** [comment]
> @joshdholtz version 2.217.0 says that support for iPhone 14 devices has been added, but only the images are added. `device_types.rb` doesn't seem to have been updated. I believe this PR also needs to be merged and a new release cut.
> 
> I'm still getting `[09:56:37]: Unsupported screen size [1290, 2796] for path './en-US/iPhone 15 Pro Max - 1 - Home.png'` otherwise.
> 
> Note how iPhone 14 is missing here: https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/device_types.rb#L131-L137

Same here. We need this PR. 
There could be small fixes needed because I'm getting black screens.

**Comment by sathoeni** [comment]
IMHO the current device size for an iPhone 14 Pro is not correct in the current master of https://github.com/fastlane/frameit-frames/ 


Therefore I've created a pull-request with the correct frame size
I've also adapted the logic of framing, to apply rounded corners when framing an iPhone 14.

Maybe you can try follow fastlane-branch that links to a corresponding frame-it/frames repo that matches the correct iPhone 14 Pro size
https://github.com/sathoeni/fastlane/tree/customFrames

If you are fine with the implementation we can close all other pull requests and hopefully it's getting merged

**Review by getaaron — APPROVED** [review]

**Comment by sathoeni** [comment]
> @guidev can you please commit my two suggestions or give me write permission to your branch? Then I'll merge this.

@getaaron You shoul merge following pull request, it contains everything of this one and even more, like the rounded corners and correct frame size

https://github.com/fastlane/fastlane/pull/21727

**Pull request closed without merging**
