### PR TITLE
testflight - added method to find internal users

### PR DESCRIPTION
**Pull request by RishabhTayal**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
This is followup pull request after discussing with @joshdholtz. Fixes issue https://github.com/fastlane/fastlane/issues/12750.

Added new method `internal_users` to get the internal users from App Store Connect.

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Can we get some tests written for this new method? 😊

**Comment by RishabhTayal** [comment]
@joshdholtz could you please help me look into the test case. Why it's failing?

**Comment by heartofagoof** [comment]
@RishabhTayal You need to set a response json with "data" key in it. That is what parse_response expects. So changing your line 166 - where you set the stubbing to 

```ruby
 MockAPI::TestFlightServer.get('/testflight/v2/providers/fake-team-id/apps/some-app-id/internalUsers') { '{"data" : ""}' }
```

instead of 

```ruby
 MockAPI::TestFlightServer.get('/testflight/v2/providers/fake-team-id/apps/some-app-id/internalUsers') { }
```
would do the trick.

However, I do see that you are not parsing this data into any object - if you just need the itunesconnect users for a particular team may be you can use the `all` method of `spaceship/lib/spaceship/tunes/members.rb` class?

**Comment by RishabhTayal** [comment]
@heartofagoof Awesome. That does it. Now the test case are passing. 

Ready for review now. ✅

**Review by joshdholtz — APPROVED** [review]
Looks good! 👍

**Pull request merged**
