### PR TITLE
Deprecate Badge action in favor of the plugin

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @ohayon</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
Should we slowly deprecate it, instead of failing the build?

**Comment by KrauseFx** [comment]
This seems like an action that might be widely used, and if someone hasn't used fastlane the last 2 months and now tries it again, it fails because of  API changes, so they need to update fastlane, with that removing the `badge` action, and therefore failing the build.

**Comment by ohayon** [comment]
Yeah, I agree that it would be best and I'm happy to deprecate it more gracefully, my motivation to do it this was was that the plugin is up to date, and this action is not, so all of the functionality is not in the action.

**Comment by KrauseFx** [comment]
Sounds good. Our first priority should probably be to keep the builds green in this case, and show warnings to move people over to the plugin 👍

**Review by taquitos — APPROVED** [review]
This looks 💯 🐐 to me

**Pull request merged**
