### PR TITLE
Version bump to 2.83.0

### PR DESCRIPTION
**Pull request by KrauseFx**
Auto-generated by fastlane 🤖

**Changes since release '2.82.0':**

* Improve actions default values formatting (#11919) via Iulian Onofrei
* Fix for regression #11917 (#11918) via Jorge
* Cache groups by app_id (#11911) via Joshua Liebowitz
* Add @minuscorp and @AndrewMcBurney to fastlane team (#11908) via Felix Krause

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
🎈🐐
linter error, but not blocking.

**Comment by janpio** [comment]
too many contributors 💯

**Comment by squeeish** [comment]
Hi guys, if it's not too selfish, is it possible to ship this immediately? The regression #11917 breaks the aws s3 plugin I use daily. :)

**Comment by taquitos** [comment]
@squeeish we did a release this morning so you should update your fastlane gem.
Also, if you're using https://github.com/joshdholtz/fastlane-plugin-s3
You'll also want to make sure that is up-to-date `fastlane-plugin-s3`

**Comment by squeeish** [comment]
Ah thanks! :)

**Pull request merged**
