### PR TITLE
[WIP] fastlane for Android

### PR DESCRIPTION
**Pull request by KrauseFx**
Work in progress
- Added declaration of supported operating systems for every action
- Added verifying of supported operation system when running each action
- Added tests

Related issue: https://github.com/KrauseFx/fastlane/issues/169

### CODE REVIEW

**Comment by adennen** [comment]
Hello, I'm trying to automate the upload of new APK files to the google play store for the company I work for. I'm interested to contribute to your fastlane project, I was wondering if you have any pointers about how to automate the initial APK upload for newly created applications? Thank you

**Comment by KrauseFx** [comment]
Increasing all the test coverage :+1:

**Comment by shoshRose** [comment]
@adennen did you have any success trying to automate the initial APK upload for applications?

**Comment by KrauseFx** [comment]
@shoshRose APK upload works already, yes :+1:

**Comment by shoshRose** [comment]
@KrauseFx for first APK too? can you direct me to any documentation. What about creating a new app in Google Play Console?
thank you!

**Comment by KrauseFx** [comment]
@shoshRose Creating a new app is not possible due to the missing API. I haven't tried the initial APK upload yet, sorry.

**Comment by shoshRose** [comment]
@KrauseFx i'm guessing some Capybara magic will be necessary like in ios..

**Comment by KrauseFx** [comment]
@shoshRose I'm getting rid of all front-end scraping with https://spaceship.airforce, we'll find a way around this :+1:

**Comment by shoshRose** [comment]
@KrauseFx looking forward to it. Please update :)

**Pull request merged**
