### PR TITLE
[fastlane_core] Prepare for fastlane plugins

### PR DESCRIPTION
**Pull request by KrauseFx**
- This adds the foundation for 3rd party plugins

### CODE REVIEW

**Comment by mfurtak** [comment]
Just to be clear, we're not yet modifying any names as part of this? That is primarily for future use with plugins?

**Comment by KrauseFx** [comment]
@mfurtak Yeah, the behavior doesn't change, it now calls the method `name_to_track` which will be over-written in the fastlane subclass to provide the `fastlane-plugin-[plugin]/[action]` notation for plugins.

**Comment by mfurtak** [comment]
Just one more thought - is there anything in this that touches Sentry? (regarding the PR description...)

**Comment by KrauseFx** [comment]
@mfurtak Whups, no. I somehow mixed that up with the version bump and added this. Nothing sentry related

**Comment by mfurtak** [comment]
👍 :ship: it

**Pull request merged**
