### PR TITLE
[deliver] fix platform

### PR DESCRIPTION
**Pull request by hjanuschka**
issue: https://github.com/fastlane/fastlane/issues/7356

### CODE REVIEW

**Comment by hjanuschka** [comment]
infact the issue was resolved by just setting the platform to `osx` - but i think the change in this PR should also be there.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Would you mind pushing again, so that we re-trigger Circle?

**Comment by hjanuschka** [comment]
@KrauseFx  done

**Review by milch — APPROVED** [review]
🎷

**Pull request merged**
