### PR TITLE
Raise exception if no match password is provided

### PR DESCRIPTION
**Pull request by KrauseFx**
- Fixes https://github.com/fastlane/fastlane/issues/9126
- This was added via https://github.com/fastlane/fastlane/pull/7561
- Error message was improved just now via https://github.com/fastlane/fastlane/pull/9130
- I think the intent was raise an exception and bail out, as the error message says it, so this PR updates it

### CODE REVIEW

**Comment by orta** [comment]
Ah yeah, always blame the user.

**Comment by KrauseFx** [comment]
Wait, what?

**Comment by KrauseFx** [comment]
Has nothing to do with the user

**Review by ohayon — APPROVED** [review]

**Comment by getaaron** [comment]
I think @orta was commenting on the method name `user_error!`

**Pull request merged**
