### PR TITLE
actions/get_ipa_info_plist_value for reading Info.plist values from a .ipa file

### PR DESCRIPTION
**Pull request by johnboiles**
If you like this directionally, I'd be happy to write a blurb about it in Actions.md

### CODE REVIEW

**Comment by johnboiles** [comment]
Looks like the failing test is unrelated and is also failing for #1032 and #1035

**Comment by KrauseFx** [comment]
Sorry about the failing tests, that's my fault. Could you take a look at https://github.com/fastlane/fastlane_core/pull/66/files and https://github.com/fastlane/fastlane/pull/1046 and how this fits together with what you did? Ideally I'd like to only have one piece of code responsible for finding and parsing the plist file.

**Comment by KrauseFx** [comment]
Also, thanks for the pull request, this is a great addition to fastlane :+1:

**Comment by johnboiles** [comment]
Oh neat, thanks for pointing me to `FastlaneCore::IpaFileAnalyser`. I'll rewrite this to use that.

**Comment by KrauseFx** [comment]
That's great, thank you so much for your contribution @johnboiles :+1:

**Pull request merged**
