### PR TITLE
[supply] prevent disabling of tracks on promotion

### LINKED ISSUE #13313: Supply seems to incorrectly deactivate lower tracks during rollout
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Supply appears to deactivate lower tracks when promoting to a new track. From what I can tell, this seems to result in APKs being unavailable to users who are whitelisted for the lower tracks.

Let's take an example here, where user A is whitelisted for the alpha track, but not the beta track. When an APK is promoted via supply from alpha to beta, we'd expect user A to be able to continue to receive the build. This doesn't appear to be the case - when looking at my Play Store console, it appears that the APK was removed from the alpha track during the promotion process.

I'm reasonably confident that this line (https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L67) is the source of this bug. It appears that Supply is *deliberately* clearing the original track when promoting, which appears to be causing unintentional behavior. Note that it doesn't matter if the user passes the `check_superseded_tracks` option or not - this happens *outside* of that block of logic.

It's possible that the behavior of the Google APIs have changed since this was authored two years ago - maybe it was necessary at one point? But it certainly seems like this is no longer needed.

I'd be happy to roll a PR adding a flag to bypass this line if we believe that's a reasonable fix. But I figured I would check with the experts here to see if my understanding is at all reasonable before attempting to fix.

### PR DESCRIPTION
**Pull request by tmtrademarked**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This PR fixes an odd bug with Supply’s `promote` functionality. If a user is using Supply to promote APKs between tracks, the current code will deactivate the binary in the lower track. This is not the desired behavior - generally, you want to leave the binary in the lower track untouched. This PR adds an option to bypass this behavior if desired.

This will fix https://github.com/fastlane/fastlane/issues/13313 if accepted.

### Description
Added an option to allow bypassing the "deactivate on promote" behavior. By default, this is set to true to preserve the current behavior. Tested in the wild by using this to promote my most recent build, and observing that the existing binaries are untouched.

### CODE REVIEW

**Comment by janpio** [comment]
(See discussion in #13313 before merging)

**Review by janpio — APPROVED** [review]

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@tmtrademarked Ahhhh, so **this** is what that deleted line was preventing 🤔 I think you are right. I think we might want to add a new option called `deactivate_on_promote` for the backwards compatability 😬 Do you mind reverting your second commit that removed that? 😇 

screen shot 2018-09-19 at 8 04 53 pm

**Comment by tmtrademarked** [comment]
@joshdholtz - updated as per request! :-)

**Review by joshdholtz — APPROVED** [review]
This is great! Thanks for making this change 😊 ❤️

**Pull request merged**
