### PR TITLE
Fix spelling of default iPad simulators.

### PR DESCRIPTION
**Pull request by ZevEisenberg**
Add hyphens to match the default names of the simulators.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The first time I uncommented the default simulators after setting up Snapshot, it complained about unknown simulators. I had to add hyphens to match the default simulators, as created by `snapshot reset_simulators`, which I assume are the same as the iOS defaults.

Test: ran `bundle exec fastlane test`.

### Description

I changed all references to `12.9 inch` and `9.7 inch` to have a hyphen. Ran all tests and they passed, but I'm guessing there may be circumstances around default simulators that I don't know enough about to test properly. Would appreciate a look from someone who knows (more) what they're doing.

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
🗒 ✍️ ✅

**Comment by KrauseFx** [comment]
Hey @ZevEisenberg, thanks for the PR, looks great 👍 Quick question: What version of Xcode are you running? Do you know if that is something that was recently changed?

**Comment by ZevEisenberg** [comment]
I'm running 8.3.2. I assumed it was an Xcode 8+ think, but I can grab Xcode 8 off our NAS and check it out if that would be helpful.

**Comment by ZevEisenberg** [comment]
@KrauseFx I just confirmed that the default set of simulators from Xcode 8.0 includes hyphens in the iPad names.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Thanks for investigating this @ZevEisenberg, great change 👍

**Pull request merged**
