### PR TITLE
vision threw new google's 🕶

### PR DESCRIPTION
**Pull request by hjanuschka**
@fastlane-bot - silence is gold!

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @hjanuschka</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by nafu — APPROVED** [review]
🕶

**Review by asfalcone — CHANGES_REQUESTED** [review]
Please hold off on merging this for now. Waiting for official wording 👍

**Comment by asfalcone** [comment]
Closed in favor of https://github.com/fastlane/fastlane/pull/8815

**Pull request closed without merging**
