### PR TITLE
do not require apk on promote

### PR DESCRIPTION
**Pull request by hjanuschka**
we wan't to promote a beta to production - this would not require an apk (as CI uploaded it).

https://github.com/fastlane/fastlane/issues/5182

### CODE REVIEW

**Comment by hjanuschka** [comment]
https://github.com/fastlane/fastlane/issues/5182

**Comment by hjanuschka** [comment]
really would love to know if there is a more elegant way to detect if the option is set - instead of testing against `ENV`

**Comment by asfalcone** [comment]
@hjanuschka I don't think this PR is neccessary. As I commented in #5182, the failure listed in that stacktrace isn't related to having an apk. 

The warning "No apk file found, you can pass the path to your apk using the `apk` option" isn't generated by the verification block where you are checking the environment variable (it comes from [here](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L138)) and can be suppressed by passing the [`skip_upload_apk`](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L92) param in your config.

**Comment by hjanuschka** [comment]
@asfalcone  ok i totally missed that, i thought i tried it with the `skip_apk_upload`  - sorry for stealing your time 😩

**Pull request closed without merging**
