### PR TITLE
[frameit] Fix offsets for iPhone 7 shots

### PR DESCRIPTION
**Pull request by adriencog**
Offsets update for iPhone 7 et iPhone 7 Plus
Rename iPhone 6S to iPhone 7

Fixes https://github.com/fastlane/fastlane/issues/6398

### CODE REVIEW

**Comment by SRowley90** [comment]
Good work been waiting for this, how can I use your fork in the meantime until it's merged in? I'm not too familiar with ruby and how to get it working from outside the normal fastlane install route.

**Comment by KrauseFx** [comment]
This looks nice, thanks. However this would break backwards compatibility. We haven't found a perfect solution for frames yet unfortunately. Ideally we'd bundle them with _frameit_ somehow

**Comment by lyricsboy** [comment]
I needed this as well, but it required a few more changes. You can see those in my fork here:

https://github.com/fastlane/fastlane/compare/master...lyricsboy:lyricsboy/frameit-updates

**Review by tadelv — APPROVED** [review]

**Comment by tadelv** [comment]
Sorry for this, I somehow managed to approve this review which was not my original intention. 
Wanted to add +1, we would like to see this in the next release and I have tested the changes from the [https://github.com/fastlane/fastlane/compare/master...lyricsboy:lyricsboy/frameit-updates](url) fork and for me they work ok. 👍

**Comment by KrauseFx** [comment]
I'm actively working on a re-write of _frameit_ that supports all the latest devices with https://github.com/fastlane/fastlane/pull/6597, please subscribe to the pull request to stay up to date. We hope to have a new version ready this week  🚀

**Pull request closed without merging**
