### PR TITLE
[action] import_from_git: Import multiple files from git

### PR DESCRIPTION
**Pull request by Kerizer**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Currently, if you need to import multiple files from git - you will clone the repository for every single file.

### Description
I've checked that previous solution still works in a same way as before and that you will have access to lanes/defs that are located in fastfiles that we added as `dependencies` and not as `path` variable.

### Testing Steps
1. Add few Fastfiles to external git repo. 
2. Import them in previous way (example):
```
import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/defs/Fastfile",
)

import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/git-commands/Fastfile",
)

import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/github-commands/Fastfile",
)

import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/bump-versions/Fastfile",
)

import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/Fastfile",
)
```
3. Check if you are able to use lanes/defs from those files
4. Change it to use import_from_git only once and add all additional files to `dependencies` and check if lanes still work
```
import_from_git(
  url: github_infra_repo_url,
  branch: github_infra_repo_branch,
  version: github_infra_repo_version,
  path: "fastlane/Fastfile",
  dependencies: ["fastlane/defs/Fastfile", "fastlane/git-commands/Fastfile", "fastlane/github-commands/Fastfile", "fastlane/bump-versions/Fastfile"]
)

lane :test do
  run_action_from_file_1
  run_action_from_file_2
  run_action_from_fastlane_Fastfile
end
```

### CODE REVIEW

**Comment by joshdholtz** [comment]
@Kerizer Can you accept the Google CLA whenever you get a chance? 😊

**Review by joshdholtz — APPROVED** [review]
This is a great change! This is good to merge whenever the CLA is accepted 😊

**Comment by Kerizer** [comment]
> This is a great change! This is good to merge whenever the CLA is accepted 😊

Once our legal team will approve this - I will do all the stuff. They work slowly cause of Christmas holidays =)

**Comment by joshdholtz** [comment]
@Kerizer Any movements on the legal time? 😊

**Comment by Kerizer** [comment]
@googlebot I signed it!

**Comment by Kerizer** [comment]
@googlebot I signed it!

**Comment by Kerizer** [comment]
@joshdholtz Sorry for direct ping, I just want to know - should I prepare the PR with docs update now or should I wait for something or ...?

**Comment by dentuzhik** [comment]
We can't wait to drop our fastlane fork and we'll be happy to contribute to docs :)

**Comment by joshdholtz** [comment]
@Kerizer @dentuzhik Happy to have this merged! If you don't mind updating the docs for this that would be 💯 

Should be this one 👉 https://github.com/fastlane/docs/blob/master/docs/advanced/Fastfile.md

**Pull request merged**
