### PR TITLE
Re-add metrics

### PR DESCRIPTION
**Pull request by KrauseFx**
_fastlane_ tracks a few key metrics to understand how developers are using the tool and to help us know what areas need improvement. No personal/sensitive information is ever collected. Metrics that are collected include: 
 
* The number of _fastlane_ runs
* A salted hash of the app identifier or package name, which helps us anonymously identify unique usage of _fastlane_
 
You can easily opt-out of metrics collection by adding `opt_out_usage` at the top of your `Fastfile` or by setting the environment variable `FASTLANE_OPT_OUT_USAGE`.

Related https://github.com/fastlane/docs/pull/627

Remaining tasks:

- [x] One bug has to be fixed that sends analytics events per action @powerivq 
- [x] We should remove the `backfill_p_hashes` method
- [x] We have to fix sending the request for short Fastfiles @krausefx
- [x] Update code to not take an `events` array, but just a single `event`
- [x] Update user agent to include fastlane version number

### CODE REVIEW

**Review by KrauseFx — COMMENTED** [review]
Works! Ready from my side 🎉

**Comment by KrauseFx** [comment]
Tests need to be fixed though

**Comment by KrauseFx** [comment]
```

FastlaneCore::AnalyticsSession single action execution action launch analytics session: launch - in fastlane_core.spec.analytics.analytics_session_spec
--
 
```

**Comment by powerivq** [comment]
Fixed all test failure. Now pending approval.

**Comment by taquitos** [comment]
`We should remove the backfill_p_hashes method`
Ahh, actually, sometimes we don't have the app-id until the end of the run, so `backfill_p_hashes` was originally used to backfill our data when we finally got the p-hash. 

So, instead of immediately sending metrics, I think we actually need to hold on to the event, and wait until we have a p-hash. At that time, we can send the event back.

**Comment by powerivq** [comment]
@KrauseFx @taquitos Updated to delay the metrics until we get the AppID.

Tested on an iOS and Android project locally to confirm that it's calculating the right package name/bundle id. Verified the GA tracking ID is up-to-date. PTAL?

**Comment by powerivq** [comment]
@joshdholtz PTAL too!

**Review by joshdholtz — APPROVED** [review]
Looks good and works good 💯 Let's get some metrics 📈

**Pull request merged**
