### PR TITLE
Update reference to age rating template

### PR DESCRIPTION
**Pull request by max-ott**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by max-ott** [comment]
I signed it!

**Comment by janpio** [comment]
Hmm, this is actually also available in the docs:
https://docs.fastlane.tools/actions/deliver/#available-age-rating-groups

But you first have to open the "Reference" `<details>` element:
https://docs.fastlane.tools/actions/deliver/#reference
(Then click the first link again)

This includes better documentation on possible values.
But should probably link to the file you added here, as an actual "example" of what the file should look like is missing there.

**Comment by KrauseFx** [comment]
Nice catch @janpio 👍

**Comment by janpio** [comment]
Javascript in the docs pages would probably be the way to go:
https://stackoverflow.com/a/37033774/252627
But this is not exactly what we need... will open an issue on fastlane/docs.

@max-ott I think for now it would be best to include the link you used and the #reference one.

**Review by janpio — APPROVED** [review]
Added the second link for completeness, now this is good to merge.

**Pull request merged**
