### PR TITLE
[crashlytics] fix generated command (generate_android_command) for Windows

### PR DESCRIPTION
**Pull request by e1iman**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Thanks for making these changes for windows! Can you also update the tests associated with this code so all of the CIs pass? 🙃 After that we can work on getting this merged 💪

**Comment by e1iman** [comment]
I signed it!

**Comment by joshdholtz** [comment]
@e1iman Thanks for making that fix! I will test this out today to make sure everything still run correctly on my side 😊

**Comment by janpio** [comment]
Nice changes @e1iman! Looks good from my side (but I didn't actually test it, just looked at the code).

**Review by janpio — APPROVED** [review]

**Review by joshdholtz — APPROVED** [review]
Looks good and works good for me 👍 Thanks for making this change!

**Pull request merged**
