### PR TITLE
Send dsId in body when setting team_id

### PR DESCRIPTION
**Pull request by summera**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [ ] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [ ] Run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Fixes https://github.com/fastlane/fastlane/issues/6711

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks so much for the PR, I already pushed the changed with https://github.com/fastlane/fastlane/pull/6716, I added your username to the commit, already in the process of preparing a new release 👍

**Comment by summera** [comment]
@KrauseFx no problem! happy to help. thanks for the awesome gem :).

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Awesome, thank you so much @summera 👍

**Comment by KrauseFx** [comment]
This is live now 🚀

**Comment by lukethoene** [comment]
[21:37:24]: Waiting for the newly created application to be available on iTunes Connect...

Great work guys!

**Pull request merged**
