### PR TITLE
Refactor fastlane CommanderGenerator usage

### PR DESCRIPTION
**Pull request by nafu**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

Remove --env option from fastlane global_options.

Now `fastlane help` shows correct options.
```bash
  fastlane

  CLI for 'fastlane' - The easiest way to automate beta deployments and releases for your iOS and
Android apps

        Run using `fastlane [platform] [lane_name]`
        To pass values to the lanes use `fastlane [platform] [lane_name] key:value key2:value2`

  Commands: (* default)
    action                 Shows more information for a specific command
    actions                Lists all available fastlane actions
    add_plugin             Add a new plugin to your fastlane setup
    docs                   Generate a markdown based documentation based on the Fastfile
    enable_auto_complete   Enable tab auto completion
    env                    Print your fastlane environment, use this when you submit an issue on
GitHub
    help                   Display global or [command] help documentation
    init                   Helps you with your initial fastlane setup
    install_plugins        Install all plugins for this project
    lanes                  Lists all available lanes and shows their description
    list                   Lists all available lanes without description
    new_action             Create a new custom action for fastlane.
    new_plugin             Create a new plugin that can be used with fastlane
    run                    Run a fastlane one-off action without a full lane
    search_plugins         Search for plugins, search query is optional
    trigger              * Run a specific lane. Pass the lane name and optionally the platform first.
    update_fastlane        Update fastlane to the latest release
    update_plugins         Update all plugin dependencies

  Global Options:
    --verbose
    --capture_output     Captures the output of the current run, and generates a markdown issue
template
    --troubleshoot       Enables extended verbose mode. Use with caution, as this even includes ALL
sensitive data. Cannot be used on CI.
    -h, --help           Display help documentation
    -v, --version        Display version information

  Options for trigger:
    --env STRING[,STRING2] Add environment(s) to use with `dotenv`

  Author:
    Felix Krause <fastlane@krausefx.com>

  Website:
    https://fastlane.tools

  GitHub:
    https://github.com/fastlane/fastlane

```

### Motivation and Context

Because --env option is not actually global_option, it's option for 'fastlane trigger'.

### CODE REVIEW

**Review by mfurtak — APPROVED** [review]
Nice work finding this conflict 👍

**Comment by nafu** [comment]
@mfurtak Thanks 👍

**Comment by thebugcode** [comment]
Thanks for bringing help back 👍

**Comment by KrauseFx** [comment]
Yeah 🚀

**Pull request merged**
