### PR TITLE
Fix typo in rubocop config file

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Nice 👍

**Comment by saraswathirbt** [comment]
fastlane hangs on
This might take a few minutes. Please don't interrupt the script
can any one please help me
fastlane -v:2.80.0

**Comment by revolter** [comment]
@saraswathirbt, Please open [a new issue](https://github.com/fastlane/fastlane/issues/new) for your problem, as it's not related to this PR.

Meanwhile, are you sure it doesn't finish? How much did you let it run?

**Comment by saraswathirbt** [comment]
@revolter  thanks for your replay, I solved that issue

**Pull request merged**
