### PR TITLE
[sigh] skip cert verification on linux & Windows

### LINKED ISSUE #19114: Match breaks due to certificate verification on Linux
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Downloading & decrypting of certificate works on doing fastlane match but verifying if the cert is installed fails on Linux on [this line](https://github.com/fastlane/fastlane/blob/66a4bb17bf6f3c0f3222b5c296926e5b58dd2b4e/sigh/lib/sigh/runner.rb#L144).

##### Command executed

```ruby
Match::Runner.new.run(FastlaneCore::Configuration.create(Match::Options.available_options, params))
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Verifying certificates...
Errno::ENOENT: No such file or directory - security
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/helper.rb:303:in ``'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/helper.rb:303:in `backticks'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:131:in `block in wwdr_keychain'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:130:in `each'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:130:in `wwdr_keychain'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:86:in `wwdr_certificates_installed?'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:25:in `installed_identies'
/usr/local/bundle/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/cert_checker.rb:12:in `installed?'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:144:in `block (2 levels) in fetch_profiles'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:138:in `each'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:138:in `block in fetch_profiles'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:120:in `each'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:120:in `find_all'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:120:in `fetch_profiles'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/runner.rb:38:in `run'
/usr/local/bundle/gems/fastlane-2.187.0/sigh/lib/sigh/manager.rb:8:in `start'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/generator.rb:108:in `generate_provisioning_profile'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:269:in `fetch_provisioning_profile'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:111:in `block (2 levels) in run'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:110:in `loop'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:110:in `block in run'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:109:in `each'
/usr/local/bundle/gems/fastlane-2.187.0/match/lib/match/runner.rb:109:in `run'
</details>

### Environment

<details>
  <pre> 
✅ fastlane environment ✅

### Stack

| Key                         | Value                                                    |
| ----------------- | ------------------------------- |
| OS                          | debian_based 10.5                                        |
| Ruby                        | 2.7.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.20.1                                       |
| Installation Source         | /usr/local/bundle/bin/fastlane                           |
| Host                        | Debian GNU/Linux 10 debian_based 10.5 (4.9.184-linuxkit) |
| Ruby Lib Dir                | /usr/local/lib                                           |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**
 </pre>
</details>

### PR DESCRIPTION
**Pull request by abdulwd**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Resolved #19114 

### Description

Skip certificate validation on Linux & Windows

### CODE REVIEW

**Comment by abdulwd** [comment]
@googlebot I signed it!

**Comment by abdulwd** [comment]
@joshdholtz I think the failing test is unrelated to the changes. Can you please help? 🙂

**Review by joshdholtz — APPROVED** [review]
This looks great to me! I added one commit to move the `Helper.mac?` check to the `default_value:`. This way it will appear with a default value of `true` when `fastlane action sigh` is run on Linux or Windows 😊 

Thanks for making this PR ❤️

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by abdulwd** [comment]
@joshdholtz Thanks a lot! This looks great 💪

**Pull request merged**
