### PR TITLE
Added "verbose" option to Carthage

### PR DESCRIPTION
**Pull request by jschmid**
Add the `--verbose` option to the Carthage action.

This is based from #641

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks @jschmid :+1:

**Comment by victor** [comment]
How should this be used?
I tried `export FL_CARTHAGE_VERBOSE=true` and a number of other possible values (True, TRUE, 1...) and I always get this:

```
[13:21:09]: Error setting value 'TRUE' for option 'verbose'
[13:21:09]: Variable Dump:
[13:21:09]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios routine"}
[13:21:09]: Please pass a valid value for verbose. Use one of the following: true, false
```

I'm sorry, Ruby is not my strong point. I'm not sure how I should set this from a CI environment

**Comment by jcampbell05** [comment]
true in quotes maybe ?

**Comment by victor** [comment]
no, neither simple nor double quotes do the trick for me.

**Comment by KrauseFx** [comment]
@victor this looks like a bug, can you submit an issue on `fastlane_core`?

**Comment by victor** [comment]
sure, will do it later today

**Pull request merged**
