### PR TITLE
Add bootsnap to optimize boot time

### PR DESCRIPTION
**Pull request by Watson1978**
Currentry, `fastlane` takes a time nearly 1 sec even if it displays help message.

```
$ time bundle exec fastlane -h > /dev/null
bundle exec fastlane -h > /dev/null  0.73s user 0.22s system 98% cpu 0.966 total
```

If you create new lane/action by trial and error, I think it is useful if boot time will be reduced.
This patch will reduce the boot time 0.966 sec -> 0.584 sec using `bootsnap` gem.
https://github.com/Shopify/bootsnap

Seems `fastlane` requires many Ruby files such as plugins/helpers and it takes a time where parses/generates AST and Ruby instruction sequences.

`bootsnap` gem generates Ruby instruction sequences cache and it will be able to reduce boot time.

At first boot, `bootsnap` generates Ruby instruction sequences cache and it take a time.

```
$ time bundle exec fastlane -h > /dev/null
bundle exec fastlane -h > /dev/null  0.94s user 0.45s system 98% cpu 1.420 total
```

But, after generated Ruby instruction sequences cache, boot time will be reduced.

```
$ time bundle exec fastlane -h > /dev/null
bundle exec fastlane -h > /dev/null  0.43s user 0.14s system 97% cpu 0.584 total
```

My environment is
* MacBook 2017
* CPU : 1.4 GHz Core i7
* Memory : 16 GB
* OS : macOS 10.13

----

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by Watson1978** [comment]
I signed it!

**Review by jetersen — APPROVED** [review]

**Comment by casz** [comment]
This is awesome! 🚀

**Comment by KrauseFx** [comment]
Hey @Watson1978, thanks for your contribution, this is great. I'm a little worried that adding another dependency for this, might have unexpected side effects. e.g. does it affect the way plugins are loaded, or the homebrew based fastlane installation, or the Fabric mac app based installation? 

I want to be sure we're not breaking any existing fastlane setups, that worked fine so far.

**Comment by Watson1978** [comment]
Thank you for your reply.
OK I need to investigate about installation process in fastlane with more carefully.

However, you can stop to use this feature ease if it could not be installed with homebrew or another.

You just catch the exception in `require` with `begin/rescue/end`, like, 

```diff
diff --git a/bin/fastlane b/bin/fastlane
index a5c215d75..5ead9716c 100755
--- a/bin/fastlane
+++ b/bin/fastlane
@@ -4,16 +4,19 @@ if RUBY_VERSION < '2.0.0'
   abort "fastlane requires Ruby 2.0.0 or higher"
 end
 
-require 'bootsnap'
-require 'fastlane/version'
-Bootsnap.setup(
-  cache_dir: "/tmp/fastlane-#{RUBY_VERSION}-#{Fastlane::VERSION}",
-  load_path_cache: true,
-  autoload_paths_cache: false,
-  disable_trace: true,
-  compile_cache_iseq: true,
-  compile_cache_yaml: true
-)
+begin
+  require 'bootsnap'
+  require 'fastlane/version'
+  Bootsnap.setup(
+    cache_dir: "/tmp/fastlane-#{RUBY_VERSION}-#{Fastlane::VERSION}",
+    load_path_cache: true,
+    autoload_paths_cache: false,
+    disable_trace: true,
+    compile_cache_iseq: true,
+    compile_cache_yaml: true
+  )
+rescue LoadError
+end
 
 $LOAD_PATH.push File.expand_path("../../lib", __FILE__)
 
```

**Comment by Watson1978** [comment]
hmm, looks like `bootsnap` gem depends on `bundler`.
When you run `fastlane` command without `bundle exec`, `bootsnap` raises exception.

```
$ rake build
fastlane 2.60.1 built to pkg/fastlane-2.60.1.gem.

$ gem install pkg/fastlane-2.60.1.gem

$ fastlane -h
/Users/watson/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/path_scanner.rb:18:in `<module:PathScanner>': uninitialized constant Bootsnap::LoadPathCache::PathScanner::Bundler (NameError)
...
```

**Comment by ohayon** [comment]
Hey @Watson1978, apologies for the delayed response here. I am going to close this PR for now as we are hesitant to introduce any more dependencies that are not totally necessary to _fastlane's_ functionality. Thank you for the contribution though! Let us know if there is anything else we can do to help and we hope to see some more PRs from you in the future! 🚀  🐙

**Comment by janpio** [comment]
@Watson1978 I actually would like to see this looked at again, as _fastlane_ really tends to be a bit on the slower side sometimes.

Can you provide timings on the speedup _without_ `bundle exec`?

**Comment by Watson1978** [comment]
@janpio If bootsnap will be shipped with my patch (https://github.com/Shopify/bootsnap/pull/91) , I will send this pull request again :)

**Pull request closed without merging**
