### PR TITLE
Fix: resolve deadlock in LatestOsVersion#version_for_os

### PR DESCRIPTION
**Pull request by stbix**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When I upgraded to Xcode 13.3.0, fastlane started to deadlock
randomly in LatestOsVersion#version_for_os. Eventually I figured
that it blocks only, when my phone is connected via USB to my
computer. I can "solve" the problem by disconnecting my phone.

### Description

LatestOsVersion#version_for_os can be catched in a deadlock when
used with Xcode 13.3.0 or later while a device is physically connected
to the computer.

In this case, xcodebuild will return a few lines of errors on stderr
which will trigger a deadlock in Open3#open3.  The problem is
mentioned explicitely in the documentation of Open3#open3:

> You should be careful to avoid deadlocks. Since pipes are fixed
> length buffer, #popen3(“prog”) {|i, o, e, t| o.read } deadlocks if
> the program generates many output on stderr. You should be read
> stdout and stderr simultaneously (using thread or IO.select). However
> if you don't need stderr output, #popen2 can be used. If merged
> stdout and stderr output is not a problem, you can use #popen2e.
> If you really needs stdout and stderr output as separate strings,
> you can consider #capture3.

Using Open3#capture2 or Open3#open2 would show the error in the
terminal, but Open3#capture3 allows us to capture only stdout and
hide stderr from the users eyes.

I tested the fix using Xcode 13.3.1 connecting and disconnecting
my phone, and it work just fine now.

### CODE REVIEW

**Comment by sleepygarden** [comment]
@stbix [stbix](https://github.com/stbix) thank you for this. I don't have connected USB devices, I'm using an amazon ec2 Mac Intel box for our CI pipeline. After upgrading from xcode 13.2.1 to 13.4 this issue kicked in for me as well.

**Comment by sleepygarden** [comment]
bump on this - I'd love to see this get merged, my team has been unable to upgrade fastlane for over half a year because of this

**Comment by mbarany** [comment]
Bump ^

**Comment by mbarany** [comment]
@giginet 🙏 please

**Review by giginet — APPROVED** [review]
Ruby's standard libraries are too difficult...

LGTM. Sorry for waiting such a long time.

**Comment by giginet** [comment]
@stbix Sorry for waiting for you such a long time.

Your commit looks good. 
However, it passed a too long time, so I rebased your commit to the current HEAD of the master branch to re-run CI jobs because you were allowed to edit this PR. 🙏 

I'll merge this soon after CI passed. Thank you for your contribution!

**Pull request merged**
