### PR TITLE
Parse version string out of last git tag

### PR DESCRIPTION
**Pull request by jeeftor**
I cant seem to re-open #1115 so I've once again created a brand new PR.  

See #1115 for details.

### CODE REVIEW

**Comment by jeeftor** [comment]
Ok i'm really confused here.  I just did the following:

    git clone https://github.com/fastlane/fastlane.git ftl
    cd ftl
    bundle install
    bundle exec fastlane test

And its not passing - so that says to me the master branch is broken.

**Comment by jeeftor** [comment]
Any updates on getting this merged - did you guys fix the CI issues?

**Comment by KrauseFx** [comment]
Hey @jeeftor, could you rebase master and squash the commits? We fixed the CI issue, so once you merge master into your branch it should be good to go :+1:

**Comment by jeeftor** [comment]
Are we good now?

**Comment by mfurtak** [comment]
Hey @jeeftor - thanks for putting this together. I'm sorry that this PR has sat so long in limbo.

We've talked this over and we're not sure this is a great fit with how we'd like to manage version information. For Apple projects, right now we believe that the **info.plist** is the canonical place to store and manipulate version info. We don't have a solid strategy for Android yet, but we believe that we'd like to have a similar strategy that stores/retrieves the info from a file in repository rather than the repository's metadata.

Again, apologies for not getting this feedback to you more quickly, but we really appreciate it! :+1:

**Comment by jeeftor** [comment]
So I do want to point something out - before we set this PR to rest.  The reason this PR came about is that we are using git-flow internally as our branching strategy and this IS how git-flow does versioning.  When you make a new release to the master branch it gets a new version tag.  Internally on both android and iOS we use this action to ensure that our app version matches the branch release version.

In many ways we've found its easier and more consistent to use branch tagging to drive version numbers than manually updating the version number.  Build number is easy to auto-increment but in order to boost the version number you need to make manual changes.  

Subsequently, you also have an action that pulls the versioning from the number of commits -which is a little wonky because you can rewrite history with git and change the number of commits - which would lead to all sorts of disasters i think.  

In any case - what we do internally (when there is a new commit to master with a new release tag)

1) Pull the latest branch tag 
2) Update the info-plist version to match the branch tag
3) Depending on configuration bump the version number or zero it out.

The reason I pushed for this PR is that internally we have 5 different projects all using this strategy - and we've found it to be better than the old one which is "try to remember to update the version number when you make a new official release"

:)

**Comment by mfurtak** [comment]
Hey @jeeftor - thanks for that explanation! It was super helpful to get a picture of what you are going for. For my part, I'll definitely try to ask for this kind of clarification earlier in the future.

I suspect you are aware, but I just wanted to mention the [extensions](https://github.com/fastlane/fastlane/blob/master/docs/README.md#extensions) capability for using custom actions locally. It doesn't make it easier to share across projects, though, which was part of your point 😀

We'll keep an eye out for more demand for this strategy! :+1:

**Pull request closed without merging**
