### PR TITLE
Removed appium development dependency and therefore nokogiri

### PR DESCRIPTION
**Pull request by KrauseFx**
This caused `bundle install` on fastlane to also install nokogiri

### CODE REVIEW

**Comment by KrauseFx** [comment]
Lol, thanks for the reaction @neonichu 👎

**Comment by neonichu** [comment]
Big :-1: Everything should depend on nokogiri, plz also add Rails.

**Comment by neonichu** [comment]
You should be adding more dependencies, not removing them

**Comment by mfurtak** [comment]
:ship: it

**Comment by orta** [comment]
Add a check in the lock files for it?

**Comment by KrauseFx** [comment]
@orta You mean `danger` should check that nokogiri isn't added as dependency?

**Comment by orta** [comment]
yep

**Pull request merged**
