### PR TITLE
[fastlane_core] Version bump

### PR DESCRIPTION
**Pull request by KrauseFx**
- Preparing for fastlane plugins 🚀 
- Added new option to hide timestamps in fastlane outputs using `FASTLANE_HIDE_TIMESTAMP` (#4838)
- Fix `PkgFileAnalyser` to shell escape `xar` arguments
- `Helper.fastlane_enabled?` improvements (#4889)
- Continuing work on #3843
- Ads Apple Developer Id to `itunes_transporter.rb` - allows `deliver` to work with multiple iTunes Providers

### CODE REVIEW

**Comment by KrauseFx** [comment]
I just noticed that that should actually be a minor version bump, since we added new options

**Comment by KrauseFx** [comment]
Alright, updated the PR, waiting for the build

**Comment by KrauseFx** [comment]
Just found out that we should actually wait for https://github.com/fastlane/fastlane/pull/4722/ to be merged, because there are some fastlane_core changes there as well 👍

**Comment by KrauseFx** [comment]
Ready go to be merged 👍

**Comment by asfalcone** [comment]
👍

**Pull request merged**
