### PR TITLE
Improved unlock_keychain action

### PR DESCRIPTION
**Pull request by xfreebird**
Change the way the unlocked keychain is added to the keychain list. Inspired from #668 .

### CODE REVIEW

**Comment by xfreebird** [comment]
@KrauseFx please review this patch for the unlock_keychain action

**Comment by KrauseFx** [comment]
I haven't tested it, but looks good on the code side. Are you using the integration already yourself?

**Comment by xfreebird** [comment]
Yes

**Comment by KrauseFx** [comment]
Thanks for the contribution @xfreebird :dancer:

**Comment by cyupa** [comment]
:+1: good job @xfreebird

**Comment by xfreebird** [comment]
Thanks @cyupa  :)

**Pull request merged**
