### PR TITLE
No longer forcing external distribution when using distribute command

### PR DESCRIPTION
**Pull request by fer662**
https://github.com/fastlane/fastlane/issues/5990

### CODE REVIEW

**Comment by KrauseFx** [comment]
This added via https://github.com/fer662/fastlane/commit/a54e1293a384db2fb273e2284f682fd1360fc83c by @tmm1, I'd like to get his +1 on this issue to make sure we don't break anything else 👍

**Comment by tmm1** [comment]
I added the distribute command for distribution to external testers. Is distribute useful for internal testing? I thought all new builds become available to internal testers automatically.

**Comment by fer662** [comment]
@tmm1 I just tested and at least on the first build you upload it's not happening. I think once you distribute something, all future builds do get release internally automatically.
I'm using skip_waiting_for_build_processing because my script makes a bunch of applications, and it's better to generate and upload all the binaries and release them after, rather than do the polling after every upload for time reasons (by the time the last app uploads most of the others are processed already). It's a common scenario for me that new apps are submitted so doing the first release manually is not a solution.

**Comment by tmm1** [comment]
Okay that makes sense. I will need to update my usage everywhere to pass in
the external flag, but this PR seems good to me.

**Comment by KrauseFx** [comment]
So this is a breaking change for the user? How does usage change for a regular pilot user?

**Comment by tmm1** [comment]
Yes, anyone using 'pilot distribute' would need to change to 'pilot
distribute --distribute_external'

**Comment by dstranz** [comment]
One question... How I can distribute same build to internal & external beta testers? It's possible to reuse already processed build and send it to external beta review?

**Comment by fer662** [comment]
I haven't dug deeply, but this override kind of contradicts the default flag settings for pilot in this regard. Does this mean they should have been specifying external if they wanted?

> FastlaneCore::ConfigItem.new(key: :distribute_external,
                                     is_string: false,
                                     env_name: "PILOT_DISTRIBUTE_EXTERNAL",
                                     description: "Should the build be distributed to external testers?",
                                     default_value: false),

**Comment by KrauseFx** [comment]
I'm not a big fan of changing the default here, especially since users seem to be able to set the value in their `Fastfile`, right? 
I'll close this PR for now, feel free to submit an issue here on GitHub so we can discuss this further

**Comment by fer662** [comment]
@KrauseFx I'm not asking to change the default, I'm saying the default is already what I needed, but there's code overriding the default to do the contrary :S

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this PR for now as it has been quite a while since there was any activity on here. Please feel free to continue discussion and we can reopen if necessary. 🚀 🐙

**Pull request closed without merging**
