### PR TITLE
Circle - Danger Integration

### PR DESCRIPTION
**Pull request by KrauseFx**
- Copy rspec results to Circle artifacts

### CODE REVIEW

**Comment by lacostej** [comment]
This could be good.  Some thoughts:

* make sure it doesn't display all errors (in case you have 100)!
* I am particularly interested if it gives some sort of information overview, like rubocop failed in spaceship, or test failed in deliver.
* are those messages hidden when the PR is updated ? That would be good as well.

**Comment by KrauseFx** [comment]
@lacostej great feedback

1. Good point, this might be something we want danger to do by default? (cc @orta)
1. Right now it's grouped by tool and contains the tool name as the first word
1. They are hidden right now, however I'd love to do this https://github.com/danger/danger/issues/153 (cc @camacho)

**Comment by orta** [comment]
> Good point, this might be something we want danger to do by default? (cc @orta)
 
Danger will list out anything you tell her, should be fine for whatever, might feel nicer to make the all one string instead of passing in as multiple fails though

**Comment by KrauseFx** [comment]
Let's merge this!!!1111 :tada:

**Pull request merged**
