### PR TITLE
Add sensitive ConfigItem for sonar_login

### LINKED ISSUE #7937: Prevent tokens being shown in log
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am using Fastlane on Travis CI for an open source project. On Travis I put all those tokens that shouldn't be public in the environment variables. They're used in my Fastfile like this
```
sonar_update_server_args = {
	project_configuration_path: "sonar-project.properties", 
	sonar_runner_args:  " -Dsonar.login="+ENV['SONAR_LOGIN_TOKEN']
}
sonar(sonar_update_server_args)
```

When I run the lane, Fastlane is logging the command it's currently executing, like shown below. This is a problem because the private tokens would show up in the public log when running this on Travis.

```
...
[15:45:48]: ------------------------------
[15:45:48]: Driving the lane 'test' 🚀
[15:45:48]: -------------------
[15:45:48]: --- Step: sonar ---
[15:45:48]: -------------------
[15:45:48]: $ cd /Users/max/Code/TumCampusApp-iOS && sonar-scanner \
-Dproject.settings="sonar-project.properties"  -Dsonar.login=6cd5b2_private_token_eb6b3b67e
...
```

When searching the docs I didn't find an option to prevent certain parameters from being logged, or even to disable the logging of the complete command.

How is this supposed to be handled?
Thanks!

### PR DESCRIPTION
**Pull request by hjanuschka**
hide executed command (as it may contain credentials).
and add special option for login token.

fixes: https://github.com/fastlane/fastlane/issues/7937

### CODE REVIEW

**Comment by mfurtak** [comment]
Nice! Can we add a regression test to ensure that a value passed for `sonar_login` does not wind up in the output?

**Comment by hjanuschka** [comment]
@mfurtak thx - good idea, added an spec for that!.

**Review by mfurtak — APPROVED** [review]
Sweet!

**Comment by mammuth** [comment]
Nice! Love it that you guys react to the feedback that quickly! ❤️

**Pull request merged**
