### PR TITLE
Add linter for Swift code

### PR DESCRIPTION
**Pull request by dcordero**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
As result of integrating Fastlane Snapshot into my project I found a few linter warnings.

At the moment Fastlane ensures Ruby code style making use of rubocop, but Swift code style is not yet validated.

### Description
Add Swift linter to ensure the code style of Swift code

### CODE REVIEW

**Comment by ohayon** [comment]
Hey @dcordero - this is really great. I think at the moment we are trying to not introduce any new dependencies into our build process so I am a bit hesitant to merge the changes that add swiftlint to our process. That being said, I would love to merge in the changes to the SnapshotHelper itself as that formatting is definitely much nicer than it was prior. Would it be possible for you to put the other changes on hold now and we can just merge the changes to the swift code?

Thanks! 🚀

**Comment by getaaron** [comment]
@ohayon Looks like `SnapshotHelper.swift` got updated elsewhere.

1. Should we close this PR?
2. `swiftlint` also found issues with:

    ```
    snapshot/example/ExampleMacOS/AppDelegate.swift
    snapshot/example/ExampleMacOSUITests/ExampleMacOSUITests.swift
    snapshot/example/ExampleTVUITests/ExampleTVUITests.swift
    snapshot/example/ExampleUITests/ExampleUITests.swift
    ```

    Should I open a PR for those?

**Comment by taquitos** [comment]
@getaaron, yeah, updating those files would be awesome so that other people don't run into swiftlint issues. I would be in favor of a new PR, and maybe @dcordero can close out this one?

**Comment by dcordero** [comment]
Thanks for taking care of this pull request @getaaron. I have  been a bit busy and I could not  update this branch with the requested changes.

As proposed by @taquitos I am closing this PR

**Pull request closed without merging**
