### PR TITLE
appledoc: added the --no-create-docset parameter

### PR DESCRIPTION
**Pull request by s-hocking**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This change adds a `--no-create-docset` parameter to the `appledoc` action, which allows it to generate HTML output only (i.e. without creating a DocSet). This is useful when creating documentation that will only be distributed on the web.

Addresses issue #11083.

PR includes a simple test, plus I tried it out on my own projects.

### Description
Simply adds an extra parameter, `--no-create-docset` that is passed through to `appledoc` [as documented here](https://github.com/tomaz/appledoc/wiki/appledoc-docs-examples-advanced#create-html-only).

### CODE REVIEW

**Comment by s-hocking** [comment]
I signed it!

**Review by janpio — APPROVED** [review]
🥇

**Comment by janpio** [comment]
Test failure looks unrelated. Still strange.

**Comment by s-hocking** [comment]
Yeah, I thought it was strange too. That test failed for me before I made any changes.

**Comment by s-hocking** [comment]
Looks like the `Plist` dependency has been updated and changed the signature of `save_plist()`.
https://github.com/patsplat/plist/pull/44/files

**Review by KrauseFx — APPROVED** [review]
Looks great from my side also, thanks @s-hocking. Quick question: do we need to update the dependency to `appledoc` (if we have any) or something?

**Comment by s-hocking** [comment]
Hey @KrauseFx, the `appledoc` dependency doesn’t need updating. Fastlane already uses the latest version. Cheers!

**Comment by KrauseFx** [comment]
Awesome, thanks for confirming 👍

**Pull request merged**
