### PR TITLE
Mac support for many mutli-platform actions

### PR DESCRIPTION
**Pull request by czechboy0**
Many of the actions unnecessarily had only iOS support declared, even though most of them work for Mac projects too, so I fixed them. (I must be literally the first Mac dev trying to do this 😄.)

### CODE REVIEW

**Comment by KrauseFx** [comment]
Ha, thanks @czechboy0 :+1: I actually am using `fastlane` for Mac, but not those actions. I guess I haven't been careful enough activating those actions for the Mac as well.
Thanks :rocket:

**Comment by czechboy0** [comment]
Oh ok cool. Great job with fastlane (again), it really is a pleasure to use.

**Comment by KrauseFx** [comment]
I like your commit messages :stuck_out_tongue_winking_eye:

**Comment by czechboy0** [comment]
Haha I was editing it all straight here on GitHub, that's why there are so many commits :smile:

**Pull request merged**
