### PR TITLE
[resign] Fix typo in resign.rb

### PR DESCRIPTION
**Pull request by eduardopelitti**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes a typo in the documentation.

### Description

Add missing "g" to "provisioning"

Did not test at all.

### CODE REVIEW

**Review by minuscorp — APPROVED** [review]
Catch! 🚀

**Comment by eduardopelitti** [comment]
@googlebot I signed it!

**Review by joshdholtz — APPROVED** [review]
Thank you for catching this! ❤️

**Comment by joshdholtz** [comment]
@eduardopelitti Can you sign the CLA when you get a chance? 😊

**Comment by eduardopelitti** [comment]
@googlebot I signed it!

Just gave it another try @joshdholtz, I was waiting for my company representatives to complete the company form. Hope it works this time.

**Comment by joshdholtz** [comment]
@eduardopelitti Looks like you are good now (the bot just isn't updating this). Thank you!!

**Pull request merged**
