### PR TITLE
[snapshot] Fix grouping for iPad Pro 12.9-inch (3rd gen) in sc…

### PR DESCRIPTION
**Pull request by claesjacobsson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
When generating screenshots for `iPad Pro (12.9-inch) (3rd generation)`, in `screenshots.html` they were grouped with other iPad Pro 12.9 inch generations. This has now been fixed.

Solves issue #14085

### Description
Added a row for the `iPad Pro (12.9-inch) (3rd generation)` in   `xcode_9_and_above_device_name_mappings` of `reports_generator.rb`.

Tested manually with a few different snapfiles. Ran tests (see above).

### CODE REVIEW

**Comment by claesjacobsson** [comment]
Do I need to add something to this PR?

**Comment by janpio** [comment]
No, just someone from the team needs to find the time to test this out (or be confident enough on code alone) to be able to leave an "Approve" review and then merge this.

**Review by mollyIV — APPROVED** [review]
Hey @claesjacobsson 👋 

Thank you for creating this PR 🙇 

I was testing the changes from your branch. Created the following `Snapfile`: 

```
// Snapfile
devices([
  "iPad Pro (12.9-inch)", "iPad Pro (12.9-inch) (2nd generation)", "iPad Pro (12.9-inch) (3rd generation)"
])

languages(['en-US'])

output_directory("./screenshots")
clear_previous_screenshots(true)
```

I made a quick summary screenshot from the results below:

Screen Shot 2019-06-27 at 21 38 43

`iPad Pro (12.9-inch) (3rd generation)` has now a dedicated section in the `screenshots.html` report, well done 👍:clap:  🎊

**Comment by claesjacobsson** [comment]
👍🏻

**Comment by janpio** [comment]
(If you have the time, you could look at https://github.com/fastlane/fastlane/issues/14951#issuecomment-506531575 @claesjacobsson - same area of the code again)

**Pull request merged**
