### PR TITLE
[snapshop] update example  devices included with xcode 13.1

### PR DESCRIPTION
**Pull request by dweekly**
The example devices (6s & iPad Air) are old enough that this demo won't work out of the box anymore with a modern XCode (13.1); suggest updating these to simulators running a current OS (iOS 15.0) and ones included with XCode.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]
Love this! Thank you for updating 😍 

But it does look like the tests fail so we need to figure that out first 🤷‍♂️

**Comment by joshdholtz** [comment]
@dweekly Sorry if you are getting spammed with these commits! I'm trying to get CircleCI to pass but its not finding the new simulators that you specified. I even tried creating all the simulators and its still not working 😔

**Comment by lucgrabowski** [comment]
Aren't those tests failing because those 2 devices are not on list of mocked available simulators? @joshdholtz 
https://github.com/fastlane/fastlane/blob/master/snapshot/spec/test_command_generator_spec.rb#L4-L19

**Comment by joshdholtz** [comment]
@lucgrabowski OMG... I had no idea that existed but that makes so much sense 😛 That is _EXACTLY_ what needs to chance 🙃

**Comment by lucgrabowski** [comment]
@joshdholtz I finally found a way to push the commit with fixed tests - I pushed it to branch in fastlane repository, pulled changes from upstream branch to fork and pushed it to fork.

**Review by joshdholtz — APPROVED** [review]
This is 🔥 So happy this is fixed! And that I learned how snapshot's tests actually work now 😉

**Pull request merged**
