### PR TITLE
Add option to provide -framework option for archive Carthage command

### PR DESCRIPTION
**Pull request by Antondomashnev**
This PR is addressing that [issue](https://github.com/fastlane/fastlane/issues/6061)

### CODE REVIEW

**Comment by Antondomashnev** [comment]
According to the answer in question https://github.com/Carthage/Carthage/issues/1501, I'd like to add  additional parameter `--output` and add also an array of frameworks support before merging.

**Comment by Antondomashnev** [comment]
Ops, I think rebasing master was not a good idea =(

**Comment by Antondomashnev** [comment]
@KrauseFx not sure if the CI failure is related to my code

**Comment by KrauseFx** [comment]
Could you rebase from master, and resolve the merge conflict? This should fix the build error 👍

**Comment by Antondomashnev** [comment]
@KrauseFx any chance this would be merged soon? Thanks 😉

**Review by milch — APPROVED** [review]
@Antondomashnev sorry for the delay, but this looks good to me! 

@KrauseFx anything that keeps this from being merged?

**Comment by Antondomashnev** [comment]
@milch looking forward to seeing it merged 🎉

**Comment by milch** [comment]
Just merged it now, thanks a lot for your contribution! 🚀 

And sorry again for the long wait. I hope it won't discourage you from contributing to fastlane in the future.

**Comment by 0xced** [comment]
⚠️ `Numeric#positive?` was introduced in Ruby 2.3.0 so specs don’t pass on Ruby < 2.3.0. Using `n > 0` instead of `n.positive?` is obviously fine.

**Comment by milch** [comment]
Huh, that's what you get for only testing on 2.3... I'll submit a PR in a second.

**Comment by Antondomashnev** [comment]
@0xced @milch I guess I've used it because of the `rubocop` warning, but I'm not 💯 sure

**Pull request merged**
