### PR TITLE
[snapshot] Introduce option to select screen screenshot method

### LINKED ISSUE #14555: Snapshot screenshoting method to make device screenshot
#### Motivation Behind Feature
I'd like to produce screenshots w/ notch (and other elements that are now excluded with current method)

#### Feature Description
Now screenshot is done by making a screenshot of first window, though it captures only the content without notch, extended margins (if layout does not support iPad Pro 3rd generation), etc.

https://github.com/fastlane/fastlane/blob/875e3482906044a4f9806dc869c8813d3a2e9a57/snapshot/lib/assets/SnapshotHelper.swift#L177
has to be replaced with
```swift
let screenshot = XCUIScreen.main.screenshot()
```

But I assume the change should be backwards compatible so this feature should be hidden under some option passed to `capture_ios_screenshots` lane.
I've already prepared a solution so if you'll approve I'll make PR.

#### Alternatives or Workarounds
Currently I have `SnapshotHelper.swift` modified locally.

### PR DESCRIPTION
**Pull request by viktorasl**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixed #14555.

### Description
I didn't find a better way to pass configuration so chose to create `configuration.json` file currently containing only a single param (maybe in the future it could be used to pass any predefined or/and custom params)

### CODE REVIEW

**Comment by joshdholtz** [comment]
@viktorasl I can't seem to run this to get any different results 🤔 Would you be able to post some sample screenshots of what I should be looking for? 🙃

**Comment by viktorasl** [comment]
The difference is shown in lined issue. Did you try running it on `iPhone X`. The main difference is the notch indicator.

**Comment by viktorasl** [comment]
@joshdholtz any thoughts about this? I can close it now as we started supporting iPad's with notches and we don't need this fix anymore but the PR is still hanging and I would like to determine the future of this.

**Comment by getaaron** [comment]
I'm going to close this since it seems it's not needed and it has several conflicts. Feel free to reopen a PR and tag me if you'd like us to take another look 👍

**Pull request closed without merging**
