### PR TITLE
[deliver,frameit] frame latest iOS devices, skip uploading iPhone61

### PR DESCRIPTION
**Pull request by daveanderson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Note: Continuation of https://github.com/fastlane/fastlane/pull/13368

Implement support for the latest Apple devices

### Description

Added support for iPhone XR, iPhone XS, iPhone XS Max. Added new resolutions, added option to use legacy iPhone X instead iPhone XS, changed default 5.8" device to iPhone XS

--- 

closes #13368

### CODE REVIEW

**Comment by daveanderson** [comment]
@mirkokg Can you please approve use of your commits in this PR?

**Review by mirkokg — APPROVED** [review]

**Comment by joshdholtz** [comment]
@daveanderson Thanks for adding this! I'm working on testing this but I also added the new frames to the `frameit-frames` repo - https://github.com/fastlane/frameit-frames/pull/5

This should add to this PR and allow for actually using the new frames with the new color

**Review by joshdholtz — CHANGES_REQUESTED** [review]

**Comment by joshdholtz** [comment]
@daveanderson Are you cool if I throw some commits onto here? 😊

**Review by mirkokg — APPROVED** [review]

**Review by mirkokg — APPROVED** [review]

**Comment by joshdholtz** [comment]
@daveanderson I added a commit to this 💪 If you want to let me know what you think that would be 💯

1. Prevent `iPhone61` from being uploaded to App Store Connect because unsupported devices
2. Add/updated `offsets.json` for all new devices
3. Added new functionality for filtering out of devices in `deliver` that aren't supported by App Store Connect

screen shot 2018-12-04 at 10 11 55 am

**Review by mirkokg — APPROVED** [review]

**Review by mirkokg — APPROVED** [review]

**Review by mirkokg — APPROVED** [review]

**Review by mirkokg — APPROVED** [review]

**Review by mirkokg — APPROVED** [review]

**Comment by KrauseFx** [comment]
@mirkokg we will need one more approval to merge this 😂

**Comment by daveanderson** [comment]
Thanks for the addition @joshdholtz ⭐️

**Comment by daveanderson** [comment]
@joshdholtz Can you approve. I believe your commit resolved your own review concern.

**Comment by daveanderson** [comment]
@KrauseFx Anything holding this up? @joshdholtz committed a change to address his own request for changes.

**Review by janpio — APPROVED** [review]
I fixed a merge conflict.

Looks good to me now!

**Review by mirkokg — APPROVED** [review]

**Comment by stevekohls** [comment]
@joshdholtz is there anything holding up approval for this? I discovered this PR the other week when I was getting ready to submit screenshots. Would be nice to have it released.

Thanks everyone for making this happen!

**Comment by justJS** [comment]
Any update on this? It's been a while and would be nice to have this for my new app update! It's a great PR so I can't wait for it to be released.

**Comment by pds1977** [comment]
On Sat, 12 Jan 2019 at 04:56, Julian Schiavo <notifications@github.com>
wrote:

> Any update on this? It's been a while and would be nice to have this for
> my new app update! It's a great PR so I can't wait for it to be released.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
From

Paul Stoneham.

**Review by joshdholtz — APPROVED** [review]

**Pull request merged**
