### PR TITLE
[action] pod_lib_lint: Add support for use_module_headers and subspecs

### PR DESCRIPTION
**Pull request by raymondhoagland**
Adds parameters to support subspecs and using module headers.  Also adds environment variables for each of the parameters.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Adds additional parameters to support underlying options of the lint command.  Namely, it adds support for the [--use-module-headers](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/lib/lint.rb#L24) and [--subspsec](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/lib/lint.rb#L19) options.

Additionally, it adds environment variables for each of the supported parameters for convenience.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@raymondhoagland Heyyy! It looks like we have some merge conflicts! Do you mind resolving these? 😊

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@raymondhoagland Heyyy! It looks like we have some merge conflicts! Do you mind resolving these? 😊

**Comment by raymondhoagland** [comment]
@joshdholtz Hey! Should be all good now.

**Review by joshdholtz — APPROVED** [review]
This looks great! Thanks for adding the new options and cleaning up this code ❤️

**Pull request merged**
