### PR TITLE
Replace raise with UI.crash calls

### PR DESCRIPTION
**Pull request by lacostej**
I replaced all 

```
raise "something".red 
```

with

```
UI.crash!("something")
```

there are more raise "" calls that I haven't converted.

I can also convert them automatically if you think it is required. (at least the one under actions ?)
And I can do the same with other modules.

### CODE REVIEW

**Comment by jcampbell05** [comment]
How would one handle a crash under the new system (If for instance it was a recoverable error).

**Comment by lacostej** [comment]
Maybe this isn't a good idea after all.

This isn't meant to be used like that. Closing

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (447/400 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:52127 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmPh-000bWg-7k
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:41:27 +0100
Date: Tue, 15 Mar 2016 03:40:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458038440;
	bh=Gu4rVCTy3snDh7Sm69gidKMfat+8HULrlng9TcSss1M=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fiLx5dQzT4cvWp5DeZkvWGc2ECn1eQ2yEtkJ5Kvcg1tLOv9EBnTbi5F4AhzkPusGB
	 wULMSs/G5N8CRbRF7vkqBCcT/slCXagp1wnX7vE/n6Kz0MyO6uiJ1yPjAIdKcd8JLs
	 73nwUnR7F1hxwFM4P+FRHjLHQwsEuwu4oCgKwDzQ=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (448/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:42477)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1afmPm-000bXZ-Jl
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:41:31 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=jFOkcl4ELpemGhngi/fMbA7LwYg=; b=TUleFlFsKKkpw+8f
	q+1/fOMmROQFD9ix9lwAAy8H80he+6oz2U5W94A3QyfoJXMB+A/OVvZYJqoEG+X0
	RvfM8fGqmQKRLpkTHWtb0gDlOxrz1BPK86NC9nxbhsbXtR3A8fHzUrvhnNfddRHe
	o1e7acIe+29r9vSZ3bF/cY2VF9k=
Received: by filter0825p1mdw1.sendgrid.net with SMTP id filter0825p1mdw1.21753.56E7E6A84
        2016-03-15 10:40:40.046961729 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 7OZUHw-wRvO4kYlWi9uD4A
	for <yann.dupuy@zyapps.com>; Tue, 15 Mar 2016 10:40:40.084 +0000 (UTC)
Date: Tue, 15 Mar 2016 03:40:39 -0700

**Pull request closed without merging**
