### PR TITLE
Add `pilot distribute` to release latest build to testflight

### PR DESCRIPTION
**Pull request by tmm1**
```
$ export PILOT_CHANGELOG="..."
$ pilot distribute
[16:19:40]: Login to iTunes Connect
[16:19:42]: Login successful
[16:19:49]: Distributing build 1.0.0(6.16.2055) from Internal -> External
[16:19:50]: Successfully set the changelog for build
[16:19:50]: Distributing new build to testers
[16:20:01]: Successfully distributed build to beta testers 🚀
```

```
$ pilot distribute
[16:20:40]: Login to iTunes Connect
[16:20:43]: Login successful

[!] Build 1.0.0(6.16.2055) has already been distributed.
```

### CODE REVIEW

**Comment by ohwutup** [comment]
Hey @tmm1 this looks really great! Would you mind just rebasing on master and pushing up again to see if that will fix the CI issue? Also, it might be nice to get some testing in for this before we merge! 📓 🚀 !

**Comment by tmm1** [comment]
Rebasd.

**Comment by ohwutup** [comment]
hey @tmm1 looks like there is still something wrong with rubocop. would you mind running `rubocop -D` in your local repo and make any changes necessary?

**Comment by tmm1** [comment]
I'm not sure what this means or how to fix it.

```
Offenses:

lib/pilot/commands_generator.rb:45:5: C: Assignment Branch Condition size for run is too high. [65.39/60]
    def run
    ^^^

15 files inspected, 1 offense detected
[[FAILURE]] with repo 'pilot' due to

Command failed with status (1): [bundle exec rubocop...]
```

**Comment by KrauseFx** [comment]
If you run `rubocop -D` it will show you the cop name. Then go ahead and add 
`rubocop:disable [cop name]` 
and
`rubocop:enable [cop name]` (at the end)

**Comment by tmm1** [comment]
rubocop failures have been addressed.

**Comment by ohwutup** [comment]
🚀 💯 🚀  Thanks @tmm1 !

**Pull request merged**
