### PR TITLE
Add ToolingAndDebugging.md to help with debugging fastlane

### PR DESCRIPTION
**Pull request by KrauseFx**
This will make it easier for everyone to contribute to _fastlane_  🚀

### CODE REVIEW

**Comment by milch** [comment]
Do we wanna put all the *.md files into a separate folder?

**Comment by milch** [comment]
e.g. Make a separate `CONTRIBUTING` folder, since the `CONTRIBUTING.md` links to those documents anyway

**Comment by KrauseFx** [comment]
@milch I'm ok either way. I just thought we wanted better visibility, and therefore have it in the roof to of the directory.

**Comment by milch** [comment]
My thoughts were just that we have a lot of *.md files in the root already, so that could decrease visibility for contributors

**Review by mfurtak — APPROVED** [review]
Merge when ready. 👍  I think we should chat about whether we care about naming consistency afterwards.

**Pull request merged**
