### PR TITLE
Add a retry option on getting builds for a train

### PR DESCRIPTION
**Pull request by ohayon**
Sometimes intermittent 502s happen while the build watcher is waiting for the build to finish processing and show up in the list of available builds. We shouldnt fail the build watching process for that, we should just try again a couple of times to continue to wait for the build

I tested this locally but can't fudge a 500 in the middle of the waiting process, so assuming no 500's come in, this will continue to work as it always has.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Spaceship::TestFlight::Build collections .builds_for_train returns the builds for a given train version | <a href='https://github.com/fastlane/fastlane/blob/96613434d97c940bdbc16b1bff4b0fb0f2846944/./spaceship/spec/test_flight/build_spec.rb'>build_spec.rb</a>|
Spaceship::TestFlight::Client#handle_response raises an exception on a HTTP error | <a href='https://github.com/fastlane/fastlane/blob/96613434d97c940bdbc16b1bff4b0fb0f2846944/./spaceship/spec/test_flight/client_spec.rb'>client_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Spaceship::TestFlight::Client#handle_response raises an exception on a HTTP error | <a href='https://github.com/fastlane/fastlane/blob/6f55b4798189e3ceeb1cfd01c5965445abfc974c/./spaceship/spec/test_flight/client_spec.rb'>client_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by taquitos — APPROVED** [review]
🐑  Nice one!

**Review by KrauseFx — COMMENTED** [review]
Awesome, extra 👍 for adding a test

**Pull request merged**
