### PR TITLE
New changelog_from_last_tag action.

### PR DESCRIPTION
**Pull request by scottrhoyt**
I created this action because the existing `changelog_from_git_commits` did not serve my use case. We have different lanes for different types of releases (e.g. Dev, QA, Prod) and use the `git_add_tag` action to tag these releases. Using `changelog_from_git_commits` the changelog will only contain the commit messages since the last tag even if that tag exists in a different `grouping`, `lane`, or uses a different `prefix`. For us this means that our changelog for a new QA release won't contain all the changes since our last QA release if we have made and tagged a Dev or Prod release since then. This action solves this issue by using the same pattern as `add_git_tag` for searching for the last tag.

I have two questions:
1. Currently I am duplicating the pattern creation portion of `add_git_tag`, but perhaps this can be refactored into a commonly accessible function to avoid duplication and keep the actions consistent in event of a change?
2. I would like to use the same output (`FL_CHANGELOG`) as `changelog_from_git_commits` so that there can be a common lane value for other actions to use. I am currently doing this by overriding `FL_CHANGELOG` in my `SharedValues` as well, but perhaps we can declare `FL_CHANGELOG` or simply just `CHANGELOG` in [actions_helper](https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/actions_helper.rb) to facilitate multiple actions that might want to set a common changelog? If so, I can make the changes necessary to accomplish this.

### CODE REVIEW

**Comment by scottrhoyt** [comment]
Also, what do you think about the action name? Should it be changed to be less vague or to differentiate from `changelog_from_git_commits`?

**Comment by scottrhoyt** [comment]
I went ahead and laid claim to the `CHANGELOG` shared valued since the test on Travis was throwing warnings about the redeclaration.

**Comment by scottrhoyt** [comment]
Let me know what you think about this @mfurtak and @asfalcone.

**Comment by mfurtak** [comment]
Hi @scottrhoyt - thanks for putting this together! :+1: 

We'll definitely take a look, but I wanted to let you know that some folks (including me) are on vacation until the new year, so it will probably be another week or so until we review. Apologies for the delay, and have a happy new years! :tada: :confetti_ball:

**Comment by mfurtak** [comment]
Hey @scottrhoyt - I've read this over. Thanks again!

If I'm understanding correctly, the main thing you are looking to affect is the tag selection process when determining how far back to collect messages for, is that right?

I'm curious whether the `changelog_from_git_commits` action can work for you if the tag naming logic you grabbed from `add_git_tag` is used to feed the right tag name as input. Just as a test, if you were to do something like...

```ruby
#...
lane_name = Actions.lane_context[Actions::SharedValues::LANE_NAME].delete(' ')
build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
tag = "builds/#{lane_name}/#{build_number}"

changelog_from_git_commits(between: [tag, 'HEAD'])
#...
```

does that meet your needs? If so, I think it would be great to get the default tag selection logic internal to `changelog_from_git_commits` to match this strategy as you've laid out.

**Comment by scottrhoyt** [comment]
I think that would work, that's more or less what I did anyway. :)

**Comment by mfurtak** [comment]
Hi @scottrhoyt - we've been doing some more thinking and planning and I think we'd like to support this use case by extending the capability of the existing `changelog_from_git_commits` action.

Apologies for the long time in limbo on this PR. I hope we can have some good news about solving the use case soon! :+1:

**Comment by scottrhoyt** [comment]
Thanks. No rush because my action is working well for me.

**Comment by mfurtak** [comment]
Excellent! Just out of curiosity - are you using this as a local extension?

**Comment by scottrhoyt** [comment]
Yeah. I've always loved that feature. :)

**Comment by mfurtak** [comment]
Awesome. I wanted to get a feel for how aware folks were of it!

**Comment by scottrhoyt** [comment]
I don't think enough. IMO this should be moved to the main README. Anecdotally, some people seem to not know it exists and build `lane`s that really should be `action`s.

**Pull request closed without merging**
