### PR TITLE
[doc][crashlytics] DeprecationMessage

### PR DESCRIPTION
**Pull request by oingbong**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
duplication Message

### Description
in https://docs.fastlane.tools/actions/crashlytics/
```
Crashlytics Beta has been deprecated and replaced with Firebase App Distribution.
Beta will continue working until May 4, 2020.
Check out the Firebase App Distribution docs to get started.

Crashlytics Beta has been deprecated and replaced with Firebase App Distribution.
Beta will continue working until May 4, 2020.
Check out the Firebase App Distribution docs to get started.

Additionally, you can specify notes, emails, groups and notifications.
Distributing to Groups: When using the groups parameter, it's important to use the group alias names for each group you'd like to distribute to. A group's alias can be found in the web UI. If you're viewing the Beta page, you can open the groups dialog by clicking the 'Manage Groups' button.
.....
```

### CODE REVIEW

**Comment by oingbong** [comment]
@googlebot I signed it!

**Comment by oingbong** [comment]
What should i do for passing test? plz

**Comment by oingbong** [comment]
@janpio Thank you for that reopen issue

**Review by joshdholtz — APPROVED** [review]
Good catch! Thanks for the contribution 😊

**Comment by oingbong** [comment]
@joshdholtz  Thanks for approved !

**Comment by joshdholtz** [comment]
No problem! Sorry it took so long 😇

**Pull request merged**
