### PR TITLE
Improve GitHub Issue and Pull Request templates

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Hoping that people would see the last (correct) way to check the boxes.

Related to #10992.

### CODE REVIEW

**Review by janpio — COMMENTED** [review]
We should A/B test this...

**Review by janpio — APPROVED** [review]

**Comment by revolter** [comment]
If only we could

**Comment by janpio** [comment]
Compare issues created over x days with old version, measure "correcteness of [x] usage", with same measurement over x days with new version. Close enough ;)

**Comment by revolter** [comment]
Damn, I broke the statistics, I've edited some people's questions because of my [OCPD](https://en.wikipedia.org/wiki/Obsessive–compulsive_personality_disorder).

**Pull request merged**
