### PR TITLE
[spaceship] increase timeout for web session connect api to 1200

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Prevent some timeouts?

### Description
Another way to hopefully prevent some timeouts along with the retry

### CODE REVIEW

**Comment by Thangaraj-M** [comment]
@joshdholtz 
When uploading screenshot with deliver, there was timeout issue occurred. Due to this extra empty screenshot is uploaded to store. Can you say how to increase the timeout value? below is the log.

INFO [2020-07-21 07:54:42.12]: Uploading 8 screenshots for language en-US
INFO [2020-07-21 07:54:42.20]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-CardDetails.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:54:48.71]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-MerchantsAlert.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:54:53.89]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-MerchantsControl.png'...
**Timeout received! Retrying after 3 seconds (remaining: 4)...**
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:57:02.53]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-SpendLimitControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:57:07.20]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-CardDetails.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:57:12.88]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-MerchantsAlert.png'...
**Timeout received! Retrying after 3 seconds (remaining: 4)...**
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:59:19.30]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-MerchantsControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:59:24.24]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-SpendLimitControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 07:59:29.04]: [32mSuccessfully uploaded screenshots to App Store Connect[0m

Below is the empty file shows in the appstore.
empty

**Comment by Thangaraj-M** [comment]
@joshdholtz 
There was timeout error occurred at the time of uptate placeholder of screenshot by the function **Spaceship::ConnectAPI.post_app_screenshot** in **app_screenshot.rb**. After that it retry again and another placeholder created and file is uploaded. Due to this empty placeholder is showing in the appstore. Can you please check this?
app_screenshot rb

**Comment by joshdholtz** [comment]
@Thangaraj-M Can you try setting `ENV["SPACESHIP_TIMEOUT"] = 1500` and let me know if you see any different behavior? It looks like the file uploader code is still using 300 as the default where the rest of the Connect API is using 1200. If that works for you and I can change that default.

Thanks!

**Comment by Thangaraj-M** [comment]
@joshdholtz  I will try with increase the timeout.

**Comment by Thangaraj-M** [comment]
@joshdholtz I tried again with increase the spaceship timeout value with 1500. But still Timeout error occurred. below is the log.
It looks the timeout occurred in the placeholder update API. The timeout occurred within 2 minutes.

INFO [2020-07-21 20:00:38.90]: Uploading 8 screenshots for language en-US
INFO [2020-07-21 20:00:38.91]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-CardDetails.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:00:44.30]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-MerchantsAlert.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:00:48.79]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-MerchantsControl.png'...
**Timeout received! Retrying after 3 seconds (remaining: 4)...**
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:02.41]: Uploading 'fastlane/output/screenshots/en-US/iPhone 7 Plus-SpendLimitControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:05.75]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-CardDetails.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:10.60]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-MerchantsAlert.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:14.40]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-MerchantsControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:18.75]: Uploading 'fastlane/output/screenshots/en-US/iPhone XS Max-SpendLimitControl.png'...
Uploading file (part 1)...
Uploading complete!
INFO [2020-07-21 20:03:23.18]: Successfully uploaded screenshots to App Store Connect

**Comment by Thangaraj-M** [comment]
@joshdholtz The timeout issue occurred at the time of distributing build also. So the whats new value is not updated. below is the log. Here within 2 minutes 5 times retry happened.
INFO [2020-07-21 06:53:51.14]: [32mSuccessfully finished processing the build 3.10.1 - 13 for IOS[0m
INFO [2020-07-21 06:55:48.16]: [32mSuccessfully set the changelog for build[0m
INFO [2020-07-21 06:55:49.22]: Distributing new build to testers: 3.10.1 - 13
Timeout received! Retrying after 3 seconds (remaining: 4)...
Timeout received! Retrying after 3 seconds (remaining: 3)...
Timeout received! Retrying after 3 seconds (remaining: 2)...
Timeout received! Retrying after 3 seconds (remaining: 1)...
Timeout received! Retrying after 3 seconds (remaining: 0)...
call_with_defaults Exception is... Server error got 500
Logger: Upload to testflight lane completed 2020-07-21 06:57:54.928

**Comment by Thangaraj-M** [comment]
@joshdholtz It looks the timeout value is not taken from SPACESHIP_TIMEOUT variable. Could you please say what is wrong?

**Comment by joshdholtz** [comment]
@Thangaraj-M Can you give this PR a try? https://github.com/fastlane/fastlane/pull/16912

**Comment by Thangaraj-M** [comment]
@joshdholtz  I will try this and update the result.

**Comment by Thangaraj-M** [comment]
@joshdholtz I updated from the branch and checked again. There was timeout occurred at the time distributing build. Not sure it running from the latest updated branch or the old one. Is there any way to check the build running from new branch or existing one? In the summary it showing 2.152.0 only.
 **[32mdeliver 2.152.0 Summary[0m**

**Comment by joshdholtz** [comment]
@Thangaraj-M The contents of your `Gemfile.lock` should show the fastlane as being remote and should have the URL in there. Also, can we move this conversation into the PR? 😇

**Comment by Thangaraj-M** [comment]
yes. I will reply in that PR

**Pull request merged**
