### PR TITLE
[fastlane_core] Added tests for certificate import

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/4798 kind of

### CODE REVIEW

**Comment by mfurtak** [comment]
LGTM.

I also noticed the nil expectation warning, but it didn't seem better to me to execute something arbitrary to make the warning go away. Is there a reason we know of that this is actually better, or does it just _feel_ better?

**Comment by KrauseFx** [comment]
Not sure how `rspec` behaves, but what I understood is that it might actually mock a method on the `nil` class? Not sure though, better to listen to warnings, there is usually some reason behind it

**Comment by mfurtak** [comment]
I wonder if we should introduce another helper method for getting the last command status? Working with `$?` in tests seems like it makes it hard to do the right thing.

If we use something like `Helper.last_process_status` in our code (which just returns `$?`), we can always safely mock `Helper` in our tests...

**Comment by KrauseFx** [comment]
Should we merge this, and work on the `last_process_status` on a separate PR?

**Comment by mfurtak** [comment]
👍

**Pull request merged**
