### PR TITLE
Disabled .plist extension verification

### PR DESCRIPTION
**Pull request by RishabhTayal**
Fixes: #12088

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Can you add tests around handling when this path contains invalid plist content? 🙃

**Comment by RishabhTayal** [comment]
@joshdholtz test case is added. Ready for review again. 👍

**Comment by joshdholtz** [comment]
After thinking about this comment - https://github.com/fastlane/fastlane/issues/12088#issuecomment-374511298 -  I think that the name of this action _may_ be a bit misleading now 🤔 

I **think** it makes the most sense to pull this logic out into a helper and then...
- Update `update_info_plist` to use the helper
- Update `update_app_group_identifiers` to use the helper
- Update `update_icloud_container_identifers` to use the helper
- Add new action `update_entitlements`to use the helper (what this PR is really for)

^ This will make it easy for users to look for things they want to do while using shared plist code

This is probably a decent amount of work so I can take over from here if you'd like 🙃

**Comment by RishabhTayal** [comment]
@joshdholtz I don't think we should restrict the file extensions to be only `.plist`. The `.entitlements` file is a valid plist file so I don't see a reason why we would restrict the file extensions.

**Comment by joshdholtz** [comment]
@RishabhTayal I don't think we should either but the name of this action is `update_info_plist` and entitlements isn't an "Info.plist" which is where things start to get weird

**Comment by RishabhTayal** [comment]
I agree too. I know you are not going to like hearing this but how about we change it to `update_plist`.

**Comment by RishabhTayal** [comment]
@joshdholtz Where do we stand with the decision on what to do? Are we creating a new helper function and new action for this?

**Comment by joshdholtz** [comment]
@RishabhTayal We can't change this action _specifically_ to be `update_plist` since that would break soooooooo many other systems. I would _could_ create a new action called `update_plist` which `update_info_plist` would use. I think that would be okay 👍

**Comment by RishabhTayal** [comment]
@joshdholtz Sounds like a plan to me. Do you think this is something I could take, If it's not too complicated?

**Comment by RishabhTayal** [comment]
You may close this PR now.

**Comment by joshdholtz** [comment]
@RishabhTayal I would be down for a PR for this if you have time 🙃 If not, I totally understand 😉

**Pull request closed without merging**
