### PR TITLE
[trainer] check specifically for file url in failure_message, fixing crash in Xcode 15 when running in Apple Silicon

### LINKED ISSUE #21475: Trainer not working with Xcode 15 beta 6
<!-- Thanks for helping fastlane! Before you submit your issue, please make sure you followed our checklist and check the appropriate boxes by putting an x in the [ ]: [x] -->

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
<!-- Please include what's happening, expected behavior, and any relevant code samples -->
Using `trainer` with Xcode 15 beta 6 doesn't appear to work. I first ran into this issue when running on an M1 on CircleCI, but this is also a local issue on my machine, also running an M1.

##### Command executed
<!-- The command you executed on the command line that resulted in an error -->
Here's the lane I'm attempting to run with no modifications from running it with Xcode 14
```
desc "Upload test reports"
	lane :upload_test_reports do
	trainer
end
```
I then simply run `fastlane upload_test_reports` from the command line and you can see the output I get below

##### Complete output when running fastlane, including the stack trace and command used
<!-- 
You can use `--capture_output` as the last command line argument for many commands to get that collected for you. Otherwise, please do it manually.
Caution: The output of `--capture_output` could contain sensitive data such as application ids, certificate ids, or email addresses. Please make sure you double check the output and replace anything sensitive you don't wish to submit in the issue 
-->

<details>
  <pre> [✔] 🚀 
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                            Used plugins                                                                                                                                                             |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Plugin                                    | Version | Action                                                                                                                                                                                                                                                                        |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| fastlane-plugin-firebase_app_distribution | 0.7.2   | firebase_app_distribution, firebase_app_distribution_add_testers, firebase_app_distribution_create_group, firebase_app_distribution_delete_group, firebase_app_distribution_get_latest_release, firebase_app_distribution_get_udids, firebase_app_distribution_remove_testers |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

[14:36:41]: ------------------------------
[14:36:41]: --- Step: default_platform ---
[14:36:41]: ------------------------------
[14:36:41]: Driving the lane 'ios upload_test_reports' 🚀
[14:36:41]: ---------------------
[14:36:41]: --- Step: trainer ---
[14:36:41]: ---------------------

+------------------------------+-------+
|     Summary for trainer 2.214.0      |
+------------------------------+-------+
| path                         | .     |
| extension                    | .xml  |
| fail_build                   | true  |
| xcpretty_naming              | false |
| silent                       | false |
| output_remove_retry_attempts | false |
+------------------------------+-------+

+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios upload_test_reports |
+------------------+-------------------------+

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | trainer          | 0           |
+------+------------------+-------------+

[14:36:41]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  sigh repair fails with "undefined method `id' for nil:NilClass (NoMethodError) certificates.map(&:id)" with Apple Distribution certificate type
    https://github.com/fastlane/fastlane/issues/21295 [open] 2 💬
    24 May 2023

➡️  [supply] added support for refresh tokens as an authentication method
    https://github.com/fastlane/fastlane/pull/16414 [open] 10 💬
    23 May 2020

➡️  Unable to upload to testflight using Xcode 14 beta
    https://github.com/fastlane/fastlane/issues/20371 [closed] 150 💬
    17 May 2023

and 24 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60gsub%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/3.2.0/bin/fastlane)
/Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/xcresult.rb:395:in `failure_message': [!] undefined method `gsub' for nil:NilClass (NoMethodError)

          file_path = self.document_location_in_creating_workspace.url.gsub("file://", "")
                                                                      ^^^^^
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:278:in `block (2 levels) in summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:244:in `map'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:244:in `block in summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:236:in `map'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:236:in `summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:225:in `parse_xcresult'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:105:in `initialize'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:82:in `new'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:82:in `block in auto_convert'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:53:in `each'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:53:in `auto_convert'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/trainer.rb:11:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:30:in `block (2 levels) in parsing_binding'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/bin/fastlane:25:in `load'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/bin/fastlane:25:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:491:in `exec'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/distiller/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
/Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/xcresult.rb:395:in `failure_message': undefined method `gsub' for nil:NilClass (NoMethodError)

          file_path = self.document_location_in_creating_workspace.url.gsub("file://", "")
                                                                      ^^^^^
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:278:in `block (2 levels) in summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:244:in `map'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:244:in `block in summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:236:in `map'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:236:in `summaries_to_data'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:225:in `parse_xcresult'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:105:in `initialize'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:82:in `new'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:82:in `block in auto_convert'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:53:in `each'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/trainer/lib/trainer/test_parser.rb:53:in `auto_convert'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/trainer.rb:11:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:30:in `block (2 levels) in parsing_binding'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/bin/fastlane:25:in `load'
	from /Users/distiller/project/vendor/bundle/ruby/3.2.0/bin/fastlane:25:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:491:in `exec'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/distiller/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/distiller/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
 </pre>
</details>

### Environment

<!-- 
Please run `fastlane env` and copy the output below. This will help us help you.
If you used the `--capture_output` option, please remove this block as it is already included there. 
-->

<details>
  <pre> [✔] 🚀 
[14:39:35]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.87.1 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 13.5                                            |
| Ruby                        | 3.2.2                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.41.0                              |
| Installation Source         | ~/project/vendor/bundle/ruby/3.2.0/bin/fastlane |
| Host                        | macOS 13.5 (22G74)                              |
| Ruby Lib Dir                | ~/.rbenv/versions/3.2.2/lib                     |
| OpenSSL Version             | OpenSSL 3.1.1 30 May 2023                       |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-15.app/Contents/Developer/  |
| Xcode Version               | 15.0                                            |
| Swift Version               | 5.9                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	desc "Update profiles with any new registered devices."
	  lane :update_code_signing_with_new_devices do
	    # add actions here: https://docs.fastlane.tools/actions
	    match(
	    	type: "development",
	    	force_for_new_devices: true)
	end

	desc "Upload test reports"
		lane :upload_test_reports do
  		trainer
	end
	
	lane :increment_version do
		setup_circle_ci
		latest_release = firebase_app_distribution_get_latest_release(
		  app: ENV['xxxxxx'],
		)
		increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1,
								 xcodeproj:"xxxxxx/xxxxxx.xcodeproj" })
	  end

    desc "Upload to Firebase App Distribution"
    lane :upload_firebase do |options|
	    setup_circle_ci
        match(
            type: "enterprise",
            readonly: true,
            app_identifier: ["xxxxxxxx"]
        )
        gym(
            scheme: "xxxxxx",
     	    export_method: "enterprise",
            export_options:{
                signingStyle: "manual",
                provisioningProfiles:{
                    "xxxxxxxxx"
                }
            }
                
        )
	    firebase_app_distribution(
			app: ENV['xxxxxx'],
			firebase_cli_token: ENV['xxxxxx'],
        	release_notes: options[:release_notes],
			groups: "all-testers",
			ipa_path: "/Users/distiller/project/xxxxxx.ipa"
	    )
    end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("xxxxxxx") # The bundle identifier of your app
apple_id("xxxxxxx") # Your Apple email address

team_id "xxxxxxx"  # Developer Portal Team ID # "xxxxxxx" (In-House)

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.214.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.7.2   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| Redacted | Redacted |
</details>


*generated on:* **2023-08-22**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by TheMetalCode**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #21475 

### Description

It would appear that with Xcode 15 there are at least some cases where test failure data would not include a `url` property. Adjusting the check in `failure_message` to specifically verify the presence of `self.document_location_in_creating_workspace&.url` prior to attempting to append it to the failure message seems liek the most straightforward resolution.

### CODE REVIEW

**Review by rogerluan — COMMENTED** [review]
Thanks for this fix, @TheMetalCode ! 🙏 

I'd normally try to figure out what is causing this value to be nil, but it might genuinely be just a different behavior of the new Xcode 15, when run specifically on Apple Silicon.

I'm personally facing this issue in CircleCI Xcode 15 Apple Silicon and think this is a valid fix.

I wish we had unit tests to cover this case, could you look into adding tests to cover this scenario @TheMetalCode ? 🙏 Also, looks like CI is failing in this PR

**Comment by TheMetalCode** [comment]
@rogerluan Will add tests and address CI, hope to get to that this evening.

**Comment by jszumski** [comment]
@rogerluan @joshdholtz this PR fixes a crash against the GA version of Xcode 15, could you take a look when you have a moment? Thanks!

**Review by rogerluan — APPROVED** [review]
💪 thanks for fixing this

**Comment by raid5** [comment]
Excellent! When might we expect a new release?

**Comment by rogerluan** [comment]
Hard to tell for sure, but I think soon enough! Meanwhile you can point your fastlane gem to master to use this 🙏

**Comment by geoff-sheldon-bfg** [comment]
Does this fix the issue described in #21295 ?

**Comment by rogerluan** [comment]
I don't think so...? Why do you think they're related @geoff-sheldon-bfg ?

**Pull request merged**
