### PR TITLE
Fixes the initialization of the csrf cache.

### PR DESCRIPTION
**Pull request by sergiocampama**
Because @csrf_cache wasn't being initialized, it always used a new hash as the storage.
This means that no csrf headers were being reused, which forces the client to re-fetch them
for each request, slowing down the task.

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context
This makes tasks that make a lot of requests (like regenerating a bunch of provisioning profiles) faster by avoiding the 2 csrf fetch requests that are unnecessary.

Tested by logging connections using Charles Proxy and ensuring the csrf requests are not being repeated for each request.

### Description
Fixes the initialization of the csrf cache.

Because @csrf_cache wasn't being initialized, it always used a new hash as the storage.
This means that no csrf headers were being reused, which forces the client to re-fetch them
for each request, slowing down the task.

### CODE REVIEW

**Comment by ohayon** [comment]
Hey @sergiocampama ! Thanks for the PR! Would you mind just running `rubocop -aD` locally to fix up that build on Circle?

**Comment by sergiocampama** [comment]
looks like the error is unrelated to my change, but a missing file one...

I ran rubocop locally with -aD as you mentioned, and -D as Circle tests it, and both pass

**Comment by sergiocampama** [comment]
any updates on retrying that failing action?

**Comment by KrauseFx** [comment]
I triggered the build again 👍

**Comment by sergiocampama** [comment]
ping?

**Comment by AaronPatterson** [comment]
PR #10720 has the same fix plus a few others related to CSRF.

**Review by KrauseFx — APPROVED** [review]
Sorry for the delay - thanks for the PR, this will be in the next release 👍

**Pull request merged**
