### PR TITLE
[frameit] add support for new iPhone 12-family devices and their new colors

### PR DESCRIPTION
**Pull request by nimau**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Add support for new iPhone 12 devices (12, 12 Pro, 12 Pro Max, 12 Mini) to frameit

### Description

Add support for new iPhone 12 devices (12, 12 Pro, 12 Pro Max, 12 Mini) to frameit
- added 2 new colors in frameit/devices_type.rb (Graphite & Pacific Blue)
- added 4 new devices in frameit/devices_type.rb (iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 12 Mini)

Note: iPhone 12 Mini device screen size doesn't match the official Apple screen specification but the size of the screenshot generated with a iPhone 12 Mini simulator (1125x2436 instead of 1080x2340). When using official size, frameit doesn't match the screenshot with iPhone 12 Mini frame.

Related: https://github.com/fastlane/frameit-frames/pull/15

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/nimau/fastlane.git", :branch => "nimau-frameit-iphone12-devices"
```

And run `bundle install` to apply the changes.

### CODE REVIEW

**Comment by rogerluan** [comment]
Hey @nimau 👋 

Thanks for contributing to _fastlane_! Could you sign the CLA as asked by the bot up there? 🙏

**Comment by everlof** [comment]
In order to fully add support for `iPhone 12 Pro` and `iPhone 12 Pro Max` we probably need to add it to another map as well:

https://github.com/fastlane/fastlane/blob/cbfd2724de7b524f680be3e80a708c36297dbf3e/snapshot/lib/snapshot/reports_generator.rb#L87

**Comment by everlof** [comment]
When I try out this fix I get:

```
[✔] 🚀 
[16:36:13]: Using device frames version 'latest'
[⠋] Framing screenshot './screenshots/sv-SE/iPhone 12 Pro Max-0_CalendarsLaidOut.png' [16:36:13]: Unfortunately device type 'Apple iPhone 12 Pro Max' is not available in Pacific Blue, falling back to Graphite...
[16:36:13]: Couldn't find template for screenshot type 'Apple iPhone 12 Pro Max Graphite'
[16:36:13]: Please run `fastlane frameit download_frames` to download the latest frames
[⠋] Framing screenshot './screenshots/sv-SE/iPhone 12 Pro-0_CalendarsLaidOut.png' [16:36:13]: Unfortunately device type 'Apple iPhone 12' is not available in Pacific Blue, falling back to Black...
[16:36:13]: Couldn't find template for screenshot type 'Apple iPhone 12 Black'
[16:36:13]: Please run `fastlane frameit download_frames` to download the latest frames
[⠋] Framing screenshot './screenshots/en-US/iPhone 12 Pro Max-0_CalendarsLaidOut.png' [16:36:13]: Unfortunately device type 'Apple iPhone 12 Pro Max' is not available in Pacific Blue, falling back to Graphite...
[16:36:13]: Couldn't find template for screenshot type 'Apple iPhone 12 Pro Max Graphite'
[16:36:13]: Please run `fastlane frameit download_frames` to download the latest frames
[⠙] Framing screenshot './screenshots/sv-SE/iPhone 12 Pro Max-0_CalendarsLaidOut.png' [16:36:13]: Unfortunately device type 'Apple iPhone 12' is not available in Pacific Blue, falling back to Black...
[16:36:13]: Couldn't find template for screenshot type 'Apple iPhone 12 Black'
[16:36:13]: Please run `fastlane frameit download_frames` to download the latest frames
```

**Comment by rogerluan** [comment]
> Please run `fastlane frameit download_frames` to download the latest frames

@everlof this is likely because this PR is also dependent on merging this PR: https://github.com/fastlane/frameit-frames/pull/15

That should fix that issue I think 🤔

**Comment by rogerluan** [comment]
> In order to fully add support for `iPhone 12 Pro` and `iPhone 12 Pro Max` we probably need to add it to another map as well.
> 
> This map here that defines a mapping:
> 
> https://github.com/fastlane/fastlane/blob/cbfd2724de7b524f680be3e80a708c36297dbf3e/snapshot/lib/snapshot/reports_generator.rb#L87

@everlof could you share what key/value pairs you added to this file to make it work for you (since you already tested it)? 😊 
So that we can apply this change to this PR still. 🙏

**Comment by everlof** [comment]
@rogerluan Here's the fix that solved it for me:

```
+        'iPhone 12 Pro Max' => "iPhone 12 Pro Max",
+        'iPhone 12 Pro' => "iPhone 12 Pro",
```

**Comment by gertjanjansen** [comment]
> @rogerluan Here's the fix that solved it for me:
> 
> ```
> +        'iPhone 12 Pro Max' => "iPhone 12 Pro Max",
> +        'iPhone 12 Pro' => "iPhone 12 Pro",
> ```
> 
> But to be clear, I still got the errors above when I tried to use the new device-colour ("pacific blue").

This is because https://github.com/fastlane/frameit-frames/pull/15 is not merged yet. When you execute `fastlane frameit download_frames` it download the frames from the master branch @ https://github.com/fastlane/frameit-frames/tree/gh-pages/latest, which does not include the iPhone 12 frames yet.

One way to solve it (for now) is:
1) Find the folder where fastlane keeps the downloaded frames (for me that was `/Users/**username**/.fastlane/frameit/latest`
2) Replace that folder with the contents of https://github.com/fastlane/frameit-frames/pull/15/files

**Comment by rogerluan** [comment]
@googlebot I fixed it.

**Comment by rogerluan** [comment]
@nimau could you fix the CLA issues? 🙏

**Comment by nimau** [comment]
@googlebot I signed it!

**Comment by nimau** [comment]
@googlebot I consent.

**Comment by nimau** [comment]
@googlebot I consent.

**Comment by nimau** [comment]
@googlebot I signed it!

**Comment by nimau** [comment]
@googlebot I signed it!

**Comment by nimau** [comment]
> @nimau could you fix the CLA issues? 🙏

Sorry, there is a commit with my work email address. I've add it to my GitHub account and as a secondary email address to my google account, I've signed again the CLA but googlebot still don't want it.
I've no idea on how to fix this myself.

**Comment by nimau** [comment]
@googlebot I consent.

**Comment by rogerluan** [comment]
@nimau not sure either, maybe add your work email to your GitHub account as a secondary email?

If that doesn't work, you could open a new PR with the same content (but committed by yourself) 😅

Thanks for understanding and getting back to us! 🤗

**Comment by nimau** [comment]
@rogerluan I've just pushed a new PR #17940  (same one with proper @author email address).
I'll cancel this one.

**Comment by nimau** [comment]
Pull request closed (recreated #17940 with correct @author email address to match CLA)

**Pull request closed without merging**
