### PR TITLE
Cordova actions

### PR DESCRIPTION
**Pull request by blackjid**
Adds actions to retrieve the app name and identifier from the cordova `config.xml` file on a cordovoa project

some dicussion was done here https://github.com/fastlane/fastlane/pull/984

### CODE REVIEW

**Comment by blackjid** [comment]
we are using this actions in our base configuration for cordova here https://github.com/platanus/fastlane-cordova

**Comment by blackjid** [comment]
@ohwutup where is the PR we talked about

**Comment by blackjid** [comment]
I've just rebased the PR against master.

**Comment by KrauseFx** [comment]
Sorry for not coming back to your earlier. Thanks for updating the PR, this looks great. Could you just fix the merge conflicts, then we can merge the changes 👍

**Comment by blackjid** [comment]
hey @KrauseFx no problem, I already fix the merge conflicts..

**Comment by KrauseFx** [comment]
Hey @blackjid, first off, sorry for the delayed reply. We're currently working on a plugin system, so that you can maintain and distribute this action without us having to review and approve every change. 

You can read more about why over here https://github.com/fastlane/fastlane/issues/4744
and here's the pull request with the code we currently have https://github.com/fastlane/fastlane/pull/4722

I'd love your action to be one of the first available `fastlane` plugins. It will be listed on the fastlane main repo, so you get the same discoverability 👍 

I'll update this issue with more information about how to wrap your action into plugin over the next few days, it's really easy to do that 🚀 

Let me know if that sounds good to you!

**Comment by KrauseFx** [comment]
Hey @blackjid, great news, the plugin system is ready to be used, I'd love your feedback on how well it works for you and how you like the approach: [Get started with plugins](https://github.com/fastlane/fastlane/issues/4873)  🚀

**Comment by KrauseFx** [comment]
Alright, plugins were published today, please migrate this into a plugin. Let us know if you need any help doing so 👍

**Pull request closed without merging**
