### PR TITLE
Detect running Ruby version and fail early

### PR DESCRIPTION
**Pull request by KrauseFx**
See discussion and reasoning https://github.com/supermarin/xcpretty/commit/91c766f4c82541564297e958254ba5d920166cf5#commitcomment-20673493

### CODE REVIEW

**Comment by KrauseFx** [comment]
signed

**Comment by KrauseFx** [comment]
I signed it!

**Comment by KrauseFx** [comment]
😂

**Comment by KrauseFx** [comment]
I signed it!

**Review by lacostej — APPROVED** [review]

**Comment by hjanuschka** [comment]
best PR

**Pull request merged**
