### PR TITLE
[action] make xcode_select action's details clearer

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by janpio** [comment]
Are you sure `self.details` can be an array?

```
bundler: failed to load command: fastlane (/home/circleci/project/.bundle/ruby/2.3.0/bin/fastlane)
NoMethodError: [!] undefined method `gsub' for #<Array:0x000056097da2f9b8>
  (erb):17:in `block in actions_md_contents'
  /usr/local/lib/ruby/2.3.0/erb.rb:861:in `eval'
  /usr/local/lib/ruby/2.3.0/erb.rb:861:in `block in result'
  /usr/local/lib/ruby/2.3.0/erb.rb:862:in `result'
  /home/circleci/project/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb:125:in `block in actions_md_contents'
  /home/circleci/project/fastlane/lib/fastlane/documentation/actions_list.rb:180:in `block in all_actions'
  /home/circleci/project/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `each'
  /home/circleci/project/fastlane/lib/fastlane/documentation/actions_list.rb:172:in `all_actions'
  /home/circleci/project/fastlane/lib/fastlane/documentation/markdown_docs_generator.rb:110:in `actions_md_contents'
  Fastfile:567:in `block in parsing_binding'
```

**Comment by mollyIV** [comment]
👋 

> If not, an alternative might be to add line breaks in some other way maybe.

That will do 😉👇 

```ruby
def self.description
  'This is ' \
  'multi line description.'
end
```

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
Thanks for making this clearer here 😊 These actions have some weird name overlap that make it very confusing. I rebased and also add a `.join("\n") like other actions have to make this return as a string. Appreciate the contribution like always ❤️

**Comment by revolter** [comment]
OMG I forgot about this, sorry for the incorrect implementation and not replying and thanks for the fix and merge ❤️

**Pull request merged**
