### PR TITLE
Fix code_server_get_assets action

### PR DESCRIPTION
**Pull request by robert-mandall-ihc**
swap incorrect fetch_integrations filter from limit to last.
See issue https://github.com/fastlane/fastlane/issues/841

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks good to me, would love a +1 from @czechboy0 to be sure :+1:

**Comment by KrauseFx** [comment]
Thanks for your contribution @robert-mandall-ihc :rocket:

**Comment by czechboy0** [comment]
lgtm, thanks!

**Comment by KrauseFx** [comment]
Great, thanks everybody, this will be in the next release :+1:

**Pull request merged**
