### PR TITLE
[match] Fixes Gitlab Secure Files API limit

### LINKED ISSUE #21204: [match] Gitlab Secure files API limited to 20 files by default
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using Match with Gitlab Secure files as storage type, Fastlane is using Gitlab API to get a list of all secure files stored on the repository (`GET /projects/:project_id/secure_files`) to later use other API to fetch them ([https://docs.gitlab.com/ee/api/secure_files.html](https://docs.gitlab.com/ee/api/secure_files.html)). Unfortunately this API uses paging and in my case after exceeding 20 files (seems to be a default but there's no mentions about it in Gitlab documentation) this is the maximum number of files Fastlane will fetch even though there's more stored on the repository. This results is some failures if certificate files were never fetched or provision profiles.
```
gitlab_project("some-org/some-project")
storage_mode("gitlab_secure_files")
```
This Merge Request adds a query parameter to modify the page size to 100 and 100 is the maximum number of Secure Files you may have on a single repository in Gitlab. As stated in Gitlab documentation:
```
Limited to 100 secure files per project. Files must be smaller than 5 MB. 
```

##### Command executed
`bundle exec fastlane match`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> **********@*********** ios-credentials % bundle exec fastlane update_profiles asUser:someuser@someorg.com

[✔] 🚀 
[11:37:00]: ------------------------------
[11:37:00]: --- Step: default_platform ---
[11:37:00]: ------------------------------
[11:37:00]: Driving the lane 'ios update_profiles' 🚀
[11:37:00]: -----------------------------------------------
[11:37:00]: --- Step: Switch to ios update_profile lane ---
[11:37:00]: -----------------------------------------------
[11:37:00]: Cruising over to lane 'ios update_profile' 🚖
INFO [2023-04-17 11:37:00.17]: -------------------
INFO [2023-04-17 11:37:00.17]: --- Step: match ---
INFO [2023-04-17 11:37:00.17]: -------------------

+----------------------------------------+--------------------------------------------------------+
|                                    Summary for match 2.212.2                                    |
+----------------------------------------+--------------------------------------------------------+
| type                                   | enterprise                                             |
| app_identifier                         | ["com.some-org.some-app"] |
| username                               | someuser@someorg.com                                             |
| team_id                                | **********                                             |
| storage_mode                           | gitlab_secure_files                                    |
| gitlab_project                         | some-org/path/to/repository                 |
| generate_apple_certs                   | false                                                  |
| verbose                                | true                                                   |
| readonly                               | true                                                   |
| force_for_new_devices                  | true                                                   |
| skip_provisioning_profiles             | false                                                  |
| git_branch                             | master                                                 |
| shallow_clone                          | false                                                  |
| clone_branch_directly                  | false                                                  |
| skip_google_cloud_account_confirmation | false                                                  |
| keychain_name                          | login.keychain                                         |
| force                                  | false                                                  |
| include_mac_in_profiles                | false                                                  |
| include_all_certificates               | false                                                  |
| force_for_new_certificates             | false                                                  |
| skip_confirmation                      | false                                                  |
| safe_remove_certs                      | false                                                  |
| skip_docs                              | false                                                  |
| platform                               | ios                                                    |
| derive_catalyst_app_identifier         | false                                                  |
| fail_on_name_taken                     | false                                                  |
| skip_certificate_matching              | false                                                  |
| skip_set_partition_list                | false                                                  |
+----------------------------------------+--------------------------------------------------------+

INFO [2023-04-17 11:37:00.18]: Initializing match for GitLab project some-org/path/to/repository 
DEBUG [2023-04-17 11:37:09.88]: Successfully downloaded all Secure Files from GitLab to /var/folders/yx/1_t7gft533z8xlcvlkgnm08r0000gr/T/d20230417-61412-nnb4li
WARN [2023-04-17 11:37:09.88]: Couldn't find a valid code signing identity for enterprise... creating one for you now
WARN [2023-04-17 11:37:09.89]: Lane Context:
INFO [2023-04-17 11:37:09.89]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios update_profiles"}
ERROR [2023-04-17 11:37:09.89]: No code signing identity found and can not create a new one because you enabled `readonly`
INFO [2023-04-17 11:37:09.89]: Successfully generated documentation at path '/Users/***********/Repositories/ios-credentials/fastlane/README.md'

+------+-----------------------------------+-------------+
|                    fastlane summary                    |
+------+-----------------------------------+-------------+
| Step | Action                            | Time (in s) |
+------+-----------------------------------+-------------+
| 1    | default_platform                  | 0           |
| 2    | Switch to ios update_profile lane | 0           |
| 💥   | match                             | 9           |
+------+-----------------------------------+-------------+

ERROR [2023-04-17 11:37:09.90]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: No code signing identity found and can not create a new one because you enabled `readonly`

URL: https://api.github.com/search/issues?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60+repo:fastlane/fastlane
➡️  [match] errSecInternalComponent if not possible to prompt for keychain password
    https://github.com/fastlane/fastlane/issues/15185 [open] 139 💬
    a week ago

➡️  Could not install WWDR certificate
    https://github.com/fastlane/fastlane/issues/20960 [closed] 46 💬
    12 hours ago

➡️  ERROR ITMS-90161: Invalid Provisioning Profile on TestFlight upload
    https://github.com/fastlane/fastlane/issues/20989 [closed] 3 💬
    24 Jan 2023

and 31 more at: https://github.com/fastlane/fastlane/search?q=No%20code%20signing%20identity%20found%20and%20can%20not%20create%20a%20new%20one%20because%20you%20enabled%20%60readonly%60&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	37: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
	36: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
	35: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<main>'
	34: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
	33: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	32: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	31: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	30: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	29: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	28: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	27: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	26: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	25: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	24: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	23: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:12:in `block (2 levels) in parsing_binding'
	16: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	14: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	13: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:24:in `block (2 levels) in parsing_binding'
	11: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	10: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 8: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 7: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 6: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 5: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 4: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
	 3: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/match/lib/match/runner.rb:99:in `run'
	 2: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/match/lib/match/runner.rb:170:in `fetch_certificate'
	 1: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': No code signing identity found and can not create a new one because you enabled `readonly` (FastlaneCore::Interface::FastlaneCrash)
	37: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `<main>'
	36: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/ruby_executable_hooks:22:in `eval'
	35: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `<main>'
	34: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/fastlane:23:in `load'
	33: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	32: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	31: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	30: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	29: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	28: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	27: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	26: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	25: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	24: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	23: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:12:in `block (2 levels) in parsing_binding'
	16: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	14: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	13: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	12: from Fastfile:24:in `block (2 levels) in parsing_binding'
	11: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	10: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	 9: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	 8: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	 7: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	 6: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	 5: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 4: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/sync_code_signing.rb:19:in `run'
	 3: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/match/lib/match/runner.rb:99:in `run'
	 2: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/match/lib/match/runner.rb:170:in `fetch_certificate'
	 1: from /Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/**********/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] No code signing identity found and can not create a new one because you enabled `readonly`\e[0m (FastlaneCore::Interface::FastlaneCrash) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                |
| --------------------------- | -------------------------------------------------------------------- |
| OS                          | 13.3                                                                 |
| Ruby                        | 2.7.2                                                                |
| Bundler?                    | true                                                                 |
| Git                         | git version 2.39.2 (Apple Git-143)                                   |
| Installation Source         | ~/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | macOS 13.3 (22E252)                                                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                                         |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                                           |
| Is contained                | false                                                                |
| Is homebrew                 | false                                                                |
| Is installed via Fabric.app | false                                                                |
| Xcode Path                  | /Applications/Xcode_14.3.app/Contents/Developer/                     |
| Xcode Version               | 14.3                                                                 |
| Swift Version               | 5.8                                                                  |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

mainTeamId = "L823EJ2XX5"
enterpriseTeamId = "X7SK4Y864U"

platform :ios do
  desc "Update provision profiles"
  lane :update_profiles do |options|
    if not username = options[:asUser] then UI.user_error!("Missing 'asUser' value. Make sure to 'fastlane update_profiles asUser:someuser@caesars.com") end

    # Caesars Palace Enterprise GPT
    update_profile(type: "enterprise", appIdentifier: "com.CaesarsDigital.iGaming.CaesarsPalaceOnline.gpt", teamId: enterpriseTeamId, username: username)
    # Caesars Palace Enterprise USC
    update_profile(type: "enterprise", appIdentifier: "com.CaesarsDigital.iGaming.CaesarsPalaceOnline.usc", teamId: enterpriseTeamId, username: username)
    # Caesars Palace Enterprise USD
    update_profile(type: "enterprise", appIdentifier: "com.CaesarsDigital.iGaming.CaesarsPalaceOnline.usd", teamId: enterpriseTeamId, username: username)
  end

  private_lane :update_profile do |options|
    if not type = options[:type] then UI.user_error!("Missing 'type' value. Make sure to 'fastlane update_profile type:development") end
    if not appIdentifier = options[:appIdentifier] then UI.user_error!("Missing 'appIdentifier' value. Make sure to 'fastlane update_profile appIdentifier:com.caesars.someASpp") end
    if not teamId = options[:teamId] then UI.user_error!("Missing 'teamId' value. Make sure to 'fastlane update_profile teamId:L823EJ2XX5") end
    if not username = options[:username] then UI.user_error!("Missing 'username' value. Make sure to 'fastlane update_profile username:someuser@caesars.com") end
    match(
      type: type,
      app_identifier: appIdentifier,
      username: username,
      team_id: "X7SK4Y864U",
      storage_mode: "gitlab_secure_files",
      gitlab_project: "caesarsdigital/usa/ios/ios-credentials",
      generate_apple_certs: false,
      verbose: true,
      readonly: true,
      force_for_new_devices: true
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.748.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.171.0      |
| aws-sdk-kms                     | 1.63.0       |
| aws-sdk-s3                      | 1.120.1      |
| babosa                          | 1.0.4        |
| bundler                         | 2.1.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.7.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.5.2        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-androidpublisher_v3 | 0.39.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.7.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2023-04-17**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by pawelini1**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #21204

This change fixes an issue for those people who have many different certs/provision profiles/keys stored on Gitlab in a "Secure files" section. The api used currently by Fastlane does not take into account paging and it's capable of downloading only 20 such files instead of all of them (max 100). This leads to signing issues as some files might be missing.
### Description
The fix itself it's quite straightforward by adding explicit page size to 100 which is the maximum number of Secure Files you can store on Gitlab repository as stated in their documentation
```
Limited to 100 secure files per project. Files must be smaller than 5 MB. 
```
on [https://docs.gitlab.com/ee/api/secure_files.html](https://docs.gitlab.com/ee/api/secure_files.html)
### Testing Steps

I've tested it on my Match setup that involves more than 20 files on Gitlab repository. Before the fix I was getting an error: 
```
/Users/pszymanski/Repositories/ios-credentials/vendor/bundle/ruby/2.7.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': \e[31m[!] No code signing identity found and can not create a new one because you enabled `readonly`\e[0m (FastlaneCore::Interface::FastlaneCrash)
```
as one of the certificates needed was not fetched as a result of that issue. After applying this fix my script finished with no issues.

### CODE REVIEW

**Comment by darbyfrey** [comment]
Hi @pawelini1, thanks for creating a PR for this!

Would you mind adding a test for this change too? Something like:

```ruby
it 'requests 100 files from the API' do
  stub_request(:get, /gitlab.example.com/).
    to_return(status: 200, body: [].to_json)

  files = subject.files

  assert_requested(:get, /gitlab.example.com/, query: "per_page=100")
end
```

@getaaron would you be able to review this change when it's ready?

**Comment by getaaron** [comment]
Agreed on the test, and happy to merge it once that's added. Thanks for the PR @pawelini1!

**Comment by darbyfrey** [comment]
Hi @pawelini1,

Thanks for adding the test! I noticed the build was failing and it looks like that test should go in the `match/spec/storage/gitlab/client_spec.rb` file. Would you mind moving it?

**Comment by getaaron** [comment]
Closed via https://github.com/fastlane/fastlane/pull/21361

Thanks for the PR, @pawelini1, and thanks @darbyfrey for fixing up the test!

**Pull request closed without merging**
