### PR TITLE
Gym option build time

### PR DESCRIPTION
**Pull request by RishabhTayal**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Reopening https://github.com/fastlane/fastlane/pull/7586

### CODE REVIEW

**Comment by KrauseFx** [comment]
Is the issue mentioned on the last PR resolved? Or is the PR WIP?

**Comment by RishabhTayal** [comment]
Yes that issue is resolved.

**Review by KrauseFx — APPROVED** [review]
Looks great, thanks for your contribution @RishabhTayal 👍

**Comment by hjanuschka** [comment]
congrats @RishabhTayal  for getting this finaly merged! many thx for your patience 🚀

**Comment by RishabhTayal** [comment]
Thanks for merging it in. Can't wait to see the feature new release and hopefully my name in release notes. :)

**Comment by KrauseFx** [comment]
@RishabhTayal Yeah, your name will be in the release notes 👍

**Comment by RishabhTayal** [comment]
💯

**Pull request merged**
