### PR TITLE
Issue template fix

### PR DESCRIPTION
**Pull request by RishabhTayal**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
In the current ISSUE_TEMPLATE.md there are some instructions for the issue author. Those instructions need to be deleted by author every time. We can add those instructions as commented code instead. This PR achieves that. Hope to get this merged. 👍

### CODE REVIEW

**Comment by KrauseFx** [comment]
Why are there always so many commits?

**Comment by RishabhTayal** [comment]
I don't understand that either. I think those are historical commits. I tried to checkout the `master` again but it doesn't work. Let me know if know a way to remove those commits.

**Comment by friederbluemle** [comment]
@RishabhTayal The reason all these commits are there is because you *merged* `master` into your local branch (multiple times), instead of _rebasing_ your changes.

Basically, all you want is the single commit 0f46fc89c2aa42a78cd92cf2edd94f081d8802cb `updated issue template md`

To fix your branch, follow these steps:

1. Make sure your local `master` is up-to-date with `origin/master`:

        git checkout master
        git pull

2. Switch to your branch again:

        git checkout issue-template-fix

3. Now perform an interactive rebase, removing all the additional commits:

        git rebase -i master

    This will open an editor, and you have to **remove** all lines, _except_ this one: `pick 0f46fc89c updated issue template md`

    Now save the editor, and you will end up with a clean branch with one commit, fully rebased onto `master`.

4. Force push to your fork:

        git push -f https://github.com/RishabhTayal/fastlane.git

**Comment by RishabhTayal** [comment]
@friederbluemle Thanks for the detailed instructions. I followed the same steps however it removes those commits for me. Please checkout the video in the link for the steps I followed.

https://www.dropbox.com/s/1hqtxrxs9q5bnf7/recording.mov?dl=0

**Comment by RishabhTayal** [comment]
And here is my remote repo setup:

screenshot 2017-10-23 12 48 00

**Comment by ohayon** [comment]
Hey @RishabhTayal - another option would be to pull master by doing `git pull fastlane master` then checkout a new branch with `git checkout -b my-new-branch` and then make the changes on top of that. If it's okay, I am going to close this PR for now as I think it may be more simple to just create a new one from master 😄 🚀

**Comment by RishabhTayal** [comment]
@ohayon sounds good. I am closing the pr now and opening a new one.

**Pull request closed without merging**
