### PR TITLE
Updating doc path for Platforms.md

### PR DESCRIPTION
**Pull request by jschoolcraft**
Simplest change, just adding a missing /fastlane/ to the Platforms.md path.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Was this merged as a separate PR?

**Comment by jschoolcraft** [comment]
No, I screwed up the pull request when I tried to do changes to
CodeSigning.md which is a similar pathing issue.  I couldn't edit it so I
deleted it and was going to create to local branches and push them
separately as pull requests, I just haven't done it yet, I'll do it now

**Comment by jschoolcraft** [comment]
Created a new pull request #4235.  Hopefully this one is correct.

**Comment by KrauseFx** [comment]
Cool, thanks

**Pull request closed without merging**
