### PR TITLE
Fix for nil output for xctest. Update documentation.

### PR DESCRIPTION
**Pull request by coreyfloyd**
This is just a follow on to #188

It fixes an issue where nil output would blow up. Added a test for this case.

Also updates the docs.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Great, thank you! :+1:

**Comment by KrauseFx** [comment]
Is there something we should add to the documentation?

**Comment by coreyfloyd** [comment]
@KrauseFx I updated `Actions.md` - I think that is sufficient.

**Comment by KrauseFx** [comment]
Ha, sorry, I missed that, `Actions.md` is perfect, thank you! :+1:

**Pull request merged**
