### PR TITLE
Add silent argument to ipa action

### PR DESCRIPTION
**Pull request by gfpacheco**
I didn't see a reason to open an issue before submiting this PR.
I'm sorry I'm not familiar with gem development and tests, and in this case I didn't test at all.
I just tried to advance the code work, even if it was small.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for contributing. Did I see correct that this doesn't change anything on existing setups, but allows the additional parameter `ipa(silent: true)` to not output build information?

**Comment by gfpacheco** [comment]
Yes! That's the intention, what do you think?

**Comment by KrauseFx** [comment]
Looks great, thanks for your contribution @gfpacheco :+1:

**Comment by gfpacheco** [comment]
I'm glad I could help somehow. Great projects BTW!

**Comment by kohtenko** [comment]
In release 1.7.0 I can't add `ipa(silent: false)`
In my `Fastfile` I got 
```
   	ipa(scheme: "App", destination: "ipa/", ipa:"App.ipa", silent: false)
```
And error in terminal says: 
```
[15:58:42]: You passed invalid parameters to 'ipa'.
[15:58:42]: Check out the error below and available options by running `fastlane action ipa`
[15:58:42]: Variable Dump:
[15:58:42]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios ipa", :SIGH_PROFILE_PATH=>"/Users/user/Documents/app/fastlane/Certificates/AdHoc_com.App.mobileprovision", :SIGH_UDID=>"31e3e52f-6a3b-450c-9397-065de6490973"}
[15:58:42]: Could not find available option 'silent' in the list of available options: workspace, project, configuration, scheme, clean, archive, destination, embed, identity, sdk, ipa, xcconfig, xcargs
[15:58:43]: fastlane finished with errors
/Users/okohtenko/.rvm/gems/ruby-2.2.1/gems/fastlane_core-0.9.2/lib/fastlane_core/configuration.rb:45:in `block in verify_value_exists': Could not find available option 'silent' in the list of available options: workspace, project, configuration, scheme, clean, archive, destination, embed, identity, sdk, ipa, xcconfig, xcargs (RuntimeError)
```

Is there way to get output for `ipa` action back?

**Comment by KrauseFx** [comment]
It seems like the option wasn't added to the `available_options` array. @gfpacheco did you test the integration?

**Comment by gfpacheco** [comment]
No, I didn't. As I said, I was just trying to advance the code writing, I wasn't sure it was all it needed to work.

**Pull request merged**
