### PR TITLE
added badge as custom action for fastlane

### PR DESCRIPTION
**Pull request by HazAT**

### CODE REVIEW

**Comment by kcharwood** [comment]
Is there a way to add custom text instead of the word beta? I have a script that does this locally, but its written in swift, and we use to add the build number to the icon.

**Comment by HazAT** [comment]
@kcharwood checkout my latest addition ... added the possibility to add a shield on top of your icon. https://github.com/HazAT/badge

**Comment by ohwutup** [comment]
thanks @HazAT this looks great! would you mind squashing the commits before we merge?

**Comment by HazAT** [comment]
@ohwutup done and thx!

**Comment by ohwutup** [comment]
WOOT! :rocket:

**Comment by ohwutup** [comment]
hey @HazAT I just realized i forgot to ask you to update the Actions.md file with some docs around this action. if you wouldn't mind doing that in a separate PR that would be amazing! thank you ! :octopus:

**Comment by HazAT** [comment]
oh ... of course PR coming soon.

**Comment by KrauseFx** [comment]
Thanks everybody :+1:

**Pull request merged**
