### PR TITLE
[action] pod_lib_lint: Add missing parameters

### PR DESCRIPTION
**Pull request by mfiebig**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The `pod_lib_lint` action was missing some of the (newer?) parameters of cocoapods `lib lint` command.

### Description

I added the missing parameters and wrote according unit tests.

### CODE REVIEW

**Comment by janpio** [comment]
Should we add a version information to the params again similar to https://github.com/fastlane/fastlane/pull/14579/files?

**Comment by mfiebig** [comment]
@janpio I added the version information for everything above 1.0

**Review by janpio — APPROVED** [review]
Simple code, great documentation, and tests!

**Review by joshdholtz — APPROVED** [review]
Looks great to me! Thanks for adding these ❤️

**Pull request merged**
