### PR TITLE
[spaceship] update API endpoints to use https://appstoreconnect.apple.com

### PR DESCRIPTION
**Pull request by cjweigle**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The Recent Gateway Timeouts are fixed by using the new url.  (#13259 + [#13271, Q2])

### Description
Change itunesconnect.apple.com to appstoreconnect.apple.com.

### CODE REVIEW

**Comment by chronweigle** [comment]
I signed It!

**Comment by saitjr** [comment]
@chronweigle  Hi, I've seem this pr reference to 504 error (#13259). Does 504 error caused by api changed ?

**Comment by chronweigle** [comment]
Yes, the API's endpoint has moved to appstoreconnect.apple.com.

**Comment by iamhyw** [comment]
Yes. my Issue #13271 Q2 is solved but trailer is still upload faild. when upload is done I still can't see the video in the appstore connect. I use .mov

**Comment by chronweigle** [comment]
I updated the PR to specify that it only addresses Q2.

**Comment by iamhyw** [comment]
OK.Still Thanks!

**Comment by andreyz** [comment]
Come on guys, pull that in ASAP, this is blocking our workflow

**Comment by joshdholtz** [comment]
Testing this now ^

**Comment by joshdholtz** [comment]
@andreyz I just woke up a little bit ago and there is a decent amount of manual testing involved in this. You can pull this down into your project by editing your `Gemfile` to contain the following...
```rb
gem "fastlane", :git => "https://github.com/chronweigle/fastlane.git", :branch => "app-store-connect"
```

**Comment by joshdholtz** [comment]
@chronweigle Thanks for finding this solution! I wasn't able to verify that this is an actual solution since I wasn't able to replicate this problem myself but things still work from my end with these changes 👌 And thanks to everyone else for being patient while I tested this change out 😊

**Review by joshdholtz — APPROVED** [review]
Looks good and worked good for me! Thanks for fixing this ❤️

**Pull request merged**
