### PR TITLE
Fix typo in plugin-badge.svg

### PR DESCRIPTION
**Pull request by kiliankoe**
- [ ] Run `rspec` for all tools you modified
- [ ] Run `rubocop -a` to ensure the code style is valid
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

I hope it's ok for not running the tests or rubocop on this.

### CODE REVIEW

**Comment by asfalcone** [comment]
@kiliankoe Can you explain the change that you made in this PR? Maybe a side by side screenshot? Thanks 👍

**Comment by kiliankoe** [comment]
Github's rich diff does a better job than I could^^

screen shot 2016-10-07 at 16 49 34

I did nothing else but fix the typo in the original. And if I'm not mistaken, generated plugins link the badge from this repo, so that should fix the typos in all of them as well.

**Review by asfalcone — APPROVED** [review]
Perfect, I just didn't look at the rich diff! Thanks for the fix 🚀

**Comment by kiliankoe** [comment]
And thanks for the merge 😊

**Comment by KrauseFx** [comment]
Ha, nice catch 👍

**Pull request merged**
