### PR TITLE
Adds an action to just push the changed tags

### PR DESCRIPTION
**Pull request by vittoriom**
Don't know if you find it useful but this action just pushes the git tags

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for sharing. I'm using the `push_to_git_remote` action for that, which also pushes tags. Did you know about this action? Or do you do something different?

**Comment by vittoriom** [comment]
Yes, I saw the `push_to_git_remote` action, but it **also** pushes tags, not **only**. As I said, this is probably nothing interesting, just thought about making a PR but close it if it doesn't add much value. Also, I could change the `push_to_git_remote` action to accept some option that specifies to only push the tags without pushing the branch.  ¯\_(ツ)_/¯

**Comment by KrauseFx** [comment]
Looks good, thanks! :+1:

**Comment by KrauseFx** [comment]
I pushed some smaller changes: https://github.com/KrauseFx/fastlane/commit/40f4558cd951cd1cd2008c94501ebc9aa7eeae6c

Please change your Ruby editor to only use 2 spaces :+1: 

Thanks again for your contribution @vittoriom :rocket:

**Comment by vittoriom** [comment]
You're totally right! I'm sorry, I just noticed the indentation was messed up... thanks!

**Pull request merged**
