### PR TITLE
Adding tag_match_pattern param to changelog_from_git_commits

### PR DESCRIPTION
**Pull request by 7mllm7**
Continuing the accidentally closed https://github.com/fastlane/fastlane/pull/1019 and implementing code review by @mfurtak.

### CODE REVIEW

**Comment by 7mllm7** [comment]
Anyone has an idea why tests fail on this? there doesn't seem to be any connection to the action that I modified.

**Comment by KrauseFx** [comment]
Sorry about the failing tests, we had troubles with rubocop last week. Could you merge back from master to get the latest `rubocop` config and see if that works? :+1:

**Comment by 7mllm7** [comment]
Done

**Comment by 7mllm7** [comment]
Right so, when can we merge? I just really wanna start using this feature :)

**Comment by KrauseFx** [comment]
Sorry for the late reply, we'll be reviewing this PR as soon as possible, probably in about 1-2 weeks :+1: cc @mfurtak

**Comment by 7mllm7** [comment]
Sure, although I believe this was already reviewed by @mfurtak in the accidentally closed https://github.com/fastlane/fastlane/pull/1019

**Comment by mfurtak** [comment]
@7mllm7 I'm sorry to keep you hanging on this! I've created #1258 to clean up the git commits a little. Let me know if that looks OK and we can get it merged! :tada:

**Pull request closed without merging**
