### PR TITLE
[deliver] Download screenshots: add `use_live_version` option

### PR DESCRIPTION
**Pull request by andreacipriani**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
   - I haven't, because if I'm not wrong there is no documentation about the `download_screenshots` options

### Motivation and Context

Imagine you have two versions on iTunes connect: `1` (live) and `2` (edit). When you created version `2`, the screenshots were not carried over from `1` (it did happen to me for the last two releases).
So you might want to download screenshots from `1`, but by default, if there is an edit version, `download_screenshots` will always use that version. References to code: [here](https://github.com/fastlane/fastlane/blob/83f9895f557293862a9f7546e0ff06cd4b3c1440/deliver/lib/deliver/download_screenshots.rb#L15) and [here](https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/spaceship/lib/spaceship/tunes/application.rb#L130).

The PR adds the possibility to specify a `--use_live_version` option to overcome this problem.

I tested that I didn't break the existing behavior when not using the new option.
I tested that when using the option: `bundle exec fastlane deliver download_screenshots --use_live_version` it uses the live version also when there is an edit version.

### Description
- Adding the new option
- When the option is set, use the already defined `live_version` [function](https://github.com/fastlane/fastlane/blob/1a79353a6d918eddca61274e97962a5f2770210e/spaceship/lib/spaceship/tunes/application.rb#L118)

### CODE REVIEW

**Comment by andreacipriani** [comment]
I signed it!

**Review by janpio — APPROVED** [review]
What a simple but nice change. Looks good!

You did test it locally and it is working as expected? Both downloading latest and live version screenshots?

**Comment by andreacipriani** [comment]
@janpio yep!

**Comment by janpio** [comment]
🥇

**Pull request merged**
