### PR TITLE
[match] add template parameter

### PR DESCRIPTION
**Pull request by hermanolsson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
For some users of Match, the lack of support for the `template` (entitlements) parameter when creating provisioning profiles is a deal breaker. For the apps my team is working on, we rely on specific entitlements configured in the dev portal when creating/updating a provisioning profile.

This has been discussed in a few issues before, but we cannot find a pull request with this change. The issue we used as guidance is #4548. We know this was kind of dismissed back then, but hopefully this PR will make sense, since it breaks nothing for regular usage, and it will be of great benefit to the ones actually using this `template` parameter.

The changes made in this pull request have been tested with our own provisioning profiles both for development and distribution.

### Description
We have made changes to Match, Sigh and Spaceship.

#### Match
* Added a template parameter and option

#### Sigh
* Added template parameter and option

#### Spaceship
* Use the template parameter in the dev portal calls

#### Tests
* Updated tests to handle the new template parameter

I'm not an every day ruby developer, but I have tried to follow all guidances for making changes to fastlane and a pull request.

### CODE REVIEW

**Comment by hermanolsson** [comment]
I signed it!

**Comment by KrauseFx** [comment]
Hey @hermanolsson, thanks for the PR and the documentation for it, this looks great. I haven't used entitlements myself yet, would you mind sending some screenshots of how a user can create the entitlements on the Dev Portal, and how this string is being chosen? Is that generally applicable and can be used by all kinds of setups?

**Comment by hermanolsson** [comment]
Hi @KrauseFx, this is a bit of new territory to me and my team, but as far as I understand, the Entitlements field is a drop-down, and the value to be entered for the `template` parameter in Match is the value from an option in that drop down. This is a bit of a hassle, but we figured the ones really in need of this functionality are fine taking the extra steps since Match takes care of everything once all setup.

Regarding "all kinds of setups", I cannot really say, but I haven't seen any other way of choosing these kinds of entitlements.

There is a screenshot in the mentioned issue above https://github.com/fastlane/fastlane/issues/4548#issuecomment-246020321 and this one looks just like our form when creating/updating a provisioning profile. Do you want me to send you what it looks like for us specifically, or is that screenshot sufficient?

Please let me know if I can do more to help this PR make it to the master branch.

**Comment by KrauseFx** [comment]
Oh interesting, thanks for that info. I'll try this on one of my sample apps, and will let you know if I have any follow-up questions 👍

**Comment by hermanolsson** [comment]
Hey again, @KrauseFx , did you get this to work with the sample apps? Can I be of any more assistance?

**Comment by thelvis4** [comment]
@hermanolsson First of all, thank you for taking the time to make the changes and open this PR! 🙌
Our team also needs this feature, so I can confirm it would be a very useful change for a niche of Fastlane users.
Because I didn't notice this PR earlier, I started working on my own on a solution, which is somehow similar to yours (just a different naming). But I decided to open [another PR](https://github.com/fastlane/fastlane/pull/9912) because that also supports updating and repairing the profiles.

Could you check if https://github.com/fastlane/fastlane/pull/9912 works in your case? That would be very helpful.
Thank you!

**Comment by nicolasbraun** [comment]
@KrauseFx  not sure you can try on your sample apps, Entitlement are manually provided by Apple and the dropdown will usually not show.

Current workaround for me is to use sigh top download profiles manually generated, not to generate them.

**Comment by KrauseFx** [comment]
Thanks for your contribution, it seems like https://github.com/fastlane/fastlane/pull/9912/ has more documentation & tests, so I'm gonna go ahead and review this. Sorry for the delay on replying to this PR 👍

**Comment by hermanolsson** [comment]
No worries at all. I'm happy this feature makes into the repo.

**Pull request closed without merging**
