### PR TITLE
Change "download zip" URL to point to latest version in README

### PR DESCRIPTION
**Pull request by BalestraPatrick**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Change "download zip" URL to point to latest version in README. I mistakenly installed an old version by download the zip file using the URL. I think the zip file hosted on the server is not being kept up to date.

### CODE REVIEW

**Review by hjanuschka — APPROVED** [review]
great catch 🚀

**Comment by hjanuschka** [comment]
@krausefx should we remove the old zip file from s3?

**Comment by mfurtak** [comment]
I believe the files downloaded between those two URL are the same. Am I mistaken?

**Comment by BalestraPatrick** [comment]
@mfurtak I tried twice to download from the old URL on two machines and both times I ended up with an old version. I was thinking to point to the release/latest page here in GitHub but after removing the direct link to the fastlane website, it seems to download the latest one.

**Comment by KrauseFx** [comment]
They should be the same, but maybe @ohayon knows more. If we merge this change, there are about 5 other locations where we link to this, so we'd need to update the URL there too.

**Comment by hjanuschka** [comment]
@KrauseFx  i am going to merge this, and do a follow up pr with hunted zip urls 👍

**Comment by mfurtak** [comment]
I think that what @balestrapatrick is talking about is how the version of fastlane that comes in the package is not always up-to-date. This is a known issue, and is not related to the URL

**Comment by hjanuschka** [comment]
@mfurtak ohh well thats sad, should we revert this one then?

**Comment by BalestraPatrick** [comment]
@mfurtak Actually I downloaded the zip file and it installed version 2.5.0. Could you please try to check if it's really downloading the latest version with the old URL?

**Comment by ohayon** [comment]
I believe @mfurtak is correct here. Those URLs should download the same thing. There is some weirdness around versioning such that the package itself is not tied to a version of _fastlane_. @BalestraPatrick - this is why it might appear as though you are downloading an old version, but upon installation or running `fastlane update_fastlane` you can update _fastlane_ to the most recent version of the gem.

**Comment by hjanuschka** [comment]
@ohayon  but using the link without `fastlane.zip` is also correct? (so no revert?)

**Comment by ohayon** [comment]
Yup @hjanuschka ! No need to revert 😄

**Comment by mfurtak** [comment]
Either link is correct (identical), but Felix had mentioned consistency for all the places we link to it

**Comment by hjanuschka** [comment]
ok - i am fine with a revert however i had immediately after felix's comment prepared a PR here: https://github.com/fastlane/docs/pull/298 and https://github.com/fastlane/fastlane/pull/8459 that should make them consistent

**Comment by mfurtak** [comment]
OK that's fine too

**Comment by Xwoder** [comment]
After I download the zip file and unzip it, I found that the content of file `.../fastlane/fastlane_lib/VERSION` still showed `1.7`.

The `Download the zip file` links to `https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip`.

**Comment by mfurtak** [comment]
Hi @Xwoder 👋 

The version number noted in the fastlane installer package represents the version of the installer package. The version of _fastlane_ that gets installed will be different. Once you install _fastlane_, it will keep itself up-to-date, and you can run `fastlane -v` to verify your version. 👍 

I'm going to lock this issue for now to cut down on notifications for everyone.

**Pull request merged**
