### PR TITLE
Frameit/title below image

### PR DESCRIPTION
**Pull request by claesjacobsson**
🔑

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

`frameit` places the title above the screenshot. I thought it might be useful to be able to place it below the screenshot when desired.

I successfully tested the code on my project and by running `bundle exec rspec`.

### Description

Support for the new parameter `title_below_image` has been added. It can be used in `Framefile.json`.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @claesjacobsson, thanks for submitting this pull request. Looks good to me, did you test if this works just like before if the user is not setting the new flag?

**Comment by claesjacobsson** [comment]
Yes, it does.

**Review by KrauseFx — APPROVED** [review]
Wohoooo, thanks for your contribution @claesjacobsson 👍

**Comment by claesjacobsson** [comment]
Thank YOU Felix!

**Pull request merged**
