### PR TITLE
Added hipchat messaging support

### PR DESCRIPTION
**Pull request by jingx23**
Like the slack integration you can send a message to a hipchat room e.g.:

```
ENV["HIPCHAT_API_TOKEN"] = "hipchat_api_token"

hipchat({
     message: "Successfully deployed new App Update for [App](http://link.com).",
     success: true,
     channel: 'room or @username'
  })
```

### CODE REVIEW

**Comment by KrauseFx** [comment]
This looks really cool, thanks for sending this pull request :+1: 

Could you also add a short instruction to the README right below the slack integration? 

I don't use hipchat myself, so I guess you have tested if it works as expected? 
Is there also a way to show an icon next to the message?

**Comment by jingx23** [comment]
Hi @KrauseFx,
of course i will add some short instruction to the README.
I checked the ability to add an icon next to the message see attached screenshot:
HipChat message with icon
Looks quite good, what do you think?

**Comment by KrauseFx** [comment]
Yes, looks great. Just the markdown doesn't seem to get parsed, but that's a string the user passes anyway.

**Comment by jingx23** [comment]
I´ve added the necessary information to the readme and added the ability to send a private message similar to the slack version.
For private messages we currently have to omit the icon because in the actual hipchat rb release html is not possible for this kind of messages :/.
Let me know if you have some other ideas or change requests.

**Comment by KrauseFx** [comment]
Ha, you can just inject HTML snippets into hipchat? ^^ Made me laugh!

Thanks for preparing this, looks great! Will be in the next release. Have you tested it? Can I release it?

**Comment by jingx23** [comment]
Thanks for merging, it´s well tested :tada:

**Pull request merged**
