### PR TITLE
Update bundler dependency to be more flexible

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/7963

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
LGTM

**Comment by summera** [comment]
@KrauseFx possible to go lower than `1.12`? For example: `~> `1.0`?

**Comment by KrauseFx** [comment]
@summera Why? We haven't tested it with a lower version, we use the bundler API directly when the user has plugins enabled for their project.

**Comment by summera** [comment]
Got it. So is `>= 1.12` required for fastlane plugins to work or you're unsure? 

I'm in a situation where the default bundler version in my AWS Elastic Beanstalk environment is lower than `1.12` (1.9.6). So I'm wondering if it's possible to make the requirement less strict by allowing lower versions of bundler for people in similar situations.

**Comment by KrauseFx** [comment]
@summera I'm unsure, I haven't tested it below that version, that's why we require it. If you can try using it with an older version, and make sure plugin installation and adding new plugins work, I'm ok with reducing the minimum version more 👍

**Comment by KrauseFx** [comment]
We can merge this for now, as it's already an improvement like this 👍

**Comment by summera** [comment]
@KrauseFx Cool sounds good 👍 . I'll get back to you on reducing the min version. Thanks again!

**Comment by KrauseFx** [comment]
Thanks 👍

**Pull request merged**
