### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Dershowitz011**
Fastlane sigh simplified usage.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

**Brilliant** tool to resign the IPAs. Made it simpler. Sigh.sh is the script you should run which is included here.

### CODE REVIEW

**Comment by Dershowitz011** [comment]
I've signed it.

**Comment by mpirri** [comment]
Thanks for your submission. What is your thought about how this would be used by _fastlane_ users? Clearly you gave a lot of thought to installing _fastlane_ for users, but how would they get their hands on this .sh file? Also, the "enter your IPA", etc workflow is already present (in a slightly) different form, when you run `fastlane sigh resign` without any command-line arguments; do you imagine this being used differently?

Thanks again!  🚀

**Comment by Dershowitz011** [comment]
Yes sigh is simplified aswell I know dear sir but I wrote this script so that people shouldn't really worry about mistakes while writing the command. This is relatively very easy. ( According to me ). They just have to enter their details and press enter/ If you could add the script in your readme or in the main folder and ask users to use the script if they please. I hope you will oblige. It'd be a great honour. Thanks. :)

**Comment by ohayon** [comment]
Hey @Dershowitz011 - thanks a lot of the contribution. While I think this is a great script, I'm not sure that we have a good distribution mechanism for getting this script in the wild given that we promote the installation of _fastlane_. Also, I think because this is not a _fastlane_ feature, we might overlook it in the future which could cause some breaking changes for folks.

I am going to close this PR for now, but please feel free to continue conversation here and we would absolutely love to have you contribute further to _fastlane_! 🚀 🐙

**Comment by Dershowitz011** [comment]
You can just include the script and add it in the description of fast lane sigh saying use this script for an easier way to resign your apps. If there's any change I should do, please let me know and I will. It's an honour contributing to this brilliant tool. 😇

**Comment by ohayon** [comment]
I think this would be really great for a personal blog post of yours if you have your own place to post one? This is a great example of a way that our community can promote fastlane and share usage patterns rather than keeping it in the fastlane repo 😄  🚀

**Pull request closed without merging**
