### PR TITLE
Don’t show error message when importing provisioning profile

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/6387

### CODE REVIEW

**Review by asfalcone — APPROVED** [review]
This looks pretty good. 

It might be useful to capture the error and display it in the future, if there is some other error that isn't a macOS farse. This code would mask other errors that might some up.

**Comment by KrauseFx** [comment]
I agree. What's the best approach to do so? Writing this to a file, and reading it seems like a lot of work just to do that. Should we merge and release, and then think about showing the error message @asfalcone?

**Comment by asfalcone** [comment]
Capture all of the output to a string, see if the first line is the error, print as a warning if it is, send the rest of the lines to the Plist parser?

Totally fine to revisit later. Just wanted to call out that this could bite us later!

**Comment by KrauseFx** [comment]
Mh, kind of difficult to see when the error ends, and when the plist starts, right? We could also switch to the fully featured Ruby IO thingy, where you have different pipes.

**Pull request merged**
