### PR TITLE
spaceship selects cookie path from set of preferred

### PR DESCRIPTION
**Pull request by summera**
Fixes https://github.com/fastlane/fastlane/issues/5662.
@KrauseFx Confirmed that this works in an AWS Elasticbeanstalk environment.
- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

### CODE REVIEW

**Review by KrauseFx — DISMISSED** [review]

**Comment by KrauseFx** [comment]
@mfurtak just pointed out, that storing this in /tmp is not a great solution. We store the cookie for 2 step verification in there, separate by account. This way, if you have 2 factor enabled, you're not asked to verify using your phone every time you run _fastlane_. We have to store it somewhere, where the cookie doesn't get lost, as it's valid for over a month, so it should persist even restarts on a Mac.

**Comment by summera** [comment]
@KrauseFx @mfurtak that makes sense. How about `/var/tmp/spaceship/#{self.user}` ?

**Comment by KrauseFx** [comment]
What's `/var/tmp`? Does it also get deleted when restarting the computer?

**Comment by summera** [comment]
It will not get deleted when restarting. It is similar to `/tmp` with the main difference being that it is preserved across reboots. Per the [Filesystem hierarchy standard (FHS)](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard):  "Temporary files to be preserved between reboots."

There is a more detailed discussion here: http://unix.stackexchange.com/questions/30489/what-is-the-difference-between-tmp-and-var-tmp

**Comment by mfurtak** [comment]
Would it make sense to delegate the responsibility of choosing the temp folder location to Ruby?

On my Mac:
```
>> require 'tmpdir'
=> true
>> Dir.tmpdir
=> "/var/folders/w6/ff6y4wtj7dx3trvb_0v1mwvc0000gp/T"
```

That folder currently contains ~300 items from many sources on my machine.

**Comment by summera** [comment]
Good thinking. I tried this on beanstalk and it returned `/tmp`. Looking at the [source](https://ruby-doc.org/stdlib-2.2.0/libdoc/tmpdir/rdoc/Dir.html) it uses `/tmp` as a backup if the various ENV vars for setting the temp directory do not exist. So that may work on some systems like Mac but may not in a linux server environment. I think this would have the same problem as using `/tmp` because the [$TMPDIR](https://en.wikipedia.org/wiki/TMPDIR) env variable is meant to specify temporary storage that may be cleaned up at regular intervals and not guaranteed to persist after reboots.

I did notice that a file I wrote to `/tmp` on beanstalk remained after a deploy. The cleanup time for `/tmp` varies per system and I'm not sure what it is on beanstalk.

`/var/tmp` is pretty standard on unix systems for storing files that need to be preserved over reboots. Another option would be to allow the user to configure the cookie path as a last resort.

**Comment by mfurtak** [comment]
Thanks for checking that out in your environment, @summera 👍 

Is it possible for you to set the `$TMPDIR` env variable for your environment before invoking _fastlane_/Ruby? In that case, if we use `Dir.tmpdir`, can you get that control over where things wind up?

**Comment by summera** [comment]
@mfurtak No problem. Using `/tmp` as my cookie dir isn't an issue for me specifically because I'm not using two-factor. The original issue for me was that the home dir was not available in my environment. 

For those users who are using two-factor, I don't think setting $TMPDIR to a location that is not ephemeral just for fastlane to work is a great solution given that $TMPDIR, by definition, is ephemeral and other programs may depend on this.

**Comment by mfurtak** [comment]
Cool. I agree with the thoughts around $TMPDIR and its meaning.

So my feeling is that the bug we try to fix here shouldn't be about selecting a single different directory, but about increasing our resiliency to not having write access to our preferred storage locations.

To that end, what do folks think about writing a `Dir.tmpdir`-like method that checks a preferred set of places, and returns a known-writable location that this data can be stored?

Another angle that needs to be considered for any change here is how we'll prevent currently authenticated users from being "signed out" by the update 👍 

Sorry to make things complicated! 😅

**Comment by summera** [comment]
@mfurtak sounds reasonable to me. That way we can prevent currently authenticated users from being signed out by keeping the current path as the first default we try in the set. 

No worries at all! Better to hash this out now then merge a problematic change 👌 .

So I guess the next question is what our preferred set of locations should be.  What do you think about the following order?

1. "~/.spaceship/#{self.user}" <-- keep current path as first option
2. "/var/tmp/spacehship/#{self.user}"
3. "#{ENV['SPACESHIP_COOKIE_PATH']}/#{self.user}"
4. "#{Dir.tmpdir}/spaceship/#{self.user}"  <-- if all else fails

**Comment by mfurtak** [comment]
That order sounds good to me!

**Comment by summera** [comment]
@mfurtak @KrauseFx Just pushed an update. Sorry for the delay on this!

**Comment by summera** [comment]
@mfurtak Just checking back in on this. Does the latest update look good to you?

**Comment by mfurtak** [comment]
Thanks for the ping. This is looking good! I'm inclined to merge it. What do you think @KrauseFx?

**Comment by KrauseFx** [comment]
Looks good to me 👍

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
🎉 🎊  Yay! Thanks for the great contribution @summera 👍

**Comment by lafiosca** [comment]
@summera @mfurtak Not sure if this is the place to mention this or if it's worth opening another issue, but when running in an environment that has no "HOME" variable set (such as AWS Lambda), it seems the expansion of "~" in step 2 fails and crashes out the program without ever getting to step 3:

```"/var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.5.0/spaceship/lib/spaceship/client.rb:426:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)",```

I'm able to work around this by setting `SPACESHIP_COOKIE_PATH` (or `HOME`) in the Lambda environment.

**Comment by KrauseFx** [comment]
@lafiosca Please submit a new issue for this 👍

**Comment by lafiosca** [comment]
Sorry for the delay on this. I hadn't seen your comment until today. The issue has been submitted as #8465. Thank you.

**Pull request merged**
