### PR TITLE
Changed the path of the tool for developing.

### PR DESCRIPTION
**Pull request by esusatyo**
I think this changed when we moved fastlane to the mono repo structure.

### CODE REVIEW

**Comment by lacostej** [comment]
@esusatyo thanks ! Maybe squash the commits

**Comment by KrauseFx** [comment]
Yeah, please squash the commits, then we can merge :+1:

**Comment by KrauseFx** [comment]
@esusatyo Any updates on this?

**Comment by esusatyo** [comment]
Sorry, please see this: https://github.com/fastlane/fastlane/pull/4189

**Pull request closed without merging**
