### PR TITLE
[WIP] remove requires from fastlane_core to decrease startup time

### PR DESCRIPTION
**Pull request by janpio**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Running `fastlane` is slow. Let's make it faster.

### Description
https://github.com/fastlane/fastlane/issues/13440 showed that most of the time in `fastlane`, even in an empty lane or a super simple command like `fastlane -v` is spent in requiring files. 

A good part of that is triggered by `fastlane_core.rb` that loads most the fastlane_core files. This is not really necessary, as the files can be loaded where and when they are actually needed.

During the test run the lane `benchmark_help_command` is run 3 times. This can be used to observe startup performance:

`master` before any changes:
macOS: 1.6, 1.5, 1.6
Ubuntu: 2.0, 2.1, 2.0
Windows: 2.5, 2.4, 2.4

After these changes:
macOS: 1.0, 0.9, 0.8
Ubuntu: 1.0, 0.9, 0.9
Windows: 2.1, 2.0, 2.1

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by KrauseFx — APPROVED** [review]
💯

**Comment by janpio** [comment]
Slight issue: While this looks awesome on CI (and in theory), it doesn't translate to real performance on my local machine - here the loading is now much slower. Huh!?

Could you please install gnomon (or similar) yourself and compare the time of `fastlane -v | gnomon` for current `master` to this branch?

(As this doesn't make any sense to me, this is also a question on StackOverflow now: https://stackoverflow.com/questions/52544443/ruby-performance-why-can-using-require-directly-before-usage-be-slower-than-m)

**Comment by KrauseFx** [comment]
With `bundle exec`

```
 ~  Developer  hacking  fastlane-proto  janpio-slim_fastlane_core  3❓  %  be fastlane -v | gnomon
[✔] 🚀
   1.4022s   fastlane installation at path:
   0.0011s   /Users/fkrause/Developer/hacking/fastlane-proto/bin/fastlane
   0.0001s   -----------------------------
   0.0013s   fastlane 2.105.2
   0.0001s

     Total   1.4053s
```

Without `bundle exec`
```
[✔] 🚀
   6.6155s   fastlane installation at path:
   0.0005s   /Users/fkrause/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/bin/fastlane
   0.0001s   -----------------------------
   0.0022s   fastlane 2.103.1
   0.0002s

     Total   6.6189s
```

**Comment by janpio** [comment]
Thanks. Now also for `master` please so we have a comparison on your machine.

**Comment by janpio** [comment]
Thanks, both are slower than the updated `janpio-slim_fastlane_core` - which is a good sign. (Benchmarking in this environment can be very strange.)

**Comment by milch** [comment]
If you're going to move require's around I would urge you to use `require_relative` when doing that. `require_relative` is much more resource friendly because it doesn't need to run through a list of potential paths where the required file could be, but instead just checks the one path that you pass

**Comment by janpio** [comment]
You are absolutely right @milch - I didn't want to bother with finding out the paths (really looking forward to your `internal()` being available ;) ) but it of course makes performance worse, so I fixed that now. Thanks for the nudge.

**Pull request closed without merging**
