### PR TITLE
Helper.keychain_path heuristic should only search for file to avoid returning directories as false positives (#9462)

### PR DESCRIPTION
**Pull request by lacostej**
See #9462 for details

### CODE REVIEW

**Review by ohayon — APPROVED** [review]
Great catch @lacostej !! 🚀

**Review by KrauseFx — APPROVED** [review]
🐑  is

**Comment by lacostej** [comment]
@KrauseFx some (maybe all) of these tests fail because the internal of the `Helper` implementation are exposed to the test. E.g.

https://github.com/fastlane/fastlane/blob/e55dc348d95591def083a84bad025242c4faa985/fastlane/spec/actions_specs/delete_keychain_spec.rb#L10-L12

Should I fix those tests? E.g. by changing its implementation to fake the result to `keychain_path` instead of its implementation?

**Comment by KrauseFx** [comment]
Nice 👍

**Pull request merged**
