### PR TITLE
Added `commit_version_bump` action

### PR DESCRIPTION
**Pull request by lmirosevic**
Checks the repo to make sure that only the relevant files have changed, these are the files that `agvtool` touchers:
- All .plist files
- The `.xcodeproj/project.pbxproj` file

Then commits those files to the repo.

Customise the message with the `:message` option, defaults to "Version Bump"

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, this would solve https://github.com/KrauseFx/fastlane/issues/35

**Comment by KrauseFx** [comment]
Sorry, maybe I'm missing something. We already have an action to bump the build number: https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/increment_build_number.rb

Could you provide a little more information of what this pull request does?

**Comment by lmirosevic** [comment]
`increment_build_number` just runs `agvtool`, which updates the build number in the projects' plist and xcodeproj files. That's cool if you want your actual build archive (.ipa) to have a new build number, but that action doesn't commit those changes to the repo, just leaves the changes in the workdir.

This action checks the git repo to make sure the only changes in the repo are those resulting from a version bump, and if so, it actually commits them to the repo.

An alternative to having this as a standalone task would be to add a `:commit` option to the increment_build_number action, so those changes are immediately committed. That's a simpler approach, but the disadvantage is that build commits will be made in your repo even if the task fails--and most actions have quite a high risk of failure: cocoapods (dependencies not available?), ipa (code doesn't compile or lib dependency missing?), sigh (member centre down?), cert (member centre down?), deliver (iTC down?).

**Comment by KrauseFx** [comment]
Not sure if just GitHub is displaying it wrong, but it looks like this PR would delete the other actions you submitted: https://github.com/KrauseFx/fastlane/pull/99/files :disappointed:

**Comment by lmirosevic** [comment]
No you were right, I meant to make a commit with just 1 parent that makes just the necessary changes, but accidentally added the master parent in there too, which effectively deleted the other merges.

Should be fixed now (I had to force push to this branch to sort it out, so if you've got a local copy, you can delete it and do a fresh checkout of it)

**Comment by KrauseFx** [comment]
Thanks, looks great :+1:

**Pull request merged**
