### PR TITLE
[fastlane_core] add -derivedDataPath when SwiftPM dependencies resolving

### PR DESCRIPTION
**Pull request by sudachi808**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

#16526

### CODE REVIEW

**Comment by sudachi808** [comment]
@googlebot I signed it!

**Comment by sudachi808** [comment]
still the same problem was happen...

https://github.com/fastlane/fastlane/issues/16339

**Review by minuscorp — APPROVED** [review]
LGTM

**Comment by minuscorp** [comment]
There's an issue with Homebrew executed with Ruby 2.4

**Comment by janpio** [comment]
That issue is not caused by this PR but is flakiness :/

**Pull request merged**
