### PR TITLE
[fastlane] Fix slack action when it adds `last_git_commit` when passing `adds last_git_commit_hash`

### LINKED ISSUE #14234: Slack last_git_commit_hash brings with it last_git_commit as well
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running
slack(default_payloads: [:git_branch, :last_git_commit_hash])

The slack plugin prints 3 payloads ('git_branch', 'last_git_commit_hash' and _'last_git_commit'_).

In the following line `should_add_payload[:last_git_commit]` should be `should_add_payload[:last_git_commit_message]`. 
https://github.com/fastlane/fastlane/blob/19779dbd4131f9bad5efddd9dd90ba92f178fa11/fastlane/lib/fastlane/actions/slack.rb#L249

This is because `last_git_commit` is part of `last_git_commit_hash` and `last_git_commit_message` is stated in the example to be used. 

This issue is also related to: #13784

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The [slack action](https://docs.fastlane.tools/actions/slack/) prints out 3 payloads `git_branch`, `last_git_commit_hash` and `last_git_commit` whenever we pass **only** two of them - `git_branch`, `last_git_commit_hash`.

closes https://github.com/fastlane/fastlane/issues/14234

### Description

The changes are about a way we were looking for a particular payload name in a `default_payloads` array. Before this change, we've been joining all of the items into a single string and check whether this string includes the payload name, i.e. 

```ruby
should_add_payload = ->(payload_name) { options[:default_payloads].nil? || options[:default_payloads].join(" ").include?(payload_name.to_s) }

options[:default_payloads] = [:git_branch, :last_git_commit_hash]
...
=> "git_branch last_git_commit_hash"

# we were iterating through each available option, so even though `last_git_commit` hasn't been provided with `default_payloads`, we were still finding this phrase as part of connected string

🙊 "git_branch last_git_commit_hash last_git_commit" includes `last_git_commit` 
```

This change introduced a new way of checking whether provided `default_payload` list contains payload name by leveraging Ruby symbols. 

The new unit test has been added to cover this case 💪 

🙇 🙇

### CODE REVIEW

**Comment by MartyCatawiki** [comment]
:+1:Nice work @mollyIV 

One small addition: It would be nice to make more clear in the example that `last_git_commit` can be used used and not `last_git_commit_message` as pointed out in this line:
https://github.com/fastlane/fastlane/blob/dbd327d1baafd6761876738ac863f88889c573d8/fastlane/lib/fastlane/actions/slack.rb#L159
Or make it work only with `last_git_commit_message`

**Comment by mollyIV** [comment]
@MartyCatawiki sure, let's keep the docs up to date, will do 💪

**Review by joshdholtz — COMMENTED** [review]
@mollyIV Ping me when you update that doc like @MartyCatawiki suggested and then we can get this merged! This is a good find and looking forward to getting this merged 💪

**Comment by mollyIV** [comment]
@joshdholtz I updated the docs 👍 🙇

**Review by MartyCatawiki — APPROVED** [review]
LGTM:+1:

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thanks again for another great contribution ❤️

**Pull request merged**
