### PR TITLE
[fastlane] drop Ruby 2.0, 2.1, 2.2 and 2.3 from gemspec

### PR DESCRIPTION
**Pull request by Kaspik**
## Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary - Supported versions are not mentioned anywhere or I didn't find the place.

### Motivation and Context
Circle.ci officially stopped supporting Ruby 2.3, we have no test coverage for that and they all are at EOL. There is no reason to keep supporting this without being sure it works via tests.

### CODE REVIEW

**Comment by Kaspik** [comment]
@joshdholtz Found annoying bug here - `Execute tests on Ubuntu` was using old Docker image `fastlane/ci:0.1.0` with Ruby 2.3.4 instead of 2.4.5...

Let me know if you are okay with this PR for drop, or if not then what do you think. 😊

**Comment by joshdholtz** [comment]
@Kaspik Good call on bumping up that docker image version 👌 Looks like Ubuntu tests are failing due to not being able to unzip an IPA in `verify_build`. You want to look into or want me to look into?

**Comment by Kaspik** [comment]
I wonder if it has something to do with the new docker file, otherwise there was no change. It uses system unzip, right? - `unzip #{build_path.shellescape} -d #{dir.shellescape} -x '__MACOSX/*' '*.DS_Store'`

Honestly I have no idea how to debug this.

**Comment by joshdholtz** [comment]
@Kaspik I ended up reruning the CircleCI build with an SSH session. I was then able to run the exact unzip command that it was failing in on got this. I’m going to fix by trying to unzip a different incorrectly signed IPA that won’t zip bomb

```sh
circleci@2c6ee3bb767d:~/project$ unzip fastlane_core/spec/fixtures/ipas/ContainsWatchApp.ipa -d /tmp/123 -x '__MA
COSX/*' '*.DS_Store'
Archive:  fastlane_core/spec/fixtures/ipas/ContainsWatchApp.ipa
  inflating: /tmp/123/ContainsWatchApp/Payload/Sample.app/Watch/Sample WatchKit App.app/Info.plist  
error: invalid zip file with overlapped components (possible zip bomb)
```

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by Kaspik** [comment]
Wohou, nice! Thanks for this, if all good now, oky to merge from my side. :)

**Comment by joshdholtz** [comment]
@Kaspik Looks like its good! I’ll wait for the other tests to pass. Also... TIL about zip bombs lol. I had no idea that was a thing.

**Review by joshdholtz — APPROVED** [review]
We’re good now! Let’s drop these 💪

**Pull request merged**
