### PR TITLE
Add check for csrf to revoke_certificate

### PR DESCRIPTION
**Pull request by asfalcone**
Addresses https://github.com/fastlane/fastlane/issues/5813#issuecomment-241476146

### CODE REVIEW

**Comment by KrauseFx** [comment]
Yeah 👍

**Comment by CareerFairPlus** [comment]
Please don't forget `create_certificate!` and `create_app!`
Thanks!

**Comment by KrauseFx** [comment]
@CareerFairPlus We already have it there

**Comment by CareerFairPlus** [comment]
Awesome, thanks!

**Comment by KrauseFx** [comment]
@CareerFairPlus Also we have this change, which might help https://github.com/fastlane/fastlane/pull/5836

**Comment by CareerFairPlus** [comment]
@KrauseFx Ok, thank you for following up.  I will try the new version when it is released.

**Pull request merged**
