### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rikusouda**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Keeping the code clean

### Description
fix typo

### CODE REVIEW

**Comment by rikusouda** [comment]
I signed it!

**Review by giginet — APPROVED** [review]

**Comment by giginet** [comment]
@rikusouda Thanks!

**Comment by rikusouda** [comment]
@giginet Thanks!

**Comment by nafu** [comment]
Thanks 🎶 @rikusouda

**Pull request merged**
