### PR TITLE
Added CI checks to show/hide_loading_indicator

### PR DESCRIPTION
**Pull request by carlosefonseca**
See #11441.

### CODE REVIEW

**Comment by carlosefonseca** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
See #11416 for work done on the same code with a different goal. but shows another location probably relevant. You might also want to make sure your code works with the other PR's code.

**Comment by carlosefonseca** [comment]
I can't do `is_ci?` on the start up animation since it's not yet available and I'd rather avoid duplicating the code. The other PR is probably better.

**Comment by janpio** [comment]
Adding an `is_ci?` check still seems useful to me as it doesn't require manually setting a ENV var, even if it won't work for all spinners.

**Pull request closed without merging**
