### PR TITLE
Fix documentation links

### PR DESCRIPTION
**Pull request by lacostej**

### CODE REVIEW

**Review by hjanuschka — DISMISSED** [review]

**Comment by lacostej** [comment]
Doh there's a plist change that came unexpectedly. Will have to amend this.

**Review by mfurtak — APPROVED** [review]

**Comment by gauravagarwalr** [comment]
The changes generated by fastlane, after running any command, in the `fastlane/README` act as noise. Recently, due to the changes in this issue/PR has caused such useless changes to be generated. This can get annoying when the developer is reviewing his/her own changes at the time of development. Is there any flag/environment variable to disable fastlane from updating README.

**Comment by hjanuschka** [comment]
@gauravagarwalr  add `skip_docs`  on top of your fastfile, to disable automatic readme generation

**Comment by lacostej** [comment]
@gauravagarwalr can you explain what you mean by "Recently, due to the changes in this issue/PR has caused such useless changes to be generated."

(I wonder if there is something else we can do to reduce your issue)

**Comment by gauravagarwalr** [comment]
@lacostej Firstly, I must apologise for the unintended tone of my previous comment. I felt having the links to the fastlane docs in the README do not help much.

One of the 2 recent changes is as shown below:

```
diff --git i/fastlane/README.md w/fastlane/README.md
index dc36ea6..a951fae 100644
--- i/fastlane/README.md
+++ w/fastlane/README.md
@@ -70,5 +70,5 @@ Create a production build
 ----

 This README.md is auto-generated and will be re-generated every time [fastlane](https://fastlane.tools) is run.
-More information about fastlane can be found on [https://fastlane.tools](https://fastlane.tools).
-The documentation of fastlane can be found on [https://docs.fastlane.tools](https://docs.fastlane.tools).
+More information about fastlane can be found on [fastlane.tools](https://fastlane.tools).
+The documentation of fastlane can be found on [docs.fastlane.tools](https://docs.fastlane.tools).
```

**Comment by lacostej** [comment]
@gauravagarwalr 

This README is meant to help people coming to your project. I understand that often they might be superfluous, at least to you :)

The changes we make to the original template should be rare and thus shouldn't affect you that often.

I would recommend to run `fastlane lanes` every time you upgrade fastlane, to make sure your project docs are up to date.

Otherwise 
* do as @hjanuschka said and prevent fastlane from generating the docs and optionally provide your own README
* or gitignore it

**Comment by gauravagarwalr** [comment]
@lacostej The idea of doing `fastlane lanes` immediately after install works best for my use case. Thanks.

**Pull request merged**
