### PR TITLE
Update Circle to use Xcode 8.3

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
For some reason this one scan test fails, but it seems to work fine with Xcode 8.3 on my local machine :/ We have to fix this though

**Comment by DanToml** [comment]
@KrauseFx I think this PR just confirmed an issue that I've been seeing on some projects over the last few days - where the simulator logarchive file is either misnamed or missing when running under 8.3 - It's on my hitlist for early this week.

**Comment by DanToml** [comment]
This should be good when #8848 is merged

**Comment by KrauseFx** [comment]
Rebased

**Comment by KrauseFx** [comment]
@DanToml seems like it's still failing on the test
```
expected FastlaneCore::Interface::FastlaneTestFailure with "Tests have failed", got #<FastlaneCore::Interface::FastlaneError: Exit status: 74> with backtrace:
```

**Comment by mccarron** [comment]
@KrauseFx @DanToml We are also seeing similar `Exit status: 74` errors with Fastlane 2.27.0 with Xcode 8.3 on Circle. Happy to provide more data if needed.

**Comment by DanToml** [comment]
@mccarron Good to know, I'll look into this asap.

**Pull request closed without merging**
