### PR TITLE
Manage JWT with Spaceship

### PR DESCRIPTION
**Pull request by snatchev**
This PR adds support for managing JWT or "Keys". Addressing issues #7848 and #9256 

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
It's art, that you managed to build this without touching any of the exiting classes, makes reviews so much easier ❤️  Great tests also.

**Comment by vbresults** [comment]
@snatchev How would we use this in match?  Is it implicit and there a use_legacy_cert flag to disable it?

**Comment by snatchev** [comment]
@vbresults we have not added this functionality to `match` yet. We are open to suggestions on how to should behave.

**Comment by vbresults** [comment]
@snatchev I see; in the short term it should be enabled with a --p8/`p8: true`.  In the longer term the old type should be phased out as other features.  There are so many benefits with the new format.

**Comment by NikKovIos** [comment]
Could you please tell how to use this feature?

**Pull request merged**
