### PR TITLE
[pilot] Trim leading zeros in app_version in wait_for_build_processing_to_be_complete

### PR DESCRIPTION
**Pull request by edwardlai3582**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Testflight truncates leading zeros in CFBundleShortVersionString and after wait_for_uploaded_build was deprecated, we can no longer get the original CFBundleShortVersionString.
To solve https://github.com/fastlane/fastlane/issues/13372#issuecomment-486729226

### Description
Compare app_version with leading zeros trimmed

### CODE REVIEW

**Comment by illl48** [comment]
> I signed it!

I signed it!

**Comment by janpio** [comment]
Ugh, this sounds like a nasty edge case based on an unfortunate implementation by Apple. We should probably add some tests for this, just that it doesn't get lost accidentally in the future.

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@illl48 Heyyy! This is an interesting find 🤔 Do you think you can move this change though to https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/build_watcher.rb and possibly add a test or two? 😊 Moving this to `BuildWatcher` will allow this change to work for other parts of _fastlane_ that might also being experiencing this same issue ❤️

**Comment by illl48** [comment]
@janpio @joshdholtz I moved the change and add a test case. If there are any problems just let me know, thanks

**Review by joshdholtz — APPROVED** [review]
@illl48 This is a great fix! Didn't know they allowed leading zeroes and didn't know they removed them 😇 Thanks for the fix!

**Pull request merged**
