### PR TITLE
fix(Docs): Typo

### PR DESCRIPTION
**Pull request by timothystewart6**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Typo
### Description

Typo in Docs

### CODE REVIEW

**Comment by getaaron** [comment]
Thanks for the PR, @timothystewart6 ! This is good to go once you get the CLA signed! :+1:

**Review by getaaron — APPROVED** [review]

**Comment by timothystewart6** [comment]
Hi.  I've signed the CLA and my commits are attached to the email I signed with.  Not sure what else I need to do.  Thank you!

**Comment by timothystewart6** [comment]
Oh weird, after I commented it removed the label.  All good!

**Comment by getaaron** [comment]
Thanks again!

**Pull request merged**
