### PR TITLE
[WIP] [deliver] fix `itc_provider` docs

### PR DESCRIPTION
**Pull request by mofneko**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Doesn't display 100% correctly in CLI 🙃

**Comment by mofneko** [comment]
Sorry
I mistakenly issued the WIP branch as PR.
Ignore me for a while because I add WIP to the title.
I will let you know when it is completed.

**Comment by janpio** [comment]
Any update on this @mofneko?

**Comment by janpio** [comment]
Closing this as the current state seems to work ok enough.

**Pull request closed without merging**
