### PR TITLE
Check for missing requires 

### PR DESCRIPTION
**Pull request by milch**
I included my require checker as a rubocop extension: https://github.com/milch/rubocop-require_tools

Checking this automatically for PRs is definitely preferred 👍🏼

### CODE REVIEW

**Comment by janpio** [comment]
Oh, that Ubuntu failure is interesting: https://circleci.com/gh/fastlane/fastlane/13647 `xcode-select` is not installed and failing. I wonder how you could guard against that :/

**Comment by milch** [comment]
Yeah seems to me like this just doesn't work. It'd probably also fail on Windows?

**Review by KrauseFx — APPROVED** [review]
Perfect! You saw the build failure, besides that, it's all 💯

**Comment by janpio** [comment]
@milch Yeah, probably not - at least not in an easy way. You could implement one of the comments that can be used to manipulate/turn off rubocop rules that is platform dependant. Then "tag" all the requires this applies to.

**Comment by milch** [comment]
@janpio Fixed ... since that code is not meant to be run on Linux anyway I just early-exit if it is 👍🏼 

Beautiful, now macOS and Ubuntu fail for the same reason

**Review by KrauseFx — APPROVED** [review]
Wow, sweeeet

**Comment by milch** [comment]
@KrauseFx Much thank, very wow

**Pull request merged**
