### PR TITLE
[scan] Make it clear that output_style: raw disables xcpretty

### PR DESCRIPTION
**Pull request by TheMetalCode**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I've personally wanted to disable xcpretty output for `fastlane scan` and found that I wasn't the only one. https://github.com/fastlane/fastlane/issues/12352

In trying to implement something like a `disable_xcpretty` option for scan, I realized that it was already possible via `output_style: "raw"`.
### Description

To ensure the documentation is clear, I edited the `output_style` option description to make it plain that the "raw" option disables xcpretty.

### CODE REVIEW

**Comment by TheMetalCode** [comment]
Just now signed the CLA

**Review by janpio — APPROVED** [review]
Simple and effective 👍

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One small change request!

**Review by joshdholtz — APPROVED** [review]
Loooooooks good! 💪

**Pull request merged**
