### PR TITLE
[action] create_pull_request: add reviewers and/or team_reviewers option

### PR DESCRIPTION
**Pull request by elneruda**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by elneruda** [comment]
@googlebot I signed it!

**Comment by elneruda** [comment]
Hi @janpio,  ci/circleci: Execute modules load up tests job failed (Error installing fastlane-2.134.0.gem) can you re-run it to validate all checks ?

**Comment by janpio** [comment]
No, the test is currently failing across all PRs so rerunning wouldn't do anything unfortunately.

**Comment by rpassis** [comment]
I had a similar issue, rebase with master and it should work.

**Comment by elneruda** [comment]
@rpassis now I can't pass the cla :(

**Comment by janpio** [comment]
The merge instead of rebase probably caused this - and also the diff pretty horrible to see the actual changes. I do not understand why Github is not more intelligent here - it should know about the actual changes :/

AS terrible as it sounds, the easiest fix would probably be to create a new branch from current `master` and then cherry pick the actual commits you made here over to that new branch, then open a new PR.

**Review by joshdholtz — APPROVED** [review]
This is great! Thanks for adding this feature in 😊 I removed the merged commits and rebased from master so that everything is now good including the CLA 💪 Really appreciate the contribution ❤️

**Comment by elneruda** [comment]
Hi @joshdholtz, thank you for validating PR especially during holidays 🎄

**Comment by joshdholtz** [comment]
@elneruda No problem at all 😊 Sorry it took so long to get to this. I got pretty backlogged 😬

**Pull request merged**
