### PR TITLE
Added new `fastlane lanes --json` flag to make it easier to get the lanes

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by RishabhTayal** [comment]
👍

**Comment by RishabhTayal** [comment]
Getting error. Crash report id: 60875e0e5bf0eb5b5ba42083e1b58b4d

**Comment by KrauseFx** [comment]
@RishabhTayal please share the complete output, including the stack trace.

**Comment by RishabhTayal** [comment]
Here is the crash report: [sentry_d0dd73b0496b97ba8135c66304a38be2.json.zip](https://github.com/fastlane/fastlane/files/140884/sentry_d0dd73b0496b97ba8135c66304a38be2.json.zip)

**Comment by RishabhTayal** [comment]
When I run from the command from Terminal, it works fine. But doesn't work from [Fastlane-Plugin](https://github.com/RishabhTayal/Fastlane-Plugin).

**Comment by RishabhTayal** [comment]
It was my mistake. I needed to change the `fastlane` path to the cloned directory. :+1:

**Comment by RishabhTayal** [comment]
@KrauseFx When do you plan on releasing this feature?

**Comment by KrauseFx** [comment]
@RishabhTayal Whenever you say that the feature works as expected for you and you can use it for the plugin :+1:

**Comment by RishabhTayal** [comment]
@KrauseFx Already integrated into the plugin! Works perfectly for my use case. Waiting for you to release. 😎

**Comment by KrauseFx** [comment]
Great, thank you @RishabhTayal :+1:

**Comment by ohwutup** [comment]
WOOT!

**Pull request merged**
