### PR TITLE
[fastlane] Primary language

### LINKED ISSUE #7074: Produce: You must choose a primary language. You must choose a primary language.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Run produce to create new app in ItunesConnect, it cannot create new app due to missing primary language although i already specific the language.
##### 
18:40:16]: [32m--- Step: produce ---[0m
[18:40:16]: [32m---------------------[0m

+----------------+----------------------------------+
|             [32mSummary for produce 1.3.0[0m             |
+----------------+----------------------------------+
| username       | developers@360.com         |
| app_name       | "CRUYFF"                         |
| team_id        | QWERTYUI                      |
| team_name      | " bv"         |
| app_identifier |ABC |
| language       | Dutch                            |
| app_version    | 2.11.0                           |
| sku            | ABC|
| company_name   | "bv"         |
| itc_team_id    | 12345678                        |
| skip_itc       | false                            |
| skip_devcenter | false                            |
+----------------+----------------------------------+

[18:40:22]: [32m[DevCenter] App 'nl.cruyffclassics.cruyffclassics' already exists, nothing to do on the Dev Center[0m
[18:40:25]: [32mCreating new app '"CRUYFF"' on iTunes Connect[0m
[18:40:26]: [33m[33mVariable Dump:[0m[0m
[18:40:26]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios createnewapp", :XCODEBUILD_DERIVED_DATA_PATH=>nil}
[18:40:26]: [31mYou must choose a primary language. You must choose a primary language.[0m

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.12.1                                           |
| Ruby                | 2.3.1                                             |
| Bundler?            | false                                             |
| Git                 | git version 2.9.3 (Apple Git-75)                  |
| Installation Source | /Users/jenkins/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                        |
| Ruby Lib Dir        | /Users/jenkins/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |
| Is contained        | false                                             |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/       |
| Xcode Version       | 8.1                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | 🚫 Update availaible |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | 🚫 Update availaible |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| fastlane            | 1.109.0 | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.56.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| io-console                | 0.4.5        |
</details>

### PR DESCRIPTION
**Pull request by hjanuschka**
should fix: https://github.com/fastlane/fastlane/issues/7074 as of itunes api changes.

can someone help verifing this?

todo:
  *  probably fix tests

### CODE REVIEW

**Comment by asfalcone** [comment]
@hjanuschka I think defaulting `primaryLocaleCode` to "en-US" makes sense, but I don't think we can deprecate the `primaryLanguage` field.

Can we add another param to this method for primary_locale_code and use that as the value for `primaryLocaleCode`?

Kinda like this:
```ruby
data['primaryLanguage'] = { value: primary_language }
data['primaryLocaleCode'] = { value: primary_locale_code || 'en-US' }
```

That way we aren't passing "English" or any language string to the locale code field, and we move the defaulting of English to the locale.

**Comment by hjanuschka** [comment]
@asfalcone ohh i missed to reply - i think first of all we should clarify if this fix fixes the issue?
because if it is not the bug, i think a change is not required, how do you see it?

**Comment by asfalcone** [comment]
@hjanuschka agreed, can you encourage some folks on #7074 to try out your fix again? :)

**Comment by tobiasstrebitzer** [comment]
I can confirm that the solution proposed by @asfalcone works. It seems like iTunes requires both primaryLanguage and primaryLocaleCode set to work.

I think we can safely defer the locale code from the language provided.

```ruby
    # Creates a new application on iTunes Connect
    # @param name (String): The name of your app as it will appear on the App Store.
    #   This can't be longer than 255 characters.
    # @param primary_language (String): If localized app information isn't available in an
    #   App Store territory, the information from your primary language will be used instead.
    # @param version (String): The version number is shown on the App Store and should
    #   match the one you used in Xcode.
    # @param sku (String): A unique ID for your app that is not visible on the App Store.
    # @param bundle_id (String): The bundle ID must match the one you used in Xcode. It
    #   can't be changed after you submit your first build.
    def create_application!(name: nil, primary_language: "English", version: nil, sku: nil, bundle_id: nil, bundle_id_suffix: nil, company_name: nil)
      # First, we need to fetch the data from Apple, which we then modify with the user's values
      app_type = 'ios'
      r = request(:get, "ra/apps/create/v2/?platformString=#{app_type}")
      data = parse_response(r, 'data')

      # Now fill in the values we have
      # some values are nil, that's why there is a hash
      data['versionString'] = { value: version }
      data['name'] = { value: name }
      data['bundleId'] = { value: bundle_id }
      data['primaryLanguage'] = { value: primary_language }
      data['primaryLocaleCode'] = { value: primary_language.to_language_code }
      data['vendorId'] = { value: sku }
      data['bundleIdSuffix'] = { value: bundle_id_suffix }
      data['companyName'] = { value: company_name } if company_name
      data['enabledPlatformsForCreation'] = { value: [app_type] }

      data['initialPlatform'] = app_type
      data['enabledPlatformsForCreation'] = { value: [app_type] }

      # Now send back the modified hash
      r = request(:post) do |req|
        req.url 'ra/apps/create/v2'
        req.body = data.to_json
        req.headers['Content-Type'] = 'application/json'
      end

      data = parse_response(r, 'data')
      handle_itc_response(data)
    end
```

(changing the code like so allowed me to finally create the app)

**Comment by tobiasstrebitzer** [comment]
One note though: Invoking "create_application!" with explicitly setting "primary_language" to nil will cause an error, eventually you'll need to fallback the value to "English" manually:

```ruby
    # Creates a new application on iTunes Connect
    # @param name (String): The name of your app as it will appear on the App Store.
    #   This can't be longer than 255 characters.
    # @param primary_language (String): If localized app information isn't available in an
    #   App Store territory, the information from your primary language will be used instead.
    # @param version (String): The version number is shown on the App Store and should
    #   match the one you used in Xcode.
    # @param sku (String): A unique ID for your app that is not visible on the App Store.
    # @param bundle_id (String): The bundle ID must match the one you used in Xcode. It
    #   can't be changed after you submit your first build.
    def create_application!(name: nil, primary_language: nil, version: nil, sku: nil, bundle_id: nil, bundle_id_suffix: nil, company_name: nil)
      # First, we need to fetch the data from Apple, which we then modify with the user's values
      app_type = 'ios'
      primary_language ||= "English"
      r = request(:get, "ra/apps/create/v2/?platformString=#{app_type}")
      data = parse_response(r, 'data')

      # Now fill in the values we have
      # some values are nil, that's why there is a hash
      data['versionString'] = { value: version }
      data['name'] = { value: name }
      data['bundleId'] = { value: bundle_id }
      data['primaryLanguage'] = { value: primary_language }
      data['primaryLocaleCode'] = { value: primary_language.to_language_code }
      data['vendorId'] = { value: sku }
      data['bundleIdSuffix'] = { value: bundle_id_suffix }
      data['companyName'] = { value: company_name } if company_name
      data['enabledPlatformsForCreation'] = { value: [app_type] }

      data['initialPlatform'] = app_type
      data['enabledPlatformsForCreation'] = { value: [app_type] }

      # Now send back the modified hash
      r = request(:post) do |req|
        req.url 'ra/apps/create/v2'
        req.body = data.to_json
        req.headers['Content-Type'] = 'application/json'
      end

      data = parse_response(r, 'data')
      handle_itc_response(data)
    end
```

**Comment by hjanuschka** [comment]
@tobiasstrebitzer many many thx - i'll let the guys in the issue test it

**Comment by hjanuschka** [comment]
2 positive reports, removed WIP  👏

**Comment by asfalcone** [comment]
This is awesome! Great use of `to_language_code`!

**Review by asfalcone — APPROVED** [review]

**Comment by vbresults** [comment]
@hjanuschka So, say I have the language code tr-TR, would I still need to turn that into "Turkish" or can I just pass tr-TR to deliver?

**Comment by hjanuschka** [comment]
@vbresults you have to use "Turkish" in that case, i guess.

**Comment by hjanuschka** [comment]
@vbresults there seems to be a bug with the locale translation, which will be triggered with "Turkish" see this pr: https://github.com/fastlane/fastlane/pull/7193 for a fix. maybe you want to +1 it.

**Pull request merged**
