### PR TITLE
escapes branch names in `push_to_git_remote` action

### LINKED ISSUE #13389: push_to_git_remote doesn't escape branch names
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
push_to_git_remote seems to not be escaping parameters

The git command is constructed as follows

```
        command = [
          ‘git’,
          ‘push’,
          params[:remote],
          “#{local_branch}:#{remote_branch}”
        ]

```

I believe that the branch names should be escaped as follows

`“'#{local_branch}':'#{remote_branch}'”
`

The issue being that pushing a branch named `release-1.0.0(1)` to the git remote fails with 
`bash: syntax error near unexpected token `('`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.5/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.5/lib                |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.14.6       |
| slack-notifier        | 2.3.2        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.6.0        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-screen            | 0.6.4        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| mini_magick           | 4.5.1        |
| multi_xml             | 0.6.0        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| declarative           | 0.0.10       |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| httpclient            | 2.8.3        |
| google-api-client     | 0.21.2       |
| emoji_regex           | 0.1.1        |
| faraday               | 0.15.2       |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| excon                 | 0.62.0       |
| CFPropertyList        | 3.0.0        |
| plist                 | 3.4.0        |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20180417 |
| faraday_middleware    | 0.12.2       |
| fastimage             | 2.1.3        |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.3        |
| dotenv                | 2.4.0        |
</details>

*generated on:* **2018-09-19**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by RishabhTayal**
fixes #13389 by escaping branch name

### CODE REVIEW

**Review by janpio — CHANGES_REQUESTED** [review]
Windows doesn't know `'` as an escaping thing.

**Comment by janpio** [comment]
Fails on Windows:
```
C:\Projects\Fastlane\win-fastlane (janpio-release-1.0.0(1) -> origin)
λ git push origin 'janpio-release-1.0.0(1)':'janpio-release-1.0.0(2)'
error: src refspec 'janpio-release-1.0.0(1)' does not match any.
error: failed to push some refs to 'https://github.com/fastlane/fastlane'
```

Works on Windows:
```
C:\Projects\Fastlane\win-fastlane (janpio-release-1.0.0(1) -> origin)
λ git push origin "janpio-release-1.0.0(1)":"janpio-release-1.0.0(2)"
Username for 'https://github.com': ...
```

You should probably just use `.shellescape` on the string.

**Comment by RishabhTayal** [comment]
like this: `"#{local_branch.shellescape}:#{remote_branch.shellescape}"`

**Comment by janpio** [comment]
Yep, that should work.

**Comment by RishabhTayal** [comment]
@janpio Done. Ready for review now.

**Review by janpio — APPROVED** [review]

**Pull request merged**
