### PR TITLE
Add Spaceship::Portal::App#update_name

### PR DESCRIPTION
**Pull request by cpunion**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

### CODE REVIEW

**Comment by KrauseFx** [comment]
Ah nice, thanks, I didn't know it's possible to update the name. Can you also update the docs in `DeveloperPortal.md` for this?

**Comment by KrauseFx** [comment]
The tests are failing:

```
      Real HTTP connections are disabled. Unregistered request: POST https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/updateAppIdName.action with body 'appIdId=B7JBD8LHAA&name=The+New+Name&teamId=XXXXXXXXXX' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Spaceship 2.3.0'}

You can stub this request with the following snippet:

stub_request(:post, "https://developer.apple.com/services-account/QH65B2/account/ios/identifiers/updateAppIdName.action").
  with(:body => {"appIdId"=>"B7JBD8LHAA", "name"=>"The New Name", "teamId"=>"XXXXXXXXXX"},
       :headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Spaceship 2.3.0'}).
  to_return(:status => 200, :body => "", :headers => {})
```

**Comment by cpunion** [comment]
@KrauseFx Done. Thanks for you help.

I saw a rule:

* We currently don't accept new actions, please publish a plugin instead, more information in Plugins.md

Should I write this action in a plugin?

**Comment by KrauseFx** [comment]
New API endpoints in _spaceship_ are good, thanks for submitting the PR 👍

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Looks great, thanks for updating the PR 👍

**Pull request merged**
