### PR TITLE
Add number_of_commits action

### PR DESCRIPTION
**Pull request by onevcat**
Add `number_of_commits` action. It will return the total count of commit in current git branch.

### CODE REVIEW

**Comment by KrauseFx** [comment]
This is perfect, thank you for contributing @onevcat :rocket:

**Comment by KrauseFx** [comment]
I added some documentation, let me know if that makes sense: https://github.com/fastlane/fastlane/commit/e4841929b6708bef80d87d5fea2db329f1170e68

**Comment by onevcat** [comment]
It's perfect. Cheers!

(Thanks to bring fastlane to us. I love it so much.)

**Comment by KrauseFx** [comment]
:smile:

**Pull request merged**
