### PR TITLE
[WIP] Update Actions file

### PR DESCRIPTION
**Pull request by jinjorge**

### CODE REVIEW

**Comment by jinjorge** [comment]
There's a link right above the following (section)[https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#clear_derived_data] that's labeled `prefilling data guide`. Where is that link supposed to lead to?

**Comment by jinjorge** [comment]
@KrauseFx any comment on the question in the previous post?

Thanks!

**Comment by KrauseFx** [comment]
@jinjorge sorry for the late reply - nice catch, this was back when snapshot used the old UI Automation, feel free to remove the link as we don't have a new one yet 👍

**Comment by asfalcone** [comment]
Going to merge this as is. Please submit another PR for the other linke @jinjorge 👍

**Comment by KrauseFx** [comment]
Thanks @asfalcone 🚀

**Pull request merged**
