### PR TITLE
[danger] Added detection of # in PR-body

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Oh so meta @fastlane-danger-bot

**Comment by mfurtak** [comment]
👍 

The regex match is probably good enough, but it would be really nice if Danger exposed the [events associated with the issue](https://developer.github.com/v3/issues/events/#list-events-for-an-issue). Then we could say for sure that an issue was referenced.

**Comment by KrauseFx** [comment]
@mfurtak: do you mean that danger should be re-triggered if the description was updated?

**Comment by mfurtak** [comment]
Nope, I was just noting that whenever someone adds a hash-tag + number reference to another issue (like we're trying to detect here) it creates an "event" associated with the GitHub issue. The list of events for a GitHub issue are also available in the API, so it might be interesting if Danger could expose that data for use in writing rules.

If that was true, we could say more definitely that one issue references another!

I opened an issue with Danger to track the idea: https://github.com/danger/danger/issues/246

**Comment by orta** [comment]
Clever

**Pull request merged**
