### PR TITLE
Update rake task name

### PR DESCRIPTION
**Pull request by patoroco**
According https://github.com/fastlane/fastlane/blob/master/rakelib/test_all.rake#L71

### CODE REVIEW

**Comment by patoroco** [comment]
I'm not sure if :now symbol (in doc paragraph) makes sense after that...

**Comment by KrauseFx** [comment]
Yeah, nice catch, thanks @patoroco 👍

**Comment by patoroco** [comment]
@KrauseFx what do you think about `:now` symbol in doc to run only some tests? I tried it, but it doesn't work :(

**Comment by KrauseFx** [comment]
To just run test (e.g. for `gym`) just do this:
```
cd gym
rspec
```
or `bundle exec rspec`

**Pull request merged**
