### PR TITLE
Update contributing docs to add --path for deps

### PR DESCRIPTION
**Pull request by LegNeato**
Following the current directions throws this error:

```
+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Switch to validate_repo lane | 0           |
| 💥   | ensure_no_debug_code         | 0           |
+------+------------------------------+-------------+

[18:16:23]: fastlane finished with errors

[!] Found debug code 'binding.pry': 
```

when running tests on a fresh install. It appears that `.gitignore` and the test runner expects `.bundle` to be the location (and that's what CircleCI does).

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description
Simple documentation fix to help first-time contributors.

### Motivation and Context
Simple documentation fix to help first-time contributors.

### CODE REVIEW

**Comment by LegNeato** [comment]
I signed it!

**Comment by KrauseFx** [comment]
Could you clarify this a little more? By default `bundle install` installs the gems somewhere in `~/.` so the current directory shouldn't be affected

**Comment by LegNeato** [comment]
Not sure, I just used bundler for the first time and it suggested `./vendor`, which when used caused the tests to fail.

**Comment by KrauseFx** [comment]
This must be related to your bundler config somehow. I don't know enough about it, but by default running `bundle install` or `bundle update` won't touch the current directory, besides the `Gemfile.lock`

**Comment by asfalcone** [comment]
I'm going to close this PR because I don't think the change is necessary for the majority of users.

**Pull request closed without merging**
