### PR TITLE
default version bump commit text with build number

### PR DESCRIPTION
**Pull request by kohtenko**
I suppose this commit message would be much easier to read in git history

### CODE REVIEW

**Comment by KrauseFx** [comment]
Sorry, but we can't just remove a parameter, this would fail all existing builds. Let's set change the  message parameter to `optional` and switch set a default message based on the version. Keep in mind, the version number might be nil.

**Comment by kohtenko** [comment]
There is a problem with default values. It's initialised before `increment_build_number` action can be trigged. This why I move default value into `run`.

We probably can just leave default value as it is, but still make a check in `run`. Do you have any thoughts about this approach?

**Comment by KrauseFx** [comment]
It's easy, you set `optional: true` and then add this to the action itself

```ruby
params[:message] ||= (build_number ? "Version Bump to #{build_number}" : "Version Bump")
```

**Comment by kohtenko** [comment]
You right, this looks much better

**Comment by KrauseFx** [comment]
That's great, thanks for contributing @kohtenko :+1:

**Comment by skywinder** [comment]
in continue of https://github.com/KrauseFx/fastlane/issues/468#issuecomment-127250625
Sometimes I need to specify my custom build number without calling `increment_build_number`. So do you know, is it possible to change `Actions::SharedValues` manually?

**Comment by kohtenko** [comment]
@skywinder No, I don't. 
About your case: it looks like your failure somewhere in this lines:
```
build_number = lane_context[SharedValues::BUILD_NUMBER] 
params[:message] ||= (build_number ? "Version Bump to #{build_number}" : "Version Bump")
```

**Comment by kohtenko** [comment]
I figured it out. This commit https://github.com/KrauseFx/fastlane/commit/c4828e8d7d6f5b3e2802111cfb83ebf0997ed1e8 is the reason.
@KrauseFx you can simply reverse this commit and release new version.

**Comment by KrauseFx** [comment]
Already pushed a new version fixing this. Sorry! :+1:

**Pull request merged**
