### PR TITLE
Custom FastFile Location

### PR DESCRIPTION
**Pull request by johnthepink**
Would you be open to allowing a custom FastFile location to be passed as an environment variable like this? Let me know if you have any feedback. Thanks!

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for the pull request. To be honest, I'd much rather prefer passing the path via a command line argument. What do you think?

Mainly I'm a little concerned about potential side effect. What if you pass `../Fastfile` - in which directory will actions like `sh` be executed? Did you try this change with different scenarios?

**Comment by KrauseFx** [comment]
I think this should use the `Dir.chdir` option, but this might break something. How about we just allow passing a custom name for the `Fastfile`, basically to support having `Fastfile1`, etc.?

On the other hand you can already import a `Fastfile` from a different location...

**Comment by KrauseFx** [comment]
I'll close this pull request for now, as I don't think we should go ahead with this feature. Thanks for the PR anyway :+1:

**Comment by johnthepink** [comment]
Makes sense. Thanks!

**Pull request closed without merging**
