### PR TITLE
Output supported platforms in action tables

### PR DESCRIPTION
**Pull request by janpio**
Step 1 of https://github.com/fastlane/docs/issues/649 is to show the supported platforms of an action. This PR outputs adds this.

### CODE REVIEW

**Review by getaaron — APPROVED** [review]
👍

**Review by joshdholtz — COMMENTED** [review]
Can you include a screenshot for doc changes so its easier to see what this change visually looks like at a quick glance? 😊

**Comment by janpio** [comment]
Nope, as I can't create the docs on Windows. (Also honestly no idea what the proper process would be to get these generated changes from `fastlane` over to `docs` locally)

**Review by joshdholtz — APPROVED** [review]

**Comment by janpio** [comment]
Thanks for the explanation. (Is this documented somewhere?)

Now I only have to make `mkdocs serve` work on Windows for the next time ;)

**Pull request merged**
