### PR TITLE
[frameit] Fixed offsets for some devices (issue #6899)

### PR DESCRIPTION
**Pull request by claesjacobsson**
🔑
Screenshots were misplaced in device frames.
Closes https://github.com/fastlane/fastlane/issues/6899

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks good, this just needs to be tested from our side before merging 👍

**Comment by claesjacobsson** [comment]
👍

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Looks great, thanks 👍

**Comment by KrauseFx** [comment]
Alright, thanks, I just pushed a new release, you can run `frameit update_frames` to get the new offsets 👍

**Comment by claesjacobsson** [comment]
👍

**Pull request merged**
