### PR TITLE
Version bump to 2.70.3

### PR DESCRIPTION
**Pull request by taquitos**
Auto-generated by fastlane 🤖

**Changes since release '2.70.2':**

* Update support for `latest` for `download_dsyms` action (#10828) via Shai Mishali
* Verify all env variables are set for deployment (#11251) via Felix Krause
* Update yard development dependency (#11308) via Felix Krause
* Fix version selection with import_from_git (#11270) via Jimmy Dee
* If using system ruby, and json isn't installed, do the right thing (#11306) via Joshua Liebowitz
* Respect skip_type_validation when testing sample code. (#11305) via Mark Pirri
* [supply] replace hardcoded string `en-US` with actual language (#11296) via Jan Piotrowski

### CODE REVIEW

**Review by ohayon — APPROVED** [review]
Are those versions in the swift files bumped automatically? 🌟  :nice: 🚀

**Comment by taquitos** [comment]
@ohayon they sure are 🎉

**Comment by jdee** [comment]
I noticed that in this 2.70.3 release all the generated Swift files say generated by 2.70.2. I wonder if that could lead someone to think their generated API is out of date. I assume the version is incremented after the Swift API is generated. I imagine that's easy to change, but maybe you made a conscious decision to do it this way.

I've developed a habit of actually doing the version bump (without a tag) immediately after each release in my repos, so that unreleased code in master always has a different version from what's released to prod. The tag is added only when the release is done (by `rake release` in a gem), and each version bump comes immediately after the preceding tag. I think this can have certain benefits. It _has_ led at least one user to conclude that I forgot to release something in the past, and had to be explained.

Anyway, if the versions at the end of each Swift source file should be changed, that would be another way to do it.

**Comment by taquitos** [comment]
I was thinking about this stuff today, and you bring up a good point. My thought process was "Well, technically, it was generated on the previous version because the next version hasn't been released yet". That being said... I think the point about user confusion is more important than being `technically` correct. In the future, I think we should increment the version, then generate the swift. Thanks for pointing that out @jdee

**Pull request merged**
