### PR TITLE
[action] add error handling for `xcodes` when running the `installed` cmd

### PR DESCRIPTION
**Pull request by mokagio**
### Motivation and Context

This changes the `xcodes` call for that branch to the `Actions.sh` block version so that we can trap any error and bubble it up to the user.

The previous version would have otherwise crashed. More details below.

This change will help users migrate from `ensure_xcode_version(version: '14')` to `xcodes(version: '14', select_for_current_build_only: true)`

### Description

When trying the `xcodes` in place of `ensure_xcode_version` for a version not installed, I experienced a crash. The reason for it was that `xcodes installed <version>` exits with 1 if the version is not installed which made its caller in Fastlane raise 

```
fastlane_core/lib/fastlane_core/ui/interface.rb:153:in 

shell_error!': \e[31m[!] Exit status of command '/opt/homebrew/bin/xcodes installed '14.0'' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
```

<details>
<summary>Full crash log</summary>

```
[14:11:07]: --------------------
[14:11:07]: --- Step: xcodes ---
[14:11:07]: --------------------
[14:11:07]: Running xcodes version 1.1.0
[14:11:07]: $ /opt/homebrew/bin/xcodes installed '14.0'
[14:11:07]: ▸ 14.0 is not installed.
...
+------------------+--------------------------+
[14:11:07]: Exit status of command '/opt/homebrew/bin/xcodes installed '14.0'' was 1 instead of 0.
14.0 is not installed.

[14:11:07]: fastlane finished with errors
...
	 4: from /Users/gio/Developer/a8c/wcios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/actions/xcodes.rb:40:in `run'
	 3: from /Users/gio/Developer/a8c/wcios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/gio/Developer/a8c/wcios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.211.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/gio/Developer/a8c/wcios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/gio/Developer/a8c/wcios/vendor/bundle/ruby/2.7.0/gems/fastlane-2.211.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command '/opt/homebrew/bin/xcodes installed '14.0'' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
14.0 is not installed.
\e[0m
```

</details>

To deal with it, I passed a block to `Action.sh` to handle the error, if any.

### Testing Steps

I added a unit test for the failing behavior. 

The fix can also be verified locally with a lane such as

```ruby
lane :test_for_xcodes do
  version = '10' # or any version not installed on the machine running the test
  xcodes(version: version, select_for_current_build_only: true)
end
```

### Next steps

The approach could be carried over to the other `xcodes` invocations via `sh`. I didn't do it in here to keep the PR focused at addressing one specific crash and to get validation on the approach itself.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary. – Not necessary

### CODE REVIEW

**Review by rogerluan — APPROVED** [review]
💯 👏 Thank you for this! Nice touch! ✨

**Comment by mokagio** [comment]
Thank you for the preemptive review approval @rogerluan 😄

**Review by rogerluan — APPROVED** [review]

**Comment by mokagio** [comment]
Thanks @rogerluan 🙇‍♂️ 

Who should I ping to get this merged? Hoping to avoid developing merge conflicts while this sits in the queue.

**Review by getaaron — APPROVED** [review]
:shipit:

**Pull request merged**
