### PR TITLE
[fastlane] sierra keychain path

### PR DESCRIPTION
**Pull request by hjanuschka**
as proposed here: https://github.com/fastlane/fastlane/issues/7046

### CODE REVIEW

**Comment by milch** [comment]
Hmm, we discussed here #6460 if we should put the keychain-finding into the core so we can access it from everywhere. Since this is now the second time this has come up, maybe now would be the time to do this.

**Comment by hjanuschka** [comment]
@milch - ok so we should continue with: #6460, if so lets close this PR  - as long as the underlying issue is solved, i am fine with it, right now users might have troubles using `unlock_keychain` on a fresh deployed sierra machine.

**Comment by milch** [comment]
@hjanuschka Yeah I think the path will be: merge #6460 -> new PR w/ keychain lookup in fastlane_core -> new PR for this issue

**Comment by hjanuschka** [comment]
@milch  as #6460  has been merged, i did the 3 follow up PR's to solve #7046

**Pull request closed without merging**
