### PR TITLE
[pilot] update build description upon upload

### PR DESCRIPTION
**Pull request by tadelv**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [☑️ ] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [ ☑️] Run `bundle exec rubocop -a` to ensure the code style is valid
- [ 🔑] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [☑️ ] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Hey, this is my contribution to #6628, please take a look if it worthy of inclusion in the master repo

### CODE REVIEW

**Review by ohayon — CHANGES_REQUESTED** [review]
Hey @tadelv, thanks for the PR! This is definitely a good change that would be sweet to merge. I do however think that this should be controlled by an option so that it won't change current expected behavior by default. 🚀

**Comment by tadelv** [comment]
@ohwutup, that's great to hear!
I'll get to it as soon as possible.

**Comment by tadelv** [comment]
@ohwutup it seems I borked something while rebasing my feature on top of upstream... What can i do?

**Comment by KrauseFx** [comment]
The easiest thing is probably to re-apply the changes to the latest code from the `master` branch 👍

**Comment by tadelv** [comment]
there is a new PR tracking this now: #6946

**Pull request closed without merging**
