### PR TITLE
[gradle] add multiple tasks option

### PR DESCRIPTION
**Pull request by att55**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

If user wants to execute multiple gradle tasks, Fastfile is like below. 

```
gradle(task: 'assembleDebug bundleDebug')
```

In this case, I think the key should be `tasks` and the value type should be `Array`.  (**Or gradle action should not accept multiple tasks.**)

So, I will add `tasks` parameter which type is Array to prevent confusing users. 

### Description

Which one of these two do you prefer? 

- Accept multiple gradle tasks. (The content in this PR)

- Disallow multiple gradle tasks.
If user want to execute multiple tasks, Fastfile is like below.

```
gradle(task: 'assembleDebug')
gradle(task: 'bundleDebug')
```
If disallowing multiple gradle tasks is better, I will change this PR content.

### CODE REVIEW

**Review by JhonJimenezCastro — APPROVED** [review]

**Comment by janpio** [comment]
The currently behavior probably stems from how the `gradle` CLI command behaves. Why is this change _needed_?

**Comment by att55** [comment]
@janpio Thank you for your review!

> The currently behavior probably stems from how the gradle CLI command behaves.

Yes, you are right. But I think `tasks option(type: array)` is needed to be **more understandable** when users pass multiple tasks to gradle action.

**Comment by janpio** [comment]
No, I also like it - just have to make sure of the motivation behind it and then make sure the new option doesn't lead to confusion.

You moved the `required` check to the code, correcT?

**Comment by att55** [comment]
> I also like it

Sorry, I misunderstood 🙏 

> You moved the required check to the code, correcT?

Yes! I moved the check which `task` is passed or not to the code.
That's because `task` was `optional`.

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This looks great! Thanks for adding this 😊 Really appreciate that contribution ❤️

**Pull request merged**
