### PR TITLE
Show better error message if gym can't detect provisioning profiles to use

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by lyndsey-ferguson** [comment]
Since you're here, could you check to see if the `provisioningProfiles` are formatted correctly? We have preprocessor macros for our `PRODUCT_BUNDLE_IDENTIFIER` and `PROVISIONING_PROFILE_SPECIFIER` and those were getting sent to this code: the exportOptionsPlist file had the variables rather than the proper values, i.e.
```
provisioningProfiles: {
  $PRODUCT_BUNDLE_IDENTIFIER_APP => $PROVISIONING_PROFILE_SPECIFIER_UUID,
  $PRODUCT_BUNDLE_IDENTIFIER_NOTIFICATION_SERVICE => $PROVISIONING_PROFILE_SPECIFIER_NOTIFICATION_SERVICE
}
```
The error we got from the export archive step was _super_ confusing. If this code could check to see if the values on the left were of a bundle id (i.e. /\w+\.\w+.*) at least, that would be great.

**Review by mpirri — APPROVED** [review]
🚢

**Comment by KrauseFx** [comment]
@lyndsey-ferguson Sorry I don't have this setup currently, so it doesn't work for you? What are the steps required to fix it?

**Comment by lyndsey-ferguson** [comment]
😢 We worked around the issue by passing the `:export_options` with the correct `:provisioningProfiles` but it was a monster to track down the problem. A warning about bad `:provisioningProfiles` would have saved us a lot of time.

**Comment by lyndsey-ferguson** [comment]
I was hoping to be efficient (lazy) and have someone else update the error handling

**Pull request merged**
