### PR TITLE
Fixes build_and_upload_to_appetize for custom build locations

### PR DESCRIPTION
**Pull request by WolfgangD**
Fixes issue #4589

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks for the fix! Unfortunately CI has an issue after squashing the commits. Do you mind rebasing from master and seeing if that fixes the problem? 👍

**Comment by WolfgangD** [comment]
@KrauseFx Happy to help. I've rebased and all checks passed.

**Comment by KrauseFx** [comment]
This is great, thanks! Are you already using [device_grid](https://github.com/fastlane/fastlane/tree/master/fastlane/lib/fastlane/actions/device_grid)? 

Thanks for your contribution @WolfgangD 🚀

**Comment by WolfgangD** [comment]
Not yet, but it is on the "to be tried out" list. Right now, we are using appetize for weekly builds to improve communication between Android an iOS teams.

**Comment by michary** [comment]
This fix breaks the build for Cocoapods resources:

```
▸ Running script '📦 Copy Pods Resources'

❌  error: Resource "/tmp/fastlane_build/Build/Products/Release-iphonesimulator/HockeySDK/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script.


** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution 📦\ Copy\ Pods\ Resources /tmp/fastlane_build/Build/Intermediates/SprIT.build/Release-iphonesimulator/SprIT\ beta.build/Script-46314BBA19DABC2900E9EE69.sh
(1 failure)
```

**Pull request merged**
