### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by Lutzifer**

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Nice, that's awesome, did you manually find those things?

**Comment by KrauseFx** [comment]
Oh, the tests are failing, could you fix that?

**Comment by Lutzifer** [comment]
will have a look at the tests.

I did find them manually, but I wanted to get up to date on what the tools and actions are able to do anyway :-)

**Comment by KrauseFx** [comment]
Cool, thanks, I can't seem to open the Circle output, but I'd assume it's about having a `.` at the end of the `description:` or similar.

**Comment by Lutzifer** [comment]
@KrauseFx The problem was: [!] Found debug code '# TODO': 

The two places where it was need better docs nonetheless

**Review by KrauseFx — APPROVED** [review]
🎉

**Pull request merged**
