### PR TITLE
[deliver] Update upload_price_tier

### LINKED ISSUE #21236: `upload': \e[31m[!] undefined method `first' for nil:NilClass\e[0m (NoMethodError) on fastlane version 2.212.2
### Issue Description
 I'm using circleci to build my ios app. 
 This issue started after upating to fastlane's latest version.

##### Command executed
fastlane run deliver dev_portal_team_name:*** team_name:*** itc_provider:*** app_identifier:*** app_version:*** ipa:**** app_icon:**** screenshots_path:**** metadata_path:****  price_tier:*** app_rating_config_path:*** automatic_release:****  submit_for_review:true overwrite_screenshots:true precheck_include_in_app_purchases:false run_precheck_before_submit:false force:true

##### Complete output when running fastlane, including the stack trace and command used

`[12:30:22]: Successfully uploaded screenshots to App Store Connect

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fix accessing first element of nil array in upload_price_tier
    https://github.com/fastlane/fastlane/pull/21213 [open] 1 💬
    a day ago

➡️  [spaceship][deliver] add app clips support for specifying default experience metadata
    https://github.com/fastlane/fastlane/pull/20300 [open] 26 💬
    2 weeks ago

➡️  [supply] added support for refresh tokens as an authentication method
    https://github.com/fastlane/fastlane/pull/16414 [open] 10 💬
    23 May 2020

and 221 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60first%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/upload_price_tier.rb:24:in `upload': \e[31m[!] undefined method `first' for nil:NilClass\e[0m (NoMethodError)
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:161:in `upload_metadata'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:61:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/fastlane:25:in `load'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/fastlane:25:in `<main>'
/Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/upload_price_tier.rb:24:in `upload': undefined method `first' for nil:NilClass (NoMethodError)
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:161:in `upload_metadata'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/deliver/lib/deliver/runner.rb:61:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/upload_to_app_store.rb:22:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:226:in `block (2 levels) in run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/fastlane:25:in `load'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/fastlane:25:in `<main>'`

### Environment

xcode: 14.2.0
falstlane 2.212.2

### PR DESCRIPTION
**Pull request by lukethoene**
Updates Pricing tier selection to correctly handle nil value

### Motivation and Context

- Bug in upload_price_tier.rb resulting in neither pricing nor availability being selected

[Resolves #21236](https://github.com/fastlane/fastlane/issues/21236)

### Description
This change adds safe nav operator to prevent NoMethodErrors when checking first app price, preventing failure to set pricing tier for new app listings.

Tested via creation of several new dummy apps to verify the pricing is set as expected.

### Testing Steps

- Create a New App
- Verify pricing is set as expected

### CODE REVIEW

**Comment by bartpowers** [comment]
👍 Works for me with this change

**Comment by anh1979** [comment]
Please, could anyone let this proceed, then?

**Review by joshdholtz — APPROVED** [review]
Looks good to me! I'll get a new version out tonight

Thanks for the fix! ❤️

**Comment by vincentisambart** [comment]
I'm sorry, but as I wrote (https://github.com/fastlane/fastlane/pull/21213#discussion_r1186918199) in the very similar #21213, I don't think this fix is correct. This will probably end up making any app available in all territories.

**Comment by pedro380085** [comment]
Thank you for releasing this as part of 2.214.0!

**Comment by wesselj2** [comment]
I can confirm what @vincentisambart  is saying. This is setting our apps to be available in all territories every time we submit and we have to manually change it.

**Pull request merged**
