### PR TITLE
bump version for cat fix

### PR DESCRIPTION
**Pull request by ohayon**
- Added new Jira action to post comments to Jira
- Improved error handling when `Fastfile` is not available
- Fix `get_version_number` action's support of target using the `-terse1` flag
- Improved appetize docs
- Auto-follow links when receiving a GitHub release
- Updated dependencies

### CODE REVIEW

**Comment by KrauseFx** [comment]
No changelog in the PR, could you run `fastlane show_changelog` and add the changelog as the PR body?

**Comment by KrauseFx** [comment]
@ohwutup please don't just copy the commit messages, instead we should make the messages readable and user friendly for our customers (e.g. `Jira Action Commits Squashed (#4268)` should be `You can now post comments to JIRA`)

**Comment by KrauseFx** [comment]
@ohwutup updated the description for you 👍

**Comment by ohwutup** [comment]
thanks @KrauseFx !!

**Comment by KrauseFx** [comment]
Happy to help 👍

**Pull request merged**
