### PR TITLE
Use xcodeproj to introspect Xcode projects

### PR DESCRIPTION
**Pull request by endocrimes**
This should be faster, and stops us from needing to maintain a parser for
the command line output of Xcode.

It also allows more tests to not require a full Xcode installation, and should
speed things up a little.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by joshdholtz — APPROVED** [review]
I had no this separate `xcodebuild_list_output_parser` existed. This looks like a good change 💪

**Review by KrauseFx — APPROVED** [review]
So good, thanks @DanToml for this PR 👍 🎉

**Comment by DanToml** [comment]
:tada:

**Pull request merged**
