### PR TITLE
Moved fastlane_folder to fastlane_core, fixed deliver issue

### PR DESCRIPTION
**Pull request by chreno**
Moved fastlane_folder.rb from fastlane to fastlane_core. The original trigger for this refactor was issue #5696.

Fixed deliver detect_values find_folders method, applied a minimal refactor and also added a some tests for the method.

Question: Do you think that create_folder and available_lanes should also be moved to fastlane_core, or should we separate the class and keep these in fastlane?

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @chreno, thanks for the PR. I'm not 100% sure this is the way to go: I wanted `fastlane_core` to have no knowledge about `fastlane`, that's why FastlaneFolder wasn't in core. 
I'll give it some more thoughts.
I definitely would like to avoid fetching the lanes from core, as lanes are really very fastlane specific.

Thanks for the PR already 👍 The build is failing, since this change requires multiple releases

**Comment by KrauseFx** [comment]
Hey @chreno, just wanted to check if you had the time to address my comment 👍

**Comment by chreno** [comment]
Hi @KrauseFx, yeah, thanks. There are two options in my mind:

1. Split fastlane_folder into 2 separate classes. One for the path operations and one other for lane operations (available_lanes method). Path would go into fastlane core, the other into fastlane. This is a really simple solution, but fastlane core will know about the fastlane folder.
2. Introduce a new helper in fastlane core which is able to return the base folder. When you are running deliver etc standalone, it would just return ".", when you are running from fastlane we would "override" the method and it would return fastlane_folder.path.

What do you think?

**Comment by mfurtak** [comment]
I personally like option 1. That would be a good separation of concerns. 👍

**Comment by chreno** [comment]
Hey @mfurtak, @KrauseFx, I moved the available_lanes method from Fastlane_folder to cli_tools_distributor. This is the only place currently where we are using it, so I thought it's the simplest to include it in that class for now. If we want to use it somewhere else we should extract it to a separate helper in fastlane.
The remaining methods in Fastlane_folder are about handling the fastlane folder and retrieving Fastfile location.

What do you think?

**Comment by chreno** [comment]
Hi @mfurtak, @KrauseFx, I just wanted to double check.. what do you think about this solution? Thanks!

**Comment by mfurtak** [comment]
This build is failing because the changes affect both _fastlane_core_ and other projects that depend on it. In order to move this forward, we will need to separate this PR into two, so that we can ship the _fastlane_core_ part first.

**Comment by chreno** [comment]
@mfurtak thanks! I'm happy to do the 2 separate PRs. Before that could you please confirm that the solution I used is fine? Thanks!

**Comment by mfurtak** [comment]
Hi @chreno - thanks for your patience! Yes, I think the approach is good 👍  Please ping me on the new PR(s) and I'll take a look.

**Comment by chreno** [comment]
Thanks @mfurtak! I opened a new PR only containing the changes in fastlane_core: #6787

**Comment by mfurtak** [comment]
@chreno Is this where we'll carry over the rest of the `FastlaneFolder` changes?

**Comment by chreno** [comment]
@mfurtak yes! Thanks!

**Comment by milch** [comment]
We've released an update to fastlane_core in the meantime, so finishing this PR should now be possible 👍

**Comment by milch** [comment]
So, what needs to happen before we can merge this PR: 

* All `deliver` changes go into their own PR
* All `fastlane_core` changes should already have been done in #6787, so they should be removed
* Changes to `fastlane` remain here

**Comment by chreno** [comment]
@milch Thanks! I created a separate PR for deliver changes:
https://github.com/fastlane/fastlane/pull/7129

**Comment by chreno** [comment]
@milch deliver changes merged in #7129.
Still have a change here in fastlane_core. I think it was accidentally left out from #6787. Do you think we can merge it here? Or should we create a separate PR for it?
Thanks!

**Comment by milch** [comment]
@chreno Please create a separate PR for this - the PRs have to be separated by tools, even if they only contain small changes to each one.

**Comment by chreno** [comment]
@milch Sure, no problem. Created a PR for it: #7220

**Comment by milch** [comment]
@chreno Thanks for your second PR and your patience! 🚀 

I merged the other PR, so now all that's missing from you is rebasing from master so that the tests will work again.

**Comment by chreno** [comment]
@milch Cool thanks! Finished with rebasing :)

**Review by milch — APPROVED** [review]

**Comment by milch** [comment]
Thank you so much for your contribution! 🚀

**Pull request merged**
