### PR TITLE
Include contents of BCSymbolMaps directory in dSYM.zip file.

### PR DESCRIPTION
**Pull request by pdrtrifork**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
DWARF files used for symbolicating Apple crash reports often times hide the actual symbols, replacing them with e.g. `__hiddden#34_`. In order to do a full symbolication .bcsymbolmap files are needed to translate these hidden symbols in to the original.

Related issues: https://github.com/fastlane/fastlane/issues/6574, https://github.com/fastlane/fastlane/issues/10902

### Description
Added the contents of BCSymbolMaps to the .dSYM.zip file.

### CODE REVIEW

**Comment by pdrtrifork** [comment]
I signed it!

**Comment by KrauseFx** [comment]
@googlebot It's signed!

**Comment by rafaelnobrepd** [comment]
Looking forward for a release including this behavior ! 👍

**Comment by KrauseFx** [comment]
Thanks for the PR @pdrtrifork, seems like the @googlebot isn't happy, can you confirm you signed the Google CLA?

**Comment by pdrtrifork** [comment]
You are welcome.

The email address used in the commits was not in the Google Group. It is now. Let me know if there is still an issue.

**Comment by KrauseFx** [comment]
I signed it!

Let's try to trigger the Google bot again 👍

**Comment by pdrtrifork** [comment]
I'm sorry about this, but this time I believe I got the email address right :-) Could you please wake up the bot again?

**Comment by pdrtrifork** [comment]
I have made an important change to the pull request, so as not to mess with the directory structure of the generated .dSYM.zip. The .bcsymbolmap files will be added to the root of the .dSYM.zip.

**Review by taquitos — APPROVED** [review]
🎈:goat:
Thank you, this is great!

**Pull request merged**
