### PR TITLE
Add Automatic Release Date for Tunes Submission

### PR DESCRIPTION
**Pull request by andyvanosdale**
Implements https://github.com/fastlane/fastlane/issues/7150

Exposes the auto_release_date field in AppVersion. The field takes in
a millisecond value. Setting this will supercede the release_on_approval
field, so this field must be nil for release_on_approval to be used.

### CODE REVIEW

**Comment by milch** [comment]
Hi @enozero, thanks for your contribution and sorry for the late reply! 

It seems like there is no user facing change to use this feature, so someone will probably have to pick this up later and implement it then if they so desire. Apparently there are some conditions on using this feature that you mention in the commit message, but should also be included in the code, e.g.:

```
Setting this will supercede the release_on_approval field, so this field must be nil for release_on_approval to be used.
```

The tests should also reflect this requirement.

**Comment by KrauseFx** [comment]
Hey @enozero, have you had the time to look into @milch's comment?

**Comment by enozero** [comment]
I have but haven't been able to update the change yet and will do so soon!

**Comment by enozero** [comment]
@KrauseFx @milch I've updated the PR with the requested changes. Please take another look and let me know if you have any questions. Thanks!

**Review by mpirri — APPROVED** [review]
Look good, thanks for the contribution!

**Pull request merged**
