### PR TITLE
Added sound parameter to OS X notification action

### PR DESCRIPTION
**Pull request by amarcadet**
I thought it would be nice to play a sound with the OS X notification action.
Since I am new to ruby it might not be the smartest way to do it or I might have done something wrong, feel free to tell me if I must update anything.

I didn't found any specs for this action, so there is no tests with my PR.

Hope you like it :smiley:

### CODE REVIEW

**Comment by KrauseFx** [comment]
This looks great, thanks for your contribution. Could you squash the commits to one commit? :+1:

**Comment by KrauseFx** [comment]
Hey @amarcadet, just wanted to check if you had the time to update this PR :+1:

**Comment by ohwutup** [comment]
hey @amarcadet, i just opened this PR with the commits squashed. going to close this one and we can restart discussion over here: https://github.com/fastlane/fastlane/pull/1408 if necessary. thanks again for this!!! :rocket:

**Comment by amarcadet** [comment]
You're right, so sorry for the delay, I was really busy and forgot about that...
Thank you! :+1:

**Comment by ohwutup** [comment]
no worries at all :rocket:

**Pull request closed without merging**
