### PR TITLE
Added option to specify scheme in update_info_plist

### PR DESCRIPTION
**Pull request by dtorres**
The action can now find the info plist path based on the scheme instead of being forced to supply the path
- [x] Add Tests

Issue #4698

### CODE REVIEW

**Comment by dtorres** [comment]
Tests added but for some reason it fails at the "Danger" stage. 
Any idea why?

**Comment by KrauseFx** [comment]
Really sorry about this issue, that's an issue with danger. Could you rebase from master? That should fix the problem

**Comment by dtorres** [comment]
@KrauseFx 🤘🤘

**Comment by ohwutup** [comment]
Hey @dtorres! Thanks for this PR, it looks great. Would you mind just squashing up the commits and we will 🚀 !

**Comment by dtorres** [comment]
@ohwutup Done!

**Comment by dtorres** [comment]
It failed (yet again) because of Dangerm but all is passing.

**Comment by KrauseFx** [comment]
Sorry we can't merge when the build is not passing. Could you rebase from master, where we updated the dependency to danger? I hope this issue is fixed then, sorry for the trouble.

**Comment by dtorres** [comment]
@KrauseFx Done

**Pull request merged**
