### PR TITLE
[action][spm] deprecate `build_path` option in favor of `scratch_path`, as recommended by Swift CLI

### PR DESCRIPTION
**Pull request by Tavernari**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The swift cli has been warning about the build-path deprecation.

### Description

This PR adds the option to use scratch_path instead of build_path, but it kept the build_path available since the swift cli is still accepting it as a warning.
I tested it, just changing the option.

### Testing Steps
Using this PR as the Fastlane source.

1. Create an SPM project 
2. Initialise fastlane 
3. Add to their Fastfile the spm action with scratch_path instead of build_path
4. Change scratch_path to build_path and it should work as well.

### CODE REVIEW

**Comment by Tavernari** [comment]
```
Failed examples:

rspec ./fastlane/spec/actions_specs/update_fastlane_spec.rb:13 # Fastlane Fastlane::FastFile update_fastlane when no update needed
rspec ./fastlane/spec/actions_specs/update_fastlane_spec.rb:28 # Fastlane Fastlane::FastFile update_fastlane when update with RubyGems
rspec ./fastlane/spec/actions_specs/update_fastlane_spec.rb:68 # Fastlane Fastlane::FastFile update_fastlane when update with Homebrew
```

I am getting these errors when running `bundle exec rspec`.

**Comment by Tavernari** [comment]
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/fastlane/fastlane/pull/20814/checks?check_run_id=9248633440) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

I signed it.

**Review by joshdholtz — DISMISSED** [review]
Didn't know about this`scratch-path` change 😅 Gave one suggestion and then we can get this merged!

**Comment by Tavernari** [comment]
> Didn't know about this`scratch-path` change 😅 Gave one suggestion and then we can get this merged!

What kind of suggestion?

**Review by lacostej — APPROVED** [review]
I think @joshdholtz's requested changes have been accepted. So we should be good to merge this.

Thanks for the contribution!

**Review by rogerluan — APPROVED** [review]
💯 Neat!

Thank you for your contribution @Tavernari 🤗

**Comment by Tavernari** [comment]
Thanks!! 😊

**Pull request merged**
