### PR TITLE
Provide a test for badge action ImageMagick verification

### PR DESCRIPTION
**Pull request by mfurtak**
Follow-up to #6568

/cc @AliSoftware

### CODE REVIEW

**Comment by AliSoftware** [comment]
Cool! This will also allow to close #6585 I opened to be sure not to forget :wink:

**Review by asfalcone — APPROVED** [review]

**Review by AliSoftware — COMMENTED** [review]
Shouldn't we also write a passing test? (if ImageMagick is present, ensure we don't fail)

**Comment by mfurtak** [comment]
Yeah, that would be good, I agree. However, it's a bit trickier to do because once the action continues on past the ImageMagick check, it immediately wants to require and use the Badge gem.

In order to turn the success case into a test that can actually run to completion, I think I would have to mock out almost 100% of the logic. At that point, I'm not sure that I'm really testing very much.

One option is to remove the private method restriction on `check_imagemagick!` and test it more directly. What do folks think about that?

**Comment by AliSoftware** [comment]
Ah, I see your point.

I think it would be better and more logical to directly test `check_imagemagick!` instead of testing `badge`.

We can still keep it private in the implementation, and use `BadgeAction.send(:check_imagemagick!)` from the specs to workaround the private accessibility 😉

**Review by AliSoftware — CHANGES_REQUESTED** [review]
Test `BadgeAction.send(:check_imagemagick!)` directly instead, to be able to provide both success & failure tests

**Comment by mfurtak** [comment]
I'm going to keep the top-level action test, as I think it's good that every action has at least one test that tries to use it as part of a Fastfile evaluation. 👍

**Comment by KrauseFx** [comment]
👍

**Pull request merged**
