### PR TITLE
[screengrab] updated the falcon dependency version

### LINKED ISSUE #15074: [screengrab] - unable to take screenshot
While running the screengrab example I see exception in the third party library `falcon`. This issue is similar to the issue reported on the [falcon repo](https://github.com/jraska/Falcon/issues/38).

```
 1) testTakeMoreScreenshots(tools.fastlane.localetester.FalconScreenshots)
[10:01:00]: ▸ com.jraska.falcon.Falcon$UnableToTakeScreenshotException: Unable to take screenshot to bitmap of activity tools.fastlane.localetester.MainActivity
[10:01:00]: ▸ at com.jraska.falcon.Falcon.takeScreenshotBitmap(Falcon.java:94)
[10:01:00]: ▸ at tools.fastlane.screengrab.FalconScreenshotStrategy.takeScreenshot(FalconScreenshotStrategy.java:24)
[10:01:00]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:94)
[10:01:00]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:76)
[10:01:00]: ▸ at tools.fastlane.screengrab.Screengrab.screenshot(Screengrab.java:60)
[10:01:00]: ▸ at tools.fastlane.localetester.FalconScreenshots.testTakeMoreScreenshots(FalconScreenshots.java:53)
[10:01:00]: ▸ at java.lang.reflect.Method.invoke(Native Method)
[10:01:00]: ▸ at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[10:01:00]: ▸ at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[10:01:00]: ▸ at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[10:01:00]: ▸ at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[10:01:00]: ▸ at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
[10:01:00]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[10:01:00]: ▸ at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[10:01:00]: ▸ at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[10:01:00]: ▸ at tools.fastlane.screengrab.locale.LocaleTestRule$1.evaluate(LocaleTestRule.java:32)
[10:01:00]: ▸ at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[10:01:00]: ▸ at org.junit.runners.Suite.runChild(Suite.java:128)
[10:01:00]: ▸ at org.junit.runners.Suite.runChild(Suite.java:27)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[10:01:00]: ▸ at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[10:01:00]: ▸ at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[10:01:00]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[10:01:00]: ▸ at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[10:01:00]: ▸ at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
[10:01:00]: ▸ at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
[10:01:00]: ▸ at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
[10:01:00]: ▸ Caused by: java.lang.NoSuchFieldException: Field mWindowTop not found for class class android.view.View$AttachInfo
[10:01:00]: ▸ at com.jraska.falcon.Falcon.findField(Falcon.java:347)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.getFieldValueUnchecked(Falcon.java:329)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.getFieldValue(Falcon.java:321)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.viewRootData(Falcon.java:239)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.getRootViews(Falcon.java:210)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.takeBitmapUnchecked(Falcon.java:103)
[10:01:00]: ▸ at com.jraska.falcon.Falcon.takeScreenshotBitmap(Falcon.java:88)
[10:01:00]: ▸ ... 36 more
```

### PR DESCRIPTION
**Pull request by RishabhTayal**
fixes: #15074

### CODE REVIEW

**Comment by colintheshots** [comment]
I think we can now close this in favor of https://github.com/fastlane/fastlane/pull/15217

I'm assuming that PR gets merged, of course.

**Review by joshdholtz — APPROVED** [review]
Tested this out against the sample project that uses both methods and works good! 👍

**Comment by joshdholtz** [comment]
Waaaiittt... How did Github close this?! I force pushed a rebase and it closed it 😱

**Comment by joshdholtz** [comment]
@RishabhTayal Do you want to open a new PR for this or do you want me to? I'm super confused on what happened here

**Comment by RishabhTayal** [comment]
Let me try.

**Comment by joshdholtz** [comment]
Oh wait... it looks like the AndroidX PR had the same version in it so no diff 😛 So this change is already in master

🙄 at me

**Comment by RishabhTayal** [comment]
no problem.

**Pull request closed without merging**
