### PR TITLE
pipe force parameter to sigh

### PR DESCRIPTION
**Pull request by CBeloch**
force parameter was unused

### CODE REVIEW

**Comment by KrauseFx** [comment]
I think at this point we always want to force generate a provisioning profile, look at the method name. What do you think?

**Comment by CBeloch** [comment]
As I always run the match step on builds it will always generate a new one and that creates a lot of them on my machine. And as I've seen, the match `force` parameter isn't used anywhere. Maybe set it to true by default (it's false atm), but pipe the option down to sigh.

**Comment by KrauseFx** [comment]
Could you give me the parameters you use and how you expect things to work differently?

**Comment by CBeloch** [comment]
There are no special parameters
`match(
	    type: "appstore",
	    force: false
)`
What I expect is, that match will generate new distribution certificate if none available or expired (works), and only generate a new provisioning when necessary (which it doesn't at the moment). So i ended up with 
match_provision
They are all for the same app

**Comment by KrauseFx** [comment]
So the information you hide, is that a timestamp (number) or something else?

**Comment by CBeloch** [comment]
It's the App-ID

**Comment by asfalcone** [comment]
I'm going to close this PR since I don't think that passing anything other than `force: true` from sigh to match is the right thing here. If you can track down a bug we'd be happy to discuss it in a github issue. Thanks :+1:

**Comment by CBeloch** [comment]
Well then you should not add a force parameter to sigh if it is not used!

**Pull request closed without merging**
