### PR TITLE
Fix to git command

### PR DESCRIPTION
**Pull request by GoodMirek**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [NA] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [NA] Run `bundle exec rubocop -a` to ensure the code style is valid
- [X] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Fix to git command

### CODE REVIEW

**Comment by KrauseFx** [comment]
Could you explain why this should be changed? Thanks

**Comment by GoodMirek** [comment]
If command is used in form:
`git clone <YOUR_GITHUB_USER> git@github.com:<YOUR_GITHUB_USER>/fastlane.git`
then git utility tries to interpret the first <YOUR_GITHUB_USER> string as a repo reference and fails.
Output from machine:
```
DN:test admin$ uname -a
Darwin DN 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
DN:test admin$ git --version
git version 2.7.4 (Apple Git-66)
DN:test admin$ git clone GoodMirek git@github.com:GoodMirek/fastlane.git
fatal: repository 'GoodMirek' does not exist
```

While command as present in the pull request passes.

**Comment by KrauseFx** [comment]
I'm not sure I'm following, I'll close this PR for now, as everyone can easily change the clone command 👍

**Comment by GoodMirek** [comment]
I do not understand the chosen resolution. The command present in the doc
is clearly wrong.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Argh, sorry, I misunderstood, PR is merged now. Sorry for the confusion.

**Comment by GoodMirek** [comment]
Thanks for merging this.

**Pull request merged**
