### PR TITLE
README Fixes

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Fixing links in all fastlane READMES

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
@asfalcone hey there, not sure if we are duplicating efforts :smile: fyi i am going through readmes too

**Comment by ReadmeCritic** [comment]
@mfurtak hey there you too

**Comment by ReadmeCritic** [comment]
@mfurtak @asfalcone hey looks like you are making more changes.. will let you go through everything and I will check for dead links 

cc @KrauseFx 
cheers

**Comment by mfurtak** [comment]
Hey @ReadmeCritic - thanks for being so on top of this! :100: 

We're currently in a period of high maintenance for `fastlane` as we migrate code, issues and update documentation. We're tweeting from [@FastlaneTools](https://twitter.com/FastlaneTools) as we make progress, so please hold off for now, and keep an eye out there for progress updates. Cheers! :+1:

**Comment by ReadmeCritic** [comment]
Would be great if you can leave a comment here if interested in me checking links 

Feel free to close if not necessary

Cheers :beers:

**Comment by mfurtak** [comment]
@ReadmeCritic We're done with our first pass. If you want to work your magic it would be most welcome :smile:

**Comment by ReadmeCritic** [comment]
on it

**Comment by ReadmeCritic** [comment]
wip

- [ ] cert	
- [ ] countdown	 
- [ ] credentials_manager 
- [ ] deliver	 
- [ ] fastlane	 
- [ ] fastlane_core	 
- [ ] frameit	 
- [ ] gym	 
- [ ] match	 
- [ ] pem	 
- [ ] pilot	 
- [ ] produce	 
- [ ] scan	 
- [ ] screengrab 
- [ ] sigh	 
- [ ] snapshot	 
- [ ] spaceship	 
- [ ] supply 
- [ ] watchbuild

**Comment by ReadmeCritic** [comment]
conflicts!! :sob:  will try again

**Pull request closed without merging**
