### PR TITLE
fix IAP modify

### PR DESCRIPTION
**Pull request by hjanuschka**
this PR trys to fix the issues that happen on modification of iap's.

since this commit: https://github.com/fastlane/fastlane/pull/7834/commits/1c1900a8c8d06ca101325c2a148ea0af1273d705 (i was moving code from setup to factory) - it seems that few parts of modify are broken.

users where unable to set `versions`/`pricing_intervals`

this PR trys to address this (and ads regression tests for it):

  * [x] IAP-Detail
  * [x] IAP-Family

following snippet fails on `master`  and works with this PR:

```ruby
require "spaceship"

Spaceship::Tunes.login("helmut@januschka.com")
app = Spaceship::Application.find("hjanuschka.sticker-test")
purchase = app.in_app_purchases.find("x.a.s.b.b.c.d.x.y.f").edit


purchase.pricing_intervals = [
  {
    country: "WW",
    begin_date: nil,
    end_date: nil,
    tier: 3
  }
]

purchase.versions = {
      'en-US': {
        name: "Edit It",
        description: "Description has at least 10 characters"
      },
      'de-DE': {
        name: "test name german1",
        description: "German has at least 10 characters"
      },
      'da': {
        name: "test name danish",
        description: "German has at least 10 characters"
      }
    } 


purchase.review_notes = "new nots 10 characters"
purchase.review_screenshot = "/Users/hja/Desktop/review.jpg"
purchase.save!
```

### CODE REVIEW

**Comment by alaincaltieri** [comment]
Hi @hjanuschka 

I've been playing a bit with the new IAP feature (great work btw 👏).

I faced some issues, maybe they can be helpful in this context, so I'm describing them here. Let me know if you prefer me to open specific issues for any one of them.

I've been using the version available as of today in your repo `https://github.com/hjanuschka/fastlane.git`, branch `fix_iap_modify`, which you're merging here.


I'm using this invocation, which raises no error:
```
@app.in_app_purchases.create!(
          type: Spaceship::Tunes::IAPType::RECURRING,
          versions: {
              'en-US' => {
                  name: title,
                  description: description
              },
          },
          reference_name: reference_name,
          product_id: identifier,
          cleared_for_sale: true,
          # review_notes: "Some Review Notes here bla bla bla",
          review_screenshot: screenshot,
          pricing_intervals: [
              {
                  country: 'WW',
                  begin_date: nil,
                  end_date: nil,
                  tier: price_tier
              }
          ],
          subscription_free_trial: free_period,
          subscription_duration: duration,

          family_id: family.family_id
      )
```
Still, the results on iTunes connect are not exactly the ones I expected:
- Cleared for Sale in Subscriptions is always false, regardless of what I set it to
- There's no set price in the IAP I obtain with the call above. Also, trying with this
```
@app.in_app_purchases.all.each {| p |
        if p.product_id == identifier
          ed = p.edit
          ed.subscription_price_target = {currency: 'USD', tier: price_tier}
          ed.save!
        end
      }
```

Makes the library crash on
```
/Users/alaincaltieri/.rvm/gems/ruby-2.1.1/bundler/gems/fastlane-cf655c30431f/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response': ITC.response.error.OPERATION_FAILED (Spaceship::TunesClient::ITunesConnectError)
	from /Users/alaincaltieri/.rvm/gems/ruby-2.1.1/bundler/gems/fastlane-cf655c30431f/spaceship/lib/spaceship/tunes/tunes_client.rb:1034:in `block in update_iap!'
	from /Users/alaincaltieri/.rvm/gems/ruby-2.1.1/bundler/gems/fastlane-cf655c30431f/spaceship/lib/spaceship/tunes/tunes_client.rb:1366:in `with_tunes_retry'
	from /Users/alaincaltieri/.rvm/gems/ruby-2.1.1/bundler/gems/fastlane-cf655c30431f/spaceship/lib/spaceship/tunes/tunes_client.rb:1028:in `update_iap!'
	from /Users/alaincaltieri/.rvm/gems/ruby-2.1.1/bundler/gems/fastlane-cf655c30431f/spaceship/lib/spaceship/tunes/iap_detail.rb:213:in `save!'
```

Same `OPERATION_FAILED` error occurs also when modifying non-renewable iaps (like a consumable one).

Let me know if you need any further detail and thank you a lot! 🙂

**Comment by hjanuschka** [comment]
@alaincaltieri many thx for the feedback i ll have a look at it, and push directly to this branch if i find fixes.

**Comment by hjanuschka** [comment]
@alaincaltieri i looked at it and the "subscriptions" are beasts!


you have to set the pricing interval in a differen format.
e.g:


```ruby
app.in_app_purchases.create!(
          type: Spaceship::Tunes::IAPType::RECURRING,
          versions: {
              'en-US' => {
                  name: "title1",
                  description: "descr at least 10 characters"
              },
          },
          reference_name: "new REF name1",
          product_id: "some.recurring1",
          cleared_for_sale: true,
          # review_notes: "Some Review Notes here bla bla bla",
          review_screenshot: "/Users/hja/Desktop/review.jpg",
          pricing_intervals: [
            {
                  country: "AO",
                  begin_date: nil,
                  end_date: nil,
                  tier: 1,
                  grandfathered: { value: "FUTURE_NONE" }
                }
          ],
          subscription_free_trial: '1w',
          subscription_duration: '1m',
          family_id: "20373395"
)
```

once the pricing interval is correct - the clear for sale also works :)


the second problem with editing.


this works:

> hint: you can use `find`  instead of looping through `all` 👍 

```ruby
purch = app.in_app_purchases.find("some.recurring1")
ed = purch.edit
ed.subscription_price_target = {currency: 'USD', tier: 3}
ed.review_screenshot = "/Users/hja/Desktop/review.jpg"
ed.review_notes = "asdas das dasdas "
ed.save!
```

it seems to fail if there is no review_screenshot and no review_note.

**Comment by mfurtak** [comment]
@hjanuschka Who do you think is the right person to review and get this in? @KrauseFx? @snatchev ?

**Comment by hjanuschka** [comment]
@mfurtak i think the best bet is on @snatchev - i don't think this brings in some troubles (only touches iap related files), as the current in-production code is defacto broken, this PR (confirmed  working by @alaincaltieri ) fixes it.
so i hope this is getting merged soon.

**Comment by Prussich** [comment]
Hi @hjanuschka,

I tried this code for subscriptions product:

`purch = app.in_app_purchases.find("some.recurring1")
ed = purch.edit
ed.subscription_price_target = {currency: 'USD', tier: 3}
ed.review_screenshot = "/Users/hja/Desktop/review.jpg"
ed.review_notes = "asdas das dasdas "
ed.save!`

It works fine! 
But when I try code below (with the localization changes), there is no localization changes on the product.

`purch = app.in_app_purchases.find("some.recurring1")
ed = purch.edit
ed.versions = 
      [{
        'en-US' => {
            name: "Test test",
            description: "Test test test"
         }
      }]
ed.subscription_price_target = {currency: 'USD', tier: 3}
ed.review_screenshot = "/Users/hja/Desktop/review.jpg"
ed.review_notes = "asdas das dasdas "
ed.save!`

What is wrong and how can I fix it?

**Comment by hjanuschka** [comment]
@Prussich `versions` should be a hash, not a array so this should work:

```ruby
purch = app.in_app_purchases.find("some.recurring1")
ed = purch.edit
ed.versions = 
      {
        'en-US' => {
            name: "Test test",
            description: "Test test test"
         } 
     }
ed.subscription_price_target = {currency: 'USD', tier: 3}
ed.review_screenshot = "/Users/hja/Desktop/review.jpg"
ed.review_notes = "asdas das dasdas "
ed.save!
```

**Comment by Prussich** [comment]
I changed the code as you recommended. But it's not working again :( Everything is changing, except for localizations.

My script:

```ruby
#!/usr/bin/env ruby
#$verbose=true

require "spaceship"

Spaceship::Tunes.login('xxx', 'xxx')

app = Spaceship::Application.find("com.xxx")


purch = app.in_app_purchases.find("com.xxx.xxx")
ed = purch.edit
ed.subscription_price_target = {currency: 'USD', tier: 9}
ed.versions = 
      {
        'en-AU' => {
            name: "Test test",
            description: "Test test test"
         },
         'en-US' => {
            name: "Test test",
            description: "Test test test"
         } 
     }
ed.review_screenshot = "/Users/xxx/xxx.png"
ed.review_notes = "asdas das dasdas "
ed.subscription_duration =  '1m'
ed.save!
```

bash-3.2$ fastlane --version
fastlane installation at path:
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/bin/fastlane
-----------------------------
fastlane 2.18.3

from git clone -b fix_iap_modify --single-branch https://git@github.com/hjanuschka/fastlane.git

**Comment by hjanuschka** [comment]
@Prussich in fact it looks like the apple-api got a bit stricter on iap modify - since the last commit in this PR.

can you pull it again https://github.com/fastlane/fastlane/pull/8367/commits/f5dac9e5091b154a1a1f727d4538a7159ef68dbb should adress it.

i ran the above code sample and it worked after the recent commit.

**Comment by Prussich** [comment]
@hjanuschka,  thank you very much, it's works now!

**Comment by jianghaoyuan2007** [comment]
Hi, @hjanuschka I met a problem. I don't find the answer of the problem. Here is my script.

Spaceship::Tunes.login(apple_id, password)

app = Spaceship::Tunes::Application.find(bundle_id)

purchase = app.in_app_purchases.find(product_id)

detailed = purchase.edit

detailed.review_screenshot = "/Users/Haoyuan/Desktop/review_screenshot.PNG"

detailed.review_notes = "new nots 10 characters",

detailed.save!

**Comment by hjanuschka** [comment]
@jianghaoyuan2007 are you using this PR as a code base - or are on a `master`?

**Comment by jianghaoyuan2007** [comment]
@hjanuschka I am using fastlane 2.24.0 as code base. fastlane 2.24.0 is installed and updated using `sudo gem update fastlane`. And could you tell what PR is?

**Comment by hjanuschka** [comment]
these PR here - solves a whole bunch of problems with iap's.
so to get it working you'd need to use the PR branch -> inside my fork: https://github.com/hjanuschka/fastlane/tree/fix_iap_modify

or you'd wait until the PR is merged.

**Comment by spazworm** [comment]
@hjanuschka I started using this branch in a script I'm working on which modifies IAPs. Couldn't get it working so I diffed the request with the same edit request in Itunes connect and worked out that the contentHosting being missing from the edit request was the cause of my issues. I've forked and fixed it for myself here
https://github.com/spazworm/fastlane/commit/81967e734a9c406374d05d06dfbb0a3b007d901a
but I'm sure there must be a better way to get it done. Thanks for all your hard work.

**Comment by hjanuschka** [comment]
@spazworm many thx, commit looks good, i added it to this branch, could you please:

  * sign the CLA stuff the bot is mentioning.
  * give this PR a another testing round?

**Comment by spazworm** [comment]
@hjanuschka submitted the CLA, I'll be working with IAP creation and modification over the next few days so that should give it a decent run through.

**Comment by hjanuschka** [comment]
@spazworm sorry to bother you again, can you reply something to this PR - this should make the @googlebot  happy (i hope)

**Comment by spazworm** [comment]
lol no worries @hjanuschka. I am okay with commits being contributed @googlebot.

**Comment by azgul** [comment]
Hey @hjanuschka I wanted to modify some IAPs and quickly realized that I needed to be on your branch to get it working. But with the following code:
```
      iap_edit = iap.edit
      iap_edit.versions = {
          'en-US': {
              name: "Whatever",
              description: "A description"
          }
      }
```

I get: 
```
undefined method `versions=' for #<Spaceship::Tunes::IAPDetail:0x007fa686a797f0> (NoMethodError)
```
Which I also get with `fastlane 2.25.0`

**Comment by hjanuschka** [comment]
@azgul can you share a couple of more lines, and also are you sure you are on the branch of this PR (because i am quiet confident that the branch here has the `version=`  on `IAPDetail` - and it was missing before the PR see here: https://github.com/fastlane/fastlane/pull/8367/files#diff-0ad09501b52f13ed83e0709d8a5b1df3R74)?

**Comment by azgul** [comment]
@hjanuschka Here is my entire script without the constants: https://gist.github.com/azgul/c73ff76798e09d49413c708fdba74d09

And my folder structure is as follows:
script.rb
fastlane/ (with your branch checked out)

am I loading the spaceship library incorrectly?

**Comment by hjanuschka** [comment]
@azgul script looks 

one note, i think you have to set review_notes and screenshot on every edit:

```
iap.review_screenshot = "/Users/xxx/xxx.png"
iap.review_notes = "asdas das dasdas "
```

about the usage of the fork i am unsure about require_relative.
could you use a Gemfile?


Gemfile:
```ruby
source "https://rubygems.org"
gem 'fastlane', :git => 'https://github.com/hjanuschka/fastlane.git', :branch => 'fix_iap_modify'
```


running: `bundle install` and later on your script with `bundle exec ruby your_script.rb` -this way it should definitly use the PR's branch.

**Comment by azgul** [comment]
@hjanuschka I'm still having issues after trying to save: https://gist.github.com/azgul/5057e8669916b329e41e557283de5077

terminates with the following stacktrace:
```
/Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response': ITC.response.error.OPERATION_FAILED (Spaceship::TunesClient::ITunesConnectError)
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/tunes_client.rb:1035:in `block in update_iap!'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/tunes_client.rb:1367:in `with_tunes_retry'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/tunes_client.rb:1029:in `update_iap!'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/iap_detail.rb:213:in `save!'
	from iap.rb:41:in `block in <main>'
	from iap.rb:19:in `each'
	from iap.rb:19:in `<main>'
```

as a sidenote it seems strange that we have to use what seems to be iPhone 4 resolution because it fails with everything else that I've tried. It even fails with iPhone 7 Plus resolution (1242x2208). I downloaded the review screenshot that was already there and it refuses to upload that and fails with:

```
/Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/du/du_client.rb:127:in `parse_upload_response': [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it. (Spaceship::Client::UnexpectedResponse)
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/du/du_client.rb:83:in `upload_file'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/du/du_client.rb:22:in `upload_purchase_review_screenshot'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/tunes_client.rb:598:in `upload_purchase_review_screenshot'
	from /Users/martin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/fastlane-636fccaeea2b/spaceship/lib/spaceship/tunes/iap_detail.rb:196:in `save!'
	from iap.rb:41:in `block in <main>'
	from iap.rb:19:in `each'
	from iap.rb:19:in `<main>'
```

I attempted resize to all the iPhone resolutions listed on http://iosres.com/ but it fails with the same error on all of them. Only works with 640x960 which you mentioned here: https://github.com/fastlane/fastlane/issues/8348#issuecomment-282074335

**Comment by hjanuschka** [comment]
@azgul i think its because your description is below 10 characters 👍  - can you try the exakt same input on itc web interface.


about screenshots, i am going to find some time to digg into the different screenshot formats.

**Comment by azgul** [comment]
@hjanuschka the iap description? It is 12 characters. And it works fine on itc

**Comment by hjanuschka** [comment]
@azgul sorry - i tried it now and found the issue, itc locales are a mess. 👍 

following snippet works (extracted from your script)

```ruby
require "spaceship"
new_iap_name = "Single Copy 01/02/19"
Spaceship::Tunes.login("helmut@januschka.com")
app = Spaceship::Application.find("hjanuschka.sticker-test")
iap_edit = app.in_app_purchases.find("x.a.s.b.b.c.d.x.y.f").edit

iap_edit.review_notes = "Fix locale. Previous version mistakenly only had en-US"
iap_edit.review_screenshot = "/Users/hjanuschka/Desktop/review.jpg"
iap_edit.versions = {
     'en-GB': {
         name: new_iap_name,
         description: "Single issue"
     }
}

iap_edit.save!
```

the issue is that itc requires to use `en-GB`  instead of `en-UK`:
bildschirmfoto 2017-04-07 um 09 41 01

**Comment by azgul** [comment]
@hjanuschka thank you. We came to the same conclusion. I inspected the network response from itc and found that I was using the wrong locale. Thank you again for your assistance

**Comment by hjanuschka** [comment]
@azgul  you are welcome, thx for helping out by providing details - and thx for using IAP via fastlane 🍺

**Comment by hjanuschka** [comment]
@azgul about the screenshots, could you share some in the various sizes? so i can dig into it.

**Comment by azgul** [comment]
http://i.imgur.com/2ehmjcj.jpg here is the one that was already uploaded through Application Loader (1242x2208). The other phone resolutions listed on http://iosres.com/ I scaled down from this

**Comment by alaincaltieri** [comment]
@hjanuschka Any news about this? It was looking promising

**Comment by hjanuschka** [comment]
it is working, this PR is still mergeable - it only lacks the multiple screenshot size.
i havent got time for that, i would love to finish this PR, as it fixes current broken iap mgmt on `master` - and do the multiple screenshots support in a seperate PR.


for those of you using, this branch, i merged the current master


@KrauseFx  can we merge this?

**Review by KrauseFx — APPROVED** [review]
I couldn't test this on a production system, but you confirmed that you did. The code looks good, and there are tests covering it. Look 👍 to me

**Comment by hjanuschka** [comment]
many thx!

**Comment by Prussich** [comment]
Hi, hjanuschka 

I try to modify approved in-app item and I got error:

`
/Users/Test/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response': ITC.response.error.OPERATION_FAILED (Spaceship::TunesClient::ITunesConnectError)
	from /Users/Test/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/tunes/tunes_client.rb:964:in `block in update_iap!'
	from /Users/Test/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1296:in `with_tunes_retry'
	from /Users/Test/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/tunes/tunes_client.rb:958:in `update_iap!'
	from /Users/Test/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/tunes/iap_detail.rb:211:in `save!'
	from ./modify_products_balance_.rb:24:in `<main>'
`

My code:
`
#!/usr/bin/env ruby

require "spaceship"

    Spaceship::Tunes.login('xxx', 'xxx')

    app = Spaceship::Application.find("com.xxx")

    $i = 0

    purch = app.in_app_purchases.find("com.xxx.xxx1")

    ed = purch.edit
    
    ed.versions = 
    {
        'en-US'=>{
                  name: "Test Test Test",
                  description: "Test Test Test"
        }
    }
    ed.review_screenshot = "/Users/Test/Documents/develop/projects/screenshot.png"
    ed.review_notes = "Test Test Test"
    ed.save!
`

git clone https://github.com/hjanuschka/fastlane.git
gem build fastlane.gemspec
gem install fastlane-2.37.0.gem 


If I try to modify the new one in-app item with this script - it works fine.
How can I modify approved in-app items?

**Pull request merged**
