### PR TITLE
Use Android environment to find adb (don't just rely on it being in PATH)

### PR DESCRIPTION
**Pull request by adamcohenrose**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

screengrab currently builds up (and verifies) an android environment and then ignores it when calling adb -- assuming that adb is on the path (and failing when it isn't!).

This patch uses the android environment that has already been verified to run adb.

### Description

1. Pick up the standard Android SDK environment variable. According to https://developer.android.com/studio/command-line/variables.html the environment variable should be ANDROID_SDK_ROOT, not ANDROID_SDK.

2. Use AndroidEnvironment when calling adb: Previously adb had to be on the PATH to work, even if android_home had been configured properly and adb had been found earlier on.

### CODE REVIEW

**Comment by adamcohenrose** [comment]
I signed the CLA

**Comment by adamcohenrose** [comment]
added my github email to the CLA

**Comment by joshdholtz** [comment]
@adamcohenrose This looks like a great change 💪 We just need to make the google-bot happy now. It looks like your first commit passed the CLA check but your second two did not. Did your last two commits have a different email address associated with them?

**Comment by adamcohenrose** [comment]
Thanks @joshdholtz 

I think the google-bot doesn't like that I signed the CLA with a different email address, and then went and added my github email to my google account afterwards... 

I've just added my google email to my github account, so maybe it will like it now?

**Comment by adamcohenrose** [comment]
@joshdholtz aha - forced googlebot to look at it again by changing the commit email addresses

**Review by getaaron — APPROVED** [review]

**Pull request merged**
