### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bolom**
the status rejected is missing in Spaceship::Tunes::AppStatus.get_from_string

### CODE REVIEW

**Review by KrauseFx — CHANGES_REQUESTED** [review]
Seems like there are lots of merge conflicts in there, please resolve them before we can review

**Comment by bolom** [comment]
@KrauseFx oops

**Comment by bolom** [comment]
I have fixed the conflicts but now I have weird messages

**Comment by hjanuschka** [comment]
@bolom i think its easier to freshly start a PR from current master and avoiding too much diff (like whitespace changes and so on)

**Pull request closed without merging**
