### PR TITLE
[WIP] Add Ruby 2.7 tests

### PR DESCRIPTION
**Pull request by joshdholtz**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by Kaspik** [comment]
Jesus Circle.CI... `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]` 🤦 

Have you thought about giving a try to Github Actions? :)

**Comment by joshdholtz** [comment]
@Kaspik Got it now 😊 chruby auto switcher was disabled in images that are Xcode 11.2 and up. And we’ll probably switch over at some point but I’d rather not change too much at once. I already feel short on time 😛

**Comment by Kaspik** [comment]
Yeah definitely. It's gonna fail anyways as it fails locally for some tests...

**Comment by joshdholtz** [comment]
@Kaspik Yup yup, my current goal is to get it to fail on CI so I know its working properly 😇 And then I will fix all the things 😉

**Comment by Kaspik** [comment]
Merge master, to see what has changed there? :)

**Comment by janpio** [comment]
Currently 10 failures that need to get fixed:

```
Failures:
 

 
  1) Fastlane Fastlane::FastFile Different Fastfiles properly shows an error message when there is a syntax error in the Fastfile
 
     Failure/Error: ff = Fastlane::FastFile.new('./fastlane/spec/fixtures/fastfiles/FastfileSytnaxError')
 

 
       #<FastlaneCore::UI (class)> received :user_error! with unexpected arguments
 
         expected: (/Syntax error in your Fastfile on line 17: fastlane\/spec\/fixtures\/fastfiles\/FastfileSytnaxError:17: syntax error, unexpected (keyword_end|end), expecting '\)'/)
 
              got: ("Syntax error in your Fastfile on line 17: fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'")
 
       Diff:
 
       @@ -1,2 +1,2 @@
 
       -[/Syntax error in your Fastfile on line 17: fastlane\/spec\/fixtures\/fastfiles\/FastfileSytnaxError:17: syntax error, unexpected (keyword_end|end), expecting '\)'/]
 
       +["Syntax error in your Fastfile on line 17: fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'"]
 
     # ./fastlane/lib/fastlane/fast_file.rb:68:in `rescue in block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:40:in `initialize'
 
     # ./fastlane/spec/fast_file_spec.rb:475:in `new'
 
     # ./fastlane/spec/fast_file_spec.rb:475:in `block (4 levels) in <top (required)>'
 
     # ------------------
 
     # --- Caused by: ---
 
     # SyntaxError:
 
     #   fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'
 
     #   ./fastlane/lib/fastlane/fast_file.rb:61:in `eval'
 

 
  2) Fastlane Fastlane::FastFile Different Fastfiles properly shows an error message when there is a syntax error in the Fastfile from string
 
     Failure/Error:
 
       ff = Fastlane::FastFile.new.parse(<<-RUBY.chomp)
 
       lane :test do
 
         cases = [:abc,
 
       end
 
       RUBY
 

 
       #<FastlaneCore::UI (class)> received :user_error! with unexpected arguments
 
         expected: (/Syntax error in your Fastfile on line 3: \(eval\):3: syntax error, unexpected (keyword_end|end), expecting '\]'\n        end\n.*/)
 
              got: ("Syntax error in your Fastfile on line 3: (eval):3: syntax error, unexpected `end', expecting ']'\n        end\n        ^~~\n")
 
       Diff:
 
       @@ -1,2 +1,2 @@
 
       -[/Syntax error in your Fastfile on line 3: \(eval\):3: syntax error, unexpected (keyword_end|end), expecting '\]'\n        end\n.*/]
 
       +["Syntax error in your Fastfile on line 3: (eval):3: syntax error, unexpected `end', expecting ']'\n        end\n        ^~~\n"]
 
     # ./fastlane/lib/fastlane/fast_file.rb:68:in `rescue in block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `parse'
 
     # ./fastlane/spec/fast_file_spec.rb:487:in `block (4 levels) in <top (required)>'
 
     # ------------------
 
     # --- Caused by: ---
 
     # SyntaxError:
 
     #   (eval):3: syntax error, unexpected `end', expecting ']'
 
     #           end
 
     #           ^~~
 
     #   ./fastlane/lib/fastlane/fast_file.rb:61:in `eval'
 

 
  3) Fastlane Fastlane::FastFile Different Fastfiles properly shows an error message when there is a syntax error in the imported Fastfile
 
     Failure/Error: ff.import('./FastfileSytnaxError')
 

 
       #<FastlaneCore::UI (class)> received :user_error! with unexpected arguments
 
         expected: (/Syntax error in your Fastfile on line 17: fastlane\/spec\/fixtures\/fastfiles\/FastfileSytnaxError:17: syntax error, unexpected (keyword_end|end), expecting '\)'/)
 
              got: ("Syntax error in your Fastfile on line 17: fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'")
 
       Diff:
 
       @@ -1,2 +1,2 @@
 
       -[/Syntax error in your Fastfile on line 17: fastlane\/spec\/fixtures\/fastfiles\/FastfileSytnaxError:17: syntax error, unexpected (keyword_end|end), expecting '\)'/]
 
       +["Syntax error in your Fastfile on line 17: fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'"]
 
     # ./fastlane/lib/fastlane/fast_file.rb:68:in `rescue in block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `chdir'
 
     # ./fastlane/lib/fastlane/fast_file.rb:50:in `parse'
 
     # ./fastlane/lib/fastlane/fast_file.rb:255:in `import'
 
     # ./fastlane/spec/fast_file_spec.rb:517:in `block (4 levels) in <top (required)>'
 
     # ------------------
 
     # --- Caused by: ---
 
     # SyntaxError:
 
     #   fastlane/spec/fixtures/fastfiles/FastfileSytnaxError:17: syntax error, unexpected `end', expecting ')'
 
     #   ./fastlane/lib/fastlane/fast_file.rb:61:in `eval'
 

 
  4) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed by default provider ID command generation generates a call to java directly
 
     Failure/Error: expect(transporter.provider_ids).to eq(java_provider_id_command)
 

 
       expected: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja... -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-\\+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 
            got: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja...on -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:191:in `block (6 levels) in <top (required)>'
 

 
  5) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed use_shell_script is false with a itc_provider short name set provider ID command generation generates a call to java directly
 
     Failure/Error: expect(transporter.provider_ids).to eq(java_provider_id_command)
 

 
       expected: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja... -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-\\+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 
            got: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja...on -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:214:in `block (6 levels) in <top (required)>'
 

 
  6) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed use_shell_script is true with a itc_provider short name set provider ID command generation generates a call to the shell script
 
     Failure/Error: expect(transporter.provider_ids).to eq(shell_provider_id_command)
 

 
       expected: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-\\+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 
            got: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:237:in `block (6 levels) in <top (required)>'
 

 
  7) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed when use shell script ENV var is set provider ID command generation generates a call to the shell script
 
     Failure/Error: expect(transporter.provider_ids).to eq(shell_provider_id_command)
 

 
       expected: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-\\+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 
            got: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:265:in `block (7 levels) in <top (required)>'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:31:in `run_block'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:13:in `block in process'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:23:in `block in synchronize'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:20:in `synchronize'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/environment.rb:20:in `synchronize'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control/modifier.rb:10:in `process'
 
     # ./.bundle/ruby/2.7.0/gems/climate_control-0.2.0/lib/climate_control.rb:10:in `modify'
 
     # ./spec_helper.rb:153:in `with_env_values'
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:263:in `block (6 levels) in <top (required)>'
 

 
  8) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed use_shell_script is true provider ID command generation generates a call to the shell script
 
     Failure/Error: expect(transporter.provider_ids).to eq(shell_provider_id_command)
 

 
       expected: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-\\+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 
            got: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:289:in `block (6 levels) in <top (required)>'
 

 
  9) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 7.x installed use_shell_script is false provider ID command generation generates a call to java directly
 
     Failure/Error: expect(transporter.provider_ids).to eq(java_provider_id_command)
 

 
       expected: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja... -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-\\+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 
            got: "/tmp/java/bin/java -Djava.ext.dirs=/tmp/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Dja...on -m provider -u fabric.devtools@gmail.com -p \\!\\>\\ p@\\$s_-+\\=w\\'o\\%rd\\\"\\&\\#\\*\\< 2>&1"
 

 
       (compared using ==)
 
     # ./fastlane_core/spec/itunes_transporter_spec.rb:312:in `block (6 levels) in <top (required)>'
 

 
  10) FastlaneCore FastlaneCore::ItunesTransporter with Xcode 6.x installed provider ID command generation generates a call to the shell script
 
      Failure/Error: expect(transporter.provider_ids).to eq(shell_provider_id_command)
 

 
        expected: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-\\+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 
             got: "\"/tmp/bin/iTMSTransporter\" -m provider -u \"fabric.devtools@gmail.com\" -p '\\!\\>\\ p@\\$s_-+\\=w'\"\\'\"'o\\%rd\\\"\\&\\#\\*\\<'"
 

 
        (compared using ==)
 
      # ./fastlane_core/spec/itunes_transporter_spec.rb:343:in `block (5 levels) in <top (required)>'
```

**Pull request closed without merging**
