### PR TITLE
Added stage flag for git_commit action

### PR DESCRIPTION
**Pull request by viktorasl**
Sometimes new files need to be staged

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks for this PR @viktorasl, it looks like this could be solved by this PR too, right? https://github.com/fastlane/fastlane/pull/1101/

Do you think it makes more sense to have 2 steps, one for staging and one for committing?

**Comment by viktorasl** [comment]
What do you mean saying "two steps"? Do you mean two actions? I think it depends on needs, for me it's important to commit newly fetched files, so I just need to stage them and commit. In that particular case it's enough to have just a flag for `git_commit` action. But if it's more common and useful to have them as a separate actions I wouldn't mind.

**Comment by asfalcone** [comment]
I also think keeping the `git_add` action separate is better because it can serve more use cases. This PR is a great idea and I can see exactly how this PR makes sense in your workflow but might not be right for everyone.

**Comment by viktorasl** [comment]
I agree. Should I close PR?

**Comment by asfalcone** [comment]
Thanks!

**Pull request closed without merging**
