### PR TITLE
Bump commander

### PR DESCRIPTION
**Pull request by neonichu**
Taking over from #5101

### CODE REVIEW

**Comment by ohwutup** [comment]
This seems good to me! Will it change testing though if it is not running production versions of sub-tools?

**Comment by ohwutup** [comment]
shall we merge this @neonichu ?

**Comment by neonichu** [comment]
I think we can do this in a better fashion now that the conflicting dependency has been reverted. I'll update the PR.

**Comment by KrauseFx** [comment]
Ahhhh, conflicts 😢

**Comment by ohwutup** [comment]
bump

**Comment by asfalcone** [comment]
@neonichu any plans to get this PR mergeable or can we close it? Thanks

**Comment by neonichu** [comment]
Updated this and squashed the history — it now only affects the hard dependency in `fastlane_core`, the other gems can be updated after in order to ensure there is no situation where the newest versions of the gems have conflicting requirements.

**Comment by KrauseFx** [comment]
But we got conflicts 😢

**Comment by KrauseFx** [comment]
Alright, this approach will not work, I gave it some more thought and documented it in https://github.com/fastlane/fastlane/pull/5612 👍

**Pull request closed without merging**
