### PR TITLE
Add a EOF newline in the pluginfile content if its not already there

### PR DESCRIPTION
**Pull request by joshrlesch**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
We use a private repo that holds some fastlane plugins that are specific to our project, I pull in specific gems from that repo in the `Pluginfile` with something like
```ruby
git "https://github.com/org/private_plugins.git" do
    gem "fastlane-plugin-private_plugin"
end
```

When I went to install a public repo with 
`fastlane add_plugin public_plugin`

I got the following error because when fastlane added the gem to the content of the `Pluginfile`, there wasn't a newline at the end of the file. And it just added it to the end of my gem block.
```
Installing plugin dependencies...

[!] There was an error parsing `Gemfile`: syntax error, unexpected end-of-input, expecting keyword_end. Bundler cannot continue.

 #  from /Users/josh.lesch/Documents/Github/modi/Gemfile:29
 #  -------------------------------------------
 #  plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
 >  eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
 #  -------------------------------------------
```

I could of just added a newline to the pluginfile and continue on, but the error output wasn't totally self explanatory of the issue, so could trip up others that do something similar.

### Motivation and Context
I tested this by making sure there wasn't a EOF newline in the pluginfile then added a new plugin with the fastlane add_plugin tool

### CODE REVIEW

**Comment by joshrlesch** [comment]
I signed it!

**Comment by KrauseFx** [comment]
How does the `\n` solve the issue?

**Comment by joshrlesch** [comment]
Adds a new line to the need of the content, before fastlane would add the gem like
```ruby
git "https://github.com/org/private_plugins.git" do
    gem "fastlane-plugin-private_plugin"
endgem 'fastlane-plugin-update_project_codesigning'
```

now 
```ruby
git "https://github.com/org/private_plugins.git" do
    gem "fastlane-plugin-private_plugin"
end
gem 'fastlane-plugin-update_project_codesigning'
```

**Comment by KrauseFx** [comment]
Ah, now I understand, thanks. Would it be easier if we just added the `\n` right before the `gem "..."` every time?

**Comment by joshrlesch** [comment]
Ha, yeah i thought about just doing that first, but wasnt sure if there was some issues with double newlines But i can change to that if you want.

**Comment by joshrlesch** [comment]
shoot sorry, did not mean to close this, had it open on my phone and my figure got a little trigger happy.

**Review by KrauseFx — APPROVED** [review]
No, actually this is fine, great job, thanks for your contribution 👍

**Pull request merged**
