### PR TITLE
Move Jenkins docs to docs page

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Review by ohayon — APPROVED** [review]

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dcordero** [comment]
The link from fastlane/docs/README.md might need to be updated.

https://github.com/fastlane/fastlane/blame/master/fastlane/docs/README.md#L28

**Comment by KrauseFx** [comment]
Nice catch @dcordero 👍

**Comment by KrauseFx** [comment]
Ah, just noticed we have all the CI systems here, let's wait for now

**Pull request closed without merging**
