### PR TITLE
Add platform parameter to spaceship iTC client's find method

### PR DESCRIPTION
**Pull request by milch**

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]

**Comment by hjanuschka** [comment]
@milch was that introduced by the produce mac support PRs? :'(

**Comment by milch** [comment]
@hjanuschka Yeah, it was missing a parameter. I just need to be more careful in the future with methods that introduce new params and check if their usage really was updated everywhere.

**Comment by hjanuschka** [comment]
@milch  sorry for the troubles, i need to be more carefull too!!
anyway we can automate this? 😄

**Comment by milch** [comment]
@hjanuschka Hmm, I don't think so, at least not without some terrible magicks. 

Well, I guess we could at least use danger to catch method definitions that have changed and then output a warning or something.

**Comment by milch** [comment]
@KrauseFx is working on getting danger to run again here: #7327

**Comment by KrauseFx** [comment]
Wow, great idea @milch 👍

**Comment by hjanuschka** [comment]
@milch great idea. 
@KrauseFx  any ideas when danger will work?

**Comment by KrauseFx** [comment]
@hjanuschka no, I'm working on it

**Pull request merged**
