### PR TITLE
Rename shield_io_timeout to shield_service_timeout

### PR DESCRIPTION
**Pull request by JrGoodle**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context
This commit changed the name of this parameter: https://github.com/HazAT/badge/commit/cdf190d46965f6b6efa5ac14c45628331f24fd70

Our CI at work failed to run fastlane because the parameter name change caused an error.

```
Could not find option 'shield_io_timeout' in the list of available options: dark, alpha, alpha_channel, custom, no_badge, badge_gravity, shield, shield_service_timeout, shield_geometry, shield_gravity, shield_scale, shield_no_resize
```

After making the changes here and [this associated change](https://github.com/HazAT/fastlane-plugin-badge/pull/3) the build was able to get past the previous error. However now I'm running into a different error when trying to run `scan` or `gym`:

```
uninitialized constant FastlaneCore::PTY::Actions
```

I'm not sure if this is because of how I'm loading the forked fastlane and plug-in repos, or if it's an actual issue.

### Description
This updates the name from `shield_io_timeout` to `shield_service_timeout` to match

### CODE REVIEW

**Comment by JrGoodle** [comment]
I signed it!

**Comment by JrGoodle** [comment]
The contents of the Gemfile I'm using to test:
```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gemspec path: File.expand_path("/Users/jenkins/fastlane")

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem 'xcpretty'
```

And the contents of `fastlane/Pluginfile`:
```ruby
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-badge', path: "/Users/jenkins/fastlane-plugin-badge"
```

**Comment by KrauseFx** [comment]
Thanks for the PR, really appreciated. This shouldn't have happened, and this PR will also break all fastlane setups using that parameter, I'll reach out to the package author 👍

**Comment by JrGoodle** [comment]
@KrauseFx so should I go ahead and close this PR?

**Comment by KrauseFx** [comment]
Seems like it's resolved as soon as a new version by Daniel is pushed 👍

**Pull request closed without merging**
