### PR TITLE
Adds `ensure_git_status_clean` action

### PR DESCRIPTION
**Pull request by lmirosevic**
A sanity check to make sure you are working in a repo that is clean. Especially useful to put at the beginning if some of your other actions will touch your filesystem, or do things to your git repo. Also needed as a prerequisite for some other actions.

This does rely on `rugged`, which is a gem with a native extension... Hope that's not an issue.

### CODE REVIEW

**Comment by KrauseFx** [comment]
```
Building native extensions.  This could take a while...
ERROR:  Error installing rugged:
	ERROR: Failed to build gem native extension.

    /Users/felixkrause/.rvm/rubies/ruby-2.0.0-p481/bin/ruby extconf.rb
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/felixkrause/.rvm/rubies/ruby-2.0.0-p481/bin/ruby

extconf failed, exit code 1
```

If somehow possible, I'd like to avoid this. Couldn't we also provide this functionality without this dependency?

**Comment by lmirosevic** [comment]
Yeah that's the issue, it needs CMake. For most of us on OS X is just a `brew install cmake`, but I can see how this might be an issue on a build server, and it does diminish the mass appeal of the lib a little if a significant portion of users gets that error when doing a `gem install fastlane`.

It's only used for a small part of the code, so I'll replace it with a `system` call to the system installed git instead.

**Comment by lmirosevic** [comment]
Should work without rugged now!

**Comment by KrauseFx** [comment]
Perfect, so simple and yet so effective :rocket:

**Pull request merged**
