### PR TITLE
[deliver] Check if each non-framed screenshot has a framed counterpart

### LINKED ISSUE #15366: [deliver] When there is at least 1 framed screenshot, all non-framed screenshot files are skipped, even for devices that have no framed screenshots
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We currently only have our iPhone screenshots framed, for iPad not.
When using `fastlane deliver` it detects some (for iPhone) framed screenshots, and therefor skips all non-framed screenshots. Since we only have non-framed screenshots, no screenshots for iPad are submitted.

##### Command executed

fastlane deliver

##### Complete output when running fastlane, including the stack trace and command used

```
[10:19:30]: Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation) - 01.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation) - 02.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation) - 03.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) (3rd generation) - 04.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) - 01.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) - 02.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) - 03.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPad Pro (12.9-inch) - 04.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone 8 Plus - 01.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone 8 Plus - 02.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone 8 Plus - 03.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone 8 Plus - 05.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone 8 Plus - 06.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone Xs Max - 01.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone Xs Max - 02.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone Xs Max - 03.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone Xs Max - 05.png
[10:19:30]: 🏃 Skipping screenshot file: ./screenshots/en-US/iPhone Xs Max - 06.png 
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
#
#  Fastfile
#  myTifi
#
#  Created by Martijn Koopman on 27/09/17.
#  Copyright © 2017 iMKapps. All rights reserved.
#
#  $Rev: 4769 $
#  $Date:: 2019-04-26 #$

before_all do
    # Set Xcode version
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode 10.1.app/Contents/Developer'
end

# Create a lane for SnapShot:
# Run this via Terminal via: fastlane screenshots
lane :screenshots do
    # Generate screenshots for the App Store:
    snapshot
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.130.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| slack-notifier        | 2.3.2        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| faraday               | 0.15.4       |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.9.5        |
| security              | 0.1.3        |
| jwt                   | 2.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| signet                | 0.11.0       |
| memoist               | 0.16.0       |
| googleauth            | 0.6.7        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.16.0       |
| tty-cursor            | 0.7.0        |
| tty-spinner           | 0.9.1        |
| tty-screen            | 0.7.0        |
| json                  | 2.2.0        |
| highline              | 1.7.10       |
| excon                 | 0.66.0       |
| rubyzip               | 1.2.4        |
| CFPropertyList        | 3.0.1        |
| plist                 | 3.5.0        |
| atomos                | 0.1.3        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.12.0       |
| claide                | 1.0.3        |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20190701 |
| faraday_middleware    | 0.13.1       |
| fastimage             | 2.1.7        |
| bundler               | 1.16.0       |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.6.0        |
| addressable           | 2.7.0        |
| multi_json            | 1.13.1       |
| os                    | 1.0.1        |
| psych                 | 2.0.8        |
| retriable             | 3.1.2        |
| mime-types            | 3.3          |
| mime-types-data       | 3.2019.0904  |
| uber                  | 0.1.0        |
| declarative           | 0.0.10       |
</details>

*generated on:* **2019-09-24**
</details>

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

It solves an open issue where if there is a single framed screenshot, all non-framed screenshots are skipped.

Resolves #15366 

### Description

When framed screenshots are detected and the current file is not framed, check to see if it has a framed counterpart. If it does, skip this unframed version. Otherwise, add this unframed version.

I created a new directory with framed and unframed files and tested just this feature.

### Testing Steps

I made a folder with a few .txt files that did and did not have the "_framed". Then, I tested my if statement like so:
```
files = Dir.glob('/Users/jess/testruby/thefiles/*.txt')
extensions = '{png,jpg,jpeg,txt}' 
framed_screenshots_found = Dir.glob("/Users/jess/testruby/thefiles/*_framed.#{extensions}").count > 0

if framed_screenshots_found
  puts "Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃"
end

files.each do |file_path|
  puts "working on: #{file_path}..."
  is_framed = file_path.downcase.include?("_framed.")

  if framed_screenshots_found && !is_framed
    # check to see if there is a framed version of this file
    fext = File.extname(file_path)
    puts file_path.gsub("#{fext}","_framed#{fext}")
    if Dir.glob(file_path.gsub("#{fext}", "_framed#{fext}")).any?
      puts "🏃 Skipping screenshot file: #{file_path} because this file has a framed version"
      next
    end
  end

  # still here then have the file_path
  puts "i am keeping #{file_path}"
end
```
**The result here shows that the statement works - it skips bob.txt because there is a bob_framed.txt, but it keeps test.txt because there is no test_framed.txt:**

```
jess:testruby/ $ ruby test_file.rb                                    [5:56:43]
Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
working on: /Users/jess/testruby/thefiles/bob.txt...
/Users/jess/testruby/thefiles/bob_framed.txt
🏃 Skipping screenshot file: /Users/jess/testruby/thefiles/bob.txt because this file has a framed version
working on: /Users/jess/testruby/thefiles/bob_framed.txt...
i am keeping /Users/jess/testruby/thefiles/bob_framed.txt
working on: /Users/jess/testruby/thefiles/test.txt...
/Users/jess/testruby/thefiles/test_framed.txt
i am keeping /Users/jess/testruby/thefiles/test.txt
```

Please note that for the test to work with minimal setup, its code is slightly different than the version in the fastlane deliver file, which includes the watch and bold:
```
if framed_screenshots_found && !is_framed && !is_watch
            # check to see if there is a framed version of this file
            fext = File.extname(file_path)
            if Dir.glob(file_path.gsub("#{fext}", "_framed#{fext}")).any?
              UI.important("🏃 Skipping screenshot file: #{file_path} because this file has a framed version")
              next
            end
          end
```

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
I'm looking at the circleci tests, and I think the details show failure because the screenshot count is higher than expected. It is 2 instead of 1 (excluding watch) and 3 instead of 2 (including watch). However, this is what I expect for this change.

**Comment by monkeywithacupcake** [comment]
What do I need to do to have this PR considered @janpio ? Is the behavior undesired?

**Comment by janpio** [comment]
Hey @monkeywithacupcake, the tests would need to be adapted to pass again of course. Additionally this lint failure needs to be fixed:

```
deliver/lib/deliver/upload_screenshots.rb:125:40: C: Style/UnneededInterpolation: Prefer to_s over string interpolation.
 
            if Dir.glob(file_path.gsub("#{fext}", "_framed#{fext}")).any?
 
                                       ^^^^^^^^^
```

**Comment by ainame** [comment]
@monkeywithacupcake 

Hi, thank you for taking the time to contribute to fastlane and I am sorry that your change is now unacceptable as is since I significantly updated `deliver/lib/deliver/upload_screenshots.rb` and your change is recognised as conflicts now.

https://github.com/fastlane/fastlane/blob/15093fc8213dcfe8982ab0e07dc8a59388c6ee92/deliver/lib/deliver/loader.rb#L88-L93

As @janpio mentioned I feel like this original change had a side effect that may cause issues to existing projects. For example, `frameit` would name a "_framed" screenshot from non-suffixed filename; e.g. `yourapp6.5_1.png` vs `yourapp6.5_1_framed.png`. In that case,   non-suffixed screenshots will also be uploaded, which is a breaking change. 

Let's continue this in https://github.com/fastlane/fastlane/issues/15366 
I'll leave my idea to the issue, which is less likely to have breaks to and probably work on it at some point.

**Pull request closed without merging**
