### PR TITLE
Add Crashlytics

### PR DESCRIPTION
**Pull request by pedrogimenez**
This adds Crashlytics support.

### CODE REVIEW

**Comment by KrauseFx** [comment]
@pedrogimenez This looks really good, thanks for working on this.

Shouldn't we also add notes about the additional parameters to the README?
```ruby
        notes_path       = params[:notes_path]
        emails           = params[:emails]
        groups           = params[:groups]
```

**Comment by KrauseFx** [comment]
:+1: for also adding tests! Much appreciated!

**Comment by pedrogimenez** [comment]
> Shouldn't we also add notes about the additional parameters to the README?

Yup. Definitely sending another pull-request later on.

**Comment by KrauseFx** [comment]
I updated the README already. Thanks.

**Comment by KrauseFx** [comment]
Thanks again @pedrogimenez for submitting this pull request :+1:

**Pull request merged**
