### PR TITLE
Added warning when no GitHub issue is linked

### PR DESCRIPTION
**Pull request by KrauseFx**
No link is here

### CODE REVIEW

**Comment by KrauseFx** [comment]
Ready to be merged from my side

**Comment by hemal** [comment]
"to the PR body" => "in the PR body." Otherwise this looks good to me.

**Comment by KrauseFx** [comment]
Thanks everyone, I'll update the PR tomorrow morning :+1:

**Comment by KrauseFx** [comment]
Updated, waiting for the build

**Pull request merged**
