### PR TITLE
Fix strip error when using an URL with appetize action

### LINKED ISSUE #11569: undefined method `strip' error when using appetize action with a URL
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

```ruby
appetize(url: "http://example.org/myapp.apk", platform: "android")
```

```bash
/Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:18:in `block in initialize_http_header': [!] undefined method `strip' for {"Content-Type"=>"application/json"}:Hash (NoMethodError)
	from /Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `each'
	from /Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
	from /Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/generic_request.rb:44:in `initialize'
	from /Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/request.rb:15:in `initialize'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/actions/appetize.rb:63:in `new'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/actions/appetize.rb:63:in `create_request'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/actions/appetize.rb:34:in `run'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
	from Fastfile:69:in `block (3 levels) in parsing_binding'
	from Fastfile:64:in `each'
	from Fastfile:64:in `block (2 levels) in parsing_binding'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/commands_generator.rb:336:in `run'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/fastlane/lib/fastlane/cli_tools_distributor.rb:94:in `take_off'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/gems/fastlane-2.75.1/bin/fastlane:20:in `<top (required)>'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/damiengavard/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C205)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.75.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-localization | 0.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-onesky       | 0.2.1   | ✅ Up-To-Date  |
| fastlane-plugin-aws_s3       | 1.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                          | Version      |
| ---------------------------- | ------------ |
| did_you_mean                 | 1.0.2        |
| io-console                   | 0.4.6        |
| CFPropertyList               | 2.3.6        |
| concurrent-ruby              | 1.0.5        |
| i18n                         | 0.9.1        |
| minitest                     | 5.11.1       |
| thread_safe                  | 0.3.6        |
| tzinfo                       | 1.2.4        |
| activesupport                | 5.1.4        |
| public_suffix                | 2.0.5        |
| addressable                  | 2.5.2        |
| rubyzip                      | 1.2.1        |
| apktools                     | 0.7.2        |
| aws-sigv4                    | 1.0.2        |
| jmespath                     | 1.3.1        |
| aws-sdk-core                 | 2.10.117     |
| aws-sdk-resources            | 2.10.117     |
| aws-sdk                      | 2.10.117     |
| babosa                       | 1.0.2        |
| bundler                      | 1.16.1       |
| claide                       | 1.0.2        |
| colored                      | 1.2          |
| colored2                     | 3.1.2        |
| highline                     | 1.7.10       |
| commander-fastlane           | 4.4.5        |
| declarative                  | 0.0.10       |
| declarative-option           | 0.1.0        |
| unf_ext                      | 0.0.7.4      |
| unf                          | 0.1.4        |
| domain_name                  | 0.5.20170404 |
| dotenv                       | 2.2.1        |
| excon                        | 0.60.0       |
| multipart-post               | 2.0.0        |
| faraday                      | 0.13.1       |
| http-cookie                  | 1.0.3        |
| faraday-cookie_jar           | 0.0.6        |
| faraday_middleware           | 0.12.2       |
| fastimage                    | 2.1.1        |
| gh_inspector                 | 1.0.3        |
| jwt                          | 2.1.0        |
| little-plugger               | 1.1.4        |
| multi_json                   | 1.13.1       |
| logging                      | 2.2.2        |
| memoist                      | 0.16.0       |
| os                           | 0.9.6        |
| signet                       | 0.8.1        |
| googleauth                   | 0.6.2        |
| httpclient                   | 2.8.3        |
| mime-types-data              | 3.2016.0521  |
| mime-types                   | 3.1          |
| uber                         | 0.1.0        |
| representable                | 3.0.4        |
| retriable                    | 3.1.1        |
| google-api-client            | 0.13.6       |
| json                         | 2.1.0        |
| mini_magick                  | 4.5.1        |
| multi_xml                    | 0.6.0        |
| plist                        | 3.4.0        |
| security                     | 0.1.3        |
| slack-notifier               | 1.5.1        |
| terminal-notifier            | 1.8.0        |
| unicode-display_width        | 1.3.0        |
| terminal-table               | 1.8.0        |
| tty-screen                   | 0.6.4        |
| tty-cursor                   | 0.5.0        |
| tty-spinner                  | 0.8.0        |
| word_wrap                    | 1.0.0        |
| nanaimo                      | 0.2.3        |
| xcodeproj                    | 1.5.4        |
| rouge                        | 2.0.7        |
| xcpretty                     | 0.2.8        |
| xcpretty-travis-formatter    | 1.0.0        |
| fastlane-plugin-aws_s3       | 1.1.1        |
| fastlane-plugin-localization | 0.2.0        |
| netrc                        | 0.11.0       |
| rest-client                  | 2.0.2        |
| onesky-ruby                  | 1.1.0        |
| fastlane-plugin-onesky       | 0.2.1        |
| oauth                        | 0.5.4        |
| jira-ruby                    | 1.4.3        |
</details>

*generated on:* **2018-01-15**
</details>

### PR DESCRIPTION
**Pull request by dagio**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Fix #11569

### Description
This change should be be properly review as I'm newbie with Ruby

### CODE REVIEW

**Comment by dagio** [comment]
I signed it!

**Review by KrauseFx — APPROVED** [review]
Thanks for your contribution @dagio 👍

**Comment by KrauseFx** [comment]
Seems like this also causes a test failure, could you update the tests also to reflect this change?

**Comment by janpio** [comment]
Hey @dagio, I took a look at your code. Why does this actually help here? I don't understand the change :/

**Comment by janpio** [comment]
Already fixed in https://github.com/fastlane/fastlane/pull/12544

Thanks anyway!

**Pull request closed without merging**
