### PR TITLE
Fix commit_version_bump could not find a .xcodeproj, this closes #6675

### LINKED ISSUE #6675: Could not find a .xcodeproj in the current repository's working directory.
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When my iOS project path is something like `xxxPods/myProjectName`,  `commit_version_bump` could not find a .xcodeproj in the current repository's working directory.
##### Complete output when running fastlane, including the stack trace and command used

[18:35:01]: ▸ /Users/xxxx/Developer/xxxx/xxxxxPods/myProjectName
[18:35:01]: Variable Dump:
[18:35:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"12", :VERSION_NUMBER=>"1.0.10"}
[18:35:01]: Could not find a .xcodeproj in the current repository's working directory.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 4    | increment_version_number            | 1           |
| 5    | get_version_number                  | 0           |
| 💥    | commit_version_bump                 | 0           |
+------+-------------------------------------+-------------+

[18:35:01]: fastlane finished with errors

[!] Could not find a .xcodeproj in the current repository's working directory.

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

What Xcode version do you use (e.g. 7.3, 8.0): 8.0

### PR DESCRIPTION
**Pull request by wangjiejacques**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

…pository's working directory when the current repository is under something like xxxPods/myProjectName

### CODE REVIEW

**Comment by asfalcone** [comment]
@WANGjieJacques Thanks for the PR! Are you able to add a test to `hg_commit_version_bump_spec` that could test for this new behavior?

**Comment by WANGjieJacques** [comment]
@asfalcone let me try.  ;]

**Comment by WANGjieJacques** [comment]
@asfalcone test done.

**Comment by asfalcone** [comment]
@WANGjieJacques It looks like some tests are failing on your branch. They don't look related to your changes though. Can you rebase on master and then push again?

**Comment by WANGjieJacques** [comment]
@asfalcone I fixed the tests failing.

**Review by asfalcone — APPROVED** [review]

**Comment by asfalcone** [comment]
Thanks @WANGjieJacques 🚀

**Comment by mmysliwiec** [comment]
I believe this PR is broken. Why do we have `[^/]*` in regex instead of just `.*`? I think the merit of the fix was to add backslash before Pods, right?

Right now any path with subfolder will not match properly so paths like:

    /Pods/SVPullToRefresh/Demo/SVPullToRefreshDemo.xcodeproj
    /Pods/SVPullToRefresh/SVPullToRefreshDemo.xcodeproj

will not be excluded.

**Comment by milch** [comment]
@mmysliwiec Are you sure it's a problem? Did you have any trouble since this PR was merged?

**Comment by WANGjieJacques** [comment]
@mmysliwiec we have `[^/]*` because we don't want `/` between `Pods` and `xcodeproj` , so any path has `/` between `Pods` and `xcodeproj` will be excluded.

**Comment by mmysliwiec** [comment]
@WANGjieJacques But why? I **want** to include paths with `/` to the reject patters since I don't want any xcodeprojs comming from the CocoaPods (including subfolders), right?

I have such Pod added to my Podfile:
`pod 'SVPullToRefresh', '~> 0.4.1'`
This Pod downloads demo project with it's own xcodeproj:
`/Pods/SVPullToRefresh/Demo/SVPullToRefreshDemo.xcodeproj`

This results with error on latest commit_version_bump action:

    fastlane finished with errors
    [!] Found multiple .xcodeproj projects in the current repository's working directory. Please specify your app's main project: 
    MyProject.xcodeproj
    Pods/SVPullToRefresh/Demo/SVPullToRefreshDemo.xcodeproj

I've changed the local commit_version_bump.rb file (line 22):

    xcodeproj_paths = Dir[File.expand_path(File.join(repo_path, '**/*.xcodeproj'))].reject { |path| %r{/Pods/[^/]*.xcodeproj} =~ path }
replaced with:

    xcodeproj_paths = Dir[File.expand_path(File.join(repo_path, '**/*.xcodeproj'))].reject { |path| %r{/Pods/.*.xcodeproj} =~ path }
and now it's working flawlessly for `SVPullToRefresh` Pod.

As you can see I've changed the reject pattern from `%r{/Pods/[^/]*.xcodeproj}` to `%r{/Pods/.*.xcodeproj}`

I believe [#6675](https://github.com/fastlane/fastlane/issues/6675) was about 'Pods like' paths: `xxxPods/myProjectName` so reject pattern with first `/` before Pods (`/Pods/`) should already fix this, right?

**Comment by WANGjieJacques** [comment]
@mmysliwiec you are right, I never thought about pod demo project, I will fix this.

**Comment by asfalcone** [comment]
Thanks @WANGjieJacques and @mmysliwiec for talking this out and coming to a solution! 🙌

**Comment by WANGjieJacques** [comment]
@asfalcone @mmysliwiec I create a pull request for this #7043

**Pull request merged**
