### PR TITLE
Clean up after auto-updating fastlane

### LINKED ISSUE #379: update_fastlane and check_version_conflict
Hi,

I'm running fastlane ios release with update_fastlane option then getting this stack trace:
(EDIT: even without update_fastlane option I still getting this error)
```
fastlane ios release
-----------------------------
--- Step: update_fastlane ---
-----------------------------
Updating produce from 0.3.4 to 0.3.5 ... 🚀
Finished updating produce
fastlane.tools succesfully updated! I will now restart myself... 😴
/Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:216:in `block in finish_resolve'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:215:in `each'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb:215:in `finish_resolve'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:129:in `block in load_default_actions'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane/actions/actions_helper.rb:128:in `load_default_actions'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/lib/fastlane.rb:18:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0@global/gems/fastlane-1.6.0/bin/fastlane:5:in `<top (required)>'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `load'
	from /Users/zakhej/.rvm/rubies/ruby-2.2.0/bin/fastlane:23:in `<main>'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zakhej/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I do not know what is mime-types and why I got two versions on my system, but after uninstalling mime-types-2.6.1 fastlane command goes well.
Does anyone know how to fix this and explain such situation?

### PR DESCRIPTION
**Pull request by milch**
Fixes #379

### CODE REVIEW

**Comment by KrauseFx** [comment]
Thanks @milch, but according to the error message:
```
can't activate mime-types-2.6.1, already activated mime-types-1.25.1
```

it seems like we need `2.6.1` instead or `1.25`, right?

**Comment by MarkMolina** [comment]
@milch @KrauseFx Can we please merge this? Our builds are stalled for days now. Removing and reinstalling everything doesn't seem to work since yesterday.

**Comment by KrauseFx** [comment]
@MarkMolina and this pull request fixes the issue for you? Have you tested it?

**Comment by MarkMolina** [comment]
Not a ruby gem master here but tried the following:

- forked of course
- gem build fastlane.gemspec
- gem install fastlane-1.7.0.gem --local

but same error unfortunately. Did I do this correctly?

**Comment by KrauseFx** [comment]
@MarkMolina We submitted [this issue](https://github.com/rubygems/rubygems/issues/1309) on RubyGems already. This pull request doesn't fix the problem unfortunately.

**Comment by MarkMolina** [comment]
Hey I just tested it locally and it doesn't work unfortunately

**Comment by KrauseFx** [comment]
Thanks @milch :+1:

**Pull request merged**
