### PR TITLE
Add an interactive console for users as well

### PR DESCRIPTION
**Pull request by lacostej**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Sometimes I wish to send code for users to test directly into their setup. This would allow to do it.

### Description

I've used the similar code in our u3d project here for years https://github.com/DragonBox/u3d/blob/8c156f401f2b8443936e3873b8566a965c783165/lib/u3d/commands.rb#L68-L80

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
I'm wondering if we should name this command `repl` instead. Because pedantically speaking the term console does not imply interactivity but more reading output (think macOS's Console.app), while things like `pry` and `irb` are called REPL (Read-Execute-Print Loop).

That being said since you added `bin/console` with such a name too we should keep the names consistent.

**Comment by lacostej** [comment]
> I'm wondering if we should name this command `repl` instead. Because pedantically speaking the term console does not imply interactivity but more reading output (think macOS's Console.app), while things like `pry` and `irb` are called REPL (Read-Execute-Print Loop).
> 
> That being said since you added `bin/console` with such a name too we should keep the names consistent.

I wouldn't change `bin/console` as it follows the bundler convention. Console there probably refer to the original [system consoles](https://en.wikipedia.org/wiki/System_console). The consistency is I think also a strong argument to keep the command identical.

Note that Mac's Console is probably one of the few IT system named console that doesn't do input. I'll blame Apple for the confusion.

**Review by rogerluan — APPROVED** [review]
Nice! 🌟 this is awesome and quite intuitive IMO.

I think this deserves to be documented somewhere, for discoverability! Idk where exactly, though. It might be in this repo, or in https://github.com/fastlane/docs, what do you think? Where should this live?

**Comment by lacostej** [comment]
> Nice! 🌟 this is awesome and quite intuitive IMO.
> 
> I think this deserves to be documented somewhere, for discoverability! Idk where exactly, though. It might be in this repo, or in https://github.com/fastlane/docs, what do you think? Where should this live?

yes, in this repo and in the docs would be nice, together with a nice screenshot or even an animated gif.

Example:

image

I hope to use it to help troubleshoot issues like #21765 :)

**Comment by rogerluan** [comment]
@lacostej you probably need to reopen this manually 👀

**Comment by lacostej** [comment]
yes, but I don't seem to be able in the same PR. Something went wrong.

**Comment by lacostej** [comment]
now it lets me

**Comment by lacostej** [comment]
nope, it is stuck. I'll reopen a new one.

**Pull request closed without merging**
