### PR TITLE
[scan] add parallel_testing option to scan

### LINKED ISSUE #19856: No option for xcodebuild option "-parallel-testing-enabled"
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

It's pretty strange that fastlane lets me set `-parallel-testing-worker-count` using `concurrent_workers`, but I have to use `xcargs: "-parallel-testing-enabled YES"` to actually enable parallel testing. I would expect that option to be configurable via fastlane as well.

### PR DESCRIPTION
**Pull request by tejassharma96**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #19856 

### Description

Added code for `-parallel-testing-enabled` to fastlane.
- Added `parallel_testing` option to `scan/lib/scan/options.rb`
- Consumed that option in `scan/lib/scan/test_command_generator.rb`
- Added tests for true/false/not set to `scan/spec/test_command_generator_spec.rb`
- Updated `fastlane/swift/ScanfileProtocol.swift` to support the new option

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much for adding this 🙌

**Comment by tejassharma96** [comment]
did you mean to add that documentation stuff here? I think you might've meant to put it in https://github.com/fastlane/fastlane/pull/19860 😅

**Comment by joshdholtz** [comment]
@tejassharma96 Totally did 😛 I should really not be using computers anymore today but here we are... Going to remove here and put it on the other 🤷‍♂️

**Comment by tejassharma96** [comment]
😂

**Comment by joshdholtz** [comment]
I almost did it again 🤦‍♂️

**Pull request merged**
