### PR TITLE
Upload ipa through s3 api instead of krausefx-ipa and refactor

### PR DESCRIPTION
**Pull request by oronbz**
Hi!
So I've noticed some files (html, plist, version, dsym) are being uploaded through s3 api but the ipa is being uploaded with krausefx-ipa command.

So what I've done here is to first refactor the s3 action to include a single upload method which all files are now used to upload with it.

From this change some methods and variables are useless and gone now.

Also, since we're not using the command anymore, build-args shouldn't exist, thus, removal of the tests that check it output was a must.

Needless to say that I've verified the ipa and all the other files uploaded successfully through the new upload method.

Should also help with #1458

### CODE REVIEW

**Comment by ohwutup** [comment]
Thanks for jumping on this @oronbz! Taking look now! Really awesome how many things you are fixing!! :rocket:

**Comment by ohwutup** [comment]
Hey @oronbz, this is an awesome PR and really cleans up the code a lot! One question I have is, just to feel a little safer about merging this and to know that there is going to be less opportunity for this to break weird edge cases, are there any tests that you think could be written here to validate all of this changed code?

**Comment by oronbz** [comment]
Hey @ohwutup,
I'm a total rookie on the ruby grounds, but I'll see If I can implement any more tests.

**Comment by oronbz** [comment]
@ohwutup I see most of the tests are checking for exceptions.
I guess this is due the fact that it's hard to test s3 without actually uploading.
You have any idea how to test it without actually using s3 client?

**Comment by ohwutup** [comment]
Hey @oronbz! No worries! I can see if I can pull some time to help out or we can just get some more eyes on this before me merge! One little favor to ask: We are working on the monorepo migration shortly, I am going to close this PR for now, would you mind reopening this on the new repo as soon as its open? Apologies for making you do a bit of extra work, we would really love to get this refactored code in, there is just going to be a bit of reorganization in the repo! Thanks @oronbz, please reach out if you have any questions at all! Thanks for your understanding. :octopus: :rocket:

**Comment by ohwutup** [comment]
[blog post for reference](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools)

**Pull request closed without merging**
