### PR TITLE
Add GitHub Action for adding a comment to include `fastlane env` in an issue description

### LINKED ISSUE #15231: Add GitHub Action for adding a comment to include `fastlane env` in an issue description
### Issue Description

Some time ago GitHub has announced [GitHub Actions](https://help.github.com/en/categories/automating-your-workflow-with-github-actions). Recently a `fastlane` organisation got an access to `Actions` Beta. It is a good time to start playing with the new feature from GitHub. 

Based on the proposal about [@fastlane-bot V2](https://github.com/fastlane/fastlane/issues/15078):

```
What does the bot do?

...
Asking about fastlane env information
```
☝️ seems to be a good candidate to start with.

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

> Some time ago GitHub has announced GitHub Actions. Recently a fastlane organisation got an access to Actions Beta. It is a good time to start playing with the new feature from GitHub.

It is the first step of bot's code migration to GitHub Actions based on [this proposal](https://github.com/fastlane/fastlane/issues/15078). 

This PR is introducing an action for adding a comment to include `fastlane env` in an issue description.

closes https://github.com/fastlane/fastlane/issues/15231.

### Description

I followed the instructions from [`Creating a JavaScript Action`](https://github.com/actions/toolkit/blob/master/docs/javascript-action.md) guidelines and [`Getting Started: GitHub context`](https://github.com/actions/toolkit/pull/80) pull request. 

I was looking at the examples from [GitHub Actions repository](https://github.com/actions), i.e. [first-interaction](https://github.com/actions/first-interaction).

Please note that this is just an action implementation. It **does not take** any effect itself. We still need to create the **[workflow](https://help.github.com/en/articles/configuring-a-workflow#creating-a-workflow-file)**, which will be using the `add-fastlane-env-comment` action. I will create dedicated issue for that once we merge this PR. 

There's a lot of changes in this PR because I needed to commit production dependencies. Please have a look at [this section](https://github.com/actions/toolkit/blob/master/docs/javascript-action.md#publish-a-v1-release-action) to get more details. To make a review easier, I did split the commits:
* `Add GitHub Action for adding a comment to include `fastlane env` in an issue description` 👈 actual code changes
* `Add production dependencies` 👈 adding production dependencies

In the future we might consider creating separate repositories for all public actions, although maybe **creating a separate repo right away** for private actions would be fine too 🤔According to [the docs](https://help.github.com/en/articles/about-actions#choosing-a-location-for-your-action):

> If you're developing an action for other people to use, we recommend keeping the action in its own repository instead of bundling it with other application code. This allows you to version, track, and release the action just like any other software.

> If you're building an action that you don't plan to make available to the public, you can store the action's files in any location in your repository. If you plan to combine action, workflow, and application code in a single repository, we recommend storing actions in the `.github` directory. For example, `.github/actions/action-a` and `.github/actions/action-b`.

 Thoughts? 

### Testing

To test the changes, I implemented the unit tests. To run them, execute `npm test` (followed by `npm install` to install the package dependencies and `npm build` to build the package). 

image

🙇 🙇

### CODE REVIEW

**Comment by mollyIV** [comment]
> In the future we might consider creating separate repositories for all public actions, although maybe creating a separate repo right away for private actions would be fine too 🤔

I would suggest to create **one public repository for all `fastlane` specific actions**:

```
fastlane/actions
```

I tested it in a private project and in a workflow we could reference these actions like:

```
jobs:
  build:
    name: Hello 👋
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: fastlane/actions/path-to-action/action-a@master
```

For the **public actions that anyone could use**, I would suggest create **a repository per action**:

```
fastlane/action-a
fastlane/action-b
```

according to the documentation:

> If you're developing an action for other people to use, we recommend keeping the action in its own repository instead of bundling it with other application code. This allows you to version, track, and release the action just like any other software.

WDYT?

**Comment by mollyIV** [comment]
After reading this comment https://github.com/fastlane/issue-bot/pull/55#issuecomment-525114536 I came up with the idea that maybe we could convert this action to more generic one. 

It would expect the **regex** and **comment message** as an input. 

```
// action.yml file

inputs:
  regex:
    description: 'A regex to look for in an issue description'
    required: true
  issue-message:
    description: 'Comment to post on an issue when any matches found'
    required: true
```

If any matches found in an issue description (based on provided regex), an action would add a comment message (provided in an input) ✨ 

WDYT? 🤔

**Comment by janpio** [comment]
- +1 on `fastlane/actions` repo for this, @joshdholtz should be able to help out.
- Not super sure about the generalization, for fastlane probably not necessary - but for other users it might be, so why not.

**Comment by joshdholtz** [comment]
I think the separate repo for actions would probably be the cleanest approach 😊 👌 

Also, can we ignore all the node modules from being committed with the actions? There are a lot of files in this PR 😇

**Comment by janpio** [comment]
https://github.com/fastlane/actions is waiting for you to come back @mollyIV :)

**Comment by KrauseFx** [comment]
Wow amazing, this looks great. Any chance we can rename the repo to `github-actions` or something, to avoid confusion with fastlane actions?

**Comment by janpio** [comment]
Smart thinking @KrauseFx - renamed it.

**Comment by joshdholtz** [comment]
@mollyIV @janpio Are we closing out this PR in favor of creating a new one in https://github.com/fastlane/github-actions?

**Comment by mollyIV** [comment]
@joshdholtz @janpio Yeah, let's do that 💪 I will create a new one in https://github.com/fastlane/github-actions.

**Pull request closed without merging**
