### PR TITLE
Fix multiplatform iOS builds

### LINKED ISSUE #20768: Creating an iOS specific build with Xcode's new multiplatform app template doesn't create .ipa
### Discussed in https://github.com/fastlane/fastlane/discussions/20759

<div type='discussions-op-text'>

<sup>Originally posted by **knlshh** October 19, 2022</sup>
I'm creating a new SwiftUI app that uses Xcode's new multiplatform app template that supports building macOS + iOS apps in a single codebase. Please note that this is **not** a Catalyst app. 

The Supported Destinations look like this in Xcode:
Screen Shot 2022-10-19 at 10 22 15 PM

When I run Fastlane's `gym` step with the platform as `ios`, I'd expect the `.ipa` file to be created, but this isn't the case (archiving succeeds, but the `.ipa` file isn't generated).

If I remove the `Mac` destination from the above list and re-run `gym`, the `.ipa` file is created. I suspect this is because of the `building_for_ios` (https://github.com/fastlane/fastlane/blob/950bb820237d52e15690408083e328f739ac0ef3/gym/lib/gym/module.rb#L28) conditional.

Copied as-is from the above link:
```
def building_for_ios?
  if Gym.project.mac?
    # Can be building for iOS if mac project and catalyst
    return building_mac_catalyst_for_ios?
  else
    # Can be iOS project and build for mac if catalyst
    return false if building_mac_catalyst_for_mac?

    # Can be iOS project if iOS, tvOS, or watchOS
    return Gym.project.ios? || Gym.project.tvos? || Gym.project.watchos?
  end
end
```

While determining if Fastlane is building for `ios`, it checks if the project supports `mac` (`Gym.project.mac`), and if yes, returns `building_mac_catalyst_for_ios`. This isn't necessarily the case since a multiplatform app can be building for iOS **and** support Mac **and** still not be building Mac Catalyst for iOS. 

Wondering if my understanding is incorrect or if this is a bug in Fastlane? 
</div>

### LINKED ISSUE #21308: [gym] "PKG invalid" when exporting iOS app
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have a lan that runs the `build_app` action, configured the following way:
```ruby
build_app(
   project: "BDZDelays.xcodeproj",
   scheme: "BDZDelays",
   export_method: "app-store",
   export_options: {
      provisioningProfiles: {
         "yalishanda.BDZDelays" => "iOS Distribution"
      }
   },
   sdk: "iphoneos16.4"
)
```

It reached the stage where it said that the achive succeede:
```
[15:45:36]: ▸ Touching BDZDelays.app (in target 'BDZDelays' from project 'BDZDelays')
[15:45:36]: ▸ Archive Succeeded
[15:45:36]: Compressing 1 dSYM(s)
[15:45:36]: $ cd '/Users/yalishanda/Library/Developer/Xcode/Archives/2023-05-26/BDZDelays 2023-05-26 15.41.12.xcarchive/dSYMs' && zip -r '/Users/yalishanda/Documents/BDZ-Delays/BDZDelays.app.dSYM.zip' *.dSYM
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/ (stored 0%)
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/Contents/ (stored 0%)
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/Contents/Resources/ (stored 0%)
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/Contents/Resources/DWARF/BDZDelays (deflated 69%)
[15:45:41]: ▸ updating: BDZDelays.app.dSYM/Contents/Info.plist (deflated 52%)

[15:45:41]: Successfully exported and compressed dSYM file
[15:45:41]: Successfully exported the .app file:
[15:45:41]: ./BDZDelays.app
[15:45:41]: Generated plist file with the following values:
[15:45:41]: ▸ -----------------------------------------
[15:45:41]: ▸ {
[15:45:41]: ▸   "provisioningProfiles": {
[15:45:41]: ▸     "yalishanda.BDZDelays": "iOS Distribution"
[15:45:41]: ▸   },
[15:45:41]: ▸   "method": "app-store",
[15:45:41]: ▸   "signingStyle": "manual"
[15:45:41]: ▸ }
[15:45:41]: ▸ -----------------------------------------
```

but then it faled to execute the folllowng command:
```
$ /usr/bin/xcrun /usr/local/Cellar/fastlane/2.213.0/libexec/gems/fastlane-2.213.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_config20230526-60135-c27bjl.plist' -archivePath /Users/yalishanda/Library/Developer/Xcode/Archives/2023-05-26/BDZDelays\ 2023-05-26\ 15.41.12.xcarchive -exportPath '/var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_output20230526-60135-ax7w82'
x+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios testflight |
+------------------+----------------+
[15:45:53]: PKG invalid
```

When I manually copy paste and execute that command, it gives me no error:
```bash
/usr/bin/xcrun /usr/local/Cellar/fastlane/2.213.0/libexec/gems/fastlane-2.213.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_config20230526-60135-c27bjl.plist' -archivePath /Users/yalishanda/Library/Developer/Xcode/Archives/2023-05-26/BDZDelays\ 2023-05-26\ 15.41.12.xcarchive -exportPath '/var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_output20230526-60135-ax7w82'
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_config20230526-60135-c27bjl.plist -archivePath '/Users/yalishanda/Library/Developer/Xcode/Archives/2023-05-26/BDZDelays 2023-05-26 15.41.12.xcarchive' -exportPath /var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_output20230526-60135-ax7w82
2023-05-26 16:02:56.787 xcodebuild[65991:1285960] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/BDZDelays_2023-05-26_16-02-56.787.xcdistributionlogs".
Exported BDZDelays to: /var/folders/ks/b40l8z9j4lj6_kmd6vv8zntr0000gn/T/gym_output20230526-60135-ax7w82
** EXPORT SUCCEEDED **
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                   |
| --------------------------- | ------------------------------------------------------- |
| OS                          | 13.3.1                                                  |
| Ruby                        | 3.1.4                                                   |
| Bundler?                    | false                                                   |
| Git                         | git version 2.39.2 (Apple Git-143)                      |
| Installation Source         | /usr/local/Cellar/fastlane/2.213.0/libexec/bin/fastlane |
| Host                        | macOS 13.3.1 ((a))                                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@3.1/3.1.4/lib                    |
| OpenSSL Version             | OpenSSL 3.1.0 14 Mar 2023                               |
| Is contained                | false                                                   |
| Is homebrew                 | true                                                    |
| Is installed via Fabric.app | false                                                   |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version               | 14.3                                                    |
| Swift Version               | 5.8                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS app in debug configuration for iOS 16.4"
  lane :build_app_debug do
    build_ios_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      configuration: "Debug",
      clean: true,
      export_method: "development",
      skip_codesigning: true,
      skip_archive: true,
      sdk: "iphoneos16.4"
    )
  end

  desc "Run all tests"
  lane :tests do
    sh('rm -rf "$(pwd)/test_output"')
    for scheme in [
      "StationDomain", 
      "SearchStationDomain",
      "ROVR",
    ] do
      run_tests(
        package_path: "BDZDelays/bdz-delays",
        scheme: scheme,
        device: "iPhone 13 Pro Max",
        result_bundle: true,
        output_directory: Dir.pwd + "/test_output"  # https://github.com/fastlane/fastlane/issues/20012
      )
    end
  end

  desc "Upload to Testfllght"
  lane :testflight do
    build_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "yalishanda.BDZDelays" => "iOS Distribution"
        }
      },
      sdk: "iphoneos16.4"
    )
    upload_to_testflight
  end
end

platform :mac do
  desc "Build the macOS app in debug configuration for macOS 13"
  lane :build_app_debug do
    build_mac_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      configuration: "Debug",
      clean: true,
      export_method: "development",
      skip_codesigning: true,
      skip_archive: true,
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.213.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| multipart-post                  | 2.3.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.4.10       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.5.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.42.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.768.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.173.0      |
| aws-sdk-kms                     | 1.64.0       |
| aws-sdk-s3                      | 1.122.0      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-05-26**
</details>

### PR DESCRIPTION
**Pull request by zachwaugh**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Currently using a multiplatform Xcode project (Xcode > New Project > Multiplatform App) will fail to build for iOS from fastlane using `build_app` with a `PKG invalid` error. The reason is the platform check for whether to do an iOS build `Gym.building_for_ios?` returns `false`, so it attempts to build an iOS app like a macOS app.

- Closes https://github.com/fastlane/fastlane/issues/21308
- Closes https://github.com/fastlane/fastlane/issues/20768

### Description
This fixes the above error by explicitly checking for cases where we might be a multiplatform app (e.g. multiple `SUPPORTED_PLATFORM` properties) and checking which `sdk` is being used. I'm not sure if this is the correct fix, I couldn't find good documentation on the right way to choose a platform to build for a multiplatform app using `xcodebuild`. Passing the `sdk: "iphoneos"` or `sdk: "macosx"` option seemed to work though, so I'm expecting that is required and what we need to check. If there is alternative way to inform `xcodebuild` about the platform, I'm happy to change the check.

I added a new example project created using the Multiplatform App template and some related tests. I'm not a Ruby programmer and not familiar with the codebase, so let me know if there is a better way to do any (or all) of this.

### CODE REVIEW

**Comment by PSchmiedmayer** [comment]
@zachwaugh Thank you for creating this PR. We run into a similar issue with one of our applications, it would be great to see this supported in fastlane.

Is there a plan to merge this PR and get it into a next release @joshdholtz. Any way that we could help there?

**Review by getaaron — APPROVED** [review]
Thanks for the PR, it looks great!

**Comment by ConradoMateu** [comment]
Hi @zachwaugh, thanks for your MR.

I have Fastlane and Gym 2.216.0 and I am still having the issue that you mentioned.

I am using Xcode 15.1 and Codemagic.

Here is the information 


+-----------------------------------------------------------------------------------------------------------------+
|                                             Summary for gym 2.216.0                                             |
+----------------------------------------------------+------------------------------------------------------------+
| scheme                                             | Truffle                                                    |
| export_method                                      | app-store                                                  |
| destination                                        | generic/platform=iOS                                       |
| sdk                                                | iphoneos                                                   |
| export_options.provisioningProfiles.art.truffle.fm | match AppStore art.truffle.fm                              |
| project                                            | ./Truffle.xcodeproj                                        |
| clean                                              | false                                                      |
| output_directory                                   | .                                                          |
| output_name                                        | Truffle                                                    |
| silent                                             | false                                                      |
| skip_package_ipa                                   | false                                                      |
| skip_package_pkg                                   | false                                                      |
| build_path                                         | /Users/builder/Library/Developer/Xcode/Archives/2023-11-13 |
| result_bundle                                      | false                                                      |
| buildlog_path                                      | ~/Library/Logs/gym                                         |
| xcodebuild_formatter                               | xcpretty                                                   |
| build_timing_summary                               | false                                                      |
| skip_profile_detection                             | false                                                      |
| xcodebuild_command                                 | xcodebuild                                                 |
| skip_package_dependencies_resolution               | false                                                      |
| disable_package_automatic_updates                  | false                                                      |
| use_system_scm                                     | false                                                      |
| xcode_path                                         | /Applications/Xcode-15.1.app                               |
+----------------------------------------------------+------------------------------------------------------------+

Here is the gym lane:

```ruby
  desc "Release a new version to TestFlight"
  lane :release do |options|

    create_keychain(
      name: ENV["MATCH_KEYCHAIN"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
      verbose: true
    )
    # Fetch certificates and provisioning profiles using match
    match(type: "appstore",app_identifier: "art.truffle.fm", readonly: true, keychain_name: ENV["MATCH_KEYCHAIN"], keychain_password: ENV["MATCH_PASSWORD"]) # readonly: true is recommended for CI
    
    # Increment version and build number
    bump_and_push_version(options)
    
    # Build the IPA
    gym(
    scheme: truffle_scheme,
    export_method: 'app-store',
    destination: "generic/platform=iOS",
    sdk: "iphoneos"
    )
    
    # Define the API key for App Store Connect
    api_key = app_store_connect_api_key(
    key_id: ENV["APPSTORE_API_KEY"],
    issuer_id: ENV["APPSTORE_ISSUER_ID"],
    key_content: ENV["AUTH_KEY"],
    in_house: false # set to true for enterprise and false for individual accounts
    )
    
    # Upload to TestFlight
    pilot(
    api_key: api_key,
    ipa: lane_context[SharedValues::IPA_OUTPUT_PATH],
    skip_waiting_for_build_processing: true
    )
    
    cleanup_git_configuration
  end
```

Is there any workaround?

**Comment by zachwaugh** [comment]
@ConradoMateu this PR was merged on Oct 7 and last release was Sept 18, so doesn't look like it's in a release yet,  you'll need to target the `master` branch for now

**Comment by NachoSoto** [comment]
I think this probably fixes #20826?

**Comment by Thomas-Vos** [comment]
It seems that passing an `sdk` value of `"iphoneos"` breaks iOS builds with a watchOS dependency.

**Pull request merged**
