### PR TITLE
[frameit] Fix inconsistent dimensions on device frames

### LINKED ISSUE #14093: [frameit] Device frames have inconsistent dimensions
While creating a PR to fix some wrong offsets, I noticed that the device frames we are using have inconsistent dimensions (only 1, 2 or 3 pixels):

image

image

image

image

This of course messes with the framing code of `frameit` and produces inexact results.

---

Fortunately it seems the "slot" (transparent area where we place the screenshot) and the offsets (pixels to left and top border of image) are not affected here - it's always just 1 or 2 additional extra lines of empty pixels for the dark variants (and an additional line for a shadow/half-pixel for the 7 plus jet black).

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
closes https://github.com/fastlane/fastlane/issues/14093 

The device frames processed by our script have inconsistent dimensions. It messes with the code of `frameit` and produces an inconsistent output. 

### Description

Even though we were trimming the background from the image, the extra 1, 2 or pixels were still there. The root cause was that there was not enough color difference between the shadow and device color, i.e. space gray or jet black models. 

The solution was to set percent color disimilarity threshold: `fuzz(90%)`.
`+repage` option has been added to remove a meta-data for further processing. 

The way I was testing the fix:
1. Run `rake` command. 
2. Check the dimensions of generated frames in `latest` 

6s

7_plus
8_plus

Thanks!

### CODE REVIEW

**Review by janpio — APPROVED** [review]
Awesome, and perfect PR description as well 😍 

Super small request: Add a comment above/in the code to explain what it does, maybe also include a link to the PR or issue there. Those Imagemagick functions are not really self explaining.

Then this is good to merge 👍

**Comment by mollyIV** [comment]
Sure @janpio 💪 
Could you please have a quick look if that looks good to you:

```ruby
 # For some images the difference between the shadow and device color is not enough to get trimmed.
 # To fix it, we set the percent color disimilarity threshold.
 # `+repage` parameter removes a meta-data for further processing.
 # To get more insights, please check https://github.com/fastlane/fastlane/pull/14199. 
```

If it does, I will add the comment in the code, cheers!

**Comment by janpio** [comment]
Simpler:

```
  image.combine_options do |co|
    co.fuzz("90%")      # color disimilarity threshold to get all shadows, see https://github.com/fastlane/fastlane/pull/14199
    co.trim("+repage")  # `+repage`remove meta-data
  end
```

Maybe?

**Comment by mollyIV** [comment]
👋 @janpio I added the comments, could you please have a quick 👀 🙇

**Comment by joshdholtz** [comment]
This is a cool fix! Giving this a test right now 💪

**Review by joshdholtz — APPROVED** [review]
This is 💯 Thanks for adding this in ❤️

**Pull request merged**
