### PR TITLE
fastlane precheck tool

### PR DESCRIPTION
**Pull request by taquitos**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
After waiting for review for multiple days, apps often get rejected for app metadata reasons, which means, the developer has to re-submit the same binary with different metadata and wait another few days. This is time consuming for developers.

We have access to the project and can presumably scan for common failures and raise warnings for the most common app rejections, thus saving hours of developer time waiting for reviews that would never pass, and getting people’s app updates out, faster.

### Description

Instead of risking rejection or painstakingly auditing your own metadata, you can now use fastlane precheck to save you the time and hassle. fastlane will review your app for the most common causes of rejection 👍.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Wohohoooo, let's ship it 🚀🚀🚀

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by ohayon — APPROVED** [review]
🚀

**Review by alexsinger — APPROVED** [review]
🚀

**Review by mpirri — APPROVED** [review]

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Pull request merged**
