### PR TITLE
Add "from" to Mailgun action 

### PR DESCRIPTION
**Pull request by 4brunu**
Has discussed https://github.com/fastlane/fastlane/pull/1061, I have create a pull request with all the commits together.

### CODE REVIEW

**Comment by asfalcone** [comment]
@4brunu can you squash these into 1 commit? Thanks!

**Comment by KrauseFx** [comment]
Thanks for your pull request @4brunu, this is a great addition to the existing mailgun integration :+1:

**Comment by KrauseFx** [comment]
@omeryarn was the original author, thanks :+1:

**Comment by 4brunu** [comment]
All the credits go to @omeryarn.

I will create another pull request this time with only one commit.

**Comment by 4brunu** [comment]
I created a new pull request with just one commit.

Sorry for the duplicated pull request, but I couldn't add the single commit to this pull request.

**Comment by KrauseFx** [comment]
Closed with https://github.com/fastlane/fastlane/pull/1092

**Pull request closed without merging**
