### PR TITLE
Freeze mutable objects assigned to constants

### PR DESCRIPTION
**Pull request by mgrebenets**
Automatic fix from rubocop to reduce number of hound error and get closer to green CI.

### CODE REVIEW

**Comment by KrauseFx** [comment]
I'm not 100% sold on this one, as it requires a lot of code change without any clear benefit. Especially things like the `version.rb`. @mfurtak what do you say? Can we disable the `freeze` rule for all repos?

**Comment by mfurtak** [comment]
Hm... I think `freeze` is the right thing to do as far as ruby is concerned.

That said, if we're not ready to keep up with all the new validations being done by **rubocop 0.36.0** I think I agree with your earlier suggestion that we lock that version to **0.35.1** across all repos until we are ready to move forward.

**Comment by mgrebenets** [comment]
So the alternative would #1155. It dramatically reduces number of total warnings for latest `master`.

**Comment by mgrebenets** [comment]
Closing this one wrt #1155. I will try to keep a version with `rubocop` `0.36.0` in sync with master just in case.

**Pull request closed without merging**
