### PR TITLE
[spaceship] Add support for Enterprise Program API

### PR DESCRIPTION
**Pull request by GevaZeichner**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #22205 & #18049

### Description

* Since the new [Enterprise Program API](https://developer.apple.com/documentation/enterpriseprogramapi) closely matches that of the [App Store Connect API](https://developer.apple.com/documentation/appstoreconnectapi), it seems we can just change the API endpoint and token header, depending on the `in_house` optional parameter within the api key.
* Fixed some existing unit tests that failed because `in_house` is now being accessed more times.
* Added tests for the changed APIClient hostname and JWT audience field.

#### Notes
* I'm checking regarding adding more unit tests for the new API itself.
* Found an existing bug if adding the `in_house` value to the api key hash as a String instead of a Bool. Can be fixed in this PR or another.
* Worth considering if to declare some portions of the client API that is not available yet on Enterprise, or to just let it naturally error out until Apple adds more matching APIs. Alternative approach could also be to add a new Client.

### Testing Steps

- Successfully tested so far:
  - Spaceship:
    - Retrieving Enterprise data (certificates, profiles, bundle IDs).
  - Cert:
    -  Creating a new dev certificate
    - I tried also creating a dist certificate and as expected, got "You already have a current" error and couldn't revoke it as it is currently being used by our org.
  - Sigh:
    - Create, download and install provisioning profiles (dev & adhoc & dist).
  - Match:
    - Create dev cert & profile and upload to git.

### CODE REVIEW

**Review by lacostej — APPROVED** [review]
LGTM

Thanks for the contribution :)

**Comment by lacostej** [comment]
> just let it naturally error out until Apple adds more matching APIs.

This is the simplest and more compatible way of doing it. If Apple adds feature, no change on our side, it just works. We adjust only if there are incompatibilities.

**Comment by justindhill** [comment]
I've been waiting for this day since the ASC API was release several years ago! I am so outrageously happy 🥹

**Comment by AStrickland-abbott** [comment]
I"m also very excited to get ride of the crazy build login setup and use a simple auth method. Just curious, but how often are PRs merged and releases made? I feel this one will make all enterprise account holders very happy.

**Comment by GevaZeichner** [comment]
Hi @lacostej thanks for the review! Anything else needed for merging?

**Comment by dxvid-pts** [comment]
This PR enables using the enterprise API for fastlane match: https://github.com/fastlane/fastlane/pull/27460

Has anyone the time to look into this as a follow-up?

**Pull request merged**
