### PR TITLE
Fix encoding error in update_url_schemes fastlane action

### LINKED ISSUE #9301: 'invalid byte sequence in UTF-8' after update_info_plist, update_url_schemes
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

running the actions

```
    update_info_plist(
      plist_path: plist_path,
      display_name: "name"
    )

    update_url_schemes(
      path: plist_path,
      url_schemes: ["test"]
    )
```

changes normal xml plist to bplist and causes the consequence action that related to reading plist file to throw an "invalid byte sequence in UTF-8" error.

### Captured Output

Command Used: `plist_tests`
<details><summary>Output/Log</summary>

```

INFO [2017-05-28 15:08:27.09]: Successfully loaded custom action '/Users/jochen/coden/esanum/iOS/fastlane/actions/get_provisioning_profile_specifier.rb'.
DEBUG [2017-05-28 15:08:27.09]: Checking if there are any plugins that should be loaded...
INFO [2017-05-28 15:08:27.11]: ---------------------------
INFO [2017-05-28 15:08:27.11]: --- Step: opt_out_usage ---
INFO [2017-05-28 15:08:27.11]: ---------------------------
INFO [2017-05-28 15:08:27.11]: Disabled upload of used actions
INFO [2017-05-28 15:08:27.12]: -------------------------------------------------
INFO [2017-05-28 15:08:27.12]: --- Step: Verifying required fastlane version ---
INFO [2017-05-28 15:08:27.12]: -------------------------------------------------
INFO [2017-05-28 15:08:27.12]: Your fastlane version 2.35.1 matches the minimum requirement of 1.97.1  ✅
INFO [2017-05-28 15:08:27.12]: ------------------------------
INFO [2017-05-28 15:08:27.12]: --- Step: default_platform ---
INFO [2017-05-28 15:08:27.12]: ------------------------------
INFO [2017-05-28 15:08:27.12]: Driving the lane 'ios plist_tests' 🚀
INFO [2017-05-28 15:08:27.12]: -------------------------------
INFO [2017-05-28 15:08:27.12]: --- Step: update_info_plist ---
INFO [2017-05-28 15:08:27.12]: -------------------------------
WARN [2017-05-28 15:08:27.55]: Lane Context:
INFO [2017-05-28 15:08:27.55]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios plist_tests"}
ERROR [2017-05-28 15:08:27.55]: invalid byte sequence in UTF-8
INFO [2017-05-28 15:08:27.55]: Successfully generated documentation at path '/Users/jochen/coden/esanum/iOS/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | opt_out_usage       | 0           |
| 2    | Verifying required  | 0           |
|      | fastlane version    |             |
| 3    | default_platform    | 0           |
| 💥   | update_info_plist   | 0           |
+------+---------------------+-------------+

ERROR [2017-05-28 15:08:27.56]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: invalid byte sequence in UTF-8

URL: https://api.github.com/search/issues?q=invalid%20byte%20sequence%20in%20UTF-8+repo:fastlane/fastlane
➡️  fastlane pilot upload crashes with "invalid byte sequence in UTF-8" 
    https://github.com/fastlane/fastlane/issues/9066 [closed] 7 💬
    3 weeks ago

➡️  invalid byte sequence in UTF-8
    https://github.com/fastlane/fastlane/issues/7850 [closed] 11 💬
    6 weeks ago

➡️  UTF-8 issue in deliver
    https://github.com/fastlane/fastlane/issues/8422 [closed] 4 💬
    2 weeks ago

and 19 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20UTF-8&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.5                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.gem/ruby/2.2.5/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.2.5/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# https://github.com/fastlane/fastlane/tree/master/docs
# https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

opt_out_usage
fastlane_version "1.97.1"
default_platform :ios

platform :ios do

  desc "plist tests"
  lane :plist_tests do

    plist_path = "Application Configuration/appConfig-Info.plist"

    update_info_plist(
    plist_path: plist_path,
    display_name: "name"
    )

    update_url_schemes(
    path: plist_path,
    url_schemes: ["test"]
    )

  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.0       |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| CFPropertyList            | 2.3.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| cocoapods-clean           | 0.0.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| xcpretty-travis-formatter | 0.0.4        |
| clamp                     | 0.6.5        |
| colorize                  | 0.8.1        |
| synx                      | 0.2.1        |
</details>

*generated on:* **2017-05-28**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.gem/ruby/2.2.5/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.2.5/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# https://github.com/fastlane/fastlane/tree/master/docs
# https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

opt_out_usage
fastlane_version "1.97.1"
default_platform :ios

platform :ios do

  desc "plist tests"
  lane :plist_tests do

    plist_path = "Application Configuration/appConfig-Info.plist"

    update_info_plist(
    plist_path: plist_path,
    display_name: "name"
    )

    update_url_schemes(
    path: plist_path,
    url_schemes: ["test"]
    )

  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.1.0        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| bundler                   | 1.15.0       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-05-28**
</details>

### PR DESCRIPTION
**Pull request by jjochen**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This fixes https://github.com/fastlane/fastlane/issues/9301
It's the same fix as https://github.com/fastlane/fastlane/pull/7188

### CODE REVIEW

**Comment by jjochen** [comment]
I signed it!

**Review by KrauseFx — APPROVED** [review]
Looks great, thanks for contributing @jjochen, welcome to _fastlane_ 👍

**Comment by KrauseFx** [comment]
The build was failing due to a temporary CircleCI error, I triggered the job again

**Comment by jjochen** [comment]
thank you 👍

**Pull request merged**
