### PR TITLE
[match] Enable importing developer ID certificates

### LINKED ISSUE #16240: Cert type 'developer_id_application' is not supported
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In addition to bug with `fastlane match developer_id` it is impossible even to upload generated certificates and provisioning profiles for `developer_id`.

##### Command executed
`bundle exec fastlane match import`

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
[16:41:13]: Successfully loaded '[REDACTED]/fastlane/Matchfile' 📄

+-------------------+----------------------------------------------------------------------------------------------------------------+
|                                            Detected Values from './fastlane/Matchfile'                                             |
+-------------------+----------------------------------------------------------------------------------------------------------------+
| app_identifier    | [[REDACTED], [REDACTED]]                                                                                       |
| git_url           | [REDACTED]                                                                                                     |
| type              | developer_id                                                                                                   |
| platform          | macos                                                                                                          |
| username          | [REDACTED]                                                                                                     |
| keychain_password | [REDACTED]                                                                                                     |
+-------------------+----------------------------------------------------------------------------------------------------------------+

[16:41:13]: Certificate (.cer) path:
[REDACTED]
[16:41:26]: Private key (.p12) path:
[REDACTED]
[16:41:38]: Provisioning profile (.mobileprovision or .provisionprofile) path or leave empty to skip this file:
[REDACTED]
[16:41:55]: Cloning remote git repo...
[16:41:55]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:41:57]: 🔓  Successfully decrypted certificates repo
[16:41:57]: Repo is at: '/var/folders/92/xjxp368d1sj04vzq_4mj4d280000gp/T/d20200402-15341-2039r1'

[!] Cert type 'developer_id_application' is not supported
```

</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.5                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.5 (19F53f)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)
platform :ios do
  ENV['GIT_TAG_GROUPING'] = "test-builds"
  ENV['MATCH_TYPE'] = "appstore"

  before_all do
    import("lanes/add_tag.rb")
    import("lanes/delete_last_tag.rb")
    import("lanes/notifications.rb")
    import("lanes/update_build_number.rb")
  end

  desc "Send notification to Slack about opened Pull Request with URL to it."
  lane :opened_pr_notification do
    slack(
      message: "New Pull Request is ready for Code Review!",
      success: true,
      channel: ENV['SLACK_CHANNEL'],
      slack_url: ENV['SLACK_URL'],
      payload: {
        "URL" => ENV['PULL_REQUEST_URL']
      },
      default_payloads: [:test_result, :git_author]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Run pod install
    cocoapods(
      use_bundle_exec: true,
      deployment: true,
      try_repo_update_on_error: true
    )

    # Increment build
    update_build_number

    # Create Keychain for Code Signing
    create_keychain(
      name: ENV['MATCH_KEYCHAIN_NAME'],
      password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    # Code Signing using match
    sync_code_signing

    # XCode build app
    build_app(
      workspace: ENV['WORKSPACE'],
      scheme: ENV['SCHEME']
    )

    # Generate the changelog based on your last commits
    changelog_from_git_commits(
      merge_commit_filtering: "exclude_merges"
    )

    # Adding tag
    add_tag

    # Upload to TestFlight
    upload_to_testflight(
      changelog: Actions.lane_context[SharedValues::FL_CHANGELOG]
    )

    # Send a success notification to Slack
    closed_pr_notification
  end

  error do |lane, exception|
    error_notification
    # If build number shared value exists - there where build number change so tag might be created
    if Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
      delete_last_tag
      update_build_number(
        decrease: true
      )
    end
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_IDENTIFIER'] # The bundle identifier of your app
apple_id ENV['APPLE_ID'] # Your Apple email address

itc_team_id ENV['ITC_TEAM_ID'] # App Store Connect Team ID
team_id ENV['TEAM_ID'] # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.144.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.292.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.92.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| faraday                   | 0.17.3       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| memoist                   | 0.16.2       |
| digest-crc                | 0.4.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

### PR DESCRIPTION
**Pull request by addisonwebb**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Resolves #16240

This update allows developer ID certificates to be imported via `fastlane match import`.

### Description
I'm new to the fastlane codebase, but it appears that match tries to be helpful by verifying the certificates you are trying to import are available in the developer portal. It pulls down the certificates and then filters them by the type specified.

Currently, the only certificate types match import will filter with are `development`, `distribution`, and `enterprise` even though match supports `developer_id` certificates ([source](https://github.com/fastlane/fastlane/blob/6527088a3f1daa16fae6a56e18833cac4d757512/match/lib/match/module.rb#L26)).

This change adds `developer_id` as a supported type that import can use to filter results from the developer portal.

### Testing Steps
To see the error that prompted this PR you can apply this patch and then run `bundle exec rspec match`. *The patch just reverts the change to `import.rb` to the current state.*

[original.patch.zip](https://github.com/fastlane/fastlane/files/4389548/original.patch.zip)

I have added a new test that should provide coverage for this use case. You can verify this test passes by running `bundle exec rspec match`.

### CODE REVIEW

**Comment by addisonwebb** [comment]
@googlebot I signed it!

**Comment by addisonwebb** [comment]
Is there anything I need/can to do to help move this forward?

**Review by kbilyk-svitla — APPROVED** [review]
LGTM

**Comment by addisonwebb** [comment]
@joshdholtz Is there anything we an do to help get this reviewed faster? It would be really nice to get this into a release sooner than later.

**Comment by joshdholtz** [comment]
I’m planning on getting this reviewed, merged, and pushed out today! Just hard to focus a lot right now on things with the state of the world 🤷‍♂️

**Comment by addisonwebb** [comment]
Understandable. Thank you!

**Comment by kbilyk-svitla** [comment]
Thank you! This feature is really important for automation of our Project.

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thanks for adding this! Really appreciate the contribution ❤️ And so sorry about the slow times!

**Comment by kbilyk-svitla** [comment]
@addisonwebb I've tested your changes and successfully uploaded developer_id provisioning profiles with certificates but I can't sync them back to the machine that will run CI actions.

When I run the command `bundle exec fastlane match --verbose --readonly` I get:

```
ERROR [2020-04-22 17:07:23.68]: No matching provisioning profiles found for 'Direct_com.***'
ERROR [2020-04-22 17:07:23.68]: A new one cannot be created because you enabled `readonly`
ERROR [2020-04-22 17:07:23.68]: If you are certain that a profile should exist, double-check the recent changes to your match repository
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
```

It seems like match expects some 'Direct_com.***' provisioning profiles and after uploading my I get:

```
certificates/profiles/developer_id_application/Developer_id_application_com.***
```

Moreover if to run command without `--verbose` match will generate some 'Direct_com.***' provisioning profiles at path:

```
certificates/profiles/developer_id/Direct_com.***
```

Please, notice the difference in folders: uploaded are located in `developer_id_application` and generated in `developer_id`.

Unfortunately I can't use generated one as they generates incorrectly for Catalyst app. 

So my hope is on you)

P.S.: @joshdholtz you might be interested also.

**Pull request merged**
