### PR TITLE
Update help text to prefix tool commands with 'fastlane'

### PR DESCRIPTION
**Pull request by mfurtak**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Description

I found a couple places where we're providing commands to run, but we haven't updated to suggest the new `fastlane` prefixed command style

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Before submitting a Pull Request, please create an issue on GitHub to discuss the change. Please add a link to the issue in the PR body.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Before submitting a Pull Request, please create an issue on GitHub to discuss the change. Please add a link to the issue in the PR body.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
That's great! How did you find them? I wonder if we still have some remains of the old way of calling the tools?

**Comment by mfurtak** [comment]
I just noticed them while using some of the tools today during manual testing 😄

**Pull request merged**
