### PR TITLE
[produce] Allow to enable/disable `access_wifi` service

### PR DESCRIPTION
**Pull request by TaimurAyaz**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
iOS 12 added `Access WiFi Information` entitlement. Support for this was added to `spaceship.portal.app_service` but the triggers were not updated. Updating them in this PR.

### Description
Allow produce to enable/disable `access_wifi` service

Added the following options to `produce enable_services`
```
--access-wifi          Enable Access WiFi
```

Added the following options to `produce disable_services`
```
--access-wifi         Disable Access WiFi
```

### CODE REVIEW

**Comment by TaimurAyaz** [comment]
@googlebot I signed it!

**Comment by betko** [comment]
Do you have plan to merge this feature?

**Comment by TaimurAyaz** [comment]
@betko I am waiting on a review.

**Comment by TaimurAyaz** [comment]
Bump

**Review by joshdholtz — DISMISSED** [review]
Thanks for adding these in! Can you also change `AccessWiFi` to `AccessWifi` on https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/app_service.rb#L43?

Right now the current changes fail because they are expecting `Spaceship.app_service.access_wifi`but it is actually `Spaceship.app_service.access_wi_fi` because of the capital `F` on the line of code I linked above. If you change `AccessWiFi` to `AccessWifi` then your code changes will work 😊

**Comment by TaimurAyaz** [comment]
Ah, right. Will do 👍

**Comment by joshdholtz** [comment]
@TaimurAyaz Heyyyy! Are you cool if I add a commit to make this change? 😊

**Comment by TaimurAyaz** [comment]
@joshdholtz go for it :)

**Comment by alexzchut** [comment]
@TaimurAyaz Please update when this feature will be merged. Thanks!

**Comment by alexzchut** [comment]
@TaimurAyaz @joshdholtz Any news on merging this? 
It is new feature being required for example for Chromecast support and currently only way is to enable it manually. If this PR is ready to be merged, please do to finally automate this ability...
Thanks a lot!

**Comment by antoinerabanes** [comment]
bump +1 I am running into this issue too

**Comment by janpio** [comment]
I did make the change. Please review code again.

**Review by joshdholtz — APPROVED** [review]
We can ship this! 🙌

**Pull request merged**
