### PR TITLE
[resign] add full sed path for resign.sh

### PR DESCRIPTION
**Pull request by keith**
If users have gnu-sed from brew in their PATH, these invocations fail
since they used BSD sed specific syntax.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] ~I've updated the documentation if necessary.~

### CODE REVIEW

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This looks great! Would you also be able to add patch notes to the top this file before we merge? 😇

**Comment by keith** [comment]
Done!

**Review by joshdholtz — APPROVED** [review]
Looks good to me! Thanks for the making this fix ❤️

**Comment by keith** [comment]
Thanks!!

**Pull request merged**
