### PR TITLE
Add option to create PushKit cert to PEM

### PR DESCRIPTION
**Pull request by sainttail**
Refer to #6961 

Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

### CODE REVIEW

**Comment by mfurtak** [comment]
@KrauseFx Can you comment on whether you'd like _pem_ to expand to be able to work with this kind of certificate?

**Comment by ohwutup** [comment]
Hey @sainttail! Thanks for the PR! I am going to close this for now as it has been inactive for a while, but please feel free to mention us if you would like this to be reopened when you can revisit the question from @mfurtak and see it through. Thanks again! 🐙 🚀

**Comment by edwardvalentini** [comment]
so is it currently not possible to generate a voip cert with the fastlane tools  -- other than by calling spaceship directly?

**Comment by npomfret** [comment]
Can someone help explain how I can create a voip certificate?

**Comment by hjanuschka** [comment]
@npomfret https://github.com/fastlane/fastlane/issues/7059

**Pull request closed without merging**
