### PR TITLE
Update hockey.rb

### PR DESCRIPTION
**Pull request by overtake**
added optional dsa_signature parameter for sparkle (macOS) updates.

### CODE REVIEW

**Review by asfalcone — CHANGES_REQUESTED** [review]
Could you add a little bit more to the option description? What type of data is the signature? A string of data? A path to a file containing the signature?

**Comment by asfalcone** [comment]
Thanks for the PR @overtake! I added a comment to address before this can be merged. 👍

**Comment by overtake** [comment]
this is string value.

discussion on hockeyapp:

https://support.hockeyapp.net/discussions/problems/55558-please-support-dsa-signing-for-sparkle-updates

**Review by asfalcone — APPROVED** [review]

**Comment by KrauseFx** [comment]
I slightly tweaked the description of the option in a separate PR to not include URLs: https://github.com/fastlane/fastlane/pull/7784

**Pull request merged**
