### PR TITLE
[RFC] Fix recursive directory change when executing actions

### LINKED ISSUE #4715: Actions go down the rabbit hole journey towards root (/)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When an action is run, the current directory is changed to the previous one, and although this gets the desired effect for actions called directly by the Fastfile, this leads to a bad environment when invoked in a nested fashion.

I created an action whose sole purpose is to print the current directory and call a block 

```ruby
module Fastlane
  module Actions
	  
    class PrintPwdAction < Action
      def self.run(params)
	      UI.important(Dir.pwd)
		  params[:block].call()
      end

      def self.description
        "A short description with <= 80 characters of what this action does"
      end
      
      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :block,
                                       is_string: false,
                                       description: 'A block to process plist with custom logic',
                                       optional: true)
        ]
      end

      def self.output
        [
          ['PRINT_PWD_CUSTOM_VALUE', 'A description of what this value contains']
        ]
      end

      def self.return_value
      end

      def self.authors
        ["Your GitHub/Twitter Name"]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
```

Here is the output of 3 nested calls
```
INFO [2016-05-18 16:21:03.42]: -----------------------
INFO [2016-05-18 16:21:03.42]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.42]: -----------------------
WARN [2016-05-18 16:21:03.42]: /Users/dtorres/Projects/MyProject
INFO [2016-05-18 16:21:03.42]: -----------------------
INFO [2016-05-18 16:21:03.42]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.42]: -----------------------
WARN [2016-05-18 16:21:03.42]: /Users/dtorres/Projects
INFO [2016-05-18 16:21:03.43]: -----------------------
INFO [2016-05-18 16:21:03.43]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.43]: -----------------------
WARN [2016-05-18 16:21:03.43]: /Users/dtorres
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

I'm looking into this.

### PR DESCRIPTION
**Pull request by dtorres**
This fixes issue [#4715](https://github.com/fastlane/fastlane/issues/4715)

Considering this is a high impact change I'm posting this as to gather comments and suggestions
## Pending
- [ ] Write tests

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @dtorres, thanks for the pull request and diving into this. It must have been really hard to know how to get started on this.

Unfortunately that's all my fault, when I first built `fastlane` I had a little quirks on the directory in which the actions run: I think the Fastfile runs inside the fastlane folder, but the actions run in the project's root.

Could you add a bit more comments to the source on how you made those decision and why those changes are necessary?

**Comment by KrauseFx** [comment]
This will definitely need some user testing before launching, as these kind of changes usually have a lot of side effects

**Comment by ohwutup** [comment]
Hey @dtorres, just wanted to bump this PR to see if you had a chance to address @KrauseFx's comments above. Thanks! 🐙

**Comment by dtorres** [comment]
@ohwutup I did in the latest commit (78cfb81) I think

**Comment by KrauseFx** [comment]
Hey @dtorres, sorry for not coming back earlier. I gave it some more thought and decided we should hold this off to a later point, maybe to a major release for 2.0. I'll close this PR for now. It's just too risky to change this right now

**Pull request closed without merging**
