### PR TITLE
Add options --skip_downloaded and --skip_uploaded_screenshots

### PR DESCRIPTION
**Pull request by jfresen**
## Add two options to skip uploading or downloading of screenshots

This PR adds two options to deliver:
- --skip_downloaded
- --skip_uploaded_screenshots

See #3747
### --skip_downloaded

The first option should be used in conjunction to --download_screenshots (hence the omission of the word "screenshots" in this option, as it would lead to overly verbose options) and will check if a screenshot exists locally before starting the download. If the file already exists, it will skip the download and output that in the console.
### --skip_uploaded_screenshots

The second option is used when delivering to iTunes Connect. The process of uploading screenshots is modified so it keeps track of all languages whose screenshots have been successfully uploaded. Not supplying the option resets this bookkeeping. When the option is supplied, the screenshots of a language are only uploaded if that language was not previously successfully uploaded, according to the new bookkeeping.

### CODE REVIEW

**Comment by jfresen** [comment]
I fixed the issues found by hound, but I don't know what to do with the errors from CircleCI. What needs to be fixed in order to let the tests pass?

**Comment by asfalcone** [comment]
@jfresen The CI error is this:
```
/lib/deliver/upload_screenshots.rb:127: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
```

**Comment by asfalcone** [comment]
@jfresen Just wanted to ping you again on this. I pasted the error from CI above. Looks like a syntax error!

**Comment by jfresen** [comment]
Hi, I completely missed your comment, sorry for that!
I found the error and fixed it. Stupid really, to have committed 'fixes' without verifying the syntax.

Anyway, it doesn't really matter as it has already been decided that my pull request is superseded by the screenshot sync feature from @lacostej. Is there a reason to still handle this PR, or should it be closed now?

**Comment by KrauseFx** [comment]
@jfresen Good point, having @lacostej's sync feature is probably the cleaner solution :+1:

**Comment by asfalcone** [comment]
Going to close this one up then! Thanks :+1:

**Pull request closed without merging**
