### PR TITLE
Rubocop static code analysis

### PR DESCRIPTION
**Pull request by JaniJegoroff**
**Background**
Rubocop is static code analyser for Ruby that reports problems in the code and suggests good coding practices based on the Ruby Style Guide. See Rubocop project: https://github.com/bbatsov/rubocop

**Motivation**
Currently Rubocop detects **730** offences when `bin` and `lib` folders are analysed. Cleaning up these warnings and agree any custom rules (maybe skip some rules completely) we will benefit
1. Cleaner codebase
2. More unified coding style throughout the project
3. Easier to spot new and fatal offences in the future

**What's implemented in this PR**
1. Added development dependency
2. Added raketask
3. Added initial custom `.rubocop.yml` config file
4. Fixed most of the warnings so that total number of offences are cut down from **730** to **196**

**What's next**
1. Clean up all the rest offences :)
2. Agree which Rubocop rules we don't agree with (we can disable those in config file)
3. How about utilising https://houndci.com to automatically report offences on GitHub PR's?

### CODE REVIEW

**Comment by KrauseFx** [comment]
This is a great pull request, thanks for working on this.

I actually wanted to start using `Rubocop` when starting with [deliver](https://github.com/Krause/deliver).

Some rules seemed a bit odd to me (please correct me, if I'm missing something), for example why not allow to have a `return` statement? Sometimes this makes it more clear, I actually want to return this exact value.



So what do you suggest? Merging and then gradually fixing the missing errors?

**Comment by JaniJegoroff** [comment]
Sounds great, I was also about to start with `deliver` but ended up working with `fastlane` instead at first. I can start `rubocop` clean up activity with `deliver` as well if you don't mind?

In Ruby, `return` statements are allowed but generally speaking they are not needed because the result from last executed statement is returned by default. You should only use explicit returns in case of **early return**. I do agree this can be confusing from time to time. Anyway, we can disable this rule check if needed.

I can open an issue for a discussion about `rubocop` rules we want to customise further or disable completely. I have couple of rules in my mind that I don't completely agree with.

If you agree with fixes then I suggest to merge this PR and we gradually fix rest of the offences.

**Comment by KrauseFx** [comment]
Thank you so much for your great contribution @JaniJegoroff. I'll go over the pull request tomorrow and will look at the enabled rules. 

I guess, once this is fully working and passing for `fastlane`, we could then also enable this for `deliver`, but first, let's see how this works out with `fastlane`.

**Comment by JaniJegoroff** [comment]
Awesome, sounds like a plan.

**Comment by KrauseFx** [comment]
Thank you @JaniJegoroff for providing this great pull request :+1:

**Comment by KrauseFx** [comment]
This resulted in an error:

```
/Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:68:in `sh_no_action': undefined method `exitstatus' for nil:NilClass (NoMethodError)
	from /Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/fast_file.rb:59:in `block in sh'
	from /Users/felixkrause/Developer/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:28:in `execute_action'
```

Fixed with https://github.com/KrauseFx/fastlane/pull/54 thanks to @milch :+1:

**Pull request merged**
