### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by mfurtak**
Changes since release 0.7.1:
- Continuing work on #4841
- Scan: Added option to generate the json compilation database with clang naming conventions (#4841)
- Enabled fastlane plugins for all the tools (#4941)

### CODE REVIEW

**Comment by asfalcone** [comment]
👍

**Comment by KrauseFx** [comment]
👍

**Comment by KrauseFx** [comment]
When providing the changelog for the tools, don't mention `Enabled fastlane plugins for all the tools (#4941)`, as it's not user facing. This is just necessary for deploying the tool

**Comment by KrauseFx** [comment]
Also `Continuing work on #4841` should be an actual changelog 👍

**Pull request merged**
