### PR TITLE
Retry 'xcodebuild -showBuildSettings' as it may hang with Xcode 7.3

### LINKED ISSUE #4059: Scan hangs when getting build settings
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Scan hangs when getting the build settings:

```
xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
```

A couple things to note:
 - I thought that it was related to https://github.com/fastlane/fastlane/issues/1844 since it was the last command showing up in the logs, but after looking at the stacktrace when I force quite `fastlane`, it seems that it's actually hanging on `showBuildSettings`.
 - I can reproduce the freeze by running the `-showBuildSettings` command manually, though it only happens one time out of five, something like that.
 - It happens consistently when running in a CI environment (circleci 7.3)
 - It started happening after I removed all files in the App target from the AppTests target. Instead, I now have `@testable import App` everywhere. This change required to modify my Podfile to have different pods for the AppTests target (see below)
 - DerivedData is relative to my project directory.

##### Complete output when running fastlane, including the stack trace and command used

Please note that I modified fastlane_core's sources to show the build settings command, which is why it shows up in the logs. If I hadn't, only the `-list` command would appear.

```
ldiqual@ldiqual-mbp ~/S/App-ios-test1> bundle exec fastlane test --verbose
/Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
INFO [2016-04-04 15:18:48.74]: ---------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: opt_out_usage ---
INFO [2016-04-04 15:18:48.74]: ---------------------------
INFO [2016-04-04 15:18:48.74]: Disabled upload of used actions
INFO [2016-04-04 15:18:48.74]: -------------------------------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: Verifying required fastlane version ---
INFO [2016-04-04 15:18:48.74]: -------------------------------------------------
INFO [2016-04-04 15:18:48.74]: fastlane version valid
INFO [2016-04-04 15:18:48.74]: ------------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: default_platform ---
INFO [2016-04-04 15:18:48.74]: ------------------------------
INFO [2016-04-04 15:18:48.91]: Driving the lane 'ios test' 🚀
INFO [2016-04-04 15:18:48.91]: ------------------
INFO [2016-04-04 15:18:48.91]: --- Step: scan ---
INFO [2016-04-04 15:18:48.91]: ------------------
WARN [2016-04-04 15:18:48.93]: xcrun xcodebuild -list -workspace './App.xcworkspace'
2016-04-04 15:18:50.261 xcodebuild[94625:3349109] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:18:50.265 xcodebuild[94625:3349109] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2016-04-04 15:18:51.94]: $ xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
2016-04-04 15:18:52.174 xcodebuild[94629:3349189] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:18:52.176 xcodebuild[94629:3349189] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
^C/Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/helper.rb:51:in ``': Interrupt
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/helper.rb:51:in `backticks'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:203:in `build_settings'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:168:in `mac?'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:180:in `ios?'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/detect_values.rb:23:in `set_additional_default_values'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan.rb:27:in `config='
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/manager.rb:4:in `work'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/actions/scan.rb:10:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:16:in `block (2 levels) in parsing_binding'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
    from /Users/ldiqual/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
    from /Users/ldiqual/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'
```

```
ldiqual@ldiqual-mbp ~/S/App-ios-test1> xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
2016-04-04 15:31:51.235 xcodebuild[94673:3360581] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:31:51.238 xcodebuild[94673:3360581] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Build settings for action build and target AppTests:
```

Note that the command above doesn't exit (1 time out of 5), I have to force kill it.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
opt_out_usage
fastlane_version "1.49.0"
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(scheme: "AppTests")
  end
end
```

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Common' do

    target 'App'

    target 'AppTests' do
        pod 'SomePod'
    end

    pod 'SomeOtherPod'
end
```

### Environment

fastlane 1.70.0
Bundler + rbenv
ruby 2.3.0
xcode 7.3
cocoapods 1.0.0.beta.6

### PR DESCRIPTION
**Pull request by ileitch**
Fixes #4059

### CODE REVIEW

**Comment by asfalcone** [comment]
@ileitch Thanks for the PR. Unfortunately we're not able to accept this PR because it breaks backward compatibility and changes the underlying behavior for all of the tools. This isn't the type of change that we'd like to introduce with investment and testing from the core team. 

We appreciate what you're trying to do to work around issues that many people are having with `xcodebuild` but we aren't able to address those inside of `fastlane`. 👍

**Comment by ileitch** [comment]
> because it breaks backward compatibility
`Helper.backticks` is a public API?

> and changes the underlying behavior for all of the tools
Notice that backticks are still used when `timeout: false`, the behavior only changed for one command.

**Comment by fcy** [comment]
> We appreciate what you're trying to do to work around issues that many people are having with `xcodebuild` but we aren't able to address those inside of `fastlane`.

This sounds like #4059 is a Won't Fix kinda issue. Which is "fine" but saying that Fastlane won't fix Xcode problems contradicts the tool, for example `scan` uses these two items as reasons to use it:

>:mag:	Xcode duplicated your simulators again? scan will handle this for you
>
>:book:	Helps you resolve common test errors like simulator not responding

These are Xcode problems that are handled inside Fastlane.

---

Would be nice to have an official position on what approach the team thinks is acceptable: ignoring the Xcode problem, timing out so the Fastlane doesn't hang forever (not a Xcode problem), or timeout + auto-retry.

**Comment by asfalcone** [comment]
@ileitch yes `Helper.backticks` is a public API as it is used in many fastlane tools which are separate gems and don't have an upper bound on their version dependency on`fastlane_core`. If this change was made and a new version of `fastlane_core` was deployed, people who updated would have broken tools 😢 

I totally get that the behavior isn't changed for all tools, but a code change this large does have the possibility to have unintended effects, especially where this code doesn't have tests.

@fcy This is a fair point, thank you for highlighting the inconsistency in our messaging. We're trying do better to be more clear about what kind of PRs we're willing to accept. 

We'll update the linked issue if we can figure out a strategy for addressing the problem with xcodebuild + `scan` that isolates the impact but gets people working consistently 💯  Thanks for the input and trying to make fastlane the best 🚀

**Comment by ileitch** [comment]
> if we can figure out a strategy for addressing the problem with xcodebuild + scan that isolates the impact but gets people working consistently

What if we simply didn't change `Helper.backticks`, and add this new command as private method, only for use in this one spot?

A timeout is also [used for another command in the same file](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/project.rb#L287-L290), however it uses `Timeout.timeout` which is inferior to the approach I've implemented when executing shell commands.

**Comment by ileitch** [comment]
@asfalcone: ping. Is the approach mentioned above acceptable?

**Comment by asfalcone** [comment]
@ileitch Thanks for the ping. We're actively working to resolve this issue https://github.com/fastlane/fastlane/issues/3921 which I believe hangs for the same or similar reason (thanks xcodebuild!!). We'd like to try to resolve this first and see if the same solution will fix the hang when executing `scan`. If we're not able to do that, we'll let you know and would be happy to review a PR that introduced the timeout and retry behavior local only to `scan`. Stay tuned to that issue for updates and we'll let you know how to proceed shortly!

**Comment by ileitch** [comment]
@asfalcone so #3921 looks unrelated to me

**Comment by fcy** [comment]
Would be nice to have more discussion here. I'm using this PR instead of the current fastlane for almost 2 months now.

**Pull request closed without merging**
