### PR TITLE
Fixed set_github_release when no commitish is provided

### PR DESCRIPTION
**Pull request by czechboy0**
Sorry about that, @KrauseFx. I thought I tested it back when I created it (or maybe GitHub changed behavior when an invalid commitish is provided). Anyway - it's fixed.

### CODE REVIEW

**Comment by czechboy0** [comment]
Fixes #575.

**Comment by KrauseFx** [comment]
Thanks for the pull request @czechboy0. The tests need to be updated :+1:

**Comment by czechboy0** [comment]
:eyes: @ that now

**Comment by czechboy0** [comment]
Btw Ruby 2.2.3 doesn't like running fastlane test for some reason. Have you seen this? (Downgrading locally to 2.2.2) @KrauseFx

**Comment by KrauseFx** [comment]
@czechboy0 Thanks, I'll check it out on 2.2.3.

**Comment by czechboy0** [comment]
Seems to happen to me on 2.2.2 as well, something about json 1.8.3, I'll look at it :/ Anyway, this PR is ready.

**Comment by KrauseFx** [comment]
Thanks :rocket:

**Pull request merged**
