### PR TITLE
[match] Add bearer authentication support for git

### PR DESCRIPTION
**Pull request by vascofg**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
In Azure Devops, to authenticate with a repository that belongs to the same Project as the currently running build, you need to specify a bearer token for authorization.
More info here: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#authorize-access-to-your-repositories

### Description
This PR adds a new parameter called `git_bearer_authorization`, similar to `git_basic_authorization`, and uses it to add the header to git's request.

### CODE REVIEW

**Comment by vascofg** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
Looks good to me.

The Swift changes would not have been necessary, these files will be auto generated on release.

Could you maybe add an example to the list of examples for the actions so people know how to use it or at least add it here as a comment?

**Comment by vascofg** [comment]
Added an example

**Review by thejohnlima — APPROVED** [review]

**Review by joshdholtz — APPROVED** [review]
Thanks for adding this! I added a few commits onto here. I added conflicting values for `git_basic_authorization` and `git_bearer_authorization` options since one would override the other in the code 😊 Really appreciate the contribution ❤️

**Pull request merged**
