### PR TITLE
[frameit] look for title.strings in parent folders

### PR DESCRIPTION
**Pull request by RobertSasak**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fix issue https://github.com/fastlane/fastlane/issues/16629
Frameit recent updat also support Android. Which is awesome! But there still bit of hassle to setup it correctly along side iOS screenshots. On iOS all screenshots per language are in a flat structure. All screenshots are in one folder. However on Android screenshots for one language are separated into several folders such as phoneScreenshots, sevenInchScreenshots and tenInchScreenshots. And those folders are already under folder images.

Frameit expect title.strings and keyword.strings to live in the same folder as all screenshots.
https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/editor.rb#L500

### Description
In addition to look for title.strings and keyword.strings in the screenshot folder, script also looks into parent folders.

### CODE REVIEW

**Review by janpio — COMMENTED** [review]
We should probably add a test for this - but there might not be tests for this functionality at all?

**Comment by RobertSasak** [comment]
I was afraid of this. I have no no idea how to write a single line in Ruby. Is there a test that is somehow similar?

**Comment by janpio** [comment]
Unfortunately not. The tests would probably go into https://github.com/fastlane/fastlane/blob/master/frameit/spec/editor_spec.rb, simulate different file structures (one for iOS, one for Android) and then show how the file is correctly picked up by `fetch_text` to be returned.

**Comment by joshdholtz** [comment]
I'll take a stab and add tests for this today 😊

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by joshdholtz** [comment]
@RobertSasak @janpio I added tests onto this if either of you would like to review!

**Review by RobertSasak — COMMENTED** [review]
What is the purpose of these two files?
frameit/spec/fixtures/editor/android/apostrophes.png
frameit/spec/fixtures/editor/android/en-US/images/featureGraphic.png

**Comment by joshdholtz** [comment]
@RobertSasak Great question! Nothing lol... I forgot to delete those 😊

**Review by janpio — APPROVED** [review]
Tests are good.

**Review by RobertSasak — COMMENTED** [review]
@joshdholtz Excelent job! Thank you for stepping in.

**Review by joshdholtz — APPROVED** [review]
Thanks for making this fix! I’m happy that we are getting better Android support for `frameit` now ❤️ Appreciate the contribution!

**Pull request merged**
