### PR TITLE
[match][sigh] fix access to certs installed by fastlane tools for productsign command for macOS

### PR DESCRIPTION
**Pull request by DuMaM**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This allows for MacOS CI to run without need of any user action from GUI.

### Description
Signing MacOS in CI right now is impossible when somebody is using match or sigh for cert management.
I'm looking for official documentation, where the process is well described, but for now this will do the job. 
https://www.hexnode.com/mobile-device-management/help/how-to-sign-macos-pkg-files-for-deployment-with-hexnode-mdm/

When somebody will follow those steps, now it will fail on `productsign` command.
Instead of using certs from keychain, user will see password prompt in GUI (even though all certs are added to be `accessible for all`), until password will not be correct command will fail.

### Testing Steps
1. Create new keychain
2. Pull any cert with `match` for appstore (Apple Distribution) with option `additional_cert_types: mac_installer_distribution`
3. This should install two certs it's recommended to enable `--verbose` during lane run to see how import behaves.
4. Execute `xcrun productsign --keychain <new_keychain> --sing <Installer_Cert_From_Match> unsigned.pkg signed.pkg`

### CODE REVIEW

**Comment by DuMaM** [comment]
It's ready to merge.

**Comment by DuMaM** [comment]
@getaaron Could you also review this one?

**Comment by getaaron** [comment]
@DuMaM this LGTM but the CircleCI builds didn't run, can you [connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) and rerun the build? (you should see ~11 checks passed instead of 2 if it worked)

**Review by getaaron — APPROVED** [review]
approved to merge pending CI

**Comment by DuMaM** [comment]
Thanks for merging it 👍 
It really helps me and I hope also for other users 😉

**Pull request merged**
