### PR TITLE
Fix broken link in code comments

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Nice catch, using web archive is a nice idea 👍

**Comment by revolter** [comment]
Yep, safest bet 😄

**Comment by KrauseFx** [comment]
Hey @revolter, thanks for all your recent contributions, I just sent you an invite to our fastlane slack to the email address on your profile 👍

**Comment by revolter** [comment]
@KrauseFx, Could you sent it to a3e9ffc4@opayq.com instead please? 😄

**Pull request merged**
