### PR TITLE
Fixes #1634 - Device Locale Not Changed to Match Language

### LINKED ISSUE #1634: Issue with launch_arguments
<table>
      <tr>
        <td>
          
        </td>
        <td>
          Original issue by @tache - Imported from <a href='https://github.com/fastlane/snapshot/issues/480'>fastlane/snapshot#480</a>
        </td>
      </tr>
    </table>

Using `snapshot 1.11.0` I am either having a user issue with configuration, it does not work the way I think it should, or it is broke.

I have the following in my Snapfile:
```
launch_arguments([ "-adsDisabled YES" ])
```

In my Swift `XCTestCase` I have  
```
...
    let app = XCUIApplication()
    
    override func setUp() {
        super.setUp()
        setupSnapshot(app)
        app.launch()
    }
...
```

In my view controller of the app target, I have 
```
let FASTLANE_SNAPSHOT = NSUserDefaults.standardUserDefaults().boolForKey("FASTLANE_SNAPSHOT")
let ADS_DISABLED = NSUserDefaults.standardUserDefaults().boolForKey("adsDisabled")
```

when running `snapshot --verbose`, I do not see either as being set. 

When I add the following in the view controller, and then check out the `~/Library/Logs/snapshot/<app>.log`, I do not see either of the key/pairs set.  
```
print(NSUserDefaults.standardUserDefaults().dictionaryRepresentation());
```

### PR DESCRIPTION
**Pull request by st3fan**
This is a patch for issue #1643 - _Device Locale Not Changed to Match Language_.

As a result, the following will now work in the Simulator:
- The whole OS is now running in the correct locale, so that system dialogs and UI will appear correctly. This includes things like permission dialogs, but also the Share Menu or Default toolbar buttons like `.Cancel`.
- The status bar changes properly
- `WKWebView` and `UIWebView` will now send a proper `Accept-Languages` header, which will result in sites more correctly displaying (or redirecting to) a version with the chosen locale.

It adds a `--localize-simulator` option to `snapshot`, which will then configure the Simulator to use the chosen language.

Note that `--localize_simulator` implies `--erase_simulator`. This is needed because you cannot change the locale without fully resetting the Simulator. (Needs to be verified, but I could not get it to work reliably without a reset)

Example output at https://people.mozilla.org/~sarentz/t/SnapshotIssue1643/screenshots.html which shows the following:
- For locales natively supported by iOS, the status bar changes accordingly
- You can see that the locale is now correctly passed to the WKWebView and that mozilla.org redirects to the localized sub-site. (This does not work for all because mozilla.org is not localized to all the languages i threw at it, but it is still a pretty good indication of how this works in practice)

### CODE REVIEW

**Comment by Chaosspeeder** [comment]
Thank you. Testing your solution. Could give you feedback tonight (German time). greetings and thank you for your work.

**Comment by st3fan** [comment]
@Chaosspeeder Great. Let me know how I can help. Would be good to have a second person succesfully using this patch!

**Comment by Chaosspeeder** [comment]
@st3fan. I have bad news. For my purposes your solution doesn't work. And I have no idea why the problems with iOS check spelling persists. 

You can see on the screenshot the somewhat strange red lines from iOS check spelling. I have the problem only in the first UI test and only in english. I develop an a german machine. But the status bar is fine and shows that your switch is working. I've got an english "Carrier" indicator and english time (7:12 AM). 

bildschirmfoto 2016-04-22 um 19 49 55

**Comment by mfurtak** [comment]
Awesome. Thanks for this @st3fan! 🚀

**Pull request merged**
