### PR TITLE
[match] remove redundant fetching of profile devices and certificates

### PR DESCRIPTION
**Pull request by nekrich**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
match is slow when running in edit mode. I found out that when the match checks device count and development certificates validity. match downloads a provisioning profile from the portal with devices and certificates payload and additionally sends two more requests to the portal to fetch devices and certificates once again. There is no need to fetch remote info twice.

### Description
Changes allow match to use devices & certificates info from the first request from the received provisioning profile. As a result, the are 2x decrease in requests sent to App Store Connect API when checking if the provisioning profile must be updated.

### Testing Steps
run match.

### CODE REVIEW

**Comment by nekrich** [comment]
@rogerluan , can you please look at this PR?

**Review by rogerluan — APPROVED** [review]
I also thought we had to fetch them again initially, but after reviewing the code better, this makes total sense to me!

However, since this is a critical part of `match`, I'll leave it for @joshdholtz to review it whenever he has some time, since he's the one who implemented this originally 🙇

**Comment by rogerluan** [comment]
Really nice catch btw @nekrich ! Thanks for this PR! 🙌

**Comment by nekrich** [comment]
Waited so long, and missed release. @joshdholtz , please review 🙏

**Comment by rogerluan** [comment]
That's a really good question @getaaron  🤔 after analyzing the code it looks like it was just forgotten? Because it even has an entry in `attr_mapping`.

From code review alone it looks like this code would even crash due to lack of `devices` accessor, idk how this is actually working in real-life tests (in the unit test is understandable why it works, since we're mocking the accessor…).

Could you confirm whether that's the expected behavior or if there's an accessor missing, @nekrich ?

**Comment by nekrich** [comment]
@rogerluan Looks likes it's missing 🤔.

**Comment by nekrich** [comment]
Added the accessor, waiting for tests.

**Comment by nekrich** [comment]
Some tests failed, but I don't see any relationship with the changes I've made 🤔.

**Comment by rogerluan** [comment]
CI seems to have broke due to CircleCI's deprecation:

image

I'm taking a look at this now

**Comment by rogerluan** [comment]
Oh, this PR just needs rebasing from master @nekrich, would you do that for us? 🙏

**Comment by nekrich** [comment]
@rogerluan , @getaaron, sorry for the delay. I've just rebased my branch 🤞.

**Comment by nekrich** [comment]
@rogerluan , @getaaron, sorry for the delay. I've just rebased my branch 🤞.

**Comment by rogerluan** [comment]
CI was failing, I just triggered it again to see if it was a flaky test.

**Review by getaaron — APPROVED** [review]
Tests look good. Thanks for the PR!

**Pull request merged**
