### PR TITLE
[WIP] [deliver] Adding in platform support for deliver

### PR DESCRIPTION
**Pull request by bassrock**
This is a WIP at the moment to add platform support to deliver.

This is dependent on #4447 and may need even more changes as well on that pull request.

### CODE REVIEW

**Comment by bassrock** [comment]
Closing this as it depends on items from #3825

**Comment by mpirri** [comment]
:+1: This looks good and we can merge it once #4781 is merged.

**Comment by KrauseFx** [comment]
@mpirri This is #4781 😉

**Comment by nonnname** [comment]
Somebody now when whe tvOS support will come? :)

**Comment by mpirri** [comment]
@nonnname Sorry for delay, will look into this shortly.

**Comment by mpirri** [comment]
@bassrock Can you rebase this from `master` so that we can merge this as soon as #4447 is merged?  Thanks!

**Comment by bassrock** [comment]
@mpirri Rebased!

**Review by mpirri — APPROVED** [review]

**Pull request merged**
