### PR TITLE
Support for updating roles on iTunes Connect members

### PR DESCRIPTION
**Pull request by MortenGregersen**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Spaceship has support for creating new members in iTunes Connect, but once they are created, you can change the roles. We want to use fastlane/spaceship to set the 'App Manager' role on some members on multiple accounts temporary and revoke it afterwards.
I've tested this with my local branch as a local gem in Gemfile. I've changed the roles on our members from 'Developer' and 'Finance' to 'App Manager' and 'Finance' and back.

### Description
This change adds support for updating the roles of a member. The given member object isn't updated. A new request to get the member is required to get an updated list of roles.

### CODE REVIEW

**Comment by MortenGregersen** [comment]
I signed it!

**Comment by KrauseFx** [comment]
That's awesome, thanks for the PR. Should we add some docs also to `DeveloperPortal.md`? Also it seems like the Google CLA bot isn't happy, because the git commit seems to not be associated with your username? Could you confirm that the code change is from you, and that you agree with the CLA? :) 
Thanks

**Comment by MortenGregersen** [comment]
D'oh! I used the wrong mail address when I made the commit. I don't want to have this merged with this mail address. I will create a new pull request with the same commit but with my github mail address.

I will reference it here when the pull request is ready.

**Comment by KrauseFx** [comment]
Alright, perfect, thanks 👍

**Comment by MortenGregersen** [comment]
I've created a new pull request with the right mail address: #10257

**Pull request closed without merging**
