### PR TITLE
[fastlane_core] PkgUploadPackageBuilder accepts platform parameter.

### LINKED ISSUE #7772: Can't send pkg to iTC
```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/pkg_upload_package_builder.rb:10:in `generate': [!] unknown keyword: platform (ArgumentError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.5.0/deliver/lib/deliver/runner.rb:93:in `upload_binary'
```

If you look into [runner.rb](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/runner.rb) and then into [pkg_upload_package_builder.rb](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/pkg_upload_package_builder.rb) you'll imedietely see that the generate(...) doesn't take the mentioned in the error platform keyword.

Of course tested on newest fastlane 2.5.0

### PR DESCRIPTION
**Pull request by hjanuschka**
Should fix #7772, thx to @masteranza for detailed problem explanation

### CODE REVIEW

**Comment by KrauseFx** [comment]
Were you able to reproduce the issue first, and then worked on the fix? 👍

**Comment by masteranza** [comment]
Works now! Thanks @hjanuschka

**Comment by hjanuschka** [comment]
didnt test - but error msg + fix seems logic - wanted to wait for one of the reporters to verify, and @masteranza already confirmed and closed issue 🙃

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Awesome, thanks, this will be in the next release 👍

**Pull request merged**
