### PR TITLE
Fastlane sh with log set to false should respect a step name

### LINKED ISSUE #22072: 🐛 Fastlane `sh` with `log:false` replacing `step_name` to `Step: shell command` instead of step_name parameter
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently, everytime I passing `log:false` into `sh` actions, the `step_name` didn't show the message I've set

example lane:

```ruby
desc 'Listing Directory'
lane:wakwaw do |options|
  sh(
    "ls",
    step_name:"\e[1;94mList current directory\e[0m"
  )
end
```

showing output:

```
Driving the lane 'wakwaw' 🚀
-----------------------------------------------
--- Step: List current directory ---
-----------------------------------------------
$ ls
**List of directory in cwd**
fastlane.tools finished successfully 🎉
```

but when I add `log:false` like this:

```ruby
desc 'Listing Directory'
lane:wakwaw do |options|
  sh(
    "ls",
    step_name:"\e[1;94mList current directory\e[0m",
    log:false
  )
end
```

the output of Step name seems to use default value `Step: shell command`

```bash
Driving the lane 'wakwaw' 🚀
---------------------------
--- Step: shell command ---
---------------------------
fastlane.tools finished successfully 🎉
```

I expecting the Step name output should use `step_name` value even when the `log` parameter is passed.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Description

Fastlane sh with log set to false should respect a step name. 

### Testing Steps

The lane: 

```ruby
sh("ls", log: false, step_name: "list files")
```

Before 😭 

Screenshot 2024-07-20 at 12 35 42

After 🎉 

Screenshot 2024-07-20 at 12 35 31

### CODE REVIEW

**Comment by mollyIV** [comment]
The error seems to be unrelated to the changes introduced in this PR. Can somebody from `fastlane` team help here please? 🙏 

```
RubyGems system software updated
Fetching bundler-2.3.21.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Users/distiller/.rbenv/versions/3.2.2/bin/bundle.lock directory.
```

**Comment by mollyIV** [comment]
FYI, the CI tests failures have been resolved by pulling the fixes from the main branch.

**Review by giginet — APPROVED** [review]
🚀

**Comment by giginet** [comment]
Running AppVeyor job is flaky. It may be fixed with a rerun. However, I don't have permission to execute the job 🤷

**Pull request merged**
