### PR TITLE
Added support for customising username and icon url for slack posts

### PR DESCRIPTION
**Pull request by ghost**
I thought it might be a nice addition to add more customisation to Slack actions. This commit lets you customise the username and icon used for Slack posts, defaulting to the current behaviour if nothing is specified.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great to me, thanks. Could you squash the commits to one? Thanks for contributing to fastlane :+1:

**Comment by KrauseFx** [comment]
Leave a quick comment after you're ready so that I get a notification :+1:

**Comment by lyptt** [comment]
Sure! That should be done now

**Comment by KrauseFx** [comment]
This is perfect, thank you so much for your contribution :+1:

**Comment by lyptt** [comment]
No problem, glad to help!

**Pull request merged**
