### PR TITLE
[supply] add an option to change the release status of a promoted track

### LINKED ISSUE #19511: changes_not_sent_for_review = true unexpectedly sends to review automatically after promoting to production
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I want to promote our build on Google Play from the internal track to the production track. Currently the build will be submitted to review automatically.

However, I want the build on the promote track in a state where I still need to go to the Google Play Console and send it to review manually so that I have more control over the final step before I need to release the version. Right now, after it has been reviewed, the version must be released before another version can be promoted to the production track.

##### Command executed
```
bundle exec fastlane android promoteVersion --env store version:[***]
```

##### Complete output when running fastlane, including the stack trace and command used
<details><summary>Output</summary>

```
11:37:31  [11:37:31]: Loading from './fastlane/.env.store'
11:37:32  +----------------------------+---------+---------------------------------------------------------------------------+
11:37:32  |                                                   Used plugins                                                   |
11:37:32  +----------------------------+---------+---------------------------------------------------------------------------+
11:37:32  | Plugin                     | Version | Action                                                                    |
11:37:32  +----------------------------+---------+---------------------------------------------------------------------------+
11:37:32  | fastlane-plugin-badge      | 1.4.0   | add_badge                                                                 |
11:37:32  | fastlane-plugin-appcenter  | 1.11.0  | appcenter_fetch_version_number, appcenter_fetch_devices, appcenter_upload |
11:37:32  | fastlane-plugin-bundletool | 1.0.3   | bundletool                                                                |
11:37:32  +----------------------------+---------+---------------------------------------------------------------------------+
11:37:32  
11:37:33  [11:37:32]: ----------------------------------------
11:37:33  [11:37:32]: --- Step: Verifying fastlane version ---
11:37:33  [11:37:32]: ----------------------------------------
11:37:33  [11:37:32]: Your fastlane version 2.195.0 matches the minimum requirement of 2.189.0  ✅
11:37:33  [11:37:32]: ------------------------------
11:37:33  [11:37:32]: --- Step: default_platform ---
11:37:33  [11:37:32]: ------------------------------
11:37:33  [11:37:32]: Driving the lane 'android promoteVersion' 🚀
11:37:33  [11:37:32]: ---------------------------
11:37:33  [11:37:32]: --- Step: shell command ---
11:37:33  [11:37:32]: ---------------------------
11:37:33  [11:37:32]: ---------------------------------------
11:37:33  [11:37:32]: --- Step: git rev-list --count HEAD ---
11:37:33  [11:37:32]: ---------------------------------------
11:37:33  [11:37:32]: $ git rev-list --count HEAD
11:37:33  [11:37:32]: ▸ 17400
11:37:33  [11:37:32]: -------------------
11:37:33  [11:37:32]: --- Step: is_ci ---
11:37:33  [11:37:32]: -------------------
11:37:33  [11:37:32]: WORKSPACE or UNITY_RELATIVE_PROJECT_PATH isn't defined, but is required for anything related to unity.
11:37:33  [11:37:32]: -----------------------------
11:37:33  [11:37:32]: --- Step: last_git_commit ---
11:37:33  [11:37:32]: -----------------------------
11:37:33  [11:37:33]: --------------------
11:37:33  [11:37:33]: --- Step: supply ---
11:37:33  [11:37:33]: --------------------
11:37:33  
11:37:33  +------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
11:37:33  |                                                                                     Summary for supply 2.195.0                                                                                     |
11:37:33  +------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
11:37:33  | skip_upload_apk                    | true                                                                                                                                                          |
11:37:33  | skip_upload_aab                    | true                                                                                                                                                          |
11:37:33  | skip_upload_metadata               | true                                                                                                                                                          |
11:37:33  | skip_upload_changelogs             | true                                                                                                                                                          |
11:37:33  | skip_upload_images                 | true                                                                                                                                                          |
11:37:33  | skip_upload_screenshots            | true                                                                                                                                                          |
11:37:33  | changes_not_sent_for_review        | true                                                                                                                                                          |
11:37:33  | package_name                       | [****]                                                                                                                                  |
11:37:33  | version_code                       | [****]                                                                                                                                                       |
11:37:33  | track                              | internal                                                                                                                                                      |
11:37:33  | track_promote_to                   | production                                                                                                                                                    |
11:37:33  | json_key                           | [****] |
11:37:33  | release_status                     | completed                                                                                                                                                     |
11:37:33  | validate_only                      | false                                                                                                                                                         |
11:37:33  | check_superseded_tracks            | false                                                                                                                                                         |
11:37:33  | timeout                            | 300                                                                                                                                                           |
11:37:33  | deactivate_on_promote              | true                                                                                                                                                          |
11:37:33  | rescue_changes_not_sent_for_review | true                                                                                                                                                          |
11:37:33  | ack_bundle_installation_warning    | false                                                                                                                                                         |
11:37:33  +------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
11:37:33  
11:37:36  [11:37:35]: Uploading all changes to Google Play...
11:37:38  [11:37:38]: Successfully finished the upload to Google Play
11:37:38  
11:37:38  +------+----------------------------+-------------+
11:37:38  |                fastlane summary                 |
11:37:38  +------+----------------------------+-------------+
11:37:38  | Step | Action                     | Time (in s) |
11:37:38  +------+----------------------------+-------------+
11:37:38  | 1    | Verifying fastlane version | 0           |
11:37:38  | 2    | default_platform           | 0           |
11:37:38  | 3    | shell command              | 0           |
11:37:38  | 4    | git rev-list --count HEAD  | 0           |
11:37:38  | 5    | is_ci                      | 0           |
11:37:38  | 6    | last_git_commit            | 0           |
11:37:38  | 7    | supply                     | 5           |
11:37:38  +------+----------------------------+-------------+
11:37:38  
11:37:38  +------------+--------------+----------------+
11:37:38  |          Plugin updates available          |
11:37:38  +------------+--------------+----------------+
11:37:38  | Plugin     | Your Version | Latest Version |
11:37:38  +------------+--------------+----------------+
11:37:38  | badge      | 1.4.0        | 1.5.0          |
11:37:38  | appcenter  | 1.11.0       | 1.11.1         |
11:37:38  | bundletool | 1.0.3        | 1.0.4          |
11:37:38  +------------+--------------+----------------+
11:37:38  [11:37:38]: To update all plugins, just run
11:37:38  [11:37:38]: $ bundle exec fastlane update_plugins
11:37:38  
11:37:38  [11:37:38]: fastlane.tools finished successfully 🎉
11:37:38  
11:37:38  #######################################################################
11:37:38  # fastlane 2.196.0 is available. You are on 2.195.0.
11:37:38  # You should use the latest version.
11:37:38  # Please update using `bundle update fastlane`.
11:37:38  #######################################################################`
```

</details>

Notice that `changes_not_sent_for_review` is set to `true`. Not sure if I'm misunderstanding the documentation here. I expected that this should be the flag that prevents the build from being submitted for review automatically.

I looked at these lines of code:
[uploader.rb#L199](https://github.com/fastlane/fastlane/blob/52191dfd2171f4614f288e9c33625e5ccb9377dd/supply/lib/supply/uploader.rb#L199)

I wonder if there needs to be a check against `changes_not_sent_for_review` which sets the `release.status` to `DRAFT`

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                                                                   |
| --------------------------- | ----------------------------------------------------------------------------------------------------------------------- |
| OS                          | 11.6                                                                                                                    |
| Ruby                        | 2.7.0                                                                                                                   |
| Bundler?                    | true                                                                                                                    |
| Git                         | git version 2.30.1 (Apple Git-130)                                                                                      |
| Installation Source         | ~/path/to/installation/source/bundle/ruby/2.7.0/bin/fastlane |
| Host                        | macOS 11.6 (20G165)                                                                                                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.0/lib                                                                                        |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                                                                                             |
| Is contained                | false                                                                                                                   |
| Is homebrew                 | false                                                                                                                   |
| Is installed via Fabric.app | false                                                                                                                   |
| Xcode Path                  | /Applications/Xcode-13.app/Contents/Developer/                                                                          |
| Xcode Version               | 13.0                                                                                                                    |
| Swift Version               | 5.5                                                                                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>Fastfile snippet</summary>

```ruby
	desc "Promote a version to production"
    	lane :promoteVersion do |options|
    		UI.user_error!("Version has to be specified with version:<version>") unless options[:version]

		    promoteTrack = "production"

    		supply(
    			skip_upload_apk: true,
					skip_upload_aab: true,
					skip_upload_metadata: true,
					skip_upload_changelogs: true,
					skip_upload_images: true,
					skip_upload_screenshots: true,
					changes_not_sent_for_review: true,
					package_name: APP_IDENTIFIER,
					version_code: options[:version],
					track: SUPPLY_TRACK,
					track_promote_to: promoteTrack,
					json_key: FASTLANE_SUPPLY_KEY_PATH
    		)
    	end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.195.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-badge      | 1.4.0   | 🚫 Update available |
| fastlane-plugin-appcenter  | 1.11.0  | 🚫 Update available |
| fastlane-plugin-bundletool | 1.0.3   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| bundler                         | 2.2.19       |
| uri                             | 0.10.0       |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.4        |
| concurrent-ruby                 | 1.1.9        |
| i18n                            | 1.8.10       |
| minitest                        | 5.14.4       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.9        |
| activesupport                   | 5.2.6        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.5.1        |
| algoliasearch                   | 1.27.5       |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.508.0      |
| aws-sigv4                       | 1.4.0        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.121.1      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.103.0      |
| babosa                          | 1.0.4        |
| curb                            | 0.9.11       |
| fastimage                       | 2.2.5        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.8.0        |
| unf_ext                         | 0.0.8        |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.16.0       |
| googleauth                      | 1.0.0        |
| mini_mime                       | 1.1.1        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| digest-crc                      | 0.6.4        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.8.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| badge                           | 0.12.0       |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.15.1       |
| ethon                           | 0.14.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.10.1       |
| cocoapods-deintegrate           | 1.0.4        |
| cocoapods-downloader            | 1.4.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.0        |
| cocoapods-trunk                 | 1.5.0        |
| cocoapods-try                   | 1.2.0        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| cocoapods                       | 1.10.1       |
| fastlane-plugin-appcenter       | 1.11.0       |
| fastlane-plugin-badge           | 1.4.0        |
| fastlane-plugin-bundletool      | 1.0.3        |
| mini_portile2                   | 2.5.1        |
| racc                            | 1.5.2        |
| nokogiri                        | 1.11.3       |
| wannabe_bool                    | 0.7.1        |
</details>

*generated on:* **2021-10-22**
</details>

side-note: I used fastlane with bundler. In only included the Fastlane code which actually triggers `supply`

### PR DESCRIPTION
**Pull request by joeflateau**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #19511

### Description

Adds an option to set the release status of a promoted track

### Testing Steps

Upload an apk/aab to an internal track with status complete and promote the track to production in draft status.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@joeflateau Hey, stranger! 👋 Curious if this is still WIP and if you need anything from me? No rush but just doing a curtsey check 😊

**Comment by joeflateau** [comment]
@joshdholtz howdy 🤠 two users from #19511 were going to be testing in the new year. I've been holding this in draft state until they got a chance to. I can move it along if it's cluttering up the queue

**Comment by joshdholtz** [comment]
> @joshdholtz howdy 🤠 two users from #19511 were going to be testing in the new year. I've been holding this in draft state until they got a chance to. I can move it along if it's cluttering up the queue

@joeflateau Nah nah nah, not cluttering up the queue at all! Just wanted to make sure I wasn't holding anything up here 😊 Just ping me its ready for me to review!

**Comment by joeflateau** [comment]
@joshdholtz this has now been tested and confirmed to work properly 🙂 ready for review

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Really love this addition! Thanks so much for the contribution 🥰

**Comment by quentin23soleil** [comment]
👋  just wondering why draft->inProgress is not possible with this?

**Pull request merged**
