### PR TITLE
[match] update `fastlane match init` to support Google Cloud Storage

### PR DESCRIPTION
**Pull request by KrauseFx**
💥 

**Remaining tasks:**

- [x] Store Google Cloud bucket in `Matchfile` during onboarding

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
TODO: store bucket

**Comment by KrauseFx** [comment]
Implements a part of https://github.com/fastlane/fastlane/issues/13772

**Comment by KrauseFx** [comment]
ok updated tests

**Review by armcburney — APPROVED** [review]
LGTM 👍, but I'd hold back on another review before 🚢ing.

**Review by joshdholtz — APPROVED** [review]
Looks good! I fixed a rubo thing and added an explicit return so merging this 💪

**Pull request merged**
