### PR TITLE
[ci] increase the max number of files available

### PR DESCRIPTION
**Pull request by lacostej**
Increase the amount of files available on mac by default.

This is in handy when running tests that involve stress testing a bit the system (such as #21792)

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### CODE REVIEW

**Comment by lacostej** [comment]
not really sure why appveyor failed here. Another flaky test?

**Comment by lacostej** [comment]
Force pushed to see if appveyor fails building again.

**Review by AliSoftware — APPROVED** [review]
If that's the reasons those tests are flaky, this is a bit scary 😅  Even if we're stress-testing the filesystem (why should we, though? Not sure that's the place of _fastlane_ itself to do that, would feel more like an Xcode problem?) I'm surprised we need that many opened files during testing in the first place. Might be worth investigating the root cause of that at some point.

**Comment by lacostej** [comment]
> if that's the reasons those tests are flaky, this is a bit scary 😅

@AliSoftware no, that's not the reason. By default we don't need that many files.

The command executor flaky test fails regularly. Last HEAD commit on master failed in one of the executor. But to reproduce the failure more consistently, I am running the same tests thousands of times, and this fails early if we don't increase the file limit.

I thought we'd better increase it right away so that we can run heavy stress testing workloads whenever we feel like.

The only drawback I can see is that if we enable it by default on the project, we wouldn't detect an internal issue in fastlane that would cause too many files to be opened during our tests. Is that an issue? That's a bit unlikely.

**Pull request merged**
