### PR TITLE
Change App Review time from 7 days to 24 hours in README

### PR DESCRIPTION
**Pull request by BalestraPatrick**
Improves the important stuff right here. 👍

### CODE REVIEW

**Comment by ohwutup** [comment]
Not sure that we want to be overly optimistic here. Currently, http://appreviewtimes.com shows that it is taking about 2 days for reviews. 🐙

**Comment by ohwutup** [comment]
We can put a link to that site in the docs though?

**Comment by BalestraPatrick** [comment]
Sounds good! Do you want me to update the text to "2 days" and add a link to the website where the statistics can be seen?

**Comment by ohwutup** [comment]
I think we should maybe change the text so something like "App review times are anywhere from 24 hours to a few days, checkout appreviewtimes.com for up-to-date expectations."

Maybe?

**Comment by jcampbell05** [comment]
Yeah it still doesn't take 1 day every time.

**Comment by BalestraPatrick** [comment]
I agree with all the mentioned points. Just updated the PR :)

**Comment by KrauseFx** [comment]
Looks good 👍

**Pull request merged**
