### PR TITLE
[pem][spaceship] update development push certificate type ID

### LINKED ISSUE #19878: [pem] [spaceship] New "Apple Sandbox Push Services" certificate type
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Looks like apple added a new certificate type ID.

##### Command executed
```
pem --app_identifier "$prefix" --team_id "$team" --output_path "build/push_certs" --pem_name "DEV_$name" --development --force
```

### Error

```
[!] Apple provided the following error info:
	The selected team does not have a program membership that is eligible for this feature.  If you need assistance, please contact Apple Developer Program Support. https://developer.apple.com/support
```

### Details

After this, I created a certificate in the web portal manually and inspected the web data. This is an excerpt from the certificate JSON:

```
      "certificateTypeId" : "JKG5JZ54H7",
      "requesterEmail" : "XXX",
      "displayName" : "XXXXX",
      "requesterLastName" : "Makarov",
      "ownerId" : "XXX",
      "platform" : "IOS",
      "certificateTypeName" : "Apple Sandbox Push Services",
      "isManaged" : false,
      "requesterFirstName" : "igor",
      "permissions" : {
        "rotate" : false,
        "download" : true,
        "approve" : true,
        "revoke" : true
      }
```

As you can see, there's a new type "Apple Sandbox Push Services" (type `JKG5JZ54H7`) which replaces "APNs Development iOS" (type `BKLRAVXMGM`).

I don't know if simply replacing the certificate type in `spaceship/lib/spaceship/portal/certificate.rb` is enough. From my manual testing, it worked but I'm not sure how this works with regards to compatibility.

@joshdholtz can you advise?

Thank you.

### PR DESCRIPTION
**Pull request by igor-makarov**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #19878

### CODE REVIEW

**Comment by igor-makarov** [comment]
@joshdholtz now I'm really out of my depth with all the build failures here.

But it does look like Apple changed the type ID.

**Comment by JimDabell** [comment]
Just a word of warning – AWS SNS is currently rejecting certificates created this way with:

> Error creating SNS platform application: InvalidParameter: Invalid parameter: Attributes Reason: You provided a certificate of type OTHER, which cannot be used to create an application of type iOS Development. Please select an application of type OTHER or provide a certificate of type iOS Development

**Comment by Robotex** [comment]
> now I'm really out of my depth with all the build failures here.

Build fail most likely because you didn't update the specs @
spaceship/spec/launcher_spec.rb#L128
spaceship/spec/portal/portal_stubbing.rb#L185
spaceship/spec/portal/portal_stubbing.rb#L200
spaceship/spec/portal/portal_client_spec.rb#L304

**Comment by nageshkumarmishra** [comment]
when we are planning to push the fix?

**Comment by valerio-castelli** [comment]
I'd love to help, but I'm not sure I can push code to @igor-makarov's fork. If I can do so, I could take care of updating the specs.

**Comment by igor-makarov** [comment]
The main question is whether we can just forget the old type ID - it's probably still going to appear for old certificates.

**Comment by igor-makarov** [comment]
I think I've figured out what to do with the old certificate type - I think it should go into the `OLDER_IOS_CERTIFICATE_TYPES` box. The old `ProductionPush` is there. 

This also gave me a lead as to what is expected to be stubbed, so I managed to fix the tests.

@joshdholtz I think this is ready for review.

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you for fixing this 😊 This will go out today 💪

**Pull request merged**
