### PR TITLE
Fix: #1073 git_commmit and git_add can allow to add paths with space

### PR DESCRIPTION
**Pull request by wanbok**
When i tried to run `git_add` and `git_commit`, It don't allow paths with space.

```
[21:18:03]: ---------------------
[21:18:03]: --- Step: git_add ---
[21:18:03]: ---------------------
[21:18:03]: Error setting value '["./Acceptance Tests/Info.plist"]' for option 'path'
[21:18:03]: You passed invalid parameters to 'git_add'.
[21:18:03]: Check out the error below and available options by running `fastlane action git_add`
[21:18:03]: Variable Dump:
[21:18:03]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios git_commit"}
[21:18:03]: Couldn't find file at path './Acceptance'
```

So, i fixed it. #1073

### CODE REVIEW

**Comment by asfalcone** [comment]
@wanbok Thanks for the PR. It looks like the tests are failing in Travis. Can you please run `bundle exec rspec` locally and fix the failing tests? 🚩

**Comment by wanbok** [comment]
@asfalcone Ok, i'll do it

**Comment by wanbok** [comment]
Hi @asfalcone 
I think the spec is excessive. But i prepared #1452, if you guys don't want to edit specs.

You can choose one, then refuse one. :)

cc @KrauseFx

**Comment by wanbok** [comment]
Attached one more spec to test `shellescaped` path on `git_commit`

**Comment by asfalcone** [comment]
@wanbok Thanks for updating the specs! This is great. Can you please squash down to 1 commit? Then this will be ready to merge :+1: 

Please also close #1452! Thanks!

**Comment by wanbok** [comment]
@asfalcone :)

**Comment by asfalcone** [comment]
Thanks! :sunglasses:

**Pull request merged**
