### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by mpirri**
Changes since release 1.97.2:
- Use export-method = 'development' by default
- Update `AvailablePlugins.md` (#5424)
- [fastlane] Updated gym dependency (#5413)
- [fastlane] Update number of available actions (#5411)
- Add Xcode 8 support: rename "OS X" to "macOS" (#5385)
- Added support for relative file paths (#5354)
- [add_git_tag] adding force option (#5348)
- Fix missing last_git_commit_message to last_git_commit (ref #5213) (#5342)
- Fixed misspell. (#5349)
- Update `AvailablePlugins.md` (#5345)
- There was 4 single checks not 3 and this was causing issues on markdown parsing (#5330)
- Added missing () (#5303)
- crash if the appropriate target is not found (#5338)
- Improve error message for black_list for invalid lane names
- Fix confusing error message when lane name is :test
- Improve instructions for publishing plugin (#5328)
- Update xcode-install version to 2.0.0 (#5322)
- Added instructions on how to make fastlane fast again (#5308)
- Fix link to `PluginsTroubleshooting.md` (#5314)
- Update `AvailablePlugins.md`
- Updated `AvailablePlugins.md` (#5305)
- Added warning when a lane name is already taken by an action
- Refactored how actions are loaded to a central point

### CODE REVIEW

**Comment by mpirri** [comment]
#overtheshoulder 🚢

**Comment by KrauseFx** [comment]
Why is the changelog different from https://github.com/fastlane/fastlane/releases/tag/1.98.0? To make it easier and faster to read?

**Comment by mpirri** [comment]
This is the literal changelog from `fastlane show_changelog`, while the changelog for the release tag was edited down to be more concise for human readability. Do you prefer a different approach?
/cc @asfalcone @mfurtak

**Comment by mfurtak** [comment]
The public release notes were edited down to remove trivial fixes. This list represents the full set of commits as generated by the lane, as @mpirri said

**Comment by asfalcone** [comment]
I removed things like the updates to README files, reworded some messages to include the action name and condensed some of the commits into 1 comment.

**Comment by KrauseFx** [comment]
Sounds perfect, thanks for clarifying 👍

**Pull request merged**
