### PR TITLE
Fix broken links in Markdown files

### PR DESCRIPTION
**Pull request by ReadmeCritic**
This pull request fixes broken links in Markdown files

This is looking like part 1 of 2, not sure I want to have it in a giant pull

Reviewed 
- [x] cert/ManualSteps.md
- [x] CODE_OF_CONDUCT.md
- [x] deliver/Reference.md
- [x] fastlane/docs/Android.md
- [x] fastlane/docs/Appfile.md
- [x] fastlane/docs/Bamboo.md
- [x] fastlane/docs/CodeSigning.md
- [x] fastlane/docs/Gitignore.md
- [x] fastlane/docs/Jenkins.md
- [x] fastlane/docs/Platforms.md
- [x] fastlane/ISSUE_TEMPLATE.md
- [x] fastlane/lib/fastlane/actions/README.md
- [x] fastlane/lib/fastlane/helper/README.md
- [x] gym/fastlane/README.md
- [x] gym/lib/gym/generators/README.md
- [x] gym/lib/gym/xcodebuild_fixes/README.md
- [x] ISSUE_TEMPLATE.md
- [x] match/lib/assets/READMETemplate.md
- [x] snapshot/lib/snapshot/fixes/README.md
- [x] snapshot/MigrationGuide.md

Fixed
- [x] CONTRIBUTING.md
- [x] deliver/Deliverfile.md
- [x] deliver/MigrationGuide.md
- [x] fastlane/docs/Advanced.md
- [x] fastlane/docs/FAQs.md
- [x] fastlane/docs/Guide.md
- [x] fastlane/docs/README.md

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
@ohwutup please review :smile:

**Comment by ohwutup** [comment]
hey @ReadmeCritic, would you mind squashing these before we merge?

**Comment by ohwutup** [comment]
closing this for a squashed version: https://github.com/fastlane/fastlane/pull/3618

**Comment by ReadmeCritic** [comment]
@ohwutup thanks, sorry for the trouble 

Will try to squash/consolidate my next contribution

**Pull request closed without merging**
