### PR TITLE
Add new badge_gravity option for badge action

### PR DESCRIPTION
**Pull request by HazAT**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @HazAT, thanks for the PR. With the new [Plugin System](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md), could we move `badge` to your repo, so that people can use it using plugins? This way you don't need to submit a PR for every change you do 👍

**Comment by KrauseFx** [comment]
@jcampbell05 has some experience with migrating an action into its plugin with xcake

**Comment by HazAT** [comment]
@KrauseFx Will convert `badge` action to the new plugin system.
Don't know what you want to do with this PR

**Comment by KrauseFx** [comment]
@HazAT I'll close this PR 👍

**Pull request closed without merging**
