### PR TITLE
Disable CollectionMethods rubocop preferences

### PR DESCRIPTION
**Pull request by mfurtak**
I'll remove the change to `print_table` once I see that hound ignores it 👍

### CODE REVIEW

**Comment by mfurtak** [comment]
OK, let's see how this works~

**Review by KrauseFx — APPROVED** [review]
Looks good

**Comment by KrauseFx** [comment]
Why does the hound bot do something different from the rubocop?

**Comment by mfurtak** [comment]
That's a good question, I don't know! We were not specifying a preference for this check, so perhaps Hound has a different set of defaults that they are applying first?

**Comment by KrauseFx** [comment]
All the other rules are considered by the Hound, just some not as it seems.

**Comment by mfurtak** [comment]
My belief is that if you change the setting to be `true` in our configuration, you would see all the places that Hound would complain about, if we started changing those files.

**Pull request merged**
