### PR TITLE
Multiple iTunes Connect Providers Fix

### PR DESCRIPTION
**Pull request by najdanovicivan**
This fixes the following error:

Transporter Error Output]: Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)

Fix for issue https://github.com/fastlane/fastlane/issues/1524

### CODE REVIEW

**Comment by najdanovicivan** [comment]
I've discovered this issue once I tried to upload TestFlight build using pilot. The issue occurred only when I tried to upload build to the second iTunesAccount. Previously I had only one Team on this account. And I was able to upload builds on the first account, but when I tried to upload to second account i got errors.
Form official iTunesConnect documentation on iTMSTransporter i saw that team id have to be added as --itc_provider parameter

**Comment by mfurtak** [comment]
Hi @najdanovicivan - thanks very much for your contribution 👍 

We've released [`deliver` 1.12.0](https://github.com/fastlane/fastlane/releases/tag/deliver/1.12.0) which includes https://github.com/fastlane/fastlane/pull/4746 to fix this. You can use the `:dev_portal_team_id` option get that info through to to the iTunes Transporter 🚚 💨

**Comment by rompic** [comment]
@mfurtak: how (couldn't find any info)? shouldn't this be taken into account automatically if team_id is specified in the app file?

**Comment by mfurtak** [comment]
@rompic - Yes, if `team_id` is specified in your Appfile, the value will be used. If not, you can pass it through your Fastfile like:

```ruby
deliver(dev_portal_team_id: 'abcd1234')
```

or on the command line, like:

```
deliver --dev_portal_team_id abcd1234
```

**Comment by rompic** [comment]
I'm afraid we still face the initial problem even thought we've updated fastlane and deliver to the latest versions. Does fastlane_version have any effect on this or at all?

**Comment by mfurtak** [comment]
@rompic OK, please open a new ticket and provide as many details as possible per the issue template, and we'll take a look. Especially helpful will be complete log output for a run that includes the `--verbose` flag from the command line.

**Comment by mfurtak** [comment]
@rompic There is another ticket on this subject (https://github.com/fastlane/fastlane/issues/4936) if you want to follow along there.

**Pull request closed without merging**
