### PR TITLE
Add full support for new promotional text support in iTC

### PR DESCRIPTION
**Pull request by KrauseFx**
This was introduced at WWDC 2017

This PR adds support for this new feature on _spaceship_ and _deliver_ 🚀

screen shot 2017-06-05 at 3 34 47 pm

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
🐑

**Comment by wiremax** [comment]
In addition to the new "Subtitle" field,

**Comment by KrauseFx** [comment]
@wiremax Oh, is there another field we should add support for?

**Comment by matteomartinelli** [comment]
@KrauseFx Yep, https://github.com/fastlane/fastlane/issues/9375

**Pull request merged**
