### PR TITLE
Remove crash reporter from fastlane

### PR DESCRIPTION
**Pull request by KrauseFx**
We remove the crash reporter for multiple reasons:

1) We didn't use it to resolve issues, as usually relevant debug information is missing
2) Crashes are only accessible to Google employees
3) Maintenance cost when it comes to removing sensitive user information

We're gonna re-visit the decision when we're solving the problem for `fastlane.ci`

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by revolter** [comment]
Related to https://github.com/fastlane/fastlane/issues/11913.

**Review by taquitos — APPROVED** [review]
This looks good, but I'd double check to make sure `trim_backtrace`, `trimmed_backtrace`, `could_contain_pii?`, and `includes_method_missing?` aren't called from anywhere else

**Comment by revolter** [comment]
I searched for those strings in the entire project with no results. So if there's no magic involved, it looks like they are not called anymore (at least by our code).

**Comment by KrauseFx** [comment]
Thanks for checking @revolter 👍

**Pull request merged**
