### PR TITLE
Truncate all values, not just strings

### PR DESCRIPTION
**Pull request by azgul**
Reason being that config options can also be arrays

### CODE REVIEW

**Comment by azgul** [comment]
Hey! I was passing an obnoxiously array in snapshots launch arguments and I realised that arrays were not being truncated. Let me know if my change is ok or what I might need to change to get this accepted. Cheers!

**Comment by azgul** [comment]
Ugh. Would it be OK to change the unit tests, or do you have better way of solving the lack of truncation?

**Comment by mfurtak** [comment]
Hi @azgul - thanks for taking this on!

I see what was tripping you up earlier, but I think in this case it would be fine to change the tests to match the new results.

For the change itself, I think you can get away with just:

```ruby
rows.map do |e|
  value = e[1].to_s.truncate(max_allowed_value_length)
  [e[0], value]
end
```

Conveniently, `nil.to_s` will result in an empty string, so we should be good! Let me know if that works for you 👍

**Comment by azgul** [comment]
Hey Michael,

I'll take a look at it when I am with my work laptop tomorrow. I wasn't
aware that `nil.to_s` is equivalent to empty string :)

**Comment by azgul** [comment]
I left the boolean check there so it wont change boolean values into strings because it looks quite ugly imho. Hope that's ok.

**Comment by mfurtak** [comment]
OK, sounds good. Thanks for the contribution!

**Pull request merged**
