### PR TITLE
[frameit] Add `title_below_image` option from issue #6824

### PR DESCRIPTION
**Pull request by claesjacobsson**
🔑
New Framefile option `title_below_image` places title below screenshot instead of above (default).

### CODE REVIEW

**Comment by claesjacobsson** [comment]
Here's an example of a screenshot using this option. Useful when it's important to show the lower part of the screen.

iphone7-shareextension_framed

**Comment by KrauseFx** [comment]
Oh, this looks really nice. Sorry we haven't yet had the time to review and test it. We have to think carefully about what kind of options we support, since we'll have to support and maintain them for a really long time. 

Thanks for your pull request, it's something we definitely consider 👍

**Comment by claesjacobsson** [comment]
Thanks! I completely understand that you need to consider. Let me know if there is something I can do to make the code more 'mergeable'. :)

**Comment by ohwutup** [comment]
Hey @claesjacobsson ! Would you mind adding a test or two to the code so we can make sure your new option performs as expected? 📈 🚀

**Comment by ohwutup** [comment]
Hey @claesjacobsson, I am going to close this PR for now as it's been open for a while without activity. We are more than happy to reopen the PR if you want to add some tests to help reliably maintain this code in the future. Thanks for your contribution! 🚀 🐙

**Pull request closed without merging**
