### PR TITLE
Updated super class sample

### PR DESCRIPTION
**Pull request by KrauseFx**
This was some very old code

### CODE REVIEW

**Comment by KrauseFx** [comment]
Ready to merge whenever CI was successful

**Comment by lacostej** [comment]
if we merge #4142 (or it alternative), then `ConfigItem.type` will become compulsory. Can we take this into account ?

**Comment by KrauseFx** [comment]
@lacostej Sure, but let's do this as a separate PR

**Comment by lacostej** [comment]
@KrauseFx you can right away add
````
 #  type: String,
````

test:

````ruby
require 'fastlane_core'
a = FastlaneCore::ConfigItem.new(key: :ipa_path,
      type: String,
      env_name: "CRASHLYTICS_IPA_PATH",
      short_option: "-k",
      description: "Value Description")

puts a.data_type
puts a.valid?("hello")
puts a.auto_convert_value("true").class
`````

`````
$ bundle exec ruby test.rb 
String
true
TrueClass
````
and problem solved. It works today.

**Pull request merged**
