### PR TITLE
Added clarification to HockeyApp action error

### PR DESCRIPTION
**Pull request by micnguyen**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Sorry, I don't understand `Is there an app created that matches the IPA's bundle ID or`, what do you mean?

**Comment by micnguyen** [comment]
Sorry for the lack of clarity. 

There's an error uploading to HockeyApp when your built IPA does not match the bundleID of the HockeyApp App using the same API Token. ie: I created a HockeyApp app with bundle id com.example.app1 and created an API Token to upload for that app. My Fastlane script used that API token but the actual IPA's file bundle id was com.example.app2 and it threw up that error message. I was wondering why I had to put in the public_identifier since I never had to, but it was simply a mismatch in the bundle ID and the Hockey action is not "creating a new app" with the bundle id of the IPA.

**Comment by ohwutup** [comment]
@micnguyen, would you mind changing that text to make it a bit more clear? i also am having a hard time understanding it from just that change you made. 

thanks! :octopus:

**Comment by micnguyen** [comment]
Apologies for the lack of clarity in the message. I'll be sure not to work on fastlane PRs during work time :)

As an additional note for clarification, from my understanding of https://github.com/fastlane/fastlane/issues/400 I would be interested to see what type of API token they are using. HockeyApp lets you either create an API token for a single app, or for all apps. If you use the API token for a single app, then obviously Hockey knows which Hockey app to upload to without the public identifier (which I don't use myself). If you use an 'all apps' token, you have to provide some way for HockeyApp to know which Hockey app it is meant to upload to. If you use the all apps token, then you will need to provide the public_identifier OR make sure the app's bundle ID matches. In my case, I had neither - and hence I got the ambiguous error that made me open this PR.

I am certain the upload API here: http://support.hockeyapp.net/kb/api/api-apps has been made when they use single app API tokens and has not been updated for an all-apps API token because public_identifier isn't even listen as a parameter you can provide in the request! Anyway, PR updated.

**Comment by ohwutup** [comment]
This is great! Thanks @micnguyen !! :rocket:

**Pull request merged**
