### PR TITLE
Allow groups and distribute external to be mutually exclusive

### PR DESCRIPTION
**Pull request by ohayon**
Fixes https://github.com/fastlane/fastlane/issues/10167

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
🎉 

Do we want to ship a release for this change?

**Comment by jahorton** [comment]
Any idea when this will be released?

**Comment by KrauseFx** [comment]
It's gonna be part of the next release, probably Monday morning :)

**Comment by KrauseFx** [comment]
You can always point your Gemfile to GitHub master, or opt-in on nightly builds 👍

**Pull request merged**
