### PR TITLE
[fastlane] update plugins too

### PR DESCRIPTION
**Pull request by hjanuschka**
On Release update plugins too, by generating the new plugin list and submitting it in the same PR as the actions.md

follow up on - https://github.com/fastlane/docs/pull/190 and https://github.com/fastlane/fastlane/pull/7098 and https://github.com/fastlane/fastlane/pull/7093

### CODE REVIEW

**Comment by KrauseFx** [comment]
We don't have a list of available plugins on docs.fastlane.tools any more: https://docs.fastlane.tools/plugins/available-plugins/

Does that look ok to you?

**Comment by hjanuschka** [comment]
there is still a link to an outdated plugin list https://docs.fastlane.tools/actions/#plugins is it supposed to be complete removed and `plugin_search` is the new way? - if so - lets close this PR

**Comment by KrauseFx** [comment]
Yeah let's close this and focus on https://docs.fastlane.tools/actions/#plugins

**Comment by KrauseFx** [comment]
Where do we update https://docs.fastlane.tools/actions/#plugins again?

**Comment by KrauseFx** [comment]
Oh, when generating the actions.md, right?

**Comment by hjanuschka** [comment]
yeah i think that the plugin update is not working now, this PR should do it.

**Pull request closed without merging**
