### PR TITLE
Remove 'zip' example from update_info_plist

### PR DESCRIPTION
**Pull request by spinningarrow**
It doesn't seem to be relevant.

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Ha, nice catch, thanks 👍  Can you address the comments from the bots?

**Comment by spinningarrow** [comment]
Yes, I'll get to it ASAP!

**Comment by KrauseFx** [comment]
Thanks ❤️

**Comment by spinningarrow** [comment]
@googlebot I signed it!

**Comment by spinningarrow** [comment]
'ASAP' took a while - sorry about that. Checks seem happy now 👍

**Review by matthewellis — APPROVED** [review]

**Comment by matthewellis** [comment]
@KrauseFx Reviewed and all seems good, are you happy to merge?

**Pull request merged**
