### PR TITLE
[reset_git_repo] only do a full reset when paths is nil

### PR DESCRIPTION
**Pull request by koenpunt**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Description

only do a full reset when paths is nil, so no accidental full-resets can occur when accidentally specifying an empty array

### CODE REVIEW

**Comment by mfurtak** [comment]
While the behavior you're going for seems reasonable to me, the change alters existing behavior that some people may be depending on.

Can you say more about why you thing this is important? We should try not to alter existing behavior that people may be using unless absolutely necessary 👍

**Comment by koenpunt** [comment]
I added a glob to the files option, which didn't match any files, and as a result the version change in the xcode project was reverted too..

```rb
reset_git_repo files: Dir['ios/**/AppIcon.appiconset/*.png']
```

**Comment by mfurtak** [comment]
Cool, thanks for the example use-case. Your approach was reasonable, and the results were surprising (and destructive) so, let's do it.

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
Thanks for the contribution 👍

**Comment by KrauseFx** [comment]
Great change 👍

**Pull request merged**
