### PR TITLE
Add and delete multiple testers API at a time

### PR DESCRIPTION
**Pull request by csc-EricWu**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

issue :#17278
It solves the problem that multiple testers cannot be deleted at one time
#17278 

I call delete_beta_testers_from_app, it works

### CODE REVIEW

**Comment by max-ott** [comment]
Please stick with the initial single quote style.

**Comment by csc-EricWu** [comment]
I use the AutoFormat plug-in, and when I save it, the program automatically formats it.

**Comment by csc-EricWu** [comment]
I've tested them. They work

**Comment by max-ott** [comment]
Please provide exact steps to test this. So far I can only see how to delete testers. Also we cannot add PRs that are not matching our code style.

**Pull request closed without merging**
