### PR TITLE
[Fastlane.swift][cert][deliver][pilot][precheck][sigh] make `username` optional where `apiKeyPath` can also be provided

### LINKED ISSUE #18177: Fastlane Swift: uploadToTestflight's username parameter conflicts with apiKeyPath parameter
[WorkaroundForGHIssue18177.txt](https://github.com/fastlane/fastlane/files/5959502/WorkaroundForGHIssue18177.txt)

### New Issue Checklist

- [x]  Updated fastlane to the latest version
- [x]  I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x]  I read [docs.fastlane.tools](https://docs.fastlane.tools/)
- [x]  I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The auto-generated API for `upload_to_testflight` makes the `username` parameter mandatory:

```
public func uploadToTestflight(apiKeyPath: String? = nil,
                               apiKey: [String: Any]? = nil,
                               username: String,   // <-- this should be String? = nil,
                               ....

```
However, I want to use the API key, specified in `apiKeyPath`. This code doesn't compile:

```
        uploadToTestflight(
            apiKeyPath: "fastlane/AuthKey_XXXXXXXXXX.json",
            localizedBuildInfo: [
                "default": [
                    "whats_new": try? String(contentsOfFile: changelogFileEn),
                ],
                "de-DE": [
                    "whats_new": try? String(contentsOfFile: changelogFileDe)
                ]
            ],
            skipSubmission: !isExternal,
            skipWaitingForBuildProcessing: false,
            usesNonExemptEncryption: false,
            distributeExternal: isExternal,
            groups: distributionGroups,
            teamId: account.appStoreConnectTeam
        )

```
because of the mandatory username parameter ("_Missing argument for parameter 'username' in call_")

When I supply the (redundant) username to `uploadWithTestflight()`, fastlane bails out with "_Unresolved conflict between options: 'api_key_path' and 'username'_".

### Workaround

I redefined `uploadToTestflight` without `username` parameter and supplied `RubyCommand.Argument(name: "username", value: nil)` in the `args` array (see [WorkaroundForGHIssue18177.txt](https://github.com/fastlane/fastlane/files/5959517/WorkaroundForGHIssue18177.txt)). However, it would be convenient, if `username` would be an optional String that defaults to nil.

#16389 reported basically the same issue.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 11.2.1                                                   |
| Ruby                        | 2.7.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.26.0                                       |
| Installation Source         | ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 11.2.1 (20D74)                                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode-12.4rc.app/Contents/Developer/       |
| Xcode Version               | 12.4                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation
import FastlaneTeufel

class Fastfile: LaneFile {
    let app: AppDetails = {
        let fileManager = FileManager.default
        let file = "\(fileManager.currentDirectoryPath)/.teufelfastlane"
        guard fileManager.fileExists(atPath: file) else { fatalError("File \(file) not found!") }
        guard let contents = fileManager.contents(atPath: file) else { fatalError("File \(file) is empty or corrupted!") }

        let decoder = JSONDecoder()
        guard let app = try? decoder.decode(AppDetails.self, from: contents) else { fatalError("File \(file) is not a valid AppDetails json!") }
        return app
    }()
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.174.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.1.4        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.7        |
| i18n                          | 1.8.5        |
| minitest                      | 5.14.2       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.7        |
| activesupport                 | 5.2.4.4      |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.426.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.0       |
| babosa                        | 1.0.4        |
| curb                          | 0.9.10       |
| fastimage                     | 2.2.2        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| digest-crc                    | 0.6.3        |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| badge                         | 0.12.0       |
| clamp                         | 1.3.2        |
| mini_portile2                 | 2.4.0        |
| nokogiri                      | 1.10.10      |
| slather                       | 2.5.0        |
</details>

*generated on:* **2021-02-10**
</details>

### PR DESCRIPTION
**Pull request by alexisbronchart**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This initially aims at resolving https://github.com/fastlane/fastlane/issues/18177
However I think it make sense not to force providing a username when apiKey or apiKeyPath can also be used.

Resolves #18177

### Description
`username` become optional in functions that also have a apiKey / apiKeyPath argument.

### CODE REVIEW

**Comment by alexisbronchart** [comment]
@googlebot I signed it!

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@alexisbronchart Thank you for this PR! However, `Fastlane.swift` is autogenerated from options define in all Ruby actions.

`optional: true` should be added to all of the `username` options in the Ruby definition of the actions. You can run then run `fastlane generate_swift_api` in this repo to test that everything generated correctly but `fastlane/swift/Fastlane.swift` shouldn’t be commit in a PR that isn’t bumping the version 😇 

Sorry for the confusion here!

**Comment by alexisbronchart** [comment]
Allright I'll change this ASAP. Thanks for the details!

**Comment by joshdholtz** [comment]
@alexisbronchart Thanks for making those changes! I’m going to make a new release tonight but leave this PR out of it. This touches a lot of tools/actions and even though this _shouldn’t_ effect anything and tests pass... I just want to manual run through everything 😊  Hope that’s okay! ❤️

**Comment by alexisbronchart** [comment]
No worries @joshdholtz better safe than sorry!

**Review by joshdholtz — COMMENTED** [review]
Hey! So I’ve played around with this and there is _one_ thing I’m trying to figure out how to rework 😊  When a configuration item is required, there is a nice interactive prompt that asks for the user to enter a value and where to set it as a configuration if they don’t want to be prompted again.

With setting this to optional, we lose that but... Spaceship does have its own prompt that is used for this. So this doesn’t technically break things but I don’t fully like how its changing things. I’m going to think about how to make the same prompt appear when an option is being set to optional 😊

**Comment by alexisbronchart** [comment]
> Hey! So I’ve played around with this and there is _one_ thing I’m trying to figure out how to rework 😊 When a configuration item is required, there is a nice interactive prompt that asks for the user to enter a value and where to set it as a configuration if they don’t want to be prompted again.
> 
> With setting this to optional, we lose that but... Spaceship does have its own prompt that is used for this. So this doesn’t technically break things but I don’t fully like how its changing things. I’m going to think about how to make the same prompt appear when an option is being set to optional 😊

Hi @joshdholtz have you already been able to look at this prompt thing?

**Comment by rogerluan** [comment]
@alexisbronchart could you revert all the changes you made to the .swift files? That would help us move this PR forward 🙏 (it even triggered merge conflicts right now, but if you just discard the changes to the swift files, those will be gone 🚀 )
Thanks!

**Comment by alexisbronchart** [comment]
> @alexisbronchart could you revert all the changes you made to the .swift files? That would help us move this PR forward 🙏 (it even triggered merge conflicts right now, but if you just discard the changes to the swift files, those will be gone 🚀 )
> Thanks!

@rogerluan done. I guess it's normal that tests are now failing since those swift changes were generated by the `generate_swift_api` script? Should I re-run it after a rebase or something?

**Comment by rogerluan** [comment]
@googlebot I consent.

**Review by rogerluan — APPROVED** [review]
Thanks for addressing the changes I had requested 💪 I reverted some other changes that had to be reverted and merged latest master to resolve the failing specs 😊 

The changes on this PR are on spot! 🎯 I faced this issue myself and ended up hot-fixing by passing `username: "random string until https://github.com/fastlane/fastlane/pull/18194 is merged"` 😆 

LGTM! 💪

**Comment by joshdholtz** [comment]
@rogerluan @alexisbronchart One thing I’m still stuck on is that this changes the prompt for username when its not specified 🤔 Previously it would use the prompt provide by the option because it was required. With this change it uses the prompt provided by `spaceship`. I’d still like to maybe find a way to keep the existing functionality 🤷‍♂️ 

## Before change
8B4641B0-0FB3-4F45-AF9E-D10EDA965597

## After change
8177D238-038B-46B3-9E13-C6C4B82B1BF3

**Comment by joshdholtz** [comment]
@rogerluan @alexisbronchart I found a solution! Kind of embarrassed it took me this long to think of it 🤦‍♂️ Pushing a commit!

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by rogerluan — APPROVED** [review]
Nice solution! 💪💪

**Review by joshdholtz — APPROVED** [review]
This is good to ship now! Thanks for making making these changes ❤️ Really appreciate it!

**Pull request merged**
