### PR TITLE
[docs] Add documentation regarding testing against FastlaneSwiftRunner

### PR DESCRIPTION
**Pull request by rogerluan**
🔑 

## Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

My motivation is that I spent some good amount of time figuring out how to test my local changes against the Swift APIs, while implementing this: https://github.com/fastlane/fastlane/pull/16805
I didn't know this was part of the process until I was told in that same PR, so I made this documentation part of the Testing.md instead of any other file (so at least it's documented somewhere how one can test the changes).

### Description

This PR adds a new section in the Testing.md file, that describes how one can test local changes against `FastlaneSwiftRunner`, and instructs the contributor to not commit those changes.

### Testing Steps

You can preview the file here: https://github.com/rogerluan/fastlane/blob/improve-testing.md/Testing.md

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]
I love this! Thank you ❤️

**Comment by rogerluan** [comment]
This was in master and a release occurred but apparently this wasn't included in the release notes 🤔 how does the release work @joshdholtz ? (or maybe this was skipped in the release notes because it's just docs?)

**Comment by joshdholtz** [comment]
@rogerluan 👋 Hey! docs stuff gets removed from the release notes. Sorry about that 😔

**Comment by rogerluan** [comment]
No worry, thanks for clarifying! 🙌

**Pull request merged**
