### PR TITLE
Directory ordering of default values for .ipa and . pkg files

### PR DESCRIPTION
**Pull request by tache**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines]
- [x] I've updated the documentation if necessary.

### Motivation and Context
When a project has multiple targets, an error could occur when there are .ipa files present for different targets having different bundle ids. The Ruby DIR command in some fastlane command default settings might not select the last .ipa file created. for example, when this occurred with pilot, it would result with the wrong .ipa file being uploaded to ITC, which would fail with an error stating that the bundle id changed. The same was noted for the .pkg option for deliver.

### Description
Replaced the default DIR ordering that was not guaranteed with a time ordered sort, which plucks the most recent ipa or pkg file for the default value.

### CODE REVIEW

**Comment by tache** [comment]
I signed it!

**Comment by tache** [comment]
This still needs to be applied. Issue is still present in the 2.28.5 version

**Review by KrauseFx — APPROVED** [review]
I like the idea, nice patch 👍

**Comment by KrauseFx** [comment]
Thanks for your contribution @tache, and sorry for the delayed reply 🚀

**Pull request merged**
