### PR TITLE
[action] swiftlint: Add missing env_names

### PR DESCRIPTION
**Pull request by tthbalazs**
🔑

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The `swiftlint` action was missing the `env_name` property from its configuration items.

### Description
This change adds the missing keys with the `FL_SWIFTLINT_KEY_NAME` format.

### Testing Steps
The change uses already well-tested functionality of Fastlane. Nevertheless I ran the swiftlint action against my local version of fastlane, with ENV values set.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@tthbalazs Can you accept the CLA? 😊

**Comment by tthbalazs** [comment]
@googlebot I signed it!

**Comment by tthbalazs** [comment]
@joshdholtz Signed. Sorry, I was checking if we want a corporate agreement as well :)

**Comment by joshdholtz** [comment]
@tthbalazs Not a problem! Just wanted to make sure your PR got merged in 😊

**Review by joshdholtz — APPROVED** [review]
Looks great to me! Thanks for adding these 😊

**Pull request merged**
