### PR TITLE
support signing dylibs located in main bundle path

### PR DESCRIPTION
**Pull request by iMokhles**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

### CODE REVIEW

**Comment by ohwutup** [comment]
Hey @iMokhles, thanks for submitting the PR, could you just tell us a little about the use case for this?

**Comment by iMokhles** [comment]
@ohwutup hey thanks for responding 
SO, iOS root known as JAILBREAK inject dylibs into Mach-O to modify codes at runtime through libraries aka ( Tweaks ) so we can also modify apps codes at runtime without JAILBREAK while swizzling it's code by injecting libraries into it'a Mach-O using injection tools ( like optool l, yololib, etc ) so the app code run signed codes which can modify it's functionality, and some people including ( ME ) places those libraries ( dylibs files ) inside the main bundle directory ( so it should be signed with the same way as frameworks to run into inside the app )

Hope it's clear :)

**Comment by ohwutup** [comment]
Hey @iMokhles, I'm not sure if it is totally clear, is this something that only Jailbreak tweak developers are going to get value out of? 🐙

**Comment by iMokhles** [comment]
hey @ohwutup
yes and no ( anyone can inject modifications without jailbreak to swizzle functions ) but for now ( some jailbreak developers including -ME ) doing those stuffs to improve functionality of some AppStore apps ( like I did here https://github.com/iMokhles/Tweaks-for-SideLoaded-Apps ) without jailbreak at all and as I explained before those tweaks ( dylibs files ) need to be signed to work, and sometimes they are placed under the main bundle directory without sub-folders


thanks 😁

**Comment by ohwutup** [comment]
Hey @iMokhles,

So I think that we would rather keep this out of our core functionality in resigning apps with _sigh_. That being said, I think that you could definitely create a plugin (https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md) that could be inserted into your _fastlane_ invocations.

I am going to close this PR for now, but feel free to keep discussion going here if you'd like!
🐙 🚀 🐮

**Pull request closed without merging**
