### PR TITLE
[pilot] improves testflight metadata upload

### PR DESCRIPTION
**Pull request by rpassis**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The current `upload_to_testflight` action allows users to submit a `changelog` to AppStoreConnect once the build has completed processing.

It turns out that **full** processing is actually not required for the changelog to be submitted. Once a build **appears** in AppStoreConnect, we are able to send the changelog information upstream without waiting for the full processing of the build to occur.

The goal of this PR is to introduce a slight change in behavior to `upload_to_testflight`, where if a user specifically sets `skip_waiting_for_build_processing` to `true` but also includes a `changelog`, we honor the changelog request by only waiting until the build appears on AppStoreConnect, and then bailing (the current behavior is to simply ignore the changelog, which is often un-intuitive and most likely undesirable).

### Description

This PR changes the internal of `build_manager` and `build_watcher` slightly.

On `build_manager` we determine whether the `skip_waiting_for_build_processing` was set to `true` and `changelog` is not `nil`.

Under this condition, we pass a new `skip_full_processing` variable to the `build_watcher` that allows us to poll the build on AppStoreConnect and bypass the most time consuming part of the processing which happens after the build appears on AppStoreConnect.

Note that this change is an implementation detail that hasn't had any effect on existing tests. I'd be more than happy to add a new test for this scenario but based on the existing tests it felt unnecessary and perhaps redundant but I'm happy to be convinced otherwise.

### Testing Steps

Run `fastlane run testflight skip_waiting_for_build_processing:true changelog:"test"` and ensure that once an IPA is uploaded, that the polling of the build only waits for the build to appear on AppStoreConnect and successfuly exist the process.

### CODE REVIEW

**Comment by rpassis** [comment]
@googlebot I signed it!

**Comment by rpassis** [comment]
Not sure what the deal is with the failed tests here, seems unrelated to this PR. Can anyone please help?

**Comment by rpassis** [comment]
Is there anything else I might be able to do to facilitate the review of this PR? Please let me know as I think this would be huge QOL improvement for developers and devops alike. 

We typically wait upwards of an hour for builds to process so they can include a changelog whereas after this PR it can literally take a few minutes.

Below is the output of a build that we have currently running. If this PR was applied to the build below we would've been able to upload the changelog 5 minutes after uploading whereas it has already been 20+ minutes and I know it will take at least double that (if not more) for the full processing to complete.

```
15:11:23 [12:11:14]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:11:48 [12:11:44]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:12:18 [12:12:14]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:12:47 [12:12:44]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:13:17 [12:13:16]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:13:46 [12:13:46]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:14:22 [12:14:16]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:14:47 [12:14:46]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:15:22 [12:15:17]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:15:52 [12:15:47]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:16:21 [12:16:17]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
15:16:51 [12:16:49]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:17:26 [12:17:20]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:17:56 [12:17:51]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:18:25 [12:18:22]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:18:55 [12:18:52]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:19:25 [12:19:23]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:19:57 [12:19:53]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:20:28 [12:20:24]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:20:58 [12:20:54]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:21:27 [12:21:25]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:21:57 [12:21:56]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:22:32 [12:22:27]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:23:02 [12:22:57]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:23:31 [12:23:28]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:24:01 [12:23:59]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:24:31 [12:24:29]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:25:00 [12:25:00]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:25:36 [12:25:31]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:26:05 [12:26:01]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:26:35 [12:26:32]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:27:05 [12:27:03]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:27:34 [12:27:33]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:28:10 [12:28:04]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
15:28:39 [12:28:35]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:29:10 [12:29:05]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:29:40 [12:29:36]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:30:09 [12:30:07]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:30:39 [12:30:38]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:31:08 [12:31:08]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:31:44 [12:31:39]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS

15:32:11 [12:32:09]: Waiting for App Store Connect to finish processing the new build (7.24.0 - 11.2) for IOS
```

**Comment by rpassis** [comment]
@Googlebot I consent

**Comment by rpassis** [comment]
@googlebot I consent.

**Comment by rpassis** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This is a great improvement! I really appreciate the time spent to fix this 🙌  I added some commits to change a few things after testing. I'm also going to be adding some tests in the morning and then I will get this merged 💪 Thanks for the contribution ❤️

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Pull request merged**
