### PR TITLE
[deliver] Buildwatcher regression 

### LINKED ISSUE #8324: Impossible to submit for review with 2.18.0 app_platform
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to run my scripts which worked several weeks ago, and after update fastlane to the latest release I get this issue:

[22:26:52]: Finished the upload to iTunes Connect
[22:26:54]: Selecting the latest build...

[!] Could not find option for key :app_platform.

[22:35:15]: Uploading app icon...
[22:35:22]: Finished the upload to iTunes Connect
[22:35:25]: Selecting the latest build...

[!] Could not find option for key :app_platform. Available keys: username, app_identifier, app, edit_live, ipa, pkg, platform, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, app_version, skip_metadata, force, submit_for_review, automatic_release, price_tier, build_number, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, overwrite_screenshots, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, app_review_information, description, name, keywords, release_notes, privacy_url, support_url, marketing_url

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.3                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| bundler                   | 1.14.4       |
</details>

*generated on:* **2017-02-21**
</details>

### PR DESCRIPTION
**Pull request by hjanuschka**
fixes https://github.com/fastlane/fastlane/issues/8324

### CODE REVIEW

**Comment by mfurtak** [comment]
Thanks for putting this fix together. 👍 

What tests are we missing that we didn't discover this before we shipped?

**Comment by hjanuschka** [comment]
i am not sure how this slipped through, and i have no clue why i used app_platform et-all
all my tests worked - but seems that i never triggered the branch with that line 😢

**Comment by GandjaFuzz** [comment]
@hjanuschka need more change
now error
```
ERROR [2017-02-22 17:23:31.53]: undefined local variable or method `sleep_time' for #<Deliver::SubmitForReview:0x007f817fbfcb08>
```

need change this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:app_platform], sleep_time)
```
on this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:platform], 30)
```

**Comment by mfurtak** [comment]
Closing in favor of a broader roll-back for now 👍

**Comment by timwredwards** [comment]
@mfurtak Is the intention to rollback to 2.17.1?

**Comment by hjanuschka** [comment]
@timwredwards we rolledback the buildwatcher PR - and a new release is on the way! will be published soon.

**Comment by mfurtak** [comment]
@timwredwards [This](https://github.com/fastlane/fastlane/pull/8335) is the roll-back, and it will be released as 2.18.2

**Comment by timwredwards** [comment]
@mfurtak Thanks my man.

**Comment by GandjaFuzz** [comment]
with my patch work great. publised already 20 apps

**Pull request closed without merging**
