### PR TITLE
Fix doc paths for Platforms.md and CodeSigning.md

### PR DESCRIPTION
**Pull request by jschoolcraft**
Also fixed a minor spelling mistake.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Perfect, could you squash the commits to one so we can merge it? Please let me know once it's ready 👍

**Comment by jschoolcraft** [comment]
Done.

**Comment by KrauseFx** [comment]
Something's wrong with the build, could you rebase from master and see if that fixes the issue?

**Comment by jschoolcraft** [comment]
Now this has Issue #4277 for this change

**Comment by asfalcone** [comment]
Hi @jschoolcraft This looks good and the build is green now, but needs to be squashed into 1 commit before we can merge. 

Try `git rebase -i HEAD~7` then force push to your branch to get rid of the extra commits.

**Pull request closed without merging**
