### PR TITLE
shows device names and fixes grouping in report, fixes fastlane#5502

### LINKED ISSUE #5502: [snapshot] summary report shows "4.7-Inch" instead of "iPhone6s"
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running the `snapshot` from `fastlane` generates the report just fine. It does not show the device name `iPhones6s` but `4.7-Inch` instead though. Is there a way to change that?

Also: Is there a template for the report that could be adjusted?

##### Complete output when running fastlane, including the stack trace and command used

NA

### Configuration Files

```
devices([
  "iPhone 6s",
])

languages([
  "de-DE",
])

ios_version '9.3'
reinstall_app true
erase_simulator true
skip_open_summary true
clear_previous_screenshots true
output_directory "./Screenshots"
stop_after_first_error true
```

### Environment

fastlane version (run `fastlane -v`):

`fastlane 1.98.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

chruby

### PR DESCRIPTION
**Pull request by tcurdt**
fixes #5502

### CODE REVIEW

**Comment by tcurdt** [comment]
So I cleaned this up. Sorry for the mess in #5847

**Comment by tcurdt** [comment]
> Hey @tcurdt, thanks for your contribution. This looks great, have you tested this change locally? Can you post a screenshot of the resulting file to this PR? 👍

Hey @KrauseFx, yes I tested this locally. Sorry but I cannot provide the screenshots. I can offer only some ascii art :)

```
de-DE
iPhone6 (4.7-Inch)
...
iPhone6s (4.7-Inch)
...
```

**Comment by KrauseFx** [comment]
Hey, you could provide the screenshot based on the `example` project contained in the `fastlane` repo, in the `snapshot` subfolder 👍

**Comment by tcurdt** [comment]
There is no CI for it? That feels almost a little ironic ;)

I've done:
```
cd fastlane/snapshot
bundle install
bundle exec fastlane list
...
[09:53:43]: Available lanes:
[09:53:43]: - test
[09:53:43]: - bump
[09:53:43]: - show_changelog
[09:53:43]: - release
```
...but neither runs `snapshot` and creates a report from the example project.

In the `example` folder are just the Xcode files - no fastlane setup.

Now what?

**Comment by KrauseFx** [comment]
Haha, yeah, I'd love to setup a CI for that @tcurdt. You can just run `snapshot` from the command line, without using fastlane 👍

**Comment by tcurdt** [comment]
@KrauseFx 

```
-d, --devices ARRAY  A list of devices you want to take the screenshots
from
```

Now if that only would tell me the syntax *how* to specify the list - but that's for another issue ;)

```
bundle exec snapshot -g de-DE,en-US -d 'iPhone 6','iPhone 6s'
```

Gave

screencapture-file-users-tcurdt-projects-fastlane-snapshot-example-screenshots-screenshots-html-1472026290623

**Comment by KrauseFx** [comment]
Perfect, thank you so much @tcurdt, and sorry it took so long, happy to have this merged 👍

**Comment by tcurdt** [comment]
@KrauseFx all good - thanks for the merge!

**Pull request merged**
