### PR TITLE
Version bump to 2.153.0

### PR DESCRIPTION
**Pull request by joshdholtz**
Auto-generated by fastlane 🤖

**Changes since release '2.152.0':**

* [deliver] verify all screenshot deleted succesfully (#16842) via Josh Holtz
* [frameit] Add font_size parameter (#16870) via Andreas Ganske
* [action] download_dsyms - add option to pass `build_number` as an integer (#16900) via Alex Benoit
* [spaceship] add endpoint availableTerritories (#16877) via Bolo Michelin
* [fastlane] fix other_action to run in root project directory (#16889) via Jorge
* [scan] fix empty simulator logs (#16833) via Lyndsey Ferguson
* [spaceship] feat: support appStoreVersionReleaseRequests (#16765) via Valerio Castelli
* [action] erb uses ErbTemplateHelper and adds trim mode (#16882) via Josh Holtz
* [deliver] reimplementing tests from 2.150.0 (#16880) via Josh Holtz
* [tests] add tests for submit_for_review spec (#16876) via Josh Holtz
* [gems] update webmock, faraday (#16853) via Anton Rieder
* [deliver] fetches app with Spaceship::ConnectAPI (#16857) via Josh Holtz
* [gems] Update rspec, rspec_junit_formatter (#16841) via Anton Rieder

### CODE REVIEW

**Comment by shizu2014** [comment]
demo_account_required Can't set

**Comment by shizu2014** [comment]
@joshdholtz 
app_review_information({
    demo_account_required:false,
  contact_first_name: "xxx ",
  contact_last_name: "xxx",
  contact_phone: "xxx",
  contact_email: "xxx",
  demo_account_name: "",
  demo_account_password: "",

  notes: ""
})
demo_account_required Can't set
Failure to set this property prevents uploading metadata and screenshots

**Comment by joshdholtz** [comment]
@shizu2014 Hey 👋 Can you create a new issue with what you are running into and your fastlane output? I will take care of right away but I'd like to track this somewhere else. Thank you! ❤

**Comment by shizu2014** [comment]
upload_metadata.rb
I edited this file
You can upload normally after commenting out this attribute 

 if !attributes["demo_account_name"].to_s.empty? && !attributes["demo_account_password"].to_s.empty?
        # attributes["demo_account_required"] = true
      else
        # attributes["demo_account_required"] = false
      end

**Comment by joshdholtz** [comment]
@shizu2014 Can you please move this over to a new issue so that I can be tracked and closed when I make a fix for this? 😇 

I would like to have more conversation more about your issue to see what problem is and what then figure out what the best solution is.

**Pull request merged**
