### PR TITLE
Add note about version in cocoapods

### PR DESCRIPTION
**Pull request by KrauseFx**
We've already received 3 PRs adding this parameter, this should avoid it in the future.

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by ohwutup** [comment]
Will using a Gemfile work when using the bundled _fastlane_?

**Comment by ohwutup** [comment]
Should we add a note saying that this will not work if _fastlane_ is installed via the zip file or homebrew?

**Comment by milch** [comment]
@ohwutup 

If the fastlane bundle was installed this could still work, since we're shelling out and could call pod using bundle exec. Maybe we should change the line https://github.com/fastlane/fastlane/blob/7908e2af585ce859312972bc2bd9e361f4229b86/fastlane/lib/fastlane/actions/cocoapods.rb#L17 here and remove the `shell_out_should_use_bundle_exec?` and just honor the `use_bundle_exec` param. This is a bit confusing for the user anyway as to why setting `use_bundle_exec` seemingly doesn't do anything.

**Comment by KrauseFx** [comment]
I'm ok either way, however we should merge this PR with the warning for now to avoid getting further PRs adding the version number. Feel free to merge directly after approving the PR 👍

**Review by milch — APPROVED** [review]

**Pull request merged**
