### PR TITLE
[action] download_dsyms: add explicit proxy specification for dsyms file downloading in case when 'http_proxy' env variable was specified

### PR DESCRIPTION
**Pull request by zhelanov**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I'd faced a problem when I've tried to use 'download_dsyms' action in our enterprise network. There is http proxy specified in 'http_proxy' environment variable on our CI system agents so every http request must be done via proxy server. 
According to [ruby docs](https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html)

> Net::HTTP will automatically create a proxy from the http_proxy environment variable if it is present.

but for some reason it don't. So there is a workaround - we can specify proxy explicitly in case when 'http_proxy' environment variable exists

### Description
**download_dsyms** action: add explicit proxy specification for dsyms file downloading in case when 'http_proxy' env variable was specified

### CODE REVIEW

**Comment by zhelanov** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
Hey @zhelanov, I fear your commits are connected to a different email address than your GitHub account so this did not get picked up. Can you please try again?

**Comment by zhelanov** [comment]
@googlebot I fixed it.

**Comment by janpio** [comment]
GH does not pick up that the commits are actually from your GH account:
https://github.com/fastlane/fastlane/pull/16434/commits
Probably the email address you have configured locally is not connected to your GH account. Adding that email address might solve this problem.

**Comment by zhelanov** [comment]
@googlebot I signed it!

**Review by janpio — APPROVED** [review]
Thanks!

We seem to be missing this all over the place: https://github.com/fastlane/fastlane/search?q=%22Net%3A%3AHTTP.new%22&unscoped_q=%22Net%3A%3AHTTP.new%22 Is there maybe a more general solution for this?

**Review by joshdholtz — APPROVED** [review]
Looks good to me! Appreciate the contribution ❤️

**Pull request merged**
