### PR TITLE
remove unnecessary usage of factory pattern

### PR DESCRIPTION
**Pull request by snatchev**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This PR removes unnecessary code that keeps getting re-used. See https://github.com/fastlane/fastlane/pull/8146

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
Did you happen to program in Java before?
🐑  it

**Comment by snatchev** [comment]
@taquitos java? never! I was reading Martin Fowler though.

I don't have permissions to merge 😞

**Review by nafu — APPROVED** [review]
Looks good to me 👍

**Comment by KrauseFx** [comment]
This is awesome 👍

**Pull request merged**
