### PR TITLE
added Actions.md documentation for badge

### PR DESCRIPTION
**Pull request by HazAT**
documentation for new action badge.
@ohwutup there you go, hope its enough.

### CODE REVIEW

**Comment by ohwutup** [comment]
this is great! thanks @HazAT! do you happen to know why the build is failing on CI?

**Comment by HazAT** [comment]
The error looks really strange, like completely unrelated... hmmm

**Comment by ohwutup** [comment]
no worries @HazAT we can fix that up and then i'll merge this!

**Comment by KrauseFx** [comment]
Thanks @HazAT, I'll add a test to also check if documentation is available in `Actions.md` so that this doesn't happen in the future :+1:

**Comment by KrauseFx** [comment]
Implemented with https://github.com/fastlane/fastlane/pull/1108

**Pull request merged**
