### PR TITLE
Add missing `highline` import in spaceship library

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/KrauseFx/xcode-install/issues/249

### CODE REVIEW

**Review by jdee — APPROVED** [review]
:shipit:

**Comment by jdee** [comment]
@KrauseFx I just had a thought. I'm sure you tested this, but is it actually `highline/import` that you need?

**Comment by jdee** [comment]
And testing may not solve the problem, since commander is probably bringing in `highline/import`. I suspect that you do need `highline/import` or you'll have to `include` a module where `ask` is used.

**Review by taquitos — APPROVED** [review]
🎈:goat: always good to require more stuff

**Comment by KrauseFx** [comment]
@jdee I didn't do a lot of testing, but in this case it seems like when someone requires spaceship, but not highline, it will fail, as that's where the `ask` method is implemented

**Comment by jdee** [comment]
I guess this is what I mean:

```
2.4.2 :001 > require 'highline'
 => true 
2.4.2 :002 > answer = ask "question"
NoMethodError: undefined method `ask' for main:Object
	from (irb):2
	from /Users/jdee/.rvm/rubies/ruby-2.4.2/bin/irb:11:in `<main>'
2.4.2 :003 > require 'highline/import'
 => true 
2.4.2 :004 > answer = ask "question"
question
42
 => "42" 
```

I don't think require 'highline' is enough to bring in the method in spaceship. But I'd have to do some testing to prove it.

**Comment by jdee** [comment]
Wait, you already had `highline/import`? I guess I'm just blind. Don't mind me.

**Comment by KrauseFx** [comment]
So the PR looks good @jdee? :)

**Pull request merged**
