### PR TITLE
Added verify_build action (again)

### PR DESCRIPTION
**Pull request by CodeReaper**
Prior history is here: #1151

It wasn't possible to merge into a single commit without doing a push --force which then closed the #1151 pull request for some reason...

@ohwutup, are we good to go?

### CODE REVIEW

**Comment by ohwutup** [comment]
sorry about the confusion with squash! thanks for doing that! could you just fix that one hound issue and squash again? you should be able to do an interactive rebase (`git rebase -i HEAD~2`) and `fixup` the second commit (that will fix the hound error) and `pick` the first one.

thanks!!

**Comment by CodeReaper** [comment]
@ohwutup I already fix that issue and pushed. I am seeing a "All checks have passed" message :)

**Comment by ohwutup** [comment]
@CodeReaper i think we are talking about different issues? this is what I'm referring to screen_shot_2016-02-24_at_5_56_51_pm

**Comment by KrauseFx** [comment]
I think the comment is actually outdated, local `rubocop` should work :+1:

**Comment by ohwutup** [comment]
nice! you're right @CodeReaper and @KrauseFx ! merging now! thanks @CodeReaper !!! :shipit:

**Pull request merged**
