### PR TITLE
[fastlane] optimize bash and zsh completion scripts

### PR DESCRIPTION
**Pull request by mcornella**
### Checklist

- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

I had issues with `bundle exec rspec`, probably due to a broken installation since it's the first time I've had to use it.

### Motivation and Context

The `_fastlane_complete` function for bash and zsh can be improved:

- It makes 3 calls to get lane names, which can be grouped into a single `sed` call.
- It leaks the `file` variable.
- It continues execution even if no `Fastfile` file has been found.

### Description

Changes:

- Group the 3 calls to `grep` and `awk` into a single `sed` call with [-E for extended regex (POSIX-compatible argument)](https://www.gnu.org/software/sed/manual/sed.html#index-_002dE).
- Makes `$file` variable local.
- Exit the function when no Fastfile file was found.

### Testing Steps

1. Add `compctl -K _fastlane_complete fastlane` to `completion.zsh` file.
2. Add `complete -F _fastlane_complete fastlane` to `completion.bash` file.
3. cd into `fastlane` repository root directory.
4. `source path/to/completion.{bash,zsh}` file depending on shell.
5. Try to complete `fastlane` command.

The same options should appear with and without these changes, while only making a single `sed` call.

### Others

Explanation of `sed` call:

- `-E`: enables extended regexp
- `-n`: disables output unless specifically enabled with `/p`.
- `s/^\s*lane\s+:(\S+).*$/\1/p`: matches whole lines that have a `lane :<lane_name> ...` format and prints only `<lane_name>` ([explanation of RegExp strings](https://www.gnu.org/software/sed/manual/sed.html#ERE-syntax)).

### CODE REVIEW

**Comment by mcornella** [comment]
@googlebot I signed it!

**Review by joshdholtz — COMMENTED** [review]
@mcornella This looks like a great change! I've actually never used this completions before (🤦‍♂️) but I'm getting an issue where its only coming up with `update_fastlane` 😬 Do you have any idea why this would be?

**Comment by mcornella** [comment]
> I'm getting an issue where its only coming up with `update_fastlane` 😬 Do you have any idea why this would be? 

Hmm it has to be an issue with the sed command using some syntax that's not truly portable. What platform/version are you running, and what are the Fastfile contents?

**Comment by joshdholtz** [comment]
> > I'm getting an issue where its only coming up with `update_fastlane` 😬 Do you have any idea why this would be?
> 
> Hmm it has to be an issue with the sed command using some syntax that's not truly portable. What platform/version are you running, and what are the Fastfile contents?

I'm running on macOS (tried on both Big Sur and Monterey).  Here is a sample `Fastfile` 👇 

```ruby
lane :test_ios do
  scan(
    scheme: "TestAllPlatforms (iOS)",
    devices: ["iPhone 12"]
  )
end

lane :test_tvos do
  scan(
    scheme: "TestAllPlatformsTV",
    devices: ["Apple TV"]
  )
end

lane :test_both do
  scan(
    scheme: "TestAllPlatformsTV",
    devices: ["iPhone 12", "Apple TV"]
  )
end
```

Is there a good way for me to debug this?

**Comment by mcornella** [comment]
A fast way to iterate on the sed command is to run it directly. Does this one work?
```sh
sed -n 's/^\s*lane\s\+\:\(\S\+\).*$/\1/p' Fastfile
```

**Comment by joshdholtz** [comment]
> A fast way to iterate on the sed command is to run it directly. Does this one work?
> 
> ```shell
> sed -n 's/^\s*lane\s\+\:\(\S\+\).*$/\1/p' Fastfile
> ```

Nope nope, that doesn't output anything for me 😱

**Comment by mcornella** [comment]
Huh, it looks like its a lack of support for extended character groups, this seems to work for me:
```
sed -En 's/^ *lane +:([^ ]+).*$/\1/p' Fastfile
```

**Comment by joshdholtz** [comment]
> Huh, it looks like its a lack of support for extended character groups, this seems to work for me:
> 
> ```shell
> sed -En 's/^ *lane +:([^ ]+).*$/\1/p' Fastfile
> ```
> 
> EDIT: we should also support tab-indentation, so this is better:
> 
> ```shell
> sed -En 's/^[ 	]*lane +:([^ ]+).*$/\1/p' Fastfile
> ```

Looks like that command works for me now 🙌 

```sh
➜  TestAllPlatforms git:(main) ✗ sed -En 's/^[  ]*lane +:([^ ]+).*$/\1/p' fastlane/Fastfile 
test_ios
test_tvos
test_both
```

**Comment by mcornella** [comment]
This is ready to merge I think.

**Review by joshdholtz — APPROVED** [review]
This looks great to me! Thank you so much for fixing this ❤️

**Pull request merged**
