### PR TITLE
[fastlane] add test workflow for GitHub Actions to plugin template

### PR DESCRIPTION
**Pull request by yutailang0119**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

The template generated by `new_plugin` has files for Travis CI and Circle CI.
GitHub Actions can be used for these same purposes.
GitHub Actions is useful because they can be used once repository is hosted on GitHub.

### Description

I add `.github/workflows/test.yml` to plugin template.
This is the file to run test in GitHub Actions.

### CODE REVIEW

**Comment by yutailang0119** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
Înteresting! Do you have a repo where this GitHub Action workflow is active so we can look at the result?

**Comment by yutailang0119** [comment]
Yes! Using it in my plugin [yutailang0119/fastlane-plugin-mackerel_api](https://github.com/yutailang0119/fastlane-plugin-mackerel_api).

The execution result is this: https://github.com/yutailang0119/fastlane-plugin-mackerel_api/actions/runs/107070498

Events that trigger workflow is customized, but it works the same.

**Review by janpio — APPROVED** [review]
This looks amazing!

**Review by nafu — APPROVED** [review]
This looks great 👍 

JFYI:
`Execute tests on macOS (Xcode 9.4.1, Ruby 2.4)` was failed but it was passed after I've rebuilt it 🙆‍♀️

**Pull request merged**
