### PR TITLE
Add workspace command line option to slather action

### PR DESCRIPTION
**Pull request by jschneier**
Hello!

Slather grew a `--workspace` flag in order to support Xcode 7.3 so I have added this option to the slather action. Let me know if I missed anything.

### CODE REVIEW

**Comment by mekanics** [comment]
+1

**Comment by jschneier** [comment]
@KrauseFx look okay?

**Comment by asfalcone** [comment]
@jschneier Is there a specific version that this flag was added in? Do we worry about passing `--workspace` to an older version of slather?

**Comment by jschneier** [comment]
@asfalcone 2.1.0...so a few days ago? It will fail with an older version. What is Fastlane's policy on handling this sort of thing? Seems like a nightmare to do anything more than document the change.

**Comment by jschneier** [comment]
@asfalcone this patch + Slather 2.1.0 enables me to run coverage again with Fastlane. I'm eager to get this merged, let me know if there is anything else you need!

**Comment by vpolouchkine** [comment]
Hey @jschneier — thanks for the PR! Would you mind opening a new Issue to discuss this change? Ideally, we want folks to do that before writing any code (per https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md#pull-requests-prs). Much appreciated!

**Comment by jschneier** [comment]
@vpolouchkine done at  #4165

**Comment by palusik86** [comment]
+1 Please merge :-)

**Comment by omni5cience** [comment]
Is there anything blocking this? Test coverage data is a pretty big part of our workflow!

**Comment by asfalcone** [comment]
Thanks all for the interest in this PR! We're discussing internally how we can best support different versions of Slather (and any other dependency we have). When this PR is merged, the action would only work with the latest which might be bad for some folks!

**Comment by jschneier** [comment]
@asfalcone thanks for letting us know that there is a discussion going on! I'm not a native rubyist but I guess I'd assume that if you do not specify a `--workspace` option then it simply wouldn't use it. Thus this change would be backwards compatible for all.

**Comment by asfalcone** [comment]
@jschneier you are very right! I just noticed that it was optional. Sorry for the delay on this one :+1:

**Comment by mrudulp** [comment]
when does this get released to the community? I am on 1.81.0 right now, with autoupdate enabled.
Any workaround for workspace apart from using sh?

**Comment by jschneier** [comment]
personally I am pointing my Gemfile at HEAD. or you could point it at a SHA.

**Comment by asfalcone** [comment]
Hoping to get to a release today! Stay tuned 📻

**Comment by asfalcone** [comment]
fastlane [`1.82.0`](https://github.com/fastlane/fastlane/releases/tag/1.82.0) was released today!

**Pull request merged**
