### PR TITLE
[fastlane] Improved handling of new lines in increment_build_number

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/commit/8a3d7af92eb2d78013dd1543041a25f5fcdf913b#commitcomment-17584735

### CODE REVIEW

**Comment by natanrolnik** [comment]
Great!

**Comment by asfalcone** [comment]
@KrauseFx Build is still failing with 
```
undefined method `strip' for 24:Fixnum
```

Can you also maybe add a test for this? 🙏

**Comment by KrauseFx** [comment]
That's the test that is catching this, so we're good, pushing a fix now 👍

**Comment by asfalcone** [comment]
I was thinking that adding a [test like this one](https://github.com/fastlane/fastlane/blob/master/fastlane/spec/actions_specs/increment_build_number_action_spec.rb#L16) but with a new line or space would helpful for the future.

Looks good to me though! 👍

**Comment by KrauseFx** [comment]
Awww, good point, adding one now

**Comment by KrauseFx** [comment]
Added tests and also updated sibling action

**Comment by asfalcone** [comment]
😍  so good!

**Pull request merged**
