### PR TITLE
Add documentation about the fastlane directory behavior

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @KrauseFx</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
Nope @fastlane-bot-helper

**Review by mfurtak — APPROVED** [review]

**Comment by KrauseFx** [comment]
@mfurtak is there any language changed you'd like me to work in, before I submit the same PR to fastlane/docs?

**Comment by KrauseFx** [comment]
Or anything we should add? Feel free to update the PR directly

**Comment by KrauseFx** [comment]
@mfurtak just waiting for confirmation before I hit that merge button and send the PR to fastlane/docs

**Comment by mfurtak** [comment]
Sorry - I like it! :ship:

**Comment by KrauseFx** [comment]
https://github.com/fastlane/docs/pull/317

**Pull request merged**
