### PR TITLE
Better failure/success messaging from precheck

### LINKED ISSUE #10036: precheck unclear error message
screen shot 2017-08-11 at 1 47 30 pm

Steps to reproduce
1. `fastlane deliver init` for any app
2. `fastlane deliver --force`

Expected result:
Successful upload with some kind of success message

Actual result:
For the user it looks like the build failed, and it wasn't successful, it took me a while to figure that out

### PR DESCRIPTION
**Pull request by taquitos**
fixes https://github.com/fastlane/fastlane/issues/10036
also fixes an issue where some precheck warnings weren't being shown

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Can you also append a screenshot of how this looks like in an error/success case?

**Comment by taquitos** [comment]
error
warn only

**Comment by KrauseFx** [comment]
So good ❤

**Comment by taquitos** [comment]
@KrauseFx thanks for reporting this 👍

**Pull request merged**
