### PR TITLE
[sigh][match][spaceship] add missing inhouse to mac profile types

### LINKED ISSUE #20352: [regression] Match Catalyst and Mac for enterprise is unable to find cert
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: hard to tell it took me quite time to debug this and i do not remember
- Last working version: 2.18x.x
I think this broke this functionality - PR #16158

### Regression Description
I was able to refresh my enterprise profiles for catalyst some time ago. I'm always running with latest fastlane version. 
Somewhere around 03/Jun/22 i noticed that something is not working fine.
It turned out that my Enterprise Profile restore lane was broken.

It's unable to find an Enterprise cert and instead match is looking for AppStore one, even if parameters are dumped correctly in logs. I my guess are connected with those lines.
https://github.com/fastlane/fastlane/blob/a0ac307f2ee7db3d372ad561045565e507b39834/sigh/lib/sigh/download_all.rb#L45

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>```
+----------------------------------------+----------------------------------------------------------------+
|                                        Summary for match 2.206.2                                        |
+----------------------------------------+----------------------------------------------------------------+
| type                                   | enterprise                                                     |
| platform                               | catalyst                                                       |
| app_identifier                         | ["some.app.id"]                                                |
| team_id                                | TeAmID                                                         |
| git_branch                             | enterprise                                                     |
| shallow_clone                          | true                                                           |
| readonly                               | false                                                          |
| force_for_new_devices                  | true                                                           |
| force                                  | false                                                          |
| generate_apple_certs                   | true                                                           |
| skip_provisioning_profiles             | false                                                          |
| username                               | user.email@evilcorp.com                                        |
| storage_mode                           | git                                                            |
| git_url                                | git@github.com:evilcorp/fastlane-apple-codesigning.git         |
| clone_branch_directly                  | false                                                          |
| skip_google_cloud_account_confirmation | false                                                          |
| keychain_name                          | login.keychain                                                 |
| include_all_certificates               | false                                                          |
| force_for_new_certificates             | false                                                          |
| skip_confirmation                      | false                                                          |
| safe_remove_certs                      | false                                                          |
| skip_docs                              | false                                                          |
| derive_catalyst_app_identifier         | false                                                          |
| fail_on_name_taken                     | true                                                           |
| skip_certificate_matching              | false                                                          |
| skip_set_partition_list                | false                                                          |
| verbose                                | false                                                          |
+----------------------------------------+----------------------------------------------------------------+

[13:23:51]: Cloning remote git repo...
[13:23:51]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[13:23:55]: Checking out branch enterprise...
[13:23:55]: 🔓  Successfully decrypted certificates repo
[13:23:55]: Verifying that the certificate and profile are still valid on the Dev Portal...
[13:23:57]: Installing certificate...

+-------------------+-------------------------------------------+
|                     Installed Certificate                     |
+-------------------+-------------------------------------------+
| User ID           | TeAmID                                    |
| Common Name       | iPhone Distribution: Evil Corp            |
| Organisation Unit | TeAmID                                    |
| Organisation      | Evil Corp                                 |
| Country           | US                                        |
| Start Datetime    | 2021-08-11 12:53:19 UTC                   |
| End Datetime      | 2024-08-10 12:53:18 UTC                   |
+-------------------+-------------------------------------------+

+-------------------------------------+--------------------------------------------------------+
|                                   Summary for sigh 2.206.2                                   |
+-------------------------------------+--------------------------------------------------------+
| app_identifier                      | some.app.id                                            |
| username                            | user.email@evilcorp.com                                |
| force                               | false                                                  |
| cert_id                             | CERT1234CODE                                           |
| provisioning_name                   | match InHouse some.app.id catalyst                     |
| ignore_profiles_with_different_name | true                                                   |
| team_id                             | TeAmID                                                 |
| fail_on_name_taken                  | true                                                   |
| include_all_certificates            | false                                                  |
| platform                            | catalyst                                               |
| adhoc                               | false                                                  |
| developer_id                        | false                                                  |
| development                         | false                                                  |
| skip_install                        | false                                                  |
| skip_fetch_profiles                 | false                                                  |
| skip_certificate_verification       | true                                                   |
| readonly                            | false                                                  |
+-------------------------------------+--------------------------------------------------------+

[13:23:58]: Starting login with user 'user.email@evilcorp.com'
[13:24:00]: Successfully logged in
[13:24:00]: Fetching profiles...
[13:24:00]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[13:24:04]: Creating new provisioning profile for 'some.app.id' with name 'match InHouse some.app.id catalyst' for 'catalyst' platform
[13:24:04]: No certificates for filter: Certificate ID: 'CERT1234CODE' 
+------------------------------------+--------------------------------------------------------------------------------------+
|                                                       Lane Context                                                        |
+------------------------------------+--------------------------------------------------------------------------------------+
| PLATFORM_NAME                      |                                                                                      |
| LANE_NAME                          | refresh_office_app_enterprise                                                        |
| SIGH_PROFILE_TYPE                  | enterprise                                                                           |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"some.app.id"=>"match InHouse some.app.id"} |
+------------------------------------+--------------------------------------------------------------------------------------+
[13:24:04]: Could not find a matching code signing identity for type 'AppStore'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide. If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert```
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 12.4                                             |
| Ruby                        | 2.6.3                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.32.1 (Apple Git-133)               |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane             |
| Host                        | macOS 12.4 (21F79)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.5.app/Contents/Developer/ |
| Xcode Version               | 13.4                                             |
| Swift Version               | 5.6.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | pl_PL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                       | Version   | Update-Status  |
| -------------------------------------------- | --------- | -------------- |
| fastlane-plugin-refresh_provisioning_profile | 0.1.5     | 💥 Check failed |
| fastlane-plugin-tmp_keychain                 | undefined | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| rexml                           | 3.2.5        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| bundler                         | 2.3.13       |
| simctl                          | 1.6.8        |
| jwt                             | 2.3.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.5.0        |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.36.2       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.595.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.0        |
| aws-sdk-core                    | 3.131.1      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| json                            | 2.6.2        |
| webrick                         | 1.7.0        |
| forwardable                     | 1.2.0        |
| logger                          | 1.3.0        |
| date                            | 2.0.0        |
| stringio                        | 0.0.2        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.0.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.1.0        |
| strscan                         | 1.0.0        |
| io-console                      | 0.4.7        |
| fileutils                       | 1.1.0        |
| etc                             | 1.0.1        |
| racc                            | 1.6.0        |
| nokogiri                        | 1.13.6       |
| psych                           | 3.1.0        |
</details>

*generated on:* **2022-06-03**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by DuMaM**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This resolves #20352 

### Description
I added missing inhouse definitions for MacOS platfrom.

### CODE REVIEW

**Comment by DuMaM** [comment]
@joshdholtz  This is not ready, and I'm unable to find a bug here :(

**Comment by joshdholtz** [comment]
Oh, my bad! Was this still a work in progress PR?! 😱

**Comment by DuMaM** [comment]
No, no. Feel free to edit. I stuck on it and wasn't able to fix it by myself.

**Comment by DuMaM** [comment]
In monday I will be able to test it out if your changes fixes my issue :)

**Comment by DuMaM** [comment]
```
[!] The request could not be completed because:
        Unable to process request - PLA Update available - You currently don't have access to this membership resource. To resolve this issue, your team's Account Holder,<holder name>, must agree to the latest Program License Agreement.
```
Yay! Something got changed :D
I reached my account holder for help here and we will see if this works.

**Comment by DuMaM** [comment]
Ok, we fixed this issue and this is working now 🎉

**Review by joshdholtz — APPROVED** [review]
Thanks for finding that these were missing! ❤️

**Comment by DuMaM** [comment]
Sorry to say but we need to revert this PR :( 
https://developer.apple.com/documentation/appstoreconnectapi/list_and_download_profiles

```
IOS_APP_DEVELOPMENT, IOS_APP_STORE, IOS_APP_ADHOC, IOS_APP_INHOUSE, MAC_APP_DEVELOPMENT, MAC_APP_STORE, MAC_APP_DIRECT, TVOS_APP_DEVELOPMENT, TVOS_APP_STORE, TVOS_APP_ADHOC, TVOS_APP_INHOUSE, MAC_CATALYST_APP_DEVELOPMENT, MAC_CATALYST_APP_STORE, MAC_CATALYST_APP_DIRECT
```

After we merge it, I found bug in my fastlane code which led to those problems.
I fixed it, and developer_id started to working as it supposed to.
I must admit I got confused by apple documentation.

Sorry for trouble 🙏 

cc: @joshdholtz

**Comment by joshdholtz** [comment]
@DuMaM Hey! It still seems like this might be okay to have in here 🙃 Unless something is specifically broken with this 🤷‍♂️ This adds more functionality with Apple ID auth. 

Does this PR break anything or just not needed by what you were doing?

**Comment by DuMaM** [comment]
No, it works fine. It basically adding something what it's unsupported in Apple Connect API, and may confuse people.
The only point in leaving it here, is to add some warning msg that there is no such thing like InHouse for enterprise Mac. They should use developer id instead.

**Pull request merged**
