### PR TITLE
[frameit] Do not only adjust the trim box for side-by-side text images

### LINKED ISSUE #15332: [Frameit] The keyword, title and device frame sometimes have a vertical offset with "stack_title" : true
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
This issue is similar to https://github.com/fastlane/fastlane/issues/10440 which focused on "stack_title" : false.
Now we have set "stack_title" to true, meaning the keyword is above the title. And these 2 text fields are stacked above the device frame.
The issue is that the vertical distances between the 2 text fields and between the title and the top of the frame. This depends whether the strings in the text fields have pixels below (e.g. the "g") the baseline of the text, or above it (like the "k").

The comparison between these 2 screenshots shows this clearly, by the dashed lines that we added:

iPhone-Xs-Max---before

I'll try to create the same solution with the `trim_boxes` as in https://github.com/fastlane/fastlane/issues/10440 for this vertical stacked situation.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
#
#  Fastfile
#  myTifi
#
#  Created by Martijn Koopman on 27/09/17.
#  Copyright © 2017 iMKapps. All rights reserved.
#
#  $Rev: 4769 $
#  $Date:: 2019-04-26 #$

before_all do
    # Set Xcode version
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode 10.1.app/Contents/Developer'
end

# Create a lane for SnapShot:
# Run this via Terminal via: fastlane screenshots
lane :screenshots do
    # Generate screenshots for the App Store:
    snapshot
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.130.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version      |
| --------------------- | ------------ |
| executable-hooks      | 1.3.2        |
| bundler-unload        | 1.0.2        |
| rubygems-bundler      | 1.4.4        |
| bundler               | 1.16.0       |
| slack-notifier        | 2.3.2        |
| rouge                 | 2.0.7        |
| xcpretty              | 0.3.0        |
| terminal-notifier     | 2.0.0        |
| multipart-post        | 2.0.0        |
| word_wrap             | 1.0.0        |
| public_suffix         | 2.0.5        |
| tty-cursor            | 0.5.0        |
| tty-spinner           | 0.8.0        |
| babosa                | 1.0.2        |
| colored               | 1.2          |
| commander-fastlane    | 4.4.6        |
| faraday               | 0.15.4       |
| http-cookie           | 1.0.3        |
| faraday-cookie_jar    | 0.0.6        |
| gh_inspector          | 1.1.3        |
| mini_magick           | 4.9.5        |
| rubyzip               | 1.2.2        |
| security              | 0.1.3        |
| naturally             | 2.1.0        |
| simctl                | 1.6.3        |
| jwt                   | 2.1.0        |
| declarative-option    | 0.1.0        |
| representable         | 3.0.4        |
| mime-types-data       | 3.2016.0521  |
| mime-types            | 3.1          |
| signet                | 0.11.0       |
| memoist               | 0.16.0       |
| os                    | 0.9.6        |
| googleauth            | 0.6.7        |
| httpclient            | 2.8.3        |
| google-api-client     | 0.23.9       |
| google-cloud-env      | 1.0.5        |
| google-cloud-core     | 1.3.0        |
| digest-crc            | 0.4.1        |
| google-cloud-storage  | 1.16.0       |
| emoji_regex           | 0.1.1        |
| tty-screen            | 0.6.4        |
| json                  | 2.1.0        |
| highline              | 1.7.10       |
| excon                 | 0.60.0       |
| CFPropertyList        | 2.3.6        |
| plist                 | 3.4.0        |
| atomos                | 0.1.3        |
| claide                | 1.0.2        |
| colored2              | 3.1.2        |
| nanaimo               | 0.2.6        |
| xcodeproj             | 1.10.0       |
| unf                   | 0.1.4        |
| domain_name           | 0.5.20170404 |
| faraday_middleware    | 0.12.2       |
| fastimage             | 2.1.1        |
| terminal-table        | 1.8.0        |
| unicode-display_width | 1.3.0        |
| addressable           | 2.5.2        |
| multi_json            | 1.13.1       |
| psych                 | 2.0.8        |
| retriable             | 3.1.1        |
| uber                  | 0.1.0        |
| declarative           | 0.0.10       |
</details>

*generated on:* **2019-09-18**
</details>

### PR DESCRIPTION
**Pull request by funnel20**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #15332

The keyword, title and device frame sometimes have a vertical offset with "stack_title" : true

### Description
**Solution to this issue**

Remove the condition to only adjust the trim box for side-by-side text images (i.e. when `stack_title` is false) in _editor.rb_.

**Before**
iPhone-Xs-Max---before

iPhone Xs Max - before highlighted

**After**
Screenshot 2019-09-20 at 11 44 23

**Improvement**
While running with `--verbose`, the `UI.Verbose()` statements display a reference to the trim box object, instead of the data:

> Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x007fb0ac494da0>

This has been solved by adding a new method `json_string_format` to Class _trim_box.rb_ that returns the trimbox parameters in a human readable JSON string format:

> Trim box for key "keyword" is adjusted to align bottom: {"width" : 857, "height" : 87 , "offset_x" : 2463, "offset_y" : 1025}

### Testing Steps
For proper debugging, added the yellow highlight again by adding the follow temporary lines to `text_image.combine_options do |i|` of `put_title_into_background()` in `editor.rb`:
```
i.background 'yellow'
i.alpha 'remove'
```

### CODE REVIEW

**Comment by janpio** [comment]
Is my title edit valid?

**Comment by funnel20** [comment]
> Is my title edit valid?

Yes

**Comment by funnel20** [comment]
Guys, what needs to be done to get my PR reviewed (a few lines of code)?

Waiting 10 weeks without any progress, while there are weekly releases, doesn't feel like a reward for investing time in improving your product.

**Review by rogerluan — APPROVED** [review]
I don't know that much about frameit, but by reviewing code & documentation this change makes sense to me 👍 
Also thanks for providing screenshots of your changes! 🙏

**Comment by funnel20** [comment]
@janpio & @rogerluan Thank you for finally merging my changes. 
I must admit that I stopped contributing to your project after the long idle status, as my input felt as a waste of time.

**Review by joshdholtz — APPROVED** [review]
I'm soooo sorry this got left for so long 😔 There is no excuse for this. I do really appreciate your contribution and having this not merged for so long is not my intent. I need to do a better job at maintaining and showing appreciation for our dedicated contributors. I'm looking at my processes and going to make sure this doesn't happen anymore going forward. Thank you, again ❤️

**Comment by funnel20** [comment]
> I'm soooo sorry this got left for so long 😔 There is no excuse for this. I do really appreciate your contribution and having this not merged for so long is not my intent. I need to do a better job at maintaining and showing appreciation for our dedicated contributors. I'm looking at my processes and going to make sure this doesn't happen anymore going forward. Thank you, again ❤️

Although I'm still disappointed, at least there is some relief that this solution has been finally merged after more than 2 years.
And I hope that your good intentions will set new standards for Google.

**Pull request merged**
