### PR TITLE
Update app only if we uploaded a new icon

### PR DESCRIPTION
**Pull request by vronin**

### CODE REVIEW

**Comment by vronin** [comment]
I signed it!

**Comment by vronin** [comment]
BTW. I think it solves another problem too. Right now, each time when delivery happens it will update version of an application prepared for submission.

**Review by KrauseFx — APPROVED** [review]
Nice, this is a great improvement 👍 Saving time 🚀

**Comment by vronin** [comment]
@KrauseFx Thank you :)

**Pull request merged**
