### PR TITLE
[docs] regenerate AvailaiblePlugins

### PR DESCRIPTION
**Pull request by hjanuschka**
as told in #6563

### CODE REVIEW

**Comment by milch** [comment]
That AvailablePlugins.md is woefully out of date, I think we just haven't kept it updated because it's automatically generated on docs.fastlane.tools anyway. 

Maybe instead of manually fixing that file, could you regenerate it using the rake task? https://github.com/fastlane/fastlane/blob/master/fastlane/Rakefile

**Comment by hjanuschka** [comment]
@milch  done

**Review by milch — APPROVED** [review]

**Comment by milch** [comment]
Great, thanks! 🚀

**Comment by KrauseFx** [comment]
We actually kind of moved this file to [docs.fastlane.tools](https://docs.fastlane.tools). Should we also deprecate the docs and link to the new page? 👍

**Pull request merged**
