### PR TITLE
[ci] fix CircleCI builds by adding back `ruby_version` parameter to the workflows

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)

### Motivation and Context

CircleCI hasn't been running in PRs or master, or it's intermittent at its best. E.g.:

image

This regressed when we merged this PR of mine: https://github.com/fastlane/fastlane/pull/21735

### Description

What is weird is that it was sometimes running and sometimes not running anymore, in master, see `4/4` (CircleCI didn't run) vs `5/5` (CircleCI ran):

image

Moving forward we really need to add CircleCI to the list of **required** checks in this repo.

I also took the opportunity to change the super vague name of the workflow from `build` to `Run Tests & Checks`:

image

### Testing Steps

Pass CI and check that CircleCI ran in this PR.

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
> Moving forward we really need to add CircleCI to the list of required checks in this repo.

100% yes!

> I also took the opportunity to change the super vague name of the workflow from build to Run Tests & Checks:

Thanks for that! 👍  Much clearer indeed.

**Comment by AliSoftware** [comment]
With the CI fixed, now it finds 4 lint violations—which were likely introduced by other PRs, back when the CI was not always running the linter, letting those go thru the cracks. We should probably use the occasion of this PR to fix those violations.

**Comment by rogerluan** [comment]
@AliSoftware I actually had opened a separate PR for those 😅 do you mind? https://github.com/fastlane/fastlane/pull/21747

**Comment by AliSoftware** [comment]
> I think we should merge that one first, then rebase this one and see if everything passes 👀

Yep, especially since the PR where you fixed those violations only ran the 4 checks, not 5:
image

So merging this PR first then rebasing https://github.com/fastlane/fastlane/pull/21747 on top should hopefully fix it.

**Comment by rogerluan** [comment]
All good @AliSoftware 💪 

image

**Pull request merged**
