### PR TITLE
spaceship and deliver: add support for the 10.5" iPad

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/11267

### CODE REVIEW

**Comment by KrauseFx** [comment]
```
Spaceship::Client::UnexpectedResponse: [!] [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it.
```

Mh, need to take a closer look into this

**Comment by KrauseFx** [comment]
Alright, pushed and can confirm it works now 👍

**Comment by milch** [comment]
Maybe rebase first?

**Comment by KrauseFx** [comment]
Why? What? :)

**Review by milch — APPROVED** [review]

**Comment by funnel20** [comment]
I just saw this title in the Release Notes of 2.75.0.
I was thinking "what, is there a new iPad???".

Apparently that depends on the definition of "new". While looking at the commits, it appears to be referring to the iPad 10.5" display size, as released by Apple in June 2017.

Can you please change this issue's title to:
"spaceship and deliver: add support for the 10.5" iPad"

**Comment by KrauseFx** [comment]
Done @funnel20, sorry you had to look into it :)

**Comment by funnel20** [comment]
@KrauseFx  No need to apologise.
I'm just happy I didn't miss an Apple announcement while failing to update my apps 😃

**Comment by KrauseFx** [comment]
Hehe, makes sense :)

**Pull request merged**
