### PR TITLE
[sigh] support macOS and Developer ID in get_provisioning_profile action

### PR DESCRIPTION
**Pull request by mjm**
🔑 

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
I really want Fastlane to have good support for building macOS apps (#13573). One piece of low-hanging fruit is getting provisioning profiles.

### Description
A lot of support is already present in Fastlane for macOS provisioning profiles, so this is mostly a matter of fixing a few issues on the edges. It adds checks on the profile type so that we use the right file extension (`.mobileprovision` vs. `.provisionprofile`). It also adds an option to Sigh for Developer ID certificates in addition to the existing types.

I also needed to make a change to the class names for Developer ID certificates in Spaceship: `DeveloperID -> DeveloperId`. This is to support the automatic class name inference that Spaceship does, so that `Spaceship.certificate.developer_id_application` maps to the right class, for instance.

With these changes, you can successfully use `sigh` in Fastlane to get a Developer ID provisioning profile for a macOS app:

```
get_provisioning_profile(
  developer_id: true,
  platform: 'macos'
)
```

### CODE REVIEW

**Comment by mjm** [comment]
I signed it!

**Review by joshdholtz — APPROVED** [review]
That is fantastic 🙌 I'm also down for adding more mac support 😊 Thanks for the contribution!

**Comment by mjm** [comment]
Awesome! In that case, expect more PRs around this coming soon!

**Comment by joshdholtz** [comment]
@mjm Looking forward to it 😊 🚀

**Pull request merged**
