### PR TITLE
Add support for --quiet option for swiftlint action

### PR DESCRIPTION
**Pull request by mgrebenets**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Add support for `swiftlint`'s `--quiet` option.

### Motivation and Context
Allow users to have quiet `swiftlint` runs to reduce console output.

### CODE REVIEW

**Review by hjanuschka — DISMISSED** [review]

**Comment by mgrebenets** [comment]
@hjanuschka Thanks for approving! I've added one last touch to it - check that `--quiet` is supported (needs to be at least `0.9.0`) and display important message otherwise.

**Comment by hjanuschka** [comment]
like putting this:

```
if params[:quiet]
          if version < Gem::Version.new('0.9.0') and !Helper.test?
            UI.important("Your version of swiftlint (#{version}) does not support '--quiet' option.\nThe option will be ignored.\nUpdate swiftlint to 0.9.0 or above using `brew update && brew upgrade swiftlint`")
          else
            command << " --quiet"
          end
        end
```

into a method - returning "--quiet" or nothing, and do a `command << new_method_name(params)`.

this should work around the rubocop `PerceivedComplexity` problem

**Comment by mgrebenets** [comment]
@hjanuschka Added `supported_option_switch` function, that now handles `--strict` and `--quiet` switches.

**Comment by hjanuschka** [comment]
@mgrebenets that looks really nice, i think you have to add the action as an exception to the unused options spec here -> https://github.com/fastlane/fastlane/blob/master/fastlane/spec/unused_options_spec.rb#L4 to get CI to green.

**Review by hjanuschka — APPROVED** [review]

**Comment by mfurtak** [comment]
This is great! If you're feeling up to it, it would be awesome to get a test case covering the "unhappy path" where the option is omitted. 👍

**Comment by mgrebenets** [comment]
@mfurtak I have added 2 more specs for `strict: false` and `quiet: false` uses.
Is that what you mean?

It seems for the case where `quiet` or `strict` are omitted there is `"default use case"` spec.

**Comment by mfurtak** [comment]
Ah, sorry for not being more specific... I was thinking about the case when you have asked for `--quiet`, but the current version of the lib is not new enough.

**Review by mfurtak — APPROVED** [review]
👍

**Pull request merged**
