### PR TITLE
Update snapshot to support both Swift 3 and Swift 2.3

### PR DESCRIPTION
**Pull request by KrauseFx**
screenshot 2016-09-20 17 19 30

### CODE REVIEW

**Review by mfurtak — APPROVED** [review]
👍

**Comment by KrauseFx** [comment]
We should do a release for this

**Comment by huguesbr** [comment]
@KrauseFx isn't it `Swift 3` only? it doesn't seem to have any compiler check for `2.3` vs `3.0`? doesn't work for me on `2.3`

**Comment by huguesbr** [comment]
Hum, in fact didn't look carefully enought, I thought it was via compiler directive, but it's 2 differents file... `snapshot update` didn't create both file, but backuping old `Snapfile` and running `snapshot init` did regenerate both. thx

**Pull request merged**
