### PR TITLE
[pem] download certificates if they exist 🎟

### PR DESCRIPTION
**Pull request by hjanuschka**
as described here -> https://github.com/fastlane/fastlane/issues/7050
let me know if this is ok for you guys!

### CODE REVIEW

**Comment by asfalcone** [comment]
@hjanuschka Is this different than what @KrauseFx was mentioning in this issue? https://github.com/fastlane/fastlane/issues/4309#issuecomment-221153594

**Comment by hjanuschka** [comment]
we'll just try it - the p12 downloads and seems to be valid.
i ll setupa sample app and verify it

**Comment by KrauseFx** [comment]
As far as I know there is no way to download an existing private key file from the Apple Developer Portal

**Comment by hjanuschka** [comment]
@KrauseFx  ok tested it - it seems to be a valid p12 cert but it doesnt work so i guess i ll close this PR now

**Pull request closed without merging**
