### PR TITLE
Possibility to create/delete a Passbook id (Pass Type IDs)

### PR DESCRIPTION
**Pull request by dgyesbreghs**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
**Why is this change required? What problem does it solve?**
It's giving the user the possibility to create/delete Passbook IDs (PassType IDs) through fastlane.

**Please describe in detail how you tested your changes.**
I've tested it with the following use cases + i've wrote a couple of unit tests to make sure everything keeps working.
- Create a PassType ID
- Delete a PassType ID
- Retrieve all the PassType IDs

### Description
I created the model called Passbook to perform the following actions:
- Retrieve all Passbook IDs
- Find a Passbook by ID
- Create a Passbook ID
- Delete a Passbook ID

I've modified the portal_client class to perform the right requests. To make sure everything keeps working, i've created a spec called 'passbook_spec' to test the above actions.

### CODE REVIEW

**Comment by dgyesbreghs** [comment]
Can someone please review this?

**Comment by ohayon** [comment]
Hey @dgyesbreghs - thanks for the PR we are definitely going to take a good look at this! At first glance it looks 💯 ! One initial question I have is, are you calling into _spaceship_ directly to access this new API you wrote? Do you think that there should be some sort of action or option passed to another tool to handle this use case? Thanks again! 🚀 🐙

**Comment by dgyesbreghs** [comment]
Hi @ohayon. Yes, i'm using spaceship directly to access this new API. But it's definitely a great idea to create a new action.

**Comment by ohayon** [comment]
👍  No rush to make that new action @dgyesbreghs - we can definitely get this merged in without an action hooked up to it. 

Would you mind adding some docs to https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md so that people know this new API is available?

**Review by ohayon — CHANGES_REQUESTED** [review]
👍 No rush to make that new action @dgyesbreghs - we can definitely get this merged in without an action hooked up to it.

Would you mind adding some docs to https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md so that people know this new API is available? 📓

**Comment by dgyesbreghs** [comment]
I've added some examples to the [DeveloperPortal.md](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md). Is this enough information?

**Review by ohayon — APPROVED** [review]

**Comment by ohayon** [comment]
@dgyesbreghs This is so awesome! Thank you so much for this. Its a really high-quality contribution 💎 . Happy to have you in the _fastlane_ community! 🚀

**Comment by dgyesbreghs** [comment]
@ohayon No problem! I love the work you're guys are doing 🎉 🚀

**Comment by proorlov** [comment]
@dgyesbreghs thank you for possibility to create/delete a Passbook id.
Is there possibility to create/delete Pass Type Id Certificates?

**Pull request merged**
