### PR TITLE
Hide timestamp by default

### PR DESCRIPTION
**Pull request by KrauseFx**
screenshot 2016-05-24 18 27 20

Remove time stamps by default from each row, you can still enable it manually though.

screenshot 2016-05-24 18 27 23

Please vote  👎 or  👍  using the emoji buttons below

### CODE REVIEW

**Comment by mfurtak** [comment]
Interesting. I thought I would be in favor of this, but now that I see it, I think I'm not :smile:

**Comment by KrauseFx** [comment]
Alright, I'll leave this open for a few more days and then we can decide 👍

**Comment by truth3** [comment]
I think they are mostly helpful for debug purposes.. especially with summary report on time saved, so I would say default should be hidden, and enable if / when needed.

**Comment by jeanregisser** [comment]
Nice! I use fastlane with TeamCity where the output is already timestamped so was getting duplicated info.

Up until now I was monkey patching the log command from the Fastfile:

```ruby
if ENV['TEAMCITY_PROJECT_NAME']
  class << Helper
    alias_method :orig_log, :log

    # Don't add the datetime for TeamCity since it already displays it
    def log(*args)
      logger = orig_log(*args)
      logger.formatter = proc do |severity, datetime, progname, msg|
        "#{msg}\n"
      end
      logger
    end

  end
end
```

So would love to see your official addition integrated to get rid of my fragile workaround 👍

**Comment by KrauseFx** [comment]
It seems like the vote is 50/50, so what we could do is to have an environment variable to remove the timestamp. How do you like that?

**Comment by mfurtak** [comment]
:ship: it!

**Pull request merged**
