### PR TITLE
Added require for 'addressable'

### PR DESCRIPTION
**Pull request by taquitos**
Fixes issue found in https://github.com/fastlane/fastlane/issues/11027

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Always good to require more stuff

**Review by ohayon — APPROVED** [review]

**Comment by funnel20** [comment]
@KrauseFx Aren't we going to fast here? The root cause is not clear, because the issue doesn't occur at each setup. See https://github.com/fastlane/fastlane/issues/11027#issuecomment-350546217

**Comment by taquitos** [comment]
Using classes from `addressable` only works if we've loaded that requirement. Since we don't actually explicitly load it in by requiring it in the `Precheck` module, it's most likely not going to be loaded when we run that rule. 

I don't think fixing issues by `requiring` a certain dependency that we have listed in our gemspec is going too fast. We want an explicit require because it's generally accepted as the right thing to do. It prevents strange flaky behavior (like that comment points out) that can vary depending on ruby version, and environment. The key here is making sure you don't implicitly depend on something.

**Comment by funnel20** [comment]
@taquitos Please don't should the messenger, I only repeat what @milch mentioned.

There was a 2nd solution by removing the dependency for `addressable`:

> Replace Addressable::URI by URI

Wouldn't that be a cleaner solution?

**Comment by taquitos** [comment]
@funnel20, not shooting the messenger at all. I just wanted to clarify why that `require` seems reasonable to me. 

Replacing `Addressable::URI` seems pretty subjective to me. On one hand, URI is provided by the system, on the other, `Addressable::URI` supposedly is a better URI implementation (but probably doesn't matter for us?). I prefer to leave things as they are if they work. In this case, since we've had `Addressable` as a dependency for a while, I feel comfortable leaving it in there now, but just making sure it doesn't break in the meantime for people where the implicit reference doesn't work right.

**Comment by KrauseFx** [comment]
Ah sorry for confirming so fast @funnel20, I didn't have all the context and just assumed adding a missing `require` is okay. Is that something we should revert and re-consider you think?

**Comment by funnel20** [comment]
@taquitos The current code (and also your PR) uses both `Addressable::URI` and `URI` within 3 lines:
https://github.com/fastlane/fastlane/blob/91f7f5e6271dfc7e725b778529a2b95ea91dd6c2/precheck/lib/precheck/rules/unreachable_urls_rule.rb#L28

https://github.com/fastlane/fastlane/blob/91f7f5e6271dfc7e725b778529a2b95ea91dd6c2/precheck/lib/precheck/rules/unreachable_urls_rule.rb#L30

This is not consistent.

These URL prechecks did work until a few weeks ago, while the require `Addressable` was never in this file. So maybe it was defined in a higher level Fastlane file.
It might be removed for whatever reason, so precheck fails and issue #11027 is created. But maybe other issues are caused by this removal too. 
Hence I think it's important to find the root cause, and not immediately apply for a (local) solution. That's why the discussion was still pending.

**Comment by funnel20** [comment]
@KrauseFx Hi Felix, I made my first Fastlane contribution last week (see #10440) and I encountered quite some proceses and procedures. Initially annoying, but of course I can understand why these are in place; to create robust and maintainable code. I'm a Ruby newbie, so luckily @ohayon helped me a lot to deliver the best solution: https://github.com/fastlane/fastlane/pull/11124#issuecomment-350068913.

I'm a bit puzzled why we are having this conversation in this PR, because this PR shouldn't exist (yet).
The discussion in issue #11027 is still pending, and several solutions were provided. Out of the blue someone who is not involved in the discussion (@taquitos) creates a PR, which is approved by you, based on assumptions and no context.

This doesn't look like a solid procedure. It seems best to put this PR on hold, and we go back to the original issue #11027 to continue the discussion. Correct me if I'm wrong.

**Comment by taquitos** [comment]
@funnel20 I think we're saying the same thing: I agree with you that it's important to find the root cause, and that's totally great that the conversation is ongoing. It sounds like you and @milch made some great progress, and a more thorough solution found. We want to keep the conversation rolling and in the original place.

The conversation I was hoping to keep in this PR is just around why we decided to merge this PR. Not at all meant to stop any other conversations around the root cause. Just this: let's get something in master that works for people and let you and the other contributors continue working towards a better solution. I apologize for merging something so quickly without jumping into that thread and discussing why we felt it was important.

Now, out of the blue isn't so out of the blue 😄 I sit next to @KrauseFx in SF, and occasionally we go through all issues and prs to make fixes in order to unblock people who are crashing or to help move things along. 

Just to clarify on your point:

> Out of the blue someone who is not involved in the discussion (@taquitos) creates a PR, which is approved by you, based on assumptions and no context.

I built the precheck tool, so I have quite a bit of context 😄 In the past I've seen similar errors which were fixed by requiring the missing dependency.

**Pull request merged**
