### PR TITLE
Version bump to 2.93.1

### PR DESCRIPTION
**Pull request by joshdholtz**
Auto-generated by fastlane 🤖

**Changes since release '2.93.0':**

* [supply] rollout can only be sent on track rollout (#12373) via Josh Holtz
* Set FastlaneCore::Globals.capture_output once (#12368) via Jerome Lacoste

### CODE REVIEW

**Comment by rezid** [comment]
nooooo !!!!!

**Comment by rezid** [comment]
we need this fix as soon as possible

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
@rezid why?

**Comment by dgruseck** [comment]
I would also appreciate a immediate release,
because we can not deploy to the google play store tracks internal, alpha or beta.
Thats the cause of a google api change described here #12372

**Comment by ima747** [comment]
Looks like the test failure was a result of a failure of deployment of the test, didn't get a a phase of execution. Can it be re-run?

gtk-runtime v2.24.10.20121010 [Approved]
gtk-runtime package files install completed. Performing other installation steps.
WARNING: Url has SSL/TLS available, switching to HTTPS for download
Downloading gtk-runtime 
  from 'https://downloads.sourceforge.net/gtk-win/gtk2-runtime-2.24.10-2012-10-10-ash.exe?download'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://downloads.sourceforge.net/gtk-win/gtk2-runtime-2.24.10-2012-10-10-ash.exe?download'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
The install of gtk-runtime was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\gtk-runtime\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - gtk-runtime (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\gtk-runtime\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by thiagotn** [comment]
Hello fellows! When version 2.93.1 will be released for download at https://github.com/fastlane/fastlane/releases?

**Comment by thiagotn** [comment]
Released! :smiley:

**Comment by dgruseck** [comment]
Thank you :tada:

**Pull request merged**
