### PR TITLE
Move frameit config to ~/.fastlane/frameit

### PR DESCRIPTION
**Pull request by KrauseFx**
More information here https://github.com/fastlane/fastlane/pull/7298

This will support both the old and the new path

### CODE REVIEW

**Review by mfurtak — APPROVED** [review]

**Comment by KrauseFx** [comment]
This requires #7298 to be merged and released 👍

**Comment by milch** [comment]
Rebased so tests will pass

**Comment by milch** [comment]
@KrauseFx Seems like you need to update the tests so this will pass

**Comment by KrauseFx** [comment]
Argh, this isn't merged yet, looking into this now

**Comment by KrauseFx** [comment]
Moved to https://github.com/fastlane/fastlane/pull/7743

**Pull request closed without merging**
