### PR TITLE
Fixed parallel upload locked due to temp file in ipa_file_analyser

### PR DESCRIPTION
**Pull request by philipp-heyse**
Ran into https://github.com/fastlane/fastlane/issues/1625

Would love to see this fixed in master.

### CODE REVIEW

**Comment by milch** [comment]
Hey @philipp-heyse, thanks for your contribution, and congrats on your first fastlane PR! 🚀  We hope you'll be inspired to submit many more.

I think this is probably a good idea, although while we're working on that piece of code - I think it'd probably be better to put the plist into a temporary directory created by `Dir.mktmpdir` instead of appending an MD5 hash and placing it in `/tmp`. Subsequent invocations of that method will always return a different temporary directory so should suit this use-case perfectly 👍

**Comment by philipp-heyse** [comment]
Thanks. I adapted the code by your suggestions.

**Comment by philipp-heyse** [comment]
Hey @milch, can you have another look at this?

**Review by milch — APPROVED** [review]

**Comment by milch** [comment]
@philipp-heyse Thanks, looks good now. We had a couple issues with Circle end of last week, but it should be working now - can you rebase to current master and push please, so that the tests will be triggered?

**Comment by milch** [comment]
@philipp-heyse Nevermind that, I just did it for you 👍

**Comment by philipp-heyse** [comment]
Thank you for your help!

**Pull request merged**
