### PR TITLE
[match] add missing git storage authentication parameters to nuke

### LINKED ISSUE #16405: `match nuke` doesn't use provided authentication info to clone certificates git repo
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`match development` can successfully clone the git repo using the provided information for authentication set in the ENV. But it seems that `match nuke` doesn't do the same thing. Based on the error log, I guess that by some reasons, it doesn't use token to clone the git repo, which leads to the authentication error.

##### Command executed
`bundle exec fastlane match nuke development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[20:04:34]: Successfully loaded '***/fastlane/Matchfile' 📄

+-----------------------+--------------------------------------------------------+
|                  Detected Values from './fastlane/Matchfile'                   |
+-----------------------+--------------------------------------------------------+
| git_url               | https://github.com/***.git |
| storage_mode          | git                                                    |
| type                  | development                                            |
| force_for_new_devices | true                                                   |
+-----------------------+--------------------------------------------------------+

[20:04:34]: Cloning remote git repo...
[20:04:34]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Cloning into '/var/folders/jy/nr9btfn56rg699g5zyj6l3180000gn/T/d20200430-30791-73wjaq'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[20:04:39]: Exit status: 128
[20:04:39]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[20:04:39]: Run the following command manually to make sure you're properly authenticated:
[20:04:39]: $ git clone https://github.com/***.git /var/folders/jy/nr9btfn56rg699g5zyj6l3180000gn/T/d20200430-30791-73wjaq

[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀
[20:08:35]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.24.2 (Apple Git-127)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E287)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.4.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "***")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.***") # The bundle identifier of your app
apple_id("***@outlook.com") # Your Apple email address

itc_team_id("***") # App Store Connect Team ID
team_id("***") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.146.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 1.17.2       |
| etc                       | 1.0.1        |
| forwardable               | 1.2.0        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.305.0      |
| aws-sigv4                 | 1.1.3        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.94.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.63.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.73.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.0       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details></pre>
</details>

### LINKED ISSUE #17347: Match Auth Error: fatal: could not read Username for 'https://github.com': terminal prompts disabled
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Will not authenticate when passing `MATCH_GIT_BASIC_AUTHORIZATION`

##### Command executed

`MATCH_GIT_BASIC_AUTHORIZATION=XXX fastlane match nuke development`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
apolloschurchapp % MATCH_GIT_BASIC_AUTHORIZATION=XXX fastlane match nuke development                 
[✔] 🚀 
[20:21:01]: fastlane detected a Gemfile in the current directory
[20:21:01]: However, it seems like you didn't use `bundle exec`
[20:21:01]: To launch fastlane faster, please use
[20:21:01]: 
[20:21:01]: $ bundle exec fastlane match nuke development
[20:21:01]: 
[20:21:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:21:02]: Successfully loaded '/Users/michael/Documents/Projects/apollos/apollos-templates/apolloschurchapp/fastlane/Matchfile' 📄

+----------------+------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------+------------------------------------------------+
| git_url        | https://github.com/ApollosProject/certificates |
| storage_mode   | git                                            |
| app_identifier | ["com.differential.XXX"]                   |
| username       | apps@XXX                               |
+----------------+------------------------------------------------+

Available session is not valid any more. Continuing with normal login.
[20:21:04]: Cloning remote git repo...
[20:21:04]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Cloning into '/var/folders/06/cdpthz5s6l97dmbhywbrc_xm0000gn/T/d20200929-28020-1xt8573'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[20:21:04]: Exit status: 128
[20:21:04]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[20:21:04]: Run the following command manually to make sure you're properly authenticated:
[20:21:04]: $ git clone https://github.com/ApollosProject/certificates /var/folders/06/cdpthz5s6l97dmbhywbrc_xm0000gn/T/d20200929-28020-1xt8573

[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above

#######################################################################
# fastlane 2.161.0 is available. You are on 2.160.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.161.0 Improvements
* [action] add file ignore param for ensure_git_status_clean (#17115) via Devzhr
* [action[ set http request read_timeout to 300 seconds for download_dsyms (#17262) via Pranav Raj
* [Fastlane.swift] fix crash in `LaneFileProtocol.swift` when executing fastlane Swift without using SPM (#17276) via Roger Oba
* [pilot] make key contents sensitive (#17256) via Roger Oba
* [action] fixed issue in app_store_connect_api_key with loading key content from env variable (#17322) via Josh Holtz
* [spaceship] checks  is not nil on Spaceship::ConnectAPI.patch_app (#17261) via Abraão Levi de Oliveira Figueredo
* [spaceship] modify `Net::HTTPGenericRequest` monkeypatch so that only Apple domains are affected (#17218) via Ash Tyndall

Please update using `sudo gem install fastlane`

 </pre>
</details>

### Environment

<details>
  <pre> <details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.6.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'com.differential.XXX', type: 'development', readonly: true)
    match(app_identifier: 'com.differential.XXX', type: 'appstore', readonly: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :deploy do
    setup_ci
    certificates
    increment_build_number(build_number: number_of_commits, xcodeproj: "ios/apolloschurchapp.xcodeproj")
    build_app(workspace: "ios/apolloschurchapp.xcworkspace", scheme: "apolloschurchappprod")
    upload_to_testflight
  end
end

platform :android do

  # necessary because setting gradle properties doesn't seem to be working
  desc "Bumps Android versionCode"
  lane :bump_version_code do
    path = '../android/app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = number_of_commits
    s[re, 1] = (versionCode).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    bump_version_code
    gradle(task: 'clean', project_dir: 'android')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android')
    upload_to_play_store(track: "internal")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS
app_identifier("com.differential.XXX") # The bundle identifier of your app
apple_id("fastlane@XXX.com") # Your Apple email address

itc_team_id("XXX") # App Store Connect Team ID
team_id("XXX") # Developer Portal Team ID

# Android
json_key_file("android/key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.differential.XXX") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.160.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| CFPropertyList            | 3.0.2        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 3.0.0        |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.18.0       |
| public_suffix             | 4.0.6        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| json                      | 2.3.1        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.28.0       |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.371.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.107.0      |
| aws-sdk-kms               | 1.38.0       |
| aws-sdk-s3                | 1.81.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-29**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #17347
Resolves #16405

### Description
Looks like these 3 parameters are not being forwarded to the storages' initialization. I reviewed every single parameter of each of the 3 storage types and these are the only 3 that were missing, that made sense to have.

### Testing Steps
To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-fix-match-nuke-missing-git-auth"
```

Then you can test by running e.g.:
`MATCH_GIT_BASIC_AUTHORIZATION=XXX fastlane match nuke development`, replacing XXX with your git auth

### CODE REVIEW

**Comment by redreceipt** [comment]
I tested, no luck :/ looks like it sent the header but still failed. that token has every box checked for full rights to do anything. Double-check I'm testing correctly?

```
...
...
...
Using fastlane 2.170.0 (was 2.160.0) from https://github.com/fastlane/fastlane.git (at rogerluan-fix-match-nuke-missing-git-auth@6b89a9f)
Bundle complete! 2 Gemfile dependencies, 96 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
apolloschurchapp % MATCH_GIT_BASIC_AUTHORIZATION=XXX bundle exec fastlane match nuke development
[✔] 🚀 
[09:45:21]: Successfully loaded '/Users/michael/Documents/Projects/apollos/apollos-templates/apolloschurchapp/fastlane/Matchfile' 📄

+----------------+------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------+------------------------------------------------+
| git_url        | https://github.com/ApollosProject/certificates |
| storage_mode   | git                                            |
| app_identifier | ["XXX"]                   |
| username       | XXX                               |
+----------------+------------------------------------------------+

[09:45:22]: Cloning remote git repo...
[09:45:22]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
Cloning into '/var/folders/06/cdpthz5s6l97dmbhywbrc_xm0000gn/T/d20201207-49075-1ojlooh'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[09:45:22]: Exit status: 128
[09:45:22]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[09:45:22]: Run the following command manually to make sure you're properly authenticated:
[09:45:22]: $ git clone https://github.com/ApollosProject/certificates /var/folders/06/cdpthz5s6l97dmbhywbrc_xm0000gn/T/d20201207-49075-1ojlooh -c http.extraheader='Authorization: Basic XXX'

[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above
```

**Comment by rogerluan** [comment]
@redreceipt did you convert your auth header to Base64? AFAIK you need to do that before using it (the docs mention that briefly https://docs.fastlane.tools/actions/match/)

**Comment by redreceipt** [comment]
Oh shoot I forgot, yea let me do that

**Comment by rogerluan** [comment]
@redreceipt did it work? 😊

**Comment by redreceipt** [comment]
Haven’t tested yet

**Comment by rogerluan** [comment]
Thanks for confirming @redreceipt ! 🤗

**Comment by rogerluan** [comment]
Closing this since https://github.com/fastlane/fastlane/pull/18202 got merged already and it's a duplicate

**Pull request closed without merging**
