### PR TITLE
Testflight demo account required checkbox fix

### PR DESCRIPTION
**Pull request by cpk1**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Apple made an update to the box that pops up when submitting builds to external testflight that makes the "Demo Account Required" check box default to being checked which was causing Pilot to fail when distributing to external testers

https://github.com/fastlane/fastlane/issues/11665
https://github.com/fastlane/fastlane/issues/11713

I uploaded a few builds and tested setting demo_account_required option that I required to true and false to ensure it was getting set correctly and used when submitting for external distribution, I also verified that the default value of false works as intended.

### Description

This change by Apple made uploaded_build.beta_review_info.demo_account_required ||= false fail because when the value was being read it already had a value of true. My change makes this an option that is defaulted to false which should bring back the behavior we used to have. Most likely there might some people who want this improved to also be able to set the demo account details when submitting to external testflight.

### CODE REVIEW

**Comment by cpk1** [comment]
I think I fixed the CLA issue

**Comment by KrauseFx** [comment]
Thanks for your contribution on this. We just changed that a few weeks ago with https://github.com/fastlane/fastlane/commit/0602fd702e0e1907394c8d45202f3a5ca4d88b5d, so allowing the user to set it makes more sense?

**Comment by cpk1** [comment]
At this point I think it makes sense to have a default of false and then allow the user to set up a demo account config if it's needed. This PR would probably make more sense if that whole dialog box was added into the options, however my focus was just on getting the basic behavior back to have pilot working again

**Review by KrauseFx — APPROVED** [review]
Sounds legit, thanks 👍

**Comment by KrauseFx** [comment]
And can you confirm you signed the CLA? Then it's ready to be merged and shipped 👍 Thanks

**Comment by cpk1** [comment]
I've signed the CLA, however I wont be able to satisfy the google bot because some of the commits got done with a non-existant email

**Comment by joaopedrok** [comment]
I having this trouble that i have wrote here and this PR can fix my problem. https://github.com/fastlane/fastlane/issues/11713

**Comment by taquitos** [comment]
@cpk1 are all the commits yours?

**Comment by cpk1** [comment]
Yes, I'm Alex. For some reason the commits when I was bringing my fork up to date last year got done under my local user name

**Comment by taquitos** [comment]
Great, thanks for confirming, and thank you for fixing this! 🎈:goat:

**Comment by joaopedrok** [comment]
It was merged, but its already released?

**Comment by joaopedrok** [comment]
I need it. Because im having some problem to distribute using PILOT. It can fix my problem. By now im unable to release my app automatically and i need to do it manually in testflight.

**Comment by KrauseFx** [comment]
Doing a release in a few minutes 🚀

**Comment by joaopedrok** [comment]
have you released?

**Comment by KrauseFx** [comment]
Sorry, still running, should be out soon

**Comment by KrauseFx** [comment]
Good news, new release is out 🚀

**Pull request merged**
