### PR TITLE
[fastlane] Fixed crash with upload_symbols_to_crashlytics

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/3951

### CODE REVIEW

**Comment by KrauseFx** [comment]
cc @NachoSoto @JaviSoto #justrubythings

**Comment by mfurtak** [comment]
LGTM :+1:

**Comment by NachoSoto** [comment]
Hmm so it was finding another `plist` whose root value was not a dictionary? I'm not entirely sure what this is trying to find, but I wonder if there's a more explicit way to look for the right file.

**Comment by KrauseFx** [comment]
@NachoSoto it's looking for the project's Info.plist to find the Crashlytics API key, so you don't have to provide it manually

**Pull request merged**
