### PR TITLE
Fixes #6285 - improper handling of adb server out of date

### LINKED ISSUE #6285: Screengrab improperly handles the adb server being out of date.
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Screengrab thinks "adb" is a valid device name if the adb server is out of date and must be restarted upon running the `adb devices -l` command because it isn't in the array used for `devices.reject`.

##### Complete output when running fastlane, including the stack trace and command used

```
Command run: 
screengrab

Output:
....lots of unrelated stuff.....

$ adb devices -l
▸ List of devices attached
▸ adb server is out of date.  killing...
▸ * daemon started successfully *
▸ emulator-5554          device product:sdk_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
Multiple connected devices, selecting the first one
To specify which connected device to use, use the -s (specific_device) config option
$ adb -s adb shell echo \$EXTERNAL_STORAGE
▸ error: device 'adb' not found
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Not relevant to this issue.

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

### PR DESCRIPTION
**Pull request by EricKuck**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

Fixes #6285

### CODE REVIEW

**Review by aeikenberry — APPROVED** [review]
👍

**Review by aeikenberry — APPROVED** [review]
👍

**Comment by mfurtak** [comment]
Nice! Thanks for the contribution 👍

**Review by mfurtak — APPROVED** [review]

**Comment by aeikenberry** [comment]
A pr so nice, I approved it twice!

**Comment by KrauseFx** [comment]
Haha, thanks @aeikenberry 👍

**Pull request merged**
