### PR TITLE
[supply] fixed supply promote uploading metadata to wrong track

### LINKED ISSUE #19058: [Supply] upload_to_play_store does not upload changelog
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
We've noticed recently our change logs do not get updated with releases. These were working fine at some point in the past.

Our build pipeline which runs on Gitlab CI generates release notes for tags information and outputs that into the relevant .txt file `<version_code>.txt`
in eg.`android/fastlane/metadata/android/en-GB/changelogs/10303027.txt`

The screenshots show our most recent release bundle and release notes are not present on the play store.
image
image

I don't the the core supply code that well, but I can see that the release notes get added to the release in [uploader.rb](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/uploader.rb#L242) after that i don't quite know how they make it to the android publisher service, maybe they don't?

I was also wondering if it was caused by our release notes being uploaded only during a promote rather than as part of an aab but haven't been able to test, although it uses the same internals of the uploader from what I can tell so I don't see that being a factor?

##### Command executed
```
upload_to_play_store(
      track_promote_to: to,
      track: from,
      version_code: version_code,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      skip_upload_changelogs: false
    )
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[10:48:08]: ----------------------------------
[10:48:08]: --- Step: upload_to_play_store ---
[10:48:08]: ----------------------------------
+---------------------------------+-----------------------------+
|                  Summary for supply 2.181.0                   |
+---------------------------------+-----------------------------+
| track_promote_to                | production                  |
| track                           | alpha                       |
| version_code                    | 10303027                    |
| skip_upload_metadata            | false                       |
| skip_upload_images              | false                       |
| skip_upload_screenshots         | false                       |
| skip_upload_changelogs          | false                       |
| package_name                    | com.redacted.app          |
| release_status                  | completed                   |
| metadata_path                   | ./fastlane/metadata/android |
| json_key                        | release-key.json            |
| skip_upload_apk                 | false                       |
| skip_upload_aab                 | false                       |
| validate_only                   | false                       |
| check_superseded_tracks         | false                       |
| timeout                         | 300                         |
| deactivate_on_promote           | true                        |
| ack_bundle_installation_warning | false                       |
+---------------------------------+-----------------------------+
[10:48:10]: Preparing to upload for language 'en-GB'...
[10:48:11]: Uploading image file ./fastlane/metadata/android/en-GB/images/featureGraphic.png...
[10:48:13]: Uploading image file ./fastlane/metadata/android/en-GB/images/icon.png...
[10:48:16]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/1_en-GB.png...
[10:48:18]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/2_en-GB.png...
[10:48:21]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/3_en-GB.png...
[10:48:24]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/4_en-GB.png...
[10:48:27]: Uploading screenshot ./fastlane/metadata/android/en-GB/images/phoneScreenshots/5_en-GB.png...
[10:48:29]: Updating changelog for '10303027' and language 'en-GB'...
[10:48:29]: Uploading all changes to Google Play...
[10:48:31]: Successfully finished the upload to Google Play</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.2                                        |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane        |
| Host                        | macOS 11.2 (20D64)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1i  8 Dec 2020                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.4                                        |
| Swift Version               | 5.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

def working_version
  version = JSON.parse(File.read('../../package.json'))['version'].split('.')
  major = version[0]
  minor = version[1]
  patch = version[2]
  {
    major: major.to_i,
    minor: minor.to_i,
    patch: patch.to_i
  }
end

def working_version_name
  working_version.values.join('.')
end

def track_version_code(track)
  # example: 10300006
  # 1.0.0 abi 3 build 6

  # example: 20312045
  # 2.12.0 abi 3 build 45

  code = google_play_track_version_codes(track: track).first.to_s

  UI.user_error!("Current version from Google Play not available") unless code

  major = code[0..-8]
  minor = code[-5..-4]
  abi = code[-6]
  build = code[-3..-1]
  {
    major: major.to_i,
    minor: minor.to_i,
    build: build.to_i
  }
end

def track_release_name(track, package)
  # eg 1.0.5

  version = google_play_track_release_names(track: track, package_name: package).first.to_s

  UI.user_error!("Current version from Google Play not available") unless version

  parts = version.split('.')
  {
    major: parts[0].to_i,
    minor: parts[1].to_i,
    patch: parts[2].to_i
  }
end

def ci_tag_version_code
  version = ci_tag_version_name.split('.')
  {
    major: version[0].to_i,
    minor: version[1].to_i,
    patch: version[2].to_i
  }
end

def ci_tag_version_name
  ENV['CI_COMMIT_TAG'].chomp('-android')
end

def last_pipeline_version_code
  File.read('../PIPELINE_VERSION_CODE').to_i
end

def calculate_next_version_code(version)
  UI.message "Calculating version code to target: #{version.values.join('.')}"

  UI.message "Pulling existing version"
  track_version = track_version_code('internal')
  UI.message "Track version code: #{track_version.inspect}"

  version_less_than_track = track_version[:major] > version[:major] ||
                 track_version[:minor] > version[:minor]
  UI.user_error!("Next version #{version} less than track version #{track_version}") if version_less_than_track

  # bump build if version is the same
  same_version = track_version[:major] == version[:major] &&
                 track_version[:minor] == version[:minor]
  build = same_version ? track_version[:build] + 1 : 1

  # work out the version code
  major = version[:major] * 10000000
  minor = version[:minor] *     1000

  code = major + minor + build
  UI.user_error!("Version code #{code} not 8 digits") if code.size != 8
  code
end

def next_staging_version_name
  next_staging_version.values.join('.')
end

def next_staging_version
  # get latest prod version so we bump staging
  prod_version = track_release_name('internal', 'com.redacted.app')
  {
    major: prod_version[:major].to_i,
    minor: prod_version[:minor].to_i,
    patch: prod_version[:patch].to_i + 1
  }
end

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  def build_clean
    UI.message "\n\nCleaning project build"
    gradle(task: "clean")
  end

  def build_set_version_code(version)
    next_version_code = calculate_next_version_code(version)
    UI.message "\n\nSetting version code to #{next_version_code}"
    increment_version_code(
      app_project_dir: 'app',
      version_code: next_version_code
    )
    # save version for pipeline artifacts
    next_version_code += + 4 * 100000 # add arm64-v8a abi code this is what google uses in the play store
    File.write('../PIPELINE_VERSION_CODE', next_version_code)
  end

  def build_set_version_name(next_version_name)
    UI.message "\n\nSetting version name to #{next_version_name}"
    set_value_in_build(
      app_project_dir: 'app',
      key: 'versionName',
      value: next_version_name
    )
    File.write('../PIPELINE_VERSION_NAME', next_version_name)
  end

  def build_set_package_suffix(suffix)
    UI.message "\n\nSetting app identifier to: com.redacted.app.#{suffix}"
    set_value_in_build(
      app_project_dir: 'app',
      key: 'applicationIdSuffix',
      value: suffix
    )
  end

  def build_staging_badge
    version = get_version_name(app_project_dir: 'app')
    add_badge(
      shield: "staging-#{version}-orange",
      alpha_channel: true,
      custom: '../staging-badge.png',
      glob: "./android/app/src/main/res/mipmap-*/ic_launcher.png",
    )
    add_badge(
      shield: "staging-#{version}-orange",
      alpha_channel: true,
      custom: '../staging-badge.png',
      glob: "./android/app/src/main/res/mipmap-*/ic_launcher_round.png",
    )
    add_badge(
      shield: "staging-#{version}-orange",
      alpha_channel: true,
      custom: '../staging-badge.png',
      glob: "./android/app/src/main/res/mipmap-*/ic_launcher_foreground.png",
    )
  end

  def build_package
    UI.message "\n\nBuilding release bundle"
    gradle(
      task: 'bundle',
      build_type: 'Release',
      properties: {
        "org.gradle.jvmargs" => "Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8",
        "android.enableJetifier" => "true",
        "android.useAndroidX" => "true",
        "android.injected.signing.store.file" => 'release.keystore',
        "android.injected.signing.store.password" => ENV['GOOGLE_PLAY_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['GOOGLE_PLAY_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['GOOGLE_PLAY_KEY_PASSWORD'],
      }
    )
  end

  def build_upload(track:, package:)
    UI.message "\n\nUploading to play store using '#{track}' track"
    upload_to_play_store(
      track: track,
      package_name: package,
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      skip_upload_changelogs: false,
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'completed'
    )
  end

  def build_promote(version_code:, from:, to:)
    UI.message "\n\Promoting #{from} to #{to}"
    upload_to_play_store(
      track_promote_to: to,
      track: from,
      version_code: version_code,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      skip_upload_changelogs: false
    )
  end

  def set_metadata_title(title)
    file = File.join(File.dirname(__FILE__), 'metadata', 'android', 'en-GB', 'title.txt')
    File.write(file, title)
  end

  desc "Set version for development"
  lane :set_development_version do |options|
    UI.user_error!("Don't run this on CI, versioning is handled automatically") if ENV['CI_JOB_ID']&.empty?
    build_set_package_suffix(options[:bundle_suffix] || ENV['ANDROID_DEVELOPMENT_APP_PACKAGE_SUFFIX'] || '')
    build_set_version_code(next_staging_version)
    build_set_version_name(next_staging_version_name)
  end


  desc "Submit a new Staging Build to internal track"
  lane :staging_build do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    UI.message("\n\nBuilding package: #{package_name}")
    build_clean
    build_set_package_suffix(ENV['ANDROID_STAGING_APP_PACKAGE_SUFFIX'] || '')
    build_set_version_code(next_staging_version)
    build_set_version_name(next_staging_version_name)
    build_staging_badge
    build_package
  end

  lane :staging_deploy do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    UI.message("\n\Deploying package: #{package_name}")
    set_metadata_title('Redacted Staging')
    build_upload(track: 'internal', package: package_name)
  end

  lane :production_build do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    UI.message("\n\nBuilding package: #{package_name}")
    build_clean
    build_set_package_suffix(ENV['ANDROID_PRODUCTION_APP_PACKAGE_SUFFIX'] || '')
    build_set_version_code(ci_tag_version_code)
    build_set_version_name(ci_tag_version_name)
    build_package
  end

  lane :production_deploy do
    package_name = CredentialsManager::AppfileConfig.try_fetch_value(:package_name)
    UI.message("\n\nDeploying package: #{package_name}")
    set_metadata_title('Redacted')
    build_upload(track: 'internal', package: package_name)
    version_code = last_pipeline_version_code
    # immediately promote to alpha
    build_promote(version_code: version_code, from: 'internal', to: 'alpha')
  end

  lane :production_promote do
    # promote alpha to production
    version_code = last_pipeline_version_code
    set_metadata_title('Redacted')
    build_promote(version_code: version_code, from: 'alpha', to: 'production')
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("release-key.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.redacted.app") # e.g. com.krausefx.app

for_lane :staging_build do
  package_name('com.redacted.app.stage')
end

for_lane :staging_deploy do
  package_name('com.redacted.app.stage')
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.187.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                             | Version | Update-Status      |
| ---------------------------------- | ------- | ------------------ |
| fastlane-plugin-badge              | 1.4.0   | 🚫 Update available |
| fastlane-plugin-android_versioning | 0.5.3   | 🚫 Update available |
| fastlane-plugin-browserstack       | 0.3.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                | Version      |
| ---------------------------------- | ------------ |
| did_you_mean                       | 1.4.0        |
| bundler                            | 2.1.4        |
| uri                                | 0.10.0       |
| rake                               | 13.0.3       |
| CFPropertyList                     | 3.0.3        |
| public_suffix                      | 4.0.6        |
| addressable                        | 2.7.0        |
| artifactory                        | 3.0.15       |
| atomos                             | 0.1.3        |
| aws-eventstream                    | 1.1.1        |
| aws-partitions                     | 1.472.0      |
| aws-sigv4                          | 1.2.3        |
| jmespath                           | 1.4.0        |
| aws-sdk-core                       | 3.115.0      |
| aws-sdk-kms                        | 1.44.0       |
| aws-sdk-s3                         | 1.96.1       |
| babosa                             | 1.0.4        |
| curb                               | 0.9.10       |
| fastimage                          | 2.2.4        |
| colored                            | 1.2          |
| highline                           | 2.0.3        |
| commander                          | 4.6.0        |
| dotenv                             | 2.7.6        |
| emoji_regex                        | 3.2.2        |
| excon                              | 0.83.0       |
| faraday-em_http                    | 1.0.0        |
| faraday-em_synchrony               | 1.0.0        |
| faraday-excon                      | 1.1.0        |
| faraday-net_http                   | 1.0.1        |
| faraday-net_http_persistent        | 1.1.0        |
| multipart-post                     | 2.0.0        |
| ruby2_keywords                     | 0.0.4        |
| faraday                            | 1.4.3        |
| unf_ext                            | 0.0.7.7      |
| unf                                | 0.1.4        |
| domain_name                        | 0.5.20190701 |
| http-cookie                        | 1.0.4        |
| faraday-cookie_jar                 | 0.0.7        |
| faraday_middleware                 | 1.0.0        |
| gh_inspector                       | 1.1.3        |
| jwt                                | 2.2.3        |
| memoist                            | 0.16.2       |
| multi_json                         | 1.15.0       |
| os                                 | 1.1.1        |
| signet                             | 0.15.0       |
| googleauth                         | 0.16.2       |
| httpclient                         | 2.8.3        |
| mini_mime                          | 1.1.0        |
| declarative                        | 0.0.20       |
| trailblazer-option                 | 0.1.1        |
| uber                               | 0.1.0        |
| representable                      | 3.1.1        |
| retriable                          | 3.1.2        |
| rexml                              | 3.2.5        |
| webrick                            | 1.7.0        |
| google-apis-core                   | 0.4.0        |
| google-apis-androidpublisher_v3    | 0.7.0        |
| google-apis-playcustomapp_v1       | 0.4.0        |
| digest-crc                         | 0.6.3        |
| google-apis-iamcredentials_v1      | 0.5.0        |
| google-apis-storage_v1             | 0.5.0        |
| google-cloud-env                   | 1.5.0        |
| google-cloud-errors                | 1.1.0        |
| google-cloud-core                  | 1.6.0        |
| google-cloud-storage               | 1.32.0       |
| json                               | 2.5.1        |
| mini_magick                        | 4.11.0       |
| naturally                          | 2.2.1        |
| plist                              | 3.6.0        |
| rubyzip                            | 2.3.0        |
| security                           | 0.1.3        |
| simctl                             | 1.6.8        |
| terminal-notifier                  | 2.0.0        |
| unicode-display_width              | 1.7.0        |
| terminal-table                     | 1.8.0        |
| tty-screen                         | 0.8.1        |
| tty-cursor                         | 0.7.1        |
| tty-spinner                        | 0.9.3        |
| word_wrap                          | 1.0.0        |
| claide                             | 1.0.3        |
| colored2                           | 3.1.2        |
| nanaimo                            | 0.3.0        |
| xcodeproj                          | 1.19.0       |
| rouge                              | 2.0.7        |
| xcpretty                           | 0.3.0        |
| xcpretty-travis-formatter          | 1.0.1        |
| badge                              | 0.12.0       |
| fastlane-plugin-android_versioning | 0.5.3        |
| fastlane-plugin-badge              | 1.4.0        |
| http-accept                        | 1.7.0        |
| mime-types-data                    | 3.2019.1009  |
| mime-types                         | 3.3.1        |
| netrc                              | 0.11.0       |
| rest-client                        | 2.1.0        |
| fastlane-plugin-browserstack       | 0.3.1        |
</details>

*generated on:* **2021-07-06**
</details>

### PR DESCRIPTION
**Pull request by spacecowboy**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When promoting an existing release on the Play store (for example promoting a beta release to production) - the upload changelog step targets the wrong track. If promoting from beta to production, then the changelog is uploaded to the beta track instead of the production track.

Fixes #19058

### Description

The target track for the changelog was fixed in the code and this PR changes so that the target changes if a promote step is being run.

### Testing Steps

To test this PR follow these steps in this order:

1. Create an internal release on the play store with a default changelog
2. Create a changelog for the release by create a VERSIONCODE.txt file in the metadata with some content
3. Run a promotion from the internal track to the alpha track (which specific tracks don't matter)
4. Verify that the release on the alpha track has the correct changelog as written in the VERSIONCODE.txt file.

Before this PR, step 4 will fail by having the default changelog.

### CODE REVIEW

**Comment by spacecowboy** [comment]
@googlebot I signed it!

**Comment by spacecowboy** [comment]
I have done a manual test and it worked as intended.

I tried writing a test for it but wasn't really able to tie it all together, would appreciate some assistance on that if a test is required.

**Review by joshdholtz — COMMENTED** [review]
@spacecowboy Thanks for making this PR! Would you be able to update the PR description with what the issue was and what your fix was? I _think_ I have an idea but the code but I just want to make sure I'm right and so I have an easy thing to read if I need to come back to this PR in the future for some reason 😊

**Comment by spacecowboy** [comment]
@joshdholtz Updated the description

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much for updating the PR description ❤️ It made reviewing this code so much easier 🙌  Really appreciate your contribution!

**Comment by raldred** [comment]
Thank you for fixing this @spacecowboy

**Pull request merged**
