### PR TITLE
Migrate to the new UI class

### PR DESCRIPTION
**Pull request by KrauseFx**
Requires https://github.com/fastlane/fastlane_core/pull/88

### CODE REVIEW

**Comment by mfurtak** [comment]
This LGTM, but you may want to rebase it onto master before you :ship: it to ensure that the CI builds can run to completion. :rocket:

**Comment by KrauseFx** [comment]
@mfurtak thanks, there are still a lot of classes to be migrated to the new UI classes first though.

**Comment by mfurtak** [comment]
Oh, right. I missed that this was WIP! :construction: :construction_worker: :construction:

**Comment by KrauseFx** [comment]
screenshot 2016-01-24 17 36 24
No stack trace when cancelling `fastlane`

**Comment by mfurtak** [comment]
Love it! :100: Go go go!

**Comment by mfurtak** [comment]
If this is ready to be merged, can we remove the `[WIP]` tag and rebase to try to resolve test problems?

**Comment by KrauseFx** [comment]
@mfurtak It's still work in progress, it's a huge change... Also, a lot of tests fail, as I have to update most of the fastlane tests to not use `.red` anymore :+1:

**Comment by KrauseFx** [comment]
Here we go :rocket:

**Pull request merged**
