### PR TITLE
Fix for #9922, Part 2: content type

### PR DESCRIPTION
**Pull request by provTheodoreNewell**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

As commented on #9922, an additional regression with the introduction of the new `github_api` action at #8971 causes file uploads to fail in the `set_github_release` action when the filename does not include ".zip".  

### Description

This PR restores the pre-existing behavior of using the `application/zip` content type header for all uploaded binary files.

### CODE REVIEW

**Review by ohayon — APPROVED** [review]
AMAZING! Thanks for making these fixes @provTheodoreNewell !! 🚀

**Comment by provTheodoreNewell** [comment]
😄

**Comment by ganjarpanji** [comment]
is this not released yet? could we make the release faster? as our teams need to attach the binaries immediately 😄

**Comment by ganjarpanji** [comment]
ah nevermind, its still possible with .zip though. thanks for the fix anyway @provTheodoreNewell

**Comment by KrauseFx** [comment]
Hehe, we generally avoid shipping new releases during a weekend 😉

**Pull request merged**
