### PR TITLE
[screengrab] Fix search for adb on Windows

### LINKED ISSUE #16075: FastLane could not recognize adb
- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm trying to generate Screenshots with fastlane but fastlane fails to recognize the adb. I have set environments variables for both Sdk and platform tools as ANDROID_HOME and PATH variables respectively. Marked AppData folder public to access. But the problem still continues.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>C:\Users\subhas\StudioProjects\shabdkosh-android-app>fastlane run adb
 [✔] 🚀
[10:48:42]: fastlane detected a Gemfile in the current directory
[10:48:42]: However, it seems like you didn't use `bundle exec`
[10:48:42]: To launch fastlane faster, please use
[10:48:42]:
[10:48:42]: $ bundle exec fastlane run adb
[10:48:42]:
[10:48:42]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:48:43]: -----------------
[10:48:43]: --- Step: adb ---
[10:48:43]: -----------------
[10:48:43]: $ C:/Users/subhas/AppData/Local/Android/Sdk/platform-tools/adb
[10:48:43]: ▸ Android Debug Bridge version 1.0.41
[10:48:43]: ▸ Version 29.0.5-5949299
[10:48:43]: ▸ Installed as C:\Users\subhas\AppData\Local\Android\Sdk\platform-tools\adb.exe
[10:48:43]: ▸ global options:
[10:48:43]: ▸ -a         listen on all network interfaces, not just localhost
[10:48:43]: ▸ -d         use USB device (error if multiple devices connected)
[10:48:43]: ▸ -e         use TCP/IP device (error if multiple TCP/IP devices available)
[10:48:43]: ▸ -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
[10:48:43]: ▸ -t ID      use device with given transport id
[10:48:43]: ▸ -H         name of adb server host [default=localhost]
[10:48:43]: ▸ -P         port of adb server [default=5037]
[10:48:43]: ▸ -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037]
[10:48:43]: ▸ general commands:
[10:48:43]: ▸ devices [-l]             list connected devices (-l for long output)
[10:48:43]: ▸ help                     show this help message
[10:48:43]: ▸ version                  show version num
[10:48:43]: ▸ networking:
[10:48:43]: ▸ connect HOST[:PORT]      connect to a device via TCP/IP
[10:48:43]: ▸ disconnect [[HOST]:PORT] disconnect from given TCP/IP device, or all
[10:48:43]: ▸ forward --list           list all forward socket connections
[10:48:43]: ▸ forward [--no-rebind] LOCAL REMOTE
[10:48:43]: ▸ forward socket connection using:
[10:48:43]: ▸ tcp:<port> (<local> may be "tcp:0" to pick any open port)
[10:48:43]: ▸ localabstract:<unix domain socket name>
[10:48:43]: ▸ localreserved:<unix domain socket name>
[10:48:43]: ▸ localfilesystem:<unix domain socket name>
[10:48:43]: ▸ dev:<character device name>
[10:48:43]: ▸ jdwp:<process pid> (remote only)
[10:48:43]: ▸ forward --remove LOCAL   remove specific forward socket connection
[10:48:43]: ▸ forward --remove-all     remove all forward socket connections
[10:48:43]: ▸ ppp TTY [PARAMETER...]   run PPP over USB
[10:48:43]: ▸ reverse --list           list all reverse socket connections from device
[10:48:43]: ▸ reverse [--no-rebind] REMOTE LOCAL
[10:48:43]: ▸ reverse socket connection using:
[10:48:43]: ▸ tcp:<port> (<remote> may be "tcp:0" to pick any open port)
[10:48:43]: ▸ localabstract:<unix domain socket name>
[10:48:43]: ▸ localreserved:<unix domain socket name>
[10:48:43]: ▸ localfilesystem:<unix domain socket name>
[10:48:43]: ▸ reverse --remove REMOTE  remove specific reverse socket connection
[10:48:43]: ▸ reverse --remove-all     remove all reverse socket connections from device
[10:48:43]: ▸ file transfer:
[10:48:43]: ▸ push [--sync] LOCAL... REMOTE
[10:48:43]: ▸ copy local files/directories to device
[10:48:43]: ▸ --sync: only push files that are newer on the host than the device
[10:48:43]: ▸ pull [-a] REMOTE... LOCAL
[10:48:43]: ▸ copy files/dirs from device
[10:48:43]: ▸ -a: preserve file timestamp and mode
[10:48:43]: ▸ sync [all|data|odm|oem|product|system|system_ext|vendor]
[10:48:43]: ▸ sync a local build from $ANDROID_PRODUCT_OUT to the device (default all)
[10:48:43]: ▸ -l: list files that would be copied, but don't copy them
[10:48:43]: ▸ shell:
[10:48:43]: ▸ shell [-e ESCAPE] [-n] [-Tt] [-x] [COMMAND...]
[10:48:43]: ▸ run remote shell command (interactive shell if no command given)
[10:48:43]: ▸ -e: choose escape character, or "none"; default '~'
[10:48:43]: ▸ -n: don't read from stdin
[10:48:43]: ▸ -T: disable PTY allocation
[10:48:43]: ▸ -t: force PTY allocation
[10:48:43]: ▸ -x: disable remote exit codes and stdout/stderr separation
[10:48:43]: ▸ emu COMMAND              run emulator console command
[10:48:43]: ▸ app installation (see also `adb shell cmd package help`):
[10:48:43]: ▸ install [-lrtsdg] [--instant] PACKAGE
[10:48:43]: ▸ push a single package to the device and install it
[10:48:43]: ▸ install-multiple [-lrtsdpg] [--instant] PACKAGE...
[10:48:43]: ▸ push multiple APKs to the device for a single package and install them
[10:48:43]: ▸ install-multi-package [-lrtsdpg] [--instant] PACKAGE...
[10:48:43]: ▸ push one or more packages to the device and install them atomically
[10:48:43]: ▸ -r: replace existing application
[10:48:43]: ▸ -t: allow test packages
[10:48:43]: ▸ -d: allow version code downgrade (debuggable packages only)
[10:48:43]: ▸ -p: partial application install (install-multiple only)
[10:48:43]: ▸ -g: grant all runtime permissions
[10:48:43]: ▸ --abi ABI: override platform's default ABI
[10:48:43]: ▸ --instant: cause the app to be installed as an ephemeral install app
[10:48:43]: ▸ --no-streaming: always push APK to device and invoke Package Manager as separate steps
[10:48:43]: ▸ --streaming: force streaming APK directly into Package Manager
[10:48:43]: ▸ --fastdeploy: use fast deploy
[10:48:43]: ▸ --no-fastdeploy: prevent use of fast deploy
[10:48:43]: ▸ --force-agent: force update of deployment agent when using fast deploy
[10:48:43]: ▸ --date-check-agent: update deployment agent when local version is newer and using fast deploy
[10:48:43]: ▸ --version-check-agent: update deployment agent when local version has different version code and using fast deploy
[10:48:43]: ▸ (See also `adb shell pm help` for more options.)
[10:48:43]: ▸ uninstall [-k] PACKAGE
[10:48:43]: ▸ remove this app package from the device
[10:48:43]: ▸ '-k': keep the data and cache directories
[10:48:43]: ▸ debugging:
[10:48:43]: ▸ bugreport [PATH]
[10:48:43]: ▸ write bugreport to given PATH [default=bugreport.zip];
[10:48:43]: ▸ if PATH is a directory, the bug report is saved in that directory.
[10:48:43]: ▸ devices that don't support zipped bug reports output to stdout.
[10:48:43]: ▸ jdwp                     list pids of processes hosting a JDWP transport
[10:48:43]: ▸ logcat                   show device log (logcat --help for more)
[10:48:43]: ▸ security:
[10:48:43]: ▸ disable-verity           disable dm-verity checking on userdebug builds
[10:48:43]: ▸ enable-verity            re-enable dm-verity checking on userdebug builds
[10:48:43]: ▸ keygen FILE
[10:48:43]: ▸ generate adb public/private key; private key stored in FILE,
[10:48:43]: ▸ scripting:
[10:48:43]: ▸ wait-for[-TRANSPORT]-STATE
[10:48:43]: ▸ wait for device to be in the given state
[10:48:43]: ▸ STATE: device, recovery, rescue, sideload, bootloader, or disconnect
[10:48:43]: ▸ TRANSPORT: usb, local, or any [default=any]
[10:48:43]: ▸ get-state                print offline | bootloader | device
[10:48:43]: ▸ get-serialno             print <serial-number>
[10:48:43]: ▸ get-devpath              print <device-path>
[10:48:43]: ▸ remount [-R]
[10:48:43]: ▸ remount partitions read-write. if a reboot is required, -R will
[10:48:43]: ▸ will automatically reboot the device.
[10:48:43]: ▸ reboot [bootloader|recovery|sideload|sideload-auto-reboot]
[10:48:43]: ▸ reboot the device; defaults to booting system image but
[10:48:43]: ▸ supports bootloader and recovery too. sideload reboots
[10:48:43]: ▸ into recovery and automatically starts sideload mode,
[10:48:43]: ▸ sideload-auto-reboot is the same but reboots after sideloading.
[10:48:43]: ▸ sideload OTAPACKAGE      sideload the given full OTA package
[10:48:43]: ▸ root                     restart adbd with root permissions
[10:48:43]: ▸ unroot                   restart adbd without root permissions
[10:48:43]: ▸ usb                      restart adbd listening on USB
[10:48:43]: ▸ tcpip PORT               restart adbd listening on TCP on PORT
[10:48:43]: ▸ internal debugging:
[10:48:43]: ▸ start-server             ensure that there is a server running
[10:48:43]: ▸ kill-server              kill the server if it is running
[10:48:43]: ▸ reconnect                kick connection from host side to force reconnect
[10:48:43]: ▸ reconnect device         kick connection from device side to force reconnect
[10:48:43]: ▸ reconnect offline        reset offline/unauthorized devices to force reconnect
[10:48:43]: ▸ environment variables:
[10:48:43]: ▸ $ADB_TRACE
[10:48:43]: ▸ comma-separated list of debug info to log:
[10:48:43]: ▸ all,adb,sockets,packets,rwx,usb,sync,sysdeps,transport,jdwp
[10:48:43]: ▸ $ADB_VENDOR_KEYS         colon-separated list of keys (files or directories)
[10:48:43]: ▸ $ANDROID_SERIAL          serial number to connect to (see -s)
[10:48:43]: ▸ $ANDROID_LOG_TAGS        tags to be used by logcat (see logcat --help)
[10:48:43]: ▸ $ADB_LOCAL_TRANSPORT_MAX_PORT max emulator scan port (default 5585, 16 emus)

Looking for related GitHub issues on fastlane/fastlane...

Traceback (most recent call last):
        24: from C:/Ruby26-x64/bin/fastlane:23:in `<main>'
        23: from C:/Ruby26-x64/bin/fastlane:23:in `load'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
        21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:221:in `block (2 levels) in run'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/adb.rb:9:in `run'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/helper/adb_helper.rb:39:in `trigger'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/forwardable.rb:230:in `sh'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Exit status of command 'C:/Users/subhas/AppData/Local/Android/Sdk/platform-tools/adb' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Android Debug Bridge version 1.0.41
Version 29.0.5-5949299
Installed as C:\Users\subhas\AppData\Local\Android\Sdk\platform-tools\adb.exe
</pre>
</details>

##fastlane env
<details>
<pre>
C:\Users\subhas\StudioProjects\shabdkosh-android-app>fastlane env
 [✔] 🚀
[11:04:45]: fastlane detected a Gemfile in the current directory
[11:04:45]: However, it seems like you didn't use `bundle exec`
[11:04:45]: To launch fastlane faster, please use
[11:04:45]:
[11:04:45]: $ bundle exec fastlane env
[11:04:45]:
[11:04:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:05:25]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                        |
| --------------------------- | ---------------------------- |
| OS                          | UNKNOWN                      |
| Ruby                        | 2.6.5                        |
| Bundler?                    | false                        |
| Git                         | git version 2.23.0.windows.1 |
| Installation Source         | C:/Ruby26-x64/bin/fastlane   |
| Host                        | Unknown  ()                  |
| Ruby Lib Dir                | C:/Ruby26-x64/lib            |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019  |
| Is contained                | false                        |
| Is homebrew                 | false                        |
| Is installed via Fabric.app | false                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

flavors ={
  'bn'=> 'com.***',
  'gu'=> 'com.***',
  'kn'=> 'com.***',
  'ml'=> 'com.***',
  'mr'=> 'com.***',
  'pa'=> 'com. ***',
  'ta'=> 'com.***',
  'te'=> 'com.***',
  'hi'=> 'com.***,
}

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Fetch meta data of apps"
  lane :fetchMetadata do
        flavors.each do |flavor,pack|
                   sh("fastlane supply init --json_key C:*** --metadata_path ./metadata/"+flavor+" --package_name "+pack)
       end
  end

  desc "Upload to playstore"
  lane :build do

    gradle(
      task: "clean"
    )

    flavors.each do |flavor,pack|

            gradle(
                task: 'assemble',
                flavor:flavor,
                build_type: 'Debug'
            )
            gradle(
                task: 'assemble' + flavor,
                build_type: 'DebugAndroidTest'
            )
#            gradle(
#                task: 'assemble' + flavor,
#                build_type: 'Release'
#            )
          end
    end

  desc "Capture screenshots"
  lane :screens do

    flavors.each do |flavor,pack|

      capture_android_screenshots(
        app_package_name: pack,
        clear_previous_screenshots: true,
        output_directory: 'fastlane/metadata/' + flavor,
        app_apk_path: "app/build/outputs/apk/" + flavor + "/debug/app-" + flavor + "-x86-debug.apk",
        tests_apk_path: "app/build/outputs/apk/androidTest/" + flavor + "/debug/app-" + flavor+"-debug-androidTest.apk"
      )
    end

  end

  desc "Upload Apks to Playstore"
  lane :upload do
    flavors.each do |flavor,pack|
           supply(
               track: 'internal',
               json_key: '***',
               package_name: '***'+flavor+'.english',
               metadata_path: 'fastlane/metadata/' + flavor,
               apk: "./app/build/outputs/apk/" + flavor + "/release/app-" + flavor + "-release.apk"
            )
          end
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("****") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("example.com") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.72.0       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| fiddle                    | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-25**
</details>

### PR DESCRIPTION
**Pull request by janpio**
On Windows `adb` is called `adb.exe`, the same applies to most executables. The `self.executable?` already has some special handling for Windows, but did not take that file extension into account.

The solution here is pretty ugly, but should work.

Closes #16075

### CODE REVIEW

**Comment by janpio** [comment]
> but should work.

Should... but does not. Something is wrong with these tests, but my brain currently can not figure that out.

**Review by kadam840 — APPROVED** [review]
Fix this for windows 'adb not found' issue.

**Comment by rogerluan** [comment]
Friendly ping @janpio 🤗 there has been some activity in this PR's issue this week, which made me notice this PR. Is there anything I can help you with, to take this PR to the finish line? 😃

**Comment by KartikSoneji** [comment]
Hi @janpio 
I am facing the same issue as well.

I have some fixes for the failing tests in this branch:  
[fix-executable-checking-windows](https://github.com/KartikSoneji/fastlane/tree/fix-executable-checking-windows)

Please let me know if I can help in any other way to finish this PR.

**Comment by joshdholtz** [comment]
@KartikSoneji Hey! If you want to open a PR from your fork/branch that would be cool 😊 I'd be happy to look into it!

**Comment by KartikSoneji** [comment]
@joshdholtz
done! #18172
Please let me know if you have any suggestions.

**Comment by joshdholtz** [comment]
@KartikSoneji Thank you! Will take a look at today 😊

**Comment by rogerluan** [comment]
Looks like we can close this PR since https://github.com/fastlane/fastlane/pull/18172 got merged 🚀

**Pull request closed without merging**
