### PR TITLE
Enable nuking of Enterprise account and warn the user beforehand

### PR DESCRIPTION
**Pull request by vburojevic**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Nuking of the enterprise account is currently disabled. This PR will enable it but user will have to confirm this action beforehand.

### Description

Issue reference: #11463

### CODE REVIEW

**Comment by vburojevic** [comment]
I signed it!

**Review by KrauseFx — APPROVED** [review]
That's awesome, thanks for your contribution @vburojevic. Did you test this on your local machine?

**Comment by vburojevic** [comment]
@KrauseFx I've changed the code in the latest commits to warn the user only if it's a distribution enterprise nuke and modified the message accordingly. I think it's not necessary when nuking development because it doesn't affect in-house apps. I've also improved the code to exit with user error if the user doesn't confirm. Seems ok to you?

I've tested the warning prompt code but didn't go through with nuking, only printed the tables because I stumbled upon an issue.

It seems that current code only fetches ad-hoc certs and profiles on Enterprise acccount when running with distribution parameter. It doesn't include enterprise certificates and provisioning profiles. But there are only 2 viable parameters now when running nuke: `development` or `distribution`, defined in commands_generator.rb.

So, I've added a 3rd option for enterprise nuke that will fetch and nuke enterprise certificates and provisioning profiles, and modified the documentation accordingly. I hope that's fine, let me know what you think.

Also, if you think we can merge this, I'll nuke our account over the weekend. So I can test everything with actual nuking just to confirm everything runs smoothly and report back here before the merge.

**Comment by vburojevic** [comment]
But maybe it's better to include enterprise provisioning profiles and certificates as part of `match nuke distribution` and leave only `development` and `distribution` options? 🤔

**Comment by janpio** [comment]
Adding the third option seems like a good idea to make sure people know what they are doing.

**Review by KrauseFx — APPROVED** [review]
Looks legit, nice change. Thanks for your contribution @vburojevic 👍

**Pull request merged**
