### PR TITLE
Bump fastlane version

### PR DESCRIPTION
**Pull request by asfalcone**
Changes since release 1.108.0:

* Update all tools to latest fastlane_core (#7026)
* Clarification of devices_file option (#7020)
* Pass generated Fastfile ID through to enhancer (#7022)
* [WIP] add troubleshoot option 🔫 (#6889)
* Update environment_printer.rb
* fix 'fastlane env' on non-macOS operating systems (#6871)
* output contained in env
* Fix `fastlane env` command for bundled fastlane (#6950)

### CODE REVIEW

**Review by mfurtak — APPROVED** [review]

**Comment by KrauseFx** [comment]
`WIP` 😂  @hjanuschka

**Comment by hjanuschka** [comment]
fastlane is still WIP 😄  @milch renamed the PR to `[WIP]`  - and forgot to rename it before merging.
i usually do not do WIP's 😁

**Comment by milch** [comment]
Sorry, my bad!

**Comment by hjanuschka** [comment]
@milch @KrauseFx  https://github.com/fastlane/fastlane/pull/7027

**Comment by klemenzagar91** [comment]
Why cant I update to v1.109.0?
Here's a photo:
screen shot 2016-11-16 at 10 36 01 pm

**Comment by ohwutup** [comment]
Hey @klemenzagar91, apologies for the issue, we have a build running now to get you a new build into the Fabric mac app! Try back in about 10 minutes and it should be good to go! 🚀

**Comment by ohwutup** [comment]
Should be all set to check the Fabric mac app @klemenzagar91! Let us know if you are running into any more issues!

**Comment by klemenzagar91** [comment]
it works. wow that's fast. thanks

**Pull request merged**
