### PR TITLE
[snapshot] Get rid of Xcode 10.2 / SwiftLint warnings

### PR DESCRIPTION
**Pull request by John-Wolfe-Bose**
Changed ‘print’ calls to call NSLog

Changed printouts of error to printing out error.localizedDescription

Upgraded SnashotHelper.swift file version number to 1.16

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass (See Note in Details Section)
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Generated SnapshotHelper.swift code file produces warnings when compiled under XCode 10.2 and SwiftLint. This pull request fixes all of those warnings.

### Description
The generated SnapshotHelper.swift has a compiler warning under XCode 10.2 (error verses error.localizeDescription).

These changes also address warnings output from SwiftLint about not using "print"

When Executing  `bundle exec rspec`, received 1 failure. BUT, this failure was NOT in a section of code that I touched.

```
Failures:

  1) Fastlane Fastlane::FastFile OCLint Integration works with both select and exclude regex
     Failure/Error: expect(result).not_to(include('Test'))
       expected "cd /Users/johnwolfe/Testing/fastlane && oclint -report-type=html -o=oclint_report.html -p ./fastlane...ane/spec/fixtures/oclint/src/DetailViewController.m\" \"fastlane/spec/fixtures/oclint/src/Model.m\"" not to include "Test"
     # ./fastlane/spec/actions_specs/oclint_spec.rb:127:in `block (4 levels) in <top (required)>'

Finished in 3 minutes 47.8 seconds (files took 3.86 seconds to load)
5785 examples, 1 failure

Failed examples:

rspec ./fastlane/spec/actions_specs/oclint_spec.rb:117 # Fastlane Fastlane::FastFile OCLint Integration works with both select and exclude regex
```

### CODE REVIEW

**Comment by John-Wolfe-Bose** [comment]
I signed it!


John Wolfe
iOS Developer

BOSE
Health Division
Mobile Apps & User Interface

Mobile +1 617 901 2855

**Comment by janpio** [comment]
Thanks @John-Wolfe-Bose, CI agrees that there is nothing wrong with your changes - probably some local problem. You might want to create an issue to get that fixed or at least looked at.

I don't know anything about Swift: Are your changes backwards compatible?

**Comment by John-Wolfe-Bose** [comment]
The replacement of print() with NSLog() - NSLog has been available from iOS 2.0

The replacement of error with error.localizedDescription - localizedDescription has been available from iOS 2.0

So both of these are backward compatible for builds using XCode.


As for my local setup, I had run the tests under Ruby 2.3.7 - even though I have Ruby 2.6.2 installed via rbenv. Since the tests mostly passed, I did not go through the work of figuring out why RBENV was not properly enabling my Ruby 2.6.2 install.

Could that have caused the failure I wrote about?

**Comment by janpio** [comment]
Ha, much simpler. I should have looked at the test failure: It checks if the returned string contains "Test", which for some reason it should not, but as you had it checked out in `/Users/johnwolfe/Testing/fastlane` this resulted in a false positive.

**Comment by John-Wolfe-Bose** [comment]
Ah, that explains it! Sorry I did not just check out the test myself. Sorry to cause you extra hassle!

**Comment by John-Wolfe-Bose** [comment]
@janpio - What do I need to do to get a review approval of this pull request? Should I invite others explicitly to do a review?

**Comment by janpio** [comment]
As it is often with open source projects, there are just not that many people around to review things right now. I am think you are good with what you did, this will now happen when it happens.

**Review by janpio — APPROVED** [review]
Changes look consistent to me, needs are review from someone that actually knows Swift though.

**Comment by John-Wolfe-Bose** [comment]
Thank you, and I completely understand. I was imagining a legion of programmers awaiting pull requests hitting some certain milestone so they can pounce on the latest pull request and thus earn bonus points and admiration of all their fellow contributors.

I guess the reality is a little less exciting?

I have been using Fastlane for a few years now, and might have some spare time to help with reviewing pull requests, if that is something that will help the project? I LOVE using Fastlane, and it is always good to give back, right?

Sincerely,
John Wolfe

John Wolfe
iOS Developer

BOSE
Health Division
Mobile Apps & User Interface

Mobile +1 617 901 2855

**Comment by janpio** [comment]
Of course! 

Having a "I looked at the code changes, seems like valid Swift and the changes make sense" or even a "I tested this locally, and it did exactly what it says" will help the contributors so much. Or maybe just starting a discussion what the PR is really about, what problem it is trying to solve etc.

So if you have the time, please go to the Pull Request list, pick any that look interesting to you and have a go at them.

PS: Bonus points and admiration are all there, as are loads of emojis in GitHub comments 🐒 🚀 , but those tend to be rather bad at paying for food and other necessities.

**Comment by John-Wolfe-Bose** [comment]
Isn’t that always the way? All ones and zeros - you would think that the ones would be filling, but no…

I will give a go a little later this week, thanks!

John Wolfe
iOS Developer

BOSE
Health Division
Mobile Apps & User Interface

Mobile +1 617 901 2855

**Review by joshdholtz — APPROVED** [review]
This looks good! Thanks for making these changes 😊

**Pull request merged**
