### PR TITLE
[spaceship] improve client (mainly: login)

### PR DESCRIPTION
**Pull request by janpio**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Spaceship and especially the login code is a scary beast: The code is hard to read and its output is hard to interpret which is cause for all kinds of confusion if something doesn't work as expected, see https://github.com/fastlane/fastlane/pull/13743 for a recent example.

### Description
This PR cleans up the login code in the Spaceship client by moving code to better locations in the files, adding better output (both normal and debug/verbose), adding additional comments, and even renaming a file. I focused especially on the 2 step validation and 2 factor authentication handling.

#### Review Note
Easiest way to review this is probably to look at the individual commits. I tried to mix "move stuff around" and "change stuff" as little as possible, so going through them individually should show the individual changes quite well.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by joshdholtz** [comment]
@janpio Test this this morning!

**Review by joshdholtz — APPROVED** [review]
✅  2FA
✅  2SA
✅  FASTLANE_SESSION env
✅  Prompted login
✅  Look up in keychain
✅  Read from file

Everything looks good 💪

**Comment by janpio** [comment]
Wheeeee! 🐦

**Pull request merged**
