### PR TITLE
added 'unzip' and 'download_file' to docs.

### PR DESCRIPTION
**Pull request by maxoly**

### CODE REVIEW

**Comment by ohwutup** [comment]
Amazing! Thanks @maxoly ! 🚀 🔌

**Comment by KrauseFx** [comment]
Why did this get merged? Both actions are not bundled in `fastlane`, right?

**Comment by maxoly** [comment]
Also Xcake plugin is not bundled in fastlane but present in Actions.md, why?

**Comment by KrauseFx** [comment]
@maxoly Ha, we forgot to remove it, since it was part of fastlane before. Let's remove that from Actions.md too 👍

**Comment by maxoly** [comment]
Oh, I got it. Thanks for clarifying that.

**Pull request merged**
