### PR TITLE
[hockey] clarify error message

### PR DESCRIPTION
**Pull request by janpio**
explain which params can be used to provide a build file

### CODE REVIEW

**Comment by taquitos** [comment]
@janpio looks like you gotta update the test: `hockey_spec.rb` 😭

**Comment by janpio** [comment]
Yep. Debug by CircleCI is the best debug ;)

**Comment by janpio** [comment]
CircleCI is happy now. (Sorry I forgot to check myself... - edited this in the Github GUI directly, so no way to run local tests.)

**Review by taquitos — APPROVED** [review]
🎈:goat:

**Pull request merged**
