### PR TITLE
Don't create the 'Actions' directory on initialization.

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by KrauseFx** [comment]
We passed on the path just to create the directory? Wow...

**Comment by KrauseFx** [comment]
Looks good, however can you also make sure the folder gets created when you run `fastlane new_action`

**Comment by ohwutup** [comment]
hahahaha yeah. i have no idea why i did that!

**Comment by ohwutup** [comment]
https://github.com/fastlane/fastlane/blob/master/lib/fastlane/new_action.rb#L27

**Comment by ohwutup** [comment]
got the go ahead to merge in hip chat from @KrauseFx

**Pull request merged**
