### PR TITLE
[spaceship] fix path to referenced fastfile

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by mpirri** [comment]
Looks good to me, but should probably do this for all of the Fastfile's for all of the other tools.

**Comment by milch** [comment]
What do we need this for?

**Comment by ohwutup** [comment]
@milch if you try to run `fastlane x` inside of a tool's directory, it spits out an error because the path to _fastlane_'s Fastfile is currently invalid. This fixes that issue.

**Review by mpirri — COMMENTED** [review]
✨ 👍 ✨

**Comment by milch** [comment]
@ohwutup Can we remove the files instead?

**Comment by ohwutup** [comment]
Thought about that. A couple (_screengrab_ and _PEM_) have extra things in there.

**Comment by milch** [comment]
Hmm, we don't ship single gems anymore, so maybe we should delete them and move the lanes from pem and screengrab into the main Fastfile

**Comment by ohwutup** [comment]
they are specific to to those tools though, putting them in the fastlane dir smells a bit funny, but happy to do that if you think thats what's good!

**Review by milch — APPROVED** [review]

**Pull request merged**
