### PR TITLE
[pilot] tester management on less-priviliged accounts

### PR DESCRIPTION
**Pull request by hjanuschka**
supports adding testers on accounts below admin role
(developer, app-manager)

Fixes: #8728

### CODE REVIEW

**Comment by hjanuschka** [comment]
@snatchev this solution seems to work, however i am not really happy with the factory thing on externalTesters, can you have a look, maybe there is a better solution. the root cause seems that per-se spaceship is adding testers to "overall" tester pool, where you have no access to if you are below  `admin` role.

however adding it to the app_id pool directly works.

**Comment by bencollier** [comment]
Just testing this - added a tester perfectly 💪 but if no first name / last name is set the user appears as **null null**.

They're added fine, but on an Admin account it just shows them as empty instead of null. Cheers!

**Comment by hjanuschka** [comment]
@bencollier awesome, thx - null value's fixed with last commit https://github.com/fastlane/fastlane/pull/8776/commits/e26a80ad52fce39d7be8dce92b8decf2bb4346c3

**Comment by bencollier** [comment]
@hjanuschka looks good! Thanks :) I've not tested it as part of a CSV import, should that use the same logic?

**Comment by hjanuschka** [comment]
@bencollier i think so, atleast it takes the same code-path 👍

**Comment by tzm41** [comment]
When will this be merged? Seeing the error when I use the web app.

**Comment by KrauseFx** [comment]
@hjanuschka This has to be re-written with the updated `pilot`, right? @taquitos actually works on the same thing for _pilot_, so you two might want to sync on this

**Comment by tzm41** [comment]
Thanks for following up!

**Comment by taquitos** [comment]
Update: I'm currently working through feedback on: https://github.com/fastlane/fastlane/pull/9046

**Comment by KrauseFx** [comment]
Alright, cool, should we close this PR for now then?

**Comment by hjanuschka** [comment]
yeah i think!

**Pull request closed without merging**
