### PR TITLE
[deliver] bring IOS_58 dimensions in line with the current Apple specification.

### LINKED ISSUE #18244: "Invalid screen size" error for iPhone 12 Pro due to invalid screen size in app_screenshot.rb
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Framed iPhone 12 Pro screenshots are 1170 x 2532 because of [this](https://github.com/fastlane/fastlane/blob/557ae2fff6925c5ac9d8f05d7070c5b7a46a119e/frameit/lib/frameit/device_types.rb#L124) line in `device_types.rb`. That matches what Apple says it expects on [this](https://help.apple.com/app-store-connect/#/devd274dd925) page: 1170 x 2532. And yet: trying to upload the screenshots generates an error. **(Note that uploading the exact same screenshots manually succeeds.)**

(Fastlane's error message says: `Invalid screen size (Actual size is 1170x2532...)`.)

##### Command executed

The error is created by `upload_to_app_store`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
...
[19:52:13]: --- Step: upload_to_app_store ---
[19:52:13]: ---------------------------------
[19:52:13]: Successfully loaded '/Users/.../fastlane/Deliverfile' 📄

+-----------------------------+--------------------------------------+
|           Detected Values from './fastlane/Deliverfile'            |
+-----------------------------+--------------------------------------+
...
+-----------------------------+--------------------------------------+

[19:52:13]: Login to App Store Connect (...)
[19:52:14]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.174.0 Summary                           |
+--------------------------------------+--------------------------------------+
| app_version                          | ...                               |
| skip_screenshots                     | false                                |
| screenshots_path                     | ./fastlane/screenshots               |
| metadata_path                        | ./fastlane/metadata                  |
| username                             | ...                  |
| app_identifier                       | ...   |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | true                                 |
| skip_metadata                        | true                                 |
| skip_app_version_update              | false                                |
| force                                | false                                |
| overwrite_screenshots                | true                                 |
| submit_for_review                    | false                                |
| reject_if_possible                   | false                                |
| phased_release                       | false                                |
| reset_ratings                        | false                                |
| app_rating_config_path               | ./fastlane/metadata/app_rating_conf  |
|                                      | ig.json                              |
| submission_information.add_id_info_  | false                                |
| serves_ads                           |                                      |
| submission_information.add_id_info_  | false                                |
| uses_idfa                            |                                      |
| submission_information.content_righ  | false                                |
| ts_contains_third_party_content      |                                      |
| submission_information.export_compl  | false                                |
| iance_uses_encryption                |                                      |
| team_id                              | ...                               |
| dev_portal_team_id                   | ...                           |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | error                                |
| copyright                            | ...                   |
| name.default                         | ...                       |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+
...
[19:52:19]: 🚫 Invalid screenshots were detected! Here are the reasons:
[19:52:19]: 🚫 Error: ./fastlane/screenshots/en-US/iPhone 12 Pro-1-Overview_framed.png - Invalid screen size (Actual size is 1170x2532. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[19:52:19]: 🚫 Error: ./fastlane/screenshots/en-US/iPhone 12 Pro-2-Ready_framed.png - Invalid screen size (Actual size is 1170x2532. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
...
</pre>
</details>

### Environment

<details>
<summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.2.1                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.2.1 (20D74)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.4                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
...
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
...
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.174.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 1.17.2       |
| etc                           | 1.0.1        |
| forwardable                   | 1.2.0        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.0        |
| aws-partitions                | 1.427.0      |
| aws-sigv4                     | 1.2.2        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.112.0      |
| aws-sdk-kms                   | 1.42.0       |
| aws-sdk-s3                    | 1.88.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.1        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.2        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.14.1       |
| googleauth                    | 0.15.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.2        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.2.0        |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| google-cloud-storage          | 1.30.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-02-19**
</details>

### PR DESCRIPTION
**Pull request by michaellenaghan**
Current Apple specification at https://help.apple.com/app-store-connect/#/devd274dd925:

5.8 inch (iPhone 12 Pro, iPhone 12, iPhone 12 mini, iPhone 11 Pro, iPhone XS, iPhone X)

1170 x 2532 pixels (portrait)
2532 x 1170 pixels (landscape)

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #18244

### Description

I re-ran the actions that used to fail (capture iPhone 12 Pro screenshots, upload them to the App Store); they no longer do.

### Testing Steps

1. Capture screenshots using 'iPhone 12 Pro'
2. Upload the screenshots to the App Store

### CODE REVIEW

**Comment by michaellenaghan** [comment]
@googlebot I signed it!

**Comment by michaellenaghan** [comment]
I see the old dimensions also listed:

* [here](https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/spaceship/lib/assets/displayFamilies.json#L117) in `displayFamilies.json`
* [here](https://github.com/fastlane/fastlane/blob/48151291f2c4949c3b1b9919ba2cc81a7cc33293/spaceship/spec/du/du_client_spec.rb#L117) in `du_client_spec.rb`
* [here](https://github.com/fastlane/fastlane/blob/f120a80f78a25b1017ac4cb047202191dcb53ea0/spaceship/lib/spaceship/tunes/tunes_client.rb#L36) in `tunes_client.rb`

It isn't clear to me whether or not any of them need to be updated?

**Review by joshdholtz — APPROVED** [review]
This looks good to me! The other spots are deprecated so this is the only change we need 😊 Really appreciate the contribution ❤️

**Comment by dhermanns** [comment]
Is this still an issue?  I'm using 2.178.0 and still getting:
```
[22:43:20]: 🚫 Error: ./fastlane/screenshots/de-DE/iPhone 8 Plus-01-main_framed.png - Invalid screen size (Actual size is 1436x2876. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
```

**Comment by michaellenaghan** [comment]
@dhermanns This fixed an issue with newer 5.8" iPhones; the 8 Plus is a 5.5" iPhone. I'm using the 8 Plus myself to generate 5.5" images, and it looks like they're the expected size: 1242x2208. (That matches what I see in [`device_types.rb`](https://github.com/fastlane/fastlane/blob/557ae2fff6925c5ac9d8f05d7070c5b7a46a119e/frameit/lib/frameit/device_types.rb#L115).)

**Comment by dhermanns** [comment]
Did you try to frame them?

**Pull request merged**
