### PR TITLE
README Fixes

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Reviewed all READMEs and fixed issues in fastlane/countdown, fastlane/fastlane and fastlane/snapshot

Started in #1944

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
@mfurtak ready to merge after review

**Comment by ohwutup** [comment]
Thanks @ReadmeCritic, could you just rebase off master and then squash?

**Comment by ReadmeCritic** [comment]
UHHHHHHHH this is done from a script so actually not easily :cry:
Will try later

**Comment by ohwutup** [comment]
https://github.com/fastlane/fastlane/pull/3616

**Pull request closed without merging**
