### PR TITLE
Improvements to sonar action

### PR DESCRIPTION
**Pull request by ghost**
- Simplified styling, copy, and removed redundant `cd` prefix command
- Added `verbose` parameter to allow users to completely hide scanner output
-  Added additional tests

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Recently, I've implemented SonarQube in a number of projects. A limitation of the current action does not allow users to output control.  While the sonar-scanner tool does support verbosity parameters, these still do not fully silent the log output.  In very large/complex code bases being scanned, the logs can get massive and difficult to visually grep through. 

### Description
This pull request is providing users the ability to control the output by adding the `verbose:` param.  This controls the output of the `sh` task in the action.   

While working on this, I decided to leave command printing to always hidden as the original owner did.  There will always be sensitive information printed and I didn't want to impact existing users with the unexpected change.

Since I was already expanding the existing feature set of the `sonar` action, I took the time to remove some redundancy, simplified copy, and simplified method names.   I'm not sure why the original author was changing directories to the project's root when actions default to that location.  I assume it was created during an earlier era of _fastlane_ where directory behavior was less understood.  Also added an extra test.

Performed testing by running sonar-scanner against the _fastlane_ and a private repository to ensure the action behaves the way I expected. Also ran rspec + rubocop as required by the the PR template.

Thanks for all y'alls hard work!  I've been using _fastlane_ at a pretty large scale for almost 2 years now and I would argue it saved our product/company from failure during a rapid growth phase.  Beyond the technical benefits, _fastlane_ has empowered to our dev/qa/product staff to keep our velocity when operating through a high risk era of our products.  I am proud to finally be contributing to the project!

### CODE REVIEW

**Comment by PetrosIchor** [comment]
I signed it!

**Comment by janpio** [comment]
huh?

**Comment by PetrosIchor** [comment]
Sorry, somehow got a commit in there that's from another account.  Switched my keys since it's not tied to that but still got in there I guess.   Might be git config related. I'll reopen when I sort it out.

**Comment by janpio** [comment]
Ah ok ;)

**Pull request closed without merging**
