### PR TITLE
[snapshot] Fix matching simulator and screenshot file names

### PR DESCRIPTION
**Pull request by claesjacobsson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Apple seems to have changed the casing of an Xcode simulator name between iOS 12.1 and 12.2: `iPhone XS Max` -> `iPhone Xs Max`. When the casing of the simulator name doesn't match the casing of the screenshot file name, the screenshots.html report doesn't group screenshots under the right device name.

Making the matching case insensitive seems to solve this problem.

Fixes parts of issue #14951

### Description
In `snapshot/lib/snapshot/reports_generator.rb`, I replaced `next unless file_name.include?(key_name)` with `next unless file_name.downcase.include?(key_name.downcase)`.
Adding the `downcase` makes the matching of screenshot file names and `available_devices` work even if Apple changes the casing of an Xcode simulator.

I tested this change by running a Snapfile including all iPhone and iPad devices.

I addition, I added a new 12.0 Simulator called `iPhone Xs Max`. Now, I had two simulators for the same device and iOS version but with different casing of the name. This resulted in an error: `The requested device could not be found because multiple devices matched the request`. Which makes sense. Removing the duplicate simulator made it work again.

### CODE REVIEW

**Comment by janpio** [comment]
Could you maybe add a comment that explains why the `downcase` is necessary? This might not be obvious in a year or two and be removed and then causing problems. 

Are there maybe even tests for this where we could add this somehow?

**Comment by claesjacobsson** [comment]
Not sure of there are any tests covering this.

**Review by joshdholtz — CHANGES_REQUESTED** [review]
It looks like this PR only accounts for the differences between the `iPhone XS (Max)` and `iPhone Xs (Max)`. The `iPhone XR` also had changes to `iPhone Xʀ` so is this also something we need to take into consideration?

| Xcode 10 | Xcode 10.2 |
|---|---|
|Screen Shot 2019-07-03 at 9 02 24 AM|Screen Shot 2019-07-03 at 9 03 00 AM|

**Comment by claesjacobsson** [comment]
I'll look into it.

**Comment by claesjacobsson** [comment]
What version of Ruby should we support?

**Comment by JulesMoorhouse** [comment]
I think the iPhone Xr uses a different character for the "r". Still an issue.

**Comment by JulesMoorhouse** [comment]
@joshdholtz oh it looks like @claesjacobsson has fixed this now!!

**Comment by getaaron** [comment]
I'm going to close this since it's no longer relevant for modern Xcode. Thank you for opening the PR, and feel free to open a new one and tag me if you disagree 👍

**Pull request closed without merging**
