### PR TITLE
Fix action output streams

### PR DESCRIPTION
**Pull request by toolmantim**
`IO.popen` has some quirks with combing output streams which can mess up tools that expect a `pty`.

Instead of doing that, we should start a non-pty stream using `Open3.popen3` and combine the streams ourselves.

Fixes buildkite/agent#171

### CODE REVIEW

**Comment by toolmantim** [comment]
The underlying problem that required me make the commands non-pty were fixed upstream in commander-rb/commander#15

**Comment by KrauseFx** [comment]
@toolmantim thanks for looking into this. So we'll still have to update the `commander` dependency, right?

**Comment by toolmantim** [comment]
Nope no need, the commander version bump was from `4.3.4` to `4.3.5`. I checked out the `krausefx-shenzhen` gem source (it's not on Github) and it depends on commander `~> 4.3`, which means a simple bundle update from people will do it (and I tested to confirm) :+1:

**Comment by KrauseFx** [comment]
@toolmantim the code of `krausefx-shenzhen` is available [here](https://github.com/fastlane/shenzhen) but will soon be replaced with [gym](https://github.com/fastlane/gym) anyway.

**Comment by KrauseFx** [comment]
I updated the dependency in `fastlane_core`

**Comment by toolmantim** [comment]
Great, thanks Felix!

**Pull request closed without merging**
