### PR TITLE
Rollback https://github.com/fastlane/fastlane/pull/9760

### PR DESCRIPTION
**Pull request by KrauseFx**
Sorry, I wasn't careful enough reading the body of the PR

### CODE REVIEW

**Review by mpirri — APPROVED** [review]
🚀

**Comment by Ruenzuo** [comment]
I'll will update a PR as soon as I can get my changes in `xcodeproj` merged and a release we can use to bump the dependency in the gemspec.

**Comment by mjholgate** [comment]
Ah - what happened here? Is this likely to be re-added in a future release?

**Comment by Ruenzuo** [comment]
@mjholgate we need a xcodeproj release to do a proper fix in Fastlane. I already requested one https://github.com/CocoaPods/Xcodeproj/pull/501#issuecomment-327527110 but no comment back yet.

**Comment by mjholgate** [comment]
Ah, thanks @Ruenzuo !

**Comment by KrauseFx** [comment]
Anything that needs to be done from our side here?

**Pull request merged**
