### PR TITLE
shows device names and fixes grouping in report

### LINKED ISSUE #5502: [snapshot] summary report shows "4.7-Inch" instead of "iPhone6s"
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running the `snapshot` from `fastlane` generates the report just fine. It does not show the device name `iPhones6s` but `4.7-Inch` instead though. Is there a way to change that?

Also: Is there a template for the report that could be adjusted?

##### Complete output when running fastlane, including the stack trace and command used

NA

### Configuration Files

```
devices([
  "iPhone 6s",
])

languages([
  "de-DE",
])

ios_version '9.3'
reinstall_app true
erase_simulator true
skip_open_summary true
clear_previous_screenshots true
output_directory "./Screenshots"
stop_after_first_error true
```

### Environment

fastlane version (run `fastlane -v`):

`fastlane 1.98.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

chruby

### PR DESCRIPTION
**Pull request by tcurdt**
fixes https://github.com/fastlane/fastlane/issues/5502

### CODE REVIEW

**Comment by tcurdt** [comment]
Not sure why this shows 8 unrelated commits. It's just one file that was changed - and the PR also shows that.

**Comment by orta** [comment]
If you're interested, you can squash [those commits](https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit) to make it only one 👍

**Comment by tcurdt** [comment]
@orta I guess the other commits are "left overs" from my testfairy PR. Should have worked on a branch both times :-/

**Comment by KrauseFx** [comment]
Hey @tcurdt, thanks for your contribution. This looks great, have you tested this change locally? Can you post a screenshot of the resulting file to this PR? 👍

**Pull request closed without merging**
