### PR TITLE
[README] fix latest version badge for screengrab

### PR DESCRIPTION
**Pull request by Unpublished**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description
Fixes latest version badge due to maven central migration.

### CODE REVIEW

**Comment by Unpublished** [comment]
@googlebot I signed it!

**Comment by Aidan145** [comment]
I have same issue in the latest version badge for screen grab. If you have any solutions then help me.

**Comment by joshdholtz** [comment]
@Aidan145 CI issue was caused by an issue that was merged into master when you created this PR 😇  I rebased to fix!

**Review by joshdholtz — APPROVED** [review]
Looks good to me! Thank you ❤️

**Pull request merged**
