### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by stevelederer**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by stevelederer** [comment]
@googlebot I signed it!

**Comment by joshdholtz** [comment]
@stevelederer Fixed in #17186 already 😱 I still really appreciate the contribution 🙏

**Comment by stevelederer** [comment]
@joshdholtz Sorry I didn't see that. Thanks for all your great work!

**Comment by joshdholtz** [comment]
@stevelederer No problem at all! I think you both made them really close to the same time 😉 And you're welcome! ❤️ Got some more good stuffing the works 😈

**Pull request closed without merging**
