### PR TITLE
[actions] download_dsyms - add auth `Connect for Api Token` automate

### PR DESCRIPTION
**Pull request by tastafur**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
As of February 27, the Two Factor will be imposed, so my continuous integration pipeline will stop working. So that it doesn't stop working I have changed the authentication to use this app_store_connect_api_key and I have verified that DownloadDsymsAction only uses the login authentication type, so I have added the other authentication type, the authentication by apiToken

### Description
If the APP_STORE_CONNECT_API_KEY or params key comes in the context lane, I use the authentication by api token instead of using the login

### Testing Steps
use the action app_store_connect_api_key in front of download_dsyms
`app_store_connect_api_key
 download_dsyms
`

### CODE REVIEW

**Comment by tastafur** [comment]
@googlebot I signed it!

**Comment by tastafur** [comment]
Hello @joshdholtz @ainame, Would the PULL REQUEST be fine? I see that several tests are failing and from what I have seen in the code I think it should not fail, could you take a look at the pull request? Thanks @joshdholtz and @ainame

**Comment by joshdholtz** [comment]
@tastafur I appreciate the time spent on this PR but this isn't going to work yet sadly 😔 The App Store Connect API does not have an endpoint available to download dSYMs with the API Token yet. I'm hoping it comes out sooner rather than later. I know this is going to be rough for everyone until that endpoint is available but its out of our control right now 💔 

Thanks again for the time spent on this!

**Comment by tastafur** [comment]
@joshdholtz will not know other methods to download the dSYM files in a continuous integration system that is not to use login, because as of February 27, if you do not have to use FASTLANE_SESSION?

**Comment by joshdholtz** [comment]
@tastafur Correct. FASTLANE_SESSION will be to be used ☹️

**Pull request closed without merging**
