### PR TITLE
macOS support for snapshot

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by ohayon** [comment]
Hey @SemenovAlexander! Would you mind signing our Google Contributor License Agreement so we can get this PR over the finish line? 🚀  Thanks!

**Comment by SemenovAlexander** [comment]
No problem. I've signed CLA and can see `Google Individual CLA`, when go to the link, provided by @googlebot. 
Is this enough?

**Comment by ohayon** [comment]
Yup! Thanks @SemenovAlexander ! Excited to get this change in there!

**Comment by mfurtak** [comment]
If the Google bot is confused it's usually because the commit is authored (in Git) with a different email address than the one used to sign the CLA. @SemenovAlexander can you check that those are in agreement? Thanks!

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @ohayon</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by mfurtak — APPROVED** [review]

**Comment by KrauseFx** [comment]
Hey @ohayon :wave:

Thank you for your contribution to _fastlane_ and congrats on getting this pull request merged :tada:
The code change now lives in the `master` branch, however it wasn't released yet to [RubyGems](https://rubygems.org/gems/fastlane).
We usually ship about once a week, and your PR will be included in the next one.

Please let us know if this change requires an immediate release by adding a comment here :+1:
We'll notify you once we shipped a new release with your changes :rocket:

**Pull request merged**
