### PR TITLE
[action] update homebrew install for appledoc action for #17503

### PR DESCRIPTION
**Pull request by seanmcneil**
--- Please delete ---

I have added a new PR with a valid CLA

### CODE REVIEW

**Comment by seanmcneil** [comment]
> @googlebot I signed it!

**Comment by seanmcneil** [comment]
> @googlebot I fixed it

**Comment by joshdholtz** [comment]
@seanmcneil This looks good but looks like there might be an issue with the email used for the commit and the CLA signed 🤔

**Comment by seanmcneil** [comment]
> @seanmcneil This looks good but looks like there might be an issue with the email used for the commit and the CLA signed 🤔

Yes, it is likely due to me using a different computer, with different git settings, than my normal one. I'd likely have to restart everything.

**Comment by joshdholtz** [comment]
@seanmcneil I’m sorry 😱 It would be easier if we didn’t have to have CLA but I don’t have any control over that 😔 If you are able are able to force push over this with a new commit with the other email or create another PR that would be great! If not, I can also create a PR for this change for you but I don’t want to take this contribution away from you 😇 

Let me know your thoughts on how you’d like to proceed! ❤️

**Comment by seanmcneil** [comment]
> @seanmcneil I’m sorry 😱 It would be easier if we didn’t have to have CLA but I don’t have any control over that 😔 If you are able are able to force push over this with a new commit with the other email or create another PR that would be great! If not, I can also create a PR for this change for you but I don’t want to take this contribution away from you 😇
> 
> Let me know your thoughts on how you’d like to proceed! ❤️

Sorry for the trouble, but I eventually got everything aligned to make CLA happy. You can delete this & one other PR attempt, as they had unacceptable commits.

**Comment by seanmcneil** [comment]
I have added a new PR with a valid CLA

**Pull request closed without merging**
