### PR TITLE
[fastlane] ignore vendor debug check when running tests

### PR DESCRIPTION
**Pull request by subdigital**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When running a system that does not have a ruby manager like rbenv, you often cannot bundle without sudo. This leads to bundler recommending that you bundle with a path like `vendor/bundle` (which is the default recommendation).

If you do this fastlane tests fail checking for TODOS, binding.pry and other debug code because they exist in your working directory for gem dependencies.

This change skips that folder when checking for debug code.

### Description

Adds `*/vendor/bundle` to the `--exclude-dir` parameter of the grep command that is searching for these strings

### Testing Steps

Checkout a fresh fastlane repo
Run `bundle install --path vendor/bundle`
Run fastlane tests: `bundle exec fastlane test`

### CODE REVIEW

**Comment by subdigital** [comment]
CLA signed, looks like that failing test is unrelated to this change.

**Comment by joshdholtz** [comment]
@subdigital Can you reply with `@googlebot I signed it!`? 😊 It needs exactly that lol

**Comment by joshdholtz** [comment]
lol, never mind! Looks like I can trigger it 🤦‍♂️

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thanks for the contribution!! ❤️

**Pull request merged**
