### PR TITLE
Do not check alternative versions like x.x and x.x.x

### PR DESCRIPTION
**Pull request by roffelund**
### Checklist

- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.
- [ ] I've added or updated relevant unit tests.

### CODE REVIEW

**Comment by TheMetalCode** [comment]
This does appear to address https://github.com/fastlane/fastlane/issues/22248

I did notice something odd in the output logs though:
publish_release_build_branch__2087__-_doximity_infra-automation-ios-test-app

**Comment by Baza207** [comment]
@TheMetalCode It seems mentioned in the PR liked here: https://github.com/fastlane/fastlane/issues/22248#issuecomment-2377654546

**Comment by TheMetalCode** [comment]
> @TheMetalCode It seems mentioned in the PR liked here: [#22248 (comment)](https://github.com/fastlane/fastlane/issues/22248#issuecomment-2377654546)

@Baza207 The issue with the log output I posted is that it's comparing app version to a `nil` value. As in, this PR makes it so that `app_version_queried` is always `nil` because `matching_build` now only returns one value.

See: https://github.com/roffelund/fastlane/blob/dual-build-bug/fastlane_core/lib/fastlane_core/build_watcher.rb#L52

**Comment by TheMetalCode** [comment]
> > @TheMetalCode It seems mentioned in the PR liked here: [#22248 (comment)](https://github.com/fastlane/fastlane/issues/22248#issuecomment-2377654546)
> 
> @Baza207 The issue with the log output I posted is that it's comparing app version to a `nil` value. As in, this PR makes it so that `app_version_queried` is always `nil` because `matching_build` now only returns one value.
> 
> See: https://github.com/roffelund/fastlane/blob/dual-build-bug/fastlane_core/lib/fastlane_core/build_watcher.rb#L52

This is resolved on https://github.com/fastlane/fastlane/pull/22255 along with _most_ of the tests being adjusted.

**Comment by roffelund** [comment]
Thanks for taking this forward @TheMetalCode

**Pull request closed without merging**
