### PR TITLE
html encode all error messages

### PR DESCRIPTION
**Pull request by hjanuschka**

### CODE REVIEW

**Review by mgrebenets — APPROVED** [review]

**Review by KrauseFx — APPROVED** [review]
I wonder why there are no tests that need to be updated?

**Comment by hjanuschka** [comment]
i was shocked about no test failing too - i expected atleast a couple of them to fail.

**Comment by KrauseFx** [comment]
@hjanuschka can you take a look on why this didn't cause any test failures?

**Comment by hjanuschka** [comment]
in fact there are only 1 spec using the `userInfo`, `resultString`.
`portal_permission_spec.rb` -> mocking a result, but not using html encoded things.


and a grep over the whole repo, just shows that `resultString` and `userInfo` are not really used.
one case is `(content["resultString"] || "").include?("NotAllowed")` -> should not be affected by the encoding.

so i am confident it is ok.


not sure if a spec with a mocked html response, checking if it gets escaped makes sense?

**Pull request merged**
