### PR TITLE
Update circle to Xcode 8.3

### PR DESCRIPTION
**Pull request by KrauseFx**
This PR also skips the legacy build API tests. For now, we should probably still keep the legacy build API with their tests alive, however in about 3-6 months I'd say we should officially remove it.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Gym Gym::PackageCommandGeneratorLegacy works with the example project with no additional parameters | <a href='https://github.com/fastlane/fastlane/blob/6ad90c1d32d6b3d44bc6bc9e7f8a296da217de9b/./gym/spec/package_command_generator_legacy_spec.rb'>package_command_generator_legacy_spec.rb</a>|
Gym Gym::PackageCommandGeneratorLegacy works with the example project with no additional parameters and an apostrophe/single quote in the product name | <a href='https://github.com/fastlane/fastlane/blob/6ad90c1d32d6b3d44bc6bc9e7f8a296da217de9b/./gym/spec/package_command_generator_legacy_spec.rb'>package_command_generator_legacy_spec.rb</a>|
Gym Gym::PackageCommandGeneratorLegacy supports passing a path to a provisioning profile | <a href='https://github.com/fastlane/fastlane/blob/6ad90c1d32d6b3d44bc6bc9e7f8a296da217de9b/./gym/spec/package_command_generator_legacy_spec.rb'>package_command_generator_legacy_spec.rb</a>|
Gym Gym::PackageCommandGeneratorLegacy uses a temporary folder to store the resulting ipa file | <a href='https://github.com/fastlane/fastlane/blob/6ad90c1d32d6b3d44bc6bc9e7f8a296da217de9b/./gym/spec/package_command_generator_legacy_spec.rb'>package_command_generator_legacy_spec.rb</a>|
Scan Scan::Runner handle_results Test Failure raises a FastlaneTestFailure instead of a crash or UserError | <a href='https://github.com/fastlane/fastlane/blob/6ad90c1d32d6b3d44bc6bc9e7f8a296da217de9b/./scan/spec/runner_spec.rb'>runner_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Scan Scan::Runner handle_results Test Failure raises a FastlaneTestFailure instead of a crash or UserError | <a href='https://github.com/fastlane/fastlane/blob/4a4f1b689e7fe441ae1e81f0b23b92b873ae5a48/./scan/spec/runner_spec.rb'>runner_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Scan Scan::Runner handle_results Test Failure raises a FastlaneTestFailure instead of a crash or UserError | <a href='https://github.com/fastlane/fastlane/blob/4a4f1b689e7fe441ae1e81f0b23b92b873ae5a48/./scan/spec/runner_spec.rb'>runner_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by mfurtak** [comment]
I think this will need to be rebased because of rubocop rules changes

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Scan Scan::Runner handle_results Test Failure raises a FastlaneTestFailure instead of a crash or UserError | <a href='https://github.com/fastlane/fastlane/blob/87d6eefa33f6adc14429c757dda57897d67a28f9/./scan/spec/runner_spec.rb'>runner_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
Rebased, and just the one _scan_ test failure remaining

**Pull request closed without merging**
