### PR TITLE
Bump xcpretty to version 0.4.0

### LINKED ISSUE #21192: Vulnerability in Rouge 2.0.7
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The fastlane release 2.212.1 is conusming xcpretty 0.3.0 
https://github.com/fastlane/fastlane/blob/master/Gemfile.lock

xcpretty 0.3.0 is conusming rouge 2.0.7 and this version has vulnerabilities
https://ossindex.sonatype.org/vulnerability/sonatype-2021-4771?component-type=gem&component-name=rouge&utm_source=dependency-track&utm_medium=integration&utm_content=v4.5.0

I don't know what to do, because the xcpretty project is dead i think? There are no changes since 2018
and the active pull request with the update of rouge is open since end of 2022
https://github.com/xcpretty/xcpretty/pull/383

##### Command executed
Not relevant.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Not relevant </pre>
</details>

### Environment

<details>
  <pre> Not relevant </pre>
</details>

### PR DESCRIPTION
**Pull request by revolter**
### Checklist

- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #21192.

Arose from https://github.com/xcpretty/xcpretty/issues/394.

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
:shipit:

**Comment by revolter** [comment]
Wow, right this minute I opened the Slack thread to check for updates, and at the same time I received the notification email 🤯

Thanks for the review ❤️

**Comment by jeffremer** [comment]
FWIW, it appears that `xcpretty@0.4.0` has [an issue](https://github.com/xcpretty/xcpretty/issues/391) where it causes UI tests bail immediately while running if there is test failure. This has the side effect of preventing us from gathering test results since the test suite doesn't finish running.

**Comment by revolter** [comment]
@jeffremer, thanks for letting me know! 🙏🏻 Really sorry for introducing that crash. I created https://github.com/xcpretty/xcpretty/pull/400 that hopefully fixes it, and if it does, I will follow through to get it into _fastlane_ as well 🤞🏻

**Comment by thevenkat94** [comment]
> FWIW, it appears that `xcpretty@0.4.0` has [an issue](https://github.com/xcpretty/xcpretty/issues/391) where it causes UI tests bail immediately while running if there is test failure. This has the side effect of preventing us from gathering test results since the test suite doesn't finish running.

So, what we have to do ..?

**Comment by revolter** [comment]
> So, what we have to do ..?

I am working on getting the fix into a future fastlane update 🤞🏻

**Pull request merged**
