### PR TITLE
Improve GitHub Issue and Pull Request templates

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Related to #11157.

### CODE REVIEW

**Comment by janpio** [comment]
Gave up already? ;)

Github should parse the template and use it to render a form with actual checkboxes.

**Comment by janpio** [comment]
> so the only way I think it happens is by copy+pasting it from the comment

✔️  `:heavy_check_mark:`

But I agree.

**Comment by milch** [comment]
How about instead of updating the template until people get it, we simply have the bot autocorrect it? 

A substitution like `s/\[\s*\S\s*\]/[x]/g` should basically fix this forever and ever even if someone comes along and decides that `[         x      ]` is acceptable to submit

**Comment by milch** [comment]
See: https://regexr.com/3i0bk

**Comment by revolter** [comment]
And replace it like https://regexr.com/3i0bq.

**Comment by janpio** [comment]
That is a very good idea. (Although I don't know if it has functionality to edit issues yet)

**Comment by revolter** [comment]
I still think that this PR should be merged, to simplify the template files, IMHO.

**Review by janpio — APPROVED** [review]

**Pull request merged**
