### PR TITLE
[spaceship] Basic support for app bundles

### PR DESCRIPTION
**Pull request by max-ott**
This adds basic support for retrieving information of app bundles

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Starting point for https://github.com/fastlane/fastlane/issues/13826

### Description
To test with `IRB`, log in with your Apple ID. (Account needs to have an app bundle for obvious reasons)

`Spaceship::Tunes.client.bundle_details(123456789)`

Expected reponse:

```{
	"adamId" => 123456789, "vendorIdentifier" => "com.acmecorp.bundle", "copyright" => "2019 Acme Corp", "primaryLocaleCode" => "en-US", "priceTierStem" => "10", "details" => [{
		"name" => "Fancy Bundle",
		"localeCode" => "en-US",
		"approvedDetail" => nil,
		"marketingText" => {
			"value" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "isEditable" => false, "isRequired" => false, "errorKeys" => nil
		},
		"marketingUrl" => {
			"value" => "https://www.acmecorp.com/bundle", "isEditable" => false, "isRequired" => false, "errorKeys" => nil
		},
		"reviewRequired" => false,
		"empty" => false
	}], "memberApps" => [{
		"adamId" => 123456789,
		"name" => "App 1",
		"iconUrl" => "https://is2-ssl.mzstatic.com/image/thumb/Purple71/...",
		"appType" => "ios",
		"priceTier" => "Tier 5",
		"versions" => [{
			"type" => "APP",
			"id" => nil,
			"version" => "4.0",
			"state" => "Ready for Sale",
			"stateKey" => "readyForSale",
			"stateGroup" => "readyForSale",
			"largeAppIcon" => {
				"assetToken" => "Purple71/...", "sortOrder" => nil, "type" => "LargeApplicationIcon", "size" => 8387, "width" => 1024, "height" => 1024, "checksum" => "a8aa085de9a1e422a7cefa78c6e98247", "url" => "https://is1-ssl.mzstatic.com/image/thumb/...", "thumbNailUrl" => "https://is2-ssl.mzstatic.com/image/thumb/...", "originalFileName" => "icon.png"
			},
			"supportedHardware" => ["iphone", "ipad"],
			"issuesCount" => 0,
			"hasGrievous" => false
		}]
	}, {
		"adamId" => 123456789,
		"name" => "App 2",
		"iconUrl" => "https://is1-ssl.mzstatic.com/image/thumb/...",
		"appType" => "ios",
		"priceTier" => "Tier 5",
		"versions" => [{
			"type" => "APP",
			"id" => nil,
			"version" => "4.0",
			"state" => "Ready for Sale",
			"stateKey" => "readyForSale",
			"stateGroup" => "readyForSale",
			"largeAppIcon" => {
				"assetToken" => "Purple71/v4/...", "sortOrder" => nil, "type" => "LargeApplicationIcon", "size" => 13736, "width" => 1024, "height" => 1024, "checksum" => "ff1ea4b7ebb224b1b4cabc49d4f0ba63", "url" => "https://is5-ssl.mzstatic.com/image/thumb/...", "thumbNailUrl" => "https://is1-ssl.mzstatic.com/image/...", "originalFileName" => "icon.png"
			},
			"supportedHardware" => ["iphone", "ipad"],
			"issuesCount" => 0,
			"hasGrievous" => false
		}]
	}, {
		"adamId" => 123456789,
		"name" => "App 3",
		"iconUrl" => "https://is4-ssl.mzstatic.com/image/thumb/...",
		"appType" => "ios",
		"priceTier" => "Tier 5",
		"versions" => [{
			"type" => "APP",
			"id" => nil,
			"version" => "4.0",
			"state" => "Ready for Sale",
			"stateKey" => "readyForSale",
			"stateGroup" => "readyForSale",
			"largeAppIcon" => {
				"assetToken" => "Purple62/v4/e7/...", "sortOrder" => nil, "type" => "LargeApplicationIcon", "size" => 15358, "width" => 1024, "height" => 1024, "checksum" => "29ecb4a1676faf2459cf4b52251b12ec", "url" => "https://is4-ssl.mzstatic.com/image/thumb/Purple62/...", "thumbNailUrl" => "https://is4-ssl.mzstatic.com/image/thumb/..., "originalFileName" => "icon.png"
			},
			"supportedHardware" => ["iphone", "ipad"],
			"issuesCount" => 0,
			"hasGrievous" => false
		}]
	}], "canSubmit" => false, "canDevReject" => false, "clearedForSale" => true, "resolutionCenterURL" => "/WebObjects/iTunesConnect.woa/ra/ng/bundle/123456789/resolutioncenter", "state" => "Ready for Sale", "stateGroup" => "readyForSale", "stateKey" => "readyForSale", "inFlightState" => "Prepare for Submission", "userBundleIcon" => {
		"value" => {
			"assetToken" => nil, "sortOrder" => nil, "type" => nil, "size" => nil, "width" => nil, "height" => nil, "checksum" => nil, "url" => nil, "thumbNailUrl" => nil, "originalFileName" => nil
		}, "isEditable" => true, "isRequired" => false, "errorKeys" => nil, "approvedAssetToken" => nil, "approvedIconUrl" => nil
	}, "clearedForSaleEditable" => true, "adamId2" => 123456789
}´

### CODE REVIEW

**Review by snatchev — APPROVED** [review]
Looks good to me.

**Review by snatchev — CHANGES_REQUESTED** [review]
Overall this look good to merge, but could you add a spec that returns a fixture you included in this PR? That would make testing features built on top of this endpoint easier. Thanks!

**Comment by max-ott** [comment]
@snatchev Do you have any pointers how to do/test this locally? To be honest, I have 0 experience with fixtures/tests. More than happy to add, if I know how to to it!

**Comment by snatchev** [comment]
@max-ott sure! The workflow would be something like this:

- add an example in `spaceship/spec/tunes/tunes_client_spec.rb`. Something like:
   ```ruby
   it "requests bundle details" do
     response = subject.bundle_details(123456789)
     expect(response.size).to eq(5) # you can add a few different reasonable expectations on the shape of the response
   end
   ```
- Run the tests. You can scope it to just the file you're working on by running `bundle exec rspec spaceship/spec/tunes/tunes_client_spec.rb`
- You should get an error that basically says "You tried to make a network request, but WebMock blocked it, and you don't have any stubs registered for this request.
- Add a stubbed response. Save the JSON response you have seen and put it in `spaceship/spec/tunes/fixtures/bundle_details.json`
- Then register the stub by doing `stub_request( ... )` and specify your fixture file. Check out https://github.com/fastlane/fastlane/blob/master/spaceship/spec/tunes/tunes_client_spec.rb#L130 as an example.

**Comment by max-ott** [comment]
@snatchev Added a quick test and fixture. As this "just" gets the whole details object, how many / deep tests make sense for you? 

```
it "requests iOS app bundle details" do
   response = subject.bundle_details(1_234_567_890)
   expect(response["adamId"]).to eq(1_234_567_890)
   expect(response["details"][0]["name"]).to eq("Fancy Bundle")
end

Which of the last 2 `expect` would be helpful?

**Review by snatchev — APPROVED** [review]

**Comment by snatchev** [comment]
@max-ott spec looks good! While this doesn't necessarily exercise a whole lot, it allows other specs, such as model tests, to be written on top of the client and we have a reference for what the request/responses look like. Thanks!

**Pull request merged**
