### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Though I have no idea where this is called, because that was the only place where "recieved" was found.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Please also fix the same typo on line 28 and 29 in this file.
Also, just wondering: Who is calling this method? When renaming it like that it would potentially break existing users of this method..

**Review by getaaron — DISMISSED** [review]
This will break the implementation with [gh_inspector](https://github.com/orta/gh_inspector)

I guess this PR is blocked by https://github.com/orta/gh_inspector/issues/19

**Comment by KrauseFx** [comment]
Yep, nice catch @getaaron 👍

**Comment by revolter** [comment]
So, will @getaaron take it from here?

**Comment by getaaron** [comment]
@revolter I'm not planning on picking up this work, just wanted to point out the issue. Feel free to open a PR to address https://github.com/orta/gh_inspector/issues/19 and then update this issue once it's merged

**Comment by revolter** [comment]
Understood, but this is beyond my knowledge, so I'll leave this open in case others want to continue it.

**Comment by revolter** [comment]
@getaaron, Could you take another look at this?

**Review by KrauseFx — APPROVED** [review]
Looks solid now, have you tested it locally also?

**Comment by revolter** [comment]
@KrauseFx, No, how can I do that?

**Comment by KrauseFx** [comment]
`bundle update`, make sure to have the new version of the gh-inspector gem, and then call `UI.crash("some txt")` somewhere in any of the fastlane files that get executed 👍

**Comment by revolter** [comment]
Blocked by https://github.com/orta/gh_inspector/pull/21.

**Comment by revolter** [comment]
@KrauseFx, No success with `UI.crash("some txt")`. I think it somehow really crashes before gh_inspector finishes :(

**Comment by revolter** [comment]
So `URI.escape` really seems to cause problems (https://github.com/orta/gh_inspector/pull/22/files#diff-11a0d7906801d9dea0eccb85667ad811R36)

**Comment by revolter** [comment]
Rebased on top of master and fixed conflicts.
Tested locally and it worked.

**Comment by taquitos** [comment]
🎈:goat:

**Pull request merged**
