### PR TITLE
[actions] update upload_symbols_to_crashlytics.rb

### PR DESCRIPTION
**Pull request by Dimon70007**
no needed extracting .dSYM.zip file for uploading to firebase crashlytics

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by Dimon70007** [comment]
found solution for successful upload dsyms here - https://github.com/fastlane/fastlane/issues/14140#issuecomment-470033243

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by joshdholtz** [comment]
@Dimon70007 Can you agree to the CLA so we can merge this? 😊

**Comment by Dimon70007** [comment]
@googlebot I signed it!

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
Thanks for fixing this!! Really appreciate the contribution ❤️

**Comment by davidrothera** [comment]
Hey @joshdholtz any chance of shipping a new release? I've got a .dSYM.zip which has strange characters in it which refuse to unzip with `unzip` and so this would fix my issues 😉

**Comment by joshdholtz** [comment]
Yeah yeah, can ship one this AM!

**Pull request merged**
