### PR TITLE
Add TOC for docs

### PR DESCRIPTION
**Pull request by skywinder**
Always forget where to find specific docs. This PR should improve readability of docs a little bit. Hope it helps! :+1:

### CODE REVIEW

**Comment by KrauseFx** [comment]
I like the idea, but it should automatically be created, right? I see you manually removed the "advertising" before submitting the pull request.
Do you think we could add a `rake docs` task to `countdown` to automatically generate this when we change something?

**Comment by skywinder** [comment]
IHMO:  static TOC, as now - it's a good first step to organize documentation.

Sadly, I not familiar with `countdown` (even don't know what is it :dizzy_face: ). 
But If you don't mind about "advertising" lines - we can add https://github.com/thlorenz/doctoc action to script for automatic update TOC's.

**Comment by KrauseFx** [comment]
Check out countdown here: https://github.com/fastlane/countdown

It makes it super easy to contribute to fastlane and basically manages all repos for you :+1:

**Comment by skywinder** [comment]
Wow, really cool script! :+1: 
That's fit's to `countdown` perfect.
I will make a PR then! 
So will we leave adv lines as is or remove them with additional script line also?

**Comment by KrauseFx** [comment]
Oh yeah, thanks @skywinder. I think it's okay to leave the comments (if they are invisible), but we don't want to have a big link to the project generating this. Did you check the license and instructions if we're allowed to remove it?

**Comment by KrauseFx** [comment]
I'll close this PR for now, as it will be in countdown :+1: Thanks again for your contribution

**Pull request closed without merging**
