### PR TITLE
Fixed supply terminating abnormally when developer deleted all APKs i…

### PR DESCRIPTION
**Pull request by kazuhidet**
### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### CODE REVIEW

**Review by ohayon — APPROVED** [review]
Thanks for this @kazuhidet !! 🚀

**Comment by ohayon** [comment]
And welcome to the _fastlane_ community! 🏎 🐙

**Comment by ohayon** [comment]
Hey @kazuhidet, apologies, I just noticed that the CI job failed, would you mind rerunning that and seeing what the issue is? 🎸

**Comment by kazuhidet** [comment]
@ohayon ohayon Yes, I am well aware of that point.
Circle CI requires a paid plan to use the Xcode environment, but I have not subscribed to it yet.

**Comment by kazuhidet** [comment]
Thanks lots.

**Pull request closed without merging**
