### PR TITLE
Deprecate update_build_info_on_upload as it is not supported by new i…

### PR DESCRIPTION
**Pull request by mpirri**
…TC/TF

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Description

As part of the recent iTunesConnect / TestFlight update, it is no longer possible to set build info without iTC first fully processing the build. This is because a `build_id` is not assigned until the processing completes and a `build_id` is required to call the update build info API call.

As such, this deprecates the `update_build_info_on_upload` option to pilot and disregards it when doing post-verification processing.

### CODE REVIEW

**Review by ohayon — APPROVED** [review]
💯

**Comment by tibo** [comment]
is there any alternative to be able to set the "what to test" field on testflight?

**Comment by mpirri** [comment]
@tibo The "what to test" field will be set when you specify a `changelog` to `pilot`. No need to use the `update_build_info_on_upload` option in this case - it will be set so long as there is a `changelog`.

I hope this helps; please let us know if you have further questions!

**Comment by tibo** [comment]
@mpirri thanks for your answer.
I manage to make it work with the `changelog` option + `skip_waiting_for_build_processing` set to false + `beta_app_feedback_email` set

**Pull request merged**
