### PR TITLE
Support manual signingStyle

### PR DESCRIPTION
**Pull request by AnisovAleksey**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fix for #10470

### Description

in this [comment](https://github.com/fastlane/fastlane/issues/10470#issuecomment-334023655) I explained how export works in Xcode 9. I implemented it in this pull-request

### CODE REVIEW

**Comment by threat70** [comment]
@googlebot check again pls

**Comment by KrauseFx** [comment]
Hey @threat70, thanks for the PR, we already have https://github.com/fastlane/fastlane/pull/10345, however we haven't decided yet how to go ahead with it yet. What do you think?

**Comment by threat70** [comment]
@KrauseFx Hello! :)
in #10345 you allow to update provisioning profiles automatically (xcodebuild will create xcode managed provisioning profiles and use them for build). But in implementation you should consider that user doesn't want to use xcode managed provisioning profiles in some cases. e.g. I specify provisioning profiles mapping and gym will not use them without signingStyle=manual. in the same time flag, that allows to update xcode managed provisioning profiles, have no any sense with manual signing.
Sry, that some tests left broken, I will fix as soon as I can :)

**Comment by KrauseFx** [comment]
Yeah, totally, but if you look at the discussion, you'll see that this might cause issues if the user isn't logged in in Xcode at all, or with the wrong Apple ID.

**Comment by threat70** [comment]
@KrauseFx 
oh, I missed the main point in discussion, sorry. So maybe I will remove -allowProvisioningUpdates, and I'll leave manual signingStyle in case where provisioning profiles map(PPM) is given, it should be correct, because without manual signingStyle PPM will be unused. What you think about it?

**Comment by Kalvin126** [comment]
Does it even use the PPM for signing? Gym still uses my project defined PPM and certs even if I defined the `signingStyle` to `manual`

**Comment by threat70** [comment]
@Kalvin126 , Hi! Could you explain how you define the `signingStyle`?

**Comment by threat70** [comment]
@googlebot check cla pls

**Comment by Kalvin126** [comment]
```Ruby
  gym(
    workspace: '.xcworkspace',
    scheme: '<Scheme>',
    configuration: 'Release',
    export_options: {
      method: "enterprise",
      signingStyle: "manual",
      team: "<Team ID>",
      provisioningProfiles: {
        "<Identifer>": "<Profile>"
      },
      signingCertificate: "iPhone Distribution: <Company>"
    }
    )```

**Comment by Kalvin126** [comment]
Is there something I have to enable to make it generate the output plist? It not in `Library/Logs/gym/`

**Comment by casz** [comment]
This +1000
Deploying asap on our local gems repo 👍 

Reduced our xcodeproj file messing and PROVISIONING_PROFILE_SPECIFIER juggle.
to just relying on Match and Appfile for Team and Provisioning swapping

**Review by jetersen — APPROVED** [review]

**Comment by casz** [comment]
@KrauseFx tbh this is the way to going at least when working with match

**Comment by casz** [comment]
`app_identifier` is read from Appfile so we can support different values for each lane!
Then added as env

```ruby
ENV['APP_IDENTIFIER'] = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
```
Build lane looks like this now
Once the next xcodeproj comes out, I should be able to drop xcargs
https://github.com/CocoaPods/Xcodeproj/pull/510
```ruby
  lane :build do |options|
    scheme = options[:scheme] || ENV['scheme']
    configuration = options[:configuration] || 'Debug'
    type = options[:type] || 'development'
    app_identifier = options[:app_identifier] || ENV['APP_IDENTIFIER']
    git_branch = options[:git_branch] || 'widex'
    if is_jenkins
      setup_jenkins
      FileUtils.rm_rf('../output')
      ENV['FL_BUILDLOG_PATH'] = 'fastlane/logs'
      bump_build_number
      app_identifiers = [
        app_identifier,
        "#{app_identifier}.watchkitapp",
        "#{app_identifier}.watchkitapp.watchkitextension",
      ]
      match(
        type: type,
        readonly: true,
        git_branch: git_branch,
        app_identifier: app_identifiers
      )
    end
    pods
    gym(
      scheme: scheme,
      configuration: configuration,
      xcargs: "APP_IDENTIFIER=#{app_identifier}"
    )
  end
```
screen shot 2017-10-12 at 18 28 42

**Comment by casz** [comment]
What are the chances for this to be the next release?

**Comment by casz** [comment]
#10670 why u no include? 😐

**Review by taquitos — APPROVED** [review]
🎈:goat:

**Comment by twobitlabs** [comment]
I think this PR introduced a bug in that `signingStyle` is always explicitly set to `manual` now and there's no way to get it to be `automatic`. Calling gym with `export_options: { provisioningProfiles: nil, signingStyle: "automatic" }` still results in signingStyle manual in the generated plist.

New issue is: https://github.com/fastlane/fastlane/issues/10778

**Comment by vorobievalex** [comment]
Another regression - #10685

**Pull request merged**
