### PR TITLE
[WIP] Working `bundle install` and `bundle exec fastlane test` on plain Windows

### PR DESCRIPTION
**Pull request by janpio**
Collection of commits that get `bundle install` and `bundle exec fastlane test` working on Windows / AppVeyor. They will be extracted into individual PRs one by one and merged, then this branch will rebased until nothing is left.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @janpio</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by janpio** [comment]
AppVeyor: 
> 4736 examples, 22 failures, 175 pending

**Comment by janpio** [comment]
Current test failures:

```
Failures:
  1) Fastlane Fastlane::FastFile Backup file Integration backup file to `.back` file
     Failure/Error: File.delete(File.join(test_path, backup_path))
     Errno::EACCES:
       Permission denied @ unlink_internal - /tmp/fastlane/tests/fastlane/file.txt.back
     # ./fastlane/spec/actions_specs/backup_file_spec.rb:26:in `delete'
     # ./fastlane/spec/actions_specs/backup_file_spec.rb:26:in `block (4 levels) in <top (required)>'
  2) Fastlane Fastlane::FastFile import raises an exception when the given path is invalid (relative)
     Failure/Error:
       expect do
         Fastlane::FastFile.new.parse("lane :test do
           import('tmp/asdf')
         end").runner.execute(:test)
       end.to raise_error(%r{Could not find Fastfile at path \'\/.*}) # /home (travis) # /Users (Mac)
       expected /Could not find Fastfile at path \'\/.*/, got #<FastlaneCore::Interface::FastlaneError: Could not find Fastfile at path 'C:/projects/fastlane/tmp/asdf'> with backtrace:
         # ./fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!'
         # ./fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
         # ./fastlane/lib/fastlane/fast_file.rb:216:in `import'
         # (eval):2:in `block in parsing_binding'
         # ./fastlane/lib/fastlane/lane.rb:33:in `call'
         # ./fastlane/lib/fastlane/runner.rb:49:in `block in execute'
         # ./fastlane/lib/fastlane/runner.rb:45:in `chdir'
         # ./fastlane/lib/fastlane/runner.rb:45:in `execute'
         # ./fastlane/spec/actions_specs/import_spec.rb:41:in `block (5 levels) in <top (required)>'
         # ./fastlane/spec/actions_specs/import_spec.rb:38:in `block (4 levels) in <top (required)>'
     # ./fastlane/spec/actions_specs/import_spec.rb:38:in `block (4 levels) in <top (required)>'
  3) Fastlane Fastlane::FastFile Backup file Integration when use action after `backup_file` action should be restore file
     Failure/Error: File.delete(File.join(test_path, file_path))
     Errno::EACCES:
       Permission denied @ unlink_internal - /tmp/fastlane/tests/fastlane/file.txt
     # ./fastlane/spec/actions_specs/restore_file_spec.rb:45:in `delete'
     # ./fastlane/spec/actions_specs/restore_file_spec.rb:45:in `block (4 levels) in <top (required)>'
  4) Fastlane Fastlane::FastFile Backup file Integration when use action without `backup_file` action should raise error
     Failure/Error: File.delete(File.join(test_path, file_path))
     Errno::EACCES:
       Permission denied @ unlink_internal - /tmp/fastlane/tests/fastlane/file.txt
     # ./fastlane/spec/actions_specs/restore_file_spec.rb:45:in `delete'
     # ./fastlane/spec/actions_specs/restore_file_spec.rb:45:in `block (4 levels) in <top (required)>'
  5) Fastlane Fastlane::EnvironmentPrinter contains the key words
     Failure/Error: let(:env) { Fastlane::EnvironmentPrinter.get }
     Encoding::CompatibilityError:
       incompatible character encodings: UTF-8 and IBM437
     # ./fastlane/lib/fastlane/environment_printer.rb:26:in `get'
     # ./fastlane/spec/env_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./fastlane/spec/env_spec.rb:14:in `block (3 levels) in <top (required)>'
  6) Fastlane Fastlane::EnvironmentPrinter prints out the loaded fastlane plugins
     Failure/Error: let(:env) { Fastlane::EnvironmentPrinter.get }
     Encoding::CompatibilityError:
       incompatible character encodings: UTF-8 and IBM437
     # ./fastlane/lib/fastlane/environment_printer.rb:26:in `get'
     # ./fastlane/spec/env_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./fastlane/spec/env_spec.rb:19:in `block (3 levels) in <top (required)>'
  7) Fastlane Fastlane::EnvironmentPrinter prints out the loaded gem dependencies
     Failure/Error: let(:env) { Fastlane::EnvironmentPrinter.get }
     Encoding::CompatibilityError:
       incompatible character encodings: UTF-8 and IBM437
     # ./fastlane/lib/fastlane/environment_printer.rb:26:in `get'
     # ./fastlane/spec/env_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./fastlane/spec/env_spec.rb:23:in `block (3 levels) in <top (required)>'
  8) FastlaneCore FastlaneCore::CertChecker shell escaping uses the correct command to import it
     Failure/Error: FastlaneCore::CertChecker.install_wwdr_certificate
       FastlaneCore::Helper received :backticks with unexpected arguments
         expected: (/curl -f -o (\/.+?) https:\/\/developer\.apple\.com\/certificationauthority\/AppleWWDRCA.cer && security import \1 -k keychain\\ with\\ spaces\.keychain/, {:print=>nil})
              got: ("curl -f -o C:/Users/appveyor/AppData/Local/Temp/1/AppleWWDRCA20180104-1440-9xchz7 https://developer..../appveyor/AppData/Local/Temp/1/AppleWWDRCA20180104-1440-9xchz7 -k keychain\\ with\\ spaces.keychain", {:print=>nil})
       Diff:
       @@ -1,3 +1,3 @@
       -[/curl -f -o (\/.+?) https:\/\/developer\.apple\.com\/certificationauthority\/AppleWWDRCA.cer && security import \1 -k keychain\\ with\\ spaces\.keychain/,
       +["curl -f -o C:/Users/appveyor/AppData/Local/Temp/1/AppleWWDRCA20180104-1440-9xchz7 https://developer.apple.com/certificationauthority/AppleWWDRCA.cer && security import C:/Users/appveyor/AppData/Local/Temp/1/AppleWWDRCA20180104-1440-9xchz7 -k keychain\\ with\\ spaces.keychain",
         {:print=>nil}]
     # ./fastlane_core/lib/fastlane_core/cert_checker.rb:64:in `install_wwdr_certificate'
     # ./fastlane_core/spec/cert_checker_spec.rb:43:in `block (4 levels) in <top (required)>'
  9) FastlaneCore FastlaneCore::PkgFileAnalyser with a normal path ::fetch_app_identifier 
     Failure/Error: subject { described_class.fetch_app_identifier(path) }
     Errno::ENOENT:
       No such file or directory - xar -C C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-jt6mlu -xf C:/projects/fastlane/fastlane_core/spec/fixtures/pkgs/MacAppOnly.pkg
     # ./fastlane_core/lib/fastlane_core/helper.rb:18:in ``'
     # ./fastlane_core/lib/fastlane_core/helper.rb:18:in `backticks'
     # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:20:in `block in fetch_distribution_xml_file'
     # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:19:in `fetch_distribution_xml_file'
     # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:6:in `fetch_app_identifier'
     # ./fastlane_core/spec/pkg_file_analyser_spec.rb:9:in `block (5 levels) in <top (required)>'
     # ./fastlane_core/spec/pkg_file_analyser_spec.rb:10:in `block (5 levels) in <top (required)>'
  10) FastlaneCore FastlaneCore::PkgFileAnalyser with a normal path ::fetch_app_version 
      Failure/Error: subject { described_class.fetch_app_version(path) }
      Errno::ENOENT:
        No such file or directory - xar -C C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-wyuqg2 -xf C:/projects/fastlane/fastlane_core/spec/fixtures/pkgs/MacAppOnly.pkg
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in ``'
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in `backticks'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:20:in `block in fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:19:in `fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:13:in `fetch_app_version'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:13:in `block (5 levels) in <top (required)>'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:14:in `block (5 levels) in <top (required)>'
  11) FastlaneCore FastlaneCore::PkgFileAnalyser with a path containing spaces ::fetch_app_identifier 
      Failure/Error: subject { described_class.fetch_app_identifier(path) }
      Errno::ENOENT:
        No such file or directory - xar -C C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-1df77y4 -xf C:/projects/fastlane/fastlane_core/spec/fixtures/pkgs/Spaces\ in\ Path.pkg
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in ``'
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in `backticks'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:20:in `block in fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:19:in `fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:6:in `fetch_app_identifier'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:22:in `block (5 levels) in <top (required)>'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:23:in `block (5 levels) in <top (required)>'
  12) FastlaneCore FastlaneCore::PkgFileAnalyser with a path containing spaces ::fetch_app_version 
      Failure/Error: subject { described_class.fetch_app_version(path) }
      Errno::ENOENT:
        No such file or directory - xar -C C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-jbh3t4 -xf C:/projects/fastlane/fastlane_core/spec/fixtures/pkgs/Spaces\ in\ Path.pkg
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in ``'
      # ./fastlane_core/lib/fastlane_core/helper.rb:18:in `backticks'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:20:in `block in fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:19:in `fetch_distribution_xml_file'
      # ./fastlane_core/lib/fastlane_core/pkg_file_analyser.rb:13:in `fetch_app_version'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:26:in `block (5 levels) in <top (required)>'
      # ./fastlane_core/spec/pkg_file_analyser_spec.rb:27:in `block (5 levels) in <top (required)>'
  13) FastlaneCore FastlaneCore::Project Project.run_command runs more complicated commands
      Failure/Error: expect(FastlaneCore::Project.run_command(cmd)).to eq("HI\n")
      Errno::ENOENT:
        No such file or directory - ruby -e 'sleep 0.1; puts "HI"'
      # ./fastlane_core/lib/fastlane_core/project.rb:441:in ``'
      # ./fastlane_core/lib/fastlane_core/project.rb:441:in `block in run_command'
      # ./fastlane_core/lib/fastlane_core/project.rb:439:in `run_command'
      # ./fastlane_core/spec/project_spec.rb:428:in `block (4 levels) in <top (required)>'
  14) FastlaneCore FastlaneCore::Project Project.run_command should timeouts and kills
      Failure/Error:
        expect do
          FastlaneCore::Project.run_command(cmd, timeout: 1)
        end.to raise_error(Timeout::Error)
        expected Timeout::Error, got #<Errno::ENOENT: No such file or directory - ruby -e 'sleep 3; puts "FOOBAR"'> with backtrace:
          # ./fastlane_core/lib/fastlane_core/project.rb:441:in ``'
          # ./fastlane_core/lib/fastlane_core/project.rb:441:in `block in run_command'
          # ./fastlane_core/lib/fastlane_core/project.rb:439:in `run_command'
          # ./fastlane_core/spec/project_spec.rb:436:in `block (5 levels) in <top (required)>'
          # ./fastlane_core/spec/project_spec.rb:435:in `block (4 levels) in <top (required)>'
      # ./fastlane_core/spec/project_spec.rb:435:in `block (4 levels) in <top (required)>'
  15) FastlaneCore FastlaneCore::Project Project.run_command retries and kills
      Failure/Error:
        expect do
          FastlaneCore::Project.run_command(cmd, timeout: 1, retries: 3)
        end.to raise_error(Timeout::Error)
        expected Timeout::Error, got #<Errno::ENOENT: No such file or directory - ruby -e 'sleep 3; puts "NEEDSRETRY"'> with backtrace:
          # ./fastlane_core/lib/fastlane_core/project.rb:441:in `block in run_command'
          # ./fastlane_core/lib/fastlane_core/project.rb:439:in `run_command'
          # ./fastlane_core/spec/project_spec.rb:458:in `block (5 levels) in <top (required)>'
          # ./fastlane_core/spec/project_spec.rb:457:in `block (4 levels) in <top (required)>'
      # ./fastlane_core/spec/project_spec.rb:457:in `block (4 levels) in <top (required)>'
  16) Frameit Frameit::StringsParser parse successfully parsing parses a valid .strings file
      Failure/Error:
        expect(translations).to eq({
          "Cancel" => "Abbrechen",
          "OK" => "OK",
          "Multiple words working" => "einlangesdeutshceswort mit Abstand"
        })
        expected: {"Cancel"=>"Abbrechen", "OK"=>"OK", "Multiple words working"=>"einlangesdeutshceswort mit Abstand"}
             got: {}
        (compared using ==)
        Diff:
        @@ -1,4 +1 @@
        -"Cancel" => "Abbrechen",
        -"Multiple words working" => "einlangesdeutshceswort mit Abstand",
        -"OK" => "OK",
      # ./frameit/spec/strings_parser_spec.rb:20:in `block (5 levels) in <top (required)>'
  17) Frameit Frameit::StringsParser parse failure parsing logs a helpful message on a bad file
      Failure/Error: expect(Frameit::UI).to receive(:error).with(/.*translations.bad.strings line 2:/)
        (FastlaneCore::UI (class)).error(/.*translations.bad.strings line 2:/)
            expected: 1 time with arguments: (/.*translations.bad.strings line 2:/)
            received: 0 times
      # ./frameit/spec/strings_parser_spec.rb:30:in `block (5 levels) in <top (required)>'
  18) Match Match::Encrypt encrypt
      Failure/Error: @e.encrypt_repo(path: @directory, git_url: @git_url)
      Errno::ENOENT:
        No such file or directory - openssl aes-256-cbc -k 2\"QAHg@v\(Qp\{\=\*n\^ -in C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-1wpkah0/randomFile.mobileprovision -out C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-1wpkah0/temporary -a
      # ./match/lib/match/encrypt.rb:96:in `crypt'
      # ./match/lib/match/encrypt.rb:45:in `block in encrypt_repo'
      # ./match/lib/match/encrypt.rb:76:in `block in iterate'
      # ./match/lib/match/encrypt.rb:74:in `each'
      # ./match/lib/match/encrypt.rb:74:in `iterate'
      # ./match/lib/match/encrypt.rb:44:in `encrypt_repo'
      # ./match/spec/encrypt_spec.rb:17:in `block (3 levels) in <top (required)>'
  19) Match Match::Encrypt raises an exception if invalid password is passed
      Failure/Error: @e.encrypt_repo(path: @directory, git_url: @git_url)
      Errno::ENOENT:
        No such file or directory - openssl aes-256-cbc -k 2\"QAHg@v\(Qp\{\=\*n\^ -in C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-tant2d/randomFile.mobileprovision -out C:/Users/appveyor/AppData/Local/Temp/1/d20180104-1440-tant2d/temporary -a
      # ./match/lib/match/encrypt.rb:96:in `crypt'
      # ./match/lib/match/encrypt.rb:45:in `block in encrypt_repo'
      # ./match/lib/match/encrypt.rb:76:in `block in iterate'
      # ./match/lib/match/encrypt.rb:74:in `each'
      # ./match/lib/match/encrypt.rb:74:in `iterate'
      # ./match/lib/match/encrypt.rb:44:in `encrypt_repo'
      # ./match/spec/encrypt_spec.rb:25:in `block (3 levels) in <top (required)>'
  20) Spaceship::DUClient#upload_geojson handles successful upload request
      Failure/Error: data = subject.upload_geojson(version, valid_geojson, contentProviderId, ssoTokenForImage)
      WebMock::NetConnectNotAllowedError:
        Real HTTP connections are disabled. Unregistered request: POST https://du-itc.itunes.apple.com/upload/geo-json with body '{
          "type": "MultiPolygon",
          "coordinates": [
            [[[-122.7, 37.3], [-121.9, 37.3], [-121.9, 37.9], [-122.7, 37.9], [-122.7, 37.3]]],
            [[[-87.9, 41.5], [-87.3, 41.5], [-87.3, 42.1], [-87.9, 42.1], [-87.9, 41.5]]]
            ]
        }' with headers {'Accept'=>'application/json, text/plain, */*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Connection'=>'keep-alive', 'Content-Length'=>'230', 'Content-Type'=>'application/json', 'Referrer'=>'https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/898536088', 'User-Agent'=>'Spaceship 2.72.0', 'X-Apple-Jingle-Correlation-Key'=>'iOS App:AdamId=898536088:Version=0.9.13', 'X-Apple-Upload-Appleid'=>'898536088', 'X-Apple-Upload-Contentproviderid'=>'1234567', 'X-Apple-Upload-Itctoken'=>'sso token for image', 'X-Apple-Upload-Referrer'=>'https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/898536088', 'X-Original-Filename'=>'ftl_FAKEMD5_upload_valid.geojson'}
        ...
        ============================================================
      # ./spaceship/lib/spaceship/helper/rels_middleware.rb:15:in `call'
      # ./spaceship/lib/spaceship/client.rb:734:in `block in send_request'
      # ./spaceship/lib/spaceship/client.rb:569:in `with_retry'
      # ./spaceship/lib/spaceship/client.rb:733:in `send_request'
      # ./spaceship/lib/spaceship/client.rb:621:in `request'
      # ./spaceship/lib/spaceship/du/du_client.rb:72:in `upload_file'
      # ./spaceship/lib/spaceship/du/du_client.rb:34:in `upload_geojson'
      # ./spaceship/spec/du/du_client_spec.rb:44:in `block (3 levels) in <top (required)>'
  21) Spaceship::DUClient#upload_geojson handles failed upload request
      Failure/Error:
        expect do
          data = subject.upload_geojson(version, invalid_geojson, contentProviderId, ssoTokenForImage)
        end.to raise_error(Spaceship::Client::UnexpectedResponse, error_text)
        expected Spaceship::Client::UnexpectedResponse with "[FILE_GEOJSON_FIELD_NOT_SUPPORTED] The routing app coverage file is in the wrong format. For more information, see the Location and Maps Programming Guide in the iOS Developer Library.", got #<WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST ...esources/controllers/login_cntrl.js")
        ============================================================> with backtrace:
          # ./spaceship/lib/spaceship/helper/rels_middleware.rb:15:in `call'
          # ./spaceship/lib/spaceship/client.rb:734:in `block in send_request'
          # ./spaceship/lib/spaceship/client.rb:569:in `with_retry'
          # ./spaceship/lib/spaceship/client.rb:733:in `send_request'
          # ./spaceship/lib/spaceship/client.rb:621:in `request'
          # ./spaceship/lib/spaceship/du/du_client.rb:72:in `upload_file'
          # ./spaceship/lib/spaceship/du/du_client.rb:34:in `upload_geojson'
          # ./spaceship/spec/du/du_client_spec.rb:55:in `block (4 levels) in <top (required)>'
          # ./spaceship/spec/du/du_client_spec.rb:54:in `block (3 levels) in <top (required)>'
      # ./spaceship/spec/du/du_client_spec.rb:54:in `block (3 levels) in <top (required)>'
  22) Spaceship::Portal::Certificate#download downloads the associated .cer file
      Failure/Error: x509 = OpenSSL::X509::Certificate.new(cert.download)
      OpenSSL::X509::CertificateError:
        not enough data
      # ./spaceship/lib/spaceship/portal/certificate.rb:315:in `initialize'
      # ./spaceship/lib/spaceship/portal/certificate.rb:315:in `new'
      # ./spaceship/lib/spaceship/portal/certificate.rb:315:in `download'
      # ./spaceship/spec/portal/certificate_spec.rb:64:in `block (3 levels) in <top (required)>'
Finished in 3 minutes 16.3 seconds (files took 3.96 seconds to load)
4736 examples, 22 failures, 175 pending
```

**Comment by janpio** [comment]
> 4736 examples, 6 failures, 179 pending

**Comment by janpio** [comment]
> 4736 examples, 4 failures, 179 pending

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by janpio** [comment]
Replaced by #11673 because merge/rebase foo.

**Pull request closed without merging**
