### PR TITLE
[fastlane] also support NO_COLOR for disabling colors

### PR DESCRIPTION
**Pull request by Cyberbeni**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

#17402 

### Testing Steps

```
bundle exec fastlane env
NO_COLOR=1 bundle exec fastlane env
```

### CODE REVIEW

**Comment by Cyberbeni** [comment]
According to https://no-color.org/ the value is irrelevant, so `NO_COLOR=0` should also disable color.

**Review by rogerluan — APPROVED** [review]
🎉 thanks for your contribution, and for taking care of this user's request! 🙌

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This looks great! I added tests for this and also added doc updates - https://github.com/fastlane/docs/pull/1007

Thanks for the contribution ❤️

**Pull request merged**
