### PR TITLE
Add VISION.md to document the fastlane philosophy

### PR DESCRIPTION
**Pull request by mfurtak**
Documents the _fastlane_ philosophy, explaining the project's focus and goals.

Attempts to make clear the relationship between _fastlane_, Fabric, and Twitter.

This is not intended to be set in stone, and should be a living document that invites community involvement 👍

### CODE REVIEW

**Comment by orta** [comment]
This doc is great 👍

**Comment by mfurtak** [comment]
Thanks @orta - we used [Danger's doc](https://github.com/danger/danger/blob/master/VISION.md) for some inspiration. 🤔

**Comment by KrauseFx** [comment]
Do we want that file to be lower case `Vision.md` to be consistent with the other document we're going to push?

**Comment by mfurtak** [comment]
All of the top-level contributor-oriented files are capitalized, so far.

* CODE_OF_CONDUCT.md
* CONTRIBUTING.md
* LICENSE
* README.md

This was intended to match those.

**Comment by KrauseFx** [comment]
We have the new files which are called like this currently:
screenshot 2016-12-01 11 59 03

**Comment by mfurtak** [comment]
I guess my thoughts are:

1. It seems to me that certain repo-root files are capitalized by (historical?) convention
    * CODE_OF_CONDUCT.md
    * CONTRIBUTING.md
    * LICENSE
    * README.md
1. For "vision" capitalization was a little less consistently applied, but VISION.md was still most common from what I saw
1. Having a consistent visual treatment for these kinds of files is good

I think my preference is therefore that:

1. This file stay VISION.md
1. "contributing" stay CONTRIBUTING.md
1. The other files adopt the SCREAMING_SNAKE_CASE style

-- or --

1. This file stay VISION.md
1. "contributing" stay CONTRIBUTING.md
1. Those files adopt another name style, but live in another folder location

-- or --

1. All files mentioned here adopt the CamelCaseNaming style
    * CodeOfConduct.md
    * Contributing.md
    * License
    * Readme.md
    * etc.

**Review by asfalcone — APPROVED** [review]
👁

**Comment by asfalcone** [comment]
Let's stick with VISION for now! 👍

**Comment by mfurtak** [comment]
We could call it `👓 .md` and split the difference ;)

**Comment by mfurtak** [comment]
Cool, let's get this in, and if we want to change the filename going forward, no problem!

**Pull request merged**
