### PR TITLE
Migrate config to 2.0

### PR DESCRIPTION
**Pull request by endocrimes**
This PR migrates the existing configuration to CircleCI 2.0, in a follow up PR, I would like to break out the linting and integration steps into their own jobs. In doing so we can probably ~half CI run time.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @DanToml</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by taquitos — APPROVED** [review]
I can see at least a 1min build/test improvement with this. 🎈:goat:

Not going to merge just yet, I want to give other peeps a chance to see this change and ask questions if they have any.

**Review by KrauseFx — APPROVED** [review]
The future 👍

**Comment by jdee** [comment]
Did you think about adding this to the plugin template? I'm using Circle 2.0 in a plugin: https://github.com/jdee/fastlane-plugin-patch/blob/master/.circleci/config.yml. This is not quite complete, since the test reporting business at the end is incorrect. I was planning eventually to update the plugin template, but if you have a configuration that would work there, and it's easy for you, you might think about updating that too. If not, I or someone else will get to it eventually.

**Comment by DanToml** [comment]
@jdee Oh definitely - I'm not 💯 on the testing process for fastlane plugins, but I'll look into it soon!

**Comment by DanToml** [comment]
@KrauseFx @taquitos I'll merge this in the morning unless anyone has objections 👍

**Comment by taquitos** [comment]
@DanToml sounds great!

**Comment by jdee** [comment]
:+1: For reference, there's a circle.yml in the plugin template. https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/plugins/template/circle.yml I think all that needs to happen is provide an acceptable, reusable .circle/config.yml in its place. Might be as simple as reusing this one. But that could be a separate PR.

**Pull request merged**
