### PR TITLE
Added action sh, fixing #182

### LINKED ISSUE #182: 'sh' action not documented
I am not able to find any documentation regarding the 'sh' action. Neither in https://docs.fastlane.tools/actions nor `fastlane actions`
I am happy to create a description based on the code of the sh_helper.rb, but not sure how to include it in the docs.
Please may you advise?

### PR DESCRIPTION
**Pull request by GoodMirek**
This is intended to fix fastlane/docs#182 'sh' action not documented
`bundle exec rspec` shows following complaint:
```
  2) Fastlane Fastlane::Action No unused options No unused parameters in 'sh'
     Failure/Error: UI.user_error!("Action '#{name}' doesn't use the option :#{option.key}")
     FastlaneCore::Interface::FastlaneError:
       Action 'sh' doesn't use the option :command
```
Unfortunatelly, I have no idea how to fix it. This is my first ruby contribution ever. I have looked around how other actions are written and tried to do it the same way.
Thanks for all your hard work and making CI better!

- [X] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [X] Run `bundle exec rubocop -a` to ensure the code style is valid
- [X] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Looks great, thanks. I added some smaller changes, it's ready now 👍

**Comment by KrauseFx** [comment]
To fix the tests, could you please add this change to your branch? https://github.com/fastlane/fastlane/commit/32b8853b18e8b8b38303ab58b7c3394f4b620145

**Comment by GoodMirek** [comment]
I have synced my branch with upstream and then merged 32b8853
Tests are OK now.
I have pushed the changes to my branch.

I hope this is what you have asked for. I am not familiar with the workflow yet, tried to follow github guide for syncing with upstream.

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Beautiful, thank you for your contribution 👍

**Pull request merged**
