### PR TITLE
Move plugin scores cache file to the docs repo

### PR DESCRIPTION
**Pull request by revolter**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by janpio** [comment]
What's the motivation behind this?

**Comment by revolter** [comment]
Updating the docs is done from the _fastlane_ repo, while the changes are commited and pushed to the docs repo, but if any plugin was changed, this file remained in the _fastlane_ repo and a PR was needed only to update this cache file. With this, the cache file is commited and pushed along with the generated docs file in the automatic PR.

**Comment by revolter** [comment]
It also makes more sense to be there.

**Comment by revolter** [comment]
@janpio, Was I clear enough?

**Review by janpio — APPROVED** [review]
Yep.

**Pull request merged**
