### PR TITLE
[action] add is_key_content_base64 to app_store_connect_api_key to make easier for env and CI

### LINKED ISSUE #17340: app_store_connect_api_key doesn't work with key_content
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When trying to create an `app_store_connect_api_key` using `key_content` `upload_to_testflight` will result in an error.
However, providing the key with `key_filepath` does work.

##### Command executed
```
app_store_connect_api_key(
  in_house: true
)
```
The rest is set with ENV VARS

##### Complete output when running fastlane, including the stack trace and command used
```
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `initialize': [!] invalid curve name (OpenSSL::PKey::ECError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `new'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/spaceship/lib/spaceship/connect_api/token.rb:57:in `create'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:33:in `api_token'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:20:in `login'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/manager.rb:16:in `start'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:28:in `block (2 levels) in parsing_binding'

##[error]Bash exited with code '1'.
Finishing: Run Fastlane Deploy
```

<details>
  <pre> I've tried providing the key with and without line breaks but still it didn't seem to make a difference</pre>
</details>

### Environment

<details>
  <pre> I don't have this, it's running on Azure DevOps</pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #17340

### Description
- Added option for `is_key_content_base64` to `app_store_connect_api_key`
- Will expect `key_content` to be base64 encoded and attempt to decode
- This was designed for ENV and CI usage

#### Using `app_store_connect_api_key` with options

```rb
lane :thing do
  app_store_connect_api_key(
    key_id: “D4943029”,
    issuer_id: “23j8932-f32f23f-23f2dsfa-23r32f”,
    key_content: “b21nIGltIGp1c3QgbWFraW5nIHRoaXMgdXAgbG9sIGkgbG92ZSBmYXN0bGFuZQ==”,
    is_key_content_base64: true
  )

  cert
  sigh
  pilot
end
```

#### Using `app_store_connect_api_key` with ENV

```env
APP_STORE_CONNECT_API_KEY_KEY_ID=D4943029
APP_STORE_CONNECT_API_KEY_ISSUER_ID=23j8932-f32f23f-23f2dsfa-23r32f
APP_STORE_CONNECT_API_KEY_KEY=b21nIGltIGp1c3QgbWFraW5nIHRoaXMgdXAgbG9sIGkgbG92ZSBmYXN0bGFuZQ==
APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64=true
```

```rb
lane :thing do
  app_store_connect_api_key

  cert
  sigh
  pilot
end
```

#### Using JSON file format

```js

{
    "key_id": "D4943029",
    "issuer_id": "23j8932-f32f23f-23f2dsfa-23r32f”,
    "key": "b21nIGltIGp1c3QgbWFraW5nIHRoaXMgdXAgbG9sIGkgbG92ZSBmYXN0bGFuZQ==",
    "is_key_content_base64": true,
    "in_house": false
}

```

```rb
lane :thing do
  cert(api_key_path: “path/to/key.json”)
  sigh(api_key_path: “path/to/key.json”)
  pilot(api_key_path: “path/to/key.json”)
end
```

### CODE REVIEW

**Review by rogerluan — COMMENTED** [review]
Should this option be added to all the other places where we have `key_contents`? Namely e.g. deliver, match, etc

**Comment by minuscorp** [comment]
Maybe a simple helper that can be used across tools is more efficient than sitting the same solution in each tool. Thoughts?

**Comment by rogerluan** [comment]
I agree @minuscorp, how do you envision this being implemented? An action similar to `app_store_connect_api_key` that should be called before lanes?

**Comment by minuscorp** [comment]
I'd pass a lambda that evaluates the need of the base 64 encoding, maybe yeah, in some TunesConnect API extension accessible for all tools, or even as a part of fastlane core if this is not strictly related to iTunes.

**Comment by joshdholtz** [comment]
@rogerluan @minuscorp Updated this a bit!

The other tools don’t have their own `key_content` option. They have an `api_key` option (which takes the key created from the `app_store_connect_api_key` action or takes it from the JSON file format). My previous example worked fine for everybody but that used the `app_store_connect_api_key` option but it did not give the Base64 encoded option to the JSON file people. I updated this to move the Base64 decode into the `Spaceship::ConnectAPI::Token` so that both the action and JSON file format can handle use the Base64 encode option.

Because its handled with the `Spaceship::ConnectAPI::Token`, all the tools get access to the encoded option 😊

**Pull request merged**
