### PR TITLE
[Scan] Can add a custom Slack message

### PR DESCRIPTION
**Pull request by esteluk**
This possibly addresses issue #1945 and allows the user to specify a custom message to be associated with each test result. 

https://github.com/fastlane/fastlane/issues/1945

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks for your pull request. What is an example use case for this?

**Comment by KrauseFx** [comment]
Ready to be merged from my side 👍

**Comment by esteluk** [comment]
Sure. One project I'm working on has a pretty standard multi-branch CI configuration. When scan reports the test results through Slack it can be hard to see exactly which branch / commit etc. that set of results relates to. 

I'm sure there are other options to send messages in the lane, but it'd be nice to include this as a part of the Scan message.

**Comment by KrauseFx** [comment]
This is great, thanks for clarifying @esteluk 👍

**Comment by KrauseFx** [comment]
The new option will be available in the next release

**Pull request merged**
