### PR TITLE
[action] Fix latest testflight build number problems / expired build scenario

### PR DESCRIPTION
**Pull request by ramnac**
Fixed everything in this change. Also handled the expired build scenario too.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This change is required to solve the latest testflight build number issue. There could be many issues related to this item. I am referring only one here.
 https://github.com/fastlane/fastlane/issues/14606

### Description
Instead of sorting it by uploaddate - as it wont work anymore, I am fetching all the builds response from Appstoreconnect API and fetching the max across the responses - to always get the latest testflight build number. First doing it with non-expired builds and then doing it with expired builds if there is no non-expired builds. This will solve all edge cases too.

 I tested it with my own account with an existing app - new version, existing version, by passing without any version. same test case repeated for the new app.

### CODE REVIEW

**Comment by ramnac** [comment]
I signed it!

**Comment by ramnac** [comment]
I signed it!

**Comment by ramnac** [comment]
I signed it!!

**Review by joshdholtz — APPROVED** [review]
@ramnac Thanks for the time spent on discussing on this issue and making this change ❤️ I added on commit to change the `UI.user_error!` message but besides that this changes made sense 💯 Thanks again!

**Comment by ramnac** [comment]
Thank you @joshdholtz

**Pull request merged**
