### PR TITLE
Allow snapshot to set the derived data path

### PR DESCRIPTION
**Pull request by st3fan**
**This is my first Fastlane/Snapshot contribution, it would be great if someone could verify/test this code before it is merged. I'm happy to address nits and suggestions for changes.**

This patch adds a `:derived_data_path` option to _Snapshot_. This is useful if you want to do multiple runs of _Snapshot_ on the same unchanged code base.

Using this option prevents _Snapshot_ from creating and deleting a temporary _Derived Data_ directory, which currently results in a full project recompilation when you do multiple runs.

This does mean that when you use the `:derived_data_path` option, you are in charge of managing (deleting) this directory.

For [Firefox for iOS](https://github.com/mozilla/firefox-ios) we execute _Snapshot_ once for every locale we have, because that lets us better manage the large amount of screenshots generated. With this patch and a more persistent _Derived Data_ directory, we save about _4.5 hours_ on the whole process. (We have 58 locales which result in almost 6000 screenshots)

Mandatory emoji :fist:

### CODE REVIEW

**Comment by i2amsam** [comment]
4.5 hours! :open_mouth: This is a great change!  One suggestion, what about adding an action to clear the `derived_data_path` so you can ensure a clean directory at the beginning?

**Comment by st3fan** [comment]
@i2amsam Sounds good. When you say action, do you mean a command like:

https://github.com/fastlane/fastlane/blob/master/snapshot/bin/snapshot#L62

**Comment by i2amsam** [comment]
@st3fan yes, exactly!

**Comment by emarley** [comment]
This would help me a bunch too. A clean build can take 15 minutes, and if I'm debugging screenshot stuff, that's 15 minutes over and over throughout my day.

**Comment by st3fan** [comment]
@i2amsam I added a `snapshot clear_derived_data` command. But not entirely sure if this is the right way to do it. Appreciate some guidance.

**Comment by i2amsam** [comment]
@st3fan awesome!  I made a couple tweaks and added tests in #3799, so I'm going to merge that one and close this. :+1: :rocket:

**Comment by st3fan** [comment]
@i2amsam Thank you!

**Comment by i2amsam** [comment]
:+1: Thank you @st3fan this is now shipped!  https://twitter.com/FastlaneTools/status/710562260125671425

**Comment by namanhams** [comment]
This is awesome !

**Pull request closed without merging**
