### PR TITLE
Fix `match nuke` for distribution

### PR DESCRIPTION
**Pull request by KrauseFx**
Fixes https://github.com/fastlane/fastlane/issues/8113

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]

**Comment by DanToml** [comment]
We should also add a test for this, but merge now to get it into the release

**Comment by KrauseFx** [comment]
Absolutely. _match_ is a bad fastlane citizen and has almost no tests compared to the other tools unfortunately 😢

**Comment by lacostej** [comment]
@KrauseFx sorry about that regression. Another thing that is rather confusing in match is that there are plenty of methods to convert from on type to another and all the inputs are strings, or sometimes symbols. Hard to know what the potential inputs are and test all cases. That's also why I wanted those conversion methods to be more explicits.

**Comment by KrauseFx** [comment]
@lacostej I agree, it's not ideal

**Comment by lacostej** [comment]
@KrauseFx the good thing is that with the new code pattern, there's no implicit conversion and the issue is very easily identified and fixed. You avoid having issues like the one where nuking enterprise would nuke development certificates. This is a code pattern we should follow more.

**Comment by KrauseFx** [comment]
@lacostej what code pattern do you mean?

**Pull request merged**
