### PR TITLE
[testfairy] Add 'testers_groups' option to 'testfairy' action

### PR DESCRIPTION
**Pull request by farshadtx**
- Change testers_group type to array
- Add optional parameters test
- Add short option value

Issue: [#4212](https://github.com/fastlane/fastlane/issues/4212)

Signed-off-by: Joe Greubel jgreubel@pivotal.io

### CODE REVIEW

**Comment by farshadtx** [comment]
This is a replacement/fix pull request to [https://github.com/fastlane/fastlane/pull/4210](url).

please close other pull request.

**Comment by KrauseFx** [comment]
Looks good from my side, @mfurtak ready to merge whenever you say it's okay 👍

**Comment by mfurtak** [comment]
Thanks folks, this is great! 👍

**Comment by Jgreub** [comment]
Woohoo!

**Comment by farshadtx** [comment]
Awesome !

**Pull request merged**
