### PR TITLE
[screenscrab] use AdbHelper instead of duplicated code

### PR DESCRIPTION
**Pull request by janpio**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
https://github.com/fastlane/fastlane/pull/12318 included 2 changes, I extracted this one to make it easier to follow the other changes:

### Description

> - screengrab now uses AdbHelper.load_devices to query devices (removed custom logic it was using)

### CODE REVIEW

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
@janpio Sorry about just getting to this now! This is 🔥 I did rebase from master since there was a PR that was also merged for `adb_host` so my latest commit on this adds support that for. Lemme know what you think when you get a chance 😊

**Comment by joshdholtz** [comment]
CircleCI isn't running so going to close and re-open

**Comment by janpio** [comment]
Yep, still looks good!

**Pull request merged**
