### PR TITLE
Add note in SnapshotHelper.swift about increment the version number

### PR DESCRIPTION
**Pull request by KrauseFx**
- Add comment to file
- Enable it with danger too

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You modified <code>SnapshotHelper.swift</code>, make sure to update the version number at the bottom of the file to notify users about the new helper file.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You modified <code>SnapshotHelper.swift</code>, make sure to update the version number at the bottom of the file to notify users about the new helper file.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by KrauseFx** [comment]
Wohoo, best danger 👍

**Comment by KrauseFx** [comment]
Note: danger works just for people with commit access

**Review by mfurtak — APPROVED** [review]

**Pull request merged**
