### PR TITLE
Adds option to provide oclint path

### PR DESCRIPTION
**Pull request by ssmiech**
Implements #1399

### CODE REVIEW

**Comment by ohwutup** [comment]
Hey @ssmiech, this is really awesome, thanks for submitting the PR, would you mind just changing that check for the string's length to using `empty?` per the hound warning? And then if you could just squash up those two commits into one we will be good to go! :rocket:

**Comment by ssmiech** [comment]
I am happy to do that. Just to note that it was there when I started :) 
I'll be a good boyscout :) 

Also, what about the second part of my proposal ? (adding an oclint binary to fastlane so that no one needs to install it at all). Is that too much maybe?

**Comment by ohwutup** [comment]
Ah! Sorry about making you go back and forth, hound is sometimes not the smartest thing. Don't worry about changing that if its going to derail you from something else! :camel: 

About the second part of your proposal, sorry I missed that at first! I just took a look and this is the first I'm hearing of the 12 factor app, so I am definitely excited to learn more about that philosophy which seems great to not have dependencies on system-wide packages (I feel like this is one of the biggest problems in getting set up with a new code base). Right now I think we should leave out the binary inside of fastlane itself mostly because I agree, it might be a bit much, and it feels like following a dependency injection type pattern that you've created here fits the current model for using external tools really well!

**Comment by ssmiech** [comment]
Done

**Comment by ohwutup** [comment]
Thanks @ssmiech ! :rocket:

**Pull request merged**
