### PR TITLE
[pilot] Add support for using App Store Connect API keys for iTunes Transporter

### LINKED ISSUE #14244: Support API keys for iTMSTransporter
### Feature Request

As a result of [this conversation](https://github.com/fastlane/fastlane/issues/14239#issuecomment-463801382), it was brought up that using API keys for the transporter part of fastlane may be useful.

#### Motivation Behind Feature
Required 2FA by apple means that users have to once a month generate a session token to use for their CI. Fastlane provides a wrapper around transporter to upload builds to testflight, so you _should_ be able to use api keys with transporter to avoid that problem for this feature of fastlane.

### PR DESCRIPTION
**Pull request by UnsafePointer**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes https://github.com/fastlane/fastlane/issues/14244

### Description

This PR has the following changes:

* Adds api_issuer and api_key to the Appfile configuration.
* Adds api_issuer and api_key options to both Deliver and Pilot.
* Updates `FastlaneCore#ItunesTransporter` to support usage of the App Store Connect API keys.

### CODE REVIEW

**Comment by Ruenzuo** [comment]
This is missing updating the documentation with the new optional values, will get into that soon, possibly more test cases if you consider that the ones I'm adding are not enough.

**Comment by Ruenzuo** [comment]
It looks like the docs are autogenerated so I hope this [template](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/ActionDetails.md.erb#L42-L50) covers the additions of this PR.

**Comment by janpio** [comment]
Awesome PR @Ruenzuo 

I really like and dislike the reusing of `username` and `password` at the same time 🙈 

---

Hey @joshdholtz, does this interfere with how you are implementing the new Testflight API in any way? I know that is focusing on just replacing the endpoints and not switching over to API keys (yet), but maybe you have some feedback here?

**Comment by janpio** [comment]
Hm, these params seem to be only available on newer builds of iTMSTransporter. Looking at https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#apdA1aded1d2 this seems to have been added with version 1.12. We should probably add that to the description. What happens when you supply those params to an older version of iTMSTransporter?

**Comment by Ruenzuo** [comment]
Good catch! I guess the iTMSTransporter `1.12` version corresponds to Xcode `10.0` (September 2018 release), so just to be on the safe side we could restrict these new parameters to Xcode 10.

**Comment by Ruenzuo** [comment]
@janpio I added a check for the Xcode version to the validator in all the new option parameters.

**Review by janpio — APPROVED** [review]
Looks good to me.

@joshdholtz?

**Review by janpio — DISMISSED** [review]
Ugh, just saw the lint failure:

```
[14:24:13]: ▸ Offenses:
[14:24:13]: ▸ deliver/lib/deliver/options.rb:10:5: C: Metrics/PerceivedComplexity: Perceived complexity for available_options is too high. [19/18]
[14:24:13]: ▸ def self.available_options
[14:24:13]: ▸ ^^^
[14:24:13]: ▸ 1048 files inspected, 1 offense detected
```

What can we do about this @joshdholtz ?

**Comment by Ruenzuo** [comment]
@janpio following what we do in [supply/options.rb#L6](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L6) I disabled that rule.

**Review by janpio — APPROVED** [review]
Looking good.

(Unfortunately I don't have an API key to actually test it)

**Comment by adnacacio** [comment]
Hm so this PR was closed without being merged ? Any information as per when Connect API keys will be supported ?

**Comment by Ruenzuo** [comment]
@adnacacio I opened this PR a month ago and I received feedback slower than I received merge conflicts, so I won't bother trying to get this merged.

Feel free to take the code or the idea, open a new pull request and give it a try yourself.

**Comment by janpio** [comment]
Will recreate manually as new PR.

**Comment by joshdholtz** [comment]
@Ruenzuo My apologies on this! This one slipped through my field of vision a bit. Personal life has been real hectic lately - getting married in a week or so so I've been very split minded lately 😬 If you would like to reopen this I would gladly review it, test it, and get it merged by end of week ❤️

**Comment by janpio** [comment]
(Can't be reopened as base repo was deleted and there were merge conflicts. Will open a new PR with manually copied over changes and conflicts solved in a few minutes)

**Comment by joshdholtz** [comment]
@janpio I'd still like to gie @Ruenzuo a chance to open fork and recreate if they'd like 😇

**Comment by joshdholtz** [comment]
I would prefer to not take credit for this work and have @Ruenzuo get the commits merged in

**Comment by Ruenzuo** [comment]
@joshdholtz thank you for the chance.

@janpio you go ahead with your PR, I don't mind at all.

**Comment by janpio** [comment]
Ok, https://github.com/fastlane/fastlane/pull/14486 is ready.

**Comment by joshdholtz** [comment]
@Ruenzuo Sorry again about letting this slip through! I should have done a better job at balancing open source and life stuff 😔

**Pull request closed without merging**
