### PR TITLE
[fastlane] Version bump

### PR DESCRIPTION
**Pull request by KrauseFx**
- Updated and unified fastlane description
- update_fastlane is now only called on fastlane deployment
- Removed rake test command for all tools
- Update gradle action documentation for command and output printing controls
- make rubygems deploy happen before we push the release to github
- Add action Pod lib lint
- Make body of commit optional in jenkins changelog generation

### CODE REVIEW

**Comment by mfurtak** [comment]
We've started putting the output of `fastlane show_changelog` (from the tool's sub-directory) into the body of these version bump PRs as a way to show what has changed for the version bump. What do you think? Does that seem useful?

**Comment by mfurtak** [comment]
💎  ✨

**Comment by KrauseFx** [comment]
Absolutely, I'll update the PR 👍

**Comment by KrauseFx** [comment]
Updated 👍

**Pull request merged**
