### PR TITLE
A ruby based autocomplete. Supports imported Fastfile and .fastlane folders

### PR DESCRIPTION
**Pull request by lacostej**
Idea is that being ruby based, we can support the DSL more easily.

Right now it supports `import` action and .fastlane folders

### CODE REVIEW

**Comment by KrauseFx** [comment]
The issue I see is that it might be very slow if the user has a lot of old versions of fastlane installed and RubyGems takes a while to resolve the dependencies.

**Comment by mfurtak** [comment]
I could be wrong, but I don't think either `fastlane` or RubyGems is involved in running this script. It's just pure stand-alone Ruby, right?

**Comment by lacostej** [comment]
This script has no external dependencies and is installed locally. The bash shebang might trigger the rvm installed ruby, but as far as I understand, no dependency resolution.

**Comment by KrauseFx** [comment]
For simplicity reasons, I think we shouldn't use Ruby to do that, as it has to be really fast to be useful for auto-completion. I'll close the PR for now, however this is very interesting code, that might be useful in the future. 

Thanks for looking into this @lacostej 👍

**Pull request closed without merging**
