### PR TITLE
Workaround for https://github.com/fastlane/fastlane/issues/5163

### PR DESCRIPTION
**Pull request by IngmarStein**
This looks like a good workaround to me.

### CODE REVIEW

**Comment by Liquidsoul** [comment]
I've got the same issue, and this change fix the issue for me using Xcode 8 beta 4 👍 
I hope this will be approved and released soon 🚀

**Comment by KrauseFx** [comment]
Very interesting approach, definitely something we could try 👍

**Comment by wkoszek** [comment]
I'm hitting this problem in my project, but with `clean` added to this command, if I run it 10 times:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -showBuildSettings -workspace Sensorama.xcworkspace -scheme SensoramaTests
```

It still hangs sometimes.

**Comment by KrauseFx** [comment]
So it seems like this doesn't actually fix the issue 😢

**Comment by ohwutup** [comment]
Going to close this in favor of https://github.com/fastlane/fastlane/pull/5188

**Comment by IngmarStein** [comment]
This was supposed to fix #5163 (always hangs with Xcode 8), not #4059 (sometimes hangs with Xcode < 8).

**Comment by dulaccc** [comment]
I support with @IngmarStein, #5188 seems to have nothing to do with this "always hangs with Xcode 8".
I'm using [his fix](https://github.com/fastlane/fastlane/pull/5626/files#diff-c9f62f5f3751ea4d26844cf52c620706R208) and it's working very well for this particular issue

**Comment by IngmarStein** [comment]
@ohwutup the underlying bug hasn't been fixed in Xcode 8 Beta 6, but the @tokorom's fix still works.

**Comment by ianterrell** [comment]
@ohwutup Petitioning for reopening. :)

**Comment by jblack10101** [comment]
+1

**Comment by lyndsey-ferguson** [comment]
@IngmarStein thanks for sharing, will try it

**Comment by lyndsey-ferguson** [comment]
It worked the first 2 times and then failed (by hanging again)

**Comment by IngmarStein** [comment]
Interesting. With my Core Data based project, I can easily run `xcodebuild clean -showBuildSettings`many times without hang (e.g. `for f in {1..20}; do xcodebuild clean -showBuildSettings > /dev/null 2>&1; done`).
Without the `clean` parameter, `xcodebuild` from Xcode 8 always hangs.

**Comment by lyndsey-ferguson** [comment]
I have this running behind Jenkins, that may be the added variable.

**Comment by IngmarStein** [comment]
@lyndsey-ferguson is it possible that you're running into #4059 then? A combination of this PR and #5188 may be required for a complete fix.

**Comment by mfurtak** [comment]
@IngmarStein Thanks for investigating and putting this together 👍 

I'm going to take this as-is, but do a follow-up to put this behavior behind a feature switch so that people can opt-in to the change. ✅

**Comment by hotbott** [comment]
Seems to work in my projects and Xcode 7.3.1. Thanks.

**Comment by lyndsey-ferguson** [comment]
@IngmarStein the commit made by @fcy works for me. I put this in my Gemfile: 
`gem 'fastlane', :git => 'https://github.com/fcy/fastlane.git', :branch => 'fcy/fix-xcodebuild-show-settings'`

**Comment by mfurtak** [comment]
After talking with @KrauseFx, we decided not to put this workaround behind a feature switch. It'll go out live for everyone by default with the next release. 👍

**Comment by mfurtak** [comment]
@lyndsey-ferguson Thanks for chiming in with your test results. 👍  We'll work on merging a retry solution next!

**Comment by mfurtak** [comment]
Hi all, this has been released as part of [`fastlane_core` 0.51.0](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.51.0) 🚀 

The retry solution from #5188 is also a part of that release.

Thanks very much for your help! Please let us know how it looks 👍

**Comment by KrauseFx** [comment]
To test the latest release, please run `[sudo] gem update fastlane_core` or if you have a `Gemfile` `bundle update`. 

Please let us know if that fixes the issue for you, so we can push new releases for _gym_ and _scan_ 🚀

**Comment by mfurtak** [comment]
Hi all, [`gym` 1.9.0](https://github.com/fastlane/fastlane/releases/tag/gym/1.9.0) 💪 and [`scan` 0.12.0](https://github.com/fastlane/fastlane/releases/tag/scan/0.12.0) 🔍 have been released to pick up these `fastlane_core` improvements.

To get updated and try them out, please run `[sudo] gem update gym scan` :rocket:

**Comment by jacobjennings** [comment]
Doesn't this ignore the -clean parameter, and break incremental builds?

**Comment by KrauseFx** [comment]
@jacobjennings Could you submit a new issue for this? 👍

**Pull request merged**
