### PR TITLE
[cert] Print a better error message when user is not Team Admin

### LINKED ISSUE #8325: Better errors for cert run with insufficient access
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane cert` with a user who is a Team Member and not a Team Admin produces an insufficiently helpful message.

#### *Reproduction steps:*

1. Create a user on an Apple Developer account with "Team Member" privileges
2. Attempt to create a distribution certificate by running `bundle exec fastlane cert` with that user

#### *Expected behavior:*

I expect a friendly error suggesting that I need to login as a Team Admin. For example:

> ⛔ This account is a Team Member, but only Team Admins can create distribution certificates.
>
> 🔎 See https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html to learn about the differences and for instructions on changing accounts.

#### *Actual behavior:*

I receive this insufficiently helpful error message:

> You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support.
https://developer.apple.com/support

##### Complete output when running fastlane

```
$ bundle exec fastlane cert -u "[REDACTED]"

+---------------+----------------------------------------------------+
|                      Summary for cert 2.18.0                       |
+---------------+----------------------------------------------------+
| username      | [REDACTED]                 |
| development   | false                                              |
| force         | false                                              |
| team_id       | [REDACTED]                                         |
| keychain_path | /Users/abrager/Library/Keychains/login.keychain-db |
| platform      | ios                                                |
+---------------+----------------------------------------------------+

[13:23:29]: Starting login with user '[REDACTED]'
[13:23:44]: Successfully logged in
[13:23:45]: Couldn't find an existing certificate... creating a new one

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] Apple provided the following error info:
	You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support.
https://developer.apple.com/support
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.2                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    ensure_git_status_clean
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # your Apple ID user
    cert(username: "[REDACTED]") 
    sigh
    gym
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "[REDACTED]"
team_id "[REDACTED]"

for_lane :beta do
  team_id "[REDACTED]"
  app_identifier "[REDACTED]"
end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| tty-screen                | 0.5.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| faraday-cookie_jar        | 0.0.6   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| json                      | 2.0.3   |
| commander                 | 4.4.3   |
| io-console                | 0.4.5   |
| excon                     | 0.55.0  |
| rubyzip                   | 1.2.1   |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| bundler                   | 1.14.3  |
| terminal-table            | 1.7.3   |
| unicode-display_width     | 1.1.3   |
</details>

*generated on:* **2017-02-21**
</details>

### PR DESCRIPTION
**Pull request by ohayon**
This fixes https://github.com/fastlane/fastlane/issues/8325

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Spaceship::Client authenticated #provisioning_profiles_via_xcode_api makes a call to the developer portal API | <a href='https://github.com/fastlane/fastlane/blob/4a0d57b284c19ba3381f9b8c8166073f971f9bc6/./spaceship/spec/portal/portal_client_spec.rb'>portal_client_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Spaceship::Client authenticated #provisioning_profiles_via_xcode_api makes a call to the developer portal API | <a href='https://github.com/fastlane/fastlane/blob/4a0d57b284c19ba3381f9b8c8166073f971f9bc6/./spaceship/spec/portal/portal_client_spec.rb'>portal_client_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ohayon** [comment]
🤔 This test is failing locally (on this branch *and* on master) with:
```
NoMethodError:
       undefined method `provisioning_profiles_via_xcode_api' for #<Spaceship::PortalClient:0x007fc397f38290>
       Did you mean?  provisioning_profiles
     # ./spaceship/spec/portal/portal_client_spec.rb:218:in `block (4 levels) in <top (required)>'
```

And on CI it is failing with:
```
Failure/Error:
       expect(profiles.sample.keys).to include("provisioningProfileId",
                                               "name",
                                               "status",
                                               "type",
                                               "distributionMethod",
                                               "proProPlatform",
                                               "version",
                                               "dateExpire",
                                               "managingApp",
                                               "deviceIds",

       expected ["provisioningProfileId", "name", "status", "type", "distributionMethod", "proProPlatform", "UUID", "..."certificates", "certificateIds", "isTemplateProfile", "isTeamProfile", "isFreeProvisioningProfile"] to include "managingApp"
     # ./spaceship/spec/portal/portal_client_spec.rb:220:in `block (4 levels) in <top (required)>'
```

**Review by KrauseFx — APPROVED** [review]
That's a great change 👍

**Comment by mfurtak** [comment]
@ohayon I think the CI problem has been resolved, so rebasing this PR on master should fix things 👍

**Comment by getaaron** [comment]
👍🏼

**Pull request merged**
