### PR TITLE
[Fastlane.swift] generate documentation

### PR DESCRIPTION
**Pull request by iMacHumphries**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The goal of this PR is to make it easier for developers to use Fastlane swift by providing documentation for functions and protocol variables. The docs will also appear in Xcode Quick Help: 
Screen Shot 2019-09-07 at 1 04 58 PM
Screen Shot 2019-09-07 at 12 57 04 PM

### Description
This PR updates the `swift_fastlane_api_generator` to pass Action documentation attributes into `Fastlane::SwiftFunction` to be used for generating Swift documentation. The documentation is added to the `swift_code` method. This PR also adds unit tests for the new documentation functions.

### Testing Steps
To run new unit tests:
`bundle exec rspec ./fastlane/spec/swift_fastlane_function_spec.rb`

### CODE REVIEW

**Comment by iMacHumphries** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
Oh wow, this is pretty awesome!

**Comment by taquitos** [comment]
This is amazing!

**Review by joshdholtz — APPROVED** [review]
This is soooooooo good! This legit makes me want to start writing my fastlane things in Swift now 🙃 I rebased this from latest master due to some merge conflicts with new actions/options being added but can't wait to get this out in the next version of _fastlane_ 🙌

**Pull request merged**
