### PR TITLE
Update available plugins

### PR DESCRIPTION
**Pull request by vmalyi**
"localization" has been added to the list of available plugins.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @vmalyi, thanks for your pull request and building a fastlane plugin. Please update the `AvailablePlugins.md` using the rake task [rake generate_plugins](https://github.com/fastlane/fastlane/blob/master/fastlane/Rakefile#L11-L14). I can take this over if you want 👍 

I noticed some smaller things in your plugin:
- https://github.com/vmalyi/fastlane-plugin-localization/blob/master/lib/fastlane/plugin/localization/actions/export_localizations_action.rb#L37 you can remove this line
- https://github.com/vmalyi/fastlane-plugin-localization/blob/master/lib/fastlane/plugin/localization/actions/export_localizations_action.rb#L18 This should be your username
- https://github.com/vmalyi/fastlane-plugin-localization#about-localization The documentation is not 100% complete yet

Thanks again for all your hard work 👍 🚀

**Comment by vmalyi** [comment]
Hi @KrauseFx,

thank you for the feedback! 

I fixed the issues you've listed in https://github.com/vmalyi/fastlane-plugin-localization/commit/56330b910af3df7b24fffd7c3e4e75dc779a953e.

When I run, however, `rake generate_plugins` I get "localization" plugin not listed in AvailablePlugins.md.

Am I missing something?

Thanks!

**Comment by KrauseFx** [comment]
I pushed https://github.com/fastlane/fastlane/pull/5560/files 🚀 Thanks again 👍

**Comment by vmalyi** [comment]
Thanks Felix! 

PS: do you see any reason why my plugin is still not listed in https://github.com/fastlane/fastlane/pull/5560/files?

It was release using normal process described at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md and seems to contain all correct metadata.

Thank you!

**Comment by KrauseFx** [comment]
Thanks for this - I could reproduce the bug of fastlane not being able to find the plugin and will push a fix

**Pull request closed without merging**
